### ISSUE TITLE
Stop drag mid-drag

### ISSUE THREAD

**Issue by mikkmartin** [wbkd/react-flow#1000]
I have an interaction (long press) that needs to cancel the drag and fire another event after x milliseconds, figured  I just fire`actions.setNodesDraggable(false)` and set to true afterwards, but it doesen't seem to work mid drag. Any way to implement this?

**Comment by moklick** [comment]
Could you create a simplified codesandbox or repo so that we better understand the issue?

**Comment by mikkmartin** [comment]
👆

**Comment by MatthieuJnon** [comment]
Have you found a solution? I'm encountering the same issue

**Comment by chrtze** [comment]
Hey @mikkmartin, have you already updated to React Flow version 10? The updates includes changes in the event handling as well, so I would be interested to know if this issue still persists. Thanks!

**Comment by moklick** [comment]
Please re-open if the issue still persists.
