### ISSUE TITLE
selectionKeyCode to null?

### ISSUE THREAD

**Issue by mikkmartin** [wbkd/react-flow#1001]
I want to implement box-selection without pressing additional keys. There doesen't seem to be away to start box selection without any meta/additional key. `selectionKeyCode={null}` or `selectionKeyCode="none"` would be nice.

**Comment by moklick** [comment]
So in this case mouse is only used for drawing selections?

**Comment by mikkmartin** [comment]
Yes, panning is done with scroll events like the UX with Facebook Origami

**Comment by moklick** [comment]
Ok, this is not possible at the moment. We will see how we can make this possible.

**Comment by moklick** [comment]
in v10 you will be able to pass `null` in order to remove the handler.

**Comment by tajammul1996** [comment]
@moklick  - In v10, with selectionKeyCode={null}, is it possible to do a selection on drag without using any keypress?

**Comment by moklick** [comment]
@tajammul1996 nope. I'll think about it..

**Comment by tajammul1996** [comment]
Thank you @moklick
