### ISSUE TITLE
multiple values for multiSelectionKeyCode

### ISSUE THREAD

**Issue by mikkmartin** [wbkd/react-flow#1002]
I want to be able to both use Shift and Cmd for multi-selection. Something like `multiSelectionKeyCode([19, 62])` would be nice. Any other way to implement it?

**Comment by moklick** [comment]
This is not possible with the current version. We will put it on our list.

**Comment by moklick** [comment]
Can be tested on the [refactor/keys branch](https://github.com/wbkd/react-flow/tree/refactor/keys). Unfortunately this is an ABC and will only be available in the next major release v10.
