### ISSUE TITLE
How to map mouse event (x,y) to node position?

### ISSUE THREAD

**Issue by evgenius1424** [wbkd/react-flow#1004]
Hi. Sorry for asking the questions here instead of SO. 

But could you please guide me how to map current mouse event position to target node position.

My motivation is that I want to add new node at the middle of the current pane (or dnd it).

I can zoom in/out, I can move pane but still want to add new element to the center.

Can you share example or code pointer?

**Comment by moklick** [comment]
In [this example](https://github.com/wbkd/react-flow/blob/main/example/src/Undirectional/index.tsx#L57-L67) we are adding a node on click. You can use the `project` function of the `useZoomPanHelpers` to calculate the position https://reactflow.dev/docs/api/hooks/

**Comment by evgenius1424** [comment]
Yes. It is exactly what I need. Missed it at docs. Thank you so much.
