### ISSUE TITLE
Use without z-index?

### ISSUE THREAD

**Issue by AdrianLsk** [wbkd/react-flow#1005]
Hi, I am looking into migrating my diagramming application to react-flow.

But I am having trouble integrating it because of the z-indices.
I am using [base web](https://baseweb.design/) framework for my components and eg. drawers, modals and select dropdowns become unclickable.

Brute-force strategy of rewriting all components in my application seems too much work, so I am thinking of how to do it efficiently.

Do you have any recommendations on how to use react-flow without z-indices or an easier idea of how to do it?

**Comment by moklick** [comment]
What is your issue with the z-indices here? Everything with z-index > 4 gets drawn on top of react-flow (edges are z-index=2, nodes are z-index=3).

**Comment by AdrianLsk** [comment]
Thanks for the information.

Base web framework uses react focus lock for locking modals, drawers and popovers plus treats z-index in a bit too complicated fashion to my taste. As explained here https://baseweb.design/components/layer.

Their components (drawer, select popovers and modals) become numb/unclickable due to the z-indices from react-flow. And even if I set their z-indices it's still doesn't work for every component. 

Since I am not an expert on this, I am a bit lost.

**Comment by moklick** [comment]
z-index=5 + position=absolute should display components on top of react flow. You can create a simplified codesandbox if the issue persists.
