### ISSUE TITLE
Question about userSelection

### ISSUE THREAD

**Issue by Alan-Fisher** [wbkd/react-flow#1006]
Hey!
First of, thanks for this amazing package, I really enjoy it!

Now I'm trying manually set user selection (blue rectangle) because it's easy to work with it to get new positions of dragged nodes.
I only found an option to setSelectedNodes (which is great, but for other cases)
It doesn't fit in this case because when we move selected nodes (e.g. selected by ctrl + click, without blue rectangle) only onNodeDrag fires. And It has updated position for only one node so we have to calculate others

1. How can I manually set user selection to trigger onSelectionDrag?
2. Or how can I easily get new positions of all selected moved nodes?

Thanks!

**Comment by moklick** [comment]
We need to polish the whole selection logic I guess. You are not the only one who is struggling with the current implementation. It would be helpful if the drag handlers would return all nodes that got dragged (if there is a multi selection).

**Comment by Alan-Fisher** [comment]
> We need to polish the whole selection logic I guess. You are not the only one who is struggling with the current implementation. It would be helpful if the drag handlers would return all nodes that got dragged (if there is a multi selection).

Yeah, just as I thought :)
No worries, current handlers are fairly complete! Will be waiting for updates

So what will be my best options to get positions of all dragged nodes?
Or can I manually set blue rectangular to some elements?

**Comment by clement-faure** [comment]
Hey, 

I'm also trying to set user selection (blue rectangle) by passing Box coordinates programmatically, when clicking on a specific Button for exemple. But the ReactFlow provider does not seems to expose such function.

Thanks!

**Comment by clement-faure** [comment]
I finally ended up by handling this on my own using `onNodeDragStop` method. 
I'm updating position of all children nodes within my container.

**Comment by Alan-Fisher** [comment]
> updating position of all children nodes within my container.

@clement-faure how exactly? :)

**Comment by clement-faure** [comment]
> > updating position of all children nodes within my container.
> 
> @clement-faure how exactly? :)

Hello @Alan-Fisher, sorry for the delay !

I'm generating a real-time tree of my react-flow view. I'm using this tree to know exactly all "nodes" within a specific container.

Using this information, when updating the container position, i'm calculating a deltaX and deltaY and applying this delta to all children to move them in the view.

Have a nice day !

**Comment by Alan-Fisher** [comment]
@clement-faure I do it this way too :)

**Comment by moklick** [comment]
We are working on a next release https://github.com/wbkd/react-flow/pull/2152. We dropped react-draggable and rewrote the dragging logic. We are now passing a third parameter nodes to `onNodeDragStart`, `onNodeDrag` and `onNodeDragStop` that includes all selected nodes. You can check out the next version with `npm install react-flow-renderer@next`.
