### ISSUE TITLE
props nodeTypes not extandable

### ISSUE THREAD

**Issue by monikabadertscher** [wbkd/react-flow#1007]
Hello
I am building a react application, where I need to define nodeTypes dynamically, according to data I receive from a server. Before rerendering I add new types to object nodeType. I see, that my programmatically created nodeType object is exactly the same as my statically created one. All the same, new types are not recognized in react-flow. Is it true, that the props nodeTypes is immutable after the first call of ReactFlow, so that you need to create all types in the beginning? 
Is there a way to change that myself in the react-flow code? 
Thank you very much for your answer.
Moka Badertscher

**Comment by moklick** [comment]
Hey @monikabadertscher 

the `nodeTypes` and `edgeTypes` props are static:

https://github.com/wbkd/react-flow/blob/main/src/container/ReactFlow/index.tsx#L188-L189

Maybe we could pass another prop like `nodeTypesId` to the `useMemo` deps array in order to recalculate the types.

**Comment by monikabadertscher** [comment]
Thank you very much. So do you mean, you could provide me those extension with a nodeTypesId? If you could, it would make my life so more easier for my project! 
Greetings, Moka

**Comment by moklick** [comment]
Do you get new nodes and the regarding types from the server or do you just want to update the types?

**Comment by monikabadertscher** [comment]
Hy Moritz
I am really grateful that you consider my request!

The situation is this:
I have a graph with up to ten nodes or so. When I create a new node, the type depends on the number of handles and where they are positioned (besides image, text and so on.) This information is from imported data (from the server) and I add the specific info for this node to node.data.
As I have to be highly dynamically (there could always coming a complete new set of data for the import), I cannot predefine the different type of nodes.

My goal is, to dynamically create the type "nodeTypes". I already have a function, which returns a correct value React.memo() which I manipulate with the individual info for handles from my node. So, my "dream-solution" would be to create the "nodeTypes" each time before I render. I already implemented this. That means, nodeTypes can have new entries each time I send the prop.

Of course I take any solution you can provide me. But the core point is, that I cannot have predefined memos for every type I need.

Thank you so much to consider my problem and have a nice day!
Moka


Von: Moritz Klack ***@***.***>
Gesendet: Wednesday, March 17, 2021 10:06 PM
An: wbkd/react-flow ***@***.***>
Cc: Monika Badertscher ***@***.***>; Mention ***@***.***>
Betreff: Re: [wbkd/react-flow] props nodeTypes not extandable (#1007)


Do you get new nodes and the regarding types from the server or do you just want to update the types?

**Comment by monikabadertscher** [comment]
Hy Moritz
And: Yes I need to change the type.

Best regards, Moka

Von: Moritz Klack ***@***.***>
Gesendet: Wednesday, March 17, 2021 10:06 PM
An: wbkd/react-flow ***@***.***>
Cc: Monika Badertscher ***@***.***>; Mention ***@***.***>
Betreff: Re: [wbkd/react-flow] props nodeTypes not extandable (#1007)


Do you get new nodes and the regarding types from the server or do you just want to update the types?

**Comment by moklick** [comment]
In v9.3.0 you can pass a `nodeTypesId` and a `edgeTypesId` if you want to update the node or edge types. Please let me know if it works for you.

**Comment by monikabadertscher** [comment]
Hello Moritz
Thank you very much. I will try that tomorrow evening or Tuesday morning. Tomorrow I have to make a presentation and for this purpose I can use it as it is. This is a very simple first step.
I am looking forward to testing and will let you know.
Best regards, Moka

Von: Moritz Klack ***@***.***>
Gesendet: Friday, March 19, 2021 11:53 PM
An: wbkd/react-flow ***@***.***>
Cc: Monika Badertscher ***@***.***>; Mention ***@***.***>
Betreff: Re: [wbkd/react-flow] props nodeTypes not extandable (#1007)


In v9.3.0 you can pass a nodeTypesId and a edgeTypesId if you want to update the node or edge types. Please let me know if it works for you.

**Comment by monikabadertscher** [comment]
Thank you for this extension.
As I had to deliver a first version on time I found a quite good solution with a bunch of predefined nodeTypes and more configuration data from my server-application. When things get soon more grouped and complex, I will change to your new solution.
I tested it and it worked well. I hope the provided solution 9.3.0 will stay there.

**Comment by moklick** [comment]
Great that it works :)

**Comment by Alexey-Koren** [comment]
@moklick Hi. II got the same problem. I need to dynamically render nodeTypes. Is now u support any method for this?
