### ISSUE TITLE
onEdgeMouse[Move/Enter/Leave] event handlers not recognized

### ISSUE THREAD

**Issue by andrew-1135** [wbkd/react-flow#1012]
Attempting to use these [event handlers](https://reactflow.dev/docs/api/component-props/) with `<ReactFlow />` causes an error: ``Warning: Unknown event handler property `onEdgeMouse[Move/Enter/Leave]`. It will be ignored.``

**Comment by moklick** [comment]
are you using the latest version v9.2.0?

**Comment by andrew-1135** [comment]
Thanks for the response, updated and everything working as expected. Definitely did not expect releases to be coming out at the rate they are.

**Comment by moklick** [comment]
Unfortunately we only have docs for the latest version.
