### ISSUE TITLE
Make background image pan

### ISSUE THREAD

**Issue by TamjidTayeb** [wbkd/react-flow#1013]
Hello,

At the moment if I add a background to my react flow background like so:
```
<Background
          color='#fff'
          gap={16}
          style = { { backgroundImage: 'url(myImage.png)'}}
/>
```
The background stays fixed while i pan the canvas. Is it possible to make the background image move with the panning of the canvas?

Example image bellow:

Before panning:
![image](https://user-images.githubusercontent.com/38994890/111565166-06720000-87ef-11eb-9cc6-0b4dd3d01d14.png)

After panning canvas to the right:
![image](https://user-images.githubusercontent.com/38994890/111565198-17227600-87ef-11eb-9a53-d9eb09c7477c.png)

**Comment by moklick** [comment]
What exactly are you trying to do here? What is your use case? There might be another way rather than adding an image to the background. The background it self doesn't move but we calculate the positions of the dots. That's why your image doesn't move here.

**Comment by TamjidTayeb** [comment]
I want to allow my users to upload an image that sits on the canvas below the grid dots and graph nodes so that each graph nodes can be visualized in relation to the background image. For example a car as a background image and the graph nodes to represent the different components of the car by being positioned where those components would be in the image (engine, wheel, exhaust etc). Thus I need my users to be able to pan and zoom and the image and graph nodes and grid dots to stay in the same position relative to each other. Is this possible?

**Comment by moklick** [comment]
You could add an inactive node (draggable:false,selectable:false,connectable:false,maybe some extra css with pointer-events:none) that only has an image as content without handles.

**Comment by TamjidTayeb** [comment]
thanks for the suggestion, is it possible to make that node sit behind the grid dots?

**Comment by moklick** [comment]
No this is not possible. All nodes would be behind the background if you change the z-indices.
