### ISSUE TITLE
Issue with Yarn 2 and strict module checking 

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#1015]
After upgrading to yarn 2, I'm getting the following compile-time error while trying to start a create-react-app application:

Module not found: react-flow-renderer tried to access react-dom, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

I believe this is because yarn 2 only gives access to what's required as a dependency or peer dependency. I'm not sure if this would work, but adding react-dom as a peer dependency might help here.

**Comment by moklick** [comment]
This is weird. React Flow doesn't need react-dom. But thanks for the hint. We will check it.

**Comment by moklick** [comment]
Can you check v9.3.0?

**Comment by wdfinch** [comment]
Just checked. Seems to be working fine now. Thanks for the quick patch @moklick.

**Comment by wdfinch** [comment]
Just had a relook at this and it seems there are also issues with the type declaration files for **react-redux** and **d3**.

The error looks like this:

.yarn/$$virtual/react-flow-renderer-virtual-1f7b0210b1/0/cache/react-flow-renderer-npm-9.3.0-185ae10f59-07abdc5493.zip/node_modules/react-flow-renderer/dist/types/index.d.ts(2,56): error TS2307: Cannot find module 'd3' or its corresponding type declarations.

I think the issue is these types are referenced by the package, however, they are listed as dev dependencies and therefore are not present in the version that is installed from npm. Therefore, when types are imported via you .d.ts files, yarn 2 will throw an error as it cannot find these type def files. Not sure how would want to fix this. My solution is to add 

```
packageExtensions:
  "react-flow-renderer@*":
    dependencies:
      "@types/react-redux": "*"
      "@types/d3": "*"
```

to my .yarnrc.yml file and therefore add them in as dependencies.

**Comment by moklick** [comment]
Thanks. Can you check v9.4.0?

**Comment by wdfinch** [comment]
Looks good now. Thanks!

**Comment by poicooler** [comment]
I think this commit 51a1fd57fb6c7c76ff90d190f0d3d909db3da938 broke this fix.

**Comment by richxcame** [comment]
> I think this commit [51a1fd5](https://github.com/wbkd/react-flow/commit/51a1fd57fb6c7c76ff90d190f0d3d909db3da938) broke this fix.

I agree with you. I have same problem!

**Comment by moklick** [comment]
I am not able to reproduce this. My steps are:

* `yarn create react-app my-app`
* `cd my-app`
* `yarn add react-flow-renderer`
* `yarn start`

**Comment by moklick** [comment]
added to `dependencies` in v10.3.15
