### ISSUE TITLE
Unknown event handler property `onNodeDoubleClick`

### ISSUE THREAD

**Issue by timijk** [wbkd/react-flow#1016]
Hi,

I'm trying to register a handler for the ```onNodeDoubleClick``` event but am getting the following error in the browser console:

![image](https://user-images.githubusercontent.com/79575215/111874325-a44f0180-898c-11eb-85bf-7385b1cc1f98.png)

Switching the event out for another (such as ```onNodeContextMenu``` or ```onNodeMouseMove```) the problem goes away and those events fire fine. After assuming it was my code (I'm using custom node types) I tried the same in the 'UpdatableEdge' demo from the website and have the same issue.

So this doesn't work:
```javascript
  <ReactFlow onNodeDoubleClick={handler} elements={elements} />
```
but this does:
```javascript
  <ReactFlow onNodeContextMenu={handler} elements={elements} />
```

I had a skim over the code but couldn't see anything obvious as to why this would be.

**Comment by moklick** [comment]
Are you using the latest version v9.3.0?

**Comment by timijk** [comment]
Yes, sorry, forgot to mention that I had the problem initially on v9.2.0 but checked and upgraded to v9.3.0 and still had the problem.

I'm running it in essentially a bare create-react-app as I'm just prototyping something at the moment. Node version is v14.16.0.

**Comment by timijk** [comment]
I've spun up a completely new create-react-app installing v9.3.0 from the start and copied code over from the other project, in the new project everything works. Can't tell what the difference between them is but obviously this is not a react-flow-renderer issue.

I'm not going to spend too much time comparing the projects to figure out what the issue is as there's so little code there I'm going to throw it out. However if I find anything relevant to the package I'll shout.

Sorry for false alarm and many thanks for creating this project.
