### ISSUE TITLE
Wrong elementBelow: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by adhammo** [wbkd/react-flow#1017]
Sometimes when I click on the edge of any **target** handle, it produces the following error: "Cannot read property 'find' of null".

![findofnull](https://user-images.githubusercontent.com/56611873/111881385-e4c47480-89b8-11eb-85ed-2095c5f520c3.png)

After some inspection I found out that somehow the **elementBelow** variable [here](https://github.com/wbkd/react-flow/blob/a5a96508968cb44ebdf172b402f5dd61f32eebc9/src/components/Handle/handler.ts#L101) returned from *document.elementFromPoint* is not a handle (the handle clicked = event.target) rather the div behind or *react-flow__pane*.

And because those div.'s don't have "target" in their class list, they get specified as sources. Thus, resulting in the error above after the action has been fulfilled.

![elementbelow](https://user-images.githubusercontent.com/56611873/111881443-07ef2400-89b9-11eb-9b77-20a437fb1d95.png)

Also, the same problem faced me before but resulted in no error just selecting the first "[0]" source handle, if existed, or the bottom center of the node.

I am wondering why aren't you checking the validity of the elementBelow before creating the action but only checking inside onMouseMove and onMouseUp [here](https://github.com/wbkd/react-flow/blob/a5a96508968cb44ebdf172b402f5dd61f32eebc9/src/components/Handle/handler.ts#L117).

**Comment by moklick** [comment]
Hey. Thanks for the report but I am not able to reproduce this. When does this happen? Does it have anything to do with `onEdgeUpdate`?

**Comment by adhammo** [comment]
I was able to produce it on your demo site as well.

![sitecrash](https://user-images.githubusercontent.com/56611873/111906695-7df79780-8a5a-11eb-831e-6328aa1e165a.png)

You need to click on the very edge of a target handle (preferably on a node that does only have one target handle and no source handles). you need to make DOM **onClick** event fire on the handle but **document.elementFromPoint** is not the handle itself. as I said it sometimes happens so keep trying xD.

Try clicking right here:

![where](https://user-images.githubusercontent.com/56611873/111906926-c2cffe00-8a5b-11eb-99cb-343108657843.png)

I am not sure what do you mean by `onEdgeUpdate`?

**Comment by moklick** [comment]
Thanks! I added that bug in one of the recents versions :/ Could you try 9.3.1?

**Comment by adhammo** [comment]
@moklick 
Yeah, it is working fine but updating edges no longer works. Can you please check that? I am not sure if it broke or it is something I did.

**Comment by moklick** [comment]
haha :D Thanks for the hint! We definitely need some time here to refactor the connection and edge updater handling. Should work with v9.3.2.
