### ISSUE TITLE
Unexpected behavior when dragging nodes after area selection 

### ISSUE THREAD

**Issue by awu43** [wbkd/react-flow#1032]
Observed in React Flow v9.3.2.

Expected behavior: all nodes move in sync like when individually dragged or dragged after selecting with multiple clicks.

What actually happens (the nodes become stuck to the mouse until another click):
![react-flow-sticky](https://user-images.githubusercontent.com/46470763/112217784-297e2480-8be0-11eb-9b0e-a83621189a2f.gif)

This can be avoided by first clicking on a node once and then dragging, but that's not intuitive at all.

**Comment by moklick** [comment]
Hey @andrew-1135 

sorry but I can't reproduce this. What browser are you using? Do you have any custom handlers that could be the reason for this behaviour? This is how it looks with the stress example:

https://user-images.githubusercontent.com/2857535/112281627-8f24ec00-8c86-11eb-8e28-a400e2c73fd5.mov

**Comment by adhammo** [comment]
I had the same problem two days ago but don't really remember what caused it and what solved it. it is working now though. Try updating the latest version.

**Comment by andrew-1135** [comment]
After some testing, the problem seems to be with Firefox since Chromium browsers worked as expected. Disabling handlers and `z-index` had no effect.

**Comment by moklick** [comment]
This is a strange bug. I can reproduce it with Firefox. When I use another `selectionKeyCode` like "a" for example the error doesn't occur anymore. Can you confirm this @andrew-1135? I think it has something to do with the "Shift" key.

**Comment by andrew-1135** [comment]
Confirmed, assigning `selectionKeyCode` to anything besides Shift fixes it. Very strange.

**Comment by Alexey-Koren** [comment]
@moklick Hi. I got this error too. Found that after selection nodes. Sometimes when you first time move them, can be toggled drop event.

![Screenshot from 2021-05-13 19-19-26](https://user-images.githubusercontent.com/36141306/118154903-4c7ac700-b420-11eb-9325-fd3c07b51029.png)

Changing of the selectionKeyCode fixing this.

**Comment by Alexey-Koren** [comment]
@moklick Hello. Found that it fixing not all. If you trying to move small selection without any items, drag event still exists. Did you had this bug before?

![Peek 2021-05-17 11-26](https://user-images.githubusercontent.com/36141306/118458406-6576c700-b703-11eb-8c1d-8e8fe2b92b8e.gif)

**Comment by Alexey-Koren** [comment]
@moklick Here this bug in examples
Firefox
![Peek 2021-05-17 21-04](https://user-images.githubusercontent.com/36141306/118535838-a696c780-b753-11eb-94db-1bf0a0d59f38.gif)
