### ISSUE TITLE
Support for accessibility

### ISSUE THREAD

**Issue by gfox1984** [wbkd/react-flow#1033]
Hi,

I really like the React-Flow library, but I wonder if it could be made more accessible by adding the appropriate [WAI-aria roles and attributes](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basic)?

To help with that, I would also suggest the use of [React Testing Library](https://testing-library.com/), which [encourages the use of queries that are accessible to everyone](https://testing-library.com/docs/queries/about#priority) for targeting elements, thus ensuring the tested components are actually accessible.

Is that something you would be willing to consider?

**Comment by moklick** [comment]
Hey @gfox1984 

thanks for your suggestion here. We have other features like grouping that are currently higher prioritized but will look into this. Also PRs are very appreciated :)

**Comment by mikebarkmin** [comment]
I think that working on accessibility is important. But at first we should discuss how this should look like. I think accessibility is not only working on correct aria roles, but also on keyboard navigation. Therefore, I think we need some ideas for keyboard navigation. Maybe we can borrow some ideas from [React Beautiful DnD](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/sensors/keyboard.md). Here are my suggestions for some workflows:
- **Traversing the Graph/Selecting a Node**: By using tab, navigate to the first node in the graph (What is the first node?). Use tab again to select a handle. Press space to follow the edge connected to the handle. Press shift+tab to go backwards. If you press tab on the last handle, follow the edge connected to the handle.
- **Moving a Node**: Select a node. Press arrow keys to move the node. Press shift+arrow key to move the node quicker.
- **Connecting Nodes**: Select a node. Tab to the desired output handle. Press "c" for going into connect mode. Press tab to go through the node aka. filtered elements list. Press space to select a node. Press tab to go through the input handles. Press space to connect.
- **Delete a Connection**: Select a node. Tab to the desired handle. Press "Del" to delete the connection.
- **Delete a Node**: Select a node: Press "Del" to delete the node.

All shortcuts should be customizable, like the deleteCode.

**Comment by moklick** [comment]
Thanks for your input here @mikebarkmin. This is very valuable. Keyboard navigation would be a really nice feature I would like to see! I will close this issue and create a new discussion in the "New Feature" section.

**Comment by moklick** [comment]
For v11 we'll add basic keyboard controls and better WAI-ARIA defaults. 

## Updates: 

### keyboard controls

* Nodes and edges accessible via tab (`tabIndex={0}` + `role="button"`)
* Nodes and edges selectable via Enter or Space, un-selectable via Escape
* Nodes moveable with arrow keys 
* Nodes and Edges get `aria-describedby` to describe controls
* all features above can be disabled with the `disableKeyboardA11y` prop

### WAI-ARIA

* Edges: Default `aria-label` - overwritable with new `Edge` prop `ariaLabel`  
* Nodes: `ariaLabel` prop (no default here, because we assume that there might be text inside the node)
* Minimap: `aria-describedby` + title
* Attribution: `aria-label`

**Comment by amharris1331** [comment]
Is it possible to currently define the aria-label for the Controls feature that shows the zoom-in, zoom-out, fit-view and a lock/unlock button?

**Comment by moklick** [comment]
aria-labels for controls are already defined. Would you like to customize them?

**Comment by amharris1331** [comment]
Hey Moritz!

Thanks for getting back to me so quickly.  My team is using the Controls Hook in our website from ReactFlow but when we run the Google Chrome extension “Accessibility Insights”, it pin points that the Controls components do not have individual aria-labels and that this needs to be added for our page to be Accessibility compliant.

This is what the HTML looks like when you inspect the UI for our page:

***@***.***

As you can see, there are no aria-labels in the definitions for the class of these Controls buttons.  Is there a way to add in the aria-label for these buttons?

Here is a copy of the code we are using as well to set up the Controls hook in our code for our page:

***@***.***

Best,

Amanda Harris

**Comment by amharris1331** [comment]
Here is the HTML for the buttons upon inspect.  As you can see, there is no aria-label defined in the class for the buttons. 
`<div class="react-flow__controls">
   <button type="button" class="react-flow__controls-button react-flow__controls-zoomin"> 
         <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
              <path d="M32 18.133H18.133V32h-4.266V18.133H0v-4.266h13.867V0h4.266v13.867H32z"></path>
          </svg>
    </button> 
    <button type="button" class="react-flow__controls-button react-flow__controls-zoomout">
       <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 5"> 
          <path d="M0 0h32v4.2H0z"></path>
       </svg>
    </button>
    <button type="button" class="react-flow__controls-button react-flow__controls-fitview">
       <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 30">
          <path d="M3.692 4.63c0-.53.4-.938.939-.938h5.215V0H4.708C2.13 0 0 2.054 0 4.63v5.216h3.692V4.631zM27.354 0h-5.2v3.692h5.17c.53 0 .984.4.984.939v5.215H32V4.631A4.624 4.624 0 0 0 27.354 0zm.954 24.83c0 .532-.4.94-.939.94h-5.215v3.768h5.215c2.577 0 4.631-2.13 4.631-4.707v-5.139h-3.692v5.139zm-23.677.94a.919.919 0 0 1-.939-.94v-5.138H0v5.139c0 2.577 2.13 4.707 4.708 4.707h5.138V25.77H4.631z">
      </path> 
       </svg>
     </button>
     <button type="button" class="react-flow__controls-button react-flow__controls-interactive"> 
       <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 32"> 
           <path d="M21.333 10.667H19.81V7.619C19.81 3.429 16.38 0 12.19 0c-4.114 1.828-1.37 2.133.305 2.438 1.676.305 4.42 2.59 4.42 5.181v3.048H3.047A3.056 3.056 0 0 0 0 13.714v15.238A3.056 3.056 0 0 0 3.048 32h18.285a3.056 3.056 0 0 0 3.048-3.048V13.714a3.056 3.056 0 0 0-3.048-3.047zM12.19 24.533a3.056 3.056 0 0 1-3.047-3.047 3.056 3.056 0 0 1 3.047-3.048 3.056 3.056 0 0 1 3.048 3.048 3.056 3.056 0 0 1-3.048 3.047z">
          </path>
      </svg>
   </button>
</div>`

**Comment by moklick** [comment]
You are using an old version of React Flow. Please update to v10, since v9 is not supported anymore https://reactflow.dev/docs/guides/migrate-to-v10/

**Comment by amharris1331** [comment]
That did the trick!  Thank you for the help!
