### ISSUE TITLE
Edge Updater: No validation

### ISSUE THREAD

**Issue by adhammo** [wbkd/react-flow#1034]
Edge updater doesn't validate the target node using the source handle `isValidConnection`.

After inspecting the code, I found [here](https://github.com/wbkd/react-flow/blob/e3cdecbafe86915b82d73890df4b50bd67a40ac9/src/components/Edges/wrapEdge.tsx#L130) that you don't really use the source handle `isValidConnection` rather you treat it as always valid.

Why don't you query for target node using its ID then get the source handle item using its ID and validate using its `isValidConnection`.

Also, why don't you pass an argument to handler `onMouseDown` to indicate edge updating rather than checking **react-flow__edgeupdater** that would also let you skip elementBelow validation and use isTarget rather than checking it yourself. hence, it would solve the problem of updating an edge through its source handle side updater (forgot to mention that there is a problem when you try to update an edge from its source handle side).

 I can create a PR to solve the previously mentioned issues, if you want.

**Comment by moklick** [comment]
Hey @adhammo 

thanks for your input here. Unfortunately we have little resources at the moment so PRs are highly appreciated :)

**Comment by Padreco-lbr** [comment]
Are there any updates on this matter? Allowing an edge update to bypass `isValidConnection` defeats the purpose of `isValidConnection`.

**Comment by moklick** [comment]
Everything would be easier if we would have a different API for the handles. How could we get the `isValidConnection` function out of the custom node component? I like your workaround @Padreco-lbr and would recommend something like that, too! I will leave the issue open for now. Maybe we can adjust the API a bit so that it is getting easier to achieve this.

**Comment by moklick** [comment]
Since v11.6.0 you can pass a global `isValidConnection` prop to the ReactFlow component. That one is also called when updating an edge.
