### ISSUE TITLE
(Layouting) Edges mispositioned on zoom when setting dagre setgraph

### ISSUE THREAD

**Issue by mountainlife** [wbkd/react-flow#1035]
Hi is there a proper way to set the distance between nodes/edges in https://reactflow.dev/examples/layouting/ ?
I tried adding the nodesep property in  dagreGraph.setGraph({ rankdir: direction, **nodesep:90** }); and it works fine on normal view but when I zoom in and zoom on the layout, the edges are being positioned in the wrong place.

**Comment by moklick** [comment]
Hi! Could you create a codesandbox or a repo so that we can check it?
