### ISSUE TITLE
The docs page (https://reactflow.dev/) is down

### ISSUE THREAD

**Issue by Akcps** [wbkd/react-flow#1036]
@ashwanthkumar @ambroseus 
Guys can you look into this

**Comment by ambroseus** [comment]
@moklick  confirmed

**Comment by leejustin** [comment]
This is just a guess, but it could possibly be related to the fact that Google Cloud has had some outage today and there is degredation in upstream services like Netlify. It helps that all of the examples can be found in this repo.

Regardless, the site looks like it's back up.

**Comment by moklick** [comment]
It was indeed a netlify issue. The docs have their own repo btw but thanks for mentioning it!
