### ISSUE TITLE
Multiple ReactFlow component instances; Background issue

### ISSUE THREAD

**Issue by sarasfive** [wbkd/react-flow#1037]
Best described in the attached screen capture:

https://user-images.githubusercontent.com/67014075/112688781-8ecb5300-8e36-11eb-99a0-97f2954f157e.mov

In this example, there are two `ReactFlow` component instances wrapped with `ReactFlowProvider`. While each maintain their own state as expected, the nested `Background` component appears to be shared across each `ReactFlow` component instance?

**Comment by moklick** [comment]
😳  what is happening here?? I will take a look. Thanks for the report!

**Comment by moklick** [comment]
bugfix released in v9.4.0

**Comment by chipnick** [comment]
Still have this bug in reactflow@11.8.2

**Comment by moklick** [comment]
@chipnick you need to pass a unique id to each flow.

**Comment by chipnick** [comment]
Still see this bug even with unique ID
![Знімок екрана з 2023-08-21 12-13-06](https://github.com/wbkd/react-flow/assets/61973588/6a273979-d6d6-4380-b2cd-84f29fe03cc6)
![Знімок екрана з 2023-08-21 12-12-27](https://github.com/wbkd/react-flow/assets/61973588/a7eb9c3f-246f-47de-9092-ae3cefb02e2f)

**Comment by moklick** [comment]
I can't reproduce this. Can you create a codesandbox for this https://new.reactflow.dev/react-ts
