### ISSUE TITLE
n-Handles: Edge drags out from bottom when position is set to right

### ISSUE THREAD

**Issue by sarasfive** [wbkd/react-flow#1038]
Demo video:

https://user-images.githubusercontent.com/67014075/112704553-49b81880-8e58-11eb-81d7-dfe13f57610a.mov

Test repo (line# 25):

https://github.com/sarasfive/react-flow-custom-node/blob/main/src/CustomNode.js

```
{sourceHandles.map((sourceHandle, index) => (
  <>
    <div style={{ height: 16 }}>Source Handle {index}</div>
    <Handle
      key={index}
      type="source"
      position="right"
      id={index}
      style={{ top: 90 + 16 * index }}
    />
  </>
))}
```

Am I doing this correctly or is there a better way to _handle_ this? :)

**Comment by moklick** [comment]
The id should be a string and you need to use the `useUpdateNodeInternals` hook when you programatically change the number of handles: https://reactflow.dev/docs/api/hooks/

**Comment by sarasfive** [comment]
> The id should be a string and you need to use the `useUpdateNodeInternals` hook when you programatically change the number of handles: https://reactflow.dev/docs/api/hooks/

Awesome. Thank you. 👍 

I've updated the [test repo](https://github.com/sarasfive/react-flow-custom-node/blob/main/src/CustomNode.js) to reflect.

**Comment by moklick** [comment]
You only need to call the hook once for the node and not for every handle:

```javascript
useEffect(() => updateNodeInternals(id), [sourceHandles]);
```

the id gets passed as a prop to the custom node.
