### ISSUE TITLE
Allow child elements in EdgeText's label 

### ISSUE THREAD

**Issue by gfox1984** [wbkd/react-flow#1045]
I would like to use [tspan](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan) to style parts of my label in an `EdgeText` component.

This works well, but the TypeScript interface expects the `label` property to receive a string. Could it be changed to `JSX.Element`?

Thanks in advance

**Comment by moklick** [comment]
Good idea. Released in 9.4.1 - example usage: https://github.com/wbkd/react-flow/blob/main/example/src/Edges/index.tsx#L46-L53

**Comment by gfox1984** [comment]
That was quick! Thank you, it's great working with libraries that are so responsive!
