### ISSUE TITLE
SSR initial load does not include styles for controls

### ISSUE THREAD

**Issue by mikebarkmin** [wbkd/react-flow#1051]
The initial load of a server side renderer page with react-flow-renderer on it does not load the styles for the controls. It happens on your documentation (gatsby):
![reactflowcontrols](https://user-images.githubusercontent.com/2592379/113099210-e3394e80-91f9-11eb-8060-9026a3223eb3.png)

And on my website (nextjs):
![bitflowcontrols](https://user-images.githubusercontent.com/2592379/113099465-44612200-91fa-11eb-84dd-5d5fe2fb2803.png)

I am not sure what is coursing it, maybe some of you have an idea?

**Comment by moklick** [comment]
We addressed this issue before.. which version are you using? The problem is that the icons are rendered without styles and the have a bigger size. Maybe we should not display them at all when no styles are loaded.

**Comment by mikebarkmin** [comment]
9.4.2. I now switched to not rendering the controls on ssr.
