### ISSUE TITLE
Potentially expensive style recalculation due to draggable's enableUserSelectHack

### ISSUE THREAD

**Issue by Zeroster** [wbkd/react-flow#1057]
[Draggable](https://github.com/react-grid-layout/react-draggable)  has a prop called ```enableUserSelectHack```, which runs [code that adds an expansive selector ](https://github.com/react-grid-layout/react-draggable/blob/13f6daf353da3b86116e55349d27427bb2bae2f8/lib/utils/domFns.js#L148-L181) when starting a node drag and the removes it after. This is also applied when selecting a node.

For large apps with many DOM elements and styles, this can take up to a second in style recalculation time alone when selecting a node or starting a drag in react-flow.

Could we make it an option in react-flow (without leaking react-flow's abstraction over draggable)? Testing react-flow with this disabled didn't seem to cause any selection issues but YMMV. It improved selection performance substantially for larger apps.

**Comment by moklick** [comment]
Thanks for the hint. This is really interesting. When I see it right we can set it to `false` without any disadvantages.

**Comment by Zeroster** [comment]
Calling ```event.preventDefault();``` in react-flow's internal ```onDragStart``` handler or in the ```onNodeDragStart``` public interface hander seems to help with the selection in Safari (at least in my app). I didn't notice any regression in Chrome or Firefox while doing a very quick check. 

I'm not sure of the potential ramifications within react-flow or for applications that may rely on the existing behavior. The event would be cancelled but would still propagated.

**Comment by moklick** [comment]
Thanks again for this finding :) Released in 9.5.1
