### ISSUE TITLE
Improve the getSmoothStepPath for the markers orient

### ISSUE THREAD

**Issue by clementloridan** [wbkd/react-flow#1058]
I have custom markers with orient="auto" but the the `getSmoothStepPath` don't give the best path for the markers.

<img width="593" alt="Capture d’écran 2021-04-01 à 17 41 57" src="https://user-images.githubusercontent.com/15263596/113319219-e3c90680-9319-11eb-8278-6b1c474ab568.png">
<img width="298" alt="Capture d’écran 2021-04-01 à 18 41 31" src="https://user-images.githubusercontent.com/15263596/113319274-efb4c880-9319-11eb-907a-97298e37c161.png">

**Comment by clementloridan** [comment]
Any idea to implement a collision detection to draw a line arround nodes?

**Comment by moklick** [comment]
Initially react-flow was built for horizontal OR vertical flows. We need to refactor the edge logic to cope with these configurations.

**Comment by moklick** [comment]
Hey @clementloridan. Could you try v9.4.3?

**Comment by clementloridan** [comment]
Hey @moklick 

No change for the `right` to `left`
<img width="822" alt="Capture d’écran 2021-04-06 à 18 24 56" src="https://user-images.githubusercontent.com/15263596/113736259-9bd52580-9705-11eb-889e-f91389ddbd42.png">

And breaking change for the `right` to `bottom` :/
![Uploading Capture d’écran 2021-04-06 à 18.25.25.png…]()

**Comment by moklick** [comment]
Thanks @clementloridan. Can you check v9.4.4?

**Comment by clementloridan** [comment]
Hey @moklick 

Voilà :p 

I got 2 issues:

1.Orient of the arrow for `right` to `left`
2. Zoom issue with handle position


<img width="1034" alt="Capture d’écran 2021-04-07 à 12 09 42" src="https://user-images.githubusercontent.com/15263596/113841857-d3da7800-979a-11eb-967f-bf9ae661d512.png">

Hope can help you. If needed ask me :)

**Comment by mikest** [comment]
Interesting. Are you using a custom wire? While I am having the zoom issues, I see it with any wire style. I don't see the handle edge orientation position problem with my own custom wires.

**Comment by clementloridan** [comment]
Yes @mikest I use custom link, and I use so a custom `getSmotthStepPath` util. But finally, U choose the bezier rendering.

**Comment by Mahdi-Soultana** [comment]
Hello everyone i  start learning react-flow and how to create custom nodes , and custom floating edges, and i found 2 problems :
case one: When we have a custom node circle with floating edge and has a marker end (arrow) , we notice that we have spacing on the corners of the circle node not float in the edges of the node?

2nd - with a custom edge we want resistance or a button in the center to follow rotating depending to the direction of the line with no weird behaviors ? 

you can see the problems in the photo or in the send box, please help me !

![ice_screenshot_20220701-101339](https://user-images.githubusercontent.com/67097548/176864863-0d466f63-ce01-4825-b657-94a0dee887cd.png)

 

https://codesandbox.io/s/sandpack-project-forked-ocw82p?file=/customNode.js

**Comment by Mahdi-Soultana** [comment]
Hello everyone i  start learning react-flow and how to create custom nodes , and custom floating edges, and i found 2 problems :
case one: When we have a custom node circle with floating edge and has a marker end (arrow) , we notice that we have spacing on the corners of the circle node not float in the edges of the node?

2nd - with a custom edge we want resistance or a button in the center to follow rotating depending to the direction of the line with no weird behaviors ? 

you can see the problems in the photo or in the send box, please help me !

![ice_screenshot_20220701-101339](https://user-images.githubusercontent.com/67097548/176864863-0d466f63-ce01-4825-b657-94a0dee887cd.png)

 

https://codesandbox.io/s/sandpack-project-forked-ocw82p?file=/customNode.js

**Comment by mrkacan** [comment]
> Hello everyone i start learning react-flow and how to create a custom nodes, a custom floating edges, and i found 2 problems : case one: When we have a custom node circle with a floating edge and has a marker end (arrow) , we notice that we have spacing on the corners of the circle node not floating in the edges of the node?
> 
> 2nd - with a custom edge we want resistance or a button in the center to follow rotation line depending to the direction of the line?
> 
> you can see the problems in the photo or in the send box, please help me !
> 
> ![ice_screenshot_20220701-101339](https://user-images.githubusercontent.com/67097548/176864863-0d466f63-ce01-4825-b657-94a0dee887cd.png)
> 
> https://codesandbox.io/s/sandpack-project-forked-ocw82p?file=/customNode.js

+1

**Comment by moklick** [comment]
hey @clementloridan 

Is this still an issue with the latest version 10.3.10?

@Mahdi-Soultana please open a new issue or better a discussion in this case.

**Comment by moklick** [comment]
Please re-open if the issue still persists.

**Comment by sumvedshami** [comment]
Hello there,

I think the issue still persists. I am using the version ^11.10.2.

Here is the image where you can see the marker orientation is weird and overlapping over the edge of the custom handle.
<img width="313" alt="Screenshot 2024-02-06 at 1 50 50 AM" src="https://github.com/xyflow/xyflow/assets/126200166/67cb2e8c-9092-4c3c-b4e4-6d297bf26359">

Below is the code of CustomEdge.

```
import React, { useState } from "react";
import { lightBlue } from "@mui/material/colors";
import CloseIcon from "@mui/icons-material/Close";
import {
  BaseEdge,
  EdgeLabelRenderer,
  getSmoothStepPath,
  useReactFlow,
} from "reactflow";

export default function CustomEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  markerEnd,
}) {
  const { setEdges } = useReactFlow();
  const [edgePath, labelX, labelY] = getSmoothStepPath({
    sourceX,
    sourceY,
    targetX,
    targetY,
  });
  const [isHovered, setIsHovered] = useState(false); // State to track hover

  const customStyle = {
    stroke: lightBlue[600],
    strokeWidth: 2,
  };

  // Define styles for normal and hovered state
  const buttonStyle = {
    position: "absolute",
    transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
    width: "24px",
    height: "24px",
    backgroundColor: isHovered ? "#f8f8f8" : "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "2px",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.2)",
    cursor: "pointer",
    pointerEvents: "all",
  };

  return (
    <>
      <BaseEdge
        id={id}
        path={edgePath}
        markerEnd={markerEnd}
        style={customStyle}
      />
      <EdgeLabelRenderer>
        <div
          style={buttonStyle}
          className="nodrag nopan"
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={() => setIsHovered(false)}
          onClick={() =>
            setEdges((es) => es.filter((e) => e.id !== id.toString()))
          }
        >
          <CloseIcon
            style={{ fontSize: "1rem", color: isHovered ? "darkred" : "red" }}
          />{" "}
        </div>
      </EdgeLabelRenderer>
    </>
  );
}

```

And here is the code of CustomHandle.

```
import React from "react";

import { Handle } from "reactflow";

import "../styles/handle.css";

const CustomHandle = ({ id, type, text, position }) => {
  const positionClass = `handle-${position.toLowerCase()}`;
  const labelClass = `label-${position.toLowerCase()}`;
  const oppositeType = type === "source" ? "Target" : "Source";

  return (
    <div className={positionClass}>
      <Handle id={id} type={type} position={position} className="node-handle" />
      <div className={`nodrag handle-label ${labelClass}`}>
        <span style={{ fontWeight: "bold" }}>{oppositeType}: </span>
        <span>{text}</span>
      </div>
    </div>
  );
};

export default CustomHandle;

```

I am unable to fix this issue. Request you to please help. Thank you.

Best Regards,
Sumved

**Comment by moklick** [comment]
Which positions are you passing to the Handle components?

**Comment by sumvedshami** [comment]
Source handle position is right, while the Target handle position is left.

Source handle:

```
<CustomHandle
  id="r"
  type={"source"}
  position={Position.Right}
/>
```

Target handle:

```
<CustomHandle
  id="l"
  type={"target"}
  position={Position.Left}
/>
```

**Comment by sumvedshami** [comment]
@moklick Can you please help here? I am still stuck here. Thank you in advance.
