### ISSUE TITLE
onSelect prop for triggering selecting same node

### ISSUE THREAD

**Issue by ambuznego** [wbkd/react-flow#1059]
When a node is selected, I trigger an information sidebar using `onSelectionChange` to open with details about that node. There is a button to close that sidebar. If closed, `ReactFlow` still considers that node selected, so selecting the same node previously selected does not trigger `onSelectionChange` and therefore I cannot trigger the sidebar to reopen. It would be nice to have `onSelect` which triggers every time so that this type of action could be supported.

**Comment by IsmaFunes** [comment]
I'm struggling with something similar: I want to select a node from a list on a sidebar, but I can't find a way to pass which node/nodes I want selected.

**Comment by sarasfive** [comment]
@IsmaFunes Is this what you're looking for? https://reactflow.dev/examples/provider/

**Comment by moklick** [comment]
At the moment you can only use the internal `setSelectedElements` action mentioned in the comment by @sarasfive. When you press the close button you can reset the selection via `setSelectedElements([])`. After that the selection should work as expected again.

**Comment by IsmaFunes** [comment]
> @IsmaFunes Is this what you're looking for? https://reactflow.dev/examples/provider/

This was the solution for me. I ended up creating a custom hook in order to dispatch some other actions as well as the react-flow one. Worked like a charm.

Thanks.

**Comment by moklick** [comment]
I will add some interfaces in form of hooks to access the internal actions and store props. But using actions and the store directly will always be a bit hacky and undocumented :D

**Comment by IsmaFunes** [comment]
That makes sense, using the internal feels kinda hacky. 

But in my case, I wanted to listen for a certain action of react-flow inside a saga, but couldn't. Hence I had to go for another implementation.

**Comment by ambuznego** [comment]
> At the moment you can only use the internal `setSelectedElements` action mentioned in the comment by @sarasfive. When you press the close button you can reset the selection via `setSelectedElements([])`. After that the selection should work as expected again.

This worked like a charm! I missed this part of the documentation. Thank you 🙏

**Comment by moklick** [comment]
Try to move the Provider one level up. I could imagine that your component isn't wrapped.
