### ISSUE TITLE
Two react flow graphs using same data

### ISSUE THREAD

**Issue by davidcas9** [wbkd/react-flow#1062]
It looks like when a component uses two ReactFlow Components, the last loaded data is the one that gets used for both ReactFlow components, e.g. :

```
<NetworkComponent elements={GraphOne}/>
<NetworkComponent elements={GraphTwo}/>
```

GraphTwo will be featured in both network components. How do I show both graphs separately on the same page?

**Comment by moklick** [comment]
You need to wrap each flow with its own `ReactFlowProvider` when you have multiple flows on a page https://reactflow.dev/docs/api/components/provider/
