### ISSUE TITLE
Not getting latest state value

### ISSUE THREAD

**Issue by Kickbuttowaski** [wbkd/react-flow#1066]
Hi Team,

I am trying to pass an onChange event to my customnode, but inside the onChange event I am not able to get the latest state value, only the initial value is getting printed.
```

const nodeTypes = {
    General: ()=>{return <General handleChange={handleChange} />},
  };
```

**Comment by moklick** [comment]
Is the handleChange function memoized via useCallback? Please provide the complete code example, preferably with a codesandbox or repo.

**Comment by moklick** [comment]
closed due to inactivity.
