### ISSUE TITLE
onElementsRemove: When composing multiple flows, removing element(s) from one flow will deselect element(s) from other flows

### ISSUE THREAD

**Issue by sarasfive** [wbkd/react-flow#1067]
Test case: https://github.com/sarasfive/react-flow-remove-elements

**STR**

1. Select node 1 (first flow)
2. Select node 2 (second flow)
3. Press backspace

**Expected**
Selected element(s) will be passed to `onElementsRemove` for the specific flow where the element(s) are to be removed. Only those elements will be deselected.

**Actual**
Selected element(s) in each flow are deselected.

For this test case, selecting `node-1` (first flow) and `node-2` (second flow) and pressing backspace deselects both `node-1` and `node-2`. Console prints `Removing elements from 1st flow` and `Removing elements from 2nd flow`.

My initial solution was to track the 'active' flow and somehow block the deselection in the non-'active' flow. The only way I could see to do this is to `useStoreActions` hook and select the elements again, but this doesn't seem to be the right approach. I couldn't get the call stack (can't block deselection) to work properly without introducing a `setTimeout`. It works, but this solution causes a deselect->select flicker (not shown in test case).

Is this a bug or would another solution be recommended?

Cheers!

**[Code](https://github.com/sarasfive/react-flow-remove-elements/blob/main/src/App.js)**
```
import React from 'react'
import ReactFlow, { ReactFlowProvider } from 'react-flow-renderer'

function App() {
  return (
    <>
      <div style={{ width: 500, height: 500 }}>
        <ReactFlowProvider>
          <ReactFlow
            elements={[
              {
                id: 'node-1',
                data: { label: 'node 1' },
                position: { x: 0, y: 0 }
              }
            ]}
            deleteKeyCode={8}
            onElementsRemove={() =>
              console.log('Removing elements from 1st flow')
            }
          />
        </ReactFlowProvider>
      </div>

      <div style={{ width: 500, height: 500 }}>
        <ReactFlowProvider>
          <ReactFlow
            elements={[
              {
                id: 'node-2',
                data: { label: 'node 2' },
                position: { x: 0, y: 0 }
              }
            ]}
            deleteKeyCode={8}
            onElementsRemove={() =>
              console.log('Removing elements from 2nd flow')
            }
          />
        </ReactFlowProvider>
      </div>
    </>
  )
}

export default App
```

**Comment by moklick** [comment]
This is not really an issue. The flows don't know of each other. You would need to implement a deselection by yourself. You could use `setSelectedElements([])` for flow A when you select a node from flow B for example.

**Comment by sarasfive** [comment]
Awesome. I should have slept on it! :)

I've updated the [test case](https://github.com/sarasfive/react-flow-remove-elements) with a [solution](https://github.com/sarasfive/react-flow-remove-elements/commit/45c2222598d0fc46d22b6eab9ebd38ff0ec71027).

```
onElementsRemove={
  activeFlow === 'flow-1'
    ? (elements) => {
        console.log('Removing elements from 1st flow')
        console.log(elements)
      }
    : null
}
```
