### ISSUE TITLE
[BUG] Artefacts from old element data

### ISSUE THREAD

**Issue by mikepan-ovoenergy** [wbkd/react-flow#1072]
Seems that edges that go beyond some width are not cleared properly on elements prop change. You can see bellow:

![image](https://user-images.githubusercontent.com/68534175/113574953-cf408300-9625-11eb-83b6-30a559a8f10a.png)

**Comment by moklick** [comment]
This looks weird. Can you provide steps how we can reproduce this or create a codesandbox or a repo?

**Comment by mikepan-ovoenergy** [comment]
The data I use is confidential and is huge. BTW, is there a chance the amount of data to be the problem here? E.g. this really happens on the bigger charts and is very consistent.

Is there something you would suggest I try?

**Comment by moklick** [comment]
What is big? Are the edges still rendered when you pan back and forth? Did you try to use another edge type like `smoothstep`?

**Comment by mikepan-ovoenergy** [comment]
The number of nodes and edges is big on some charts - around 70 nodes and 70 edges.
Zoom In/Out doesn't help, artefacts are still there on zooming. They are actually not artefacts, but fully rendered react elements, without click events on them though.

Just tried with `arrowHeadType: 'smoothstep'` and nothing changes.

**Comment by moklick** [comment]
You are sure that your data is correct? Can you reproduce it with the [stress example](https://reactflow.dev/examples/stress/)? Did you try to set `onlyRenderVisibleElements =false`?

**Comment by moklick** [comment]
Hey @mikepan-ovoenergy. Could you send me your ReactFlow props? Maybe it happens with a specific configuration.

**Comment by moklick** [comment]
closed due to inactivity. Feel free to open it again if the issue still occurs.
