### ISSUE TITLE
[BUG] Error on Node drag

### ISSUE THREAD

**Issue by fonpah** [wbkd/react-flow#1074]
When i add onNodeDrag handler and then try to drag the node i get an error thrown:
_Cannot assign to read only property 'x' of object '#<Object>'_
I looked at the code and i think this is happening because you are trying to update the x and y values of the node that is actaully wrapped with a _useMemo_ react hook.
https://github.com/wbkd/react-flow/blob/b620bfd7d4d9a42611ed84b33659514a0b2988ad/src/components/Nodes/wrapNode.tsx#L131

**Comment by moklick** [comment]
Sorry I can't reproduce this. It's possible to mutate an object that was created with a useMemo. Can you create a codesandbox or a repo?

**Comment by fonpah** [comment]
Sorry for wasting your time, I am not able to reproduce it in a smaller codebase. it must be something wrong  with my large project codebase.
https://codesandbox.io/s/lively-currying-0p803?file=/src/App.tsx

Thanks for the prompt response. will proceed to close this issue
Cheers
