### ISSUE TITLE
Edge positions getting messed up during zoom.

### ISSUE THREAD

**Issue by mikest** [wbkd/react-flow#1075]
![image](https://user-images.githubusercontent.com/742517/113949556-68a59b80-97c4-11eb-90c4-a206a0223a40.png)

I'm wondering if you have any pointers for tracking down this issue. I'm seeing a behavior where my edges will get lost during zoom at some point. It doesn't happen to all edges.

I'm using custom nodes, but otherwise generic styles.

**Comment by moklick** [comment]
This is a weird bug :/ Which browser are you using? Which react flow version is it?

**Comment by clementloridan** [comment]
I got this issue also: https://github.com/wbkd/react-flow/issues/1058#issuecomment-814752331

**Browser**: Chrome - Version 89.0.4389.114

**Comment by moklick** [comment]
How can I reproduce this? Could one of you create a codesandbox or a repo or post your ReactFlow props here? Maybe it happens for some interaction configuration.

**Comment by mikest** [comment]
This is on edge, but let me try and do a repro for you.

**Comment by mikest** [comment]
I can reproduce on one of the examples while running in Storybook (a component library test case manager):

![image](https://user-images.githubusercontent.com/742517/114254121-76912300-9962-11eb-80fe-6f2e743a0d50.png)

```
import { select } from '@storybook/addon-knobs';
import { storiesOf } from '@storybook/react';
import React, { useState } from 'react';

import ReactFlow, { removeElements, addEdge, MiniMap, Controls, Background, Edge, Elements } from 'react-flow-renderer';

//import CustomEdge from './CustomEdge';

const onLoad = (reactFlowInstance: any) => reactFlowInstance.fitView();
const onNodeDragStop = (event: any, node: any) => console.log('drag stop', node);
const onElementClick = (event: any, element: any) => console.log('click', element);

const initialElements: Elements<any> = [
    {
        id: 'edges-1',
        type: 'input',
        data: { label: 'Input 1' },
        position: { x: 250, y: 0 },
    },
    { id: 'edges-2', data: { label: 'Node 2' }, position: { x: 150, y: 100 } },
    { id: 'edges-2a', data: { label: 'Node 2a' }, position: { x: 0, y: 180 } },
    { id: 'edges-3', data: { label: 'Node 3' }, position: { x: 250, y: 200 } },
    { id: 'edges-4', data: { label: 'Node 4' }, position: { x: 400, y: 300 } },
    { id: 'edges-3a', data: { label: 'Node 3a' }, position: { x: 150, y: 300 } },
    { id: 'edges-5', data: { label: 'Node 5' }, position: { x: 250, y: 400 } },
    {
        id: 'edges-6',
        type: 'output',
        data: { label: 'Output 6' },
        position: { x: 50, y: 550 },
    },
    {
        id: 'edges-7',
        type: 'output',
        data: { label: 'Output 7' },
        position: { x: 250, y: 550 },
    },
    {
        id: 'edges-8',
        type: 'output',
        data: { label: 'Output 8' },
        position: { x: 525, y: 600 },
    },
    {
        id: 'edges-e1-2',
        source: 'edges-1',
        target: 'edges-2',
        label: 'bezier edge (default)',
        className: 'normal-edge',
    },
    {
        id: 'edges-e2-2a',
        source: 'edges-2',
        target: 'edges-2a',
        type: 'smoothstep',
        label: 'smoothstep edge',
    },
    {
        id: 'edges-e2-3',
        source: 'edges-2',
        target: 'edges-3',
        type: 'step',
        label: 'step edge',
    },
    {
        id: 'edges-e3-4',
        source: 'edges-3',
        target: 'edges-4',
        type: 'straight',
        label: 'straight edge',
    },
    {
        id: 'edges-e3-3a',
        source: 'edges-3',
        target: 'edges-3a',
        type: 'straight',
        label: 'label only edge',
        style: { stroke: 'none' },
    },
    {
        id: 'edges-e3-5',
        source: 'edges-4',
        target: 'edges-5',
        animated: true,
        label: 'animated styled edge',
        style: { stroke: 'red' },
    },
    {
        id: 'edges-e5-6',
        source: 'edges-5',
        target: 'edges-6',
        label: 'styled label',
        labelStyle: { fill: 'red', fontWeight: 700 },
        arrowHeadType: 'arrow',
    },
    {
        id: 'edges-e5-7',
        source: 'edges-5',
        target: 'edges-7',
        label: 'label with styled bg',
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: '#FFCC00', color: '#fff', fillOpacity: 0.7 },
        arrowHeadType: 'arrowclosed',
    },
    // {
    //     id: 'edges-e5-8',
    //     source: 'edges-5',
    //     target: 'edges-8',
    //     type: 'custom',
    //     data: { text: 'custom edge' },
    //     arrowHeadType: 'arrowclosed',
    // },
];

const edgeTypes = {
    // custom: CustomEdge,
};

const stories = storiesOf('ReactFlow', module) as any;

stories.addWithJSX('ReactFlow Example', () => {
    const [elements, setElements] = useState(initialElements);
    const onElementsRemove = (elementsToRemove: any) => setElements(els => removeElements(elementsToRemove, els));
    const onConnect = (params: any) => setElements((els: any) => addEdge(params, els));

    const containerStyle = { flex: 1, width: 800, height: 800 };

    return (
        <div id={'react-flow-wrapper'} style={containerStyle}>
            <ReactFlow
                elements={elements}
                onElementClick={onElementClick}
                onElementsRemove={onElementsRemove}
                onConnect={onConnect}
                onNodeDragStop={onNodeDragStop}
                onLoad={onLoad}
                snapToGrid={true}
                edgeTypes={edgeTypes}
                key='edges'
            >
                <MiniMap />
                <Controls />
                <Background />
            </ReactFlow>
        </div>
    );
});
```

**Comment by mikest** [comment]
Tried reproducing in Safari, Chrome, Edge and Firefox and was able to get the behavior in all browsers. I also did some digging into the output html in the browser debugger. It looks like the edge renderer is generating the SVG paths at the wrong locations.

How does the edge renderer resolve its source/target positions? They appear to be based on the positions of the DOM elements.

**Comment by moklick** [comment]
Thanks for the info. Is it possible that it has something to do with the storybook wrapper? Some lazy loaded styles or something like that? I will setup a storybook env and see if I can find the issue here.

**Comment by mikest** [comment]
Possible, but unlikely. Storybook loads the wrappers in an iFrame. Casual inspection of the DOM didn't reveal anything unusual.

**Comment by mikest** [comment]
Some further investigative notes:
- This problem only happens when using the Wheel Mouse to zoom quickly.
- Zooming through the controls hasn't reproduced the problem.
- The problem appears to happen more often if nodes are also moved.
- The behavior is intermittent.
- It is consistent with rendering updates looking at stale positioning data in the DOM when calculating where the edges should be.

Have you made any progress in reproducing on your end?

**Comment by TippyLion28** [comment]
Also suffering from this bug (as per #1136). Using chrome. Anecdotally it seems to happen mostly when doing a lot of zooming or maybe even switching windows/tabs, but can't prove this.

**Comment by mikest** [comment]
@TippyLion28 what react version are you using?

**Comment by moklick** [comment]
I would really like to fix this. But I still can't reproduce this bug :/

**Comment by mikest** [comment]
@moklick i will put something together for you.

**Comment by TippyLion28** [comment]
@mikest React 17.0.1

**Comment by mikest** [comment]
@moklick here is a reproducible test case made with vanilla react, react-flow-renderer, typescript and nothing else.

`https://github.com/mikest/rf-test`

I'm fairly certain that the DOM update performance of the graph during zoom is what causes the problem to surface.
![image](https://user-images.githubusercontent.com/742517/116450422-234b1b80-a810-11eb-9baa-77fabaa32c33.png)

There is some code borrowed from my project in here which I'm using to create a collection of elements. The `snooze()` call increases the cost of the `render()` which shakes the problem out pretty reliably.

Steps to reproduce:
- yarn start
- alternate between:
- 1. two finger zoom in and out of the graph
- 2. dragging different nodes to new locations
- repeat until edge wires no longer show up on node handles.

The repositioning of elements seems important to reproducing the problem.

I think the reason you're having a hard time reproducing this is that the DOM update performance for the default examples are very very fast. For apps which take longer to render there is a problem with the observed position of the laid out elements when the edge renderer gets around to calculating the handle positions.

The problem is very much performance dependent.

I'm going to try adding an expensive SVG to the nodes to see if it makes the problem occur more/less easily, but branch `main` reproduces the problem on my recent MacBook Pro.

(if you're still having trouble reproducing I would be happy to hop on a video call to demonstrate.)

**Comment by mikest** [comment]
Here's an example of the kind of rearranging I do when trying to reproduce the problem:

![image](https://user-images.githubusercontent.com/742517/116453707-0c0e2d00-a814-11eb-8672-6ecc3140a8ea.png)

I'll grab one of the "hub" nodes and drag it off to the side, then rapidly zoom all the way in and out again.

**Comment by moklick** [comment]
Thanks for the example. This is really helpful. Can you try to set `onlyRenderVisibleElements={false}` and check if the issue still occurs?

**Comment by mikest** [comment]
@moklick i switched our code to `onlyRenderVisibleElements={false}` and I haven't seen the issue reproduce yet. this workaround will work for now, thank you!

**Comment by moklick** [comment]
I just released a patch in 9.5.4. In that version we also set `onlyRenderVisibleElements = false` by default. The feature is not working good at all and for now it's better if it's turned off .. However could you check if the bug still occurs with the new version when you set `onlyRenderVisibleElements={true}`?

**Comment by moklick** [comment]
Please re-open if the issue still occurs

**Comment by rafaell-lycan** [comment]
There's no troubleshooting section on the docs @moklick, I'm wondering who many tips you all can give us for fine tunning and knowing issues. Anyhow, nice tip.

**Comment by JoseHenrique975** [comment]
I have a similar problem, I have a parent component "HDefault" > "ConditionNode" > child "CardCase"; 
and I have to position each Handle according to the map in the list and for each item in the list. I must load a "CardCase" component and with it a handle. The first time the component loads the handles position correctly. But, when zooming occurs, it appears that the elements "change size" and the handles lose their position.   

ConditionNode
_type Props = {
    node: ChatbotNodeDTO,
    topFather: number,
    elementChildren: Element | null
}
export default function ConditionNode({node, topFather, elementChildren}: Props) {

    const [conditions, setConditions] = useState(node.conditions);
    const { zoom } = useViewport();

    function findCase(caseId: string){
        if(elementChildren?.children == null) return;

        const allChilds = [];
        addAllChilds(allChilds, elementChildren);
    
        const items: any[] = [...allChilds];
        console.log(zoom)

        return items.find(item => item.id == caseId );
    }

    function addAllChilds(allChilds: any[], element) {
        if(!element?.children) return;
        
        const childs = [...element?.children];
        childs.forEach(child => {
            allChilds.push(child);
            addAllChilds(allChilds, child);
        })
    }

   

    return (
        <>
           <div id={node.id}>
            <div className="w-full h-auto px-2 overflow-x-auto overflow-y-hidden rounded p-2 flex  border-solid border-slate-200 border bg-white gap-x-3">
                <div className="w-6">
                <img className="w-3.5 h-3.5" src="../../../assets/chatbot-condition.png" alt="Condicional" />
                </div>
                    <div className="flex flex-col w-full">
                        <span className="text-sm">Condicional</span>
                        {
                            conditions &&
                            conditions.length > 0 &&
                            conditions.map((condition, index) => {
                                const caseHtml = findCase(condition.id);
                                if(condition.id == 'ceb07c2f-05da-4824-8bc1-645924bd312b')                                    
                                    console.log('ceb07c2f-05da-4824-8bc1-645924bd312b', caseHtml?.getBoundingClientRect()?.top, caseHtml?.getBoundingClientRect()?.height, zoom)
                                return <CardCase key={condition.id} id={condition.id} subMenu={condition} topFather={topFather} sizeTop={caseHtml?.getBoundingClientRect()?.top ?? 0} sizeHeigth={caseHtml?.getBoundingClientRect()?.height ?? 0}  />
                            } )
                        }
                    </div>
                </div>
           </div>
        </>
    )
}_

Card Case Component

type Props = {
 id: string,
 subMenu: any,
 topFather: number,
 sizeTop: number,
 sizeHeigth: number
}

export default function CardCase({ id, subMenu, topFather, sizeTop, sizeHeigth }: Props) {

/*
 useEffect(() => {

  
   if (cardRef.current) {
     const rect = cardRef?.current as unknown as HTMLElement;
     const elemnt = document.getElementById(id)?.getClientRects();
     console.log("Direto do html");
     console.log(elemnt);
     const pane = rect?.getBoundingClientRect()
     setSizeCard(pane);
     console.log("TopFather");
     console.log(topFather);

     console.log("Size Card");
     console.log(sizeCard?.top);
     console.log("sizeCard height")
     console.log(sizeCard?.height);
     const testFather = document.getElementById("testepai")?.getClientRects();
     console.log("Test father");
     console.log(testFather);
   }
    
 }, [cardRef, id]);
  */


  // console.log(topFather, sizeTop, sizeHeigth);

    return(
      <>
        <div className="w-full mt-2 bg-gray-100 text-center rounded-lg flex items-center justify-between p-3" id={id}
        >
          <div className="text-left flex items-center justify-start lg:justify-center">
            <span className="text-sm">{subMenu?.name}</span>
          </div>

          {
            <Handle isConnectable={true} type="source" position={Position.Right} style={{ top:`${sizeTop - topFather + sizeHeigth / 2}px`  }} id={id} />
          }          
        </div>
      </>
    )
}

Can anyone tell me how to fix this in relation to zoom? Leave it positioned in the middle of the cardCase and even when zooming it doesn't lose position?
