### ISSUE TITLE
Background are dots cut-off

### ISSUE THREAD

**Issue by ffdead** [wbkd/react-flow#1088]
Hi thanks for a cool lib!

I just noticed that the background dots are cut-off. This is what it looks like with very large dots: ![](https://www.dropbox.com/s/h1kdryp30xoxm1k/Screenshot%202021-04-12%20at%2010.20.56.png?dl=0&raw=1)
 (but also visible with the default size 🔍 )

**Comment by clementloridan** [comment]
Hey @ffdead, you can trick with a custom Background component:

1. Create a background component from `additional-components/Background/index.tsx`
2. To this custom `createGridDotsPath` : 

`
import React from 'react';

export const createGridDotsPath = (size, gap, fill) => {
    return (
        <>
            <circle cx={size} cy={size} r={size - 0.5} fill={fill} />
            <circle
                cx={size + gap / 2}
                cy={size + gap / 2}
                r={size / 1.5}
                fill={fill}
            />
        </>
    );
};
`

@moklick this solution looks good for you?

**Comment by moklick** [comment]
very good catch 🕵️‍♂️ fix was released in 9.5.0
