### ISSUE TITLE
How to access to Handle props?

### ISSUE THREAD

**Issue by clementloridan** [wbkd/react-flow#1089]
Hey @moklick,

I need to access to `isValidConnection` to have access on my custom node to display a tooltip on the hover of the handle.

To resume: access isValidation inside of a custom node OR do same like a custom Node but for handle.

The goal is to display a tooltip if my handle is not valid.

And how to have the validation not only on the hover on the handle but at the start of the Dnd?

**Comment by mikest** [comment]
I have this same question for the same reason. Commenting to follow along.

**Comment by clementloridan** [comment]
@moklick Any suggestions?

**Comment by moklick** [comment]
when do you want to display a tooltip? When user drags an edge above the handle or just on mouse enter?

**Comment by clementloridan** [comment]
On the hover of invalid handle.

**Comment by moklick** [comment]
Inside a custom node you should have all the information you need to clarify what kind of connections a handle could accept. You don't need the `isValidConnection` function.

**Comment by clementloridan** [comment]
Thks @moklick
