### ISSUE TITLE
When Rendering an item in the Flow area, you cannot modify any other details inside "data"

### ISSUE THREAD

**Issue by ericmeadows** [wbkd/react-flow#1093]
When using `onDragStart`, I am unable to pass along additional information, such as an image location, etc.

```
const onDragStart = (
  event: DragEvent,
  nodeType: string,
  imageLocation: string = "",
) => {
  event.dataTransfer.setData("application/reactflow", nodeType);
  event.dataTransfer.effectAllowed = "move";
};
```

Diving into things, the NodeProps should allow things to be extended, because it is defined as:
```
export interface NodeProps<T = any> {
  id: ElementId;
  type: string;
  data: T;
  selected: boolean;
  isConnectable: boolean;
  xPos?: number;
  yPos?: number;
  targetPosition?: Position;
  sourcePosition?: Position;
  isDragging?: boolean;
}
```

Ideally, I would not like to repeat the node types for an image change, when that image location,  handles, and layout are the same for these nodes, but I have 15 of them.

**Comment by ericmeadows** [comment]
Solved - nevermind!

**Comment by surajmahangade** [comment]
Hello, How did you update the "data" of a node after it is rendered?
