### ISSUE TITLE
Node Enter/Leave events not available when nodesDraggable=false

### ISSUE THREAD

**Issue by Codesleuth** [wbkd/react-flow#1094]
```tsx
<ReactFlow
  nodesDraggable={false}
  onNodeMouseEnter={(event, node) =>
    console.log({ name: 'onNodeMouseEnter', event, node })
  }
  onNodeMouseLeave={(event, node) =>
    console.log({ name: 'onNodeMouseLeave', event, node })
  }>
  {...}
</ReactFlow>
```

When disabling `nodesDraggable` we do not get events fired for  `onNodeMouseEnter` or `onNodeMouseLeave`. I can see why this is the case when I look at the code, but this is a feature I require for hovers similar to #313.

**Comment by Codesleuth** [comment]
As a workaround (for now) I'm adding an empty `onElementClick` handler which forces `pointerEvents = 'all'`.
Not ideal but it does work.

**Comment by moklick** [comment]
Good catch! Fix released in 9.5.1

**Comment by Codesleuth** [comment]
Brilliant, thanks for the fix! 🚀

**Comment by Inesseni** [comment]
Thank youuu was searching for hours for an easy-to-understand code snippet how to get ANY data from the nodes! (I'm a total beginner) This helped a lot! :)
