### ISSUE TITLE
How to customize edge label?

### ISSUE THREAD

**Issue by nfwyst** [wbkd/react-flow#1100]
my label is a component with some complex interaction, the text does not meet my needs.

**Comment by nfwyst** [comment]
I tried to use foreignObject, but it will not change with the path tag

**Comment by nfwyst** [comment]
@moklick Is there any solution 😭

**Comment by moklick** [comment]
Hey @nfwyst 

you need to implement a custom edge with your own label component. The given EdgeText component is very limited.

**Comment by nfwyst** [comment]
> Hey @nfwyst
> 
> you need to implement a custom edge with your own label component. The given EdgeText component is very limited.

Thanks for your suggestion, bro
