### ISSUE TITLE
Node position not updating 

### ISSUE THREAD

**Issue by nikhil-wisetr** [wbkd/react-flow#1101]
I am creating a flow which need regularly updating the node position but once I add the node x and y positions are not updating.
Meanwhile the data that I am updating in the node is showing fine.

**Comment by moklick** [comment]
Are you using strings as IDs? Can you share some code (codesandbox or repo)?

**Comment by nikhil-wisetr** [comment]
Yes, I am using string as ids

**Comment by moklick** [comment]
When you update the position you need to create new objects. Altering x or y is not enough.
