### ISSUE TITLE
An existing node, how to change the position X and Y

### ISSUE THREAD

**Issue by amans2k** [wbkd/react-flow#1102]
Hello everyone,

I am stuck on an issue. Where trying to update an existing node position.
But it is not working.

Following this example
https://reactflow.dev/examples/update-node/

Able to change the label, add styles, mark hidden like the example, but position X Y are not changing.

Any help is appreciated.

**Comment by moklick** [comment]
Are you creating a new object for the position? Can you share some code?

**Comment by moklick** [comment]
closed due to inactivity. Feel free to re-open.
