### ISSUE TITLE
How trigger remove node functionality from inside custom node?

### ISSUE THREAD

**Issue by mumairofficial** [wbkd/react-flow#1103]
I could not find anything related inside docs and thought it's better to ask this as a question here!

I am designing a custom node, which has a button to remove a node from canvas, and wondering if there is any callback method that I can invoke on delete node operation. Here is the basic structure which I am after:

![image](https://user-images.githubusercontent.com/6498132/115082070-bcc82280-9f1e-11eb-90c8-8af670ae0ba8.png)

My question is how can I remove the node while triggering the removal operation from inside of the custom button?

**Comment by moklick** [comment]
You need to alter your elements array and remove the node for example by filtering it via its id. The `onElementsRemove` is just a callback that is fired when you select a node and press Backspace.

**Comment by ananddoesembed** [comment]
@mumairofficial  did you get it. since useState is asynchronous its hard to get last element. how did you find it?

**Comment by mumairofficial** [comment]
@ananddoesembed I did not get your question but here is what I did, each node has a unique id and I have that id available inside my custom node element. I already had redux-store in my application and I synchronize it with the react-flow state. Then I simply dispatch remove the action and add node id as payload and synchronize react-flow and private context.

**Comment by benobab** [comment]
Can you share an example @mumairofficial?
Thanks.

**Comment by Decoder3-14** [comment]
@benobab now you could use the   `useReactFlow()` across your custom nodes to add, delete and get your nodes and edges. To delete a node, you simply need to get the nodes and filter by id.

**Comment by KaiyuanMa** [comment]
I get now you can just do a filter to delete the node, but what about the edges that are connected to it? A filter on nodes state does not trigger onEdgesChange, so how can I delete edges that are connected to the node in the state?

**Comment by haok1402** [comment]
> I get now you can just do a filter to delete the node, but what about the edges that are connected to it? A filter on nodes state does not trigger onEdgesChange, so how can I delete edges that are connected to the node in the state?

You can import [getConnectedEdges](https://reactflow.dev/api-reference/utils/get-connected-edges) from `reactflow`, filter out edges that are connected, and update with [setEdges](https://reactflow.dev/api-reference/types/react-flow-instance). 

Below is a code snippet that demonstrates the idea.

```
const handleDeleteOnClick = useCallback(() => {
      let nodeToDelete = null;
      const newNodes = nodes.reduce((acc, node) => {
        if (node.id === id) {
          nodeToDelete = node;
        } else {
          acc.push(node);
        }
        return acc;
      }, [] as Node[]);

      if (nodeToDelete !== null) {
        setNodes(newNodes);
        const connectedEdges = getConnectedEdges([nodeToDelete], edges);
        const newEdges = edges.filter((edge) => !connectedEdges.includes(edge));
        setEdges(newEdges);
      }
    }, [id, nodes, edges, setNodes, setEdges]);
```
