### ISSUE TITLE
Minimap renders badly on Firefox 87.0

### ISSUE THREAD

**Issue by doches** [wbkd/react-flow#1108]
The minimap appears to render badly (no AA/poor scaling) at all zoom levels on Firefox 87.0 on MacOS (and likely other versions of Firefox):

<img width="720" alt="firefox" src="https://user-images.githubusercontent.com/25926/115228925-a97da880-a112-11eb-9921-b1f0ddc82e98.png">

Contrast with a smoothly-scaled minimap on Chrome:

<img width="639" alt="chrome" src="https://user-images.githubusercontent.com/25926/115228935-abe00280-a112-11eb-9002-968917787f49.png">

To recreate, just open https://reactflow.dev/examples/ in Firefox on MacOS.

**Comment by moklick** [comment]
I releases a fix two days ago. Could you check the latest version? I will update the website as well

**Comment by doches** [comment]
I actually noticed it on the /examples website, not in a project of mine -- was just looking at react-flow for a potential project and noticed it didn't render as nicely as you probably expected. Thanks for the response, though, and for not dismissing it as "works in Chrome"!
