### ISSUE TITLE
Can't remove Element from React Flow

### ISSUE THREAD

**Issue by ThePrograminator** [wbkd/react-flow#1109]
Hey There,
In short when i remove an node in React Flow, the node on the screen disapears, but i can see that the elements array is the same. So that if i add a new node, the 'deleted' one reapears on the screen.

I have searched if this could be a React or UseState hook problem, but i can't find anything like this. I have tried a combination of four ways to delete the element with no luck.

I very much hope you can help

Packages Versions:

"react": "^17.0.1",
"react-flow-renderer": "^9.5.1"

```
//How i declare i my elements
const MissionTab = (props) => {
	const [ elements, setElements ] = useState([]);

//my testing remove method
const testRemove = (elementsToRemove) => {
		console.log('elementsToRemove before', elements);
		var removeElementsResult = removeElements(elementsToRemove, elements);
		console.log('removeElements result', removeElementsResult);

		elements.slice(0, 1);
		setElements(removeElementsResult, console.log('setElements removeElementsResult', elements));
		setElements([], console.log('setElements empty array after', elements));
		setElements(
			elements.filter((item) => item.id !== elementsToRemove.id),
			console.log('setElements filter after', elements)
		);
		setElements(
			(els) => removeElements(elementsToRemove, els),
			console.log('setElements like docs after', elements)
		);
		console.log('elements after', elements);
	};

//This method is set to the the onElementsRemove={onElementsRemove}
const onElementsRemove = (elementsToRemove) => (
		console.log('elementsToRemove', elementsToRemove), testRemove(elementsToRemove)
	);
```

![Result image](https://user-images.githubusercontent.com/19344505/115242212-f157fc00-a121-11eb-83f8-357c189ecd91.PNG)

**Comment by AviusX** [comment]
Did you figure out why the deleted node reappears on the screen? And what did you do to fix it?
