### ISSUE TITLE
Svelte Wrapper

### ISSUE THREAD

**Issue by jeffRTC** [wbkd/react-flow#1110]
Looks neat but I wonder if you guys can ship a svelte wrapper or svelte  version of this..

**Comment by moklick** [comment]
Hey! I actually thought about doing a svelte-flow project but that would be independent from this project and not a wrapper.

**Comment by samuelstroschein** [comment]
@moklick 
Hi Moritz, 
are you still planning on doing a svelte-flow project?

**Comment by moklick** [comment]
I would love to :D But I think it is unrealistic because of time constraints..

**Comment by samuelstroschein** [comment]
understandable, thanks for the reply!
