### ISSUE TITLE
is Dynamic auto layouting using dagre possible?

### ISSUE THREAD

**Issue by laptopisasset** [wbkd/react-flow#1113]
I am building a node-based editor with react-flow, my requirement is that If I add a new node, it should automatically layout using 
LR rankdir in the graph. 

- I added a custom component Graph that holds ReactFlow Component
- Parent to Graph is ReactFlowProvider if I listen for useStoreState in Graph. which leads to infinite rendering

pls guide me if at all i am doing it wrong.

**Comment by TippyLion28** [comment]
+1 for this. Would like to be able to auto position only part of my graph and not the entire thing.

**Comment by leejustin** [comment]
The Layouting example on the docs uses `dagre`. https://reactflow.dev/examples/layouting/

**Comment by laptopisasset** [comment]
> The Layouting example on the docs uses `dagre`. https://reactflow.dev/examples/layouting/

yes, it uses dagre i to used dagre but the example specifies a static elements to be drawn in the editor in the graph, whereas my requirement is when adding a new node the node it self should layout correctly with respect to the previous node. in order to this  I first want to add the element  to reactflow internal element state with arbitrary position using actions.setElements which will calculate the node's width and height, in order to set the element and retrieve its position and reset in elements, but it pushes to me to render hell.

**Comment by laptopisasset** [comment]
import { FC, useEffect } from "react";
import ReactFlow, {
  Background,
  BackgroundVariant,
  Controls,
  Elements,
  useStoreActions,
  useStoreState,
  isNode,
} from "react-flow-renderer";

import _ from "lodash";

import dagre from "dagre";

const createGraphLayout = (elements: Elements): Elements => {
  const g = new dagre.graphlib.Graph();
  g.setGraph({ rankdir: "LR" });

  g.setDefaultEdgeLabel(() => ({}));

  elements.forEach((element) => {
    if (isNode(element)) {
      g.setNode(element.id, {
        label: element.id,
        width: element.__rf?.width,
        height: element.__rf?.height,
      });
    } else {
      g.setEdge(element.source, element.target);
    }
  });

  dagre.layout(g);

  return elements.map((element) => {
    const node = g.node(element.id);
    return {
      ...element,
      position: {
        x: node.x - node.width / 2,
        y: node.y - node.height / 2,
      },
    };
  });
};

const NodeDebug: FC = () => {
  const elements = useStoreState(
    (state) => [...state.nodes, ...state.edges],
    _.isEqual
  );

  const setElements = useStoreActions((actions) => actions.setElements);
  useEffect(() => {
    if (elements.length) {
      const newElements = createGraphLayout(elements);
      setElements(newElements);
    }
  }, [elements]);
  return null;
};

const Graph: FC = () => {
  return (
    <ReactFlow
      elements={[
        {
          id: "1",
          type: "input",
          data: { label: "input" },
          position: { x: 0, y: 0 },
        },
      ]}
    >
      <NodeDebug />
      <Background variant={BackgroundVariant.Lines} color="red" />
      <Controls />
    </ReactFlow>
  );
};

export default Graph;

**Comment by laptopisasset** [comment]
To Put in simple words how to dynamically calculate upcoming node's position as if it should look like graph.

**Comment by moklick** [comment]
For this you need to recalculate the elements position with the `createGraphLayout` function again after you added a node.

**Comment by laptopisasset** [comment]
yes you are right, when i do so i am stuck at renderLoop . adding the elements with setelements and listening of elements from usestorestate, can u please provide an example how you would have done it. since the example in docs uses static hight and width of node

**Comment by moklick** [comment]
Instead of this:

```js 
  useEffect(() => {
    if (elements.length) {
      const newElements = createGraphLayout(elements);
      setElements(newElements);
    }
  }, [elements]);
```

I would run graphlayout initially in the `onLoad` callback and then whenever you add a node.

**Comment by laptopisasset** [comment]
**then whenever you add a node** you will not have nodes width and height right, in order to have those you need to listen for those by using useSelector right? Then it will cause the same problem think so.

**Comment by alu0100888423** [comment]
Same problem here, I hope a solution, thank you very much in advance

**Comment by laptopisasset** [comment]
hi is there any updates @moklick

**Comment by cfree** [comment]
@laptopisasset When I tried something similar, I found that spreading pieces of state into an array created a re-render loop:

```
const elements = useStoreState((state) => [...state.nodes, ...state.edges]);
```

This did not:
```
const nodes = useStoreState((state) => state.nodes);
const edges = useStoreState((state) => state.edges);
...
const fn = useCallback(() => {
  const elements = [...nodes, ...edges];
  createGraphLayout(elements);
}, [nodes, edges]);
```

**Comment by RickeyWard** [comment]
> @laptopisasset When I tried something similar, I found that spreading pieces of state into an array created a re-render loop:
> 
> ```js
> const elements = useStoreState((state) => [...state.nodes, ...state.edges]);
> ```
> 
> This did not:
> 
> ```js
> const nodes = useStoreState((state) => state.nodes);
> const edges = useStoreState((state) => state.edges);
> ...
> const fn = useCallback(() => {
>   const elements = [...nodes, ...edges];
>   createGraphLayout(elements);
> }, [nodes, edges]);
> ```

note that `useStoreState` takes a "selector" passed into `useSelector` from react-redux. This is NOT intended to create new data in a shape you prefer, this is used to extract and watch specific data from the store and it performs equality checks (if something you didn't select changes your useStoreState wont cause a re-render), anything "new" returned from the selector will cause an infinite render loop by virtue of its purpose.

**Comment by 420407904** [comment]
I have a simple question. I don't want to set the height. What do I need to do to make the height of each node adaptive according to its own content, or is there no way

> `const nodeWidth = 172;
> const nodeHeight = 36;
> 
> const getLayoutedElements = (nodes, edges, direction = 'TB') => {
>   const isHorizontal = direction === 'LR';
>   dagreGraph.setGraph({ rankdir: direction });
> 
>   nodes.forEach((node) => {
>     dagreGraph.setNode(node.id, { width: nodeWidth, height: nodeHeight });
>   });`

**Comment by RickeyWard** [comment]
> I have a simple question. I don't want to set the height. What do I need to do to make the height of each node adaptive according to its own content, or is there no way

It is not necessary to set the height to a static value, each node can be a different value, but dagre isn't aware of the dom, you have to tell dagre the size of the nodes so you must measure them when you add them  to dagre, There's several ways to do this, depending on version of the library. _rf on the node is a reference to the node's dom object, you can get the height from that. Just look at the [example ](https://github.com/wbkd/react-flow/issues/1113#issuecomment-824520152)the OP posted above.

**Comment by 420407904** [comment]
Thank you answer me, and I apply this to my specific projects, there is the problem, look at this picture, it is in the second level, they were pulling away, should the second picture is that the layout of the, don't know if I'll have the clear, I don't know if I a few steps, thank you very much

![image](https://user-images.githubusercontent.com/66370869/167249882-7999500e-4ac5-4bbd-9b4f-9684eda9e703.png)
![image](https://user-images.githubusercontent.com/66370869/167250227-a27e13e9-7361-48c4-9919-cad10632bd83.png)

**Comment by 420407904** [comment]
dagre.layout(g)
![image](https://user-images.githubusercontent.com/66370869/167251142-2776506c-8024-4803-982b-b57936ec13fd.png)

**Comment by RickeyWard** [comment]
> Thank you answer me, and I apply this to my specific projects, there is the problem, look at this picture, it is in the second level, they were pulling away, should the second picture is that the layout of the, don't know if I'll have the clear, I don't know if I a few steps, thank you very much
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/66370869/167249882-7999500e-4ac5-4bbd-9b4f-9684eda9e703.png)
> 
> ![image](https://user-images.githubusercontent.com/66370869/167250227-a27e13e9-7361-48c4-9919-cad10632bd83.png)
> 
> 

It appears dagre thinks there is a node that the flow isn't rendering. Could be a bug in dagre as it hadn't been actively maintained in 3 years. You'll need to log all your state data as well as input and out of dagre to figure out what's missing. The purpose of this gh issue was to discuss how it could be achieved not really to deep dive individual issues.

**Comment by vaibhav-systango** [comment]
@moklick @chrtze how do we use dagre with subnodes ? Currently it's aligining parent nodes perfectly but the child nodes are going out of the parent nodes when using dagre . This is the example I referred:
https://reactflow.dev/docs/examples/layout/dagre/

@leejustin @laptopisasset @RickeyWard @cfree

**Comment by moklick** [comment]
Dynamic auto layout with dagre is possible. As explained you need to re-layout your graph when you add a node. The easiest way is to have pre-defined dimensions for your nodes. If that's not possible you need to wait for the first render and then do a re-calculation of the layout.  

@vaibhav-systango  If you need to handle sub flows, you could try [elkjs](https://github.com/kieler/elkjs) or [fcose](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose).

**Comment by jayanthbondi** [comment]
@laptopisasset ,
I'm facing the similar issue, could you please help me if you have the solution

**Comment by youngjuning** [comment]
```tsx
useEffect(() => {
    console.info(reactFlowInited, nodesInitialized)
    if (reactFlowInited && nodesInitialized) {
      setLayoutedNodes('LR');
    }
  }, [nodesInitialized, reactFlowInited, nodes?.length]);
```

**Comment by loggerhead** [comment]
I'm facing the same issue and here's my solution:
```javascript
  const isMeasured = nodes.length > 0 && nodes[0].measured?.width;

  useEffect(() => {
    if (isMeasured) {
      doLayout();
    }
  }, [isMeasured]);
```

**Comment by bcakmakoglu** [comment]
@loggerhead I'd recommend using [`useNodesInitialized`](https://reactflow.dev/api-reference/hooks/use-nodes-initialized) instead.

**Comment by hendstephen** [comment]
@jayanthbondi
Not sure if this is helpful, but I came up with a solution before finding this thread. It automatically recomputes the layout when new nodes are added to the graph. It accounts for measured node size so nodes don't need fixed sizes. It may be overkill for some cases, but for my specific project there were some scenarios where new nodes needed to be added without triggering a recompute of the layout (for example, dragging and dropping an edge creates a new node and leaves everything as is so the node will appear where it was dropped). Thus, making this a provider allows any child components to skip the next recompute. 

Note, for this to not cause the UX to jump around my custom node type has an `isHidden: boolean` property which sets the nodes opacity to 0 so it isn't visible. Then once the layout is computed we can unhide all nodes.

```jsx
/**
 * Recomputes the layout any time a new node is added to the graph. To skip a recompute, set the `skipNextRecompute` flag to true.
 */
export type DagreLayoutContextType = { skipNextRecompute: (skip: boolean) => void };

export const DagreLayoutContext = React.createContext<DagreLayoutContextType>({ skipNextRecompute: () => {} });

export const DagreLayoutProvider = (props: { skipInitialLayout: boolean; children: React.ReactNode }) => {
  const { skipInitialLayout, children } = props;
  const [shouldSkipNextRecompute, setShouldSkipNextRecompute] = React.useState<boolean>(skipInitialLayout);
  const [recomputeTriggered, setRecomputeTriggered] = React.useState<boolean>(false);
  const nodesInitialized = useNodesInitialized();
  const { getNodes, getEdges, setNodes, setEdges, fitBounds } = useReactFlow<CustomUINode, CustomUIEdge>();

  // Trigger recompute when nodes uninitialized
  React.useEffect(() => {
    if (!nodesInitialized) {
      setRecomputeTriggered(true);
    }
  }, [nodesInitialized, setRecomputeTriggered]);

  // If this recompute skipped, reset the flag for the next recompute
  React.useEffect(() => {
    if (shouldSkipNextRecompute && recomputeTriggered && nodesInitialized) {
      setShouldSkipNextRecompute(false);
      setRecomputeTriggered(false);
    }
  }, [shouldSkipNextRecompute, nodesInitialized, recomputeTriggered, setShouldSkipNextRecompute, setRecomputeTriggered]);

  // If this recompute was not skipped, run the recomputation
  React.useEffect(() => {
    if (!(recomputeTriggered && nodesInitialized && !shouldSkipNextRecompute)) {
      return;
    }

    setRecomputeTriggered(false);

    // getLayoutedElements calls dagre to compute the layout. height and width correspond to 
    // dagreGraph.graph().height and width, which allows us to fit the viewport to the layout 
    const { nodes, edges, height, width } = getLayoutedElements(getNodes(), getEdges());

    setEdges(edges.map(e => ({ ...e, hidden: false })));
    setNodes(
      nodes.map(n => ({
        ...n,
        data: {
          ...n.data,
          isHidden: false
        }
      }))
    );
    fitBounds({ width: width ?? 0, height: height ?? 0, x: 0, y: 0 }, { duration: zoomDuration });
  }, [recomputeTriggered, nodesInitialized, shouldSkipNextRecompute, getNodes, getEdges, setNodes, setEdges, fitBounds]);

  return (
    <DagreLayoutContext.Provider value={{ skipNextRecompute: setShouldSkipNextRecompute }}>
      {children}
    </DagreLayoutContext.Provider>
  );
};
```

Then just wrap your ReactFlow component in the layout provider.
```jsx
export const TreeForm = (props: ITreeFormProps) => (
  <ReactFlowProvider>
    <DagreLayoutProvider skipInitialLayout>
      <TreeFormInternal {...props} />
    </DagreLayoutProvider>
  </ReactFlowProvider>
);
```

This works reliably for my project, but always open for suggestions!

**Comment by bryantabaird** [comment]
I'm admittedly unsure if the async await in the `requestAnimationFrame` is appropriate, but the opacity trick worked for my use case (very basic), pending the `fitView` handler completion. Heavily inspired from the [layouting example](https://reactflow.dev/learn/layouting/layouting):

```typescript
const ReactLayoutFlow = ({
  initialNodes,
  initialEdges,
}: ReactLayoutFlowProps) => {
  const { fitView } = useReactFlow();

  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const [opacity, setOpacity] = useState(0);

  const nodesInitialized = useNodesInitialized();
  const [initialLayoutFinished, setInitialLayoutFinished] = useState(false);

  const onLayout = useCallback(
    (rankdir: string) => {
      const layouted = getLayoutedElements(nodes, edges, { rankdir });

      setNodes([...layouted.nodes]);
      setEdges([...layouted.edges]);

      window.requestAnimationFrame(async () => {
        await fitView();
        if (!initialLayoutFinished) {
          setInitialLayoutFinished(true);
          setOpacity(1);
        }
      });
    },
    [nodes, edges, setNodes, setEdges, fitView, initialLayoutFinished]
  );

  useEffect(() => {
    if (nodesInitialized) {
      onLayout("TB");
    }
  }, [nodesInitialized]);

  return (
    <div style={{ width: 1000, height: 1000, opacity }}>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        fitView
      >
        <Panel position="top-right">
          <button onClick={() => onLayout("TB")}>vertical layout</button>
          <button onClick={() => onLayout("LR")}>horizontal layout</button>
        </Panel>
      </ReactFlow>
    </div>
  );
};

export default ReactLayoutFlow;
```

There are still probably better solutions out there

**Comment by sontx** [comment]
Dagre works well for top-level nodes, so my approach is to perform the layout for each group (focusing on the top-level nodes in each group) separately:
1. Layout each group (subflow) from the deepest to the shallowest, and center each subflow within its parent.
3. After layout, the order of nodes might change, so we need to ensure that parent nodes appear before their children.

With some help from ChatGPT, the final code seems to work for me 😁

![image](https://github.com/user-attachments/assets/c8b2b0bf-8520-4692-9982-3f620c4654c2)

**Comment by ckpearson** [comment]
Unsure if it's been mentioned here but Dagre has an open issue (https://github.com/dagrejs/dagre/issues/258) as it appears there's no way to request a layout pass while "pinning" specific nodes to not move.
