### ISSUE TITLE
Problem on edge select

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1114]
Hello, I'm trying to select this stepEdge but is so tiny that makes it hard to do, how can I put a padding or something like this to increase the "selection" box?

![image](https://user-images.githubusercontent.com/36650520/115571464-6566e100-a295-11eb-944d-4dd8b5158772.png)

**Comment by moklick** [comment]
I would like to have an invisible edge below that is a bit thicker. I will put it on my list but unfortunately my resources are a bit limited these days.

**Comment by CamboimGabriel** [comment]
is there no other way to do this besides add a new component?

**Comment by clementloridan** [comment]
No but it's easy to do this if your create your custom link:
Cf: https://reactflow.dev/docs/api/edge-types/

```
<path
  id={id}
  strokeLinejoin="round"
  style={{
      ...style,
      stroke: 'red',
      strokeWidth: '4px',
      fill: 'none',
  }}
  d={edgePath}
  markerStart={markerStart}
  markerEnd={markerEnd}
/>
<path
    id={id}
    strokeLinejoin="round"
    style={{
        ...style,
        stroke: 'transparent',
        strokeWidth: `${24 / zoom}px`,    //  Here, I custom the size of line with the zoom relation
    }}
    className="react-flow__edge-path"
    d={edgePath}
/>

**Comment by CamboimGabriel** [comment]
@clementloridan I tried this but when I click on it does not select the right edge, what can I do?

**Comment by CamboimGabriel** [comment]
@clementloridan It works but Sometimes does not, theres something am I missing?

**Comment by clementloridan** [comment]
@CamboimGabriel Can you share some code (codesandbox or repo)?

**Comment by CamboimGabriel** [comment]
![image](https://user-images.githubusercontent.com/36650520/115962048-c38f0080-a4ef-11eb-9633-65d0a3c71e8e.png)
https://github.com/CamboimGabriel/frontend-movi Here it is @clementloridan  check on components -> flowComponents -> CustomEdgeWithoutLabel

Its working but everytime I need to click more than one time to really select it

**Comment by CamboimGabriel** [comment]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/36650520/115973620-d83db980-a52c-11eb-8976-4f7708b70ca5.gif)

@clementloridan with 50px stroke-width ghost edge

**Comment by NielXu** [comment]
@CamboimGabriel  I think the problem is that the edge is animated. Try to update the style of the ghost edge:

```javascript
      <path
        id={id}
        strokeLinejoin="round"
        style={{
            ...style,
            strokeDasharray: 0,    // <--- This line
            stroke: 'transparent',
            strokeWidth: 25,
        }}
        className="react-flow__edge-path"
        d={edgePath}
      />
```

**Comment by CamboimGabriel** [comment]
@NielXu Thanks bro, thats it!!!
