### ISSUE TITLE
Minimap node style 

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1115]
Hello, I need to change the node style on minimap. I have these node shapes: 

![image](https://user-images.githubusercontent.com/36650520/115581948-db237a80-a29e-11eb-88bf-62f1393de0e1.png)

But on minimap they are with different shapes

![image](https://user-images.githubusercontent.com/36650520/115581974-e2e31f00-a29e-11eb-9890-8242b1572585.png)

When I checked the elements they are rendering by general shape

![image](https://user-images.githubusercontent.com/36650520/115582145-07d79200-a29f-11eb-9e9a-80c598560c90.png)

How can I change the node shape on minimap?

**Comment by moklick** [comment]
Not possible at the moment but I put it on the list.

**Comment by moklick** [comment]
Why did you close it? Is it solved for you?

**Comment by CamboimGabriel** [comment]
I closed cuz you said that is not possible atm, so I can just wait
