### ISSUE TITLE
Disable cmd + mouse wheel zoom / pan

### ISSUE THREAD

**Issue by elund121** [wbkd/react-flow#1117]
Is there a way to prevent the zoom / pan behavior when using `cmd + mouse wheel`? I looked around the interaction example https://reactflow.dev/examples/interaction/ but couldn't find what I was looking for.

**Comment by moklick** [comment]
Good point! I might need to update the example. We have a [`zoomActivationKeyCode` prop](https://reactflow.dev/docs/api/component-props/) which defaults to `Meta`. If you set it to `null` it should work.

**Comment by elund121** [comment]
> Good point! I might need to update the example. We have a [`zoomActivationKeyCode` prop](https://reactflow.dev/docs/api/component-props/) which defaults to `Meta`. If you set it to `null` it should work.

thank you so much, that did the trick! 

The typing lists it as `zoomActivationKeyCode?: KeyCode` so may be worth updating that to `zoomActivationKeyCode?: KeyCode | null` as well

**Comment by moklick** [comment]
good point! I will add that info.
