### ISSUE TITLE
moving an existing edge doesn't trigger proper events

### ISSUE THREAD

**Issue by obaid** [wbkd/react-flow#1120]
When moving an an Edge we don't get callbacks `onConnectStart` and `onConnectEnd`. These should be called or we should introduce new event callbacks to indicate that an edge is being dragged?

**Comment by moklick** [comment]
is `onEdgeUpdate` not enough in this case?

**Comment by obaid** [comment]
Not really. Since we have logic that depends on the other callbacks.

**Comment by moklick** [comment]
Ok, got it. So a `onEdgeUpdateStart` and may be `onEdgeUpdateEnd` would work?

**Comment by obaid** [comment]
That would be super!

**Comment by moklick** [comment]
do you really need the `onEdgeUpdateEnd` callback or could you handle the one in the `onEdgeUpdate` callback?

**Comment by obaid** [comment]
actually now that i think about it both `onEdgeUpdateEnd` and `onEdgeUpdate` would be the same. So just need `onEdgeUpdateStart`

**Comment by moklick** [comment]
That's what I thought too :) I will add the new handler.

**Comment by obaid** [comment]
Thanks @moklick

**Comment by moklick** [comment]
released in 9.5.4 :)

**Comment by nileshlande12** [comment]
@moklick - when we start edge drag and left in middle way without connecting to target, in such cases onEdgeUpdateEnd will also be helpful, in one of our use cases.

**Comment by moklick** [comment]
added `onEdgeUpdateEnd` in v9.6.0
