### ISSUE TITLE
Using onClick on EdgeText

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1121]
![image](https://user-images.githubusercontent.com/36650520/115965192-5040bb00-a4fe-11eb-8960-f82d8bc4d488.png)
I'm trying to click on the label. I cant click on the label (EdgeText) because the flow dashboard is above it, what can I do do resolve this?

Here is the problem, only when I put the cursor into specific position it works: 
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/36650520/115973046-96ab0f80-a528-11eb-9725-0c8e4e4f283d.gif)

Here is the code of the customEdge:
```
 <>
      <path
        id={id}
        style={
          selected === true
            ? {
                strokeWidth: 1.5,
                stroke: "blue",
              }
            : style
        }
        className="react-flow__edge-path"
        d={edgePath}
        markerEnd={markerEnd}
      />
      <EdgeText
        onClick={() => console.log("test")}
        x={center[0]}
        y={center[1]}
        label={data.text.toUpperCase()}
        labelStyle={labelStyle}
        labelShowBg={labelShowBg}
        labelBgStyle={labelBgStyle}
      />
    </>
```

**Comment by moklick** [comment]
thanks for the report! please check 9.5.3

**Comment by CamboimGabriel** [comment]
Working well, thanks!!
