### ISSUE TITLE
flow display centering problem

### ISSUE THREAD

**Issue by mwei2018** [wbkd/react-flow#1122]
The node in my flow is customized, but the component appears not in the center of the canvas, but in the upper left corner.
https://www.screencast.com/users/wybztn/folders/Default/media/ba8a27bc-4464-4bbc-b7ba-e286fdc9eab6

react-Flow:
![image](https://user-images.githubusercontent.com/2967082/115977787-b2a4c480-a5ad-11eb-95c7-9486c9453607.png)
My first node position x=250 
    {            
      id: '1',
        type: 'input',
        data: { label: 'An input node' },
       position: { x: 250, y: 10 },    
      }
I checked the display and found that the canvas size is as follows
![image](https://user-images.githubusercontent.com/2967082/115978512-7aec4b80-a5b2-11eb-9042-23575c910f6a.png)

How to set the center display when loading?
Can we set the defaultPosition, but how to get the center position of the canvas, I tested it is not the center of the screen.

**Comment by moklick** [comment]
Hey @mwei2018 

when you want to place a node in the center you need to use the `project` function to convert the screen coordinates to the internal coordinate system. 

1. Measure the size of the renderer via `getBoundingClientRect` for example
2. Put the center of the dimensions in the [project function](https://reactflow.dev/docs/api/hooks/). For a 1200x600px renderer: `const xy = project({ x: 600, y: 300 })` 
3. Use the `xy` position for your first node

**Comment by moklick** [comment]
Closed due to inactivity. Feel free to re-open if the issue still occurs.

**Comment by thisisclint21** [comment]
Is it possible to start the chart with nodes in the center?

**Comment by moklick** [comment]
@thisisclint21 that should be the case when you use the fitView prop https://reactflow.dev/docs/api/react-flow-props/#fitview

**Comment by SatbeerVocso** [comment]
How to make Reactflow Component in a center of page becz when If style like marginleft 50% whole parent component shift to left instead of only ReactFLow Component ? I want make it at center

**Comment by moklick** [comment]
@SatbeerVocso please provide a codesandbox for this: https://new.reactflow.dev/react-js

**Comment by Steven-Low** [comment]
**YA 2024, V12**
To position a node in center of the canvas:
1) first you need to get the browser screen width and height.
2) then use the screenToFlowPosition module from the useReactFlow() to get the flow coordinates

```
const {x, y, } = screenToFlowPosition({x:window.innerWidth/2, y:window.innerHeight/2});
```
