### ISSUE TITLE
Nodes automatic hints about alignment with other nodes.

### ISSUE THREAD

**Issue by IOR88** [wbkd/react-flow#1124]
Hi wbkd team,

First of all really thanks for this great library, Your documentation is very helpful.
I have a question we would like to achieve effect of automatic hints about alignment as You can see in https://app.diagrams.net/.

When You move node around it shows You a lines how You can align active node with other nodes. I am wondering if it will be difficult to add to the react-flow ? Maybe You have some advises where to have a look on in library ? Or what would be the best place to add this feature to library ?

Best,
Igor

**Comment by shemayas** [comment]
Would be nice to have this feature in the library
