### ISSUE TITLE
Undo and Redo operations with keyboard shortcuts

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1127]
How can I implement this?

**Comment by leejustin** [comment]
I think it's important to consider what is an "undoable" and "redoable" operation. Should you be able to undo a node drag? Or is it only for node/edge creation and deletion? The scope of what you want to be able to handle will increase the complexity.

There's no easy way to set this up out-of-the-box and I imagine that the complexity depends on how you set up your use case.

As an example, I have data defined as an `Array` similar to the example here: https://reactflow.dev/docs/getting-started/ . If I wanted to set up undo and redo operations, I'd possibly consider setting up a nested array and a pointer to the active set of nodes and edges to render.

**Comment by moklick** [comment]
I will close this since not an issue with the library. Thanks @leejustin for your input here 👍
