### ISSUE TITLE
OnEdgeLabelDoubleClick ?

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1137]
I need to call a function from the react component when double click on label, I cant export that function to use on EdgeText because its inside a react component and I need to use the setStates of that component, is it possible to implement something like this prop to place on reactflow component like:

`<ReactFlow  onEdgeLabelDoubleClick={(edge) => myfunction(edge)}  />`

**Comment by moklick** [comment]
We will not add this function. We don't have the information at the place where we render the `EdgeText`. I don't want to pass more information down to that component. I am sure there is a way with a custom edge somehow.
