### ISSUE TITLE
Possible to apply smooth step to connections during creation?

### ISSUE THREAD

**Issue by TamjidTayeb** [wbkd/react-flow#1144]
When forming connections between nodes, the node does not have the 'type' I have applied to it

EG: My connection has type smooth step but while I am making the connection it doesn't have this styling applied to it:
![image](https://user-images.githubusercontent.com/38994890/116325981-c0a15200-a806-11eb-9d13-e96cf89ccd01.png)

Is it possible to make the connection have this type applied to it while dragging to create a new connection too ?

**Comment by moklick** [comment]
We have a `connectionLineType` option https://reactflow.dev/docs/api/component-props/

**Comment by TamjidTayeb** [comment]
thanks :)
