### ISSUE TITLE
draggable content within a node. 

### ISSUE THREAD

**Issue by nicojochnick** [wbkd/react-flow#1145]
Hi! Thanks for this amazing library.

I'm building a list with draggable items inside a node. The dragging works, but I get this strange behavior (shown below) where the internal item being dragged and the pointer aren't aligned. Seems that there is some issue where the board is interfering with the cursor position when dragging something inside a node. 

The problem persists with `className = {'nodrag'} `and gets worse the further the node is from the top left of the viewport.

<img width="789" alt="Screen Shot 2021-04-27 at 8 07 35 PM" src="https://user-images.githubusercontent.com/32424438/116327447-c78f7c80-a794-11eb-8d5b-4c07fbe064a4.png">

**Comment by moklick** [comment]
Hey @nicojochnick 

It's good that you are already using the `nodrag` class but I need to see your code to understand the issue here. Maybe it's on your side maybe react-flow is doing strange things.. can you share a sandbox or a repo with me?

**Comment by moklick** [comment]
Closed due to inactivity. Feel free to re-open if the issue still occurs.
