### ISSUE TITLE
add onEdgeClick prop to ReactFlow component

### ISSUE THREAD

**Issue by TamjidTayeb** [wbkd/react-flow#1146]
Hello,
Edges by default have an onClick prop which is how it is set to 'selected' but this prop isn't exposed to the ReactFlow component.

https://github.com/wbkd/react-flow/blob/6b6c85fe457f1a60850264a37d310d8da33c8a34/src/components/Edges/wrapEdge.tsx

 Can you please add this prop to the ReactFlow component so that we can handle when user clicks on an edge?

thanks a lot

**Comment by moklick** [comment]
It's the `onElementClick` option. It triggers for nodes and edges.
