### ISSUE TITLE
Crashes on iPad (Chrome and Safari)

### ISSUE THREAD

**Issue by obsidiandevel** [wbkd/react-flow#1148]
Hi,

When i try using the library, the site simply freezes up. https://reactflow.dev does the same. Seems pretty serious; happy to provide more information. How can i be the only person experiencing this?

**Comment by moklick** [comment]
Which iPad and which iOS version are you using? I am testing the lib on several phones including an iPhone without issues but i don't have an iPad.

**Comment by obsidiandevel** [comment]
Thanks for the instant response.

# iPad info

- Software Version: 13.3.1 (17D50) (not from self: apparently this is the safari version)
- Model Name: iPad Pro (12.9-inch) (3rd Generation)
- Model Number: MTJP2B/A

Chrome version: 87.0.4280.163

**Comment by leejustin** [comment]
I'm running iPad 14.4 on an iPad Pro 11 inch. The examples run flawlessly. I use this library for a mobile-friendly website and I test occasionally on my iPad. I have never encountered the issues that you are describing.

**Comment by moklick** [comment]
3rd generation iPad is 8 years old.. but should work anyway

**Comment by moklick** [comment]
Ahh it's a pro.. then it's really weird that it's not working. I will see if I can find one.

**Comment by obsidiandevel** [comment]
Could this be it:

## useResizeHandler.ts

```
import { useEffect, MutableRefObject } from 'react';
import { useStoreActions } from '../store/hooks';

import { getDimensions } from '../utils';

export default (rendererNode: MutableRefObject<HTMLDivElement | null>) => {
  const updateSize = useStoreActions((actions) => actions.updateSize);

  useEffect(() => {
    let resizeObserver: ResizeObserver;

    const updateDimensions = () => {
      if (!rendererNode.current) {
        return;
      }
...
```

**Comment by obsidiandevel** [comment]
So, if I rip the ResizeObserver code out of ReactFlow.esm.js the example loads, however the flow charts don't.

**Comment by obsidiandevel** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver


<img width="1053" alt="image" src="https://user-images.githubusercontent.com/79421241/118230444-463c2780-b4c0-11eb-8bd9-c25fab8f90f8.png">


Super stranger since the version of Safari I'm using is greater than this. Also doesn't explain why it doesn't work in chrome on OSX iPad.

**Comment by obsidiandevel** [comment]
OK so seems like I'm getting somewhere:

```
npm install resize-observer-polyfill --save-dev
```

Then I added the following to ReactFlow.esm.js

```
import ResizeObserver from 'resize-observer-polyfill';
```

Is ReactFlow.esm.js a source or intermediary file?

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/79421241/118231203-5a345900-b4c1-11eb-9cec-b4ddd314b844.png">

Boom. Fixes the issue, though now need to find the 'proper' fix, push it to a branch etc.

**Comment by obsidiandevel** [comment]
Yes I'm an idiot, that's the 'dist' directory. So here's the fix:

```
npm install resize-observer-polyfill --save-dev
```

Then add:

```
import ResizeObserver from 'resize-observer-polyfill';
```

To:

`src/container/NodeRenderer/index.tsx`
`src/hooks/useResizeHandler.ts`
`src/types/index.ts`

Could this get added quickly or would you like a PR?

**Comment by obsidiandevel** [comment]
https://github.com/obsidiandevel/react-flow/commit/eba2e14b0b5d5f026e8dfd4bf652c35e3f4c065c

**Comment by moklick** [comment]
We will not add the polyfill to the library. If you need it, you need to add it by yourself. Thanks for the info @obsidiandevel!

**Comment by obsidiandevel** [comment]
OK. How do i use my fork for this? https://github.com/obsidiandevel/react-flow when i try using this fork as an NPM dep it doesn't work. Are there build procedures i need to follow instead?

I respect you don't want to use Polyfill, but then i'll need to drop this library, sadly since it's really good.

Thanks,

Obsidian.
