### ISSUE TITLE
Layouting Callback Hook?

### ISSUE THREAD

**Issue by kmcentush** [wbkd/react-flow#1153]
Love the project! One small headache I'm dealing with is using the `fitView()` function after I update the layout of some nodes. These make their way into the react-flow via the `elements` arg. I believe you've mentioned in the past that the layouting is asynchronous, so the `fitView()` would have to be called after that for it to have any effect. 

Is there a way to hook into a callback as part of the layouting? Even whenever the flow updates would also work for my use case. I could use that to then fit the view whenever I wanted based on some component state.

**Comment by likelion** [comment]
Should it be a hook at the end of UPDATE_NODE_DIMENSIONS in react-flow/src/store/reducer.ts ?

**Comment by moklick** [comment]
I want this too! PRs are highly appreciated :) If anyone has a good idea where to put this.

**Comment by moklick** [comment]
This will be fixed in v10.
