### ISSUE TITLE
Add edge when mouse up anywhere on node

### ISSUE THREAD

**Issue by coliphant-varicent** [wbkd/react-flow#1154]
Two nodes. I try to add an edge by mouse down on a connector point. I want to finish the add with a mouse up anywhere on the second node. In the demo, it only works when I mouse up over the second node's connection point.

**Comment by moklick** [comment]
You could try to make the source handle the same size as the node by default and then show the target handle when a user starts a connection. I am not 100% sure if this would work.. It's just an idea.
