### ISSUE TITLE
Customize connection handles to make drag / drop easier?

### ISSUE THREAD

**Issue by sgrove** [wbkd/react-flow#1155]
Right now we're having some trouble with the drop zones (and initial drag target) being so small - is there some way to customize the css / component to make the circles/zones larger?

**Comment by ralppppy** [comment]
Yes how can we do this?

**Comment by moklick** [comment]
You can use regular CSS/ pass a style prop/ use styled components to style the handles. All used class names are listed in the [theming section](https://reactflow.dev/docs/theming/). The handles have the class name `react-flow__handle`.

**Comment by vallode** [comment]
Sorry to revive this, I find resizing the circles/zones themselves to be unsatisfactory and would much rather be able to denote either half of the node or all of it, to be the drop zone for the connection.

I've not yet been able to get this to work, do you think this would be possible currently or are we looking at some sort of PR?

**Comment by jonra1993** [comment]
If anyone is facing a similar issue I checked @moklick suggestion and app and I refactor it in this way. "styled-components" did the magic

![image](https://user-images.githubusercontent.com/23468720/129086766-ee07647c-09db-4a50-b35f-a4a03a66ff17.png)


`
import styled from 'styled-components';
import { Handle, Position, NodeProps, Connection, Edge, HandleType } from 'react-flow-renderer';

const CustomBottomHandle = styled(Handle)`
&& {
  left: -1px;
  bottom: 0px;
  transform: translateY(0px);
  background: #EF8354;
  border-radius: 0px 0px 10px 10px;
  height: 15px;
  width: calc(100% + 2px);
  &:hover {
    background: #ed956f;
  }
}`;

`

**Comment by zyaanbookee** [comment]
Is it possible to make whole node as drop area?

**Comment by utkuturunc** [comment]
@zyaanbookee 

```typescript
  const onConnectStart: OnConnectStart = useCallback(() => {
    setConnectionInProgress(true);
  }, [setConnectionInProgress]);

  const onConnectEnd: OnConnectEnd = useCallback(() => {
    setConnectionInProgress(false);
  }, [setConnectionInProgress]);
```

```
      <ReactFlow
        onConnectStart={onConnectStart}
        onConnectEnd={onConnectEnd}
```

then where you create the handle

```
<div style={{position: 'relative'}}>
   <Handle style={{ top: 0, left: 0, right: 0, bottom: 0, zIndex: connectionInProgress ? 1000 : -1 }} ...
</div>
```

**Comment by Canopix** [comment]
I've just created a custom handle that adds four invisible handles, one on each side. You can customize the color or maybe use a CSS pattern to indicate an area for performing an edge action.

In this way, it remains invisible, allowing you to perform an edge action from any node edge.
![2023-09-28 16 09 13](https://github.com/wbkd/react-flow/assets/4460417/0c75fb91-d41b-451b-82a2-26631339248b)



```
import React from 'react';
import { Handle, Position } from 'reactflow';

const CustomHandle = ({
	id,
	type,
	position,
}: {
	id: string;
	type: string;
	position: Position.Left | Position.Top | Position.Right | Position.Bottom;
}) => {
	const handleStyle: {
		left?: string;
		top?: string;
		transform?: string;
		borderWidth?: string;
		width?: string;
		height?: string;
		right?: string;
		borderRadius?: string;
		bottom?: string;
		background?: string;
	} = {
		transform: 'translateY(0px)',
		borderWidth: '0px',
		width: '15px',
		height: 'calc(100% + 2px)',
		background: 'none',
	};

	switch (position) {
		case Position.Right:
			handleStyle.right = '-1px';
			handleStyle.top = '0px';
			handleStyle.height = 'calc(100% + 2px)';
			handleStyle.width = '15px';
			handleStyle.borderRadius = '10px 10px 0px 0px';
			break;
		case Position.Bottom:
			handleStyle.left = '-1px';
			handleStyle.bottom = '-2px';
			handleStyle.width = 'calc(100% + 2px)';
			handleStyle.height = '15px';
			handleStyle.borderRadius = '0px 0px 10px 10px';
			break;
		case Position.Top:
			handleStyle.left = '-1px';
			handleStyle.top = '0px';
			handleStyle.width = 'calc(100% + 2px)';
			handleStyle.height = '15px';
			handleStyle.borderRadius = '10px 10px 0px 0px';
			break;
		case Position.Left:
			handleStyle.left = '-1px';
			handleStyle.top = '0px';
			handleStyle.width = '15px';
			handleStyle.height = 'calc(100% + 2px)';
			handleStyle.borderRadius = '10px 0px 0px 10px';
			break;
		default:
			break;
	}

	return (
		<Handle
			id={id}
			type={type === 'XXXX' ? 'source' : 'target'}
			position={position}
			style={handleStyle}
		/>
	);
};

export default CustomHandle;
```
