### ISSUE TITLE
Need to have onEdgeUpdateEnd

### ISSUE THREAD

**Issue by nileshlande12** [wbkd/react-flow#1157]
I'm really happy after seeing new features introduce in 9.5.4, i e. onEdgeUpdateStart,
But seems like this is not sufficient, in my use case i will need to have onEdgeUpdateEnd as well,
My Case: onEdgeUpdateStart i'm enabling one flag, which start showing target location on node, but if i left dragging in middle without connecting to target then i also need to reset that flag to hide target location.

Can you please provide this feature as well, i will be really thankful.

**Comment by Analog-Mafia** [comment]
Indeed!

 We have functionalities like 
onConnect 
onConnectStart 
onConnectEnd 
onEdgeUpdateStart 
onEdgeUpdate 

However, onEdgeUpdateEnd is missing.  I think having onEdgeUpdateEnd would be really helpful

Great library btw!

**Comment by VARUNATTARDE** [comment]
Really happy for using this library. Looking for the similar kind of feature i.e. onEdgeUpdateEnd .
Thankyou.

**Comment by moklick** [comment]
yep, we will add that handler.

**Comment by saschahofmann** [comment]
Would it be possible to fire onEdgeUpdate even when the the edge hasn't been dragged on a new handle? 

I'd like to remove an edge by dragging it to empty space!

**Comment by moklick** [comment]
added in v9.6.0
