### ISSUE TITLE
My problem is that tooltip of bootstrap does not show on react flow library? May be somebody know how to solve this problem?

### ISSUE THREAD

**Issue by KirillAleshkin** [wbkd/react-flow#1166]

**Comment by moklick** [comment]
How did you try to add it? It should work with a custom node. Please post a codesand box or some code. Otherwise it's hard to say.

**Comment by KirillAleshkin** [comment]
<SimpleTooltip content={data.tooltip}>
  <CurrentStyle>
    <CiNumber />
  </CurrentStyle>
</SimpleTooltip>

--

**Comment by KirillAleshkin** [comment]
--
may by do you have same examples or link where i can to look how do u use
it in your library?

**Comment by moklick** [comment]
This is very specific. I don't know an example that uses React Bootstrap Tooltip with React Flow.. 
Your code example is not sufficient. What is SimpleTooltip for a component?

**Comment by KirillAleshkin** [comment]
it was pointer events:none
