### ISSUE TITLE
Drag and drop multiple elements

### ISSUE THREAD

**Issue by estellegresillon** [wbkd/react-flow#1167]
Using [this example](https://reactflow.dev/examples/drag-and-drop/) from your doc, is it possible to drag and drop multiple nodes in the workspace ? Or is that a feature that I have to code from scratch ?

Thanks by advance

**Comment by moklick** [comment]
Hey! There is no drag and drop function built in. Single dnd and multi dnd needs to implemented by yourself but it should be possible :)
