### ISSUE TITLE
Flow doesn't re-render on elements state change

### ISSUE THREAD

**Issue by quocanhbk** [wbkd/react-flow#1168]
`const Body = () => {
    
    const addChild = (parentId) => {
        setParent(parentId)
        setPopup(true)
    }
    let {chart, insertNode} = useChart(departmentData, addChild)
    const onLoad = (reactFlowInstance) => reactFlowInstance.setTransform({x: 10, y: 10, zoom: 0.8})
    const [popup, setPopup] = useState(false)
    const [parent, setParent] = useState()
    const reff = useClickOutside(() => setPopup(false))
    console.log("Body render")
    
    return (
        <Container>
            <FlowContainer>
                {chart.map(item => item.id).join(" ")}
                <FlowBorder>
                    <ReactFlow 
                        onLoad={onLoad}
                        elements={chart} 
                        nodesDraggable={true} 
                        nodesConnectable={false}
                        nodeTypes={{department: DepartmentNode}}
                        >
                    </ReactFlow>
                    {popup && <PopupContainer>
                        <AddChildForm reff={reff} chart={chart} parentId={parent} onAdd={(data) => {setPopup(false); insertNode(data)}}/>
                    </PopupContainer>}
                </FlowBorder>
            </FlowContainer>
        </Container>
    )
}`
"chart" is a React state returned from a custom hook, basically I'm trying to add new node to chart through a form. The text below "FlowContainer" renders fine but "ReactFlow" stays the same, the same nodes and edges from initial.

**Comment by moklick** [comment]
I would need to see how you are altering the elements array. Can you paste this code here, too?

**Comment by quocanhbk** [comment]
Thanks for replying early!
Here's the rest of my code
**The Hook**
`
import { useRef, useState } from "react"
import Flow from '../drawFlow'

const useChart = (initData, onAddClick) => {
    let shapedData = initData.map(item => ({
        id: item.id,
        data: {
            name: item.data.name,
            manager: item.data.manager,
            jobTitle: item.data.jobTitle,
            onAddClick: onAddClick
        },
        parentId: item.parentId
    }))
    const chartRef = useRef(new Flow(shapedData))
    const [chart, setChart] = useState(chartRef.current.nodes)

    const insertNode = (data) => {
        chartRef.current.insertNode(data)
        setChart(chartRef.current.nodes)
    }
    return {chart, insertNode}
}

export default useChart
`

**The Flow Class**
`
class Flow {
    constructor(data) {
        this.nodes = []
        this.drawNode(data)
    }

    removeNode(nodeId) {
        this.nodes = this.nodes.filter(node => node.id === nodeId)
    }

    getNode(nodeId) {
        return this.nodes.find(node => node.id === nodeId)
    }

    getParentNode(nodeId) {
        return this.nodes.find(node => node.id === this.getNode(nodeId).parentId)
    }

    moveDownNode(nodeId) {
        this.getNode(nodeId).position.y += 120
    }

    haveChildren(nodeId) {
        return this.nodes.filter(node => node.parentId === nodeId).length > 0
    }
    getChildrenNode(nodeId) {
        return this.nodes.filter(node => node.parentId === nodeId)
    }

    getHeight(nodeId) {
        let height = this.haveChildren(nodeId) ? this.getChildrenNode(nodeId).length + this.getChildrenNode(nodeId).reduce((pre, cur) => pre + this.getHeight(cur), 0) : 0
        return height
    }
    getAncestorPath(nodeId) {
        let arr = [nodeId]
        let curNode = this.nodes.find(node => node.id === nodeId)
        while (curNode.parentId !== null) {
            let parId = curNode.parentId
            arr.push(parId)
            curNode = this.nodes.find(node => node.id === parId)
        }
        return arr
    }
    insertNode(node) {
        let parentNode = this.getNode(node.parentId)
        
        this.nodes.filter(n => n.type === "department").filter(n => n.position.y > parentNode.position.y && !this.getAncestorPath(n.id).includes(node.parentId)).forEach(n => {
            this.moveDownNode(n.id)
        });

        let height = this.getHeight(parentNode.id)
        this.nodes.push({
            id: node.id,
            type: "department",
            data: node.data,
            position: {x: parentNode.position.x + 200, y: parentNode.position.y + (height + 1) * 120},
            parentId: node.parentId
        }, {
            id: "e" + node.id,
            source: node.parentId,
            target: node.id,
            type: "step"
        })
    }
    drawNode(data) {
        let rootNode = data.find(node => node.parentId === null)
        this.nodes.push({
            id: rootNode.id,
            type: "department",
            data: rootNode.data,
            position: {x: 0, y: 0},
            parentId: null
        })
        let nodeDataQueue = data.filter(node => node.parentId !== null)
        while (nodeDataQueue.length > 0) {
            let curNodeData = nodeDataQueue.pop()
            //check if parent node is drawn. if true, draw the node
            if (this.nodes.map(node => node.id).includes(curNodeData.parentId)){
                this.insertNode(curNodeData)
            }               
            else
                nodeDataQueue.unshift(curNodeData)
        }
    }
}

export default Flow
`

After filling the form, I run the "insertNode" function in the hook

**Comment by quocanhbk** [comment]
Thanks for replying early! Here's the rest of my code

**The hook**
`import { useRef, useState } from "react"
import Flow from '../drawFlow'

const useChart = (initData, onAddClick) => {
    let shapedData = initData.map(item => ({
        id: item.id,
        data: {
            name: item.data.name,
            manager: item.data.manager,
            jobTitle: item.data.jobTitle,
            onAddClick: onAddClick
        },
        parentId: item.parentId
    }))
    const chartRef = useRef(new Flow(shapedData))
    const [chart, setChart] = useState(chartRef.current.nodes)

    const insertNode = (data) => {
        chartRef.current.insertNode(data)
        setChart(chartRef.current.nodes)
    }
    return {chart, insertNode}
}

export default useChart
`

**The Flow class**
`class Flow {
    constructor(data) {
        this.nodes = []
        this.drawNode(data)
    }

    removeNode(nodeId) {
        this.nodes = this.nodes.filter(node => node.id === nodeId)
    }

    getNode(nodeId) {
        return this.nodes.find(node => node.id === nodeId)
    }

    getParentNode(nodeId) {
        return this.nodes.find(node => node.id === this.getNode(nodeId).parentId)
    }

    moveDownNode(nodeId) {
        this.getNode(nodeId).position.y += 120
    }

    haveChildren(nodeId) {
        return this.nodes.filter(node => node.parentId === nodeId).length > 0
    }
    getChildrenNode(nodeId) {
        return this.nodes.filter(node => node.parentId === nodeId)
    }

    getHeight(nodeId) {
        let height = this.haveChildren(nodeId) ? this.getChildrenNode(nodeId).length + this.getChildrenNode(nodeId).reduce((pre, cur) => pre + this.getHeight(cur), 0) : 0
        return height
    }
    getAncestorPath(nodeId) {
        let arr = [nodeId]
        let curNode = this.nodes.find(node => node.id === nodeId)
        while (curNode.parentId !== null) {
            let parId = curNode.parentId
            arr.push(parId)
            curNode = this.nodes.find(node => node.id === parId)
        }
        return arr
    }
    insertNode(node) {
        let parentNode = this.getNode(node.parentId)
        
        this.nodes.filter(n => n.type === "department").filter(n => n.position.y > parentNode.position.y && !this.getAncestorPath(n.id).includes(node.parentId)).forEach(n => {
            this.moveDownNode(n.id)
        });

        let height = this.getHeight(parentNode.id)
        this.nodes.push({
            id: node.id,
            type: "department",
            data: node.data,
            position: {x: parentNode.position.x + 200, y: parentNode.position.y + (height + 1) * 120},
            parentId: node.parentId
        }, {
            id: "e" + node.id,
            source: node.parentId,
            target: node.id,
            type: "step"
        })
    }
    drawNode(data) {
        let rootNode = data.find(node => node.parentId === null)
        this.nodes.push({
            id: rootNode.id,
            type: "department",
            data: rootNode.data,
            position: {x: 0, y: 0},
            parentId: null
        })
        let nodeDataQueue = data.filter(node => node.parentId !== null)
        while (nodeDataQueue.length > 0) {
            let curNodeData = nodeDataQueue.pop()
            //check if parent node is drawn. if true, draw the node
            if (this.nodes.map(node => node.id).includes(curNodeData.parentId)){
                this.insertNode(curNodeData)
            }               
            else
                nodeDataQueue.unshift(curNodeData)
        }
    }
}

export default Flow

`

**Comment by quocanhbk** [comment]
Thanks for replying early! Here's the rest of my code

**The hook**
```
import { useRef, useState } from "react"
import Flow from '../drawFlow'

const useChart = (initData, onAddClick) => {
    let shapedData = initData.map(item => ({
        id: item.id,
        data: {
            name: item.data.name,
            manager: item.data.manager,
            jobTitle: item.data.jobTitle,
            onAddClick: onAddClick
        },
        parentId: item.parentId
    }))
    const chartRef = useRef(new Flow(shapedData))
    const [chart, setChart] = useState(chartRef.current.nodes)

    const insertNode = (data) => {
        chartRef.current.insertNode(data)
        setChart(chartRef.current.nodes)
    }
    return {chart, insertNode}
}

export default useChart
```

**The Flow chart**
```
class Flow {
    constructor(data) {
        this.nodes = []
        this.drawNode(data)
    }

    removeNode(nodeId) {
        this.nodes = this.nodes.filter(node => node.id === nodeId)
    }

    getNode(nodeId) {
        return this.nodes.find(node => node.id === nodeId)
    }

    getParentNode(nodeId) {
        return this.nodes.find(node => node.id === this.getNode(nodeId).parentId)
    }

    moveDownNode(nodeId) {
        this.getNode(nodeId).position.y += 120
    }

    haveChildren(nodeId) {
        return this.nodes.filter(node => node.parentId === nodeId).length > 0
    }
    getChildrenNode(nodeId) {
        return this.nodes.filter(node => node.parentId === nodeId)
    }

    getHeight(nodeId) {
        let height = this.haveChildren(nodeId) ? this.getChildrenNode(nodeId).length + this.getChildrenNode(nodeId).reduce((pre, cur) => pre + this.getHeight(cur), 0) : 0
        return height
    }
    getAncestorPath(nodeId) {
        let arr = [nodeId]
        let curNode = this.nodes.find(node => node.id === nodeId)
        while (curNode.parentId !== null) {
            let parId = curNode.parentId
            arr.push(parId)
            curNode = this.nodes.find(node => node.id === parId)
        }
        return arr
    }
    insertNode(node) {
        let parentNode = this.getNode(node.parentId)
        
        this.nodes.filter(n => n.type === "department").filter(n => n.position.y > parentNode.position.y && !this.getAncestorPath(n.id).includes(node.parentId)).forEach(n => {
            this.moveDownNode(n.id)
        });

        let height = this.getHeight(parentNode.id)
        this.nodes.push({
            id: node.id,
            type: "department",
            data: node.data,
            position: {x: parentNode.position.x + 200, y: parentNode.position.y + (height + 1) * 120},
            parentId: node.parentId
        }, {
            id: "e" + node.id,
            source: node.parentId,
            target: node.id,
            type: "step"
        })
    }
    drawNode(data) {
        let rootNode = data.find(node => node.parentId === null)
        this.nodes.push({
            id: rootNode.id,
            type: "department",
            data: rootNode.data,
            position: {x: 0, y: 0},
            parentId: null
        })
        let nodeDataQueue = data.filter(node => node.parentId !== null)
        while (nodeDataQueue.length > 0) {
            let curNodeData = nodeDataQueue.pop()
            //check if parent node is drawn. if true, draw the node
            if (this.nodes.map(node => node.id).includes(curNodeData.parentId)){
                this.insertNode(curNodeData)
            }               
            else
                nodeDataQueue.unshift(curNodeData)
        }
    }
}

export default Flow
```

**Comment by moklick** [comment]
it seems that the `useChart` creates a new `chartRef` with the same `shapedData`. This is not a react-flow issue but some issue with your `useChart` code, I guess.

**Comment by quocanhbk** [comment]
Can you take your time and tell me what's wrong with my code ? As I see, `shapedData` is only used once to initialize a class instance

**Comment by moklick** [comment]
You are right.. This should be OK. Are you using strings for node and edge ids?

**Comment by quocanhbk** [comment]
Yes. Here is the initial array
![image](https://user-images.githubusercontent.com/64638082/117162230-73c5fa00-ad77-11eb-9fcc-bbaccd8c5e4f.png)

**Comment by Analog-Mafia** [comment]
Hey @moklick . I',m facing a similar issue. When I modiy elements, some elements like edges are rendered visible only when I zoom into the Flow.

**Comment by nileshlande12** [comment]
Hi @moklick - With new version I'm also facing similar issue, whenever I'm droping node or connecting edge sometimes it failed to render edge, and it renders as soon as if I do any activity on canvas (zooming or paning), is there any workaround for now ?

**Comment by quocanhbk** [comment]
when I replace `setChart(chartRef.current.nodes)` with `setChart(chartRef.current.nodes.slice(0, chartRef.current.nodes.length))`, it works. Now I have another problem is that when I programmatically change the position of a node, it stands still.

**Comment by quocanhbk** [comment]
My workaround for this problem!
Change from
```
setChart(chartRef.current.nodes)
```
to
```
setChart([])
setTimeout(() => {
    setChart(chartRef.current.nodes)
}, 1);
}
```

**Comment by maxsteenbergen** [comment]
I'm facing the same issue and @quocanhbk's solution using the `setTimeout` of 1 or 0 works, but does cause an unpretty flash. I'm aware of having to notify React-Flow of updates by passing a new object, but I believe I'm doing that? 

More precisely: this doesn't work: 

```js
const onPaneClick = () => {
  let mutatedChartNodes = [...ActiveChart.nodes]

  mutatedChartNodes.forEach( node => {
    node.position.x = node.position.x + 50
  })
    
  setActiveChart({...ActiveChart, nodes: mutatedChartNodes })
}
```

but this does:

```js
const onPaneClick = () => {
  let mutatedChartNodes = [...ActiveChart.nodes]
  
  setActiveChart({nodes: [], edges: []})

  setTimeout( () => {
    mutatedChartNodes.forEach( node => {
      node.position.x = node.position.x + 50
    })
    setActiveChart({...ActiveChart, nodes: mutatedChartNodes })
  }, 0)
}
```

**Comment by moklick** [comment]
try to create a new object:

```js 
const onPaneClick = () => {
  const mutatedChartNodes = ActiveChart.nodes.map(node => {
    node.position = {
      x: node.position.x + 50,
      y: node.position.y
    };

   return node;
  });

  setActiveChart({...ActiveChart, nodes: mutatedChartNodes })
}
```

**Comment by maxsteenbergen** [comment]
@moklick Thanks! That did work, though I don't understand why my original code wouldn't create a new object.

**Comment by moklick** [comment]
You are just updating the position object but don't create a new one. At the end it's just a bad API on our site and a bad DX .. It's not your fault.

**Comment by baptisteArno** [comment]
Hey friends, I think I have the same issue but even if I create a new array, it won't update the position of my nodes:

```tsx
export const LogicFlow = () => {
  const { steps } = useStoreState((state) => state.chatbot.value!);
  const [elements, setElements] = useState(
    getLayoutedElements(parseElements(steps))
  );

  useEffect(() => {
    setElements([...getLayoutedElements(parseElements(steps))]);
  }, [steps]);

  return (
    <Flex h="screen" flex="1" pt="57px" bgColor="blue.500">
      <ReactFlow elements={elements}>
        <Controls />
        <Background color="#aaa" gap={16} />
      </ReactFlow>
    </Flex>
  );
};
```

I'm computing the layout automatically with `getLayoutedElements` so I'm only changing node positions. Could this be the issue? How can I force the re-rendering of the Graph?

**Comment by moklick** [comment]
Hey @baptisteArno 

you are creating a new array but no new position objects. You need to do something like:

```js 
node.position = {
 x: 123,
 y: 456 
}
```

inside your `getLayoutedElements` function.

**Comment by baptisteArno** [comment]
Well the `getLayoutedElements` create those new positions:

```tsx
const getLayoutedElements = (elements: FlowElement[]) => {
  dagreGraph.setGraph({ rankdir: "TB" });
  const width = 200;
  const height = 100;

  elements.forEach((el) => {
    if (isNode(el)) {
      dagreGraph.setNode(el.id, {
        width,
        height,
      });
    } else {
      dagreGraph.setEdge(el.source, el.target);
    }
  });

  dagre.layout(dagreGraph);

  return elements.map((el) => {
    if (isNode(el)) {
      const nodeWithPosition = dagreGraph.node(el.id);
      el.targetPosition = Position.Top;
      el.sourcePosition = Position.Bottom;
      el.position = {
        x: nodeWithPosition.x - width / 2 + Math.random() / 1000,
        y: nodeWithPosition.y - height / 2,
      };
    }
    return el;
  });
};
```

**Comment by moklick** [comment]
ok, this looks good.

**Comment by baptisteArno** [comment]
Fixed by initializing dagreGraph on each function call:
```jsx
const getLayoutedElements = (elements: FlowElement[]) => {
  const dagreGraph = new dagre.graphlib.Graph();
  dagreGraph.setDefaultEdgeLabel(() => ({}));
  dagreGraph.setGraph({ rankdir: "TB" });
  const width = 200;
  const height = 100;
  [...]
};
```

**Comment by gaomAndximi** [comment]
> Fixed by initializing dagreGraph on each function call:
> 
> ```js
> const getLayoutedElements = (elements: FlowElement[]) => {
>   const dagreGraph = new dagre.graphlib.Graph();
>   dagreGraph.setDefaultEdgeLabel(() => ({}));
>   dagreGraph.setGraph({ rankdir: "TB" });
>   const width = 200;
>   const height = 100;
>   [...]
> };
> ```

it works！
