### ISSUE TITLE
How to get the position of the mouse using the graph coordinate system?

### ISSUE THREAD

**Issue by sztanko** [wbkd/react-flow#1176]
Thank you for your amazing library.

I am implementing a custom tree layout and  drag & drop functionality for the graph layout and I would like to get the position of mouse in terms the graph coordinate system for onMouseMove event (so I can determine the closest graph tree branch where the draggable element should potentially belong to)
Because of zoom and translate, `event.clientX - ref.current.getBoundingClientRect().x` wouldn't really work here.

Could you please advise on what would be the easiest way of retrieving those coordinates?

Thanks,

D.

**Comment by sztanko** [comment]
Actually, seems like I found the solution:

```const [instance, setInstance] = useState(null)
...
<ReactFlow
        const ref = useRef(null)
        ref={ref}
        elements={elements}
        onLoad={(instance) => {
          setInstance(instance)
          console.log(instance)
        }}
        onMouseMove={(event) => {
          const rect = ref.current.getBoundingClientRect()
          const pos = instance.project({ x: event.clientX - rect.x, y: event.clientY - rect.y })
         console.log(pos)  
       
        }}
      />
```

**Comment by moklick** [comment]
Yes. you can also use the `project` function of the [`useZoomPanHelper` hook ](https://reactflow.dev/docs/api/hooks/) if you don't want to use the instance function.
