### ISSUE TITLE
Error in ConnectionLine when trying to change the source handle on an edge that has a target that is an output type node

### ISSUE THREAD

**Issue by ImBaedin** [wbkd/react-flow#1177]
Example here: https://codesandbox.io/s/bold-breeze-nlg5s?file=/src/App.js

![image](https://user-images.githubusercontent.com/7637729/117340894-0e513680-ae67-11eb-9f86-975d836a4d34.png)

**Comment by sginn** [comment]
I ran into this problem as well.  The `updatable-edge` example reproduces the awkward positioning of a dragged edge, and if you change Node C to an "Output" node, you can recreate the crash

>  sourceNode.__rf.handleBounds[connectionHandleType] is null

If we change [this line](https://github.com/wbkd/react-flow/blob/2eea1c34a15a39ea37781c8e2f2d93b5d64d858f/src/components/Handle/handler.ts#L120) to the below, everything appears to work again:

```
const handleType = isTarget ? 'target' : 'source';
```

@moklick I was going to submit a PR for this change, but saw that change would likely regress https://github.com/wbkd/react-flow/issues/982

I'm not sure if there's an answer that gets us both issues...

**Comment by moklick** [comment]
I will take a look at this issue. Thanks for the input here!

**Comment by moklick** [comment]
Could you try v9.5.5 ?

**Comment by sginn** [comment]
This is great!  Thanks for the really fast turnaround!
The upgrade fixed the issue for us.
