### ISSUE TITLE
Feature Request - Add an onDisconnect function

### ISSUE THREAD

**Issue by thijsheijden** [wbkd/react-flow#1195]
Since there is a onConnect function, an onDisconnect function would be nice.

**Comment by moklick** [comment]
You can check this inside the `onRemoveElement` handler. When the passed element is an edge, the user disconnected it.

**Comment by g-a-v-i-n** [comment]
What happened to `onRemoveElement` ?

**Comment by bcakmakoglu** [comment]
@g-a-v-i-n 
There's a new handler for these events `onNodesChange` and `onEdgesChange` which you can listen to and filter the changes by type. For removals it's `type === 'remove'`

```jsx
<ReactFlow onNodesChange={(changes) => console.log(changes.filter(c => c.type === 'remove'))} ...>

**Comment by rickyzhangca** [comment]
I still suggest an `onDisconnect` function as `onConnect` is included in`<Handle />` API. It will be more consistent and intuitive. `onNodesChange` often requires more complicated logic to achieve the `onDisconnect` purpose. 
E.g. let a node react to the connection changes. `onConnect` does the half of job now, and an `onDisconnect` would do the other half in a cleaner fashion

**Comment by moklick** [comment]
We have an [`onEdgesDelete`](https://reactflow.dev/docs/api/react-flow-props/#onedgesdelete) callback. Isn't that the same thing?

**Comment by LucaLyon1** [comment]
Hey, just started using the library not too long ago. 
IMO, we should have a onDisconnect prop in the Handle component, the current onEdgesDelete forces you to move the connection logic to the parent component.
Having onDisconnect prop in the Handle would allow a custom node to handle its connection logic (such as this type of node only accept one connection, and the parent component doesn't have to know).

**Comment by bcakmakoglu** [comment]
@diamanthaxhimusa if you use the store function [`deleteElements`](https://reactflow.dev/api-reference/types/react-flow-instance#delete-elements) it will create a change that you can track.
