### ISSUE TITLE
Edge heads need to be responsive and customizable 

### ISSUE THREAD

**Issue by zoomKoding** [wbkd/react-flow#1198]
Hello! 
First of all, I want to say thank you for this awesome project!
It is very easy to use and customize!

I found some issues related to edge heads.
The issues are reflected in the image below.

![image](https://user-images.githubusercontent.com/36878344/118390921-9952dd80-b66c-11eb-8a36-b4b9e86df789.png)

As you can see, the edge is Bezier(default) type.
We want the edge head:
- to be rotated responsively to the angle of the edge end.
- to have the same color with the edge.

**Comment by zoomKoding** [comment]
![image](https://user-images.githubusercontent.com/36878344/118391326-af619d80-b66e-11eb-814f-0b38a70d6520.png)

I fixed the first issue with creating a function that can calculate the angle of the bezier edge end.
As each arrowed edge has its own angle value, I concluded that each edge needs to have its own marker defs. 


**If each edge has its own defs with the correct calculated angle and style information, the issues above could be solved.**

I wanted to write pull request for the responsive marker end, but it seems that `MarkerDefinitions` component is not very customizable and is only used globally.

Before going deep into the code, I needed your opinion for one defs for one arrowed edge.
If you like my idea, I will work on it and make PR!

Thank you again for this awesome project! 
Also, I would be happy to contribute to your project. 🌝

**Comment by moklick** [comment]
Hey @zoomKoding 

this looks pretty nice! As I see it right you could implement the desired behaviour with a custom edge. Since everyone has different expectations and requirements I would like to keep it simple as possible.. Thanks for your help! Maybe you can find an existing feature that you can help us with :)

**Comment by irynahotsiy** [comment]
Hey @zoomKoding

Could you please share your solution  for `to be rotated responsively to the angle of the edge end`?
