### ISSUE TITLE
Move viewport using ControlButton

### ISSUE THREAD

**Issue by clement-faure** [wbkd/react-flow#1206]
I'm currently trying to implement custom Control Button to move viewport programatically.

![image](https://user-images.githubusercontent.com/23209488/118607462-e774f780-b7b8-11eb-816e-37059d9bc23f.png)

My first approach was to retrieve current viewport position and use setTransform method.

```
const [, , zoom] = useStoreState((state) => state.transform);

// Method
const currentPosition = instance.project({ x: 0, y:0 })
instance.setTransform({ x: currentPosition.x + offsetX, y: currentPosition.y + offsetY, zoom)

```

But that does not work. Which instance methods am i supposed to use ?

Thank you in advance.

-----
**Dependencies:**

"react-flow-renderer": "^9.5.4",

**Comment by moklick** [comment]
Hey @clement-faure 

I would use the `useZoomPanHelper` hook like this:

```js 
const [x, y, zoom] = useStoreState((state) => state.transform);  
const { transform } = useZoomPanHelper();

// function for going 10px to the right:
transform(x + 10, y, zoom)
```

**Comment by clement-faure** [comment]
I have also tested this approach but this break the flow view.

I have created a reproduction sandbox here : https://codesandbox.io/s/epic-swartz-7hl5w?file=/src/App.js
