### ISSUE TITLE
A flag in the onConnectEnd event to know if connection ended because user stopped or because node was connected

### ISSUE THREAD

**Issue by saswatds** [wbkd/react-flow#1207]
I am trying to find a way to know if the connection ended without connecting nodes and do some special action in such cases. The `onConnectEnd` seems to be the API to use but it does not tell why exactly it stopped. Maybe passing an 2nd argument with boolean would solve my issue.

**Comment by moklick** [comment]
Maybe you could solve this by yourself. Try to set a flag `connecting=true` when user starts to connect. Then you set the flag to `false` in the `onConnect` handler. If it's still `true` in the `onConnectEnd` handler, there is no new connection. Does it work?

**Comment by moklick** [comment]
Closed due to inactivity. Feel free to re-open if the issue still occurs.

**Comment by eastrd** [comment]
> Maybe you could solve this by yourself. Try to set a flag `connecting=true` when user starts to connect. Then you set the flag to `false` in the `onConnect` handler. If it's still `true` in the `onConnectEnd` handler, there is no new connection. Does it work?

Sorry but I don't get this. Both `onConnect` and `onConnectEnd` are fired simultaneously and this would mean a race condition if `onConnectEnd` tries to access `connecting` while `onConnect` is modifying it. 

How would you be able to use that state flag to check if the connection has failed without creating a race condition? (been stumbling on this issue for 2 hours now)

**Comment by haris-aqeel** [comment]
@moklick  I am trying to use your solution in React, but you know, that we obtain the latest state after re-render so it remains the same.

Can you tell me another way of doing this thing. Maybe you can end something like onConnectionFailed?

**Comment by nzinovyev19** [comment]
+1, I have the same problem. My main initiative is run some logic only if connection wasn't created. All logic with changing some flags (e.g. with simple useState bool value) perform after running onConnectEnd

**Comment by morozover** [comment]
+1

**Comment by bramdeba** [comment]
I was able to solve this exact problem by using the React.useRef()-hook.

```
const connectionCreated = useRef(false)

const onConnectStart = useCallback(() => {
  connectionCreated.current = false
  ...
}, [...])
  
const onConnect = useCallback(
  (params) => {
    connectionCreated.current = true
    ...
  },
  [...]
)

const onConnectEnd = useCallback(
  () => {
    if (!connectionCreated.current) {
      // No connection established
      ...
    } else {
      // Connection established
      ...
    }
  }
)
```
