### ISSUE TITLE
In multiple graphs, displays the last graph for all graphs

### ISSUE THREAD

**Issue by moria-phytech** [wbkd/react-flow#1210]
Hi,

I want to display 2 graphs,
I get 2 graphs with the information of the last graph

Code:

![code](https://user-images.githubusercontent.com/75024592/118993258-08427600-b98e-11eb-9be4-9c4fcdd82abe.png)

The result:

![flows](https://user-images.githubusercontent.com/75024592/118993340-1b554600-b98e-11eb-9bd7-329187f21c6a.png)

**Comment by moklick** [comment]
Hey! You can find the answer here https://github.com/wbkd/react-flow/discussions/986
