### ISSUE TITLE
Edges connecting to wrong handle when updating

### ISSUE THREAD

**Issue by louis-cf-lin** [wbkd/react-flow#1212]
I want to open with saying thank you for this amazing library, it's a really beautiful.

I've been trying to develop a simple editor with updatable edges but get the following error:
![image](https://user-images.githubusercontent.com/46121192/119089443-3db69480-ba5e-11eb-9671-afc6bd7e77c9.png)

I've stripped my editor down to the most basic skeleton and couldn't debug it so I tried reproducing it with the [Updatable Edge example](https://codesandbox.io/s/suspicious-sun-sjpz1?file=/src/App.js). I've set the initial elements with just one input and one output node. When updating the edge using the source node's handle, the error is reproduced.

I think this issue is similar to #190

**Comment by moklick** [comment]
Thanks for the report! I will check it.

**Comment by moklick** [comment]
Hey @louis-cf-lin! Can you check v9.5.5?

**Comment by louis-cf-lin** [comment]
@moklick can confirm it's fixed! Thanks for the speedy fix
