### ISSUE TITLE
New edge type with more points in edge path

### ISSUE THREAD

**Issue by monikabadertscher** [wbkd/react-flow#1213]
Hello
I followed the Issue #1014 about circular connection for edge with source and target on the same node. My goal is to have a new edge type for this purpose not with loops but two more points (to have something like a rectangle edge). As I understand from the latest discussions, at the moment it is not possible to do this extension (e.g. from my side) because such an edge path could not be handled within the react-flow-renderer framework. Is that correct? Do you think this will be possible and is there a timeline?

Thank you very much for your answer.
Moka

**Comment by moklick** [comment]
Hey @monikabadertscher 

this is possible by implement a custom edge. You can find custom edge example here: https://github.com/wbkd/react-flow/tree/main/example/src/Edges
