### ISSUE TITLE
Unlock control overrides nodesConnectable prop

### ISSUE THREAD

**Issue by Redirts** [wbkd/react-flow#1214]
I have a flow with nodesConnectable={false} and as long as the lock (Interactive) control is locked it prevents the user from being able to drag a line from one handle to another.

Once I unlock the control, it seems to be ignoring my nodesConnectable prop setting and allows the user to drag a line from one node to the other besides also allow nodes to be dragged, etc.

![image](https://user-images.githubusercontent.com/23477559/119734608-2703a980-be73-11eb-9cb5-4caa841cb000.png)

Is this the expected behavior?

**Comment by moklick** [comment]
Hey @Redirts 

it's intended. This is our definition of "interactive":

```js
nodesDraggable: true,
nodesConnectable: true,
elementsSelectable: true,
```

As a workaround you could set `nodesConnectable=false` in the `onInteractiveChange` handler.
