### ISSUE TITLE
paneMoveable is not disabling zooming

### ISSUE THREAD

**Issue by PhilGarb** [wbkd/react-flow#1216]
Hi everyone!

It seems like I either found a bug in the code or in the docs. On https://reactflow.dev/docs/api/component-props/ it says for the prop: `paneMoveable`: default: `true` - If set to `false`, panning and zooming is disabled.

However when I am setting it to false zooming still works. 

Here is a small reproduction:

https://codesandbox.io/s/optimistic-archimedes-25l7i?file=/src/App.js

**Comment by moklick** [comment]
Thanks for the report! The docs are wrong ;) I will update it. If you want to disable zoom you can set `zoomOnScroll={false}`.
