### ISSUE TITLE
Restrict dragging to X or Y axis

### ISSUE THREAD

**Issue by maxsteenbergen** [wbkd/react-flow#1217]
It would be very useful to allow dragging of nodes to be constrained to a single axis. In my use case, I have a node that I want to allow movement on the X axis, but to be fixed on the top of the pane regardless of the pane's transform.
I've managed to pin the node to the top when moving the pane but when dragging the node itself, the node's Y position keeps pinned to the cursor regardless of my override.
Maybe add a `dragAxisConstraint` prop on node types?

Relevant code below

```js
onNodeDrag = (event, draggedNode) => {
  const canvas = Instance.toObject()
  const mutatedChartNodes = ActiveChart.nodes.map( node => {
    if(node.id === draggedNode.id) {
      node.position = {
        ...node.position,
        y: canvas.position[1] // <- this doesn't apply
      };
    }

    return node;
  });

  setActiveChart({...ActiveChart, nodes: mutatedChartNodes })
```

**Comment by datoslabs** [comment]
May I suggest a `validateNodeMovement(node, oldPosition, newPosition) : revisedNewPosition` callback function instead?  This allows additional flexibility for developers to specify custom boundaries for all/specific `nodes` and fairly easy to implement by updating wrapNode.onDrag as follows:

```
...
    const onDrag = useCallback(
      (event: DraggableEvent, draggableData: DraggableData) => {
        const oldPosition = [node.position.x, node.position.y];
        let newPosition = [node.position.x + draggableData.deltaX, node.position.y + draggableData.deltaY];
        if (validateNodeMovement) {
          newPosition = (node, oldPosition, newPosition);
        }
        if (onNodeDrag) {
          node.position.x = newPosition[0];
          node.position.y = newPosition[1];
          onNodeDrag(event as MouseEvent, node);
        }

        updateNodePosDiff({
          id,
          diff: {
            x: newPosition[0] - oldPosition[0],
            y: newPosition[0] - oldPosition[1],
          },
          isDragging: true,
        });
      },
      [id, node, onNodeDrag]
    );
...
```

**Comment by datoslabs** [comment]
Upon further examination of the code, I would suggest exposing/adding some of the `React-Draggable` props as `Node` options for the benefit of not only this request but also the Node Drag Handle #1413 request I have recently opened.

For example:
```
{
  id: '1',
  type: 'input',
  data: { label: 'Node 1' },
  position: { x: 250, y: 5 },
  draggableProps:{
    axis: 'y',
    handle:'.dragHandle', //drag handle selector  
    bounds:{top: -100, left: -100, right: 100, bottom: 100}, //restrict movement to 100 px in any direction
  }
}
```
`draggableProps` will be passed through to the `DraggableCore` component inside `NodeWrapper` via `NodeRenderer` component and allows a greater degree of control with minimal code changes.  I have made similar code changes to add `dragHandle` on a local fork and it seemed to work fine; I think it would be fairly easy to expand it to add additional props.  I am not sure if this is the direction the maintainer of this project wants to go as it exposes an underlying dependent library which may cause future breaking changes if there's a decision to swap out `React-Draggable` for another DnD library.

**Comment by moklick** [comment]
With v10, you can hook into the onNodesChange function and set a fixed x or y coordinate. Example implementation: 
https://codesandbox.io/s/peaceful-darkness-t9351t?file=/src/Flow.tsx


```js 
const onNodesChange = useCallback((changes: NodeChange[]) => {
  setNodes((nds) => {
    const parsedChanges = changes.map((change) => {
      if (
        change.type === "position" &&
        change.position &&
        change.positionAbsolute
      ) {
        const fixedY = nds.find((node) => change.id === node.id)?.data.fixedY;

        if (fixedY) {
          change.position = { x: change.position.x, y: fixedY };
          change.positionAbsolute = {
            x: change.positionAbsolute.x,
            y: fixedY
          };
        }
      }

      return change;
    });

    return applyNodeChanges(parsedChanges, nds);
  });
}, []);
````

with nodes that look like this:

```js
 const node = {
    id: "1",
    type: "input",
    data: { label: "Node 1", fixedY: 5 },
    position: { x: 250, y: 5 }
 };
```
