### ISSUE TITLE
Reproducing Overview example

### ISSUE THREAD

**Issue by gireeshkbogu** [wbkd/react-flow#1224]
I am trying to reproduce the Overview example. I see that the rectangle boxes sizes, font type, capital letters are different when  I run the same exact code on my computer. How can I reproduce the same figure?

My figure
<img width="602" alt="Screen Shot 2021-05-31 at 6 50 19 AM" src="https://user-images.githubusercontent.com/3885659/120204626-e17e0e00-c1dd-11eb-805e-fb7f0bdbfef9.png">

[Reactflow figure](https://reactflow.dev/examples/)
<img width="432" alt="Screen Shot 2021-05-31 at 6 50 38 AM" src="https://user-images.githubusercontent.com/3885659/120204632-e2af3b00-c1dd-11eb-961d-fcf2c8d55efa.png">

**Comment by awu43** [comment]
The examples don't display their [external CSS styling](https://reactflow.dev/docs/theming/). If you inspect one of the example nodes and then disable the following rules the example matches your figure:

```
.react-flow .react-flow__node {
    font-size: 14px;
}
```
```
.react-flow {
    font-family: jetbrains-mono;
    text-transform: uppercase;
}
```
