### ISSUE TITLE
Not able to delete node by backspacing on local device

### ISSUE THREAD

**Issue by Aditi-Bhatt** [wbkd/react-flow#1226]
The code mentioned for deleting a node by clicking and pressing delete is not working locally. Kindly let me know what needs to be done.

**Comment by moklick** [comment]
Hey @Aditi-Bhatt 

did you implement the `onElementsRemove` handler like in this example: https://reactflow.dev/examples/ ? The handler gets called when the user presses Backspace.

**Comment by Aditi-Bhatt** [comment]
I have implemented the same code present in: https://reactflow.dev/docs/getting-started/    in the basic functionality section.

**Comment by Ark-kun** [comment]
The deletion feature is really hard to discover.

I was under impression that it did not exist even though I saw the `onElementsRemove` hooks.

The `Del` key never did anything.

>The handler gets called when the user presses Backspace.

I think you'll significantly improve the discoverability of this feature if you add support for using `Del`, not just `Backspace`.

**Comment by moklick** [comment]
You can change the key code with the `deleteKeyCode` prop. If this is still an issue please re-open with a codesandbox or something like that so that I can take a look at your code.

**Comment by Ark-kun** [comment]
>@Ark-kun You can change the key code with the deleteKeyCode prop.

You cannot set it to multiple keys though. So half of the users will always be broken.
