### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Keanottesen** [wbkd/react-flow#1227]
There is a lot of jank when I am rendering the ReactFlow component. I have a lot of API calls and stuff going on besides, but I cannot really figure out what gives me the low performance. Do you have any tips on how to optimize the performance. 

https://user-images.githubusercontent.com/47158972/120385003-2c576d00-c327-11eb-9e36-6f41303c5cb7.mov

https://user-images.githubusercontent.com/47158972/120385008-2e213080-c327-11eb-9f0f-6df1f7b5bf5e.mov

**Comment by clement-faure** [comment]
Hello @Keanottesen,

Did you memoized (using `useMemo` or `memo`) all your custom nodes and edges ?

**Comment by Keanottesen** [comment]
Yes, they are all memoized.
I am not that familiar with performance optimization. But its seems to me that there is something more fundamentally wrong. For example if I have my page with the react flow open, all my buttons in my side drawer also starts loosing frames. My app works perfectly fine when react flow is not rendered. But I cannot figure out what is creating the issue.

**Comment by Keanottesen** [comment]
> Yes, they are all memoized.
> I am not that familiar with performance optimization. But its seems to me that there is something more fundamentally wrong. For example if I have my page with the react flow open, all my buttons in my side drawer also starts loosing frames. My app works perfectly fine when react flow is not rendered. But I cannot figure out what is creating the issue.

**Comment by clement-faure** [comment]
Did you defined a specific handler for props `onNodeDrag` ?

**Comment by Keanottesen** [comment]
No, I did not. Should I do that?

**Comment by clement-faure** [comment]
> No, I did not. Should I do that?

No, it depends but using it and updating global state could have been the cause. 
I can not help you more without having a reproduction codesandbox

**Comment by Keanottesen** [comment]
https://codesandbox.io/s/withered-smoke-0c3g2?file=/src/App.js

Here is a minimal version of my implementation.

**Comment by Keanottesen** [comment]
A little update to this. there seems to be a direct correlation between how scaled my browser window is, thus my react flow component and its performance. However, when playing around with the examples I cannot find the same correlation. Anyone who can explain this?

**Comment by moklick** [comment]
Hey @Keanottesen 

could you solve this? Your codesandbox looks good to me.

**Comment by Keanottesen** [comment]
I am not totally sure why, but my performance have improved significantly after I have removed the dotted background.

**Comment by moklick** [comment]
which version are you using?

**Comment by Keanottesen** [comment]
9.2.0
