### ISSUE TITLE
When onElementClick is defined, user can't navigate in the flow on top of nodes

### ISSUE THREAD

**Issue by clement-faure** [wbkd/react-flow#1229]
When defining a `onElementClick` method on the ReactFlow component, the end user can not navigate on top of existing nodes.

It can be easily reproduced on the following example https://reactflow.dev/examples/interaction/.

- Navigate on top of nodes works fine
- Click on the : capture onElementClick checkbox
- You can not navigate anymore on top of nodes

I guess it is the default behaviour, but it is possible override that ? I would like to have clickable elements in read only mode.

One workaround would be to have a specific keyboard to hold to navigate in the flow, but is that doable ?

**Comment by moklick** [comment]
Hey @clement-faure 

you are right. This is the default behaviour. You could implement your own solution with a keyboard event that toggles `elementsSelectable` and `onElementClick`.

**Comment by clement-faure** [comment]
> Hey @clement-faure
> 
> you are right. This is the default behaviour. You could implement your own solution with a keyboard event that toggles `elementsSelectable` and `onElementClick`.

Well noted, thank you.
