### ISSUE TITLE
Variant lines act like miro's lines while zooming in/out

### ISSUE THREAD

**Issue by ertugrulcetin** [wbkd/react-flow#1230]
When we zoom out in [miro](https://miro.com/) app, lines become small (disappear), and they create bigger lines and it goes like that (while zooming out) - if zoom in it makes the opposite. That would be great if the library has this functionality.

![kk](https://user-images.githubusercontent.com/8271291/120561265-e1b02080-c40c-11eb-87cb-d7d4b25dda47.gif)

**Comment by awu43** [comment]
After some tinkering, here's my attempt at implementing dynamic grid size:

https://user-images.githubusercontent.com/46470763/120908893-ff0b0780-c623-11eb-815c-fe30569d9992.mp4

```JSX
import React, { useState } from "react";

import ReactFlow, {
  Background,
  BackgroundVariant,
} from "react-flow-renderer";
import type {
  FlowTransform,
} from "react-flow-renderer";

import "./App.scss";
import initialElements from "./initial-elements";

const BASE_BG_GAP = 32;
const BASE_BG_STROKE = 1;
// At zoom = 1

export default function App() {
  const [elements, _setElements] = useState(initialElements);
  const [currentZoom, setCurrentZoom] = useState(1);

  return (
    <div className="App">
      <ReactFlow
        elements={elements}
        onMove={(flowTransform: FlowTransform | undefined) => {
          if (flowTransform) {
            setCurrentZoom(flowTransform.zoom);
          }
        }}
      >
        <Background
          variant={BackgroundVariant.Lines}
          gap={BASE_BG_GAP / currentZoom}
          size={BASE_BG_STROKE / currentZoom}
        />
      </ReactFlow>
    </div>
  );
}
```

**Comment by moklick** [comment]
Hey @ertugrulcetin 

I agree that this background looks really nice but we will not work on our background variant since we have too many other things on our list ;) You could use the current `Background` component as a foundation for your own custom Background component. I am also willing to accept a PR for a new background variant :)
