### ISSUE TITLE
Fit view on graph load but when dragging it goes back to (0, 0)

### ISSUE THREAD

**Issue by baptisteArno** [wbkd/react-flow#1231]
https://user-images.githubusercontent.com/16015833/120658453-bddcf100-c485-11eb-988c-0b42027727fd.mp4

It's happening when the Flow component is unmounted and mounted back. [Here is a codesandbox reproduction](https://codesandbox.io/s/elastic-joliot-rp5wv).

Click on "Another view" then click back to "Flow view" and try to drag the Graph

**Comment by abbieschenk** [comment]
I'm encountering the same. I've tried setting reactFlowInstance to a React state variable in onLoad, and calling fitView when clicking a button, but it had the same effect.

**Comment by moklick** [comment]
Hey @baptisteArno 

could you try to wrap the `ReactFlow` component with a `ReactFlowProvider`?

**Comment by baptisteArno** [comment]
Yup! It seems to do the trick 👍
