### ISSUE TITLE
Integration with Power BI

### ISSUE THREAD

**Issue by geekycoder561** [wbkd/react-flow#1236]
I want to use React Flow for creating custom visualization in Power BI but when I include the ReactFlow Library my visual becomes blank. Kindly, guide me on this how to use this.

**Comment by awu43** [comment]
Fyi, it's going to be difficult for others to help you on this when Power BI is a paid product.

**Comment by geekycoder561** [comment]
@awu43 Yes I know but th project is very crucial for me , and Reactflow best suits to my expectation. I want to know from the React Flow team that if React flow is compatible or not with Power Bi custom visualization?

**Comment by moklick** [comment]
I don't know Power BI. Do you get an error or do you have any more information about this?

**Comment by geekycoder561** [comment]
Thank you for your response, I am stuck in between actually we can create
custom visualization in Power BI using react and it's libraries , I am
trying to build an Process Mining tool and react- flow is best suitable for
me but it gives me blank screen when I use react flow in the Div Tag.
Please help me on this issue as it can be great for the team too as I am
creating it for an organization

Regards,

**Comment by geekycoder561** [comment]
For your reference :

https://youtu.be/eJ6uHwaGJRM

This is how we create a visualization using React using libraries.

**Comment by moklick** [comment]
does the parent container of the react flow component has a proper width and height?
