### ISSUE TITLE
Input text selection in custom nodes

### ISSUE THREAD

**Issue by harsohailB** [wbkd/react-flow#1238]
How can I select text in inputs on a custom node without the node being dragged?

I found that it can be done in datablocks:
![image](https://user-images.githubusercontent.com/47438886/120841548-de11bc00-c528-11eb-94b7-11951a2e574d.png)

**Comment by moklick** [comment]
And the class "nodrag" to the input element.

**Comment by harsohailB** [comment]
Works perfectly! Thank you.
