### ISSUE TITLE
An option to wrap multiple node with a text?

### ISSUE THREAD

**Issue by GiladFeder** [wbkd/react-flow#1249]
Hey!

I am wondering if there is an option (either internally or through other libs) to wrap a few nodes in a container and give it a title.

Something similar to this:

<img width="560" alt="Screen Shot 2021-06-08 at 19 14 22" src="https://user-images.githubusercontent.com/38831140/121221204-02a1c700-c88e-11eb-96a2-3856f0d37414.png">

Thanks!
Gilad

**Comment by awu43** [comment]
This is a highly wanted feature (that I also want) which may or may not be on be way (#1022). Related: #1024.

**Comment by moklick** [comment]
Not possible at the moment. Let's continue the discussion in #1022
