### ISSUE TITLE
change connector path while dragging connectorLine

### ISSUE THREAD

**Issue by monikabadertscher** [wbkd/react-flow#1250]
Hello
I tried to add Points to the path in my ConnectionLineComponent while drawing the connection. But I did not find an EventHandler where I can do this without loosing the connectorLine. Is there a way to do this?
Thank you for your response.
Moka

**Comment by moklick** [comment]
Hey @monikabadertscher 

sorry, this is not possible and we will not add this feature. It's too rare in my view.
