### ISSUE TITLE
`onClick` did not pass the original element in `elements`

### ISSUE THREAD

**Issue by harrisoff** [wbkd/react-flow#1251]
I create a state `selectedNode`, and want it updated along with `elements`.

[code sandbox](https://codesandbox.io/s/festive-johnson-pjc3w?file=/src/App.tsx)

```jsx
export default () => {
  const [elements] = useState([]);
  const nodes = useMemo(() => elements.filter(isNode), [elements]);

  const [selectedNode, setSelectedNode] = useState();
  const handleClick = (el) => {
    if (isNode(el)) {
      setSelectedNode(el);
    }
  };

  useEffect(() => {
    console.log('useEffect triggered')
    if (selectedNode) {
      const updatedNode = nodes.find((n) => n.id === selectedNode.id);
      setSelectedNode(updatedNode);
    }
  }, [nodes, selectedNode]);

  return <ReactFlow
    elements={nodes}
    onClick={(e, el) => handleClick(el))
  />
}
```

But this caused that every time a node is clicked, `useEffect` triggers twice.

I find that it is because the `el` in `onClick(e, el)` is not the original object in `elements`, src code here: [wrapNode.tsx#L59](https://github.com/wbkd/react-flow/blob/main/src/components/Nodes/wrapNode.tsx#L59)

I guess maybe it's better to pass the original node to `onClick`?

**Comment by moklick** [comment]
You can get the selected elements via the undocumented `selectedElements` entry of the store:

```js 
const selectedElements = useStoreState(s => s.selectedElements);
```

**Comment by harrisoff** [comment]
I need to use the rest of properties other than `id, type, position, data`, so I still need to look for the original node by in the `nodes`.
What's the point only returning those four properties?
