### ISSUE TITLE
Input type file, default DnD not works because of onlyRenderVisibleElements={false}

### ISSUE THREAD

**Issue by GoncharovVV** [wbkd/react-flow#1263]
I cant Drag n Drop image to the file selector <input type="file"> (outside of flow chart) on page where flow chart exists . 
All this not helps: 
1. Add 'nodrag' class name
2. onMouseDown={(e) => {
            e.stopPropagation();
          }}
          onDragOver={(e) => {
            e.stopPropagation();
          }}
          onMouseEnter={(e) => {
            e.stopPropagation();
          }}
          onMouseMove={(e) => {
            e.stopPropagation();
          }}
          onMouseOver={(e) => {
            e.stopPropagation();
          }}
          onDrag={(e) => {
            e.stopPropagation();
          }}
          onDragEnd={(e) => {
            e.stopPropagation();
          }}
          onDragEnter={(e) => {
            e.stopPropagation();
          }}
          onDragStart={(e) => {
            e.stopPropagation();
          }}
How can I disable flow chart listener? Which event I should add .stopPropagation(); ?

**Comment by moklick** [comment]
You could try to add `pointer-events: none` to the React Flow pane when you start dragging the image and reset it on drop.
