### ISSUE TITLE
How to add a "custom control" Edge?

### ISSUE THREAD

**Issue by ilanskogan** [wbkd/react-flow#1266]
Hi, i saw there was already a closed ticket like this but the answer provided there is not enough in my opinion.
i need to have an edge like this:
![Screen Shot 2021-06-14 at 17 02 53](https://user-images.githubusercontent.com/71634959/121905011-5e5acd00-cd32-11eb-8544-850fe61310d0.png)
this edge has a button on its center and I should be able to pass him callbacks on events like "onClick" and so on.
i know we can create custom edges and we have all those edges utils but it seems like all I can get with them is a custom edge with some styled simple label, I cant pass HTML elements there.
can someone show me how can I achieve this, please? 
and if this is not possible so I would like to know and request this as a feature.

**Comment by mmairs9** [comment]
+1, I requested a related feature - #1246

**Comment by ilanskogan** [comment]
@mmairs9 looks like the solution is to use foreignObject
if you render this inside the custom edge
` <foreignObject className={styles.foreignObject} x={targetX} y={sourceY + 20} >
                <div className={styles.addButton} onClick={() => alert('here')}>+</div>
            </foreignObject>}`
you can render any HTML you want inside the foreignObject

**Comment by mmairs9** [comment]
@ilanskogan thanks for this! I'm using smoothStep Edge path, so using a combination of target/source coordinates and exporting [getCenter](https://github.com/wbkd/react-flow/blob/main/src/components/Edges/utils.ts#L22) function from the edge utils I was able to achieve the desired place for the drop node as a custom edge. Does the foreign object not solve your use case here?

**Comment by ilanskogan** [comment]
@mmairs9 yes looks like we found the solution, closing

**Comment by moklick** [comment]
I added a simple example "Edge With Button" https://reactflow.dev/examples/edge-with-button
