### ISSUE TITLE
Feature request: Default multi-handle node

### ISSUE THREAD

**Issue by Ark-kun** [wbkd/react-flow#1267]
Currently the package comes with three node types: "1 source", "1 target", "1 source and 1 target".
Everything else requires adding new node types, adding CSS etc.
I think these types are not enough for majority of use cases. People often need multiple sources for example.
It would be great to have a multi-handle node type (maybe even as the only default node type).

**Comment by moklick** [comment]
It's a good idea but I will not add another node type. We recommend to use custom nodes only. The given ones are just showcases..

**Comment by mrinalsharma** [comment]
Can this be added to examples?
