### ISSUE TITLE
Feature request: Support deleting elements using the `Del` key

### ISSUE THREAD

**Issue by Ark-kun** [wbkd/react-flow#1268]
This key is widely used on the majority of machines in the world.

**Comment by moklick** [comment]
You can specify the keyCode via the `deleteKeyCode` prop https://reactflow.dev/docs/api/component-props/

**Comment by Ark-kun** [comment]
>You can specify the keyCode via the deleteKeyCode prop https://reactflow.dev/docs/api/component-props/

Will it work on Mac?

**Comment by avichai-PhoneDo** [comment]
deleteKeyCode={['Backspace', 'Delete']}
