### ISSUE TITLE
Feature request: Add node to selection using Ctrl+click

### ISSUE THREAD

**Issue by Ark-kun** [wbkd/react-flow#1269]
This is a very common mechanism for adding items to selection.

**Comment by Ark-kun** [comment]
Err... How do I say it... The idea to use Win+click for multi-selection is pretty radical.
It would be interesting t hear the backstory.

**Comment by moklick** [comment]
You can change it by using the `multiSelectionKeyCode` prop https://reactflow.dev/docs/api/component-props/

**Comment by Ark-kun** [comment]
I'm not sure that the issue is fixed.

The default multi-selection key is unusable on most machines.

Just because there is a way to work around the issue does not mean that the issue does not exist.
