### ISSUE TITLE
Playground for react-flow

### ISSUE THREAD

**Issue by arjungarg07** [wbkd/react-flow#1279]
Currently, we don't have any playground where one could do some changes and see the changes in the flow in real-time.

It would be really good if we could have playgrounds like: [mermaid](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZylcbiAgICBCIC0tPiBDe0xldCBtZSB0aGlua31cbiAgICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICAgIEMgLS0-fFR3b3wgRVtpUGhvbmVdXG4gICAgQyAtLT58VGhyZWV8IEZbZmE6ZmEtY2FyIENhcl0iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjp0cnVlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0), [plantUML](https://www.planttext.com/), [dotUML](https://dotuml.com/playground.html)

Thoughts?

**Comment by moklick** [comment]
Hey @arjungarg07 

could you re-open this issue in the https://github.com/wbkd/react-flow-docs repo? Thanks!
