### ISSUE TITLE
Nodes need to know their connections and upstreams

### ISSUE THREAD

**Issue by Ark-kun** [wbkd/react-flow#1292]
Many scenarios require the nod to be aware about the upstream node connected to it.

* Prohibit connecting two sources to same target
* Required inputs that must be connected

**Comment by nfwyst** [comment]
You can management the connections by yourself

**Comment by datoslabs** [comment]
Couple options come to mind:

1. Use the utility functions like `getOutgoers` and `getIncomers` (see source code src/utils/graph.ts for more detail).
2. Get the internal states via `useStoreState` hook (ie `useStoreState((state) => state.nodes)` to get the nodes array and `useStoreState((state) => state.edges)` to get the edges array); based on your description, you probably only need to use edge array, apply filter then reduce operation to get the upstream nodes (pretty much the same logic as `getIncomers` method).
