### ISSUE TITLE
Suggestion on node editor tool.. 

### ISSUE THREAD

**Issue by rakesh-eltropy** [wbkd/react-flow#1293]
Hi,

React flow seems to be a great node editor tool. We are looking to build a contact center flow and allow our customers to configure them (Similar to AWS Connect). I want an advice whether it will be possible using react flow or any other suggestion on the tools available for the same (Open source or commercial tools):

<img width="1792" alt="Screenshot 2021-06-21 at 12 15 25 AM" src="https://user-images.githubusercontent.com/11676761/122685219-975dda80-d227-11eb-9298-2882087a8b56.png">
<img width="1792" alt="Screenshot 2021-06-21 at 12 16 41 AM" src="https://user-images.githubusercontent.com/11676761/122685225-9d53bb80-d227-11eb-9858-633fd4a766b8.png">

**Comment by moklick** [comment]
Hey @rakesh-eltropy 

this is something you can build with React Flow. As a reference you can check out what we are building with it: https://editor.datablocks.pro/demo
