### ISSUE TITLE
Feature request: fitView with separate max zoom

### ISSUE THREAD

**Issue by saschahofmann** [wbkd/react-flow#1301]
I'd like to separately, manage the max zoom level when `fitView`ing meaning I can set a higher `maxZoom` in general provide an optional `maxZoom` to the function.

Alternatively, it could be nice to a "dry-run" of the `fitView` function that returns the zoom level that'd would be zoomed to and use the output of that to alternatively zoom to the `maxZoom` level instead.

**Comment by saschahofmann** [comment]
Ha cool thx you guys dont mess around 👍

**Comment by moklick** [comment]
released in 9.6.2
