### ISSUE TITLE
Internal node state __rf.handleBounds not updated after moving handle location

### ISSUE THREAD

**Issue by datoslabs** [wbkd/react-flow#1305]
Hi,

I was able to programmatically move a `Handle's` location via `CSS style`, e.g. `<Handle ... style={{left:'50%'}}/>` to `<Handle ... style={{left:'70%'}}/>` inside `onEdgeUpdateEnd` callback; after updating the `elements` array, the screen refreshed and moved the `Handle` accordingly except the connected edge still points to the original location on the screen.  Turns out the `targetX` and `targetY` values provided to the `Edge` component still reflects the old values.  After debugging and reading the source code, I tried to force an update on the node internal states via `useStoreActions((actions) => actions.updateNodeDimensions)` but `node.__rf.handleBound` remained the same value before and after the update.  Is there another way to force refresh `node.__rf.handleBound`?

**Comment by datoslabs** [comment]
As an update in case anyone encountered similar issues, I was able to get `node.__rf.handleBound` to update after wrapping `updateNodeDimensions` call inside `setTimeout` with 0.1s delay.  Note, I had ensured that a new `node` object for the updated `node` was created when updating the `elements` array; as such the problem I encountered was not related to stale object reference, otherwise the `handle` would not have moved after updating the elements array.

Pseudo code as follows:

```
const onEdgeUpdateEnd = (event, edge) => { 
  calculateNewHandlePosition();
  setElements((els)=>updateHandlePosition(nodeId, handled, els));

  // need to postpone updateNodeDimensions to allow for at least 1 render cycle to pass in order to update node.__rf.handleBound correctly.
  setTimeout(function waitB4UpdateNodeDimensions() {
          const nodeElement = document.querySelector(`.react-flow__node[data-id="${nodeId}"]`);
          updateNodeDimensions([{ id:nodeId, nodeElement, forceUpdate: true }]);
  }, 100);
}
```
Is there a better solution to this issue?

**Comment by moklick** [comment]
I am not sure how the `updateHandlePosition` function works but you might be able to listen to a change inside your custom node and call `updateNodeDimensions` in a `useEffect` after a handle position change happened.

**Comment by datoslabs** [comment]
Currently each `handle's` position (eg `left:'70%'` vs `left:'25%'`) is tracked inside `node.data` so that the custom `node` can correctly position each `handle` in its `render` method.  `updateHandlePosition` function basically updates `handle's` position inside `node.data` based on the output from `calculateNewHandlePosition`; in other words, `updateHandlePosition` loops and finds the target `node` and saves the corresponding `handle's` new position in `node.data`).

The custom `node` has `useEffect` to detect the changes in `node.data` to trigger rendering of the `node's` `handles` with their new positions; this part is working as expected but the `edge` connecting to the moved `handle` did not update.  Since `useEffect`  preceeds rendering what would be the best way to detect the rerendering of the nodes are done to trigger the 'updateNodeDimensions' call?

**Comment by supercmmetry** [comment]
When will this issue be resolved?

**Comment by EdwardSalter** [comment]
I have just stumbled upon this issue as I was experiencing the same issue after my custom node rearranged handles based on some sorting.
I tried using the code that @datoslabs posted here and got that working.

> ```
> const onEdgeUpdateEnd = (event, edge) => { 
>   calculateNewHandlePosition();
>   setElements((els)=>updateHandlePosition(nodeId, handled, els));
> 
>   // need to postpone updateNodeDimensions to allow for at least 1 render cycle to pass in order to update node.__rf.handleBound correctly.
>   setTimeout(function waitB4UpdateNodeDimensions() {
>           const nodeElement = document.querySelector(`.react-flow__node[data-id="${nodeId}"]`);
>           updateNodeDimensions([{ id:nodeId, nodeElement, forceUpdate: true }]);
>   }, 100);
> }
> ```

I was however not happy with the `document.querySelector` method of retrieving the node to update and was perusing the documentation looking to see if I could find out whether the custom node receives a ref to the HTML Element in question.
Within search, I actually managed to stumble across the `useUpdateNodeInternals` hook that is documented [here](https://reactflow.dev/docs/api/hooks/). This hook can be used in place of @datoslabs code and enables us to do force this update without having to resort to dispatching internal actions.

To get it working, I know having the following code:
```jsx
import { Handle, useUpdateNodeInternals } from 'react-flow-renderer';

const MyCUstomNode= (props) => {
  const sortedItems = useMemo(() => {
    const itemsCopy= Array.from(props.items);
    items.sort();
    return items;
  }, [items]);

  const updateNodeInternals = useUpdateNodeInternals();

  // Since the Handles are rendered based on the `sortedItems` array, detect changes in this array and forcefully update the node internals.
  useEffect(() => {
    updateNodeInternals(props.id);
  }, [sortedItems]);

  return (
    // ...
    {sortedItems.map((item) => {
      <Handle id={item.id} type="source" />
    })}
    // ...
  )
}
```

**Comment by moklick** [comment]
as @EdwardSalter pointed out `useUpdateNodeInternals` is the way to go when you programatically change the handles.
