### ISSUE TITLE
Drag stop listeners aren't working if multiple nodes are moved

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#1314]
### Issue

If more than one node is selected with the "click to multi select" feature (https://github.com/wbkd/react-flow/issues/609, https://github.com/wbkd/react-flow/pull/663), then there seems to be no handler that will work, if more than one node is dragged.

### Reproducing the issue

* Open the [overview example](https://github.com/wbkd/react-flow/blob/e1c34d3cd276d5acfef0f2233e83598c578dfdae/example/src/Overview/index.tsx)
* Enable or set `multiSelectionKeyCode` (default is `Meta`)
* `Meta + Click` two nodes
* Drag to change both node positions

### Observation

`onNodeDragStop(event, node)` will fire, but only contain a single node instead of a list of all nodes. 

![image](https://user-images.githubusercontent.com/13085980/123558971-a26db900-d799-11eb-9a54-e09eb43c32bb.png)

`onSelectionDragStop(event, nodes)` doesn't fire. Based on [this comment](https://github.com/wbkd/react-flow/issues/858#issuecomment-768888429) it seems to be the expected behavior, and "selection" is the blue box, but not multiple elements that are selected per click.

### Potential solutions

It might be that I'm missing something here. So, helping me out, could be a solution :)
If that's not the case:
* `onSelectionDragStop` could fire with a list of moved nodes regardless if the multiselection was done with `multiSelectionKeyCode` or with a rectangle
* `onNodeDragStop` could be called with a list of nodes instead of a single node, if more than one node was moved

### Info

* Using `react-flow` in version `9.6.1`
* Similar to https://github.com/wbkd/react-flow/issues/858
* Relevant comment https://github.com/wbkd/react-flow/issues/1006#issuecomment-799758872

**Comment by pudgereyem** [comment]
Thanks for creating this issue @andys8, I have the exact same problem. Let me know if you find something out :)

**Comment by andys8** [comment]
@moklick Hey, please don't feel pressured or anything, but I'd be very much interested in your thoughts about this issue. Is it likely to be tackled in the near future? How would the solution look like (referring to the options mentioned)?

It would help me a lot in being able to better decide how to move forward with this :)

**Comment by moklick** [comment]
Hey @andys8 

it's definitely an issue. I am thinking about changing the api to `onNodeDrag(event, draggedNode, [selectedNodes])`. What do you think about that? Is it possible for to use `const selectedElements = useStoreState(s => s.selectedElements)` as a workaround for now?

**Comment by andys8** [comment]
> I am thinking about changing the api to `onNodeDrag(event, draggedNode, [selectedNodes])`. What do you think about that?

That might work and not break existing implementations. Cool :+1: 

> Is it possible for to use const selectedElements = useStoreState(s => s.selectedElements) as a workaround for now?

That sounds like a feasible workaround. I didn't try to go with a workaround for now, if the change for the api is in sight. The suggested api change is looking promising :)

**Comment by andys8** [comment]
Hey @moklick , what do you think about the implementation of your suggested change (`onNodeDrag(event, draggedNode, [selectedNodes])`)? Is it straight forward or a larger change to the library?

**Comment by andys8** [comment]
For now I'll go with this workaround: 

* `onSelectionChange` is used to track the current selected nodes (and alternative would be the hook mentioned above)
* `onNodeDragStop` does only contain a single node (even if multiple are selected)
* `reactInstance.getElements()` returns all elements. Edges need to be filtered, and positions of  the selected nodes are used to update the positions of the external state.

**Comment by elbakerino** [comment]
Another workaround, using the internal state of nodes, so far seems to work with single and multi selection drag movement.

```jsx
const store = useStore()
const onNodeDragStop: (event: ReactMouseEvent, node: Node) => void = React.useCallback((e, node) => {
    // get currently selected elements
    const selectedElems = store.getState().selectedElements
    // get those as nodes to be able to access `__rf`
    const nodes = store.getState().nodes.filter(n => selectedElems?.findIndex(se => se.id === n.id) !== -1)
    const updatedNodes = []
    nodes?.forEach(elem => {
        // do your updating stuff
        updatedNodes.push({
            id: elem.id,
            type: elem.type,
            // @ts-ignore
            position: elem.__rf && elem.__rf.position ? elem.__rf.position : elem.position,
        })
    })
    updateNodesMoved(updatedNodes)
}, [updateNodesMoved, store])
```

**Comment by kiwdahc** [comment]
Why can't this work exactly the same as `onSelectionDragStop` ?

**Comment by ChristianMaehler** [comment]
Hi. The solution described above is not working for me. The selectedElems have the same positions like the elements stored in my own state. I implemented a different solution:

1) Calculate the position offset of the node that is passed to the onNodeDragStop handler compared to the node stored in my internal state. This deltaX and deltaY should be the same for all selected and moved elements
2) Iterate through all selected elements that are nodes and apply deltaX, deltaY to all positions
3) if elem.__rf exists, then apply elem.position to elem.__rf.position - and not vice versa as described above

This is working for me - positions on the screen are correct and persisting state in a DB and reloading results in the same rendering result.

**Comment by moklick** [comment]
We are working on a next release #2152. We dropped react-draggable and rewrote the dragging logic. We are now passing a third parameter `nodes` that includes all selected nodes. You can check out the next version with `npm install react-flow-renderer@next`.

**Comment by VincentFP** [comment]
@tonychandesign 

`onNodeDragStop` triggers only for a single node move. Even if a third parameter takes an array of nodes.
You should use `SelectionDragHandler` to handle group of nodes moving. 
See https://reactflow.dev/api-reference/types/selection-drag-handler

This works exactly the same.
