### ISSUE TITLE
Node partly draggable

### ISSUE THREAD

**Issue by Keanottesen** [wbkd/react-flow#1321]
Is there any way to make a node partly draggable? So if I for example have a node like a post it note. I would like to resize it using re-resizable og something similar. However, due to the draggable feature of a node i cannot resize the node, without the node is dragged simultaneously. However, I would still like to drag the post it, but only, when the user is hovering over the correct spot on it. Kind of like: https://react-latest-ui.github.io/react-sticky-notes/.

**Comment by wernst** [comment]
Not the maintainer, but you should be able to prevent dragging by adding the `nodrag` class to any element inside a custom node - https://reactflow.dev/docs/api/node-types/ (see "Prevent dragging & selecting"). That class can be added to the re-resizable handle classes so only the handles will ignore the drag (see sandbox).

Example sandbox (sorry if messy, forked something else i had done): https://codesandbox.io/s/white-waterfall-qy9o1?file=/src/App.js

**Comment by Keanottesen** [comment]
Arh thats great! thank you very much for a precise answer!

**Comment by Keanottesen** [comment]
@wernst can i ask where you read about the nodrag class, I cannot seem to find it in the documentation?

**Comment by wernst** [comment]
@Keanottesen  https://reactflow.dev/docs/api/node-types/ (see "Prevent dragging & selecting")
