### ISSUE TITLE
React flow is unusable on touch devices

### ISSUE THREAD

**Issue by Ark-kun** [wbkd/react-flow#1323]
Edge creation (by dragging) does not trigger.
Cannot drag nodes from the Sidebar (DragNDrop sample).

Node dragging works though.

I think it's important to support touch-based devices like iPads and other tablets.

**Comment by moklick** [comment]
Hey @Ark-kun 

we already have it on our list #1021

**Comment by BusyginArtem** [comment]
I try to implement dragging nodes from the Sidebar on touch devices , but I can't find an appropriate method for the action touch end on the pane.
