### ISSUE TITLE
[support]Does it support left-to-right display?

### ISSUE THREAD

**Issue by bi-kai** [wbkd/react-flow#1332]
Does it support left-to-right display?
Does it support collapsing levels?
![图片](https://user-images.githubusercontent.com/15070379/125013472-7528e100-e09e-11eb-9710-431b8922e772.png)

Does it support top-down icons and text?
![图片](https://user-images.githubusercontent.com/15070379/125013664-cc2eb600-e09e-11eb-8b4a-3efc01053514.png)

**Comment by moklick** [comment]
1. left-to-right yes
2. it's not built in but you can implement with the help of the [`isHidden` prop](https://reactflow.dev/docs/api/nodes/) and the [`getIncomers`/`getOutgoers` helper functions](https://reactflow.dev/docs/api/helper-functions/)

**Comment by harshavnaik** [comment]
@moklick  I tried the same, nodes are getting hidden but edges are not hiding.
