### ISSUE TITLE
Create new node after releasing the edge drag

### ISSUE THREAD

**Issue by kumarvikramaditya1** [wbkd/react-flow#1334]
### Discussed in https://github.com/wbkd/react-flow/discussions/1329

<div type='discussions-op-text'>

<sup>Originally posted by **kumarvikramaditya1** July  9, 2021</sup>
Is there a way in which we can create a new node from a context menu which gets triggered on releasing an edge drag. Here is some more explanation.

1. There is a default node created.
2. Two create a new node:
    3. Drag an edge from the handle and release it in the open space.
    4. A context menu appears asking a type of node selection
    5. On selecting a type, the new node is created and the Source and Target nodes are auto linked.

Any help is appreciated. Thanks !
</div>

**Comment by moklick** [comment]
Let's try to use the issues for bugs and stuff. I will close this in favor of #1329
