### ISSUE TITLE
Position "fixed" for elements inside the react flow wrapper doesnt work

### ISSUE THREAD

**Issue by ilanskogan** [wbkd/react-flow#1345]
I have a custom node that renders a right pane inside it, the right pane has position fixed and it needs to be right to the right of the screen (right: 0), seems like the position fixed that is set on the right pane isn't working

**### Update:**
the problem is that the node itself has a transform attribute so it sets the node as a relative element to my fixed element. is there a solution for this?

**Comment by moklick** [comment]
Why is the right pane part of the node? Couldn't you add it as a sibling or direct child of the react flow component?

**Comment by ilanskogan** [comment]
@moklick it will make more sense if the right pane will be part of the block, that way when adding a custom block to the flow you can be sure it can handle all the logic there.
if I render the right pane as sibling of the react flow component and I have a few of that custom block, I need to manage a bit complex state in the redux to know which custom node was clicked so ill know which content to render inside the right pane.
its not that bad and that's what I am doing now but I think it was better if I could render fixed elements there as well

**Comment by eladgrott** [comment]
+1

**Comment by moklick** [comment]
Maybe you could use a Portal to render the pane somewhere else. Anyway this is not an issue with React Flow. I would suggest to use proper state management and call an action when you want to render the pane.
