### ISSUE TITLE
sourceX of an edge isnt the same as the x in the "position" object inside the actual source node

### ISSUE THREAD

**Issue by ilanskogan** [wbkd/react-flow#1346]
Hi guys im trying to understand why the sourceX of an edge is not the same of the x inside the position of the source node.
in fact I see that the diff is exactly half of the node component

**Comment by moklick** [comment]
sourceX is the the x position of the handle itself. x is the position of the node.

**Comment by ilanskogan** [comment]
@moklick thanks for the reply, don't you think its better if sourceX will be the x of the node? that way if you want to add a block after a click on an edge you know exactly what x you should give to the new node and you don't need to calculate it based on the x of the handle and the width/height of the node
