### ISSUE TITLE
Example on Saving and Restoring in a Class Component

### ISSUE THREAD

**Issue by atkawa7** [wbkd/react-flow#1347]
Thank you for this library. Just wondering is there an example on restoring a class component without using  `useZoomPanHelper`

**Comment by moklick** [comment]
What do you mean with "restoring a class component"?

**Comment by atkawa7** [comment]
Thank you @moklick  for the response. I am trying to figure out how to restore a node's position when I save and restore. The issue is I am using a class component i.e 

```tsx
class Example extends React.Component<any,any> { render(){...}}
```

and not a functional component so I can't call `useZoomPanHelper`. I need the `transform` method in-order for my nodes to return to the previous positions but I am not sure how to do that in class component. The example shown here https://reactflow.dev/examples/save-and-restore/ only shows how to to do it in a functional component.  It utilizes hooks which I have no idea how to replicate in a `class component`.

**Comment by moklick** [comment]
You can use the `setTransform` of the react flow instance https://reactflow.dev/docs/api/react-flow-instance/

**Comment by atkawa7** [comment]
Thank you @moklick

**Comment by aniel928** [comment]
@moklick  how can i use the setCenter function of `useZoomPanHelper` in a class instance?  I'm using dagre for automatic layout and trying to focus on the first node on render, but I don't see a function in the instance page you linked.
