### ISSUE TITLE
Why should we add small delta when doing manually layouting?

### ISSUE THREAD

**Issue by 07akioni** [wbkd/react-flow#1351]
I see this (`+ Math.random() / 1000`) in the document.

![image](https://user-images.githubusercontent.com/18677354/125919361-b0bc3c27-0395-400d-8564-199de4720082.png)

https://reactflow.dev/examples/layouting/

Why should we do this, if the position's not updated then there's no need for updating the node.

**Comment by moklick** [comment]
The problem is that the state is not synced. When you drag a node, the position in your local elements state has no changed. When we now pass the same position again the nodes position won't update. It's the fault of the API. Hopefully we can change this in near future.
