### ISSUE TITLE
`node.__rf.width` and `node.__rf.height` is not ready in `onLoad`.

### ISSUE THREAD

**Issue by 07akioni** [wbkd/react-flow#1353]
I want to do manually layouting in `onLoad` callback. However size is not ready at that time (However DOM is ready).

It's hard to find the proper timing for first layouting.

**Comment by cfree** [comment]
I had the same issue and had to add a check to make sure the elements all had dimensions before I did my layouting:

```javascript
...
const nodeHasDimension = (el) => el.__rf.width && el.__rf.height;

const FlowBuilder = () => {
  const nodes = useStoreState(state => state.nodes);
  const edges = useStoreState(state => state.edges);
  const setElements = useStoreActions(actions => actions.setElements);
  const [shouldLayout, setShouldLayout] = useState(true);

  useEffect(() => {
    if (shouldLayout && nodes.length && nodes.length > 0 && nodes.every(nodeHasDimension)) {
        const elements = [...nodes, ...edges]
        const elementsWithLayout = getLayoutedElements(elements);

        setElements(elementsWithLayout);
        setShouldLayout(false);
      } 
  }, [shouldLayout, nodes, edges, setElements, setShouldLayout]);

  const onLoad = useCallback((reactFlowInstance) => {
    reactFlowInstance.fitView();
    reactFlowInstance.zoomTo(1);
  }, []);

  return (
    <div className={Styles['pane']}>
      <ReactFlow
        elements={initialElements}
        onLoad={onLoad}
        elementsSelectable={false}
      />
    </div>
  )
}
```

**Comment by aslakhol** [comment]
@cfree your answer seems really promising, but when attempting it all my nodes just align on top of each other. They have width and height when getLayoutedElements is called, but it seems the graph isn't updated. Is anything crucial missing from your example?

I also had to wrap the builder component in a ReactFlowProvider to get the state hooks to work.

**Comment by moklick** [comment]
They lay on top of each other because they are not layouted yet, right?

**Comment by aslakhol** [comment]
Yes, it seems the setElements is not triggering when I wait until all the elements have dimensions. 

If I don't check the dimensions and  just check the other three conditions in the example posted by @cfree above setElements works and nodes align based on whatever default height and width I put in getLayoutedElements.

**Comment by kenzouno1** [comment]
+1

**Comment by tisoap** [comment]
I was able to make it work by updating `getLayoutedElements`  from the [Layouting](https://reactflow.dev/examples/layouting/) example to update not just `position` but also `__rf.position` with new x/y values

**Comment by thim81** [comment]
@tisoap Would you mind sharing your code here on how you solved the `getLayoutedElements` with the `__rf.position`

I'm trying to solve the same problem myself.

**Comment by moklick** [comment]
Will be fixed in v10.
