### ISSUE TITLE
Removal of handle styling

### ISSUE THREAD

**Issue by cfree** [wbkd/react-flow#1354]
Is there a way to remove the styling of the `<Handle />` dot? I tried using CSS to hide it (`visibility: hidden`), but then the edge doesn't completely connect to the node.

**Comment by mikeestee** [comment]
we set its background to transparent, then it still captures mouse events but does render on screen.

**Comment by cfree** [comment]
I tried that too, same effect. I messed with the styling more and basically made the Handle 0x0 in size - that worked. Thanks!
