### ISSUE TITLE
how to set default edge type when using typescript

### ISSUE THREAD

**Issue by stonepreston** [wbkd/react-flow#1355]
I am trying to set the default edge type to step. The documentation shows that the react flow component takes an edge type prop with the default one being :

```
{
  default: BezierEdge,
  straight: StraightEdge,
  step: StepEdge,
  smoothstep: SmoothStepEdge
}
```

So I would like to make mine be something like:

```
{
  default: StepEdge,
  straight: StraightEdge,
  smoothstep: SmoothStepEdge
}
```
However I cant seem to find out how to import the edge types in order to make the above object. Any hints on how to accomplish this?

**Comment by moklick** [comment]
Hey! 

In this example we are setting up a custom edge with TS: https://github.com/wbkd/react-flow/blob/main/example/src/Edges/index.tsx#L86-L89 Does it help?

**Comment by stonepreston** [comment]
@moklick I saw that, and its similar to what I am trying to do except I am not wanting to use a custom edge type, I am simply wanting to change the default type from Bezier to Step. The problem I am running into is that the Edge types (StepEdge, StraightEdge, etc) dont seem to be exported. (Im brand new to typescript so that might be playing ito my confusion haha)

```
import { 
  EdgeTypesType,
  // This fails, error says they arent exported
  StepEdge,
  StraightEdge,
  SmoothStepEdge
} from 'react-flow-renderer/nocss';

const edgeTypes: EdgeTypesType = {
  // cant use this here since the types are not exported
  default: StepEdge,
  straight: StraightEdge,
  smoothstep: SmoothStepEdge
}
```
Is this the wrong way to go about this? Is the default type meant to be changed this way?

**Comment by moklick** [comment]
Ahh now I get it ;) That's correct. I will export the built-in edges, too!

**Comment by moklick** [comment]
Should work with v9.6.5

**Comment by stonepreston** [comment]
> Should work with v9.6.5

That did it! Thanks! Is there a way to change the path that gets displayed when you are connecting nodes? ie right now when I click on a handle and drag the bezier path is drawn, is that configurable somehow?

**Comment by Vasanthkumar26** [comment]
When we are trying to connect the nodes we are getting step view by using connectionLineType
## But after connecting the nodes the edge is going back to default [Bezier view]
## We want to have step view while and after connecting the node

Kindly help to resolve this.
Thanks in advance.

**Comment by moklick** [comment]
For that you need to use `type: "smoothstep"` for the newly created edges.

**Comment by Vasanthkumar26** [comment]
### Resolved

`const onConnect =  useCallback((params)=>
setEdges(addEdge({...params, type:"smoothstep`, edges))
);`

#### Thanks for your support

**Comment by ffarhadijs** [comment]
> ### Resolved
> `const onConnect = useCallback((params)=> setEdges(addEdge({...params, type:"smoothstep"}, edges)) );`
> 
> #### Thanks for your support

this worked for me

**Comment by ejabu** [comment]
also worked for me using this.

```tsx

const defaultEdgeOptions = {
  animated: false,
  type: 'buttonedge',
};

const edgeTypes = {
  buttonedge: ButtonEdge,
};

function Flow() {
  ...
  const onConnect = useCallback((params: Connection | Edge) => setEdges((eds) => addEdge({...params}, eds)), [setEdges]);


  return (
    <div className={styles.flow}>
      <ReactFlow
       ...
        defaultEdgeOptions={defaultEdgeOptions}
      />
    </div>
  );
}

```

**Comment by hiimnhan** [comment]
It doesn't work to me unfortunately. I create a custom edge and want it to be the default edge but even the edge has the custom type (I console.log it) it seems to render the default one (bezier path). But when add the `markerEnd` in the object in `initialEdges`, it works with that `markerEnd`. 

Custom Edge: https://github.com/hiimnhan/survey-flow/blob/main/src/components/Edge/Arrow/OneWayArrow.tsx
edge types: https://github.com/hiimnhan/survey-flow/blob/main/src/components/Edge/edgeTypes.ts
App.tsx: https://github.com/hiimnhan/survey-flow/blob/main/src/App.tsx

Am I missing something?

**Comment by Sathishkumar1072** [comment]
When i use custom edge like :
  const onConnect = useCallback((params)=> setEdges(addEdge({...params, type:"custom-edge"}, edges)) );
How to set the edge type as 'smoothstep'

**Comment by moklick** [comment]
React Flow comes with built-in edge types like "smoothstep" or "step". If you are using a custom edge component, it depends on your implementation how the edge path looks like. We do have helpers that you can use in your custom edge to draw a smoothstep path for example: https://reactflow.dev/api-reference/utils/get-smooth-step-path

Example: https://reactflow.dev/examples/edges/custom-edges (check out the ButtonEdge)

**Comment by Sathishkumar1072** [comment]
> React Flow comes with built-in edge types like "smoothstep" or "step". If you are using a custom edge component, it depends on your implementation how the edge path looks like. We do have helpers that you can use in your custom edge to draw a smoothstep path for example: https://reactflow.dev/api-reference/utils/get-smooth-step-path
> 
> Example: https://reactflow.dev/examples/edges/custom-edges (check out the ButtonEdge)

Yeah , this is working fine for me. Thanks for spending your precious time for this info.

**Comment by Nivedhavenkat16** [comment]
Hi all i need n help in node view i have use the type = smoothstep in initialedges ,what i want mean still want bend(curve) in edges , i used type bezier but i dont want that much curve ,i need curve inbetween smoothstep and bezier ,
what want to i do?
