### ISSUE TITLE
Custom nodes can still be connected even when `nodesConnectable=false`

### ISSUE THREAD

**Issue by louis-cf-lin** [wbkd/react-flow#1358]
Hi there! 

Setting the `nodesConnectable` prop doesn't affect custom node handles. In particular, it seems like toggling the `nodesConnectable` option only toggles the `connectable` class for default node handles but not for custom nodes. 

You can see some symptoms of this in the [Custom Node](https://reactflow.dev/examples/custom-node/) example. If you lock it, the custom node handle maintains the `connectable` class. And if you have two custom nodes, you're able to connect the two even if `nodesConnectable=false`.

Thanks for your work!

**Comment by moklick** [comment]
Your are right! You need to pass the `isConnectable` prop by yourself. I will update the examples! thanks for the hint.
