### ISSUE TITLE
Drag stop is not fired when you click and release without dragging

### ISSUE THREAD

**Issue by justinvdvelden** [wbkd/react-flow#1365]
Hello,

I got the properties `onNodeDragStart, onNodeDragStop` on the canvas.
When I Click and release the mouse directly only onNodeDragStart is fired.

Here is a code sandbox with console.logs:

https://codesandbox.io/s/react-flow-dragstrart-becw3

Ragads,
Justin

**Comment by moklick** [comment]
Hey @justinvdvelden 

we only fire `onDragStop` when the node was moved. Unfortunately we can't distinguish between `onNodeDragStart` and `onClick`. That's why `onNodeDrag` gets fired immediately.

**Comment by moklick** [comment]
We added a new prop called [`nodeDragThreshold`](https://reactflow.dev/docs/api/react-flow-props/#nodedragthreshold) that makes it possible to delay/prevent node drag events. Available since 11.9.0
