### ISSUE TITLE
Behavior for "move edge" operation?

### ISSUE THREAD

**Issue by mikeestee** [wbkd/react-flow#1367]
Left a comment in the discussions section a few days ago. We're trying to get target handles that are already connected to an edge to start a _move_ operation on mouse down, instead of a _new edge_ operation.

Users are very confused by the default behavior.

Any help would be appreciated!

### Discussed in https://github.com/wbkd/react-flow/discussions/1350

<div type='discussions-op-text'>

<sup>Originally posted by **ambika-dubey** July 15, 2021</sup>
I believe the current default behavior is to enable edge updates/edits from the end of an existing edge (not from the target handle that the edge connects to). Is there a way either to set some flag so that updates can happen from the target handle, or a straightforward workaround? Thank you!</div>

**Comment by moklick** [comment]
I will close this in favor of #1350
