### ISSUE TITLE
Flow is not remembering which node is dragged on top off each other

### ISSUE THREAD

**Issue by justinvdvelden** [wbkd/react-flow#1369]
Hello,

When you drag a node and then select an other node some times the node on top is pushed to the back.

Here is is a giphy to make it understand a bit better:
https://gyazo.com/e5696ce9df9b9ad5ef37a8d327210a3a

Regards,
Justin

**Comment by RickeyWard** [comment]
The node renderer has no concept of stacking order, nodes are rendered as html entities into a div so normal html stacking order applies. (unless selected, selected nodes are always on top of unselected nodes)

Its messy to stack nodes but if you wanted to get the effect you're after, you could move nodes to the bottom of the list when they are selected. essentially in onSelectionChange, take that node out of the element list, and then append it back to the bottom. This would make the most recently selected nodes last to be rendered so "ontop" of the others.

I don't think it's very valuable though, no one likes to see nodes on top of each other.

**Comment by moklick** [comment]
Good idea @RickeyWard :)
