### ISSUE TITLE
Key event handling

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#1370]
support for combinations and multiple keys for one action.

With the new api it should be possible to pass a single value, an array for multiple possibilities and a combination of keys marked with a plus sign.

Old api:

```
deleteKeyCode="Backspace"
deleteKeyCode={8}
```

new api:

```
deleteKeyCode="Backspace" 
deleteKeyCode={['Backspace', 'Delete']}
deleteKeyCode="Meta+Delete" 
```

Related: 
#1269
#1268
#1054
#1002
#1281

**Comment by mikebarkmin** [comment]
What about this API? 

```
single: deleteKeyCodes={["Backspace"]}
multiple: deleteKeyCodes={["Backspace", "Delete"]}
combos: deleteKeyCodes={[["Meta", "Delete"]]}
```

We could even leave deleteKeyCode as is to keep backward compatibility. This also allows for three key combos and should be easier/cleaner to define in TypeScript. But of could also use [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html), if we use your API suggestion.

**Comment by moklick** [comment]
There will be so many changes :D Maybe it would be good if we could keep the simple string API (we will already drop the `key` (number) API). Your idea to use a nested array for combinations is good.

**Comment by louis-cf-lin** [comment]
+1 excited for this new API.

**Comment by Ark-kun** [comment]
Is there any ETA when this issue is fixed?
We've released our project and our Mac users are really confused and cannot delete the nodes =(
https://github.com/Cloud-Pipelines/pipeline-editor/issues/1

**Comment by moklick** [comment]
you could tell your users to use Backspace or bind another key for mac users.
