### ISSUE TITLE
useNode, useEdge hooks

### ISSUE THREAD

**Issue by mikebarkmin** [wbkd/react-flow#1373]
I think it would be great, if there were a `useNode` and `useEdge` hook. Just like a `useState` hook, both should allow to update the state of a node and edge. 

A possible API could look like this:

```
const [{ data, position}, setData, setPosition] = useNode<NodeType>(id);
```

I think it would improve the developer experience and would prevent cluttering the data property of a node with an `onChange` listener, like on the front page of the documentation.

**Comment by RickeyWard** [comment]
This sounds interesting, but not sure exactly how it would work since even though there is an internal state, the library expects you to use it as if it was a controlled component. The internal state is more of an optimization.

**Comment by mikebarkmin** [comment]
That is correct. I would be totally fine with onChange props like `onNodeDataChange` and `onEdgeDataChange` for example. I think this would be in line with the other event handlers, like `onConnect` for example.

**Comment by moklick** [comment]
This is definitely one of the weak points of this library. I wrote about it here #960 and we will try to change the API in the next major release. What do you think about adding `onNodeChange`, `onEdgeChange` and `onViewportChange`?

**Comment by RickeyWard** [comment]
separating and combining nodes and edges does seem like something you end up doing a little too often, I'm in support of changing it to separate them. but the elements prop would also need to change to accommodate.

**Comment by moklick** [comment]
You are right. I think we should separate elements into `nodes` and `edges` and also split the `onElementClickHandler`.
