### ISSUE TITLE
edge sourceX and sourceY sometimes is a float 

### ISSUE THREAD

**Issue by ilanskogan** [wbkd/react-flow#1374]
I can't reproduce this consistently but my custom edge sometimes gets sourceX and sourceY as a float that is very close to the actual integer it should be. for example instead of sourceX of 150 I see 149.99989843899817 or 150.0222....
I do some calculations based on that number so this breaks my code sometimes. 
I suspect this is somehow related to zooming but can't tell for sure.
***the position of the source and target elements are always round integers
have you seen that before?

**Comment by moklick** [comment]
That's possible because of the dragging. If you need integers you could Math.round them before your calculation.
