### ISSUE TITLE
Replace d3-zoom dependency

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#1376]
d3-zoom is an excellent library but we should look out for a smaller alternative that fits our needs. Right now my favorite lib is https://github.com/timmywil/panzoom but I am open for other suggestions.

**Comment by chrtze** [comment]
we should also consider https://airbnb.io/visx/zoom-i
pros: no dependencies, react-library, not DOM-based

**Comment by moklick** [comment]
the package works great and we probably don't want to re-implement it. Maybe a good idea would be to replace `react-draggable` with `d3-grab` since it's used by `d3-zoom`.
