### ISSUE TITLE
connectors are not showing properly when bidirectional edges

### ISSUE THREAD

**Issue by srinivasuk** [wbkd/react-flow#1379]
https://ibb.co/2tfFqjw
In the above image department3 to Student3 line is not shown at edges
can this be done like this?
https://ibb.co/2cYzhWk
having curves on edges if they are hidden

**Comment by moklick** [comment]
Hey @srinivasuk 

this is not built in but you could implement a custom edge logic https://reactflow.dev/docs/api/edge-types/

**Comment by srinivasuk** [comment]
we are not familiar with that side of development, anyone in your team
available to do it. I can pay for the cost. thanks

**Comment by srinivasuk** [comment]
{
const edgePath = getBezierPath({
sourceX,
sourceY,
sourcePosition,
targetX,
targetY,
targetPosition,
});
const markerEnd = getMarkerEnd(arrowHeadType, markerEndId);
const [edgeCenterX, edgeCenterY] = getEdgeCenter({
sourceX,
sourceY,
targetX,
targetY,
});

return (
<>
<path
id={id}
style={style}
className="react-flow__edge-path"
d={edgePath}
markerEnd={markerEnd}
/>

currently we are using this edge, how can we change this code to show edges
clearly at connectors?

**Comment by srinivasuk** [comment]
[image: image.png]
i am trying to get like this as in google drawing (google docs)
[image: image.png]
when i move the box line gets automatically adjusted to curve around the
boxes and comes over the boxes

i feel this should be default behavior

Appreciate if someone point us in right direction, thanks
