### ISSUE TITLE
Read a flow

### ISSUE THREAD

**Issue by Keanottesen** [wbkd/react-flow#1382]
I do not have an issue related to the core of the library, but rather with some logic i have to implement on top. Thus my question might be out of the scope for this section. I apologize if so. But if anyone could be able to point me in direction or help with a solution it would be much appreciated!

Basically i have to compare two flows and find all matching results. So in the below example i compare flow 1, with flow 2. In this example there are three matching results colored in green.

I need to know some inner state of the specific matching examples, so cannot just know the number of occurrences. I need to figure out where the specific elements is and what data lies inside of them. In the first example below I would basically have a result of 3 arrays consisting of 3 different flow elements with two nodes and one edge in each.

My initial though was to compare each edge and its respective sources and targets 1 by 1. However, when i tried writing the solution, it failed on more complex examples, where there might be more edges in the flow i was comparing. Like the second example drawn below.

Hope my problem makes sense. Any help is much appreciated!

| Flow 1  | Flow 2  | Result | 
|---|---|---|
| ![condition](https://user-images.githubusercontent.com/47158972/126643396-2be0c365-17cd-487a-8480-1c565c10af63.png)  | ![workspace](https://user-images.githubusercontent.com/47158972/126643390-2ec5a4e7-c761-4340-8968-ae7b5c626c3e.png)  | ![result](https://user-images.githubusercontent.com/47158972/126644303-cbe06b28-87e5-4a39-a2b0-ebb743d80a6b.png)|
|![example2](https://user-images.githubusercontent.com/47158972/126749958-3a4b2c74-90be-4b42-bb69-5d8373bf27ae.png)| ![flowflow](https://user-images.githubusercontent.com/47158972/126750593-3191ba51-67fa-41af-953b-44d681b00bdb.png)|![flow22](https://user-images.githubusercontent.com/47158972/126750426-7a02de02-56cb-4bb8-805f-6aed08e19df0.png)|

**Comment by datoslabs** [comment]
I have had to implement something similar in my solution; what you laid out is the same approach I took.  Could you provide more details on what's wrong with the more complex example?

**Comment by Keanottesen** [comment]
Basically i fail to implement a solution that can keep the history. When looping through the arrays and solutions can keep appearing down different paths. The fact that you need to follow the path synchronously makes me struggle to come with a viable solution that can keep saving, disregarding and reading. I would love to see you implementation if a may @datoslabs

**Comment by datoslabs** [comment]
My implementation has since changed quite a bit but the basic logic is as follows:

```
let indexed = {nodes:{}, edges:[]};
elements.reduce((accum, x)=>{
	if (x.source && x.target)
		accum.edges.push(x);
	else 
		accum.nodes[x.id] = x;
	return accum;
},indexed);

let edgeDefIndexed = {}
indexed.edges.reduce((accum, x)=>{
	accum[`${indexed.nodes[x.source].data.label}-->${indexed.nodes[x.target].data.label}:${x.label}`] = {
		from: indexed.nodes[x.source],
		to: indexed.nodes[x.target],
		edge: x
	};
	return accum;
}, edgeDefIndexed);
```
Then I compare the `edgeDefIndexed` keys from both graphs to identify the duplicates (or changes in my case).

**Comment by Keanottesen** [comment]
Alright i need to know where the subgraphs lie. I have since learned that the problem is similar to a Subgraph isomorphism problem ( https://en.wikipedia.org/wiki/Subgraph_isomorphism_problem ).
