### ISSUE TITLE
Feature idea / question

### ISSUE THREAD

**Issue by bentron2000** [wbkd/react-flow#1385]
I find myself creating some logic to dynamically reassign links to different handles as I move nodes around so that they stay looking lovely and don't tie themselves in knots :)

At the moment I'm using the centre of the node to calculate positions/angles to decide when to switch a link to new handles - but this is not ideal. I'd really like to have a reference to the handles themselves so I can calculate on the relative positions of two handles at either end of an edge.

Question: How might I get a reference to these handles?

failing that...

Feature Request: Can I get references to the handles somehow? 

:)

Thanks for the awesome library :)

**Comment by datoslabs** [comment]
Since `handles` are rendered by `nodes`, and assuming you have a custom `node` implementation with multiple `handles` (as `DefaultNode` only supports 1 input and 1 output `handle` each), wouldn't you have access to those handles when the node is moved?

**Comment by moklick** [comment]
We are now forwarding the ref. Released in v9.6.7
