### ISSUE TITLE
Detect click outside nodes

### ISSUE THREAD

**Issue by christinehesher** [wbkd/react-flow#1400]
I have a custom dropdown inside nodes which should open on button click and close if the user clicked anywhere outside of it. So, I added a ref to the dropdown and an event listener to handle clicks which works fine if I click somewhere inside the selected node or any other node. But it doesn't work  if I click outside any nodes (it doesn't matter if there is Background component or not). What can I do? Please help, I've been at it for hours now...

**Comment by moklick** [comment]
Could you use the `onPaneClick` handler?

**Comment by christinehesher** [comment]
Thank you @moklick, it works!

**Comment by TomekDevK** [comment]
Hello, i have same issue.

Is there any way to handle 'onClickOutside' method. I would rather not to use 'onPaneClick', beacause i would like to manage dropdown visibility from inside a component. I tried to find a way to make it work, but i failed.

**Comment by lukoboi** [comment]
I found a solution. You can add an `onBlur` event handler to the element which triggers when clicking anywhere outside the element. example:
`<div onBlur={() => handleClickOutside()} />`

**Comment by Mu-xue** [comment]
> how to stop event propagation to `onPaneClick` after `onConnectEnd`

@ivetrivel Sorry, I have the same problem,  how to solve it?

**Comment by imvetri** [comment]
@Mu-xue sorry. I forgot.

Try this. Add a click handler at the parent dom level. 

Check and see if if the event object has information about the source. The event object will have information on which interaction started event.

Go through the properties of event object for two cases  and let me know what you find.

**Comment by bilal-uforia** [comment]
I want to do the same , and I have which is not input, that needs to get closed when click outside but it now works,
I want to handle it in the component, I dont want to use onPaneClick , also I want to click by adding listener to the doucment, I added but that listener is not called

const handleClickOutside = (event) => {
        console.log(  !divRef.current.contains(event.target));
        if (divRef.current && !divRef.current.contains(event.target)) {
            setShowDynamicText(false);
        }
    };

    useEffect(() => {
        document.addEventListener('mousedown', handleClickOutside);
        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, []);

**Comment by imvetri** [comment]
Hi. The tool is bloated. find contact us page in ui-editor.com anf tell me
your concerns.
