### ISSUE TITLE
getSmoothStepPath() is wrong when sourcePosition == 'left'

### ISSUE THREAD

**Issue by leonbloy** [wbkd/react-flow#1403]
When an edge goes from right to left, getSmoothStepPath() computes the path wrong, it starts vertically instead of horizontally

Eg:

```
let sourceX = 200; 
let sourceY = 200;
let sourcePosition = 'left'
let targetX = 100; 
let targetY = 100;
let targetPosition = 'right';
let borderRadius = 0;

let path= getSmoothStepPath({sourceX,
  sourceY,
  sourcePosition,
  targetX,
  targetY,
  targetPosition,
  borderRadius}) ;
```
  
returns `M 200,200L 200,150Q 200,150 200,150L 100,150Q 100,150 100,150L 100,100`
which is wrong.

If we reverse source and target, then we get the right path:
`M 100,100L 150,100Q 150,100 150,100L 150,200Q 150,200 150,200L 200,200`

**Comment by moklick** [comment]
Fixed by 03887ad79f7404359c97db9473d4cdc1061d46af
