### ISSUE TITLE
Is scroll supported as a move option

### ISSUE THREAD

**Issue by megashot** [wbkd/react-flow#1417]
Hello,

Is scrolling as an option to move up/down left/right supported (or planned) out-of-the-box. I was able to make it work with css but when you zoom in/out or 'fit content' it gets messed up.

_Thank you this amazing library its easily customizable and performant. :)_

**Comment by TitoGrine** [comment]
You can set the `panOnScroll` to true on your `ReactFlow` component to allow panning using the scroll wheel.

If you use a trackpad you can easily move in all four directions, but using a mouse I'm not sure how to move horizontally. The standard `shift+scroll` doesn't seem to work.
You can still zoom with the scroll wheel by pressing `ctrl` or you can set a custom keycode using `zoomActivationKeyCode`.

For more information check the [Prop Types page](https://reactflow.dev/docs/api/component-props/) from the docs.

**Comment by megashot** [comment]
Hey @TitoGrine 

My problem is not the scrolling itself but the size when react-flow is in scroll-container. when I open the page the ReactFlowState.width/height do not take into consideration the 'scroll' part of the parent.

**Comment by megashot** [comment]
With _panOnScroll_ works pretty good but if try to move the scrollbars everything goes crazy, dots/lines do not get rendered.

**Comment by moklick** [comment]
@megashot could you open a codesandbox that illustrates your issue?

**Comment by megashot** [comment]
Hello @moklick 

Here is an example: https://codesandbox.io/s/xenodochial-yalow-1pgk6

(if you try to scroll down using the scroll-bars the dots/lines do not get rendered)

**Comment by TitoGrine** [comment]
@megashot Well, I couldn't figure out what the issue was, it doesn't happen just for the Background dots, it can also affect the rendering of the Nodes and Edges themselves.  

Either way, if you remove the `style` prop and instead add the following CSS rule you get your scrollbars and everything gets rendered even using the handles. 
```css
.react-flow__zoompane {
  max-height: 100%;
  max-width: 100%;
  overflow: scroll;
}
```
Here's your [codesandbox code](https://codesandbox.io/s/xenodochial-tharp-ijgfz?file=/src/styles.css) with these changes.

Hope this is enough to get what you were looking for.

**Comment by megashot** [comment]
@TitoGrine Thank you now everything works, have a great day.

**Comment by RodolfoRdz11** [comment]
I have the same issue with scrollbars, the background get rendered but not the connection lines
![Sin título](https://user-images.githubusercontent.com/38471637/156684551-abaad1e5-a785-43dd-ad7e-7cdb0503caa1.jpg)

**Comment by vaniprasad338** [comment]
After adding the native scroll bar and trying to create edges, the edges are bending backwards.
