### ISSUE TITLE
loses structure when changing flow in different pages

### ISSUE THREAD

**Issue by KirillAleshkin** [wbkd/react-flow#1418]
I have two flows in different forms when switching with a router from one flow to another, flow loses his shape.
And when i refresh the page it returns his form
I use react-flow and dagre
upd: i used ReactFlowProvider and it didn't help me

my structure is 
ModalButton
Flow1
ModalButton

ModalButton
Flow2
ModalButton

Flow1 = () => {

return (
Genetic Flow
)
}

Flow2 = () => {

return (
Genetic Flow
)
}

Thank you for your amazing work!

**Comment by KirillAleshkin** [comment]
<ModalButton>
Flow1
</ModalButton>

<ModalButton>
Flow1
</ModalButton>

Flow1 = () => {

return (
Genetic Flow
)
}

Flow2 = () => {

return (
Genetic Flow
)
}

**Comment by KirillAleshkin** [comment]
<ModalButton
Flow1
ModalButton>

**Comment by KirillAleshkin** [comment]
ModalButton
Flow1
ModalButton

ModalButton
Flow2
ModalButton

**Comment by moklick** [comment]
You need to wrap each flow with its own ReactFlowProvider.
