### ISSUE TITLE
Using fitView with resizable container

### ISSUE THREAD

**Issue by pjaspinski** [wbkd/react-flow#1419]
Hi, I stumbled upon a problem when using ReactFlow with [React-RND](https://github.com/bokuweb/react-rnd). 
React-RND provides a resizable component, in which I want to place a ReactFlow diagram.

Here is a [sandbox](https://codesandbox.io/s/react-flow-in-react-rnd-fitview-problem-4v2xo). You can drag the dark border to resize the container and see the issue.

**Implementation**
When user stops resizing the component, the `onResizeStop` event is fired. I use it to set updated container dimensions to the state.
```js
onResizeStop={(e, direction, ref, delta, position) => {
  setDiagramWidth(ref.style.width);
  setDiagramHeight(ref.style.height);
}}
```
This state is then passed as props to the component containing ReactFlow diagram.
```js
<Diagram width={diagramWidth} height={diagramHeight}></Diagram>
```
These are then used to set dimensions of a div containing the diagram.
```js
return (
  <div style={{ height, width }}>
    <ReactFlow
      // ...
    >
        // ...
    </ReactFlow>
  </div>
);
```
In the diagram component there is also a `useEffect` that calls `fitView` when these props change.
```js
React.useEffect(() => {
  fitView();
}, [width, height, fitView]);
```

**Problem**
It seems that `fitView` always uses dimensions from before the last resizing. I couldn't find a solution that would fully fix it. Is there a way to force it to use updated dimensions? Or is it a problem with `fitView`'s implementation?

I would really appreciate any help on this one.

**Comment by pjaspinski** [comment]
I achieved this behaviour by adding a `fitVIewToDimensions` function, that takes dimensions as a parameter. If anyone faces this problem in the future, here is my [fork](https://github.com/pjaspinski/react-flow).

**Comment by Krithika3** [comment]
@pjaspinski do you have a code snippet for the same? I am trying to do something similar and would be of help to me

**Comment by pjaspinski** [comment]
I don't have access to the codebase that I was working on when I created this issue, but I guess, that it was something along these lines:
```js
const Component= () => {
  const {width, height} = useStore(sizeSelector);

  useEffect(() => {
    fitView();
  }, [width, height]);

  return ...;
};
```
Just check what is the structure of this lib's internal state and prepare `sizeSelector` that will get you these dimensions. Hope it helps!

**Comment by shazlehu** [comment]
I've been searching for this answer for months, and at long last, here it is.

In Typescript:
```typescript
  const widthSelector = (state: { width: any }) => state.width;
  const heightSelector = (state: { height: any }) => state.height;
  const reactFlowWidth = useStore(widthSelector);
  const reactFlowHeight = useStore(heightSelector);

  useEffect(() => {
    reactFlowInstance.fitView();
  }, [reactFlowWidth, reactFlowHeight, reactFlowInstance]);
```
