### ISSUE TITLE
Flow collapses

### ISSUE THREAD

**Issue by Alykirill** [wbkd/react-flow#1422]
I have one flow component and I transfer it to tree different places in the project. now, inside the project, when I switch between flows, the shape of my flow collapses
Please help my (reactFlowProvider didn't help)

my structure is

ModalButton
{...Flows}
ModalButton

Flow1 = () => {
return (
Genetic Flow
)
}

Flow2 = () => {
return (
Genetic Flow
)
}

Generic Flow = () =>{
 ReactFlow
            className="react-flow"
            elements={layoutedElements}
            nodeTypes={nodeTypes}
            arrowHeadColor="black"
            minZoom={1}
            maxZoom={1}
            defaultZoom={1}
            defaultPosition={[150, 0]}
            paneMoveable={false}
            nodesDraggable={false}
            nodesConnectable={false}
            elementsSelectable={false}
          
return 
}

Thank you!

**Comment by moklick** [comment]
You need to wrap each flow with its own ReacFlowProvider.
