### ISSUE TITLE
all surrounding handles

### ISSUE THREAD

**Issue by Keanottesen** [wbkd/react-flow#1436]
Hello

I am trying to build a custom node, with handels surrounding the entire surface. However, it seems like the library cannot handle when calculating handleIds on the run. Is this true or am i missing anything

Code:
```
 {[...Array(Math.round(containerRef?.current?.offsetWidth / 5) || 0).keys()].map(x => (
        <Handle
          style={{ ...handleStyle, left: 5 * x || 5, top: 0 }}
          type="source"
          id={`top${x}`}
          position={Position.Top}
        />
   ))}
```

The error occurs in ConnectionLine

Error:
Uncaught TypeError: Cannot read property 'find' of null
    at ConnectionLine (ReactFlow.js:8994)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.wrapped (build.umd.js:956)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)

**Comment by jonra1993** [comment]
Hello, @Keanottesen @moklick  I have been used this library for a while it is really easy to understand and use. Currently, I am facing a new challenge for customizing handles. Do you have any suggestions on how to do something similar to this?. This kind of block is really common in email automation builders.

![image](https://user-images.githubusercontent.com/23468720/129068875-bb051fad-89c5-4f12-b90c-65ff30499db3.png)

**Comment by Keanottesen** [comment]
@jonra1993 

You just need to make a custom node that is circular and the put an icon in the middle. The handles I guess should be on the top en button. And if it is like customer.io or something, they all should expand from the same point. So you can just make the handles go across the upper half and the lower half, and be invisible

**Comment by jonra1993** [comment]
Thanks, @Keanottesen I am going to check customer.io also after reading some posts styled components seems to be an excellent option for customization.

**Comment by datoslabs** [comment]
@Keanottesen, I have in the past implemented a custom node with configurable source/target handles similar to what you have tried and did not encounter any issues.  My current implementation has changed to allow users to drag and place the handle alongside the edge of the custom node.  From the stack trace and `ConnectionLine.tsx` file in the repository, there is no code referencing 'find' property; do you have an example in codesandbox?

**Comment by moklick** [comment]
closed due to inactivity. Feel free to open it again if the issue still persists.
