### ISSUE TITLE
Ugly edge ids if sourceHandle and targetHandle aren't specified

### ISSUE THREAD

**Issue by Sajakiari** [wbkd/react-flow#1438]
Hi. 

Currently if an edge doesn't have `sourceHandle` and `targetHandle` the generated id will look like this:
`reactflow__edge-{source}null_{target}null` because of the string conversion.

It would be nice to have a check for null handlers to have pretty ids.

PS. Thanks for the great library!

**Comment by Azim-Ahmed** [comment]
you can add new custom id ,, when you call onConnect Function.

**Comment by bonniss** [comment]
See #1364

**Comment by Sajakiari** [comment]
Thanks for the replies, problem solved!
