### ISSUE TITLE
Drag and drop function of sidebar example delay error

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1440]
Hi, When I try to drap and drop it has a delay and delay increases if theres a animated edge on the board, in chrome on linux has a lot of delay even without animated edges, but in firefox doesnt have anyone until I put any animated edge on it... On normal edges the bug doesnt occur
![image](https://user-images.githubusercontent.com/36650520/129246383-efc14d71-a473-4619-b097-5e2265222b5c.png)

**Comment by moklick** [comment]
Please re-open if this issue still persists.
