### ISSUE TITLE
Looks the is no way to set custom color of arrowhead for selected edge

### ISSUE THREAD

**Issue by fedulovivan** [wbkd/react-flow#1443]
Reproduceble on demo page - https://reactflow.dev/examples/edges/.
Since arrowhead is renderred with **marker.react-flow__arrowhead** which is located outside of **.react-flow__edge.selected** its not possible to "sync" its color with edge:
<img width="381" alt="Screenshot 2021-08-13 at 13 00 14" src="https://user-images.githubusercontent.com/752105/129340656-a52d57af-9c7f-4244-9c43-505c67b5ddb5.png">

**Comment by tomc278** [comment]
To achieve this I just created a CustomEdge following the example here https://reactflow.dev/examples/edges/, added a new arrow marker of a darker colour and then set that if the **selected** prop is true in the custom component.

Total work around obviously and I agree that having the colours synced up that would be better :)

**Comment by moklick** [comment]
since v10, an edge has a `markerStart` and `markerEnd` option, that allows to pass a color https://reactflow.dev/docs/api/edges/edge-options/#markerstart--markerend-options

**Comment by a798032825** [comment]
> since v10, an edge has a `markerStart` and `markerEnd` option, that allows to pass a color https://reactflow.dev/docs/api/edges/edge-options/#markerstart--markerend-options

the color cant be changed when I want to select the edge for some cases

**Comment by ShrutiChandak19** [comment]
> To achieve this I just created a CustomEdge following the example here https://reactflow.dev/examples/edges/, added a new arrow marker of a darker colour and then set that if the **selected** prop is true in the custom component.
> 
> Total work around obviously and I agree that having the colours synced up that would be better :)

can you share an example where you passed multiple markerEnd?

**Comment by waqarilyas** [comment]
Checkout this example. It has full custom edge implementation with color, width, type, and other styling. Posting to help anyone facing issues with custom edges in react flow:

[custom-edge.tsx](https://gist.github.com/waqarilyas/bd92dd063112795b9f7f17433630ab7a)
