### ISSUE TITLE
Node drag causes React-Flow's internal state to get out of sync

### ISSUE THREAD

**Issue by datoslabs** [wbkd/react-flow#1444]
I encountered a problem where after node is dragged, its position becomes stale and cannot be updated via changing node.position property; the root cause of this seems to be related to the following code in the reducer:

https://github.com/wbkd/react-flow/blob/4b043bceccf41ae1edbd52e2919e1bf5a65aef99/src/store/reducer.ts#L44-L46

In my testing, the condition is never `true` and therefore allows `node.__rf.position` to get out of sync with `node.position`; I believe the correct logic should be 

```
if (storeNode.__rf.position.x !== propElement.position.x || storeNode.__rf.position.y !== propElement.position.y) { 
   updatedNode.__rf.position = propElement.position; 
 } 
```
Please note, this bug only surfaces **after** node position has been updated by node drag and subsequently updating the node's position via `node.position` will cease to have an effect on the node's position (ie `node.__rf.position` becomes out of sync with `node.position`).

**Comment by jossh88** [comment]
If u are saving nodes in local state than u update same inside onNodeDragStop with new position.
Else have a look here https://github.com/wbkd/react-flow/issues/916#issuecomment-788095320

**Comment by datoslabs** [comment]
Thank you @jossh88, however, this issue is different from #916.  The inconsistencies I mentioned are not between my local state and the internal react-flow state; rather, they are observed in internal react-flow state.  As a result, the API behaves inconsistently concerning node position updates via `node.position` property.  

Before node drag, programmatically updating `node.position` will move the node to the specified position; after node drag, programmatically updating `node.position` has no effect on the node position.  In other words, suppose a node has a starting position of `{x:0,y:0}`:

**Before node drag**
Updating local state's `node.position = {x:10, y:10}` will trigger the API to move the node to (10,10).  Using `useStoreState`, I can see the internal state where both `node.position` and `node.__rf.position` have been updated to `{x:10,y:10}`.

**After node drag**
Suppose we drag the node to a new position {x:50, y:50} via mouse then update local state's `node.position = {x:20, y:20}`, using `useStoreState` the internal state now shows `node.position={x:20,y:20}` and `node.__rf.position={x:50, y:50}`.  Since `NodeComponent`'s `xPos` and `yPos` properties are based on `node.__rf.position` as shown from the code excerpt below, the node is not moved to (20,20):

https://github.com/wbkd/react-flow/blob/64d1913356d171fd2c4303c918c3e375f57cbee7/src/container/NodeRenderer/index.tsx#L85-L86

**Comment by Danybs** [comment]
when drag elements to flow if move nodes, dont update position state 
i updated elements state position this way:

```
    const onNodeDragStop = (event, node) => {
        let elementsCopy = elements;
        let index = elements.findIndex(element => element.id === node.id);
        let newPositionNode = elements[index];
        newPositionNode.position = node.position;
        elementsCopy.splice(index, 1, newPositionNode);
        setElements(elementsCopy);
    };
```

regards

**Comment by datoslabs** [comment]
Thank you @Danybs; the PR I submitted to fix this issue had been approved, hopefully, it will be released soon.  Per my experiment and writeup above, after node drag `node.position !== reflect node.__rf.position`; this is why the fix needs to be made to the reducer as any attempts to programmatically update a node's position after node drag event will not physically move the node since rendering is based on `node.__rf.position` NOT `node.position`.

**Comment by datoslabs** [comment]
Sharing an update on this issue.  Tl;dr version is that for each node, there are 3 position values with `node.__rf.position` (from the store) as the source of truth, in order to reliably update the node position programmatically one needs to:

1.  Deep clone the element or perform a shallow clone but make sure the position object is a new instance like the following:
```
  setElements(els=>{
    els.map(e=>{
      if (!isEdge(e)) {
        const clone = {...e, position:{x:e.position.x, y:e.position.y}}.
        ... //logic to update clone's position
        return clone;
      }
    });
  });
```
2.  If the current element position is needed to determine the new position, obtain it from store's `node.__rf.position` as both `element.position` and store's `node.position` may not reflect the current element position (ie after node drag). 

**Now the long version:**
The root cause of the problem I originally reported is due to the use of shallow copy in `SET_ELEMENTS` reducer; when shallow copy is also used in `setElements` call like the following:
```
  setElements(els=>{
    els.map(e=>{
      if (!isEdge(e)) {
        const clone = {...e}.
        ... //logic to update clone's position
        return clone;
      }
    });
  });
```
Both `node.position` (ie `storeNode.position` in the reducer code) and `element.position` (`propElement.position` in the reducer code) in the reducer ends up referencing the same instance because `position` is a nested object.  Furthermore, before the node is dragged to a new position when node position is updated programmatically via `setElements()`, all 3 copies of `position` point to the same instance, ie `node.position === node.__rf.position === element.position`, which is the reason the position update via `setElements()` appears to "work".  However, as soon as the node is dragged out of position the link breaks and `node.__rf.position` references a different instance while `node.position === element.position`.  Any further updates to the node position via `setElements()` using shallow copy will result in `if (storeNode.position.x !== propElement.position.x || storeNode.position.y !== propElement.position.y)` statement in the reducer to evaluate to false since `storeNode.position === propElement.position` as explained above; hence failed to update the node's position `__rf.position`.  This is why it's essential to either perform a deep clone or to create a new `position` object in a shallow clone when attempting to change element's position programmatically via `setElements()`.

**An even more detailed explanation, for documentation purposes:**

The reason react-flow keeps 2 internal states of the node positions (ie `storeNode.position` vs `storeNode.__rf.position`) is to keep track of the on-screen position vs user specified position via `setElements()`. This way if user altered the node position via node drag it can detect in the next 'setElements()' update if the node position needs to be updated by checking `if (storeNode.position.x !== propElement.position.x || storeNode.position.y !== propElement.position.y)` in the `SET_ELEMENTS` reducer before updating `storeNode.__rf.position`.  Without this mechanism, the node will jump back to its old position (before drag) after non-position updates such as changing the node label.  In other words: if user performs the following steps: 1). drag nodeID 'A' to new position, 2). update nodeID 'A' label, without the 2 internal states, nodeID 'A' will jump back to the original position before step 1) unless user takes the extra step to always sync up `element.position` with `node.__rf.position` in each `setElements()` call.  This is one of the reasons react-flow is a semi-controlled react component. 

This logic/design is sound except because `position` is a nested object and since the reducer uses a shallow copy, the position object inside the store (both `storeNode.position` as well as `storeNode.__rf.position`) is actually the same instance as the `position` object provided through `setElements()` (ie `propElement` in the reducer code).  Therefore, **before node drag**, `propElement.position === storeNode.position === storeNode.__rf.position`; **after node drag**, `UPDATE_NODE_POS_DIFF `reducer is called and assigned a new instance to `storeNode.__rf.position` at which point `propElement.position === storeNode.position !== storeNode.__rf.position`. Because of this it gives the "illusion" that node position is being updated by `setElements()` before node drag even though `if (storeNode.position.x !== propElement.position.x || storeNode.position.y !== propElement.position.y)` always evaluates to `false` unless user performs a deep clone before updating the node position.

**Comment by moklick** [comment]
This is fixed in v10. You can now decide if you want to use React Flow as a controlled or uncontrolled component: https://reactflow.dev/docs/getting-started/core-concepts/
