### ISSUE TITLE
Pan on Space + Move

### ISSUE THREAD

**Issue by gfox1984** [wbkd/react-flow#1448]
Hi,

I would like to restrict the panning to when the space key is pressed (it's common in tools to use Space + Move to pan). I thought this would be straightforward but I could not find a way to do it. Is there something like:
- a property (eg: panActivationKeyCode)?
- a way to enable / disable panning (so that I can enable it only when Space is pressed)?
- an event that can be cancelled (eg: in onMoveStart)?

Else, do you have any suggestion or workaround?

**Comment by gfox1984** [comment]
OK, I found a way using `react-hotkeys-hook` and the `paneMoveable` property:

```
const [isSpacePressed, setIsSpacePressed] = useState(false);
useHotkeys('space', (ev) => {setIsSpacePressed(ev.type === 'keydown')}, {keyup: true, keydown: true}); 

[...]

<ReactFlow
  [...]
  paneMoveable={isSpacePressed} />
```

Having said that, it might be easier for implementers if there was a property exposed for choosing the key that activates panning, just like we have for zooming and selection? Also I noticed you have a useKeyPress hook, which could be exported, as an alternative if we didn't want to add a new property (but I feel like there should be a guide somewhere on how to implement this).

**Comment by moklick** [comment]
This will be easy with v10 you can do:

```jsx 
import ReactFlow, { useKeyPress } from 'react-flow-renderer';

function Flow() {
  const spacePressed = useKeyPress('Space');

  return <ReactFlow panOnScroll={true} panOnDrag={spacePressed} nodes={[]} edges={[]} />;
}
```
