### ISSUE TITLE
Create custom nodes as class components?

### ISSUE THREAD

**Issue by D-Niermann** [wbkd/react-flow#1454]
Is it possible to create custom Nodes as class components?
I want to be able to define a base custom node where all my other custom nodes derive / inherit from. 
If this behaviour is also possible with functional components that would also be fine.

Currently I use the following syntax to define custom Nodes:
`const BasicCustomNode: FC<NodeProps<dataType>> = ({ data, isConnectable }) => {...}`
`export default memo(BasicCustomNode);`

**Comment by moklick** [comment]
Hey @D-Niermann 

this should be possible. You can only extend class components. Did you see this https://reactjs.org/docs/composition-vs-inheritance.html? Maybe it could help you to find other solutions for your problem here.

**Comment by moklick** [comment]
Please re-open if the issue still persists.
