### ISSUE TITLE
Feature request: Pass "selected" to MiniMap nodeClassName callback

### ISSUE THREAD

**Issue by fedulovivan** [wbkd/react-flow#1461]
Use case: Render selected nodes on minimap with custom styling (e.g. with custom border color).
As present time only _node_ object is passed to _nodeClassName_ callback, which is missing selected property (assume it's not included by design, since _interface Node_ is also missing it).

Possible changes for API:

1. Add second argument to nodeClassName callback, like `nodeClassName(node: Node, extraProps: { selected: boolean })`.
2. Extend Node interface with selected prop (this may require more significant update of codebase).

**Comment by moklick** [comment]
Added since v10.
