### ISSUE TITLE
Deselect the selected element when clicking it with the multi selection key pressed

### ISSUE THREAD

**Issue by gfox1984** [wbkd/react-flow#1462]
I am using `multiSelectionKeyCode` to select multiple elements, so far so good. Now I would also expect that clicking an element that was already selected while the key is pressed would deselect it. Currently, it does nothing (the element remains selected).

I'm not sure what's the default behaviour on Mac, but this is common behaviour on Windows at least, and also on most tools that handle multiple selection, such as Google Drive.

**Comment by moklick** [comment]
released in v10.3.0
