### ISSUE TITLE
Disable Keys / Shortcuts

### ISSUE THREAD

**Issue by dominikspiertz** [wbkd/react-flow#1463]
Hello dear react-flow team,
as recently discovered, react flow now also supports specific key shortcuts for various functions. We developed with react-flow for a longer time and build a custom interface and shortcut behaviour for our react-flow visualization. Therefor we want to disable the shipped behaviour of react flow and the shortcut keys. By now we would have to provide unreachable keys like `null` to props like `deleteKeyCode` or similar. When from time to time we update react-flow and there will be more shortcuts added we will most likely miss updates and possibly break our experience on not disabled shortcuts. For us it would be the best to set a prop `keys` to `false` so we can opt-out of the provided shortcuts however they are going to improve or change. Would it be possible to have a prop like that in the near future?

**Comment by moklick** [comment]
We will not add a general `keys` option to opt-out all shortcuts but added `null` as a valid type to remove the handler. We only have three short cuts and we don't plan to add more.
