### ISSUE TITLE
Multiline label on the edge

### ISSUE THREAD

**Issue by MrBattary** [wbkd/react-flow#1464]
Greetings!
As for the logic of my application, I can have multiple edges, from one node to another. 
Although they have different labels, they all follow the same path, overlapping each other.
I decided to combine these edges into one, simply increasing the label, using a line break. 
But after some time, I realized that this was impossible and decided to use (tspan).
But their use leads to strong visual bugs:

**Through y**
![download1](https://user-images.githubusercontent.com/49065223/130441802-40e01006-4995-4819-be36-836ad92ea69d.png)

**Through dy**
![download2](https://user-images.githubusercontent.com/49065223/130441859-c460ab07-7d84-4eee-9db9-e7b4dfd006c1.png)

Any suggestions, on how could I fix this?

**Comment by moklick** [comment]
If tspans do not work for you, you can escape svg world and use `foreignObject` and use normal divs. That is what we do in our edge button example https://reactflow.dev/examples/edge-with-button

**Comment by moklick** [comment]
Since v11.2.0 it is possible to use a div based edge label renderer that should make this way easier https://reactflow.dev/docs/api/edges/edge-label-renderer/
