### ISSUE TITLE
Scroll as move option breaks on zoom

### ISSUE THREAD

**Issue by megashot** [wbkd/react-flow#1465]
Hello,

[_(previously I asked about adding scroll as pan-option)_](https://github.com/wbkd/react-flow/issues/1417)

[Codesandbox](https://codesandbox.io/s/sharp-dubinsky-t9w2o?file=/src/Flow.tsx)

I am facing a new issue, when you max zoom and then go back the view breaks and you can't see the top/bottom nodes.

Thank you :)

**Comment by TitoGrine** [comment]
Can you elaborate on the issue? Using your codesandbox I couldn't replicate anything similar to what you are describing..

**Comment by moklick** [comment]
Hey @megashot 

this css rule in your example breaks the internal logic:

```css
.react-flow__zoompane {
  max-height: 100%;
  max-width: 100%;
  overflow: scroll;
}
```

The `panOnScroll` should work for you. I re-visited your other issue. There it's broken because of your passed style:

```jsx
style={{
  maxHeight: "100%",
  maxWidth: "100%",
  overflow: "auto",
  overscrollBehavior: "none"
}}
```

You should never see a scrollbar within your React Flow container. +

When you check this example https://reactflow.dev/examples/interaction/ and activate `zoomOnScroll` and `paneMoveable` isn't this what you are looking for?

**Comment by megashot** [comment]
Hello @moklick 

 I would like to have a scroll bar, my "test" users find it easier the navigate because they can see where the last nodes (both x,y axis) are and they don't have to keep scrolling.  I tried with panOnScroll, the scrollbar appears but when you drag up/down it just keep going and does not stop when you are at the last node (by position).
 
 Thank you for your time :)

**Comment by megashot** [comment]
I forked the library and managed to make it work by removing the translate X-Y from transform, making all svg visible even if they are outside of the draw area and manually managing the width and height (when width is 1000px and node is at 900px expand the area by 1000)

**Comment by FedkoAnastasiia** [comment]
> I forked the library and managed to make it work by removing the translate X-Y from transform, making all svg visible even if they are outside of the draw area and manually managing the width and height (when width is 1000px and node is at 900px expand the area by 1000)

I ran into the same problem as you. Can you share the solution?

**Comment by megashot** [comment]
> > I forked the library and managed to make it work by removing the translate X-Y from transform, making all svg visible even if they are outside of the draw area and manually managing the width and height (when width is 1000px and node is at 900px expand the area by 1000)
> 
> I ran into the same problem as you. Can you share the solution?

I ended up building my own, changing react-flow to suit my case was almost impossible + the license thing didn't help
