### ISSUE TITLE
Edges crossing through the nodes

### ISSUE THREAD

**Issue by aashan007** [wbkd/react-flow#1468]
Hi there,

I was working with the react-flow library for a project and was trying out the coneection of nodes through edges. I have few doubts on this.

![image](https://user-images.githubusercontent.com/17931542/130936056-ef9ad8c4-cc1b-4a22-84db-bf8b9e735899.png)

1. In the above image, I have placed my handle for node 2 at left side and for node 1 at bottom. Now my expectation was edge would originate from the left side, instead it overlapped through the node 2. 
  Is there a way I can pass my edges through the open spaces instead of crossing over the nodes? 

2. I am using step as edge type. As we can see for the connection between node 1 and node 2 looks more like a strainght line. Can we have a edge like the below onet? 

![Screenshot from 2021-08-26 14-49-46](https://user-images.githubusercontent.com/17931542/130937339-5f96e6de-9df3-4c7a-9fe2-154148c89a72.png)

Is the above issues solvable with the react-flow? Thanks

Regards,
:)

**Comment by awaisshah228** [comment]
For anyone looking for a solution to edges crossing through nodes — I built **[avoid-nodes-edge](https://www.npmjs.com/package/avoid-nodes-edge)**.

Edges automatically find paths through open spaces, routing around all obstacle nodes with clean orthogonal (90-degree) turns. Powered by libavoid WASM running in a Web Worker.

**[Live Demo](https://avoid-nodes-pro-example.vercel.app)** | **[GitHub](https://github.com/awaisshah228/react-flow-avoid-nodes-routing)**

```bash
npm install avoid-nodes-edge libavoid-js
```

Works with React Flow v12+.

**Comment by tisoap** [comment]
I'm the creator of [react-flow-smart-edge](https://github.com/tisoap/react-flow-smart-edge) , a library that uses using A* pathfinding to route edges around other nodes, avoiding intersections. It has smart equivalents for every type of edge React Flow has. It's been updated to work with React Flow 12.
