### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by Shafahummer** [wbkd/react-flow#1483]
Typescript showing error for Handle position prop.                   
                    <Handle
                        type="source"
                        **position="right"**
                        style={{ borderColor: "red, backgroundColor: "#FFFFFF", display: "flex", alignItems: "center" }}
                    >
                        <div style={{ color: "red", fontSize: 6, fontWeight: "bold" }}>+</div>
                    </Handle>

<img width="641" alt="Screenshot 2021-09-01 at 2 24 39 PM" src="https://user-images.githubusercontent.com/44742741/131643155-9aad49f8-2e26-415f-84f2-b106f02f4ed9.png">

**Comment by PhilGarb** [comment]
There is a Position enum you have to import and use it like so: `position={Position.Right}`

**Comment by Shafahummer** [comment]
> There is a Position enum you have to import and use it like so: `position={Position.Right}`

Thank you
