### ISSUE TITLE
How To remove Edge (only edge)

### ISSUE THREAD

**Issue by jorgefo** [wbkd/react-flow#1485]
HI 

How to remove one edge from the elements, I try with example https://reactflow.dev/examples/edge-with-button but is not remove the element and the code is empty about this, only show javascript alert no remove the edge.

I try with removeElements but is not working for removing edge, only remove nodes.
And i try with updateEdge like that:

updateEdge(edge,{}, elements);
and 
updateEdge(edge,null, elements);

but still not working

**Comment by moklick** [comment]
Hey,

there is not universal answer for this. It depends on your state management/ elements management. `removeElements` and `updateEdge` are just helper functions that you can use. You put in some parameters like elements or a certain edge and you receive an updated set of elements back. When you use these functions you need to pass the updated elements back to the React Flow component.

Check these examples:

https://reactflow.dev/examples/update-node/
https://reactflow.dev/examples/save-and-restore/

**Comment by moklick** [comment]
In the examples we add functions to the data option of nodes/edges. We only do this for simplifying the examples. I would recommend to use a state lib like Zustand or use React context.

**Comment by AndreyPatseiko** [comment]
My solution.
1) OnConnect function add `data: {setEges}`
```
const onConnect = useCallback(
    (params) =>
      setEdges((eds) =>
        addEdge(
          {
            ...params,
            type: 'edgewithbutton',
            markerEnd: { type: MarkerType.ArrowClosed },
            style: { strokeWidth: 2 },
            data: { setEdges },   <---------
          },
          eds,
        ),
      ),
    [setEdges],
  );
```
2) in edgeWithbutton component, read this props and use it.
```
export const EdgeWithButton = ({  ...,  markerEnd,  data,}) => {
  ...
   const onEdgeButtonClick = (evt, id) => {
    evt.stopPropagation();
    data?.setEdges((edges) => edges.filter((ed) => ed.id !== id));
  };

  return (
    <>
       ...    
      <foreignObject >
        <RemoveIcon onClick={(event) => onEdgeButtonClick(event, id)} />
      </foreignObject>
    </>
  );
};
```

**Comment by AdnanSalah84** [comment]
@AndreyPatseiko 

Awesome.

I wonder how to pass setNodes to a custom node?

**Comment by prepwork** [comment]
@AndreyPatseiko, there is no need to pass `setEdges()` function with `data` since it is already present in ReactFlow instance, which can be obtained with `useReactFlow()`:


```JSX
const reactFlow = useReactFlow()

const onClick = useCallback(
  (evt, id) => {
    evt.stopPropagation()
    reactFlow.setEdges((edges) => edges.filter((edge) => edge.id !== id))
  },
  [reactFlow]
)
```

**Comment by wanglihuaya** [comment]
> ```js
> reactFlow.setEdges((edges) => edges.filter((edge) => edge.id !== id))
> ```

Thank you. You're right.
