### ISSUE TITLE
How do I implement drawing on the react-flow canvas?

### ISSUE THREAD

**Issue by ramseskamanda** [wbkd/react-flow#1493]
### Discussed in https://github.com/wbkd/react-flow/discussions/1492

<div type='discussions-op-text'>

<sup>Originally posted by **ramseskamanda** September  2, 2021</sup>
Hi everyone!

I'm building a collaborative tool using this package, and I'm trying to add drawing functionality to the canvas. Would anyone be able to set me on the right path? I've already built all the drawing logic on a separate canvas that would be positioned on top/as a child of ReactFlow (similar to how the Background component is implemented), however, allowing both drawing events and panning events at the same time is proving to be more difficult than I anticipated. Would anyone know how to implement something like that?

If anyone needs an example of what I'm trying to implement, it would be like Figma, where one can draw anywhere on an infinite canvas and interact with the canvas at the same time through panning.

Thank you in advance for your help!</div>

**Comment by moklick** [comment]
The discussion section in the right place for this kind of question :)
