### ISSUE TITLE
Change priority on stack order

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1494]
Guys, how can I put the node below the edge on stack order?
![image](https://user-images.githubusercontent.com/36650520/131911804-45a1bb19-3f50-471a-83ee-f87335ffe706.png)
I want to create a custom node thats always below the edges on stack order (I need to see the edge above this node)

**Comment by moklick** [comment]
You can adjust the z-index

```css 
.react-flow__edges {
  z-index: 4;
}
```
