### ISSUE TITLE
onElementClick Can't get  All data from element

### ISSUE THREAD

**Issue by Azim-Ahmed** [wbkd/react-flow#1502]
I want this json 

`{
    "type": "smoothstep",
    "style": {
      "stroke": "black",
      "strokeWidth": "1.5"
    },
    "selectable": true,
    "source": "node_process_G2N_akq",
    "sourceHandle": "a",
    "target": "node_process_RtZXRz9",
    "targetHandle": null,
    "id": "node_process_G2N_akq>node_process_RtZXRz9",
    "labelBgBorderRadius": 4,
    "arrowHeadType": "arrow",
    "label": "Add Your Text",
    "labelBgStyle": {
      "fill": "white",
      "stroke": "black"
    },
    "data": {
      "line": true,
      "node": false,
      "source": "node_process_G2N_akq",
      "target": "node_process_RtZXRz9"
    }
  }`

But , When I use onElementClick function , 

I got only this data: 

`data:
line: true
node: false
source: "node_process_G2N_akq"
target: "node_process_RtZXRz9"
[[Prototype]]: Object
id: "node_process_G2N_akq>node_process_RtZXRz9"
source: "node_process_G2N_akq"
sourceHandle: "a"
target: "node_process_RtZXRz9"
type: "smoothstep"
`

How Can I get all data , when I click an element.

**My main purpose is to update edge text .**

**Comment by datoslabs** [comment]
While react-flow keeps an internal "rendering" state, we should treat it as a controlled react component, and therefore we should retrieve and maintain the data from the elements array/state controlled in our HOC.  Since your main purpose is to update the edge text, I would suggest looking up the most up-to-date edge json from the elements array (via Edge `id`) and update the elements state.

**Comment by moklick** [comment]
As @datoslabs pointed out you need to update the elements state that you pass to the ReactFlow component. When you want to update it in a custom edge for example you would need to pass down a function (or get it from a context/state) that alters the state. Maybe this example helps https://reactflow.dev/examples/update-node/
