### ISSUE TITLE
Custom node types don't hot-reload

### ISSUE THREAD

**Issue by lostfictions** [wbkd/react-flow#1505]
I've noticed that while I'm designing my custom node types, they don't seem to hot-reload like the rest of my React components, and in fact require a full page reload to come into effect. At a glance, this seems to be the culprit:

https://github.com/wbkd/react-flow/blob/b3f102ce1bf850c756106587b7f07ea1fcb1ef2b/src/container/ReactFlow/index.tsx#L215-L216

I was able to resolve this by passing in the undocumented prop `nodeTypesId` to `<ReactFlow />`, defined as a constant at the module level (not the component level) like this:

```tsx
const nodeTypesId =
  process.env.NODE_ENV === "development"
    ? Math.random().toString()
    : "literally whatever string literal you want";
```

This feels like a bit of a kludge. If the only reason for the memoization is to wrap custom types, maybe it should be the user's responsibility to wrap them before passing them into the component? It would be slightly less ergonomic, but also less surprising. Either way, I think it would be great if this quirk was documented.

**Comment by moklick** [comment]
This is a good point, thanks. I will document the `nodeTypesId` and `edgeTypesId` attributes (and maybe we can change this in the next major release).

**Comment by moklick** [comment]
since v10 we are no longer memoizing custom nodes. This shouldn't be an issue anymore. Please re-open if the issue still persists.
