### ISSUE TITLE
pass children to Handle component cause the Handle not being abled to drag

### ISSUE THREAD

**Issue by fengChongxiu** [wbkd/react-flow#1507]
### my code

```javascript
<Handle
      type="source"
      position={Position.Right}
      id={id}
    >
    <IconPlus style={{ opacity: disabled ? 0.2 : 1, zIndex: -1 }} />
</Handle>
```

when i add a source or target class to its children, it works ok

```javascript
<Handle
      type="source"
      position={Position.Right}
      id={id}
    >
    <IconPlus class="source" style={{ opacity: disabled ? 0.2 : 1, zIndex: -1 }} />
</Handle>
```
after digging into the source code, i found this 
![image](https://user-images.githubusercontent.com/17736007/132682556-c8be9ed3-c29d-4764-a37a-731e5c5914d0.png)
i am not sure if this is a feature or bug, i think most users may expect the children can respond to users' drag action

**Comment by nikhil2kumar** [comment]
+1

**Comment by fengChongxiu** [comment]
@datoslabs pointer-events indeed works, but i also need to add some listener to handle's children

**Comment by supercmmetry** [comment]
I want to include hover behavior in the children. But doing so requires me to set `pointer-events: auto`. Is there any fix for this?

**Comment by datoslabs** [comment]
Would adding the hover event behavior to the handle achieve the same as hover event behavior over handle's children?

**Comment by cliffordfajardo** [comment]
@fengChongxiu - were you able to resolve the issue?
Could you share a small codesandbox.io example so other's can take a look as well? 
- https://codesandbox.io/s/react-ts?file=/src/App.tsx

**Comment by fengChongxiu** [comment]
> were you able to resolve the issue

just by setting pointer-event to none to handle's children
