### ISSUE TITLE
Vue js port of react-flow?

### ISSUE THREAD

**Issue by StashOfCode** [wbkd/react-flow#1515]
Is there a vue js port of react-flow? If not, which libarry would your recommend? I found X6 and butterfly, but they are mostly in Chinese and look a lot more bulky and convoluted than react-flow

**Comment by leejustin** [comment]
No there isn't AFAIK. You could try using something that is framework-agnostic. I've heard about Rete.js before though I haven't used it myself: https://rete.js.org/ You could take a look and see if it satisfies your use case. It's definitely not as well put together or polished as React Flow.

**Comment by StashOfCode** [comment]
@leejustin, that's true - this one looks really polished and lightweight. Anyways, I ended up using G6 https://g6.antv.vision/en/examples/gallery. It turned out to be quite good and google translate came to the rescue when there were no English docs ;)

**Comment by moklick** [comment]
g6 is great :) Maybe this is also interesting for you https://github.com/akashgoswami/vue-reactflow

**Comment by StashOfCode** [comment]
@moklick, nah, looks abandoned :)

**Comment by moklick** [comment]
yeah.. I think it's more of a demo.

**Comment by Lehoczky** [comment]
vue-flow is actively maintained and works great:)

https://github.com/bcakmakoglu/vue-flow
