### ISSUE TITLE
Support to get the edgeId on the handle prop

### ISSUE THREAD

**Issue by nikhil2kumar** [wbkd/react-flow#1517]
We have a requirement to style handle differently if there's no edge linked to a handle. For now, I'm scanning through all the edges and checking if the handle id is present in any one of them. This works for now but as the chart becomes large then this might impact the performance.

Is there a way to use it on the handle directly instead of this workaround?

**Comment by datoslabs** [comment]
Have you tried keeping track of edges connected to/from the node as part of the node's `data` payload?  For example:

```
const initialElements = [
  { id: '1', data: { label: 'Node 1', sourceHandles:{'a':'e1-2','b':null} }, position: { x: 100, y: 100 } },
  { id: '2', data: { label: 'Node 2', targetHandles:{'a':'e1-2','b':null} }, position: { x: 100, y: 200 } },
  { id: 'e1-2', source: '1',sourceHandle:'a', target: '2', targetHandle:'a' },
];
```

**Comment by nikhil2kumar** [comment]
We actually thought of this but the problem with this approach is that if we add a new edge then we'll have to scan through the nodes and update the source and target nodes. For now, I'm doing the same but it would be helpful if the handle prop has inherent support for edge id
