### ISSUE TITLE
Graph changing zoom when drag it

### ISSUE THREAD

**Issue by Umenokin** [wbkd/react-flow#1518]
We have an application that has some configurations which can be visualized as a graph. Once we load the application we would show a graph immediately and it would work like a charm. Then we can open configuration in the same container while unmounting the graph. If I go back to the graph everything works fine but if I try to drag nodes would jump to the top right corner. 

To summarize
1. It does not happen on the first mount
2. It is "on drag" issue because it would not jump "on click".
3. It does not happen on the first mount but would happen on all following mounts
4. We use fitView on every mount. It would center nodes but the graph would still jump on drag
5. Passing different keys to react-flow on every mount would not help

Is there a way to completely reset internal react-flow states as a quick fix?

**Comment by Umenokin** [comment]
It seems the issue is not "on drug" but because when we mount the graph, we are using fitView, but when you drug, it changes to zoom to a different value. Is it a bug or a feature?

**Comment by CKanishka** [comment]
Hey @Umenokin, I am facing a similar issue. Were you able to fix it? Any help will be highly appreciated.

**Comment by moklick** [comment]
Hey @CKanishka could you create a codesandbox to show the bug? Did you try to wrap your flows with a [React Flow Provider](https://reactflow.dev/docs/api/components/provider/)?

**Comment by CKanishka** [comment]
> Hey @CKanishka could you create a codesandbox to show the bug? Did you try to wrap your flows with a [React Flow Provider](https://reactflow.dev/docs/api/components/provider/)?

Hey @moklick thanks a lot for the prompt response, it is working as expected after wrapping it with **ReactFlowProvider**
