### ISSUE TITLE
Support Creating Edges on Touch

### ISSUE THREAD

**Issue by aunyks** [wbkd/react-flow#1522]
Hi! This project is amazing. I noticed that we can move nodes around and interact with their content on touch devices, but it doesn't seem that we can drag from a source handle to a target handle to create a new edge.  

What changes need to be made to support creating edges on touch devices?

I've tried changing `MouseEvent`s to `PointerEvent`s, but I kept getting TypeScript errors. Any help would be awesome!

**Comment by Azim-Ahmed** [comment]
Thanks for arising this issue , I have been stucked by this feature. @moklick

**Comment by leejustin** [comment]
Mobile support is planned for v10. See here: https://github.com/wbkd/react-flow/projects/1#card-65341240

**Comment by aunyks** [comment]
Thanks @leejustin!
