### ISSUE TITLE
Edges not visible

### ISSUE THREAD

**Issue by 1moere1** [wbkd/react-flow#1526]
I took the example from https://reactflow.dev/examples/ to try out react-flow and could not make the edges visible. The state does correctly hold the edges in it though.
![image](https://user-images.githubusercontent.com/9694983/134488137-af08a7ae-d8c7-4bea-b2ee-9edcb6b77efb.png)

**Comment by 1moere1** [comment]
solved. the issue was based on the usage of tailwindcss

**Comment by thbor** [comment]
> solved. the issue was based on the usage of tailwindcss

how to solve?
