### ISSUE TITLE
Collapse a group of nodes? 

### ISSUE THREAD

**Issue by Ertuyo** [wbkd/react-flow#1527]
The issue with having many nodes is that it becomes unclear very quickly. 
Collapsing a group of nodes while still showing the incoming and outcoming connections would be a nice feature. 
Is this already a feature? Or is there something similar?

**Comment by leejustin** [comment]
No such feature exists out of the box. You could create your own logic that uses custom Node types that have some kind of "collapsed" look. Then swap out those nodes with regular ones based on some user action.

**Comment by moklick** [comment]
Thanks @leejustin!

@Ertuyo you can get the outgoing nodes with the [`getOutgoers` helper function](https://reactflow.dev/docs/api/helper-functions/) and set the `hidden` attribute to `true` or a custom data attribute that collapses your custom node content.
