### ISSUE TITLE
when I change tab, the Nodes / Edges disappeared

### ISSUE THREAD

**Issue by aaronxdd** [wbkd/react-flow#1528]
when I first render the page, the flow is OK, can see the below pic
![微信图片_20210924153509](https://user-images.githubusercontent.com/16145101/134647095-7fa6c88d-7dcb-4693-8312-7182b7794ca2.png)

when I change tab, the  Nodes / Edges disappeared, you can see the node and edge container dont have nodes and edge
![微信图片_20210924153501](https://user-images.githubusercontent.com/16145101/134647531-f213c67c-a5ad-43d3-ba93-f71d9f83c496.png)
s,

**Comment by SRottgardt** [comment]
Hi,

i have the same problems i use the tabs from https://mui.com/components/tabs/

the first time the page is loaded, the react flow chart is empty, I switch the tabs back and forth, it is loaded correctly.

**Comment by aaronxdd** [comment]
> Hi,
> 
> i have the same problems i use the tabs from https://mui.com/components/tabs/
> 
> the first time the page is loaded, the react flow chart is empty, I switch the tabs back and forth, it is loaded correctly.

I have solve it

**Comment by aaronxdd** [comment]
add onlyRenderVisibleNodes={false} to your component
![微信图片_20210930113551](https://user-images.githubusercontent.com/16145101/135382989-28e79081-d7b1-4114-a095-c39879495c80.png)
