### ISSUE TITLE
Will it be a good option to add a magnifier to display the content of a node?

### ISSUE THREAD

**Issue by arfath77** [wbkd/react-flow#1529]
When we have a large flow it becomes difficult to review the flow, would it be a nice feature to have a magnifier to view the node content. Maybe using some key to activate it and when we hover on a node it will magnify it.

Can you please share your thoughts?

**Comment by moklick** [comment]
Thanks for your input @leejustin. That's a good point! With a custom node your feature wish should be implementable. We have a [contextual zoom](https://reactflow.dev/examples/contextual-zoom-features  ) example. Maybe this could also help you.
