### ISSUE TITLE
Is there a way to check/validate that every nodes have a edge connected?

### ISSUE THREAD

**Issue by MrRainesE** [wbkd/react-flow#1532]
i am using the save and restore example and i want to validate/check ik every node have e connected edge before saving the object.

**Comment by datoslabs** [comment]
You should be able to count edges (to and from) for each node with a simple reduce function like the following :

```
import {isEdge} from "react-flow-renderer";
...
let nodeEdgeCount = {};
reactFlowInstance.getElements().reduce((map, x)=>{
	if (isEdge(x)) {
		map[x.source] = map[x.source] ? map[x.source] + 1 : 1;
		map[x.target] = map[x.target] ? map[x.target] + 1 : 1;
	} else {
		!map[x.id] && (map[x.id] = 0);
	}
	return map;
}, nodeEdgeCount);
```
`reactFlowInstance` is obtained from `onLoad` callback.

**Comment by moklick** [comment]
Thanks @datoslabs
