### ISSUE TITLE
Request for support to export the snapshot of the flow.

### ISSUE THREAD

**Issue by nikhil2kumar** [wbkd/react-flow#1534]
Right now to export the flow as a .png or .pdf the user has to zoom out and manually take a screenshot of the flow chart. 

Is there a way to screenshot it without having to zoom out?

**Comment by datoslabs** [comment]
You can try calling the `reactFlowInstance.fitView()` (`reactFlowInstance` from `onLoad`) and use `html2canvas` to save a screenshot.

**Comment by moklick** [comment]
Thanks @datoslabs

**Comment by moklick** [comment]
I've created an ["Download Image" example](https://reactflow.dev/docs/examples/misc/download-image/) that uses [html-to-image](https://github.com/bubkoo/html-to-image).

**Comment by ghost** [comment]
When the number of nodes and edges is large, errors are occurring — is there a better approach to handle this? Please point it out for me. @moklick @datoslabs
