### ISSUE TITLE
Set default edge type and style for drag-and-drop custom nodes

### ISSUE THREAD

**Issue by abhitirkey** [wbkd/react-flow#1538]
I'm unable to set a custom edge type with a pre-defined style for new nodes that are dragged onto the canvas (. For such nodes, it's assuming the default edge type (bezier I think). It seems to me that the type and styles of are set programmatically for pre-existing nodes only.

Any tips/suggestions?

**Comment by nectum** [comment]
I just sat with the same thing. I modified the onConnect and when doing addEdge you can spread the params and modify like this;

`const onConnect = (params: Connection | Edge) =>
    setElements((els) =>
      addEdge(
        { ...params, arrowHeadType: ArrowHeadType.Arrow, type: "smoothstep" },
        els
      )
    );`

Maybe not the answer you need but may help you a bit on the road :)

**Comment by moklick** [comment]
As @nectum pointed out you need to pass the `type` attribute to the `addEdge` function.
