### ISSUE TITLE
useStoreState Performance with transform

### ISSUE THREAD

**Issue by dominikspiertz** [wbkd/react-flow#1561]
Hello dear react flow team,
we recently had a hard time to overcome some performance issues while using `useStoreState` to get the `transform` value. Since we have a lot of sub-components which rely on our custom hooks that sometimes need to use the `transform` from react-flow to achieve our goals, we needed to split our hooks in terms of whether they used the store state to get the `transform` property. One of our problems was, that if a component needs data about the `zoom` level (`transform[2]`) we still got re-renderings since if `transform` changes, it also changes if we only need to use the `zoom`. So we created a custom hook that subscribes to `transform` with `useStoreState` and memoized the single values of transform(`transform[0]`, `transform[1]`, `transform[2]`), that helped a lot. 

The second case which is still untackled and could be optimised would be the `selector` for `transform`. Of course `useStoreState` returns a new value whenever the tree is zoomed or moved. Since we need that for calculations when the user moves the tree around that is fine. But yet a delay of receiving the data would be great to improve performance a lot. Even if it is 0.1 seconds. 

The two ideas to create a better performance in my opinion with react flow would be the following:
- Create a hook or a selector that only exports one memoized instance of `transform`
- Have the ability to receive the `transform` value after a defined timeout of seconds when the values has not been changed anymore (delayed callback)

**Comment by moklick** [comment]
could you call a function after moving stops and use the `useStore` / `store.getState()` then to get the current transform? https://react-redux.js.org/api/hooks#usestore

**Comment by dominikspiertz** [comment]
I need the values doing the diagram move, since the transform is needed to calculate the translateExtent. Since I have no other way defining it, but by using those coordinates, I need them when the user moves the diagram. Just a small delay might be possible if the diagram is rapidly moved to improve the performance. If I would only get it after the user stops for some time, he would be able to drag the diagram across the translateExtent boundaries, causing the diagram to jump into the boundaries, after I calculate the values.

**Comment by moklick** [comment]
Could you provide a simple example via a codesandbox? I am not sure if I really get the issue here.

**Comment by dominikspiertz** [comment]
Hello @moklick, no problem. I will create one tomorrow and send it here so you can see it

**Comment by dominikspiertz** [comment]
Hey @moklick I created a sandbox demo for you. First of all,  I was wrong about my assumption that we use the transform state for the calculation of translateExtent. We have another function, that consumes x,y and zoom from the store state and is used along in each node (isElementOutsideViewport in the sandbox). By throwing around the tree you will notice fps drops from 60 to about 30. This is by design not a problem of react flow but we struggle how to optimize the performance when asking for all the values from react flow. Keep in mind that our real world application uses way more components, complexity and places where data is re-used. I say that because, the example from codesandbox still runs well in the browser. We also have optimized our ui to run on mobile which acts way worse, with all the store updates received.

Here is the demo:
https://codesandbox.io/s/react-flow-usetransform-performance-tv4fm

Thanks in advance for every feedback regarding the performance.

**Comment by moklick** [comment]
Hey @dominikspiertz 

we just released v10, that doesn't use Redux anymore but Zustand. With Zustand it's possible to do [transient updates](https://github.com/pmndrs/zustand#transient-updates-for-often-occuring-state-changes). Maybe it helps here:

```js 
import { useStoreApi } from 'react-flow-renderer';

function Component() { 
  const store = useStoreApi(); 
  const tranform = useRef(store.getState().tranform)
 
 useEffect(() => store.subscribe(
    state => (tranform.current = state.tranform)
  ), [])

 // ... do something with transform.current
```
