### ISSUE TITLE
TypeError: Cannot assign to read only property 'position' of object '#<Object>'

### ISSUE THREAD

**Issue by nikhil2kumar** [wbkd/react-flow#1562]
I'm trying auto layout following the example published in the docs(using dagre). 

So, basically when I use multi-select with shift+mouse drag and paste the nodes and edges again after changing the ids and then trigger the layout it crashes with error `TypeError: Cannot assign to read only property 'position' of object '#<Object>'`. But if I repeat the same process by selecting the node using cmd+click then it works just fine. 

I'm using the useStoreState to get the selectedElements and using them to create duplicates and paste it again.

I tried deep cloning the elements at every stage but that didn't work too.

**Comment by CamboimGabriel** [comment]
Same problem here

**Comment by CamboimGabriel** [comment]
how did u solved?

**Comment by nraskoti92** [comment]
for me, removing `__ref` from the node object solved this issue.
