### ISSUE TITLE
EdgePath casts black triangle shadows

### ISSUE THREAD

**Issue by AnnaxGrace** [wbkd/react-flow#1564]
<img width="404" alt="Screen Shot 2021-10-08 at 10 22 37 AM" src="https://user-images.githubusercontent.com/61895571/136585517-2cd73f4a-b293-47de-b8d1-e889b21d281a.png">

It seems that the custom edgepath still has the straight path and it's casting shadows. I had the issue on another chart, but then it went away, without any changes from me. I have tried changing the .react-flow_edge{} css and  the styling in the custom edge. However, when I inspect it you cannot just click on the triangles since they are a part of the larger edgepath. Please advise!

**Comment by moklick** [comment]
That is part of the base css which should be loaded by default.
