### ISSUE TITLE
Feature Request: Add setCenter to OnLoadParams

### ISSUE THREAD

**Issue by InfamousStarFox** [wbkd/react-flow#1565]
`OnLoadParams` currently has `setTransform` to allow for zooming to a certain viewport. However, due to way transform handles scaling, the passed in scale distorts the `XYPosition`, requiring a bit of math to calculate the corrected coordinates to use in setTransform.

Adding `setCenter` to `OnLoadParams` will allow for zooming in on a node without the need for additional math.

**Comment by moklick** [comment]
will be available in v10.
