### ISSUE TITLE
MultiSelection-Drag breaks Snap-To-Grid 

### ISSUE THREAD

**Issue by panexe** [wbkd/react-flow#1579]
It seems like selecting multiple Nodes (with shift + click + drag) and then moving them across the pane breaks out of the grid thats set via snap-to-grid, especially when zoomed in.

I manually set the elements back on to the grid in the onSelectionDragStop function, which shows the missplacement the nodes would have normally. 
![snap_to_grid_error](https://user-images.githubusercontent.com/31887780/137093815-ba7ec7ac-f02e-474e-ad82-890117c14d24.png)

**Comment by moklick** [comment]
fix released in v10.3.0
