### ISSUE TITLE
Widen edges area for onElementClick handler without widening strokeWidth

### ISSUE THREAD

**Issue by agnevusheva** [wbkd/react-flow#1580]
Hi! 
I noticed that quite often it may be hard to click on the edge as it's thin. I know that I may make them wider with the strokeWidth prop in the style object, but I would not like them to be wider than 2.5.
So, is there a way to increase an area in which onElementClick handler would work without widening the visible part of the edge with the strokeWidth?
Thank you in advance.

**Comment by AlyonaGN** [comment]
Many thanks, worked for me!
