### ISSUE TITLE
Source Handle generated on custom node at with a style top: 50% not generating edge

### ISSUE THREAD

**Issue by ghost** [wbkd/react-flow#1585]
I'm currently generating a custom with programmatically generated handles. This issue is seen only for a source node being generated with a style {top : 50%}. 

Sharing a simplified version of my code:

```
const CustomNode =({data}) => {

const calcHandlePosition = (index) => {
    const dataLength = data.inputs.length;

    const isConnectable = true;
    if (dataLength === 1 && index === 0) {
      return "50%";
    } else if (dataLength === 2) {
      return `calc(30% * ${++index}`;
    }
  };

return(
<div>
 {data.inputs.map((ip, index) => {
        return (
          <React.Fragment key={`node_ip_${index}`}>
            <Handle
              type="target"
              id={`target_${ip.name}_${index}`}
              position="left"
              style={{
                borderColor: "white", 
                backgroundColor: `${ip.color}`,
                top: calcHandlePosition(index)
              }}
              isConnectable={isConnectable}
            />
            <span> {ip.label} </span>
          </React.Fragment>
        );
      })}
{data.outputs.map((op, index) => {
        return (
          <React.Fragment key={`node_op_${index}`}>
            <Handle
              type="source"
              id="bottomSource"
              position="right"
              style={{
                borderColor: "white",               
                backgroundColor: `${op.color}`,
              }}
              isConnectable={true}
              
            />

          </React.Fragment>
        );
      })}

</div>
)
}
```

The handles are working fine when there are multiple of them but for a single source handle at top: 50% the crosshair is coming slightly to the left and no edge can be generated for it neither can it be connected by any edge.
I also noticed that the source handles work only when top is equal to less than 35~36%.
I even tried not setting the top value, but the issue persists.
Can someone please help out? 
Thank you.

**Comment by datoslabs** [comment]
Do you have a working sandbox with this problem?  Handle at "top:50%" works in the [horizontal example](https://reactflow.dev/examples/horizontal/) so it may be due to other elements around the handle `div` that may conflict with it.
