### ISSUE TITLE
Disable edge creation and updating

### ISSUE THREAD

**Issue by MNewbigging** [wbkd/react-flow#1603]
Hi, I couldn't find an answer on the docs/examples so thought I'd ask here.

Can I disable the ability to draw new edges from source -> target node handles, as well as the ability to update them?

I'm aware I can just do nothing when the onEdgeUpdate comes in, but there is still the onHover and dragging behaviour leading up to the onEdgeUpdate which I'd rather not have.

I've seen that using the controls I can lock the graph, which prevents all edge manipulation - but it also prevents moving nodes around which I'd like to keep.

I'm trying to make a node graph that represents a data structure made outside the graph itself. As such, I don't want users to be able to create or change edges within the graph itself.

I suppose what I'm really looking for is a way of making handles non-interactive. Is there such a thing? If not, how might I go about doing this myself?

**Comment by chaos87** [comment]
How did you figure this out? 

I have found how to disallow creating new edges, but can't find how to prevent existing edges to be updated
