### ISSUE TITLE
Edges don't get rendered properly on first load

### ISSUE THREAD

**Issue by Stealthx9** [wbkd/react-flow#1615]
Hi, 
we are using react_flow to visualize an existing taskflow.

There is an issue for us where the edges don't fir at all on the first load of the component. (It is inside a Modal)
If the Modal gets opened the second time the edges all fit.

Do you have any clue why this is happening?

firstload
![image](https://user-images.githubusercontent.com/27856193/138833949-a358be96-7966-49ab-bb9f-f43c17beb1a1.png)

secondload
![image](https://user-images.githubusercontent.com/27856193/138833994-ec6432c2-fe21-46fb-aa75-d873892dcd78.png)

**Comment by moklick** [comment]
Please feel free to re-open if the issue still occurs.
