### ISSUE TITLE
graph gets re-rendered when nodeTypes/edgeTypes change

### ISSUE THREAD

**Issue by chrtze** [wbkd/react-flow#1620]
When the nodeTypes object is created inside the render function of a component without using `useMemo`, the graph gets re-rendered infinitely. Maybe we can check if the keys of the nodeTypes object change or show a warning when something like this happens.

```
const InfiniteRender = () => {
  const nodeTypes = {
    foo: Bar
  };

  const onNodesChange = () => {
    ...
  }


  return <ReactFlow onNodesChange={onNodesChange} nodeTypes={nodeTypes} />
}
```

**Comment by miclegoden** [comment]
When the library customize, 
"It looks like you have created a new nodeTypes or edgeTypes object. If this wasn't on purpose please define the nodeTypes/edgeTypes outside of the component or memoize them."
Actually, Components were connected.
How do we check this issue?
