### ISSUE TITLE
[Feature Requets] Add Edges with Midpoint Support

### ISSUE THREAD

**Issue by ottovw** [wbkd/react-flow#1623]
Graph editors like Omnigraffle or Visio allow to add "Mid Points" on an edge in order to enable more complex edge layouts.

Here's an Example:
![image](https://user-images.githubusercontent.com/1045946/139352591-ee2aa314-6f0f-48f2-b511-5a2559c5f8a9.png)

This could be a valuable addition to this great library.

**Comment by ottovw** [comment]
move this to the discussions: https://github.com/wbkd/react-flow/discussions/1029

**Comment by MaxKoldun** [comment]
@ottovw How to enable these mid points in the react flow ?
