### ISSUE TITLE
Using component for a label, having trouble restoring/passing in default elements

### ISSUE THREAD

**Issue by acomito** [wbkd/react-flow#1624]
I feel bad because I'm sure there is an issue already covering this, or it's in the docs, but I just couldn't seem to locate an answer.

I didn't 100% follow how the restore/save example from the docs could apply here-- maybe I'm missing something.

Anyway,

When I use a component for a node label, everything works fine. However, if I leave and come back to my flow editor, and pass in default elements, I get an error rendering ReactFlow. Just to be clear:

- Go to my ReactFlow editor page
- add some nodes/edges with react components for the data.label field
- everything works fine
- I'm saving my array of elements in state management (little-state-machine to be exact), so it's persisted
- I leave the "ReactFlow editor page" in my app, and then I go back to the "ReactFlow editor page" 
- Since I have a flow saved, I am then passing in the elements that are stored in little-state-machine
- I get an error related to the label being a react component (I think)

I think it's related to the lable, because when I do a basic String as a label, the above all works and I can restore/pass in defaults and everything renders. It's only when the label is a react component that ReactFlow seems angry.

For context, my elements come out of ReactFlow and are saved looking like this:

```
const elements = [
  {
    "id": "5dffb495452f8b0021610d82",
    "type": "default",
    "data": {
      "label": {
        "key": null,
        "ref": null,
        "props": {
          "children": [
            {
              "type": {
                "attrs": [],
                "componentStyle": {
                  "rules": [
                    "\n  margin: 0px;\n  bottom: 0;\n  font-weight: 400;\n  line-height: 145%;\n  font-family: ",
                    null,
                    ";\n  display: ",
                    null,
                    ";\n  color: ",
                    null,
                    ";\n  font-size: ",
                    null,
                    ";\n"
                  ],
                  "staticRulesId": "",
                  "isStatic": false,
                  "componentId": "sc-jrsJWt",
                  "baseHash": 1397025452
                },
                "foldedComponentIds": [],
                "styledComponentId": "sc-jrsJWt",
                "target": "span"
              },
              "key": null,
              "ref": null,
              "props": {
                "children": "RebootXFR"
              },
              "_owner": null,
              "_store": {}
            },
            {
              "type": {
                "attrs": [],
                "componentStyle": {
                  "rules": [
                    "\n  margin: 0px;\n  bottom: 0;\n  font-weight: 300;\n  line-height: 24px;\n  letter-spacing: 1px;\n  font-family: ",
                    null,
                    ";\n  display: ",
                    null,
                    ";\n  color: ",
                    null,
                    ";\n  font-size: ",
                    null,
                    ";\n"
                  ],
                  "staticRulesId": "",
                  "isStatic": false,
                  "componentId": "sc-kEqXSa",
                  "baseHash": 576982587
                },
                "foldedComponentIds": [],
                "styledComponentId": "sc-kEqXSa",
                "target": "span"
              },
              "key": null,
              "ref": null,
              "props": {
                "children": "RebootXFR"
              },
              "_owner": null,
              "_store": {}
            }
          ]
        },
        "_owner": null,
        "_store": {}
      }
    },
    "style": {
      "border": "1px solid #2a2b2e",
      "width": 250
    },
    "position": {
      "x": 40,
      "y": 230
    }
  }
]
```
 
and the error I'm getting

```
Error: Objects are not valid as a React child (found: object with keys {key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
```

<img width="1168" alt="Screen Shot 2021-10-29 at 12 57 54 PM" src="https://user-images.githubusercontent.com/12701635/139474084-c04b0e83-bfa1-42d7-b6b3-25b052e46ea8.png">

**Comment by ottovw** [comment]
Hey @acomito ,

you shouldn't put a component in the data attribute, because it can't get serialized properly & loaded again.

If you want a component for the label:
- pass the props like 'label' to data
-  create a custom node with that component: https://reactflow.dev/examples/custom-node/

Hope that helps

**Comment by moklick** [comment]
Thanks @ottovw . That's the correct way! Passing a component as a label can be used for testing things quickly. I would recommend to only use custom nodes in real world applications.

**Comment by acomito** [comment]
Thanks guys! 

Amazing package.

**Comment by jsh854** [comment]
hey guys , wanted to ask is there a way i can pass custom nodes inside a custom node?
i want a component as a wrapper that will hold the subflow components and they behave as such they are inside that component where in i can add proper styling as well as have those subflows pointing to any thing as such

**Comment by moklick** [comment]
@jsh854 you can use any node type (also your custom nodes) as a parent node, but you can't use other nodes inside a node. If you want to add a node to a parent node, you need to use the node option "parentNode" https://reactflow.dev/docs/api/nodes/node-options/#options

**Comment by moklick** [comment]
@jsh854 you can use any node type (also your custom nodes) as a parent node, but you can't use other nodes inside a node. If you want to add a node to a parent node, you need to use the node option "parentNode" https://reactflow.dev/docs/api/nodes/node-options/#options
