### ISSUE TITLE
Connecting Top to Top or Bottom to Bottom creates an unexpected path shape

### ISSUE THREAD

**Issue by Vazerthon** [wbkd/react-flow#1642]
Related to #1613

# Context

Setup uses:
 - a canvas with `connectionMode={ConnectionMode.Loose}`
 - custom nodes with Handles on each side, all set as `type="source"`
 - custom edges using a smooth step path
 - react-flow-renderer v9.6.10

# Observed behaviour

When connecting top -> top or bottom -> bottom, the drawn curve creates an S shape rather than the expected `n` or `u`.

![image](https://user-images.githubusercontent.com/8657986/140083282-9fc6fbd7-432e-45b4-a42e-f44f9a0f2f7e.png)
![Peek 2021-11-03 14-50](https://user-images.githubusercontent.com/8657986/140083665-77a05395-dd8a-4475-a186-48ec664d2ccd.gif)

# Expected behaviour

The path should not be covered by the nodes it connects to

# Minimal reproduction environment

(same environment as linked issue)
https://codesandbox.io/s/falling-frost-i767n

<details>
<summary>Minimal reproduction code in case Codesandbox is deleted</summary>

```
import * as React from "react";
import ReactFlow, {
  ReactFlowProvider,
  ConnectionMode,
  Background,
  addEdge,
  getMarkerEnd,
  ArrowHeadType,
  getSmoothStepPath,
  Position,
  Handle
} from "react-flow-renderer";

//-------------- custom edge --------------

export function CustomEdge({ id, ...props }) {
  const edgePath = getSmoothStepPath({ ...props });
  const markerEnd = getMarkerEnd(ArrowHeadType.ArrowClosed);

  return (
    <path
      id={id}
      d={edgePath}
      markerEnd={markerEnd}
      fill="none"
      stroke="black"
    />
  );
}

// -------------- / --------------

// -------------- custom node --------------

export function CustomNode({ ...props }) {
  return (
    <div
      {...props}
      style={{ width: "200px", height: "100px", border: "1px solid black" }}
    >
      <Handle id="1" type="source" position={Position.Left} />
      <Handle id="2" type="source" position={Position.Top} />
      <Handle id="3" type="source" position={Position.Right} />
      <Handle id="4" type="source" position={Position.Bottom} />
    </div>
  );
}

// -------------- / --------------

export default function App() {
  const edgeTypes = {
    editable: CustomEdge
  };

  const nodeTypes = {
    custom: CustomNode
  };

  const [elements, setElements] = React.useState([
    { id: "1", position: { x: 100, y: 200 }, data: {}, type: "custom" },
    { id: "2", position: { x: 400, y: 300 }, data: {}, type: "custom" },
    { id: "3", position: { x: 700, y: 400 }, data: {}, type: "custom" },
    { id: "4", position: { x: 1000, y: 500 }, data: {}, type: "custom" }
  ]);

  const onConnect = (edge) =>
    setElements((els) => addEdge({ ...edge, type: "editable" }, els));

  return (
    <div style={{ width: "100%", height: "100vh" }}>
      <ReactFlowProvider>
        <ReactFlow
          nodesConnectable
          edgeTypes={edgeTypes}
          nodeTypes={nodeTypes}
          connectionMode={ConnectionMode.Loose}
          elements={elements}
          onConnect={onConnect}
        >
          <Background />
        </ReactFlow>
      </ReactFlowProvider>
    </div>
  );
}

```
</details>

**Comment by Ipicky22** [comment]
Hi @Vazerthon !

I tried to solve your problem, and I found a little something. I think this is just a food for thought, but maybe it will help you.
I only modified your custom edge, and I created a function to try to calculate the centerY. I tried to do the same for the centreX, but I have the impression that it does not impact the position of the edge.

```Javascript
export function CustomEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  style = {},
  data,
  arrowHeadType,
  markerEndId
}) {
  const calculateCenterY = (sourceY, targetY) => {
    if (sourceY > targetY) {
      return sourceY + 20;
    }
    if (sourceY < targetY) {
      return sourceY + targetY - targetY / 1.5;
    }
  };

  const edgePath = getSmoothStepPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
    centerY: calculateCenterY(sourceY, targetY)
  });
  const markerEnd = getMarkerEnd(ArrowHeadType.ArrowClosed);

  return (
    <path
      id={id}
      d={edgePath}
      markerEnd={markerEnd}
      fill="none"
      stroke="black"
    />
  );
}
```

In the case of the bottom - bottom, this solves your problem but not in all cases. For Top-Top this does not solve anything, I think you have to pass the position in the calculation function, and if it is Top or Bot then calculate the centerY differently.

Hoping that helps you

**Comment by moklick** [comment]
Good point @Vazerthon . I guess the edge routing needs a bit of a rework ;) It can't be that we have a separate condition for all possibilities. Surely there is a generic way that works for all positions. Right now we have other tasks on our list but I will keep this open.,

**Comment by Vazerthon** [comment]
Thanks for the suggestion @Ipicky22 and sorry for taking so long to reply.
> But there you try to source-source, it is possible that this poses other problems later.

This is necessary for connecting anything to anything. It's OK according to the docs as long as the canvas is in `ConnectionMode.Loose`. 

> It can't be that we have a separate condition for all possibilities.

Absolutely, there must be an elegant way to handle it that isn't a huge ladder of nested `if` statements.
I'm spending quite a lot of time using and benefiting from react-flow at the moment so it's in my interest to fix this. I'll have a play around and see if I can raise a PR at some point. If I come up with any ideas I'll mention them here.

**Comment by moklick** [comment]
@Vazerthon that sounds awesome :)

**Comment by moklick** [comment]
This issue was fixed with v11 https://reactflow.dev/blog/react-flow-v11/#edge-routing-and-edge-selection
