### ISSUE TITLE
Problem with using ReactFlow in multiple components 

### ISSUE THREAD

**Issue by haochenuw** [wbkd/react-flow#1653]
**Problem**: When I define a <Foo> component and uses <ReactFlow> in it, and create two <Foo> instances in the main app, it has very strange behavior: sometimes the two nodes act as if they are one (if I drag one, the other moves as well). Sometimes it just doesn't render.

**Example**: 
https://codesandbox.io/s/focused-river-u1gnk?file=/src/App.js

**Comment by flexplatox** [comment]
To handle multiple Flows on a page, you need to wrap each one with a `ReactFlowProvider`.

See my forked Sandbox which fixes this issue: https://codesandbox.io/s/nifty-tdd-prl3j?file=/src/App.js

**Comment by haochenuw** [comment]
Thanks!! That solved it. Would it be possible to make this information more visible in the online doc?

**Comment by dropbeardan** [comment]
Thanks, this should be more highlighted somewhere in the docs
