### ISSUE TITLE
 Can't resolve 'react-flow-renderer' when trying to run examples

### ISSUE THREAD

**Issue by Yi-Jiahe** [wbkd/react-flow#1656]
According to the readme development, to run the examples you need to install the React Flow dependencies via `npm install` and the ones of the examples `cd example && npm install`, and run the example app via:

```sh
cd example && npm start 
```

However, the example app uses `"react-flow-renderer": "file:../"` and the module for the react-flow-renderer package is `  "module": "dist/ReactFlow.esm.js"` . The readme should have a step for building the react-flow-renderer package via `npm run build` in the root directory to run the examples I believe? 

When I run `npm run build` however, I get:

```sh
$ npm run build

> react-flow-renderer@9.6.11 build
> rollup -c --environment NODE_ENV:production && postcss src/*.css --dir dist


src/index.ts → dist/ReactFlow.js, dist/ReactFlow.esm.js...
Created bundle ReactFlow.js: 442.12 kB → 93.46 kB (gzip)
Created bundle ReactFlow.esm.js: 437.92 kB → 93.12 kB (gzip)
created dist/ReactFlow.js, dist/ReactFlow.esm.js in 32.4s

src/index.ts → dist/nocss/ReactFlow-nocss.js, dist/nocss/ReactFlow-nocss.esm.js...
Created bundle ReactFlow-nocss.js: 436.67 kB → 92.08 kB (gzip)
Created bundle ReactFlow-nocss.esm.js: 432.46 kB → 91.74 kB (gzip)
created dist/nocss/ReactFlow-nocss.js, dist/nocss/ReactFlow-nocss.esm.js in 21.3s
(node:15300) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:698:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**Comment by Ipicky22** [comment]
Hi ! 

I tried running the "examples" folder with an npm install, but during the npm run start it encountered a problem.
The logical procedure is as follows :

```Console
git clone https://github.com/wbkd/react-flow.git
cd react-flow
cd example
npm install
npm run start
```

But as I said it has a problem. To operate, the following operations must be carried out : 

```Console
git clone https://github.com/wbkd/react-flow.git
cd react-flow
cd example
```
Remove react, react-dom and react-flow-renderer lines of your package.json and save.
```Console
npm install react react-dom react-flow-renderer
npm install
npm run start
```

And your localhost should start with the whole example folder ;)
Hoping I could help

**Comment by Yi-Jiahe** [comment]
Yup I ended up removing the example folder from the react-flow directly and installing the react, react-dom and react-flow-renderer separately. 

Thanks for the detailed run down of how you addressed the issue.

**Comment by moklick** [comment]
Hey @Yi-Jiahe 

you need to do `npm start` in the examples folder (for the examples) and in the root folder (for building the library)
