### ISSUE TITLE
Save or Export to JSON 

### ISSUE THREAD

**Issue by radikaledward1** [wbkd/react-flow#1657]
It Is possible to save or export the diagram created to JSON format? to save it in a database column ...

**Comment by Ipicky22** [comment]
Hi @radikaledward1 !

I do not believe that we can have the graph directly in JSON format. 
However, it is not complicated to create some functions to restructure your graph in the form you want, and thus be able to put it in a database. 
Personally this is what I do for my application.

I hope I have been helpful.

**Comment by chrtze** [comment]
Hi @radikaledward1, you can also use the `toObject` method on the react-flow instance for that. https://reactflow.dev/docs/api/react-flow-instance/

**Comment by radikaledward1** [comment]
> Hi @radikaledward1 !
> 
> I do not believe that we can have the graph directly in JSON format. However, it is not complicated to create some functions to restructure your graph in the form you want, and thus be able to put it in a database. Personally this is what I do for my application.
> 
> I hope I have been helpful.

Hi, Thanks for response, Could you share how you use that functions to save the graph structure? just to have a reference.

**Comment by radikaledward1** [comment]
> Hi @radikaledward1, you can also use the `toObject` method on the react-flow instance for that. https://reactflow.dev/docs/api/react-flow-instance/

Thank you for the response, so, "ToObject" method returns a JSON structure for each element right? i mean, Should I to use that method for each element in the graph or this method returns the whole graph structure to JSON? Could you give me a hint?

**Comment by FeherMarcell** [comment]
@radikaledward1 Check the [example code](https://reactflow.dev/examples/interaction/save-and-restore) that saves and restores the chart to localStorage
