### ISSUE TITLE
Possibility to set custom node types dynamically from state 

### ISSUE THREAD

**Issue by mabezdek** [wbkd/react-flow#1660]
Hi,

I would like to ask for posssibility to set nodeTypes dynamically via useState update. We have configuration of node types in server JSON, application sends request for this JSON, parse him and creates dynamic node types. **Now we need to update node types in ReactFlow component**, otherwise we are getting the following error

`Node type "xx" not found. Using fallback type "default".`

Thank you

**Comment by moklick** [comment]
Hey! The nodeTypes get memoized. If you want to update them you need to pass `nodeTypesId` as a prop (that is different from the previous `nodeTypesId`) https://reactflow.dev/docs/api/component-props/

**Comment by mabezdek** [comment]
Hey @moklick you probably safed my life! It works! Thank you so much, this library is awesome!

**Comment by ElyesBenCheikh1** [comment]
hi 
I faced the same problem. I created a custom node but every time i call it  this message came at the console : Node type "xx" not found. Using fallback type "default".

**Comment by ElyesBenCheikh1** [comment]
hi,
i actually resolved the problem using your answer to the previous question.
Thank you, i really apreciate your work.

**Comment by vikrantaroraa** [comment]
@ElyesBenCheikh1 It would really help, if you could create a sandbox to demonstarte the problem and the solution as I am also trying to update the nodeTypes dynamically  by creating new types of nodes.

@moklick by any chance, do you have any codesandbox regarding this?

**Comment by havocthehobbit** [comment]
I think an example of source  would have been great since the link doesnt really work well anymore with new changes to documentation page 
but they search does help now and gives an example . 
https://reactflow.dev/learn/troubleshooting#it-looks-like-you-have-created-a-new-nodetypes-or-edgetypes-object-if-this

```
import { useMemo } from 'react';
import { ReactFlow } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
 
import MyCustomNode from './MyCustomNode';
 
function Flow(props) {
  const nodeTypes = useMemo(
    () => ({
      myCustomNode: MyCustomNode,
    }),
    [],
  );
 
  return <ReactFlow nodeTypes={nodeTypes} />;
}
 
export default Flow;
```
