### ISSUE TITLE
Edge label gets hidden

### ISSUE THREAD

**Issue by Ishtiaq-Ahmad** [wbkd/react-flow#1665]
When applying smart routing the edge labels get hidden. Please guide me in this regard.

**Comment by moklick** [comment]
Hey @Ishtiaq-Ahmad 

what do you mean with "applying smart routing"?

**Comment by Ishtiaq-Ahmad** [comment]
i have used path finding library, [https://github.com/wbkd/react-flow/pull/1628](url)
so whenever i change the type of edge to smart routing label gets hidden. and when i use others types of edge such as 
default, straight,  step, smoothstep, then edge label works normall

https://user-images.githubusercontent.com/67997286/142577166-8863d119-e893-4c8e-8421-3ebb4e2c01c7.mp4

**Comment by tisoap** [comment]
Hey @Ishtiaq-Ahmad , the `SmartEdge` is not a part of the official React Flow repo, it's a custom Edge [I've made myself](https://github.com/tisoap/react-flow-smart-edge). I've just recently released a version that supports labels.

**Comment by Ishtiaq-Ahmad** [comment]
ok thank you soo much.

**Comment by Ishtiaq-Ahmad** [comment]
Hello dear, i have installed the latest version. but i am still getting label problem. label gets hidden when i select smartEdge.

**Comment by moklick** [comment]
Please consider to open an issue in the related repository https://github.com/tisoap/react-flow-smart-edge
