### ISSUE TITLE
Drag and Drop imgs

### ISSUE THREAD

**Issue by medaminefh** [wbkd/react-flow#1667]
Hi, Is there any exemple of how to use drag and drop functionalities with imgs ?

**Comment by moklick** [comment]
Sorry, I don't get your question. Could you elaborate?

**Comment by medaminefh** [comment]
Hi @moklick, thanks for responding.
So what I want to do is This 


![ezgif com-gif-maker](https://user-images.githubusercontent.com/37845480/142181656-f6e54bbf-191f-4fef-a961-aa362c3fa9b7.gif)

Instead Of dropping an "Input", I want an Image or let's say a Component

**Comment by moklick** [comment]
Ah! That's possible. When you drop a node you could add node with an image (or better a custom node). Take this example https://reactflow.dev/examples/drag-and-drop/ and replace the `newNode` part with this:

```js 
const newNode: Node = {
  id: getId(),
  type,
  position,
  data: {
    label: <img className="nodrag" src="https://via.placeholder.com/150" />,
  },
};
```
