### ISSUE TITLE
Custom label for connections point

### ISSUE THREAD

**Issue by tranchem** [wbkd/react-flow#1674]
Hi there!

I'm trying to create custom connection points: "In, Right, Wrong" like this
![Screenshot 2021-11-16 100246](https://user-images.githubusercontent.com/43035967/141888247-1ce230ba-599a-4596-9f4b-a0e8a9a7e201.png)
How to set the label for point connection?
I have looked into the documentation and old issues but nothing answer.
Please help me!
Thank you so much!

**Comment by Ipicky22** [comment]
Hi @tranchem !

You can add elements in the Handle components, like this :

```Javascript
<Handle id="1" type="source" position={Position.Left}>
        <div style={{ marginLeft: 8 }}>Test</div>
</Handle>
´´´

With that I get the text "Test" next to my Handle, then you have to play with the divs and styles to get the result you want.

I hope I have been helpful !

**Comment by moklick** [comment]
Custom nodes are just divs. You can place the elements as seen in your screenshot with CSS. 
Take a look at this example https://reactflow.dev/examples/custom-node/ or this part of the docs to get a better understanding of custom node implementations https://reactflow.dev/docs/api/node-types/#custom-nodes

**Comment by tranchem** [comment]
Hi @Ipicky22 @moklick!
Thank you so much! 
I had done it.
Have a nice day!
