### ISSUE TITLE
Edge paths are not symmetrically aligned

### ISSUE THREAD

**Issue by ayassinov** [wbkd/react-flow#1675]
## Current 

The edge path between node 1 and 4 is not aligned with the edge path between the 3 and 4.
When there's a lot of nodes it makes the graph less readable.

![image](https://user-images.githubusercontent.com/183475/141963583-beae3964-7795-4e97-beb0-d8b1cbdee4c1.png)

## Expected 
![image](https://user-images.githubusercontent.com/183475/141964417-46acee1b-183e-4b37-8d02-186e85fb23cb.png)

## Codesandbox

https://codesandbox.io/s/condescending-wood-riv88?file=/src/App.js

**Comment by moklick** [comment]
Hey @ayassinov 

our current edge implementation works as expected. We don't pay attention to edges or nodes that are not connected. If you want this kind of edge in your application you need to implement a custom edge. You can find more information about custom edges in the [docs](https://reactflow.dev/docs/api/edge-types/#custom-edges) or in this [example](https://reactflow.dev/examples/edges/).  

Hope it helps :)

**Comment by vvroul** [comment]
Hello @moklick 

Do you have any idea/example on how we can implement that custom edge?

**Comment by moklick** [comment]
Hey @vvroul 

you would need to implement your own edge routing logic. This is a complex topic. There are libraries like [elkjs](https://github.com/vectordotdev/vector) that might help you to achieve this edge routing
.
