### ISSUE TITLE
[question] Source and target handle

### ISSUE THREAD

**Issue by yuniyakim** [wbkd/react-flow#1678]
Is it possible to create a custom node with a handle that is both source and target at the same time?

Creating two handles at the same position but with different types doesn't seem to work correctly.

**Comment by Ipicky22** [comment]
Hi @yuniyakim !

I do not believe this is possible.

However you can create a handle area, which hides a source handle and a target handle. I've seen a way out with this example before, but I'm not getting my hands on it again.

However, I redid the diagram to make it clearer.

![exemple](https://user-images.githubusercontent.com/37102040/142229338-58cf8855-62e7-4924-97d3-2be90c622a40.PNG)

The user drops the edge in the handle area, and he attaches himself to the right handle depending on whether the start of the edge is a source or a target.

I hope I have been helpful.

**Comment by yuniyakim** [comment]
> However you can create a handle area, which hides a source handle and a target handle. I've seen a way out with this example before, but I'm not getting my hands on it again.

@Ipicky22 hi!

Have you seen this example in the issues section?

**Comment by flexplatox** [comment]
If you're looking for the ability to use one handle to both create and accept new connections, you can use the `connectionMode` prop set to `loose`.

See https://reactflow.dev/docs/api/component-props/

**Comment by yuniyakim** [comment]
> If you're looking for the ability to use one handle to both create and accept new connections, you can use the `connectionMode` prop set to `loose`.
> 
> See https://reactflow.dev/docs/api/component-props/

This is exactly what I was looking for. Thank you!
