### ISSUE TITLE
Propose to make node data NOT optional

### ISSUE THREAD

**Issue by mattmazzola** [wbkd/react-flow#1679]
The current data type for Node is

![image](https://user-images.githubusercontent.com/2856501/142265517-16741556-b401-49fc-8382-6f29276c03b7.png)

This means even when you assign `T` such as `Node<ElementData>` and know in your program all Nodes would have `T`.
it will still show the data as possibly being undefined.

![image](https://user-images.githubusercontent.com/2856501/142265829-91c5417e-4f0e-4f75-b7f6-afcb001490e7.png)

Because T defaults to `any` which could be undefined.

Changing `data?: T` to `data: T` would still allow setting `data: undefined` on new element objects if needed.

Side note, I think the default renderer for nodes actually requires the data to be `{ label: 'string }` so setting undefined on Nodes might crash application which means this is another reason it should not be typed as optional since it's actually required.

**Comment by flexplatox** [comment]
Could this have unintended side-effects for projects expecting a potentially `undefined` value? Why not create your own node `interface` with these requirements? Sure, some internal ReactFlow functions like `isNode` and `isEdge` may be expecting the internal `Node` type, but these can easily be ignored if you can guarantee that your own interface will be used.

I may be forgetting an important factor with this. If so, please correct me.

**Comment by mattmazzola** [comment]
> Could this have unintended side-effects for projects expecting a potentially undefined value?

I do not think so.  I think it only has side effect for TypeScript projects during type checking / compilation.  At runtime an object without a property is treated the same as if the property had been set to undefined.

```
let x = {}
x.data
// undefined
```
```
let x = { data: undefined }
x.data
// undefined
```

However, it is different for types. Because it is `data?: any` (Using any since it is most permissible case and T defaults to any)

You are not required to add the data property 
```
const node: Node = {
  id: uuid.v4(),
  position: { x: 0, y: 0 },
}
```

However, if it is changed to `data: any`
```
const node: Node = {
  id: uuid.v4(),
  position: { x: 0, y: 0 },
  data: undefined,
}
```

> Why not create your own node interface with these requirements?

I think this is an acceptable approach, but since it a standard problem that almost everyone will have (As I said above you like have to define data anyways) I think the library should absorb this complexity or make the problem obsolete.

**Comment by mattmazzola** [comment]
Should also call out if this change was made, I think it would technically would be a breaking change.

Any consumer who was using the `Node` or `Edge` from the library and not explicitly specifying the `data` property would get an error.  Even though data is likely required for any usefulness of this library to render content in the node, I think there could be a case where nodes instance was created without data and then data was set later.

This would break
```
const node: Node = {
  id: uuid.v4(),
  position: { x: 0, y: 0 },
}

...

node.data = {
  label: "My New Node"
}
```

Would need to defer instance creation until all data was available, such as:
```
const node: Node = {
  id: uuid.v4(),
  position: { x: 0, y: 0 },
  data = {
   label: "My New Node"
  }
}
```

**Comment by flexplatox** [comment]
> I think it only has side effect for TypeScript projects during type checking / compilation.

This is what I mean, yeah. TypeScript will only complain during type checking and compilation. Runtime, of course, will have no difference.

> I think this is an acceptable approach, but since it a standard problem that almost everyone will have (As I said above you like have to define data anyways) I think the library should absorb this complexity or make the problem obsolete.

Okay, this is a fair point. I wonder, what if the maintainers created a new `StrictNode` type or something with this behavior, keeping the current type. This would both prevent breaking changes during type checking/compilation and offer the behavior you're requesting.

Of course, this likely wouldn't be a straightforward implementation. Depending on how often the `Node` type is used, they may have to extract a new type, `BaseNode`, for the purpose of explanation, to which the value could be `Node | StrictNode`.

---

For others unaware of the context:

We're generally getting TS errors when creating a custom Node type in TS. For example, adding a few properties to the object. Using internal ReactFlow methods, they expect the exported `Node` type which has proven to be difficult to properly extend (in particular, if the types of some values need to be modified (**for the purpose of explanation**, if we need the `id` to be `number`)).

---

I'm not entirely aware of the internal usage of the `Node` type within ReactFlow, but it may be more tedious than we're assuming here. As always, this will be up to the maintainers to decide.

For now, the best approach is probably to create a custom `Node` type for your project and use `// @ts-ignore` for any TS errors ReactFlow throws.

**Comment by moklick** [comment]
Thanks for your input @mattmazzola . You have a good point here and the timing is good ;) We are refactoring the types for v10 and I will put this on the list.

**Comment by tisoap** [comment]
@moklick On a project I faced an issue where nodes needed to have a certain data shape, but even if the external interface to my component consuming React Flow did make it required, I still had to do type casting since `<ReactFlow>` callbacks assume `data` is optional, even if I'm enforcing it to not be from the outside

**Comment by HammadAli01** [comment]
can i assign additional key and values to a new node 
what i am trying to do is assign an object all attributes and values to the new node made so that i can use predefined node attributes as well as objects

**Comment by Sec-ant** [comment]
+1 for this implementation. And by the way, will `data` in `Edge` become required too in v10? If not, is there any simple way to do the typing thing where we usually use generics like `useReactFlow<CustomNodeData,CustomEdgeData>()` while prevent ts from complaining `data` in `Edge<CustomEdgeData>` can be `undefined`?

**Comment by loichuder** [comment]
Hello :wave: 

As far as I can see, `data` is now mandatory in nodes but is still optional in edges ?

https://github.com/wbkd/react-flow/blob/afa38727fad2400e817a3dcc6c575cb83cbf2bd2/packages/core/src/types/edges.ts

**Comment by bigmistqke** [comment]
Bump. Any updates on this? Would like to require data-prop in edge too.
