### ISSUE TITLE
Handle with source and target

### ISSUE THREAD

**Issue by RaFaTEOLI** [wbkd/react-flow#1680]
Is it possible to have a handle with a source and target property at the same time?

I've tried many ways of my own but I didn't succeed to make it work, I would like a node with a handle that would accept connections but would also connect.

Somehow a property that would be source and target as well.

**Comment by flexplatox** [comment]
If I'm understanding your inquiry properly, you can use the `connectionMode` prop set to `loose`:

> `connectionMode`: default: `strict`. Possible values are `strict` (only source to target connections are possible) or `loose` (source to source and target to target connections are allowed)

[Source](https://reactflow.dev/docs/api/component-props/)

**Comment by RaFaTEOLI** [comment]
Thank you so much! I looked for a solution in the docs but I couldn't find it.
It turned out to be simpler than I thought.
