### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by Azim-Ahmed** [wbkd/react-flow#1688]
How to get of this , I cannot create new nodes

**Comment by xplato** [comment]
Could you provide some contextual code to help us interpret this issue more accurately? An explanation of what you're trying to achieve, besides creating nodes, would also be useful.

**Comment by cliffordfajardo** [comment]
@Azim-Ahmed - were you able to resolve the issue?

If not, can you share a small codesanbox? 
- codesanbox.io  --- [react template](https://codesandbox.io/s/react-ts?file=/src/App.tsx)

**Comment by dzikoysk** [comment]
Also got similar report from Lighthouse:

![obraz](https://user-images.githubusercontent.com/4235722/156475428-f0b85c78-b4b6-4267-bcc8-e511994f5c0e.png)

**Comment by moklick** [comment]
This has nothing to do with React Flow. The d3 drag handlers are not passive because they have to cancel the scroll event (https://github.com/d3/d3-drag/issues/35#issuecomment-314798648).

**Comment by dzikoysk** [comment]
Shouldn't this not be used when dragging is turned off?

```
nodesDraggable={false}
draggable={false}
`

Just like with `nowheel` class. 🤔

**Comment by moklick** [comment]
We are always assigning the wheel handler and then use the filter option in order to prevent it (when a certain option is set or the mouse is hovering a node for example).

**Comment by moklick** [comment]
Got it! Thanks for the hint. I'll leave this issue open for now.

**Comment by dzikoysk** [comment]
Thanks, looking forward v10! ❤️

**Comment by qpointsystems** [comment]
Same issue for me. Using ReactFlow in a "static diagram" mode, so I'm turning unwanted options off like draggable, etc
