### ISSUE TITLE
[FR] Add elements data validation function

### ISSUE THREAD

**Issue by mdneyazahmad** [wbkd/react-flow#1689]
When we input flow data from textarea. It should be validated before we initialize the flow designer.

**Comment by xplato** [comment]
From the very little information you provided, it doesn't sound like this is an issue with ReactFlow. Can you provide some more context to help me interpret this issue?

**Comment by moklick** [comment]
Hey @mdneyazahmad 

please use the discussion section or Discord for specific implementation questions.
