### ISSUE TITLE
Links pass through the nodes

### ISSUE THREAD

**Issue by aShelist** [wbkd/react-flow#1690]
In the standard behavior, the connections goes through the node. And it can confuse the user.

Is it possible to somehow make the connections go around the nodes?

**Comment by xplato** [comment]
If I understand correctly, you're probably going to want to create a custom Edge type. The relevant documentation can be found here: https://reactflow.dev/docs/api/edge-types/

**Comment by aShelist** [comment]
> If I understand correctly, you're probably going to want to create a custom Edge type. The relevant documentation can be found here: https://reactflow.dev/docs/api/edge-types/

Yes, that's right. Unfortunately, when creating a custom Edge type, it only knows about the source point and target point.

Maybe there are examples when it is necessary to node as a "wall" and no connections pass through it?

**Comment by xplato** [comment]
Issue #1642 provides a small amount of starter code which may help with the issue you're talking about. You'd need to create a custom Edge, find the ReactFlow coordinates of two nodes, and adjust the SVG path respectively.

Here, you can see that the Bezier Path is being calculated from the positions of both nodes:

https://github.com/wbkd/react-flow/blob/56507104cfd672dbda5303003082e62f887c3f7c/src/components/Edges/BezierEdge.tsx#L19-L46

**Comment by tisoap** [comment]
I  had the same requirement in a project so I created a custom edge and published it as a module:
https://github.com/tisoap/react-flow-smart-edge

**Comment by moklick** [comment]
For now this can only be done with a custom edge logic.
