### ISSUE TITLE
[FR]: Modifier keys to increase Handle pointer event size

### ISSUE THREAD

**Issue by xplato** [wbkd/react-flow#1695]
Forgive the rather ambiguous title. 

Preface: I know this is a somewhat advanced feature; I just thought I'd mention it.

Within my project, we're trying to find a way to use a modifier key (like Option) to click and drag from anywhere within a node which will start dragging a handle.

This would look like:

1. Start holding Option
2. Click and Drag mouse from anywhere within a node
3. The edge line starts displaying (as if dragging from the `Handle` component)
4. Drag line to anywhere within another node
5. Release mouse to attach line

It seems like there is already some code, whether by intention or coincidence (likely the latter), to begin this feature. For example, the `onNodeDragStart={(ev, el) => {}` function passes a few key props. Namely, `altKey`. This indicates whether the key is pressed during the drag, clearly.

The trouble we're having is starting the new line connection, and then dropping it on another node.

If this is something outside of the scope of ReactFlow, feel free to close this issue. I thought I'd mention this as the tiny handle area is a little too small by default to create new connections. It's possible, but not as easy as it could be.

This feature suggestion would really make creating new connections a breeze.

Thank you so much for your time.

**Comment by datoslabs** [comment]
@xplato, you should be able to implement a custom handle to make it bigger so that it's easier for the users.  BTW, `onNodeDragStart` is for dragging the node itself, if I understood you correctly, you are concerned about DnD on the node handles to start/end a connection.

**Comment by xplato** [comment]
Increasing the handle size has always been a possibility. I'm mentioning new behavior that allows creation of an edge directly on a node, not only the handle—behavior that would be activated with some modifier key (`option`, for instance).

**Comment by moklick** [comment]
This is a good idea @xplato ! At this point our priority is the v10 release. I will keep this issue open to discuss it after the release.

**Comment by ratasorin** [comment]
Any updates on this feature, or any ways we might be able to implement it ourselves @moklick ?

**Comment by moklick** [comment]
This is possible and we have an example :) https://reactflow.dev/docs/examples/nodes/easy-connect/
