### ISSUE TITLE
Library Breaking When Trying Update Edge

### ISSUE THREAD

**Issue by phantomdebug** [wbkd/react-flow#1697]
I have two custom nodes that I am trying to drag the upper part of the edge (the source), to another custom node (target), but when i do that it breaks the application with the following message:

TypeError: Cannot read properties of null (reading 'find')
    at ConnectionLine (cjs.js:12)

This only happens when the target is a custom node, whenever the target is a normal node like my finish node which is an output type, it works perfectly!

Also it is important to say that whenever i drag from the lower part of the edge (the part where the arrow is) it works perfectly too, even with custom nodes.

Here is an example of it working...
<img width="322" alt="Works" src="https://user-images.githubusercontent.com/94709373/142671736-77f32fa1-ada9-4716-877c-07f7dfa2e7ca.png">

But when i try to drag from start to apiNode it breaks even before i can drag it.
<img width="303" alt="DoesntWork" src="https://user-images.githubusercontent.com/94709373/142671824-a9536339-507d-4d0c-b544-801d6fe24507.png">

**Comment by xplato** [comment]
I had a similar problem with custom nodes. I discovered that my nodes didn't have the `data-nodeid` attribute. Can you try inspecting the DOM output to see if your custom nodes have the same attributes as normal nodes?

The `find` function this error is referencing works with the ID of the node, this is why I'm asking.

It may also be helpful to provide the code you're using to create these custom nodes.

**Comment by phantomdebug** [comment]
Thank you for the answer!

Here are my DOM attributes:
<img width="357" alt="CustomNode" src="https://user-images.githubusercontent.com/94709373/142674208-e7e6abf9-d82c-40ae-8fd7-5dabf8fa8353.png">

They seem normal haha.

And here is my custom node code:

`const ConversationNode: FC<NodeProps> = ({ data }) => {
  return (
    <Box
      borderWidth="1px"
      borderRadius="3px"
      borderColor="blue"
      color="black"
      background="#fff"
      p="5"
      fontSize="12px"
    >
      <Flex
        data-testid="label"
        flexDirection="column"
        alignContent="center"
        alignItems="center"
      >
        <CFiMessageCircle color="black.300" /> {data.label}
      </Flex>
      <CustomHandle />
    </Box>
  );
};`

This custom handle is a component that i created so i can use the same in other custom nodes, because they all have the same handle attributes.

Here is the CustomHandle code:

`const CustomHandle = (): JSX.Element => (
  <>
    <Handle
      type="source"
      position={Position.Right}
      id="source-a"
      isConnectable={true}
    />
    <Handle
      type="source"
      position={Position.Right}
      id="source-a-1"
      isConnectable={true}
      style={{ top: "75%" }}
    />
    <Handle
      type="source"
      position={Position.Right}
      id="source-a-2"
      isConnectable={true}
      style={{ top: "25%" }}
    />

    <Handle
      type="source"
      position={Position.Left}
      id="source-b"
      isConnectable={true}
    />
    <Handle
      type="source"
      position={Position.Left}
      id="source-b-1"
      isConnectable={true}
      style={{ top: "75%" }}
    />
    <Handle
      type="source"
      position={Position.Left}
      id="source-b-2"
      isConnectable={true}
      style={{ top: "25%" }}
    />

    <Handle
      type="source"
      position={Position.Bottom}
      id="source-c"
      isConnectable={true}
    />
    <Handle
      type="source"
      position={Position.Bottom}
      id="source-c-1"
      isConnectable={true}
      style={{ left: "75%" }}
    />
    <Handle
      type="source"
      position={Position.Bottom}
      id="source-c-2"
      isConnectable={true}
      style={{ left: "25%" }}
    />

    <Handle
      type="source"
      position={Position.Top}
      id="source-d"
      isConnectable={true}
    />
    <Handle
      type="source"
      position={Position.Top}
      id="source-d-1"
      isConnectable={true}
      style={{ left: "75%" }}
    />
    <Handle
      type="source"
      position={Position.Top}
      id="source-d-2"
      isConnectable={true}
      style={{ left: "25%" }}
    />
  </>
);`

**Comment by phantomdebug** [comment]
And in case you're wondering those custom nodes they are dropped on screen and i generate an id for each one of them:

`const onDrop = (event: DragEvent) => {
    event.preventDefault();

    if (reactFlowInstance) {
      const type = event.dataTransfer.getData("application/reactflow");
      const label = type === "input" ? "Start" : type;
      const position = reactFlowInstance.project({
        x: event.clientX - 300,
        y: event.clientY - 300,
      });

      const newNode: Node = {
        id: getId(),
        type,
        position,
        data: { label: `${label}` },
      };

      setElements((es) => es.concat(newNode));
    }
  };`

**Comment by xplato** [comment]
I see. I don't see anything right away that would indicate this error.

Try adding the following prop to your `ReactFlow` component and let me know what the console output is.

```
onConnect={(source, target) => {
    console.log('source', source);
    console.log('target', target);
}}
```

Specifically, I'm looking for the ID value of the `source` and `target`. Also, if they do output an ID, please check if those IDs match the IDs of the nodes in the DOM.

**Comment by Ipicky22** [comment]
Hi @phantomdebug  !

I encountered the same problem when I wanted to make a Custom Node with a dynamic handle number.
I don't know if my solution will solve your problem, but maybe a research lead.

I solved with useUpdateNodeInternals, the documentation :
https://reactflow.dev/docs/api/hooks/#useupdatenodeinternals

You can find my way out with the answers and some code here : [#1641 ](https://github.com/wbkd/react-flow/issues/1641)

Another thing, wouldn't it be better to create an object containing all your information, and in CustomHandle to map this object? You would have a unique Handle like that ;)

I hope I have been helpful.

**Comment by phantomdebug** [comment]
> I see. I don't see anything right away that would indicate this error.
> 
> Try adding the following prop to your `ReactFlow` component and let me know what the console output is (try connecting two nodes together to see it).
> 
> ```
> onConnect={(source, target) => {
>     console.log('source', source);
>     console.log('target', target);
> }}
> ```
> 
> Specifically, I'm looking for the ID value of the `source` and `target`. Also, if they do output an ID, please check if those IDs match the IDs of the nodes in the DOM.

Thanks for the tips, I tried, but when the error occurs it occurs before even trying to connect, and when i checked dom, the IDs of the nodes matched.

**Comment by phantomdebug** [comment]
> Hi @phantomdebug !
> 
> I encountered the same problem when I wanted to make a Custom Node with a dynamic handle number. I don't know if my solution will solve your problem, but maybe a research lead.
> 
> I solved with useUpdateNodeInternals, the documentation : https://reactflow.dev/docs/api/hooks/#useupdatenodeinternals
> 
> You can find my way out with the answers and some code here : [#1641 ](https://github.com/wbkd/react-flow/issues/1641)
> 
> Another thing, wouldn't it be better to create an object containing all your information, and in CustomHandle to map this object? You would have a unique Handle like that ;)
> 
> I hope I have been helpful.

Thank you for your answer, i'm gonna look into it right now, but one thing i noticed is that my handles id are always the same across all the nodes, they follow these handle id patterns:

source-a - Position Right
source-a-1 - Position Right Bottom
source-a-2 - Position Right Top

source-b - Position Left
source-b-1 - Position Left Bottom
source-b-2 - Position Left Top

source-c - Position Bottom
source-c-1 - Position Bottom Left
source-c-2 - Position Bottom Right

source-d - Position Top
source-d-1 - Position Top Left
source-d-2 - Position Top Right

That's why i use the same component in all custom nodes i have, because they must have the same handles, and i think i cannot use those IDs in all nodes... 

I'm gonna look into the hook you mentioned and also do some testing, thank you

**Comment by Ipicky22** [comment]
@phantomdebug 

I don't think that the fact that all the handles of the cutom nodes have the same id is a problem, because I am doing the same in my example.

when a custom node is created it receives an ID, and I think the handles are associated through this ID. And the hook allows you to do that.

For example my custom node has an ID "custom-node-id" and the handles will be found maybe like "custom-node-ID source-a".

I think you should put a UseEffect with the useUpdateNodeInternals hook which takes the nodeId as a parameter.

If you want you can send a codesandbox of your code and I can try on my side.

**Comment by phantomdebug** [comment]
> @phantomdebug
> 
> I don't think that the fact that all the handles of the cutom nodes have the same id is a problem, because I am doing the same in my example.
> 
> when a custom node is created it receives an ID, and I think the handles are associated through this ID. And the hook allows you to do that.
> 
> For example my custom node has an ID "custom-node-id" and the handles will be found maybe like "custom-node-ID source-a".
> 
> I think you should put a UseEffect with the useUpdateNodeInternals hook which takes the nodeId as a parameter.
> 
> If you want you can send a codesandbox of your code and I can try on my side.

I followed your instructions and i added the hook on the useEffect, but i still got the same error, is this what you meant?

`
const ConversationNode: FC<NodeProps> = ({ id, data }) => {
  const updateNodeInternals = useUpdateNodeInternals();

  useEffect(() => {
    updateNodeInternals(id);
  }, []);

  return (
    <Box
      borderWidth="1px"
      borderRadius="3px"
      borderColor="blue"
      color="black"
      background="#fff"
      p="5"
      fontSize="12px"
    >
      <Flex
        data-testid="label"
        flexDirection="column"
        alignContent="center"
        alignItems="center"
      >
        <CFiMessageCircle color="black.300" /> {data.label}
      </Flex>
      <CustomHandle />
    </Box>
  );
};

export default memo(ConversationNode);
`

**Comment by Ipicky22** [comment]
Yes, can you share your code in sandbox ?

**Comment by phantomdebug** [comment]
> Yes, can you share your code in sandbox ?

Sure, let me create and you will send you right away...

**Comment by phantomdebug** [comment]
> Yes, can you share your code in sandbox ?

There you go, but funny thing that just happened, it works normally on the sandbox, but my local server doesn't...

https://codesandbox.io/s/zealous-joliot-nwkx1?file=/src/App.tsx

**Comment by phantomdebug** [comment]
Guys, thank you for everyone who has tried to help, i just figured out that what solved the problem was updating react-flow-renderer from 6.9.7 to 9.6.11, the problem is now gone!

I figured this out because the codesandbox updated the react-flow-renderer and it somehow fixed the issue!

Closing this issue! thank you.
