### ISSUE TITLE
any way for a particular node to show at the top. See the video

### ISSUE THREAD

**Issue by amans2k** [wbkd/react-flow#1700]
Hello,

First of all a great library.

I was using this in a project. Implemented dagre. In between found some issues, but corrected most.

One thing I am stuck at is this.
See http://imgwxl.com/a/2021-11-21-17:01:36.png

After condition, yes and no should come in a single horizontal line, but as you can see they are adjusting automatically with dagre.

Later I found elkjs and tried this. See http://imgwxl.com/a/2021-11-21-05:41:46.png
On node level, they have a 'partition' key, which keeps the node on the same level. See yes and no.

If I mark node n22, partition 3, it will move to n31 'sales' node.

Does anyone have any solution with dagre on this?

Any help (paid also) would be appreciated.

**Comment by moklick** [comment]
Is your question about layouting or the z-index?

**Comment by amans2k** [comment]
Hi @moklick 
it is about layouting

I have a node called condition.

2 nodes coming out of it, lets say 'yes' and 'no'
both nodes should appear in a single horizontal line.

Any idea or possibility how that can be achieved via dagre.

**Comment by moklick** [comment]
Please consider to ask this in the dagre repository. We can't help you with this.
