### ISSUE TITLE
If i can use 3rd party component as custom nodetype. I can't access react-redux context value

### ISSUE THREAD

**Issue by jagadeeshpatta** [wbkd/react-flow#1707]
If i can use 3rd party component as my custom node component i am getting following issue.

**Error: could not find react-redux context value; please ensure the component is wrapped in a `<Provider>`**

Thanks for any suggested solution.

**Comment by xplato** [comment]
Is your `ReactFlow` component wrapped in the `ReactFlowProvider`? If not, wrap it and see if this error still happens. If the error doesn't go away, please add an explanation of what you're trying to achieve.

See: https://reactflow.dev/docs/api/components/provider/

**Comment by jagadeeshpatta** [comment]
I have following components to render.

1. ComponentA
2. ComponentB
3. ComponentC
4. ComponentD
5. ComponentRenderer

`ComponentRenderer` Will takes care of render the components form A to D by conditional rendering. 

My main component like 

class MainComponent {

  nodeTypes = {
    'a': ComponentA,
    'b': ComponentB,
    'c': ComponentC,
    'd': ComponentD,
    'renderer': ComponentRenderer,
  }

nodesList = [
  {
  id: '1',
  type: 'renderer',
  position: {
    x: 20,
    y: 200,
  },
  data: {
    ...customdata,
  },
  }
]

  render() {
      <ReactFlowProvider>
           <ReactFlow
             nodeTypes={nodeTypes}
             elements={nodesList}
           />
      </ReactFlowProvider>
  }
}

Note: 

- All components under the same package. 
- ComponentRenderer renders remaining components based on internal business conditions.


Thanks
Jagadeeswara Rao patta

**Comment by xplato** [comment]
Have you tried wrapping `MainComponent` in the `ReactFlowProvider `? You could also setup a Codesandbox so that I can investigate this issue quicker.

**Comment by jagadeeshpatta** [comment]
I have moved all used components under the one folder structure then its working fine. 

Thanks for support.
