### ISSUE TITLE
Issues with fitView when asynchronously loading elements and container height from an API - NextJS (codesandbox provided)

### ISSUE THREAD

**Issue by tompbsmith** [wbkd/react-flow#1712]
Hi,

I'm having trouble trying to get fitView called after new elements are loaded asynchronously in a Next JS site I'm working on.

I've looked through all the fitView-based threads on here and tried all the solutions but they're not working for me. I followed [this thread](https://github.com/wbkd/react-flow/issues/533) and tried the different fixes in there, including the one linked at the bottom by @chrtze ([here](https://codesandbox.io/s/unruffled-ishizaka-fhljt?file=/src/App.js)) but it didn't solve the issue for me.

Just to explain my set-up. I have an API that serves react-flow elements as json to the getStaticProps() function of two pages in a NextJS app. These pages pass the elements, along with the container height to the component that uses ReactFlow as props. I use useEffect to set the elements and height and have tried using the setup in @chrtze 's answer to set the ReactFlow state onLoad() with a second useEffect that checks that the elements, ReactFlow instance and height have been set and then calls fitView() on the instance. Each page has a link to each other underneath the ReactFlow container, which triggers the re-render.

However, this isn't working, the charts don't resize and clip out of the container. I have added a button that calls fitView() on click to make sure fitView() is working correctly, which it is. It just seems that, even with using the useEffect() trick, fitView() still isn't being called after the new height is set and the new elements are loaded.

I've also added console.log() comments to see in what order each function is called (onLoad and the useEffects) and it seems they are called in a different order on first load (when you refresh the page manually) and when you click the link, triggering the re-render, so I guess this is where the issue might be.

I would be very grateful if somebody could take a look and can see what I am doing wrong. The main difference between my example and @chrtze 's is that I'm using NextJS and also changing the height of the container <ReactFlow /> sits inside, so maybe that's part of the issue also?

Here is the codesandbox: [https://codesandbox.io/s/sleepy-silence-1pdcw](https://codesandbox.io/s/sleepy-silence-1pdcw)

Thanks to anyone who has a look at it, it's greatly appreciated!

P.S. Please ignore the custom node and edge visual bugs, I haven't got around to fixing them yet because this issue took my focus.

**Comment by xplato** [comment]
I know this may not be the "straightforward" answer you're looking for, but it might help.

I had this same problem, although instead of fitting the view I needed to set it to a specific placement and zoom.

Anyways, what I did was create a loading component that visually covered the ReactFlow container. I then passed this loading state to the container of ReactFlow, which would turn off the loading screen once the RF instance was loaded. It looks roughly like this:

```
const FlowContainer = () => {
    // state here
    return (
         <>
             <FlowLoading loading={loading} />
	    <FlowPanel setLoading={setLoading} />
        </>
    )
}
```

Then, in `FlowPanel`:

```
const onLoad = reactFlowInstance => {
	setInstance(reactFlowInstance);

	setTimeout(() => {
                // notice that I don't use the state instance
		if (Boolean(reactFlowInstance)) {
			reactFlowInstance.fitView();
		}
		setLoading(false);
	}, 20);
};
```

This timeout should help. Essentially, we're allowing the Flow to render without us seeing it right away. Once it's done rendering (given to us by `onLoad`), we can safely remove the loading screen and fit the view.

My setup is identical to yours: NextJS with API-served elements. I'm not sure if this will work for you, but let me know if it does.

I hope this helps.

**Comment by chrtze** [comment]
I have just encountered the same bug in a different project. We will look into it for the next release as well.

**Comment by tompbsmith** [comment]
@xplato Thanks for this, I think that'll be the way I end up going. I've got it working (relatively well) with the setTimeout trick so far so thanks for that! The graphs I'm working with are relatively small so the change before/after the fitView isn't perceptible but I'm worried that when I start incorporating larger graphs, they will flash for a split second as not fitting before fitView is called and so I'll probably then need to go your route and overlay a "loading" pane. Thanks again for the help!

**Comment by moklick** [comment]
@tompbsmith I don't know how complex your project is, but could you try the next major version `npm i --save react-flow-renderer@next` (there are some breaking changes that are listed here #1555). That version comes with a `fitViewOnInit` prop that should solve your problem.

**Comment by moklick** [comment]
Please re-open if the issue still persists.
