### ISSUE TITLE
Edge with button problems on Safari

### ISSUE THREAD

**Issue by bulka52017** [wbkd/react-flow#1714]
Hi, 

I've faced two problems on Safari, button on edge either not renders or flickers while hovering on it. The problems doesn't seem to happen on other browsers. It can be reproduced on your example here [https://reactflow.dev/examples/edge-with-button](url).

https://user-images.githubusercontent.com/37633322/143442079-a28608e0-195f-4425-a99e-17ec6b34c171.mov

Also recording from chrome and safari for comparison

Chrome:

https://user-images.githubusercontent.com/37633322/143442383-e3bb97f1-fd6f-4893-8a71-39d1ec9e27d6.mov

Safari:

https://user-images.githubusercontent.com/37633322/143442468-5f135731-be0b-46ef-9540-cf7c68598295.mov

Additionally, I don't know if it's related, but fonts are blurring while starting hovering on them on Safari.

Chrome and safari for comparison:

https://user-images.githubusercontent.com/37633322/143443263-d4c40933-54da-4fa1-845e-ed2c40a2e489.mov

https://user-images.githubusercontent.com/37633322/143443284-95f25b76-7d35-464b-8d4a-58423b081f9e.mov

Haven't found any previous related issues, if it's something that you're working on please let me know.

**Comment by moklick** [comment]
The problem in the example occurs because of:

```css
.edgebutton:hover {
  transform: scale(1.1);
  box-shadow: 0 0 6px 2px rgba(0, 0, 0, 0.08);
}
```

When you remove the `transform` rule everything is fine. I will close this issue and adjust the example. Thanks for the report!
