### ISSUE TITLE
Edges stay in the ui even when we change the values of json

### ISSUE THREAD

**Issue by mhmm2005** [wbkd/react-flow#1715]
https://stackoverflow.com/questions/70114700/react-flow-renderer-edges-remain-in-ui-without-any-parents

**Comment by piyushchauhan** [comment]
@mhmm2005 Unable to play this video.

**Comment by mhmm2005** [comment]
@piyushchauhan yes you are right, i just upload the video about issue to YouTube, please check it

**Comment by moklick** [comment]
Hey @mhmm2005 

could you create a codesandbox or repo for this issue?

**Comment by mhmm2005** [comment]
@moklick I create a codesandbox,
https://codesandbox.io/s/vigorous-rumple-pgfi3?file=/E2e.js
Thanks in advance.

**Comment by moklick** [comment]
This is not an issue with react flow. I am not sure what you are doing in that `loadData` function but when you only call it once instead of every second everything works as expected.

**Comment by mhmm2005** [comment]
@moklick  I know if i just once get data it works fine, but i need to update the information about edges and nodes periodically updated...

**Comment by xplato** [comment]
@mhmm2005 Once again, this is not an issue with ReactFlow. It's a problem related your codebase than can be solved with a better understanding of how React works under the hood.

I'd recommend reading through [A complete guide to `useEffect` by Dan Abramov.](https://overreacted.io/a-complete-guide-to-useeffect/) If that article doesn't answer your question, try posting on Reddit.

**Comment by mhmm2005** [comment]
@xplato I found the issue, it was because of repeated id for edges...

**Comment by xplato** [comment]
I'm glad you were able to fix it quickly :)
