### ISSUE TITLE
Drag and Drop Example does not allow me be create my own node in the sidebar itself.

### ISSUE THREAD

**Issue by piyushchauhan** [wbkd/react-flow#1719]
While exploring https://reactflow.dev/examples/drag-and-drop/

event of type `DragEvent<HTMLDivElement>` allows to set data with strings only with `event.dataTransfer.setData('application/reactflow', nodeType);` 
`nodeType` must a string.

I want to add the node data in `onDragStart` fn itself. The library should be able to transfer the node in the flowInstance.

**Comment by moklick** [comment]
This is not an issue with React Flow. The examples are just very simple. I am not sure what you want to do here. You can stringify your data or better get the data from somewhere else in the moment you add it to the React Flow pane.

**Comment by sreeteja06** [comment]
@piyushchauhan where you able to add custom node data to onDragStart? If so can you share how you did it.
