### ISSUE TITLE
Cannot declare two edge type 

### ISSUE THREAD

**Issue by YukioSenpai** [wbkd/react-flow#1730]
My problem is that i am creating edges that are using a custom type : 

` id: `e${i}`,
   type: 'removeEdge'`

But if i want to have my edge with a type step, i can't do that because i already define my type with my custom edge.

Is there a possibility to add an other type if you already defined your edge with a custom type ?

**Comment by moklick** [comment]
Hey @YukioSenpai 

sorry I can't follow you. What is the exact issue here? Do you have a code example I could look at?

**Comment by YukioSenpai** [comment]
<img width="537" alt="Screenshot 2021-11-30 at 18 09 19" src="https://user-images.githubusercontent.com/25082266/144094242-050452c7-0e16-43d0-b56f-46c7ee7bc494.png">

I am creating edge like that, i give them a type, who here is custom (to be able to add a button to delete them on click). The problem is i also want to give them the type step : `type: 'step` to make the edge straight. But i looked around and it look like it's not possible.

**Comment by moklick** [comment]
You can only have on type for an edge. When you implement a custom one you can use the `getSmoothStepEdge` helper function https://reactflow.dev/docs/api/edge-utils/ within your custom one to render a step edge. This is a custom edge that uses the `getBezierEdge` helper https://reactflow.dev/examples/edge-with-button
