### ISSUE TITLE
Typescript : ReactFlow component doesn't accepts children

### ISSUE THREAD

**Issue by EmanueleGurini** [wbkd/react-flow#1731]
Hi guys, we'r getting this problem: 

## Premise 
We'r using:
1. "react-flow-renderer": "^9.5.4" 
2. "typescript": "3.4.4"

## Problem
following instructions at this link https://reactflow.dev/examples/ we put Minimap, Controlls and Backgrounds components inside `<ReactFlow>` but we'r getting this message : 

> Property 'children' does not exist on type 'IntrinsicAttributes & ReactFlowProps & RefAttributes<HTMLDivElement>'

We can bypass this problem just doing following steps:

 `const ReactFlowAny : any = ReacFlow`

and 

```
<ReactFlowAny>
   <Controlls ...>
   <Minimap ...>
   <Background ...>
</ReactFlowAny>
```

We think that could be a problem about typescript inferfaces: could you fix it?

**Comment by YukioSenpai** [comment]
I am in `"react-flow-renderer": "^9.6.7"` and i have no problem at all

**Comment by moklick** [comment]
I can't reproduce this. Please update to the latest version. All examples in this repo are written in Typescript. The wrapper uses `FunctionComponent` which includes children.
