### ISSUE TITLE
No sourceHandleId and targetHandleId in custom edge

### ISSUE THREAD

**Issue by stanislav-grin** [wbkd/react-flow#1735]
I'm trying to get the handle's position in the custom Edge component, but for some reason both `sourceHandleId` and `targetHandleId` props are null, so I can't find the handle without this.

I'm using Floating Edge from this example: 
https://reactflow.dev/examples/floating-edges

```js
function FloatingEdge({ id, source, target, sourceHandleId, targetHandleId }) {
  const nodes = useStoreState(state => state.nodes)

  const sourceNode = useMemo(() => nodes.find(n => n.id === source), [source, nodes])
  const targetNode = useMemo(() => nodes.find(n => n.id === target), [target, nodes])

  if (!sourceNode || !targetNode) {
    return null
  }

  // sourceHandleId and targetHandleId are null

  ...
```

And in custom nodes I pass `handleId` to the Handle components:

```js
<Handle
  type="source"
  position="top"
  id="here-goes-a-handler-id"
  isConnectable={ isConnectable }
  className="node-handler"
/>
```

What can be an issue?
I was trying to find a similar problem/question in existing issues, but no luck.

**Comment by chrtze** [comment]
hi @stanislav-grin! thanks for sponsoring us, we really appreciate it. The sourceHandleId and targetHandleId properties are passed down from your edge configuration in the elements array. To use it in your custom edge, you need to set the `sourceHandle` property on your edge. For example:

```
{
        id: "e2a-3",
        source: "2",
        target: "3",
        sourceHandle: "a",
        animated: true,
        style: { stroke: "#fff" },
        type: "custom"
      }
```

Hope that helps!

**Comment by stanislav-grin** [comment]
Hi @chrtze, thank you! That helped me.
