### ISSUE TITLE
Edges disappearing when graph is updated

### ISSUE THREAD

**Issue by ericjunkins** [wbkd/react-flow#1736]
## Problem 
I'm trying to make a graph where clicking on a node will show/hide all of its' recursive children. I tried following along with some of the examples and cherry picking what I needed. 

I'm having an issue where when I update the `elements`  to the graph it deletes all the links in the graph (not just hides them, but no longer DOM elements) that are either source or target of the clicked node. I also had to force that node to have `opacity: 1` otherwise it would also be hidden. 

## Code 

```
import React, { useState, useEffect } from 'react';
import ReactFlow, {isNode} from 'react-flow-renderer';
import dagre from 'dagre';

import { Spinner, Center } from '@chakra-ui/react';

import './layouting.css';

export const TestGraph = [
    { name: 'A', label: "A", parent: null, sectionParent: "A", type: "input"},
    { name: 'B', label: "B", parent: "A", sectionParent: "A"},
    { name: 'C', label: "C", parent: "B", sectionParent: "B"},
    { name: 'D', label: "D", parent: "B", sectionParent: "B"},
    { name: 'E', label: "E", parent: "C", sectionParent: "B"},
]

export const getGraphElements = (parents = ['A']) => {
    let nodes = [],
        links = []
    
    // Find all the nodes that have section parents in current selection
    let filtered = TestGraph.filter(d=> parents.includes(d.sectionParent))
    
    filtered.forEach(function(d){
        // Add all the nodes
        nodes.push({
            id: d.name,
            type: d.type ? d.type : null,
            position: {x:0, y:0},
            data: {
                label: (
                    <>
                        {d.label}
                    </>
                ),
            },
            style: {
                cursor: "pointer",
                opacity: 1
            }
        })
        // If the parent isn't the root then add the link to the parent
        if (d.parent != null){
            links.push({
                id: d.parent + '-' + d.name,
                source: d.parent,
                target: d.name,
                style: {
                    opacity: 1
                }
            })
        }
    })

    return nodes.concat(links)
}


const dagreGraph = new dagre.graphlib.Graph();
dagreGraph.setDefaultEdgeLabel(() => ({}));

const nodeWidth = 172;
const nodeHeight = 36;

const getLayoutedElements = (elements, direction = 'TB') => {
    const isHorizontal = direction === 'LR';
    dagreGraph.setGraph({ rankdir: direction });
  
    elements.forEach((el) => {
      if (isNode(el)) {
        dagreGraph.setNode(el.id, { width: nodeWidth, height: nodeHeight });
      } else {
        dagreGraph.setEdge(el.source, el.target);
      }
    });
  
    dagre.layout(dagreGraph);
  
    return elements.map((el) => {
      if (isNode(el)) {
        const nodeWithPosition = dagreGraph.node(el.id);
        el.targetPosition = isHorizontal ? 'left' : 'top';
        el.sourcePosition = isHorizontal ? 'right' : 'bottom';
  
        // unfortunately we need this little hack to pass a slightly different position
        // to notify react flow about the change. Moreover we are shifting the dagre node position
        // (anchor=center center) to the top left so it matches the react flow node anchor point (top left).
        el.position = {
          x: nodeWithPosition.x - nodeWidth / 2 + Math.random() / 1000,
          y: nodeWithPosition.y - nodeHeight / 2,
        };
      }
  
      return el;
    });
};

const onLoad = (reactFlowInstance) => {
    reactFlowInstance.fitView();
};

const OverviewFlow = () => {
    const [parents, setParents] = useState(["A", "B"])
    const [elements, setElements] = useState([]);
    
    useEffect(()=>{
        let ele = getGraphElements(parents);
        let layoutedElements = getLayoutedElements(ele)
        setElements(layoutedElements)
    }, [parents])

    const updateParents = (name) => {
        // Don't do anything if root or null node is clicked 
        if ( name === 'A' || name === null ) return

        // Get temporary array for the parent set nodes shown
        let tmp = Array.from(parents); 
        if (parents.includes(name)) tmp.splice(tmp.indexOf(name))
        else tmp.push(name)

        setParents(tmp)
    }
    
    return (
        <Center w="100%" h="100%">
        {elements.length ? 
            <ReactFlow
                elements={elements}
                nodesConnectable={false}
                onLoad={onLoad}
                snapToGrid={true}
                cursor="pointer"
                onElementClick={(e)=>{ updateParents(e.target.getAttribute('data-id'))}}
                snapGrid={[15, 15]}
                onlyRenderVisibleElements={false}
            >
            </ReactFlow>
            :
            <Spinner size="xl" />
        }
        </Center>
    );
};

export default OverviewFlow;

```

### Image pre-click with edges 

![image](https://user-images.githubusercontent.com/25470708/144682924-23a36be5-d93b-428a-ad8e-e6d990560e5c.png)

### Image after Clicking node "B"

![image](https://user-images.githubusercontent.com/25470708/144683831-c0fce452-7628-4944-9abf-e07513938552.png)

### Image after Clicking node "B" a second time to show all children again

![image](https://user-images.githubusercontent.com/25470708/144683138-77605695-c0a0-4d3d-a742-92a1f1ee57ea.png)

---
Is this because of some way that I'm updating and handling the `elements` for the graph?

**Comment by xplato** [comment]
It's interesting that the C -> E edge remains after a click.

Could you create a Codesandbox so I could investigate this quicker?

**Comment by ericjunkins** [comment]
@xplato sure, I should have started with making a sandbox for to share. Here's the [sandbox link](https://codesandbox.io/s/stupefied-rgb-ldg64?file=/src/App.js) with the example as described above.

**Comment by datoslabs** [comment]
@ericjunkins, the problem resides in the fact that the code is recreating the entire `elements` array including each node's positions; if you rewrite the `useEffect(()=>...,[parents]);` logic to update nodes and edges `isHidden` property like the following (pseudo-code), it would work:

```
...
setElements(els => els.map( .../* update elements' isHidden property goes here*/));
``` 

I tested it out based on your sandbox and it works but unfortunately, I navigated away before I had a chance to save it.  There are several reasons recreating the entire `elements` array is not recommended; besides the obvious performance issues it might cause, `react-flow` maintains an internal state and the rendering of edges depends on the rendering of nodes so elements array update is dealt differently than when the graph is first initialized which is why the edges were not rendered in your case.  I have written up in the past extensively on similar edge update issues and provided explanations.  The tldnr version is when edges are being rendered, it relies on the nodes' underlying HTML element coordinates and bounding-box to construct its `<path>`; when all the nodes positions change (in the `getLayoutedElements()`) there is a race condition between React updating the HTML elements' coordinates/bounding-boxes and rendering of the edges thus causing some of the edges to disappear.

**Comment by ericjunkins** [comment]
@datoslabs I was able to get the example working by changing the `isHidden` property of them. Howerver you mention that it  is inadvisable to be recreating the `elements` array at each step. I believe that this is _not_ an issue and i'll close this issue and move discussion to the Discussions board instead.
