### ISSUE TITLE
Feature Request : Prevent nodes from overlapping each other

### ISSUE THREAD

**Issue by HusainNahrpurawala** [wbkd/react-flow#1737]
Hi,
I faced a weird bug, when I implemented collapsing nodes. When some nodes are hidden, other nodes can overlap them and since they are not rendered we don't know that then. But on setting isHidden to false, all the nodes are cluttered. 
So it would be great if nodes could have preventOverlap property which could push nodes when they try to overlap.

This could also be a handy property overall. 

And if this is possible using styles or changing the position prop, please let me know.

**Comment by cliffordfajardo** [comment]
Hi @HusainNahrpurawala 👋 
Can you share a small codesanbox.io links with a small example demonstrating what you are referring to?
With a codesanbox.io link, it will be easier to understand the problem and interact with it as well.

The `react-flow` team works on this project in their free time with limited time and resources, despite sharing this amazing free library with others. The easier it is to understand your challenge or issue the higher chance it may have of action being taken upon it.

I understand that it may be slightly challenging to reproduce the code as it takes some time to package it up into a small reproducible code example, but it is greatly appreciated

Below is a sample reference bug report issue that might help you create a small reproducible codesandbox.io example that will make it easier for the team to understand the challenge you are facing.


## Sample Image Example ↓ </summary>
<a href="https://github.com/wbkd/react-flow/issues/1796">
  <img src="https://user-images.githubusercontent.com/6743796/147515703-fcb9e485-bbd0-4e3c-9035-0e9bfbf3b979.png" alt="sample bug report image"/>

</a>

**Comment by moklick** [comment]
Hey @HusainNahrpurawala 

thanks for your input, but we will not add collision detection to the core.

**Comment by Pankaj-birla** [comment]
Hey @moklick Is there now a way to implement a solution for preventing nodes from overlapping, whether via a plugin, custom implementation, or other methods?

Thanks in advance for the update!

**Comment by moklick** [comment]
Layouting is a huge topic and there are libraries that can help you to position your nodes automatically. We collected the good ones on this page: 

https://reactflow.dev/learn/layouting/layouting

I hope it helps!

**Comment by cliffordfajardo** [comment]
Very nice! This live playground on the official website is great! It lets you test out different libraries and common examples
https://play.reactflow.dev/

![Image](https://github.com/user-attachments/assets/78034f83-afed-4454-8ae9-51e61c3660e1)

![Image](https://github.com/user-attachments/assets/7a31a012-5548-4072-9c15-b2c78d2ff2a7)
