### ISSUE TITLE
Drag issue in ReactFlow inside ReactFlow.

### ISSUE THREAD

**Issue by jagadeeshpatta** [wbkd/react-flow#1743]
Hi Support,

I have Created one treeview. It has following are the some sample components to replicate the functionality.

ComponentA
     - Has ReactFlow instance. And it has one custom node (ComponentB). And it container 'nodrag' class inside node props to enable drag inside the component. 
    
ComponentB
     - Has ReactFlow instance. 

Now my concern is i am unable to do drag or pan operations on ReactFlow instance inside ComponentB. Could you please suggest how can i achieve this one.

Note: I have already encapsulated Provider for both the reactflow instances.

Thanks
Jagadeeswara Rao Patta

**Comment by jagadeeshpatta** [comment]
Yes it is

**Comment by datoslabs** [comment]
Are you looking to allow users to zoom/pan on the group node and/or enable horizontal/vertical scrolling on the group node without affecting the overall zoom/pan?

**Comment by jagadeeshpatta** [comment]
I would like to enable scroll and pan on group of sub nodes (1a to 1f) in the above example.

**Comment by datoslabs** [comment]
TBH @jagadeeshpatta, I have not had a chance to try out the new feature so I am not 100% sure.  I reviewed the implementation and have posted some questions for the maintainers in #1024; their response will determine if it's feasible to scroll and pan children nodes within parent nodes (and hide them if they are outside of the "parent view port").

**Comment by moklick** [comment]
There is no support for a React Flow instance inside a React Flow component. As @datoslabs said we worked on a sub flow feature (see installation instructions and API in this PR: #1555) but all nodes are on the same canvas. There are no separate zoom levels and pan transforms for sub flows. 

I will close this for now. If you have any updates or further questions feel free to open it again.

**Comment by jagadeeshpatta** [comment]
If i use below code for inner tree its working fine

`<ReactFlowProvider>
              <ReactFlow
                nodeTypes={nodeTypes}
                elements={positionedElements}
                snapToGrid="true"
                snapGrid="[15,15]"
                onLoad={onLoad}
                zoomOnDoubleClick={false}
                onMouseUp={(event) => {
                  const canvas = event.currentTarget
                  select(canvas).on('zoom', null)
                }}
                onPaneClick={(event) => {
                  const canvas = event.currentTarget
                  const treestate = treeInstance.toObject()
                  select(canvas).call(
                    D3.zoom.on('zoom', (ev) => {
                      const { x, y } = ev.transform
                      treeInstance.setTransform({ x, y, zoom: treestate.zoom })
                    }),
                  )
                }}
              />
            </ReactFlowProvider>`
