### ISSUE TITLE
Scroll does not behave as expected when zoomOnScroll and panOnScroll disabled

### ISSUE THREAD

**Issue by audrey-insitro** [wbkd/react-flow#1757]
When zoomOnScroll is disabled, if your mouse is hovering over the chart then scrolling up and down does nothing rather than the expected behavior of scrolling up and down the webpage. This can be seen in the interactive example here when zoomOnScroll and panOnScroll are both unchecked: https://reactflow.dev/examples/interaction/

**Comment by xplato** [comment]
If you don't need interactivity, you can set `pointer-events: none;` via CSS on the container.

**Comment by audrey-insitro** [comment]
After some more digging, it looks like disabling the `preventScrolling` option is what I need. Closing this.

**Comment by reckter** [comment]
`preventScrolling` should probably be added to this documentation page: https://reactflow.dev/docs/guides/panning-and-zooming/

**Comment by moklick** [comment]
Good point @reckter . I just added it to the docs!
