### ISSUE TITLE
how to style edges when clicking and dragging?

### ISSUE THREAD

**Issue by TamjidTayeb** [wbkd/react-flow#1758]
I have been able to style edges that exist in the diagram, but i want to make the visible edge that appears when you click and drag to create a new edge have the same styling, namely i want to give it a specific strokeWidth. I tried passing a strokeWidth to the ReactFlow component but nothing changes, how can I achieve this?

As you can see bellow the existing edge on the right has a strokeWidth of 5px but i haven't been able to apply that to the edge on the left which is created when clicking and dragging to create a new edge

![image](https://user-images.githubusercontent.com/38994890/145647290-039dc91b-a3e7-4707-8836-d10ceaba12b2.png)

**Comment by moklick** [comment]
Hey @TamjidTayeb 

we call it "connectionline" in the docs. The prop you are looking for is `connectionLineStyle`. 

```js
const connectionLineStyle = { strokeWidth: 5 };

... 

// React Flow prop
connectionLineStyle={connectionLineStyle}
```

Does this work for you?
