### ISSUE TITLE
React-DnD within Node

### ISSUE THREAD

**Issue by AndrewJSchoen** [wbkd/react-flow#1765]
Hi all,

Thanks for the great library! I am trying to set up a system where the major nodes of a diagram are handled by `react-flow` like in the [drag and drop example](https://reactflow.dev/examples/drag-and-drop/), and then internally, `div` elements can be dragged and dropped _within_ those nodes with the `react-dnd` library (in a nested way). Note, the main nodes handled by `react-flow` cannot be dragged into the nodes, only onto the canvas. Only specific elements can be dragged into nodes, and they are a different set than the ones interacting with the canvas directly. Currently, I have it working that the canvas nodes can be dragged around in `react-flow` and elements can be dragged _into_ those nodes with `react-dnd`, however once those elements are placed, they no longer respond to drag events through `react-dnd`. I have tried using the `nodrag` class on the elements to get around this, but it doesn't change the behavior. It seems like the event propagation seems to be blocked or something. Do you have any suggestions on how to get this working?

Thanks!

**Comment by moklick** [comment]
This is a very unique use case :D I would try to set pointer-events=none for the react-flow nodes while you drag a dnd-node to a react-flow node. Besides the `nodrag` class we can't help you with this. Feel free to re-open with a codesandbox if the pointer events solution doesn't work.
