### ISSUE TITLE
Edges messed up on re-render.

### ISSUE THREAD

**Issue by jsonporter** [wbkd/react-flow#1766]
I have a case where the incoming graph data can change; usually these changes only affect a few elements and most the elements will be the same.

However when the new data is detected and I go to re-render the graph the new elements are rendered in the correct position however the edges are all messed up.  One thing to note is that in my setup I am using the storeState to get rendered dimensions (eg, el.__rf) so I included the code for positioning as well but I don't think the position logic is the problem because the elements end up in the correct positions (again, its just the edges that are seeming to get stuck).

Reading through similar issues involving the edges I have tried `setElements([])` in order to clear the graph before I set the new data as well as wrapping that in a timeout - neither seem to work. Do you have any ideas? Am I doing something wrong?

Before Refresh:
![Before-refresh](https://user-images.githubusercontent.com/84735036/146038322-fd97652d-fa9b-4923-a435-845dfab36d25.png)

After Refresh:
![After-refresh](https://user-images.githubusercontent.com/84735036/146038338-ab17928f-520c-4d44-85e6-2e7311cbf545.png)

For context, I am using ReactFlowProvider as:

```
<ReactFlowProvider>
    <LayoutReactFlow
        type={type}
        graphData={state.rfGraphJson}
        backgroundStyle={backgroundStyle}>
    </LayoutReactFlow>
 </ReactFlowProvider>
```

And then <LayoutReactFlow> is this:
```
const LayoutReactFlow: React.FC<any> = ({ graphData, backgroundStyle }) => {

    const [instance, setInstance] = useState<null | any>(null);
    const [shouldUpdate, setShouldUpdate] = useState(true);
    const [shouldRefit, setShouldRefit] = useState(false);
    const [graphWithPositions, setGraphWithPositions] = useState(graphData);
    const nodes = useStoreState(store => store.nodes);
    const edges = useStoreState(store => store.edges);
    const setElements = useStoreActions(actions => actions.setElements);

    useEffect(() => {
        if (instance && shouldRefit) {
            instance.fitView({ padding: 0.01 });
            setShouldRefit(false);
        }
    }, [shouldRefit, instance]);

    useEffect(() => {
        if (!shouldUpdate) {
            setElements(graphWithPositions);
        }
    }, [graphWithPositions]);

    useEffect(() => {
        if (!shouldUpdate) {
            setElements(graphData);
            setShouldUpdate(true);
            setShouldRefit(false);
        }
    }, [graphData, setShouldUpdate]);

    useEffect(() => {
        if (
            shouldUpdate &&
            !shouldRefit &&
            nodes.length > 0 &&
            edges.length > 0 &&
            nodes.every(
                node => node.__rf.width != null && node.__rf.height != null
            )
        ) {
            const nodesAndEdges = (nodes as any[]).concat(edges);
            const elementsWithLayout = setReactFlowGraphLayout(
                nodesAndEdges,
                'LR'
            );
            setShouldUpdate(false);
            renderPositionedElements(elementsWithLayout);
        }
    }, [nodes, edges]);

    const renderPositionedElements = data => {
        setGraphWithPositions(data);
        setShouldRefit(true);
    };

    const onLoad = (rf: any) => {
        setInstance(rf);
    };

    const reactFlowStyle: React.CSSProperties = {
        display: 'flex',
        flex: `1 1 100%`,
        flexDirection: 'column'
    };

    return (
        <ReactFlow
            elements={graphWithPositions}
            onLoad={onLoad}
            nodeTypes={CustomNodeTypes}
            style={reactFlowStyle}
            onlyRenderVisibleElements={false}
        >
            <Background
                style={backgroundStyle.background}
                color={backgroundStyle.gridColor}
                gap={backgroundStyle.gridSpacing}
            />
        </ReactFlow>
    );
};
```

And then the positioning logic from `setReactFlowGraphLayout()` is:
```
export const setReactFlowGraphLayout = (
    elements: Elements,
    direction: string
) => {
    const dagreGraph = new dagre.graphlib.Graph();
    dagreGraph.setDefaultEdgeLabel(() => ({}));
    dagreGraph.setGraph({
        rankdir: direction,
        edgesep: 60,
        nodesep: 30,
        ranker: 'longest-path',
        acyclicer: 'greedy'
    });
    elements.forEach(el => {
        if (isNode(el)) {
            const nodeWidth = el.__rf.width;
            const nodeHeight = el.__rf.height;
            dagreGraph.setNode(el.id, { width: nodeWidth, height: nodeHeight });
        } else {
            dagreGraph.setEdge(el.source, el.target);
        }
    });

    dagre.layout(dagreGraph);
    return elements.map(nodeState => {
        if (isNode(nodeState)) {
            const node = dagreGraph.node(nodeState.id);
            return {
                ...nodeState,
                position: {
                    x: node.x - node.width / 2,
                    y: node.y - node.height / 2
                }
            };
        } else {
            return { ...nodeState };
        }
    });
};
```

**Comment by thadk** [comment]
Fixing this solved it for me: https://github.com/wbkd/react-flow/issues/1715#issuecomment-985885004

**Comment by moklick** [comment]
This is a strange bug. As @thadk I would guess that it has something to do with the edge ids. Are you able to create a minimal codesandbox for this example @jsonporter ?

**Comment by jsonporter** [comment]
Okay yeah I was able to make a (very) poorly ported version of our setup but while it doesn't look so great it can repo the error so hopefully its helpful. And thanks for your quick response! 

https://xxyhk.csb.app/

**Comment by thadk** [comment]
Yes, if I modify the edges in your sandbox to have a different edge id's, then it cleans them up as expected before redrawing. Thanks for sharing the intriguing example usage. I also started with the custom node example myself when I ran into this issue.

**Comment by moklick** [comment]
Hey @jsonporter you are nesting ReactFlow components. This is not supported ;) We are working on a next release that supports subflows (you can find the instructions how to test it here: #1555). I can't reproduce this when the flows are not nested.

**Comment by jsonporter** [comment]
Ah yeah, that makes sense haha 😂 .  But reading through that PR it looks like the sub-workflow bit is done so i'll give that a shot. And then any guess on an ETA for that formal release? (can just be a ball-park estimate). Regardless, thanks again for the quick replies!

**Comment by moklick** [comment]
Hopefully by end of January ;)
