### ISSUE TITLE
Feature request: customizable drag and select triggers

### ISSUE THREAD

**Issue by rikkertkoppes** [wbkd/react-flow#1767]
I'd like to prioritize box selection over dragging the canvas, but allow both of them. To do that, I'd like to be able to appoint left mouse button drag to box selection (which is now shift-lmb-drag) and middle mouse button drag to canvas move (which is now lmb-drag).

I can imagine this being a configurable option though

**Comment by xtecox** [comment]
Got here looking for the same feature

**Comment by rsdouglas** [comment]
+1

Middle mouse to pan the canvas would be super useful for us.

**Comment by chrtze** [comment]
Thanks for this feature request. We could add a property for configuring the mouse button to drag the pane quite easily as d3-zoom already supports this. Open questions:

* Should we really expose the option for the middle mouse button? This won't work on trackpads etc.
* How should we call the new prop? Something like `dragPaneMouseButton`? Maybe there is a better idea.
* What options should this prop accept? 0 (left), 1 (center), 2 (right)?

**Comment by rikkertkoppes** [comment]
How about exposing a function via a hook. Any advanced scenario can then be
implemented by the user.

For example, by using use-gesture https://use-gesture.netlify.app/
