### ISSUE TITLE
Connect nodes without keep holding left mouse click

### ISSUE THREAD

**Issue by merin83** [wbkd/react-flow#1768]
Currently while using a mouse, the connection between the nodes is made only by holding the left click of the mouse and dragging the line to the node we want to connect. We additionally want to connect nodes by clicking on the source handle and moving over with the mouse to the destination node and left-click again. Any way we can implement this behavior?

**Comment by datoslabs** [comment]
I have implemented a similar point-n-click connection mechanism using leader-line and `div` overlay on top of `react-flow`.  The transparent `div` overlay on top of `react-flow` essentially intercepts all the mouse events in "node connection" mode and allows users to move the mouse to select the destination node without holding the left mouse button down.  I have not found an easy way to implement similar UX mechanism within the `react-flow` framework.

**Comment by moklick** [comment]
As @datoslabs said it's not easy to implement this. It's on our list as mobile support #1677.

**Comment by merin83** [comment]
@datoslabs Thanks for the heads up. Please do share the link if you have the implementation available somewhere so that I can take a look into it.

@moklick Looking forward to the mobile support. Thanks for this awesome library.
