### ISSUE TITLE
V10 API Example - Infinite loop ?

### ISSUE THREAD

**Issue by doflo-dfa** [wbkd/react-flow#1774]
```js
import ReactFlow, {
  applyNodeChanges,
  applyEdgeChanges
} from 'react-flow-renderer';

const initialNodes = [
  { id: '1', data: { label: 'Node 1' }, position: { x: 250, y: 0 } },
  { id: '2', data: { label: 'Node 2' }, position: { x: 150, y: 100 } }
];

const initialEdges = [
  { id: 'e1-2', source: '1', target: '2' }
];

const BasicFlow = () => {
  const [nodes, setNodes] = useState(initialNodes);
  const [edges, setEdges] = useState(initialEdges);

  const onNodesChange = useCallback((changes) => setNodes((ns) => applyNodeChanges(changes, ns)), []);
  const onEdgesChange = useCallback((changes) => setEdges((es) => applyEdgeChanges(changes, es)), []);

  return (
    <ReactFlow
      nodes={nodes} 
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
    />
  );
};

export default BasicFlow;

```
Using: 
react-flow-renderer@10.0.0-next.28

It appears that once 

```nodeTypes = { { } }```

is added to the API example that, there is a pretty serious loop occuring ? am I missing something.  applyNodeChanges is triggering onNodesChange which is then calling the callback and on and on etc.

**Comment by moklick** [comment]
Good point. I will add it to the docs. We are not memoizing node types anymore. If your node types were dynamic you had to use a hacky API to update them in v9. In v10 it behaves like all other props too. You need to take care that you don't create a new nodeTypes object on every render. If you use useMemo or define the nodeTypes outside of the component this issue shouldn't occur.

**Comment by doflo-dfa** [comment]
I was just playing with this building a sandbox and I discovered the issue with memo ... I think we are good

**Comment by moklick** [comment]
It's not dumb at all ;) Maybe it is a bad idea to change the API but I think it's more consistent and also clear what can be expected.

**Comment by doflo-dfa** [comment]
I totally agree with the decision, albeit a difficult one, to adjust the API. The project benefits from consistency, a straightforward API and configurability. A number of the other alternative projects out there have carried forward a great deal of legacy which has resulted in convoluted messy API's as well as hard to identify bugs.

I am glad I delayed implementing, the work we had done with 9 was easily adapted to 10 and 10 is so far stable enough i can complete our more in depth integration. 

Is there any way / value in contributing examples.  I have an example using mui dropdowns (they use portals for the menu popup which requires keeping the scale in sync) on custom nodes, it's basically an extension of the dynamic render based on scale example already provided.

**Comment by rithvikvibhu** [comment]
Thanks @moklick I did search the issues the day before this issue was created, that's a real coincidence :p Anyway, just wanted to say that memoizing outside the function worked. I see the PR description has also been updated, cheers!
