### ISSUE TITLE
Custom Node styles should be respected when rendered

### ISSUE THREAD

**Issue by cliffordfajardo** [wbkd/react-flow#1783]
### Describe the Bug

I have set a `width` and `height` on my custom node.
When the node is rendered, it renders larger than the dimensions I specified

### Your Example Website or App

https://codesandbox.io/s/agitated-pasteur-zuhrf?file=/src/examples/Example1/CustomNode1/index.tsx

### Steps to Reproduce the Bug or Issue

1. Render a custom node, add dimensions to it. For example:

```tsx
const CustomNode1: React.FC<NodeProps> = ({ data, isConnectable }) => {
  return (
    <>
      <div
        className="my-custom-node"
        style={{ width: 100, height: 100, border: "2px solid red" }}
      >
        <div>CustomNode1</div>
      </div>
    </>
  );
};
```

2. After rendering it is rendered in the svg canvas, inspect the element via browser devtools:

### Expected behavior

1. As a user, when I specify the dimensions of my Custom Element, it should be rendered in the dimensions I specified:

![CleanShot 2021-12-21 at 10 19 28](https://user-images.githubusercontent.com/6743796/146979396-e5a1f2f7-1bdc-4c5f-9234-58ed48ca5ffd.png)

## Proposed Solution(s)
Add the following CSS rule in the core `react-flow` library. This would be scoped to anything inside of `.react-flow`:

```css
/* Use a better box model (opinionated).*/
*,
::before, 
::after {
	box-sizing: border-box;
}
```

A pro of adding this to the core library:
- respects specified dimension of nodes out the box
- it's only scoped to the `.react-flow` namespace
- css reset/normalization is pretty standard & it's baked most modern JS/CSS libraries. For example: 
   - [material UI react has a reset](https://mui.com/components/css-baseline/#global-reset) (73k+stars on github)
   - [AntD React](https://github.com/ant-design/ant-design/search?q=normalize) (76k stars on github)

## Alternative Solution(s) Considered
1. a user can add the CSS snippet about to their own project
  - pros: not part of core
  - cons: adds burden on user, when it might make sense to add this into core for a better experience out of the box
2. OR a user can add `normalize.css` or `modern-normalize.css` to their project
  - modern CSS resets add automatically add `box-sizing: border-box;` to all elements since its a best practice nowadays

### Platform

- OS: MacOS
- Browser: Chrome
- Version: Latest ( 96.0.xx)

**Comment by moklick** [comment]
Thanks for the report! In React Flow v10 #1555 we added ` box-sizing: border-box;` to the `.react-flow__node`. Do you think this is enough or would you add it to all children?

**Comment by cliffordfajardo** [comment]
Hey @moklick - I haven't tried v10 yet. I'll try it out sometime this week.
Are there docs for version 10 yet or is the description of #1551 sufficient enough you feel for migrating?

**Comment by moklick** [comment]
The description of #1555 is all we have for now ;) And it should be sufficient.

**Comment by moklick** [comment]
I will close this, since it's solved in v10. W
