### ISSUE TITLE
ConnectionLine invisible when edges array is empty

### ISSUE THREAD

**Issue by sandervoerman** [wbkd/react-flow#1785]
### Describe the Bug

In version 10.0.0-next.29, the ConnectionLine component is invisible when there aren't yet any edges in the flow. But it does seem to exist, because if you 'blindly' drag the connection to a new node anyway, a new edge will appear. After that, the ConnectionLine will be visible once you start dragging a second connection. So far I have only been able to encounter this problem while the existing edges array is empty. As soon as there is at least one existing edge, the problem no longer occurs.

### Steps to Reproduce the Bug or Issue

This bug can be reproduced from several of the examples in this repository that have been updated to the new API:

- In the [TouchDevice](https://github.com/wbkd/react-flow/tree/v10/example/src/TouchDevice) example, if I try to drag an edge between the nodes, the connection line is invisible, but I can still establish the edge. As soon as that edge exists, I can see a connection line when I start dragging a second edge.
- In the [UpdatableEdge](https://github.com/wbkd/react-flow/tree/v10/example/src/UpdatableEdge) example, if I try to drag an additional edge, I can see the connection line. However, if I first select the existing edge and delete it by hitting the backspace key, the connection line will be invisible if I try to subsequently add an edge.
- In the [FloatingEdges](https://github.com/wbkd/react-flow/tree/v10/example/src/FloatingEdges) example, I can add (non floating) edges by finding the invisible handles on the nodes. The example code actually contains a custom FloatingConnectionLine component, which will be visible when I do this. However, if I edit the example code so that it no longer contains all the initial edges, the FloatingConnectionLine will be invisible on my first attempt to draw an edge between two nodes.

### Expected behavior

As a user, I expect to see a connection line while trying to drag a new edge from a node, but instead I don't see anything, and yet if I nevertheless keep the mouse down, or my finger on the touch screen, a new edge will appear when I release it upon hitting a target handle.

### Platform

- OS: Windows 10, Android 9
- Browser: Chrome 96.0, Firefox 95.0
- Version: the problem occurs both when installing reactflow 10.0.0-next.29 from npm, and when cloning the v10 branch from github and installing the development server locally.

**Comment by moklick** [comment]
Thanks a lot for taking the time and testing the beta version! The bug is fixed in v10.0.0-next.30.
