### ISSUE TITLE
getEdgeCenter Reports Incorrectly for Mixed Bezier Edges

### ISSUE THREAD

**Issue by mattwatts-aimltd-uk** [wbkd/react-flow#1787]
### Describe the Bug

If I have a mixed bezier-style edge, for example one which connects from Position.Right as the source and Position.Top as the target, the getEdgeCenter method returns a bad location. This works fine if I use a smoothstep edge:

Smoothstep Behaviour (expected):
![image](https://user-images.githubusercontent.com/64019154/147116003-4a699288-63ba-4cbc-9092-31853a6d79d3.png)

Bezier behaviour:
![image](https://user-images.githubusercontent.com/64019154/147116137-a809051d-46d8-4697-bda0-5fb9dd39b9da.png)

This returns the correct co-ordinates when using non-mixed edge types, for example always vertical or always horizontal

### Steps to Reproduce the Bug or Issue

1. Create two custom nodes, one with a source/target on top & bottom and one with a source/target on left & right.
2. Create a custom edge with a foreignObject button, copying the implementation [here](https://reactflow.dev/examples/edge-with-button)
3. Observe that when connecting a left/right source with a top/bottom target, the foreignObject position is incorrect due to the output of getEdgeCenter

### Expected behavior

The getEdgeCenter method should return the correct location, regardless of the type of edge being used (bezier or smoothstep)

### Platform

- OS: Windows
- Browser: Edge (Chromium) - 
- Version: Version 96.0.1054.62 (Official build) (64-bit)
- React-Flow-Renderer Version: 9.6.8

**Comment by kuldeepkeshwar** [comment]
@mattwatts-aimltd-uk you might want to check https://github.com/wbkd/react-flow/issues/1796#issuecomment-1016305104

**Comment by mattwatts-aimltd-uk** [comment]
> @mattwatts-aimltd-uk you might want to check [#1796 (comment)](https://github.com/wbkd/react-flow/issues/1796#issuecomment-1016305104)

Interesting, I'll have a look! Thanks

**Comment by moklick** [comment]
This is fixed in v10.
