### ISSUE TITLE
Work not properly under React 18 with StrictMode

### ISSUE THREAD

**Issue by Himself65** [wbkd/react-flow#1798]
### Describe the Bug

I'm using react 18-RC.0, everything doesn't work.

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/react-flow-node-shapes-forked-qo8ch?file=/src/index.js

### Expected behavior

Should work

### Platform

React 18

**Comment by Himself65** [comment]
```tsx
ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

```

**Comment by Himself65** [comment]
The only workaround is to remove `React.StrictMode`

**Comment by Himself65** [comment]
Reference: https://github.com/reactwg/react-18/discussions/19

**Comment by moklick** [comment]
React 18 is not yet supported. However I just checked it with the next version and it is working. The next version is already released as a beta. You can find the installation instructions and changed API in this PR: #1555. We will not do any changes for v9 in order to support React 18.

**Comment by Himself65** [comment]
Thanks for the feedback. I've migrated my project to v10, and it works perfectly.
