### ISSUE TITLE
save restore crashing with DomException 

### ISSUE THREAD

**Issue by gryslik** [wbkd/react-flow#1817]
### Describe the Bug

Hi,

I'm trying to get the save/restore functionality working. When I try to save, I get the following error:

```
Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': Symbol(react.element) could not be cloned.
```

Running a console.log(JSON.stringify(flow)) I get:
```
{"elements":[{"id":"1","type":"input","data":{"label":"Input Node"},"position":{"x":250,"y":25}},{"id":"2","data":{"label":{"type":"div","key":null,"ref":null,"props":{"children":"Default Node"},"_owner":null,"_store":{}}},"position":{"x":100,"y":125},"type":"default"},{"id":"3","type":"output","data":{"label":"Output Node"},"position":{"x":250,"y":250}},{"id":"e1-2","source":"1","target":"2","animated":false,"sourceHandle":null,"targetHandle":null,"type":"default"},{"id":"e2-3","source":"2","target":"3","animated":false,"label":"Future Edge Information","sourceHandle":null,"targetHandle":null,"type":"default"}],"position":[0,0],"zoom":1}
```

### Steps to Reproduce the Bug or Issue

Clicking the save button. 

### Expected behavior

I expected it to save

### Platform

- OS: Linux
- Browser: Chrome

**Comment by gryslik** [comment]
Realized the other issue is closed. I'm cross-linking it here : https://github.com/wbkd/react-flow/issues/1717

My issue is identical.

**Comment by gryslik** [comment]
More experimentation:

I can confirm that it breaks when trying to save a "React Component", namely, this element:

```
  {
    id: '2',
    // you can also pass a React component as a label
    data: { label: <div>Default Node</div> },
    position: { x: 100, y: 125 },
  },
```

If I go in an take out the <div> it works fine. Is there any way to be able to save react elements directly?

**Comment by moklick** [comment]
Hey @gryslik 

this is not an issue with React Flow. You can't serialize/ Json.stringify a React component.
Using a component as a label is something you can do but I would recommend to use custom node implementations and only pass the data you need. If you want to store the flow as a JSON you can't use React components within your node data.
