### ISSUE TITLE
react-flow__viewport is truncating edge elements?

### ISSUE THREAD

**Issue by cliffordfajardo** [wbkd/react-flow#1820]
### Describe the Bug
After `<ReactFlow>` loads and I pan over / drag the view the `.react-flow__viewport` appears to be truncating only the edge elements

### Steps to Reproduce the Bug or Issue
1. Let `<ReactFlow>` load
2. Drag the view & observe (video below) that the edges are being truncated (not not the boxes or any other part of the view)

https://user-images.githubusercontent.com/6743796/148275294-d06a052d-9399-438f-81b2-fcc32379e5f8.mp4

Strangely, when I reproduce the code in a codesandbox, the behavior observed in the video is not happening, which is good & weird
- https://codesandbox.io/s/strange-tree-2c8i4?file=/src/examples/Example1/index.tsx:866-875

**Am I forgetting to run some update handler or something similar ❓**

### Expected behavior
`.react-flow__viewport` class shouldn't truncate the remaining view

NOTE: i realize that it's probably the code in my original environment since it works in the codesanbox, but I wanted to share this in case anyone else stumbled upon this. I will keep looking into this.

<img width="1838" alt="001" src="https://user-images.githubusercontent.com/6743796/148282416-d5841fc6-f48d-48ec-88bd-76fa780606f6.png">

### Platform
- OS: MacOS
- Browser: Chrome, Safari, Firefox
- Version: latest

**Comment by cliffordfajardo** [comment]
Hi @moklick 
Do you have any tips or suggestions 🙏  Maybe I need to call some sort of method in the library?

_I will keep digging further, I'm 99% sure it's my enviornment setup since the codesandbox works_

**Comment by cliffordfajardo** [comment]
UPDATE
The problem was the component library I have loaded in my app `antd` has an svg rule that was applying a style to the svg
- https://github.com/ant-design/ant-design/blob/b6bd4c18b4f00efa7d8e133618ee008fcf5a2911/components/style/core/global.less#L284

```css
svg:not(:root) {
  overflow: hidden; // Hide the overflow in IE
}
```

**Comment by moklick** [comment]
Argh .. good finding! I didn't know that antd does this stuff. Thanks for the update.
