### ISSUE TITLE
Cross platform multiSelectionKeyCode

### ISSUE THREAD

**Issue by RomanistHere** [wbkd/react-flow#1830]
### Describe the Bug

multiSelectionKeyCode doesn't work cross platform (on Mac)
I thought that this code: `multiSelectionKeyCode: isWindows ? 17 : "Meta"` - should work,
Ideally, I'd suggest that `multiSelectionKeyCode: true` - should do this by default (use Ctrl in Windows and Cmd in Mac), but it doesn't actually work for Mac at all. 17 works fine for Windows.

### Steps to Reproduce the Bug or Issue

- Use multiSelectionKeyCode option with "Meta" value 
- Use Cmd to multiselect nodes
- It doesn't work

### Expected behavior

I expected multiselect to work on mac with Cmd hold when it set up to "Meta"

### Platform

macOS, Windows
Chromium

**Comment by moklick** [comment]
This bug is fixed in the next major release (with this it will be possible to specify multiple key codes). You can find the installation instructions and api changes in this PR: #1555
