### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Graph')

### ISSUE THREAD

**Issue by sleepingsaint** [wbkd/react-flow#1840]
### Describe the Bug

I built my react application with typescript using react flow and dagre. I used vite as the build tool. In development everything is working fine. But when I build the project it is giving the error "Uncaught TypeError: Cannot read properties of undefined (reading 'Graph')".

Below is my package.json dependencies
```json
{
 "dependencies": {
    "dagre": "^0.8.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-flow-renderer": "^9.7.3"
  },
  "devDependencies": {
    "@types/d3": "^7.1.0",
    "@types/dagre": "^0.7.47",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@vitejs/plugin-react": "^1.0.7",
    "typescript": "^4.4.4",
    "vite": "^2.7.2",
    "vite-tsconfig-paths": "^3.3.17"
  }
}
```

### Your Example Website or App

https://git-visualizer.pages.dev/

### Steps to Reproduce the Bug or Issue

1. Clone the repo https://github.com/sleepingsaint/git-visualizer.git
2. Install dependencies 
3. run build and preview scripts
```bash
yarn build && yarn preview
```
4. Open localhost:5000 to preview the build
5. Open the console log to see the error

### Expected behavior

![Screenshot from 2022-01-14 17-25-32](https://user-images.githubusercontent.com/35530053/149511718-8b079f7e-47a9-48d4-99ab-bff4b91d194e.png)

It should a node with controls and minimap as per the above picture.

### Screenshots or Videos

![Screenshot from 2022-01-14 17-27-57](https://user-images.githubusercontent.com/35530053/149512016-80475a17-08d3-4fe3-8a5a-c2ad7697d117.png)

The error is being shown in the console log

### Platform

- OS: [Linux]
- Browser: [Chrome, Brave, Firefox]
- Version: [Chromium: 97.0.4692.71]

**Comment by moklick** [comment]
I didn't looked into this too close but but when I comment out the dagre stuff everything is working fine. I would say that this is an issue with dagre. Can you confirm that it works when you are not using dagre @sleepingsaint ?

**Comment by sleepingsaint** [comment]
Thanks for the suggestion. It's working fine without dagre, but there is another error I forgot to mention, i.e without @types/d3 building the project is giving an error.

```
$ tsc && vite build
node_modules/react-flow-renderer/dist/types/index.d.ts:2:56 - error TS2307: Cannot find module 'd3' or its corresponding type declarations.

2 import { Selection as D3Selection, ZoomBehavior } from 'd3';

Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After adding @types/d3 as a dev dependency it worked fine.

Can you suggest any other alternative to dagre to build the layout?

**Comment by moklick** [comment]
That's strange. `@types/d3` is part of the devDependecies https://github.com/wbkd/react-flow/blob/main/package.json#L53 

For layouting we are using [elkjs](https://github.com/kieler/elkjs) mostly and recently also [cytoscape](https://js.cytoscape.org/).

**Comment by sleepingsaint** [comment]
Well the problem still exists. I tested again with the same setup ( vite, react, typescript, react-flow-renderer ) and still facing the problem. 

I facing some issues with elkjs and it seems they are not solved yet. Could you please share the link to layout examples with cytoscape? 

Thanks :)

**Comment by moklick** [comment]
@sleepingsaint I thought it's working without dagre? Unfortunately I don't have ReactFlow + Cytoscape examples that I could show you.

**Comment by rweilg** [comment]
@sleepingsaint and anyone coming from google with the same setup (vite, react, typescript, react-flow-renderer) and error, the issue for us related to hoe Vite handle the namespace export of graphlib in dagre, adding the following to the Vite config solved it for us:

```
  build: {
    commonjsOptions: {
      ignoreTryCatch: false,
    },
  },
```
We lost quite a bit on this an even considered reimplementing the feature in something other than dagre so it would be great if a line was added to the examples using dagre saying this issue could show up in projects using Vite.

**Comment by rweilg** [comment]
@sleepingsaint and anyone coming from google with the same setup (vite, react, typescript, react-flow-renderer) and error, the issue for us related to how Vite handles the namespace export of graphlib in dagre, adding the following to the Vite config solved it for us:

```
  build: {
    commonjsOptions: {
      ignoreTryCatch: false,
    },
  },
```
We lost quite a bit on this an even considered reimplementing the feature in something other than dagre so it would be great if a line was added to the examples using dagre saying this issue could show up in projects using Vite.
