### ISSUE TITLE
Cannot make connection two input nodes with each other.

### ISSUE THREAD

**Issue by Ishtiaq-Ahmad** [wbkd/react-flow#1846]
### Describe the Bug

Hi,
I faced a weird problem, when I connected input node to input node. 
i have provided a video below. you can see that i can connect input node  to output node. but i cannot connect input node to input node. Is it possible that i connect 2 output nodes or two input nodes with each other?
it would be great if edges could have property which could connect source node to source node target node to target node..

https://user-images.githubusercontent.com/67997286/150487840-f3a08afb-9ccb-4e28-ab63-5a151b82fe35.mp4

Please let me know this. 
Thanks

### Steps to Reproduce the Bug or Issue

Please see Provided video

### Expected behavior

i just want to connect two input nodes or two output nodes with each other.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey @Ishtiaq-Ahmad 

this is the weird default behaviour of React Flow ;) You can only connect source => target. If you also want to connect source => source and target => target, you need to set `connectionMode="loose"` on the `<ReactFlow />` component.

**Comment by Ishtiaq-Ahmad** [comment]
@moklick 
Thank you . this has solved my problem.
