### ISSUE TITLE
Large bundle size, currently 165KB

### ISSUE THREAD

**Issue by a3957273** [wbkd/react-flow#1856]
### Describe the Bug

Bundling using Webpack in a Next.JS application currently generates a bundle size of 165KB.  This is larger than the rest of our application combined.

### Steps to Reproduce the Bug or Issue

Build any ReactFlow application and inspect the bundle size.

### Expected behavior

The bundle size is expected to be small.

### Platform

N/A

**Comment by moklick** [comment]
Hey @a3957273 

we have react-draggable and d3-zoom as dependencies. The large bundle size is on our list and we would like to drop the d3-zoom dependency but haven't found a good alternative or the time to try to solve this problem internally (and I am also still not sure if this makes sense). However this is not a bug.. Minified and gzipped it should be around ~47 kb which is OK.

**Comment by a3957273** [comment]
The 165KB size was taken pre-compression.  The 'over the wire' size isn't too much of an issue, but on low-end devices the load time of the page can be hindered by the amount of JavaScript that needs to be parsed.

It's fair that this isn't a bug, apologies for classifying it as such.
