### ISSUE TITLE
"nodrag" class for images still allows them to be dragged

### ISSUE THREAD

**Issue by kahboom** [wbkd/react-flow#1881]
### Describe the Bug

Hello, apologies if i'm not using this correctly, but I've tried adding the `"nodrag"` class to an image, yet when I drag the node, if the cursor happens to be on the image instead of the other parts of the node, it tries to drag the image instead of the node. Is this the expected behavior? I'm using a custom node, if that matters.

### Your Example Website or App

Borrowing the CodeSandbox example from [this](https://github.com/wbkd/react-flow/issues/802#issuecomment-752490771) issue: https://codesandbox.io/s/exciting-mendel-0sb2s?file=/src/DrgDrp.js

Please see screen capture GIF below.

### Steps to Reproduce the Bug or Issue

1. Add an image to a node.
2. Add `nodrag` class to the image.
3. Behavior for dragging from the image is different than from dragging the enclosing node.

### Expected behavior

I would like a way to disable any dragging of the image, only the node it's enclosed in.

### Screenshots or Videos

![2022-02-03 12 47 56 pm](https://user-images.githubusercontent.com/3844502/152346868-51f60ae2-7d38-40d7-8268-702feaf11ecc.gif)

### Platform

- OS: macOS
- Browser: Chrome

**Comment by moklick** [comment]
Hey @kahboom 

I think this is the default browser behaviour. Did you try to add `pointer-events: none` to the image?

**Comment by kahboom** [comment]
Thanks @moklick , that fixed it for me. :)
