### ISSUE TITLE
Smart edge applies for all edges

### ISSUE THREAD

**Issue by Ishtiaq-Ahmad** [wbkd/react-flow#1885]
### Describe the Bug

This is pretty awesome feature that you have developed. lots of appreciation for this. i have been using this nice feature with React flow. during the development I got a weird problem. SmartEdgeProvider wrap React flow, whenever i change the SmartEdgeProvider options then smart edge applies for all edges. and this is not fulfilling my requirement. could you tell me please is it possible to control smart edge individually or if this feature is not available could you add this feature please? you can see a video below where i have highlighted smart edges with green color.

### Steps to Reproduce the Bug or Issue

selected an edge
apply smart routing
manipulate that single smart edge
other smart edge should not be effected.

### Expected behavior

i want to control smart edge individually for every edge. if i manipulate a selected edge with smart routing options then other smart edges should not be effected.

### Screenshots or Videos

https://user-images.githubusercontent.com/67997286/152482454-ad29f636-fed8-4277-9724-be9e23801871.mp4

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey @Ishtiaq-Ahmad 

please open an issue in the https://github.com/tisoap/react-flow-smart-edge repo.
