### ISSUE TITLE
Translate X and Y results in NaN on fitView when all nodes are hidden

### ISSUE THREAD

**Issue by felipedecome-togdesign** [wbkd/react-flow#1889]
### Describe the Bug

When all nodes have `isHidden: true`, translate values results in NaN throwing an Error on fitView.

### Steps to Reproduce the Bug or Issue

1. Starts a project with reactflow
2. Provide an array of nodes with ìsHidden: true`.
3. Try to fitView

### Expected behavior

Translate values should be 0 when result is NaN.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/87035812/152571301-38434656-93bf-481e-9f5e-08ac07557f15.png)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 9.7.1

**Comment by moklick** [comment]
this is fixed in v10.
