### ISSUE TITLE
Selecting edges or nodes don't deselect the other type.

### ISSUE THREAD

**Issue by matt-way** [wbkd/react-flow#1899]
### Describe the Bug

Due to the separation of nodes and edges, when selecting either one, the other remains selected. For example, if you select a node, and then select an edge, both remain selected, when only the edge should be selected.

This occurs because the selection state of nodes and edges act independently. To handle this currently I have done the following (example for node changes only):

    const onNodesChange = useCallback(changes => {
      const selected = changes.find(c => c.type === 'select' && c.selected)
      if (selected) {
        // deselect all edges
        setEdges(es => es.map(e => ({ ...e, selected: false })))
      }
      setNodes(ns => applyNodeChanges(changes, ns))
    }, [])

This works for single selection only, and will likely fail for multi select. 

This can be fixed by calling `addSelectedEdges([])`, whenever `addSelectedNodes` is called for single selection (and vice versa).

### Steps to Reproduce the Bug or Issue

Click on a node.
Click on an edge.
The node is not deselected.

### Expected behavior

When performing single selection of elements, full deselection should occur, not just of the same type.

### Platform

- OS: n/a
- Browser: Chrome
- Version: 10

**Comment by moklick** [comment]
Hey @matt-way,

thanks for reporting an issue for v10 :) This is really helpful. We will look into this.

**Comment by moklick** [comment]
good catch! Thanks @matt-way
