### ISSUE TITLE
Handle not connectable when it has a children

### ISSUE THREAD

**Issue by Nauss** [wbkd/react-flow#1901]
### Describe the Bug

I was trying to connect two simple custom nodes but no connection was made and the `onConnect` handlers were not fired.

My code was pretty close to the examples with this exception:
```javascript
<Handle {...}>
    <div>{name}</div>
</Handle>
```

Removing some of my modifications step by step, I found that the `div` child of the `Handle` component was causing the bug.

I might I have missed something in the way `Handle` should be used ?

### Your Example Website or App

https://codesandbox.io/s/nervous-voice-3e3bp?file=/src/ColorSelectorNode.js

### Steps to Reproduce the Bug or Issue

In the code sandbox, try to connect "An input node" to the custom node input.

Removing the Handle child makes it work properly.

### Expected behavior

I'm not sure what to expect, either:
- Adding children to the `Handle` should not break it. Or,
- It should probably be mentioned in the documentation that `Handle` **must** not have children

**Comment by moklick** [comment]
The problem is, that the children is above the handle. The easiest way to fix this is to set `pointer-events: none` for the children.
