### ISSUE TITLE
Selection mode won't release when interrupted by right click or tab switching

### ISSUE THREAD

**Issue by Sec-ant** [wbkd/react-flow#1912]
### Describe the Bug

In react-flow, by default, if you enable `selectNodesOnDrag` and use `Shift` as the `selectionKeyCode`, you'll enter selection mode when you press `Shift`. If you then right click to open a context menu while `Shift` key is being pressed, and later release key `Shift`, the `Shift` keyup event won't be fired. And because of this, react-flow will still think you're in selection mode, so you can only drag selection regions but nothing else. In order to break the selection mode, you'll have to press and release `Shift` again.

Similar behavior is also found when you switch tabs (use `Ctrl`+`Tab` as a short cut, but you can only `Ctrl`+`Shift`+`Tab` now because `Shift` is being pressed) during the `Shift` key being pressed. If you release `Shift` and switch back later, you're still in selection mode. And wierdly, pressing and releasing `Shift` again won't save you now. Other similar focus losing events in browser level triggered by mouse or keyboard events (eg, use keyboard short cut to open a new page) are all likely to cause this problem.

I have no idea how to fix this, but I do notice that when you open the context menu, the selection region rectangular is converged to the selected nodes covered by the selection. So even `Shift` is not detected being released by the event handler, internally react-flow should still know when the selection is completed or interrupted?

### Your Example Website or App

https://codesandbox.io/s/pedantic-volhard-6olmne?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/s/pedantic-volhard-6olmne?file=/src/App.js
2. Wait for loading and click the preview browser to make sure it is focused.
3. Press `Shift` and use left mouse key to drag a selection region.
4. Don't release `Shift`, right click in place to open the context menu.
5. Release `Shift` now, the keyup event won't be fired.
6. Try to click the nodes in react-flow like normal, you'll find them being "frozen", that's because you're still in selection mode.
7. Press and release `Shift` again to "unfreeze" and break the selection mode.

If you replace 4. with opertations like tab switching or creating new tabs/windows, 7. won't help you "unfreeze" the nodes.

### Expected behavior

Quit selection mode whenever the drag-selection procedure is interrupted.

### Screenshots or Videos

![demo](https://user-images.githubusercontent.com/10386119/154911523-54195c83-eb1f-4b4a-a4b3-7117cf3e48c8.gif)

### Platform

- OS: [Windows 10 21H2, 19044.1526]
- Browser: [Microsoft Edge 98.0.1108.56]
- Version: [10.0.0-next.40]

**Comment by Sec-ant** [comment]
Keep `Shift` pressed and switch to another tab and release `Shift` and then switch back will also reproduce this problem. And it seems to be prone to false triggers.

**Comment by moklick** [comment]
Hey @Sec-ant

thanks for the report!

The tab switching is fixable. We need to reset everything key related in a visibilitychange event. I will add that!
The right click is a bit problematic. It's the same issue that is explained in #824. Right now I don't see a way to fix this. All key handling libraries have this issue. Check this for example: https://wangchujiang.com/hotkeys/

**Comment by Sec-ant** [comment]
Thanks @moklick for the explanation, I'll close this.

**Comment by moklick** [comment]
Released in v10.0.6
