### ISSUE TITLE
Support for text on Edges

### ISSUE THREAD

**Issue by dayvough** [wbkd/react-flow#192]
Hi, love the repo and was just looking for something like this to help my team explain lots of scenarios.

However I'd like to ask if there's support for Text on the Edges coming soon so that I can explain decision trees without having to add an additional two more nodes for "YES" and "NO"

Cheers

**Comment by moklick** [comment]
Good idea! We will look into it :)

**Comment by moklick** [comment]
We now have support for edge labels! You can checkout the examples 

demo: https://react-flow.netlify.app/edges
demo source: https://github.com/wbkd/react-flow/blob/master/example/src/Edges/index.js
