### ISSUE TITLE
When selecting a text and drag into the pane it creates a new node.

### ISSUE THREAD

**Issue by mmezgin** [wbkd/react-flow#1921]
### Describe the Bug

![React Flow Bug](https://user-images.githubusercontent.com/49004855/155133027-38f5b1c3-8748-43a1-ad7a-978d69ee0cf2.gif)

### Steps to Reproduce the Bug or Issue

1. Implement Drag and Drop
2. Select a text and drag into pane

### Expected behavior

It must not create a new node like this.

### Platform

-Web

**Comment by moklick** [comment]
This is because you don't handle this invalid case. You need to check of the dropped element is valid. We will update the examples on our site.
