### ISSUE TITLE
The library doesn't support tree shaking

### ISSUE THREAD

**Issue by shemayas** [wbkd/react-flow#1927]
### Describe the Bug

When including the library, even just one function, the whole size of the library is added to the bundle

### Steps to Reproduce the Bug or Issue

1. install the latest `create-react-app`
2. run a build and write down the size of the bundle (in my case 132k)
3. install the latest version of react-flow-renderer `npm i react-flow-renderer@next`
4. import one function to the `app.js` file, for example:
```js
import {addEdge} from "react-flow-renderer";
function App() {
  return (
    <div className="App">

    </div>
  );
}

export default App;
```
5. build again and compare the size of the bundle (in my case it grow to 308k)

### Expected behavior

The bundle size should grow only with the size of the imported peace of code

### Platform

- OS: Linux - Ubuntu
- Browser: Not relevant
- Version: Not relevant

**Comment by moklick** [comment]
Hey @shemayas 

this should work better with v10. Unfortunately we are using a default export for the `ReactFlow` component. That's why most of the code is always bundled. But in v10 the bundle gets smaller when you don't import `Controls`, `Background` or one of the new hooks for example
.

**Comment by shemayas** [comment]
Thanks @moklick for your response.

But I used react flow v10 in the test I provided
