### ISSUE TITLE
Nodes are not draggable when integrated with `dagre` in v10

### ISSUE THREAD

**Issue by kafkahw** [wbkd/react-flow#1930]
### Describe the Bug

Discussed in this [thread](https://github.com/wbkd/react-flow/pull/1555#issuecomment-1049026315) and creating an issue to track it. 

I created an example with v9 that's integrated with dagre for custom layout. It works pretty well (see the example [here](https://stackblitz.com/edit/react-whyxhu?file=src%2FApp.js)). However, after upgrading to v10, I created a similar example [here](https://stackblitz.com/edit/react-ts-qfwtky?file=App.tsx) but found that the dragging feature is not working. The only difference btw these two examples is that I split elements into nodes and edges due to the new API changes. The rest code should be pretty much the same. It might be something related to the new API `onNodesChange` and `onEdgesChange`, but I can't figure out the exact reason. Do you have ideas on this?

I understand that we can work around the issue if we call the layout calculation once as suggested [here](https://github.com/wbkd/react-flow/pull/1555#issuecomment-1048621732). However, in our app we will add nodes dynamically. Based on @moklick's suggestion https://github.com/wbkd/react-flow/issues/1113#issuecomment-829461998, it seems that we should re-calculate the layout whenever a new node is added. That's why I implemented this way in v9 and it works like a charm. I'm wondering if someone can shed a light on how to make it work in v10 as well.

### Your Example Website or App

https://stackblitz.com/edit/react-ts-qfwtky?file=App.tsx

### Steps to Reproduce the Bug or Issue

1. Go to this Stackblitz [example](https://stackblitz.com/edit/react-ts-qfwtky?file=App.tsx). 
2. Try to drag any node in the graph.
3. You'll find out that nodes are not draggable.

### Expected behavior

As a user, I expected all nodes in the graph are draggable by default.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 98.0.4758

**Comment by OrhanTozan** [comment]
If you want the same behaviour as v9, replace nodes={} and edges={} with defaultNodes and defaultEdges.

**Comment by moklick** [comment]
@kafkahw  as I said in the comment, this is not an issue with the library but with your implementation. When you add nodes dynamically, and you want to re-layout the nodes, you need to do the layouting after you added the new node. 

@OrhanTozan this is not the case. When you are using `defaultNodes`/ `defaultEdges` you can only manipulate the nodes and edges by using the `useReactFlow` hook or by altering them directly by using the store.

**Comment by kafkahw** [comment]
hi @moklick, I think my implementation is pretty much the same in v9 and v10. However, it just stops working in v10. That's why I raised the issue here.
If you take a closer look at the examples I provided above, the implementation does re-layout the nodes, as you suggested, whenever a new node is added (i.e. adding a new node -> state `nodes` got updated -> re-render will call `getLayoutedNodes` again on the new `nodes`).

I'd suggest keeping this issue open until we have a solid example to show people how to dynamically change nodes and with `dagre`. That way more people can easily find this issue when they have similar questions/problems in v10 and may bring in more ideas and solutions to this. 

NOTE: At this moment people are even confused with how to achieve this in v9 (see this [open issue](https://github.com/wbkd/react-flow/issues/1113)). My example in v9 can be an answer to that issue. However, I still don't have a clear idea about how to do it in v10.

**Comment by moklick** [comment]
@kafkahw did you update the example? I can't see an issue anymore. The nodes are draggable now.

**Comment by kafkahw** [comment]
@moklick yes, I eventually figured out a way to call `getLayoutedNodes` more explicitly so nodes will be draggable. however, it's a different implementation compared to that in v9.
Thanks for looking into this! I know you're busy with v10 release at this moment, but would like to bring this issue into your attention because it may be breaking some existing apps using v9. IMHO, the old implementation with v9 is more clear and easier to maintain as I only have to update nodes and then `getLayoutedNodes` will be called automatically on nodes which will be assigned to `ReactFlow`.
Please take this as a very low priority task/issue for now if it's not a blocker to v10. I'm super excitedly looking forward to the release of v10!

**Comment by sushantdhiman** [comment]
I am facing exactly same issue (I am using elkjs for layouting), I opted for `defaultNodes/ defaultEdges` which seems to be working.
