### ISSUE TITLE
Drag selection is working even without selectionKeyCode pressed

### ISSUE THREAD

**Issue by shahbaz-shoukat** [wbkd/react-flow#1931]
### Describe the Bug

Press the `selectionKeyCode` key and click-drag in react-flow pane, you will be able to create a drag selection. 
But when you click outside the react-flow pane with the key pressed the selection overlay is not getting removed and it will create the selection area even without the selection key.

**With v9:** (Working fine)
https://codesandbox.io/s/drag-selection-react-flow-v9-7-4-220eoo

**With v10:** (Not working)
https://codesandbox.io/s/drag-selection-react-flow-v10-8hmfoh

### Your Example Website or App

https://codesandbox.io/s/drag-selection-react-flow-v10-8hmfoh

### Steps to Reproduce the Bug or Issue

1. Press the `selectionKeyCode` key.
2. Keep it pressed and click outside of react-flow pane.
3. Now release the key and click-drag on the react-flow pane. It creates a selection area even with  `selectionKeyCode` key released.

### Expected behavior

Drag selection should not work without the selection key pressed.

### Screenshots or Videos

<img width="1626" alt="Screenshot 2022-02-25 at 5 54 29 PM" src="https://user-images.githubusercontent.com/58297676/155727473-5dfa7c1a-16c4-4548-a0e5-561d3dbc9cfc.png">

### Platform

- OS: [macOS(Monterey)]
- Browser: [Chrome(98.0.4758.109)]

**Comment by moklick** [comment]
Thanks @shahbaz-shoukat ! This is fixed in v10.0.6
