### ISSUE TITLE
Multiple Text Line in Node

### ISSUE THREAD

**Issue by tonytbn** [wbkd/react-flow#1955]
### Describe the Bug

Look like we can not pass a json multiple line into the Node data: label.

For example :  "data": { "label": "NODE 1 \n NODE 2"},

it keeps display "NODE 1 NODE 2" the text node. 

### Steps to Reproduce the Bug or Issue

pass json arrary to node

[
    {
        "id": "supplier",
        "type": "input",
        "data": { "label": "NODE 1 \n NODE 2"},
        "position": { "x": 0, "y": 300 },
        "style": { "color": "#273746", "backgroundColor": "#ABEBC6", "fontSize": "12px", "fontWeight": "bold" },
        "draggable": false,
        "sourcePosition": "right",
        "targetPosition": "left"
    }
]

### Expected behavior

Expect NODE 1  and NODE 2 have to display in 2 line , not in 1 line

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/97651145/157476572-79c3d1cb-22e6-40a9-a2d7-77e1f57c9bd3.png)

### Platform

OS : Window 11
Chrome: Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by moklick** [comment]
Hey @tonytbn 

the built-in nodes are very simple examples. When you build an application with React Flow, we recommend to use custom nodes only. However if you want to pass multiline text to the default node, you could pass a React component as a label:

```js
const nodes = [{
  "id": "supplier",
  "type": "input",
  "data": { "label": (
    <>
      NODE 1<br />
      NODE 2
    </>)
   },
  "position": { "x": 0, "y": 300 },
  "style": { "color": "#273746", "backgroundColor": "#ABEBC6", "fontSize": "12px", "fontWeight": "bold" },
  "draggable": false,
  "sourcePosition": "right",
  "targetPosition": "left"
}];
```

**Comment by tonytbn** [comment]
Thank moklick, but the thing is i got the input as a string 

{ "label": "(
    <>
      NODE 1<br />
      NODE 2
    </>)"
   },

it has to be double quote before open and close parenthesis. after that i use JSON.parse to convert string to object array. and the result like this 

![image](https://user-images.githubusercontent.com/97651145/157576792-3384d22b-5435-4248-afe0-fbe5a8f61046.png)

if remove "" , i can not use JSON.parse.
