### ISSUE TITLE
Unable to access react-flow hooks inside custom node component

### ISSUE THREAD

**Issue by jagadeeshpatta** [wbkd/react-flow#1957]
### Describe the Bug

I am using micro frontend design pattern in my project. i have created my ReactFlow instance in one package. And my custom node(nodetype) in another package. In this case initialization of hooks getting below error.

VM3799 react_devtools_backend.js:4061 Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useReduxContext (ReactFlow.js:2150:1)
    at useStore (ReactFlow.js:2172:1)
    at useDispatch (ReactFlow.js:2210:1)
    at useStoreActions (ReactFlow.js:2614:1)
    at useUpdateNodeInternals (ReactFlow.js:11804:1)
    at CustomComponent (CustomComponent.jsx:90:53)
    at we (react-dom.production.min.js:84:293)
    at zj (react-dom.production.min.js:226:496)
    at Th (react-dom.production.min.js:152:223)
    at tj (react-dom.production.min.js:152:152)

At Line No: 90 I have below code 

const updateNodeInternals = useUpdateNodeInternals()

### Steps to Reproduce the Bug or Issue

1. Use ReactFlow in one component. Which is belongs to package-1
2. Create custom node. which was used as node type in ReactFlow instance in package-2
3. In custom node access the hooks (const updateNodeInternals = useUpdateNodeInternals())

### Expected behavior

ReactFlow store / hooks / resources should be accessible in its custom nodes also.

### Platform

- OS: macOS
- Browser: Chrome
- Version: Recent

**Comment by RegiByte** [comment]
have you tried wrapping your child component with ReactFlowProvider as described in https://reactflow.dev/docs/api/components/provider/  ?

**Comment by jagadeeshpatta** [comment]
Yes, I have wrapped **ReactFlowProvider** for my custom node. But, in my custom node **store.getState()** always returning empty array.

**Comment by jagadeeshpatta** [comment]
Can i wrap my application root component with  **ReactFlowProvider** ?

**Comment by Holybasil** [comment]
same problem
by the way, v9 is ok. I recently upgraded from V9 to V10.
index.js
```js
import SpecialNode from "./SpecialNode"

const nodeTypes = {
    special: DefaultNode
}

<ReactFlowProvider>
   <ReactFlow nodeTypes={nodeTypes} />
</ReactFlowProvider>
```

SpecialNode.js
```js
const selectedNodes = useStore(flowState => flowState.selectedNodes); // undefined
```

**Comment by moklick** [comment]
@Holybasil there is no `selectedNodes` anymore. Try to get `transform` for example. Does that work?

```js 
const transform = useStore(flowState => flowState.transform); 
```

**Comment by jagadeeshpatta** [comment]
While i am using lerna as micro-front end tool. Then if i am trying to create ReactFlow as common component in maintaining in libarary-package. And my custom nodes available in other package. By that time i can't access react-flow state inside my custom nodes.

**Comment by moklick** [comment]
Is this still an issue @jagadeeshpatta ? Are you using the latest version v10.1.0 ?

**Comment by moklick** [comment]
Please re-open if the issue still occurs.
