### ISSUE TITLE
Contribute with lock board plugin

### ISSUE THREAD

**Issue by raichuk** [wbkd/react-flow#197]
Hi WebKid team,
first of all thanks for this incredible library, I was looking for something like this to use on a shared board.

I've checked the code of plugins and the `useStoreState` and `useStoreActions` hooks in order to create a button that locks the board, using the `setInteractivity` function and is working (at the time as a button on controls plugin but I think that might be better as a separated plugin).

If you think that this could be a useful addition, I want to know which are the steps to follow to contribute.

Thanks again for all this tremendous work.

**Comment by moklick** [comment]
Hey @raichuk,

thanks for your kind words :)

I really like the idea of an interactive on/off button. You could integrate it in the controls plugin and add some options so that one could enable zoom/focus graph/interactive.

What do you think about that?

**Comment by raichuk** [comment]
Hi @moklick, thanks for this fast response.

You are right, the Controls plugin could integrate this change and the user would be able to enable it or not for later use.

I have some little things to check, but overall is done, so I can follow the process that you have for proposing a PR 

Thanks.

**Comment by moklick** [comment]
I think we need a contribution guide. Can you make a new branch from the develop branch? That would be perfect.

**Comment by raichuk** [comment]
Of course, I will commit there and when everything is done I will update you, so you don't need to start with the guide immediatly.

Thanks @moklick

**Comment by raichuk** [comment]
Hi @moklick.

I have everything ready, at least to check it when you have time.
I've branched from `development` branch and commited trying to follow the pattern that you use, but, of course, when trying to push my branch it returns me `403`.

Do you want me to fork and create PR from my fork?

Thanks!

**Comment by moklick** [comment]
Hey @raichuk 

you should be able to create a PR from your fork via the web UI https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by raichuk** [comment]
@moklick it's ready now, thanks for this opportunity!.
