### ISSUE TITLE
Connection line from handles on the left or on the top have wrong curve

### ISSUE THREAD

**Issue by michal-perlakowski** [wbkd/react-flow#1970]
### Describe the Bug

When you drag from a handle on the left side on the node, the curve looks as if the handle was on the right side.

### Steps to Reproduce the Bug or Issue

- Go to the [Horizontal demo](https://reactflow.dev/docs/examples/horizontal/).
- Start dragging from the left handle of Node 7.
- The curve looks as if the handle was on the right side.

### Expected behavior

The curve should go to the right side of the cursor.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/7311642/158415435-2654ffe8-0e78-42a6-9beb-f98cee6c5414.png)

**Comment by Holybasil** [comment]
Here's a problem that looks similar.
![CleanShot 2022-03-17 at 15 47 41](https://user-images.githubusercontent.com/21138718/158762524-cce3a77b-b2da-411b-900a-1c6d261b64b3.png)
```js
{
    id: "e1-4",
    source: "4",
    target: "3",
    sourceHandle: "1",
    targetHandle: "2",
    markerEnd: {
      type: "arrow"
    }
  }
```
https://codesandbox.io/s/react-flow-multiple-handle-connection-py9ptm

**Comment by moklick** [comment]
Thanks! This is fixed in v10.0.3. For now we are not using a curved connection line anymore and bottom to top, right to left flows should work too.

**Comment by jimstenoo** [comment]
I seem to have a similar issue.

I want to be able to connect source handles with source handles, and target handles with target handles, so I use `connectionMode="loose"`

The logic for this works, but when I connect two targets, the flow node data is representing the right handles, though the edge snaps to the source.

You can test this by rendering a flow with the snippet below.
And try to connect the target handles of each node.

Expected result:

<img width="538" alt="Screenshot 2022-06-23 at 18 54 55" src="https://user-images.githubusercontent.com/19685783/175353525-c771aced-f0c1-44d5-9437-67a0fa9a7d89.png">

Actual result:

<img width="457" alt="Screenshot 2022-06-23 at 18 22 25" src="https://user-images.githubusercontent.com/19685783/175353624-0fb44d12-b10e-4601-9640-a1aa988be30b.png">


I encountered this problem with a custom node with more than one handles.

In that case the edge data (including the targetHandle id) was correct but it was just the UI that didn't correspond with the edge data.

Does anyone have an idea if I am doing something wrong? Or is it a bug?



```
import ReactFlow from 'react-flow-renderer';

const defaultNodes = [


  {
    id: '1',
    data: { label: 'Default Node' },
    position: { x: 0, y: 0 },
    // when you don't pass a type, the default one gets used
  },
  {
    id: '2',
    data: { label: 'Default 2' },
    position: { x: 300, y: 0 },
  },
];

const defaultEdges = [];

function Flow() {
  return <ReactFlow defaultNodes={defaultNodes} defaultEdges={defaultEdges} fitView connectionMode="loose"/>;
}

export default Flow;
```

**Comment by jimstenoo** [comment]
Amazing thanks for your help!

I did have unique id's on each handle in my custom and the 'loose' setting, but setting all handle 'types' to 'source' worked for me. Thanks a lot
