### ISSUE TITLE
Markers arrow are not working on v10

### ISSUE THREAD

**Issue by IgorZanellaDev** [wbkd/react-flow#1976]
### Describe the Bug

Arrows are not working, getMarkerEnd works but arrows are not showed.

### Your Example Website or App

https://reactflow.dev/docs/examples/edges/

### Steps to Reproduce the Bug or Issue

Simple use arrows.

### Expected behavior

Arrows are not working, also in your examples, I can't see them also if they are on the edges settings.

Check also here:
https://reactflow.dev/docs/examples/edges/

### Screenshots or Videos

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/10119449/158803626-5f3b1db8-7cf2-4558-b2b4-413f7bf0feb6.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 99.0.4844.74

**Comment by Holybasil** [comment]
Try it
```js
{
   markerEnd: { type: 'arrow', color: '#f00' }
}
```
Refer to this link
https://reactflow.dev/docs/guides/migrate-to-v10/#8-arrowheadtype-markerendid---markerstart--markerend

The example on the documentation was probably forgotten to be updated.

**Comment by moklick** [comment]
Thanks @IgorZanellaDev. If you find bugs in the docs, you can open an issue in this repo: https://github.com/wbkd/react-flow-docs
