### ISSUE TITLE
Floating Edges Don't Work with Sub Flows

### ISSUE THREAD

**Issue by AustinGilliam** [wbkd/react-flow#1980]
### Describe the Bug

The Floating Edge concept introduced in the examples breaks when a Sub Flow is added, creating an issue where edges move when their target node does, and the target node is moved when the group node moves, but the nodes aren't in the right place.

### Your Example Website or App

https://reactflow.dev/docs/examples/floating-edges/

### Steps to Reproduce the Bug or Issue

1. Edit the Target node in the Floating Edge example so that it is contained by a group. I personally tried the following in createNodesAndEdges() of the utils.js file:
```
nodes.push({ id: 'target', data: { label: 'Target' }, position: center, parentNode: 'group', extent: 'parent'});
nodes.push({ id: 'group', type: 'group', position: center});
```
2. Refresh the display on the right.
3. Drag the group node -- the target node should move.
4. Drag the target node -- the edges should move, but they're pointing to empty space, and the example locks up.

### Expected behavior

Floating edges should work with sub flows/group nodes similar to other edge types.

### Screenshots or Videos

This is what happens after the first render:

<img width="604" alt="Screen Shot 2022-03-17 at 1 09 17 PM" src="https://user-images.githubusercontent.com/47156234/158856294-7b4ae68f-340b-4cac-bd7c-6971a1f1ac0b.png">

This is what happens when I try to drag the Target node:

<img width="563" alt="Screen Shot 2022-03-17 at 1 12 08 PM" src="https://user-images.githubusercontent.com/47156234/158856435-41986dc1-0d9a-4d26-b43a-91e2100ea32a.png">

### Platform

- OS: macOS BigSur version 11.6
- Browser: Chrome Version 99.0.4844.51 (Official Build) (x86_64)
- Version: v10.0.3

**Comment by moklick** [comment]
We adjusted the example. It now also works with sub flows. The issue was that we used `position` instead of `positionAbsolute`

**Comment by nav1610** [comment]
In the same [example](https://reactflow.dev/docs/examples/floating-edges/), I am trying to add the label to the edge, but it won't show

`edges.push({
      id: `edge-${i}`,
      target: 'target',
      source: `${i}`,
      type: 'floating',
      label: `edge-${i}`,
      markerEnd: {
        type: MarkerType.Arrow,
      },
    });`
