### ISSUE TITLE
OnNodesChange is triggered when the component is initialized

### ISSUE THREAD

**Issue by Holybasil** [wbkd/react-flow#1982]
### Describe the Bug

I think the onNodesChange event is triggered only when the nodes or edges change as stated in the documentation.

![CleanShot 2022-03-18 at 15 39 51](https://user-images.githubusercontent.com/21138718/158957635-db81f516-629c-42c2-90ac-6f2aa9cbc7bc.png)

However, it puzzled me that it is triggered immediately when the component is initialized.

### Your Example Website or App

https://codesandbox.io/s/react-flow-onnodeschange-hxg0z0

### Steps to Reproduce the Bug or Issue

1. Open the link below
2. Check the console

### Expected behavior

OnNodesChange should be triggered when change occurs.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Good point! I will add a note to the docs. In this case the nodes get initialized. After the mount, React Flow measures them and notifies the onNodesChange handler about the width and height.
