### ISSUE TITLE
Default zoom value is not working when we assign a state variable.

### ISSUE THREAD

**Issue by hariraghupathy** [wbkd/react-flow#1998]
### Describe the Bug

In a react component, when we assign a state variable as value to the `default zoom` property, It does not work as expected. But when we hardcode the value, it works.

### Steps to Reproduce the Bug or Issue

```
import React, { useEffect, useState } from "react";
import ReactFlow, { Node } from "react-flow-renderer";

const initialNodes = [
  {
    id: "1",
    type: "input",
    data: {
      label: (
        <>
          Welcome to <strong>React Flow!</strong>
        </>
      ),
    },
    position: { x: 250, y: 0 },
  },
  {
    id: "2",
    data: {
      label: (
        <>
          This is a <strong>default node</strong>
        </>
      ),
    },
    position: { x: 100, y: 100 },
  },
];

const initialEdges = [
  { id: "e1-2", source: "1", target: "2", label: "this is an edge label" },
];

export const ReactComponent = () => {
  const [nodes, setNodes] = useState(initialNodes);
  const [edges, setEdges] = useState(initialEdges);
  const [zoom, setZoom] = useState(0);

  const addNode = () => {
    // code to update the nodes
  };

  useEffect(() => {
    if (nodes.length === 1) {
      setZoom(1);
    } else {
      setZoom(0);
    }
  }, [nodes]);

  useEffect(() => {
    console.log("Default zoom value is printed correct" + zoom);
  }, [zoom]);

  return <ReactFlow nodes={nodes} edges={edges} defaultZoom={zoom} />;
};
```

### Expected behavior

Default zoom prop should pick latest state value of zoom.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey @hariraghupathy 

the `defaultZoom` prop works like `defaultValue` for an `<input />` component. It's the initial value and you can't change it afterwards. Currently we don't have a controlled prop that you can use the control the zoom level. You need to use `zoomTo` from the react flow instance https://reactflow.dev/docs/api/react-flow-instance/#zoomto
