### ISSUE TITLE
Parent element covers the child element and therefore child element's event cannot be triggered. 

### ISSUE THREAD

**Issue by so2liu** [wbkd/react-flow#2003]
### Describe the Bug

Since all elements' z-index is 0, event owner depends on which element place order in data structure. 

Like this example, https://codesandbox.io/s/react-flow-render-issue-parent-covers-childs-area-fzbcby

Child 1 cannot be moved, since it is coverd by parent. Otherwise, child 2 is able to moved. 

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/react-flow-render-issue-parent-covers-childs-area-fzbcby

### Expected behavior

All child elements should be on top of parent. 

### Platform

- OS: macOS
- Browser: Chrome

**Comment by Sec-ant** [comment]
There's a note [on this page](https://reactflow.dev/docs/guides/sub-flows/#:~:text=node%20specific%20options.-,ORDER%20OF%20NODES,-It%27s%20important%20that):
> ORDER OF NODES
> It's important that your parent nodes appear before their children in the `nodes`/`defaultNodes` array to get processed correctly.

**Comment by so2liu** [comment]
ok
