### ISSUE TITLE
useUpdateNodeInternals doesn't update edges after moving handles

### ISSUE THREAD

**Issue by AndrewRayCode** [wbkd/react-flow#2008]
### Describe the Bug

I move my component handles around dynamically. The edges to those handles don't move, and any additional attempt to connect edges to the moved handles fails, the edges get connected to the wrong place. I'm using `useUpdateNodeInternals` but it doesn't work as I would expect.

### Steps to Reproduce the Bug or Issue

I have a custom handle component like this:

```jsx
const CustomHandle = ({ nodeId, id, handleIndex, ...props }: any) => {
  const updateNodeInternals = useUpdateNodeInternals();
  useEffect(() => {
      updateNodeInternals(nodeId);
  }, [nodeId, updateNodeInternals, handleIndex, id]);

  return <Handle id={id} {...props} />;
};
```

this is to try to force the edges to update correctly after I move handles around. I render it like this:

```jsx
{data.inputs.map((input, index) => (
          <React.Fragment key={input.name}>
            <div
              className="react-flow_handle_label"
              style={{
                top: `${handleTop - textHeight + index * 20}px`,
                left: 15,
              }}
            >
              {input.name}
            </div>
            <CustomHandle
              handleIndex={index}
              nodeId={id}
              id={input.name}
              className={cx({ validTarget: input.validTarget })}
              type="target"
              position={Position.Left}
              style={{ top: `${handleTop + index * 20}px` }}
            />
          </React.Fragment>
        ))}
```

### Expected behavior

In this case the effect fires, but the edge does not get moved to the right place. The edge stays stuck to the stale handle even after the handles update and the effect runs.

Sadly, this works:

```jsx
const CustomHandle = ({ nodeId, id, handleIndex, ...props }: any) => {
  const updateNodeInternals = useUpdateNodeInternals();
  useEffect(() => {
    setTimeout(() => {
      updateNodeInternals(nodeId);
    }, 0);
  }, [nodeId, updateNodeInternals, handleIndex, id]);

  return <Handle id={id} {...props} />;
};
```

the settimeout indicates to me there's some state/updating issue going on.

### Platform

Mac Chrome 10.0.3

### Additional context

Related to https://github.com/wbkd/react-flow/issues/916

Discord convo starts here https://discord.com/channels/771389069270712320/859774873500778517/956236629603926046

As a consumer of react-flow, `useUpdateNodeInternals` is the first part of the API I personally find "ugly" - it's an imperative manual user step and it's unclear when it should be fired, and this issue indicates to me it's exposing some state update ordering that the end consumer shouldn't have to worry about. Also this is not something obvious to google for, I didn't discover it in the docs myself, someone in discord pointed me to this API. Ideally updating handles would "just work" out of the box.

**Comment by AndrewRayCode** [comment]
Actually after my setTimeout update, it put the edge right in the middle of the node, so I think i'm still missing something

<img width="193" alt="Screen Shot 2022-03-23 at 11 56 12 AM" src="https://user-images.githubusercontent.com/79215/159775122-49b9558c-e37d-4f14-ac89-fb0bf479ea61.png">

**Comment by AndrewRayCode** [comment]
I don't animate the position of anything in my graph. I have some css animations which animate the opacity of drop shadows and border colors when dragging connection lines to indicate which targets are droppable, but I don't think that's what you mean

**Comment by onlaps** [comment]
having same problem with repositioning edge when node's size is chaning

**Comment by andreas-schultz** [comment]
This seems to be a regression. For me `updateNodeInternals` still worked as expected in version `9.6.1`, but does not anymore in version `9.7.4`.

**Comment by CamboimGabriel** [comment]
did you solved?

**Comment by moklick** [comment]
Did you try to add `props.style` to the `useEffect` ? Could someone create a codesandbox or repo for this specific case?

**Comment by moklick** [comment]
Could you try to use v10.3.15 ? It should work better now.

**Comment by RAFA3L** [comment]
I have a similar problem trying to delete orphans edges dynamically, my handles are dependent of values in fields, so I need to delete them when fields are updated and the handles removed.

This is weird, inside a custom node I try this:

```
useEffect(() => {
  console.log(nodeInternals); // updated
  console.log(nodeInternals.get(props.id)); // old
}, [nodeInternals, props.id]);
```

The first log print the updated state of the handleBounds (inspecting the node in the tree map), but the second print the node with the old state.

Using the setTimeout suggested by @AndrewRayCode  works, so I can get the updated handleBounds and remove the edges:

```
  useEffect(() => {
    setTimeout(() => {
      const node = nodeInternals.get(props.id);
      const propSymbols = Object.getOwnPropertySymbols(node);
      const handleBounds = node[propSymbols[0]].handleBounds;
      const orphans = edges.filter(
        (e) =>
          e.source === node.id &&
          !handleBounds.source.find((h) => h.id === e.sourceHandle)
      );
      reactFlowInstance.deleteElements({ edges: orphans });
    }, 0);
  }, [nodeInternals, props.id, edges, reactFlowInstance]);
```
  
  
  And in my field changes handle something like this:
  
```
  const handleChanges = (e) => {
    updateNodeFields(node.id, e.formData, e.errors);
    updateNodeInternals(node.id);
  };
```

Regards

**Comment by Timot05** [comment]
I'm running into similar issues using reactflow 11.11.2. Is there additional documentation about how to solve this issue?

**Comment by moklick** [comment]
Hey @Timot05 could you provide a codesandbox or repo for this?

**Comment by Timot05** [comment]
Here is a [codesandbox](https://codesandbox.io/p/sandbox/funny-microservice-76cdth?file=%2FApp.js%3A125%2C7&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvyxhbd300073b6ixzbdun80%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvyxhbd300033b6i2tir6d6e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvyxhbd300043b6itn7atlnd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvyxhbd300063b6itgkv657t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvyxhbd300033b6i2tir6d6e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvyxhbd200023b6iiuo92qiu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A125%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A125%252C%2522endColumn%2522%253A7%257D%255D%257D%252C%257B%2522id%2522%253A%2522clvyxotck00023b6j9ouat8hp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A25%257D%255D%252C%2522filepath%2522%253A%2522%252FColorSelectorNode.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvyxhbd300033b6i2tir6d6e%2522%252C%2522activeTabId%2522%253A%2522clvyxhbd200023b6iiuo92qiu%2522%257D%252C%2522clvyxhbd300063b6itgkv657t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvyxhbd300053b6ipjtbmi8u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvyxhbd300063b6itgkv657t%2522%252C%2522activeTabId%2522%253A%2522clvyxhbd300053b6ipjtbmi8u%2522%257D%252C%2522clvyxhbd300043b6itn7atlnd%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvyxhbd300043b6itn7atlnd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) that is a modified version of [this example](https://reactflow.dev/examples/nodes/custom-node). Pressing on the button moves the handles. The links don't update though.

**Comment by bcakmakoglu** [comment]
@Timot05 
You're passing `data.id` to `updateNodeInternals` but there is no `id` in your `data` object.
The `data` object is meant for you to put in some arbitrary data you need for your business logic, it doesn't contain the node properties.

```ts
  function handleUpdateNodes() {
    setPos(pos + 5);
    updateNodeInternals(data.id); // <--- `data.id` doesn't exist, you're passing `undefined` here
  }
```

To fix the problem you need to pass the actual node id to `updateNodeInternals`

```tsx
// `id` is a prop that is passed to custom nodes
export default memo(({ id }) => {
  const updateNodeInternals = useUpdateNodeInternals();

  const [pos, setPos] = useState(5);

  function handleUpdateNodes() {
    setPos(pos + 5);
    updateNodeInternals(id); // <-- pass the node id to `updateNodeInternals`
  }
```

[Here's your sandbox corrected.](https://codesandbox.io/p/sandbox/weathered-sun-y4n7z4?file=%2FColorSelectorNode.js%3A4%2C1-11%2C4)

**Comment by Timot05** [comment]
Thanks @bcakmakoglu, your sandbox doesn't seem to be available publicly.

I applied the change myself and this indeed solved the issue. In my project, I was using `updateNodeInternals` from the parent object, which didn't seem to be working properly. But moving it inside solved it. Thanks!
