### ISSUE TITLE
Object.defineProperty called on non-object at ReactFlow.esm.js

### ISSUE THREAD

**Issue by lysa21** [wbkd/react-flow#2009]
### Describe the Bug

Bug on v9, error on function 

Object.defineProperty called on non-object
    at defineProperty (<anonymous>)
    at Function.defineProperties (<anonymous>:133:7)
    at ReactFlow.esm.js:545:1
    at Array.forEach (<anonymous>)
    at getAugmentedNamespace (ReactFlow.esm.js:543:1)
    at Module.../../node_modules/react-flow-renderer/dist/ReactFlow.esm.js 

### Steps to Reproduce the Bug or Issue

In url : https://www.youtube.com/

### Expected behavior

In other url, it's ok

### Screenshots or Videos

![Capture d’écran de 2022-03-23 23-11-41](https://user-images.githubusercontent.com/61892780/159805079-336ce5cd-c9d1-42cb-891e-01768782e6eb.png)
![Capture d’écran de 2022-03-23 23-11-51](https://user-images.githubusercontent.com/61892780/159805094-973795c4-0641-4d4c-8d9c-6d912b4a5ee6.png)

### Platform

- OS: [Linux]
- Browser: [Chrome]
- Version: [e.g. Version 97.0.4692.99 (Build officiel) (64 bits)]

**Comment by moklick** [comment]
Hey @is343 

could you provide any more context here? Is React Flow running in an extension? How did you build it?

**Comment by is343** [comment]
I think you incorrectly tagged me instead of the original poster for this issue.
@lysa21 @moklick

**Comment by startly** [comment]
hello,  @moklick,  yes it is in extention and if i remove content of function getAugmentedNamespace in node_module it's work

**Comment by moklick** [comment]
This doesn't seem to be an issue with React Flow. If you think, that it is an issue with React Flow, please provide a repo.
