### ISSUE TITLE
The request 'es6-set/polyfill' failed  in v10

### ISSUE THREAD

**Issue by lysa21** [wbkd/react-flow#2017]
### Describe the Bug

The request 'es6-set/polyfill' failed 

### Steps to Reproduce the Bug or Issue

import of react flow

### Expected behavior

implément react flow

### Screenshots or Videos

![Capture d’écran de 2022-03-24 11-07-20](https://user-images.githubusercontent.com/61892780/159892990-45e8712f-b225-401f-afd7-aa8f756a3e30.png)

### Platform

- OS: [Linux]
- Browser: [e.g. Chrome]

**Comment by moklick** [comment]
Hey @lysa21 

could you provide a bit more context? How are you trying to load or import React Flow?

**Comment by startly** [comment]
hello @moklick , it is in extention, i use v9 for the moment, because when i update v10, i have this error

**Comment by startly** [comment]
Very thanks, it seem ok for install now, i migrate tomorrow :)
