### ISSUE TITLE
v10 doesn't work with Jest

### ISSUE THREAD

**Issue by ERuseckas** [wbkd/react-flow#2019]
### Describe the Bug

v9 was fine
But once I moved to v10, all tests where react-flow is involved in some way started to fail:
```js
***/node_modules/react-flow-renderer/dist/esm/index.js:1
--
197 | ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { _ as _slicedToArray, a as _defineProperty, P as Position, C as ConnectionMode, g as getHostForElement, u as useStoreApi, b as useStore, c as addEdge, d as getMarkerId, r as rectToBox, e as getConnectedEdges, f as getDimensions, h as PanOnScrollMode, i as clamp, j as getNodesInside, k as getSelectionChanges, l as getRectOfNodes, m as ConnectionLineType, M as MarkerType, n as isNumeric, o as Provider$1, p as createStore, q as applyEdgeChanges, s as applyNodeChanges } from './index-5236d2af.js';
198 | ^^^^^^
199 |  
200 | SyntaxError: Cannot use import statement outside a module
```

### Steps to Reproduce the Bug or Issue

No steps needed.

### Expected behavior

Based on research Jest doesn't work well with ESM. So the solution would be to provide CJS.

### Platform

Any platform.

**Comment by moklick** [comment]
Thanks for the report. Have you tried this https://jestjs.io/docs/ecmascript-modules ?

**Comment by ERuseckas** [comment]
I tried it. It only created more problems for me :))

So far my solution is custom mapping:
```js
"moduleNameMapper": {
	"^react-flow-renderer": "identity-obj-proxy"
},
```

`identity-obj-proxy` is good enough, if tests don't really depend on react-flow, but react-flow is imported in tested file. Otherwise you'd have to do proper custom mapping.

In general I guess this ticket could be closed as few possible solutions exists.

**Comment by moklick** [comment]
Ok. Thanks for the hint. We might add information like these to the docs.
