### ISSUE TITLE
multi selection (with Meta key) is always on when a hotkey is used

### ISSUE THREAD

**Issue by RobCvdV** [wbkd/react-flow#2022]
### Describe the Bug

On a mac, when using the Meta key to multiselect nodes (default), after using a hotkey like cmd+c  multiselect is always on.

The behaviour is different when using other keycodes. usaing multiSelectionKeyCode="Alt" results in not being able to multi select after using a hotkey.

Note the console logging in the example for both using "Meta" or "Alt", it appears the key pressed or not pressed won't work properly after using any hotkey, no matter which hotkey shortcut it used.

### Your Example Website or App

https://codesandbox.io/s/react-flow-multiselect-bug-h28ih8

### Steps to Reproduce the Bug or Issue

1. setup/use a boilerplate react-flow app.
2. have several nodes
3. press cmd+c anywhere while the flow component is focused
4. select nodes without the cmd/meta key
5. selection is being added instead of replaced

### Expected behavior

without the Meta key selection should replace any other selection (so deselect other nodes and edges)

### Platform

- OS: MacOS (only one tested)
- Browser: Chrome, Safari, Firefox
- Version: -

**Comment by RobCvdV** [comment]
possible solution in PR #2030

**Comment by moklick** [comment]
Should be fixed in v10.0.7
