### ISSUE TITLE
"Flakey" drop target when custom node+handle+css

### ISSUE THREAD

**Issue by AndrewRayCode** [wbkd/react-flow#2023]
### Describe the Bug

Dragging a connecting line over a handle does not trigger the hover/droppable state when expected.

### Steps to Reproduce the Bug or Issue

My handle CSS:
```
.flownode .react-flow__handle {
  width: 14px;
  height: 14px;
  transition: 0.1s all ease-out;
  z-index: 10;
}
```

Here's my custom FlowNode component.

```

const CustomNodeComponent = ({ data }: NodeProps) => {
  return (
    <div
      className={cx('flownode', data.stage)}
      style={{
        height: `${handleTop + Math.max(data.inputs.length, 1) * 20}px`,
      }}
    >
      <div className="flowlabel">{data.label}</div>
      <div className="flowInputs">
        {data.inputs.map((input, index) => (
          <React.Fragment key={input.name}>
            <Handle
              id={input.name}
              className={cx({ validTarget: input.validTarget })}
              type="target"
              position={Position.Left}
              style={{ top: `${handleTop + index * 20}px` }}
            />
            <div
              className={cx('react-flow_handle_label', {
                validTarget: input.validTarget,
              })}
              style={{
                top: `${handleTop - textHeight + index * 20}px`,
                left: 15,
              }}
            >
              {input.name}
            </div>
          </React.Fragment>
        ))}
      </div>
    </div>
  );
};
```

### Expected behavior

Connecting lines should drop over the area of the node

### Screenshots or Videos

In the movie, you can see that the white outer glow, which I style on `.react-flow__handle.react-flow__handle-connecting`, triggers intermittently as I drag the connecting line over the handle.

https://user-images.githubusercontent.com/79215/160260880-53826e53-40ad-422c-b817-cdb8250ff509.mov

### Platform

Mac, Chrome, 10.0.6

**Comment by OvichHeigVD** [comment]
Any updates on this? Am facing the same issue.

**Comment by AndrewRayCode** [comment]
I can still reproduce this in `10.3.14`

Doing some debugging, it seems that the drop target over the handle is sometimes the connection line itself, and sometimes it's the handle. I'm not sure if this is the cause of the flakiness. I captured 2 separate debugging lines when inspecting the source around `checkElementBelowIsValid`, and in the "bad' drop, you can see the element it's checking is the path

<img width="893" alt="Screen Shot 2022-08-06 at 11 58 11 AM" src="https://user-images.githubusercontent.com/79215/183263021-26a36439-124a-4aef-a623-e79543de87a1.png">

I tried removing pointer events from the connection line, but it doesn't seem to have any effect on the flakiness:

```
.next-stage-edge .react-flow__edge-path {
  pointer-events: none; /* added this */
  stroke-width: 3;
}
```

Also checking the source for where `react-flow__handle-connecting` is added, [it's using `checkElementBelowIsValid`](https://github.com/wbkd/react-flow/blob/9f5d610a92c4e41010a647a2a699305f37dab533/src/components/Handle/handler.ts#L158), which seems to not consistently find the handle, and sometimes finds the path

Adding `isConnectable` to the `<Handle>` component also seems to have no effect.

I'm trying to figure out what's different between my code and https://reactflow.dev/docs/examples/nodes/custom-node/ - since this doesn't seem to show any flakey drop target issues.

Actually, it's unclear to me how the react-flow-renderer code works, since it uses `elementFromPoint` - and when dragging the connecting line, the connect line is always under the mouse.

How does react-flow-renderer guarantee the connection line is ignored when dragging over a handle? That might point me to the difference between my setup and the default one

**Comment by AndrewRayCode** [comment]
Ah finally figured it out, it's because my custom connectionline component had a wrapper element that didn't hide pointer events. This css fixed it for me:
```
react-flow__edge,
.react-flow__edge-path,
.react-flow__connection {
  pointer-events: none;
}
```

**Comment by moklick** [comment]
Oh. This is a good point @AndrewRayCode ! We will add this
