### ISSUE TITLE
couldn't create edge between custom nodes

### ISSUE THREAD

**Issue by brunopenso** [wbkd/react-flow#2027]
### Describe the Bug

Hi Guys,

I'm starting working with react flow and going step by step on creating new features.  I already read some documentation to understand how to customize nodes and on the process of doing this I'm getting this error: `couldn't create edge for target handle id: l1; edge id: a1-a3`

I read some of the issues on github including #1641 and other related in the same issue and had no success.

### Your Example Website or App

https://codesandbox.io/s/exciting-shaw-tyfq4v?file=/src/styles.css

### Steps to Reproduce the Bug or Issue

1. Try to connect a custom node with a default node using mouse (it worked > `A1-B1`)
2. Try to connect a custom node with a custom node using mouse (not worked > `A1-A3`)
3. Create an edge(custom node to custom node id `a1-a3`) in the `edges.js` to see if the edge will be drawn on the page but I get an error on the console

### Expected behavior

Render the edge between custom nodes

### Platform

- OS: macOS
- Browser: Chrome
- Version:  99.0.4844.83

**Comment by terceser** [comment]
Hello, 

in your SystemNode, you should set handle type `'source' | 'target'`

for example, with

```html
<!-- SystemNode.js -->
<Handle
  position={Position.Top}
  type="target"
  id="a1"
  key="a1"
  isConnectable={isConnectable}
  isValidConnection={validateConn}
/>
```

you can then connect A1 to A3 at this specifc Top Handler

![image](https://user-images.githubusercontent.com/7141065/160653451-076da22f-5413-42db-93c2-ad5084d2f969.png)

**Comment by moklick** [comment]
Does this solve your issue @brunopenso ? We will revise the docs!

**Comment by brunopenso** [comment]
Hi Thanks for the answer.

As I understood this type parameter is optional I really need? I saw that the default is undefined [here](https://reactflow.dev/docs/api/nodes/handle/)

Let me explain:

I'm trying to build a product to map architecture landscape so for me it doesn't matter if it is a target or a source, if it really need what I can do is trying to create 2 handles in each side of the node, one for source and other for target.

**Comment by terceser** [comment]
Hi,

The default `undefined` in the doc is not quite correct.

In fact, the default value is `source` [source code here](https://github.com/wbkd/react-flow/blob/main/src/components/Handle/index.tsx#L30)

If i understand correctly, a handle of type `source` can only be connected to a handle of type `target`. (and also in vice-versa if connection mode is Loose)

In your case, IMHO, yes, you can create 2 handles on the top side with type `target`, and 2 handles on the bottom side with type `source`

**Comment by brunopenso** [comment]
Hi everyone,

Adding the type `target` to the handle it works fine. 

@terceser I will test the ConnectionMode and if need a new issue will be open.

@moklick Do you want me to open a new issue to update the documentation? Or this stay open?

**Comment by brunopenso** [comment]
I saw that the doc is already update [here](https://github.com/wbkd/react-flow-docs/blob/main/docs/api/nodes/handle.md)

Thanks all!!!
