### ISSUE TITLE
Custom ConnectionLine regression from v9

### ISSUE THREAD

**Issue by ERuseckas** [wbkd/react-flow#2031]
### Describe the Bug

Connection mode is strict.

Seems like it is assumed that user creates connection from source handle to target handle only.
But it's actually possible to create connection from target handle to source handle too.
Once target to source is used connection line circle is rendered in a wrong spot.
Plus using available `ConnectionLineComponentProps` it's impossible to know, is user creating connection from source or target handle.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-6sgwfv

### Steps to Reproduce the Bug or Issue

1. Go to provided Codesandbox link
2. to see difference try to:
- create new connection by dragging from source/target handles
- update existing connection by dragging edge from source/target nodes

### Expected behavior

I'd expect it to work in the same way like in v9.

### Additional context

I think it's related to this change, which was added into v10:
```js
switch (connectionHandleType) {
    case 'source':
      {
        sourceX = fromX;
        sourceY = fromY;
        sourcePosition = fromPosition;
        targetX = toX;
        targetY = toY;
        targetPosition = toPosition;
      }
      break;
    case 'target':
      {
        sourceX = toX;
        sourceY = toY;
        sourcePosition = toPosition;
        targetX = fromX;
        targetY = fromY;
        targetPosition = fromPosition;
      }
      break;
  }
```

**Comment by Sec-ant** [comment]
Sorry, I don't get the expected behavior in your issue, can you elaborate with more details?
Actually the code you attached is added by me to exactly address the bidirectional natrue of dragging a connection line. And [`ConnectionLineComponentProps` is updated with two more props: `fromNode` and `fromHandle`](https://github.com/wbkd/react-flow/blob/1a5f691559975f8b09c430458f9903e1b86ebc55/src/types/edges.ts#L158-L159) so that you can get the node or handle the connection line is dragged from. `sourceNode` and `sourceHandle` are kept for compatiblity reasons only. But yes these should be documented.

**Comment by moklick** [comment]
I don't think that we changed the behaviour here. You can connect target -> source, but you can't do source -> source or target -> target (when connectionMode=strict). This should be the same for v9 and v10.

**Comment by ERuseckas** [comment]
Ah, true, I missed `fromHandle` prop. Using it I can achieve everything I need.

But there are still few things, which someone should look into:

1. in v9 `sourcePosition` and `targetPosition` were based on actual handle position. In v10 these are identical doesn't matter, which handle user uses. Basically it became useless. The only way to get position is to use `fromHandle?.position`.

2. custom connection line example renders this circle `<circle cx={targetX} cy={targetY} fill="#fff" r={3} stroke="#222" strokeWidth={1.5} />`. It works fine only if user drags from source handle. Dragging it from target handle results in rendering circle in a wrong spot.

**Comment by moklick** [comment]
We added `fromX`, `fromY`, `toX`, `toY`, `fromPosition` and `toPosition`. We will remove the `source..` and `target..` props in v11.
