### ISSUE TITLE
Fallback node render does not work correctly. 

### ISSUE THREAD

**Issue by dwjohnston** [wbkd/react-flow#2033]
### Describe the Bug

If declaring a node `type` that does not exist, the console will report that no renderer for this node type exists and inform you that the default layout is being used. 

eg: 

```
Node type "foo" not found. Using fallback type "default".
```

However, the behaviour of such nodes does not match the actual default node behaviour. 

### Your Example Website or App

https://codesandbox.io/s/bold-voice-84d6jv?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

See linked sandbox: https://codesandbox.io/s/bold-voice-84d6jv?file=/src/Flow.js

Note that lines 24 and 25 show the same node with the same position, the difference is that the line 25 node has type 'foo'. 

```js
// Standard node
 { 
    id: "2",
    data: { label: "Node 2" },
    position: { x: 250, y: 100 }
 },
 
// Node with unrecognised 'type' property 
{
    id: "2",
    type: "foo",
    data: { label: "Node 2" },
    position: { x: 250, y: 100 }
  },
```

### Expected behavior

We would expect that the nodes should display the exact same way, but they don't. The node with type 'foo' has no border, and doesn't not respect positioning the same way. 

### Screenshots or Videos

Actual default behaviour: 
<img width="457" alt="Screen Shot 2022-03-31 at 11 53 16 am" src="https://user-images.githubusercontent.com/2467377/160954647-a35bd15d-0f85-44b5-923d-d4934051af3a.png">

Fallback default behaviour: 
<img width="457" alt="Screen Shot 2022-03-31 at 11 53 00 am" src="https://user-images.githubusercontent.com/2467377/160954654-47776f27-c326-40e1-87ed-dfb999428f2a.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
fix released in v10.3.0
