### ISSUE TITLE
react-beautiful-dnd not working within react flow node

### ISSUE THREAD

**Issue by dexkode4** [wbkd/react-flow#2040]
### Describe the Bug

I built a node item where it's possible to reorder the list with the node
But each time I drag an item it moves out of the node
Please is there a way to fix this ?? 
Many Thanks

https://codesandbox.io/s/hopeful-bose-i0rxsj?file=/src/App.js

### Expected behavior

Item should stay with the node

### Screenshots or Videos

![React App](https://user-images.githubusercontent.com/50272234/161443317-0805aa55-c5b8-4da0-9c6b-1634ffc32242.gif)

**Comment by dexkode4** [comment]
I found the fix for this 
it's as a result transform property on the react-flow-renderer nodes
see [this](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#extending-draggableprops-style)

**Comment by makeitrein** [comment]
> I found the fix for this it's as a result transform property on the react-flow-renderer nodes see [this](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#extending-draggableprops-style)

Could you clarify a bit more about your solution if you have a moment? Definitely just hit this roadblock and trying to figure out the best way to unblock myself.
