### ISSUE TITLE
`onConnectEnd` getting triggered twice

### ISSUE THREAD

**Issue by CKanishka** [wbkd/react-flow#2049]
### Describe the Bug

Instead of taking an edge out of an handle if we just click on a handle then the `onConnectStart` and `onConnectEnd` callbacks get triggered more than once

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-bgb4z0?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Click on a handle of node
2. Do not take out an edge out of the handle
3. The callbacks will get triggered more than once

### Expected behavior

The callbacks should get executed only once as it was in the earlier version of React Flow.

### Screenshots or Videos

https://user-images.githubusercontent.com/30779692/161759635-9c02d111-feec-4739-8cce-3bd12b6e9164.mov

### Platform

- OS: macOS
- Browser: Chrome
- Version: 99.0

**Comment by CKanishka** [comment]
@moklick Any help or comment regarding this behaviour will be highly appreciated.

**Comment by nguyenthanh140195** [comment]
I use 'onConnectStart' and 'onConnectStop' to know the status of making the connection but get the same error

**Comment by moklick** [comment]
`onConnectStart` gets triggered twice, because we are starting a drag connection and a click connection. You can get rid of that if you set `connectOnClick={false}`. I will see if we can get rid of this behaviour in the next release #2152

**Comment by moklick** [comment]
The easiest fix would be to introduce new event handlers like `onTapConnectStart`, `onTapConnect` and `onTapConnectStop` or `onClickConnect`.

**Comment by moklick** [comment]
I added `onClickConnectStart`, `onClickConnectEnd` and `onClickConnectStop` for the upcoming release.

**Comment by moklick** [comment]
released in v10.3.0

**Comment by rsdouglas** [comment]
@moklick We're running into this (onConnectEnd being triggered twice) in v11.10.1 - is this a regression or are we doing something wrong?

**Comment by moklick** [comment]
lgtm https://codesandbox.io/p/sandbox/icy-star-hwf85h?file=/src/Flow.tsx:50,1-51,1

can you send a codesandbox that reproduces your issue.
