### ISSUE TITLE
Can't access nodes using useStore()

### ISSUE THREAD

**Issue by tbertrand7** [wbkd/react-flow#2054]
### Describe the Bug

When using the useStore() hook: `const nodes = useStore((store) => store.nodes)`, nodes is always undefined.

### Steps to Reproduce the Bug or Issue

WIthin a ReactFlowProvider, attempt to access store.nodes.

### Expected behavior

store.nodes should be defined.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 10.0.8

**Comment by moklick** [comment]
When you are using `useStore` you are accessing the undocumented internals. In most cases you don't need to that. If you want to access the nodes and you can't use your local ones, you can

1. use the `useNodes` hook: `const nodes = useNodes();` https://reactflow.dev/docs/api/hooks/use-nodes/
2. use the internal nodes: `const nodes = useStore((store) => Array.from(store.nodeInternals.values()));`
