### ISSUE TITLE
types error with v10 and react 18

### ISSUE THREAD

**Issue by Adidi** [wbkd/react-flow#2059]
### Describe the Bug

Working with the package with react 18 and typescript produce type errors in `ReactFlowProvider` and `ReactFlow` `nodeTypes` and `edgeTypes` props

### Steps to Reproduce the Bug or Issue

1. install react-flow-renderer versoin >= 10
2. install react 18 with types (`@types/react` and `@types/react-dom`)
3. You will see type errors in `ReactFlowProvider` and `ReactFlow` components as described above

### Expected behavior

As a user that uses typescript i guess i expect it to work :)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 100.0

**Comment by ERuseckas** [comment]
React 18 isn't supported yet

**Comment by Adidi** [comment]
10x.

**Comment by moklick** [comment]
Please check #2067 and let me know if you are encountering any issues. Thanks for your help!

**Comment by Adidi** [comment]
@moklick works perfectly with `react-flow-renderer@next`
Thanks for the excellent work with the lib
