### ISSUE TITLE
Node resizing bug after restoring a flow

### ISSUE THREAD

**Issue by Hillal-azem** [wbkd/react-flow#2071]
### Describe the Bug

At first, on custom nodes, when you modify the label in the node, its size adapts and the edge with the other nodes adapt. However, if we do the same thing on the nodes of a restored flow, the size of the nodes adapts but the edge lose the true position of the handle. 

I even used the updateNodeInternals function before saving, but the result is the same.

FYI, I tested with default nodes and it generates the same bug.

i'm saving like this: 

`const onSave = useCallback(() => {
        if (rfInstance) {
            const flow = rfInstance.toObject();
            flow.nodes.forEach(node => {
                updateNodeInternals(node.id);
            });
            localStorage.setItem('flow', JSON.stringify({
                ...flow,
            }))
        }
    }, [rfInstance]);`

### Steps to Reproduce the Bug or Issue

1. create two custom nodes and link them with an edge 
2. save the flow 
3. restore the flow 
4. update (first) node label with big text 

### Expected behavior

Th node handles should adapt its handle positon 

### Screenshots or Videos

Before saving: 

<img width="558" alt="Capture d’écran 2022-04-13 à 10 53 44" src="https://user-images.githubusercontent.com/39773773/163139223-cadfe1bf-02b9-46cb-a06c-f6ed4458a6eb.png">

After restoring: 

<img width="558" alt="Capture d’écran 2022-04-13 à 10 54 20" src="https://user-images.githubusercontent.com/39773773/163139350-8f48c4b4-ec46-43d1-8d88-62299befdf4f.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
This should be fixed in v10.3.9. Can you confirm @Hillal-azem ?

**Comment by moklick** [comment]
Please re-open if the issue still occurs.
