### ISSUE TITLE
Performance drop when render big images on pane

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#2073]
### Describe the Bug

When I try to put a large file on pane, the scroll lose a lot of performance, how can I solve this?

### Your Example Website or App

https://userflows.d.visualsitemaps.com/

### Steps to Reproduce the Bug or Issue

1. Upload a large file image
2. Scroll

### Expected behavior

Lose performance

### Screenshots or Videos

https://user-images.githubusercontent.com/36650520/163265064-f340f41e-ba71-4cf3-b74c-74ba8cf3134d.mp4

### Platform

- OS: Linux
- Browser: Chrome

**Comment by visualsitemaps** [comment]
I have confirmed this on OS Chrome. The zooming in/out becomes very rough and clunky. 
[Take a look at how smooth it is in this viewer](https://whimsical.com/image-canvas-zooming-Csvqeuzzko8EuNzSFPcD7v):

**Comment by moklick** [comment]
Hey @CamboimGabriel 

I am not sure what is happening here. But it's not a React Flow issue. When I zoom in and out I can see that the src of the image changes. This shouldn't happen. If you fixed that I would also try to decrease the image size on the client before you add it to the pane.

**Comment by visualsitemaps** [comment]
Thanks @moklick we managed to resolve the performance issue.
