### ISSUE TITLE
v10.1.0 - MarkerType.ArrowClosed not working 

### ISSUE THREAD

**Issue by noams-unbiased** [wbkd/react-flow#2075]
### Describe the Bug

Hello.

I've just installed the new version (worked with version 9.x previously), and refactored my code to work as described in the docs.
I can't get the `MarkerType.ArrowClosed` setting to work.
here's how i define my edge:
```typescript
edges.push({
            id: `edge-${nodes[i].id}-${nodes[i+1].id}-from`,
            source: nodes[i].id,
            target: nodes[i+1].id,
            markerEnd: { type: MarkerType.ArrowClosed },
          })
```
The result is a simple edge with no arrow. `MarkerType.Arrow` doesn't work either.

the html (svg) code generated for the edge is:
```
<g class="react-flow__edge react-flow__edge-default nopan"><path d="M832,29 C832,87.5 832,87.5 832,146" class="react-flow__edge-path" marker-end="url(#type=arrowclosed)" marker-start="url(#)"></path></g>
```
Note that the marker-end property is added as expected, but the arrow drawing doesn't include the arrow.

However, the `defs` section of the edges container is completely empty. so the `type=arrowclosed` marker is undefined

Is it a bug? or am I doing something wrong? 

### Steps to Reproduce the Bug or Issue

Start with an empty canvas, and dynamically add a couple of nodes and an edge with an end marker as i've pasted in the description..

### Expected behavior

I expect the edge to end with an arrow head.

### Platform

Google Chrome | 99.0.4844.51 (Official Build) (64-bit)   
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}   
OS | Linux   
JavaScript | V8 9.9.115.8

**Comment by noams-unbiased** [comment]
I've done a bit of research, and it seems like the `useMemo` function in [MarkerDefinitions](https://github.com/wbkd/react-flow/blob/3548891b8e4f6ffbb9de1fbbef582d8eb55304c7/src/container/EdgeRenderer/MarkerDefinitions.tsx#L47) is not called again as I add edges - even though the edges array is changing.

This is because the edges array is addressed by reference, and we get the same array in every run, just different values.
When I change the `ReactFlow` edges prop to `edges={[...edges]}` the arrows are indeed drawn. but this means i will make the `useMemo` function irrelevant since the array will change on every re-render even if there is no change to the edges.

**Comment by moklick** [comment]
Hey @noams-unbiased 

when you are adding a new edge or node you should create a new array. Otherwise React Flow can't recognize the changes. Don't create a new array on every render but just when you add a new edge or node.
