### ISSUE TITLE
Can't use material ui drawer with react flow

### ISSUE THREAD

**Issue by ramizqazi** [wbkd/react-flow#2077]
### Describe the Bug

I want to use this material UI drawer with react flow but i can't . drawer closes automatically any where i press on drawer. please help me with this.

### Steps to Reproduce the Bug or Issue

I don't Know

### Expected behavior

drawer should not close .

### Screenshots or Videos

https://user-images.githubusercontent.com/77078731/163383148-72c84096-fcd4-43e1-9091-d716ab2b8024.mp4

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
You can probably solve the issue by adding `className="nowheel nodrag nopan"` to your `Drawer` component.
That would disable any interaction with React Flow in the background while scrolling etc. inside your Drawer.

Here's a [sandbox](https://codesandbox.io/s/clever-sound-gqppvr?file=/src/Drawer.js:2063-2108) with the suggestion.
