### ISSUE TITLE
useKeyPress: keyboard repeat not working

### ISSUE THREAD

**Issue by raarts** [wbkd/react-flow#2080]
### Describe the Bug

With useKeyPress(), if I press and hold a key, the action only happens once. I need to specifically release and press it again.

### Steps to Reproduce the Bug or Issue

I think this speaks for itself.

### Expected behavior

I want to press the key, and have actions repeating while I keep it pressed.

### Platform

- OS: MacOS
- Browser: All
- Version: 10.1.0

**Comment by moklick** [comment]
Hey @raarts 

This is not how the API is supposed to work. It's a hook that returns a boolean. If you want a repeating action you need to come up with your own implementation like:

```js 
const interval = useRef();
const metaPressed = useKeyPressed(['meta']);

useEffect(() => {
  if (metaPressed) {
    interval.current = window.setInterval(doSomething, 100);
  } else {
    window.clearInterval(interval.current);
  }
}, [metaPressed])
```

_(untested pseudo code)_
