### ISSUE TITLE
Dragging nodes over elements outside of the graph causes position glitch

### ISSUE THREAD

**Issue by NikolMarg** [wbkd/react-flow#2081]
### Describe the Bug

In bigger graphs (can happen very easily in production graphs that contain a lot of data but also happens when there are many nodes) there is a drag glitch when hovering over outside elements.

### Your Example Website or App

https://codesandbox.io/s/react-flow-drag-issue-4zq7lf?file=/src/FlowExample.tsx

### Steps to Reproduce the Bug or Issue

1. Add as many nodes as possible in the graph (anything over 300 should do, but it can happen to much smaller graphs with data).
2. Select all nodes with Shift.
3. Drag the selection over the text (some of the text should get selected too)
4. Notice the position of the nodes not updating smoothly and them jumping back and forth.

### Expected behavior

There should either be no glitch, or no way for the text to get selected.

### Screenshots or Videos

https://user-images.githubusercontent.com/1859501/163693458-617e073d-8acd-4c34-bba4-2df5316d8db6.mov

### Platform

- OS: macOS
- Browser: Chrome
- Version: Latest

### Additional context

- It's possible that this is not happening in the provided stress example because the example is within an iframe.
- This started happening after upgrading to v.10

**Comment by samanrnr** [comment]
Hi, I have a similar issue, especially when the number of nodes increases. it has some problems with React 18.0.0. it works perfectly with react 17.0.2

https://user-images.githubusercontent.com/25515980/164909858-5cc42a7b-bc06-4400-acba-6d622665fb6c.mp4

.

**Comment by bcakmakoglu** [comment]
> Hi, I have a similar issue, especially when the number of nodes increases. it has some problems with React 18.0.0. it works perfectly with react 17.0.2
> stress.mp4
> 
> .

Have you tried installing `npm i react-flow-renderer@next`? 
Current latest version doesn't support React 18 yet but the next tag does.

**Comment by samanrnr** [comment]
I tried that. It didn't solve.

**Comment by moklick** [comment]
I would not call this a bug with React Flow. I tried the codesandbox and it seems fine. Please re-open if you think that this is still an issue with the latest version.

**Comment by NikolMarg** [comment]
Upgrading to the latest version fixes the issue, great work!
