### ISSUE TITLE
`NodeTypes` has incorrect type definition

### ISSUE THREAD

**Issue by albtsantos** [wbkd/react-flow#2094]
### Describe the Bug

In a newly created TypeScript project, when following the [custom node example](https://reactflow.dev/docs/examples/custom-node/), assigning `nodeTypes` on `ReactFlow` will present an error.

```
Type '({ className, ...rest }: ComponentProps) => Element' is not assignable to type 'ReactNode'
```
 
I assume the type `NodeTypes` has incorrect definitions. ReactFlow is not expecting a node, but a component type.

After applying the necessary changes to pass the type check (`const nodeTypes = { selectorNode: <ColorSelectorNode /> }`) the code runs, but rendering doesn't work:

```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <FileSelectionBlock />. Did you accidentally export a JSX literal instead of a component?
```

Suppressing the type check when assigning `nodeTypes` works. 

### Steps to Reproduce the Bug or Issue

1. Create a TypeScript project using `create-react-app --template typescript`.
2. Install `react-flow-renderer`.
3. Copy the [custom node example](https://reactflow.dev/docs/examples/custom-node/).
4. Most types will be inferred automatically at this point, but you might have to make small adjustments here and there.
5. Try running the project. 

### Expected behavior

Everything should work -- it's the same code as the example (that works with JavaScript in CodePen). 

### Platform

- OS: macOS 12.1 (21C52)
- Browser: Chrome, Safari
- Version: Latest

**Comment by moklick** [comment]
You are probably using React18. If so, you need to install `react-flow-renderer@next`. Does that work for you?

**Comment by albtsantos** [comment]
Thank you @moklick! Works like a charm.

**Comment by yinhw0210** [comment]
@moklick 
I also ran into this problem in version 11.10.3 and the editor told me I couldn't change the type "{customNodes: JSX.Element; } "is assigned to type" NodeTypes ".
Attribute "customNodes" is incompatible with index signatures.
You cannot assign type "Element" to type "ComponentType<NodeProps>".
