### ISSUE TITLE
"EdgeTypes" TypeScript type is not compatible with React components

### ISSUE THREAD

**Issue by tisoap** [wbkd/react-flow#2097]
### Describe the Bug

The `EdgeTypes` TypeScript type used for the `edgeTypes` prop does not actually allow for custom edge components.

### Your Example Website or App

https://codesandbox.io/s/react-flow-edge-types-66ufup?file=/src/Flow.tsx

### Steps to Reproduce the Bug or Issue

1. Create a new TypeScript base project using React Flow
2. Create a variable of type `EdgeTypes` and initialize it with a custom edge component
3. Try to pass said variable to the `edgeTypes` prop on the `<ReactFlow>` component

### Expected behavior

I expected to be able to add custom edges to my React Flow graph without problems, as instructed by the [documentation](https://reactflow.dev/docs/api/edges/custom-edges/), but instead I'm getting a TypeScript error. The application still succeeds in running, the problem is just in the type definitions.

### Screenshots or Videos

![Captura de tela 2022-04-24 174714](https://user-images.githubusercontent.com/28565117/164995936-0f97e545-6b63-4114-a7a3-521f08e71f94.png)

### Platform

Non applicable.

### Additional context
I believe the type of `EdgeTypes` should be something in the lines of:
`Record<string, JSXElementConstructor<EdgeProps>>`

**Comment by moklick** [comment]
Hey @tisoap. When you are using React18, you need to install `react-flow-renderer@next`.

**Comment by tisoap** [comment]
@moklick I've downgraded my codesandbox example to React 17 but the typing problem persists
https://codesandbox.io/s/react-flow-edge-types-66ufup?file=/src/Flow.tsx

**Comment by moklick** [comment]
This is fixed in v10.2.0
