### ISSUE TITLE
setEdge from useReactFlow not working when passing empty array

### ISSUE THREAD

**Issue by SylvainLtt** [wbkd/react-flow#2107]
### Describe the Bug

Hi,

I want to delete all edges using setEdges from useReactFlow hook.
In order to do this I call `setEdges([]);` but it seems nothing happens.
Calling setEdges with a non-empty array works fine but does not with an empty array.

Is there something I'm missing ?
Thanks

### Your Example Website or App

https://codesandbox.io/s/react-flow-setedge-issue-qftobt

### Steps to Reproduce the Bug or Issue

1. Click on 'delete all edges' in sidebar.
2. Nothing happens.

### Expected behavior

All edges should disappear.

### Platform

- OS: Ubuntu 20.04
- Browser: Chromium 100.0.4896.127

**Comment by shemeshx** [comment]
I also deal with this issue. waiting for answer.

**Comment by chrtze** [comment]
Please see my comment on https://github.com/wbkd/react-flow/issues/2117
