### ISSUE TITLE
data.label is not assignable to parameter of type Node< { label: string} > in typescript react

### ISSUE THREAD

**Issue by Aldo111** [wbkd/react-flow#2110]
### Describe the Bug

```
TS2345: Argument of type '({ id: string; type: string; data: { label: string; }; position: { x: number; y: number; }; } | { id: string; data: { label: Element; }; position: { x: number; y: number; }; type?: undefined; })[]' is not assignable to parameter of type 'Node<{ label: string; }>[]'.
  Type '{ id: string; type: string; data: { label: string; }; position: { x: number; y: number; }; } | { id: string; data: { label: Element; }; position: { x: number; y: number; }; type?: undefined; }' is not assignable to type 'Node<{ label: string; }>'.
    Type '{ id: string; data: { label: JSX.Element; }; position: { x: number; y: number; }; type?: undefined; }' is not assignable to type 'Node<{ label: string; }>'.
      The types of 'data.label' are incompatible between these types.
        Type 'Element' is not assignable to type 'string'.
```

Following the `initialNodes` example from the [Core Concepts page](https://reactflow.dev/docs/getting-started/core-concepts/) in a react/ts project causes an error in type definitions (perhaps with the latest version of react?):

```
{
    id: "2",
    // you can also pass a React component as a label
    data: { label: <div>Default Node</div> },
    position: { x: 100, y: 125 },
  },
  ```
This node is the problematic one, which causes an error when used with
`  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);`

### Steps to Reproduce the Bug or Issue

1. Use the initialNodes example from the Core Concepts page within a typescript/.tsx project file.

### Expected behavior

There shouldn't be any error in using this type but there is.

### Platform

- OS: Windows
- Browser: Chrome
- IDE: VS Code

**Comment by Aldo111** [comment]
Sorry, this was silly on my part. I didn't add `: Node[]` to the initialNodes constant.

**Comment by SteveAtKlover** [comment]
@Aldo111 can u add this to the examples section? this is still broken there.

**Comment by paulwongx** [comment]
The roadmap should include typescript examples and if not, just for this example where you put a ReactElement label, because I also encountered this issue and everyone will encounter this issue when going through the docs.
