### ISSUE TITLE
Edges are not visible outside `.react-flow__viewport` when we export the canvas to png

### ISSUE THREAD

**Issue by sriramanb2021** [wbkd/react-flow#2118]
### Describe the Bug

Edges are getting cut off outside `.react-flow__viewport` when we export the whole react flow canvas as png. I'm facing issue while using [html-to-image](https://www.npmjs.com/package/html-to-image), but this issue is reproducible with all the methods used to convert a canvas to png file. There is a related issue #2016 which fixed the issue in the canvas, but this occurs in the exported png.

### Steps to Reproduce the Bug or Issue

1. Create any complex graph with many nodes and edges
2. Convert the react flow canvas to png with any external package

### Expected behavior

Edges should not cut off outside `.react-flow__viewport`, since nodes are visible outside.
This was working perfectly fine in v9. 

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [100.0]

**Comment by junrezapico** [comment]
@sriramanb2021 Were you able to solve this problem? I'm running into this exact issue with [html2canvas](https://github.com/niklasvh/html2canvas) on react-flow-renderer version 10.0.8

**Comment by sriramanb2021** [comment]
@junrezapico Yeah. I replaced html-to-image with [save-html-as-image](https://www.npmjs.com/package/save-html-as-image), and it worked flawlessly!

**Comment by moklick** [comment]
you might need to add `.react-flow svg { overflow: visible; }` if some other CSS rules overwrite it

**Comment by sriramanb2021** [comment]
Hi @moklick, thanks for the suggestion. But adding this css is not working for me as this issue occurs only when exporting the canvas to png.

**Comment by moklick** [comment]
I've created an ["Download Image" example](https://reactflow.dev/docs/examples/misc/download-image/) that uses [html-to-image](https://github.com/bubkoo/html-to-image).

**Comment by ratnajeetshyamkunwar** [comment]
> `.react-flow svg { overflow: visible; }`



> @junrezapico Yeah. I replaced html-to-image with [save-html-as-image](https://www.npmjs.com/package/save-html-as-image), and it worked flawlessly!

@junrezapico which react-flow version were you using? I am using 11.5.6 and even the `save-html-as-image` is producing cropped image.

**Comment by ratnajeetshyamkunwar** [comment]
> I've created a ["Download Image" example](https://reactflow.dev/docs/examples/misc/download-image/) that uses [html-to-image](https://github.com/bubkoo/html-to-image).

@moklick nodes out of the viewport are getting cropped. Is there a solution for this?
![reactflow (25)](https://user-images.githubusercontent.com/36529897/224016113-4304b556-2825-4f3e-a13b-16342e787d03.png)

**Comment by shubham-solytics** [comment]
this issue is still there in new version

**Comment by moklick** [comment]
It's not an issue but just the way how the html-to-image library works. If you want all nodes to be visible you need to adjust the transform style of the react-flow__viewport element: https://codesandbox.io/s/trusting-jang-jiixm4?file=/DownloadButton.js:693-1199 

I will update the example on the website!

**Comment by evisdrenova** [comment]
is there a way to export this as an svg and maintain the animated edges?

**Comment by furkanbicak** [comment]
Is there a way to include the button in the upper right corner in the image?

**Comment by moklick** [comment]
@furkanbicak yes, that's possible. You need to change the selector to ".react-flow".

**Comment by vect-ybetou** [comment]
Hello, The codesandbox examples are not working anymore, the edges are not part of the exported image.

**Comment by vect-ybetou** [comment]
The issue I mentioned is linked to an `html-to-image` dep regression : 
https://github.com/bubkoo/html-to-image/issues/506

**Comment by kranthi-thought-flow** [comment]
> you might need to add `.react-flow svg { overflow: visible; }` if some other CSS rules overwrite it

This worked for me.
