### ISSUE TITLE
Dynamically change the parentNode option on connection between two nodes

### ISSUE THREAD

**Issue by jimymltta** [wbkd/react-flow#2124]
### Describe the Bug

Hi,

I'm trying to implement the sub flow feature on my project, but 'dynamically'. I don't know in advance which nodes will be in the canvas, and which ones will be the parents/children nodes.

The thing I'm trying to do is : 

1 - I create a node 'a' (from a sidebar)
2 - I create a node 'b'
3 - I connect nodes 'a' and 'b' together
4 - On connection between the two nodes, I'd like to add the parentNode option to node 'b', saying that its parents is node 'a'.

I already tried this : 

```
const onConnectBefore = useCallback(
    (connection) => {
      const source = connection.source;
      const target = connection.target;

      const setParent = (source, nodeId) => {
        source.setParentNode(nodeId);
      };

      console.log("onConnectBefore", connection);
      console.log(source);
      console.log(target);
      if (source.type === "StepNode") {
        setParent(source, target.id);
      }
    },
    [setParentNode]
  );
```

This onConnectBefore function is called in the onConnect : 

```
const onConnect = useCallback(
    (connection) =>
      setEdges((eds) => {
        const source = connection.source;
        const target = connection.target;
        onConnectBefore(connection);
        console.log("connect", source, target);
        return addEdge(connection, eds);
      }),
    [setEdges]
  );
```

The parentNode/setParentNode is a state with an initial value of "".

Thanks in advance for your help!

### Steps to Reproduce the Bug or Issue

/

### Expected behavior

1 - I create a node 'a' (from a sidebar)
2 - I create a node 'b'
3 - I connect nodes 'a' and 'b' together
4 - On connection between the two nodes, I'd like to add the parentNode option to node 'b', saying that its parents is node 'a'.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey! What is the issue here? Do you need help with a custom implementation or did you find a bug? If so, please create a codesandbox. Thanks!

**Comment by moklick** [comment]
Please re-open if the issue persists
