### ISSUE TITLE
Title is set in the reactflow examples but not in prod for Controls

### ISSUE THREAD

**Issue by JohnCliffe** [wbkd/react-flow#2134]
### Describe the Bug

https://reactflow.dev/docs/examples/interaction/drag-and-drop/

Title is set in the reactflow examples but not in prod.

This means that you get a nice little tooltip when you hover over the Controls on the examples but when you implement it there is no tooltips. I'd love to hear if anybody has a solution to this if I am wrong but after digging into it this is all I can see.

### Steps to Reproduce the Bug or Issue

Implement ReactFlow

Hover over the Controls

### Expected behavior

Tooltip should display

### Platform

Windows 11

**Comment by moklick** [comment]
The examples are basically the prod version of the library. We are not adding something.

**Comment by moklick** [comment]
please re-open if the issue still persists. I can't reproduce this.
