### ISSUE TITLE
Same keycode breaks Selection & MultiSelection

### ISSUE THREAD

**Issue by reemadsouza** [wbkd/react-flow#2135]
### Describe the Bug

I want to assign Control/Command + Click on Windows/Mac for both selecting while dragging or selecting multiple nodes by clicking on nodes respectively but Multiselection breaks in the below code

` const selectionKeyCode = ['Meta', 'Control'];
  const multiSelectionKeyCode = ['Meta', "Control'];`

I want both to select multiple nodes by pressing Control/Command, dragging and selecting nodes as well as pressing Control/Command and clicking on nodes to be selected which breaks in the above node.

` const selectionKeyCode = 'Shift';
  const multiSelectionKeyCode = ['Meta', 'Control'];`

` const selectionKeyCode = 'Meta';;
  const multiSelectionKeyCode = 'Meta';`

This works but then there are two different key actions required which is not normal behavior in Windows or Mac. Also, Meta is a Windows key on Windows while Meta is a Command key on Mac so always need to have an array. 

### Steps to Reproduce the Bug or Issue

1. Press Control on Windows or Command on Mac, drag and draw a rectangle to select
2. Press Control on Windows or Command on Mac, and click on more than 1 node to select

### Expected behavior

1. Allows use of Control key on Windows or Command key on Mac but failes

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by CamboimGabriel** [comment]
For me too, what I did is create a drag select from scratch using selecto
![image](https://user-images.githubusercontent.com/36650520/167990776-3d40c1ba-4744-4704-bfff-f076236f484e.png)

**Comment by moklick** [comment]
this should be fixed with 10.3.7

**Comment by moklick** [comment]
Please re-open if the issue still persists

**Comment by maclockard** [comment]
@moklick I am unable to set `multiSelectionKeyCode` and `selectionKeyCode` to the same key code. I'm currently use @reactflow/core 11.3.1.
