### ISSUE TITLE
Handle connection is slightly off center/misaligned

### ISSUE THREAD

**Issue by Aldo111** [wbkd/react-flow#2138]
### Describe the Bug

![image](https://user-images.githubusercontent.com/4701812/167823140-cb1a4933-8701-47b4-8541-c7496c45c4e0.png)

Once in a while when I'm deleting or reconnecting handles to each other, I'll see this misaligned handle connection as seen on the right here. Not sure if it has anything to do with my handles being custom styled (though it seems to be able to handle that 90% of the time just fine, with the connection going into the center of the orange handle).

### Steps to Reproduce the Bug or Issue

~~Haven't identified a way to consistently reproduce this.~~

1. Place a node with variable height (eg. put a div or something inside of it)
2. Increase the height of the node after it's been placed
3. Try connecting

### Expected behavior

![image](https://user-images.githubusercontent.com/4701812/167823418-c145ad5d-ba21-4591-8a03-2c9b507301e3.png)

### Platform

- OS: Windows
- Browser: Chrome (latest)
- Version: latest

**Comment by Aldo111** [comment]
I just noticed this happens specifically when your Node's height changes after it's been placed. eg. I have a couple of form inputs with potentially variable height inside that right node, depending on user input.  (Hence, the handle moves down a little bit)

Is there a way to ensure that even if the height changes, the end of the connection is able to find the position of the handle?

**Comment by moklick** [comment]
We are measuring the node and update the internals whenever the dimensions change. It's weird that it seem not to work here. Can you create a simplified codesandbox for this?
