### ISSUE TITLE
Drag / Click doesn't work with there's focus on other element

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#2139]
### Describe the Bug

https://reactflow.dev/docs/examples/nodes/custom-node/ using this as an example, if I open the color picker and, with it open, try to drag any node, it doesn't allow, it takes me two action to be able to do that (click outside and than drag)

### Steps to Reproduce the Bug or Issue

1. Open Color Picker
2. Try to drag a node

### Expected behavior

I expect to be able to drag and click if the color picker, any picker, or even an input is focused

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
I can't reproduce this and even if I could I wouldn't say that it has something to do with React Flow. You might need to call `blur()` for an input but it should already work, as the video shows: 

https://user-images.githubusercontent.com/2857535/168049760-79f865e4-081c-4404-8843-d9b733b7ca33.mov

**Comment by moklick** [comment]
please re-open if the issue still persists.
