### ISSUE TITLE
Non-Bezier edges connecting a node to itself are invisible

### ISSUE THREAD

**Issue by barneaoren** [wbkd/react-flow#2140]
### Describe the Bug

Using latest version of ReactFlow, trying to connect a node to itself results with invisible edge when not using bezier and not always visible when using bezier.

### Steps to Reproduce the Bug or Issue

```typescript
import React, { StrictMode } from "react";
import ReactDOM from "react-dom";
import ReactFlow from "react-flow-renderer";
import "./styles.css";

const initialNodes = [
  {
    id: "n1",
    data: { label: "n1" },
    position: { x: 200, y: 0 }
  },
];

const initialEdges = [
  {
    id: "e1",
    source: "n1",
    target: "n1",
    type: "step"
  }
];

const EdgesFlow = () => (<ReactFlow nodes={initialNodes} edges={initialEdges} fitView />);

const rootElement = document.getElementById("root");
ReactDOM.render(
  <StrictMode>
    <EdgesFlow />
  </StrictMode>,
  rootElement
);
```

### Expected behavior

It is expected that the edge will be at least visible, and that it will be possible to select it for adjustments or removal needs.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/11270701/167965605-2e05ff55-90a2-4351-9934-2a1a17ca059f.png)

### Platform

- OS: Any
- Browser: Any
- Version: 10.x

### Additional context

There is also an issue related to this one, where if we have a step with outputs on the left and right and we connect the left output to a step located to the right, the edge will go up/down and to the left, through the source node. This will cause a visual confusion where it seems as the edge is connected to the right output while it is in fact connected to the left.

**Comment by moklick** [comment]
React Flow doesn't support self connecting edges. If you need it, you need to implement a custom edge. Example: https://codesandbox.io/s/self-connecting-node-2nbh7v?file=/src/CustomEdge.tsx

**Comment by aztack** [comment]
Above `CustomEdge.tsx` is a **horizontal** (input at right and output at left) self-connected node.
Here is a **vertical** (input at top and output at bottom) version:
```tsx
import { BezierEdge, EdgeProps } from "reactflow";

export default function CustomEdge(props: EdgeProps) {
  if (props.source !== props.target) {
    const newProps = { ...props,
      sourceX: props.sourceX - 2,
      targetX: props.targetX - 2,
    };
    return <BezierEdge {...newProps} />;
  }

  const { sourceX, sourceY, targetX, targetY, id, markerEnd } = props;
  const radiusX = 50;
  const radiusY = (sourceY - targetY) * 0.6;
  // notice here
  const edgePath = `M ${sourceX - 2} ${sourceY - 2} A ${radiusX} ${radiusY} 0 1 0 ${ targetX - 2 } ${targetY + 2}`;

  return (
    <path
      id={id}
      className="react-flow__edge-path"
      d={edgePath}
      markerEnd={markerEnd}
    />
  );
}
```
