### ISSUE TITLE
Pro-Examples(Resize & Rotate): Node is draggable on an area that is not part of the visible node

### ISSUE THREAD

**Issue by bcakmakoglu** [wbkd/react-flow#2156]
### Describe the Bug

In the new pro example for the [Resizable and Rotatable](https://reactflow.dev/docs/examples/nodes/resize-rotate/) node I noticed the following issue:
When you resize the node, the node is visibly resized and moved depending on the direction of resize, to make it look smooth. This causes the actual node element wrapper to be misaligned with the visible node box that apparently has it's own stylings as putting them on the wrapper would interfere with setting another transform value I guess.

The small issue though is that the visible element and the invisible wrapper are **both** draggable.

### Your Example Website or App

https://reactflow.dev/docs/examples/nodes/resize-rotate/

### Steps to Reproduce the Bug or Issue

1. Go to the linked example
2. Resize a node so that it also moves a bit
3. Check the devtools to see the underlying node wrapper element
4. Drag on "empty" space to move node around

### Expected behavior

Dragging should only be possible in the visible part of the node, not the invisible wrapper.

### Screenshots or Videos

<img width="719" alt="grafik" src="https://user-images.githubusercontent.com/78412429/168855677-81b5e1ec-4d94-40fb-b146-a7db318c9beb.png">

Both the purple (the actual visible node) and blue areas (the devtools rect) are draggable and move the node around.

### Platform

- OS: macOS
- Browser: Chrome, Safari, Firefox

**Comment by bcakmakoglu** [comment]
This issue is actually even more noticeable on a rotate, as the underlying node-wrapper is not rotated *at all*.
Generally I understand the problem with applying the resize and rotation to the actual `react-flow__node` element - I just hope that there is a more elegant solution than what I came up with (understandably I don't want you to actually post a solution in here, as this concerns a pro-example 😉)

What **is** possible to "solve" the issue is just adding a `dragHandle` to the node definition (i.e. something like `dragHandle: [data-moveable-id='1'])` and setting the cursor to default (i.e. `style: { cursor: 'default' }`).

Obviously this is just a remedy so that the invisible part of the node isn't draggable and doesn't show a grab-cursor - node events like click etc. still get triggered on the wrong area so it's really not a viable solution imo.

Anyway, just wanted to let you guys know 😄

**Comment by chrtze** [comment]
This will be fixed with the release of v11.

**Comment by chrtze** [comment]
This is fixed in the new version of the Pro example: https://reactflow.dev/docs/examples/nodes/resize-rotate/
