### ISSUE TITLE
MultiSelect option created with Control Button

### ISSUE THREAD

**Issue by jGreen-thinktum** [wbkd/react-flow#2160]
### Describe the Bug

From what I've seen currently there is a way to multiselect with shift and dragging the mouse, and multiselect based on a key code. I am wondering if there is a way in which a control button can be used to multiselect nodes within a canvas. Is there any props within the ReactFlow component that could allow this like just a boolean which allows the user to group/click multiple nodes adding them to the selected elements?

### Steps to Reproduce the Bug or Issue

Selecting multi nodes without pressing additional key only selects one node at a time.

### Expected behavior

Control Button once selected will allow the user to select multiple nodes adding them to the selected elements.

### Platform

Windows 11

**Comment by moklick** [comment]
closed in favour of #2167
