### ISSUE TITLE
d3-drag in 10.3 breaks react-select inside node

### ISSUE THREAD

**Issue by abn5x** [wbkd/react-flow#2172]
### Describe the Bug

The new 10.3 removes react-draggable and changes it for d3-drag, that seems to break event handling inside nodes, which in turn breaks react-select, when clicking(right click) it doesn't open the menu or trigger any event, other buttons work, but react-select doesn't. 

Reverting to 10.2.3 (and react-draggable) solves the issue entirely. 

### Steps to Reproduce the Bug or Issue

1. Create node with react-select
2. ~~Right click~~ Left click to open it
3. Nothing happens

### Expected behavior

Events should trigger without any issue inside nodes.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 101.0.4951.64

**Comment by abn5x** [comment]
I think it's related with #2171

**Comment by moklick** [comment]
`react-draggable` which we used before didn't drag on right click, I will add it to the current version as well.

**Comment by abn5x** [comment]
@moklick whoops I meant left click xD, I think that with right click the react-select was working.

**Comment by moklick** [comment]
Did you try to add the `nodrag` class name?
