### ISSUE TITLE
Node position not accurate when parent node is hidden + `expandParent` is set to true

### ISSUE THREAD

**Issue by bcakmakoglu** [wbkd/react-flow#2179]
### Describe the Bug

In the nested nodes example I noticed the following issue:
You hide a parent node and enable  `expandParent` on a child node which is not hidden.
Now you drag the child node and it starts going all over the place.

Currently child nodes are not automatically hidden when a parent node is - should that be the case? Otherwise `expandParent` should probably be ignored while the parent is hidden I guess.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-8oqeyk?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Open the example
2. Drag a node
3. Watch it go all over the place

### Expected behavior

Either child nodes are hidden when their parent is hidden or expand parent should be ignored when the parent isn't visible.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Thanks for the report @bcakmakoglu ! I think we should hide the child nodes.

**Comment by moklick** [comment]
Is still a bug in the latest version 10.3.6 @bcakmakoglu ?

**Comment by bcakmakoglu** [comment]
@moklick No, the issue is fixed. Seems like it didn't have anything to do with hidden nodes but with the expandParent issue from #2181 

I'll close this issue then 😄
