### ISSUE TITLE
Node dragging property doesn't return to false

### ISSUE THREAD

**Issue by jech33** [wbkd/react-flow#2183]
### Describe the Bug

When dragging a node the dragging property is set to true which is ok, but when the user stops dragging the node, the dragging property remains in true, doesn't return to its original value (false)

### Steps to Reproduce the Bug or Issue

Open react dev tools
Select a node in dev tools
Start dragging that node and check its dragging value
Stop dragging the node and check the dragging value

### Expected behavior

As a user I expected the dragging property to be false when a node is not being dragged, but if I drag it and then stop, the dragging property remains whit a true value.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/67987594/170793127-b6c0d7c9-0df6-454f-89d8-23daa705130f.png)

### Platform

- OS: [Windows 11]
- Browser: [Vivaldi]
- Version: [5.2.2623.48 (Stable channel) (64-bit)]

**Comment by moklick** [comment]
fix released in 10.3.3
