### ISSUE TITLE
Edges between blocks lay on each other

### ISSUE THREAD

**Issue by Vladislav747** [wbkd/react-flow#2185]
### Describe the Bug

I have customized edges and now i get error that two lines are placed on the same coordinates https://prnt.sc/RqOztFoGfiWC. 

The problem is that i can't distinguish them and can delete the right one for example. Is there something i can do with it?

### Steps to Reproduce the Bug or Issue

Create two or more blocks on the same y axis

### Expected behavior

Edges have offfset

### Platform

- OS: Linux
- Browser: Chrome
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
If you have multiple edges coming from / going to a node, you need to implement a [custom node with multiple handles](https://reactflow.dev/docs/guides/custom-nodes/#using-multiple-handles).

**Comment by Vladislav747** [comment]
My Situation is that they are coming from one parent to Handle to two other children Handle. Is it possible to set some kind of offset for this edge?

**Comment by moklick** [comment]
Ah, now I get it. You could try to implement a custom edge that checks for other connections and offsets itself or do some layouting, so that this doesn't happen.
