### ISSUE TITLE
html tag don't work in custom edge

### ISSUE THREAD

**Issue by Jasminou** [wbkd/react-flow#2190]
### Describe the Bug

we can't use react component or div within a custom edge component.

is custom edge need to be an svg object to be able to be displayed ?

### Your Example Website or App

https://reactflow.dev/docs/examples/edges/custom-edge/

### Steps to Reproduce the Bug or Issue

adding a div in my custom edge but does't seem to be displayed 

### Expected behavior

I expected to be able to use <div> or any other component to build my custom edge component 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
Edges are svgs so in order to embed a div/button or similar you'll have to use a foreign object.

[There's an example for that in the docs right here](https://reactflow.dev/docs/examples/edges/edge-with-button/).

**Comment by Jasminou** [comment]
thanks :)
