### ISSUE TITLE
Source handle's position changes do not cause the position of the edge connecting to the source handle to change

### ISSUE THREAD

**Issue by JasonWu008** [wbkd/react-flow#2191]
### Describe the Bug

Here is the example: https://codesandbox.io/s/sandpack-project-forked-m7lt57?file=/ColorSelectorNode.js

When I click the button, the source handle's position changes, but the edge won't change. 

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-m7lt57?file=/ColorSelectorNode.js

### Steps to Reproduce the Bug or Issue

1. click the button

### Expected behavior

I hope the edge will change with the source handle

### Platform

- OS: macOS
- Browser: Chrome
- Version: 10.3.4

**Comment by moklick** [comment]
Hey @JasonWu008 

you need to use [`useUpdateNodeInternals`](https://reactflow.dev/docs/api/hooks/use-update-node-internals/) when you programatically change the handles. I updated your example: https://codesandbox.io/s/sandpack-project-forked-u6tx30

**Comment by JasonWu008** [comment]
Thanks! It helps a lot. The React-Flow is amazing! I hope more and more developers can benefit from it. Best wishes!

**Comment by moklick** [comment]
Nice to hear that :)
