### ISSUE TITLE
Custom styling breaks handles

### ISSUE THREAD

**Issue by georgefst** [wbkd/react-flow#2193]
### Describe the Bug

Shouldn't the following properties be in `style.css`, rather than the default theme?

```
.react-flow__handle {
  position: absolute;
  border: 2px solid #4b5563;
}
```

### Steps to Reproduce the Bug or Issue

Follow the `Theming` docs: https://reactflow.dev/docs/guides/theming/.

Add this import:
```
// you need these styles for React Flow to work properly
import 'react-flow-renderer/dist/style.css';
```

But not this one:
```
// additionally you can load the default theme
import 'react-flow-renderer/dist/theme-default.css';
```

### Expected behavior

Trees should "work properly", to quote the docs.

They do not. Rendering breaks without the `position` and `border` properties mentioned above, with edges being mispositioned.

### Platform

Firefox and Safari on MacOS.

**Comment by moklick** [comment]
Good catch! Fixed in v10.3.7
