### ISSUE TITLE
State: nodes incorrectly positioned on rerender

### ISSUE THREAD

**Issue by kinney** [wbkd/react-flow#220]
i calculate node positioning from my server and pass those nodes directly to a `Graph` component. 

when my nodes initially render, they are positioned correctly, but if i later pass a new set of nodes, the positioning is wrong -- the tree appears much larger and less dense, it's as if the x/y position for each node gets multiplied by some number. if i then refresh my page, my nodes appear positioned correctly again. 

i understand `react-flow` manages internal position state - i'm wondering if something isn't getting cleared on rerender?

i suspect i could get around the problem if i had the ability to reset position state before passing `Graph` new elements.

in case you aren't sure what's going on, i'll keep poking to see if i can identify the root cause.

thanks!

**Comment by moklick** [comment]
You are right. We only check if there are changes in the data option of a node. I need to figure out how we can solve this.

**Comment by krizka** [comment]
My 5 cents to this. 
`useElementUpdater` should have dependencies on useEffects, like [elements]
also, it calling very often from parent on it's update.

**Comment by moklick** [comment]
Hey @kinney 

we are now also apply style and position changes to the nodes. I added a "change pos" button to the basic example https://react-flow.netlify.app/basic

Could you check if the new version works for you?

**Comment by krizka** [comment]
@moklick thank you!

**Comment by kinney** [comment]
awesome - thank you!

the main issue is fixed. one related thing - if i zoom out and switch between positions, my tree similarly appears larger and less dense than it should. i realize this may be a different root cause (or maybe even intended behavior?). happy to create a new issue if you'd prefer.  here's a slightly modified example that makes it easier to see:

https://gist.github.com/kinney/8df18b69a4c319936a800c145c2679ed

(+1 on great lib!)

**Comment by moklick** [comment]
@kinney thanks for reporting this bug! It should be fixed in v1.3.5.

**Comment by kinney** [comment]
amazing - it's all working great. thank you!

**Comment by ashokslsk** [comment]
> Hey @kinney
> 
> we are now also apply style and position changes to the nodes. I added a "change pos" button to the basic example https://react-flow.netlify.app/basic
> 
> Could you check if the new version works for you?
> 
> Thanks @krizka we changed that!

Link not working

**Comment by moklick** [comment]
Thanks @ashokslsk  I updated the link

**Comment by steinhardt21** [comment]
> Thanks @ashokslsk I updated the link

The link is not working again. Can you fix it please?

**Comment by moklick** [comment]
this is the link: https://react-flow-dev.netlify.app/basic
