### ISSUE TITLE
React flow adding name to different dynamic edges

### ISSUE THREAD

**Issue by Samiullah110** [wbkd/react-flow#2204]
### Describe the Bug

I want to add an Input field to different edges and name that single edge accordingly I have already tried custom edges but it is not showing the input on the edge. any solution for this
?  

### Steps to Reproduce the Bug or Issue

![SC1](https://user-images.githubusercontent.com/69460086/172319010-de1e6801-7371-4c52-913e-a2bd82124d80.png)

### Expected behavior

I expected to show a name on different edges

### Screenshots or Videos

![SC1](https://user-images.githubusercontent.com/69460086/172318880-cf097a9f-258f-42a7-9f77-acb1162d700c.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey! Could you provide a codesandbox or repo for this?

**Comment by Samiullah110** [comment]
> 

``

> Hey! Could you provide a codesandbox or repo for this?

import React, { useEffect, useMemo } from 'react';
import logo from './logo.svg';
import './App.css';
import { useCallback, useState } from 'react';
import ReactFlow, {
  MiniMap,
  Controls,
  applyEdgeChanges,
  applyNodeChanges,
  addEdge,
  ReactFlowProvider,
  useReactFlow,
  useEdgesState
} from 'react-flow-renderer';
import ColorSelectorNode from './Components/CustomNodeSelector';
import CustomNodeSelectorOpr from './Components/CustomNodeSelectorOpr';
import AddComponent from './Components/AddComponent'
import { v4 } from "uuid"
import nextId from "react-id-generator";
import Edgetype from './Components/Edgetype';
import ConnectionLine from './Components/ConnectionLine';
function App() {
  const nodeTypes2 = useMemo(
    () => ({
      selectorNode: ColorSelectorNode,
      selectorNode2: CustomNodeSelectorOpr ,
      selectorNode3: AddComponent
    }),
    []
  );
   const edgeTypes = {
    custom: Edgetype,
   };
   let nodeId = 0;
  const addComponent = useCallback((nameofNode, typeofNode, checkNode,finalEdge) => {
    // setIsModalVisible(true);
    dara=true
    let id = `${++nodeId}`;
    const newNode = {
    
       type: 'selectorNode2',
      id,
      position: {
        x: Math.random() * 500,
        y: Math.random() * 500,
      },
      data: {
        label: `${nameofNode}`,
      },
      style: {
        background:'#ffff',
        color: '#ffff',
        //  border: '1px solid #222138',
        width: 240,
        borderRadius:  '6px',
     
      },
    };
    reactFlowInstance.addNodes(newNode);

    // setIsDrawer(true)


   }, []);
const initialNodes = [];
 const [nodes, setNodes] = useState(initialNodes);
const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const onNodesChange = useCallback(
    (changes) => setNodes((nds) => applyNodeChanges(changes, nds)),
    [setNodes]
  );
  const onConnect = useCallback(
    (connection) => setEdges((eds) => addEdge({ ...connection, }, eds)),
    [setEdges]
  );
const reactFlowInstance = useReactFlow();

  const rfStyle = {
    backgroundColor: '#f3edeb',
  };
 return (

    <div style={{ width: '100%', height: '100vh' }} className="App">

      <button
        onClick={addComponent}
        className='add-new-node-button'
        style={{
          marginTop: '1%', marginLeft: '10%',
          border: '2px solid #85bf31', padding: '5px',
          backgroundColor: '#85bf31', color: 'white', borderRadius: '4px'
        }}>
        Add New Component
      </button>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        onNodeClick={onDeleteNode}
        style={rfStyle}
        nodeTypes={nodeTypes2}
        edgeTypes={edgeTypes}
        connectionLineComponent={ConnectionLine}

      />
   </div>
  );
}

export default App;

this is the edge typeComponent(Custom)
import { Input } from 'antd';
import React from 'react';
import { getBezierPath, getMarkerEnd } from 'react-flow-renderer';

export default function Edgetype({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  style = {},  
  markerEnd,
}) {
  const edgePath = getBezierPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });

  return (
    <>
      <path
        id={id}
        style={style}
        className="react-flow__edge-path"
        d={edgePath}
        markerEnd={markerEnd}
      />
      <text>
        <textPath
          href={`#${id}`}
          style={{ fontSize: '12px' }}
          startOffset="50%"
          textAnchor="middle"
        >
         <hello>disabled</hello>
        </textPath>
      </text>
     
    </>
  );
}

**Comment by Samiullah110** [comment]
> Hey! Could you provide a codesandbox or repo for this?
Is it Possible to open a modal on onClick on the edge and name that edge?

**Comment by moklick** [comment]
One thing: You need to wrap your `edgeTypes` with a `useMemo` or define them outside of the component. 

I can't see how this is an issue with React Flow. Where is your implementation that doesn't work?

**Comment by Samiullah110** [comment]
> One thing: You need to wrap your `edgeTypes` with a `useMemo` or define them outside of the component.
> 
> I can't see how this is an issue with React Flow. Where is your implementation that doesn't work?

@moklick The problem has been solve, Thanks.

**Comment by Samiullah110** [comment]
> > One thing: You need to wrap your `edgeTypes` with a `useMemo` or define them outside of the component.
> > I can't see how this is an issue with React Flow. Where is your implementation that doesn't work?
> 
> @moklick The problem has been solved, Thanks.

**Comment by moklick** [comment]
great!
