### ISSUE TITLE
Error in collaborative (pro) example

### ISSUE THREAD

**Issue by ysds** [wbkd/react-flow#2209]
### Describe the Bug

I seem to get an error with [the collaborative example](https://reactflow.dev/docs/examples/interaction/collaborative/).
Could you please check it?

### Steps to Reproduce the Bug or Issue

1. Go to https://reactflow.dev/docs/examples/interaction/collaborative/

### Expected behavior

The example is displayed correctly

### Screenshots or Videos

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/4065765/172748368-d7dcdcdc-6856-49d2-acf1-cccf5ebe3233.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/4065765/172748762-8165fbe4-e1b4-41d2-8475-17cfb9eaae35.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 101.0.4951.54

**Comment by moklick** [comment]
I can't reproduce this issue 🤔

**Comment by ysds** [comment]
Certainly this issue does not seem to occur now.

If, as in the other example, there are users who can edit live code in sandpack, they might break the yjs sync data with the wrong code.

**Comment by moklick** [comment]
ahh :D that's a good point. We will remove the edit button for that example. Thanks for the hint 👌
