### ISSUE TITLE
zoomActivationKeyCode type doesn't allow null as value

### ISSUE THREAD

**Issue by alessandropisu** [wbkd/react-flow#2211]
### Describe the Bug

zoomActivationKeyCode prop doesn't allow _null_ as value to disable the functionality, while the documentation says that is possible to set it to _null_.

### Steps to Reproduce the Bug or Issue

1. Set _zoomActivationKeyCode_ value as null

### Expected behavior

To be able to set _zoomActivationKeyCode_ null

### Platform

- OS: macOS
- Browser: Chrome
- Version: 10.3.6

**Comment by moklick** [comment]
Thanks. Fixed in 10.3.7
