### ISSUE TITLE
Passing Nodes and Edges down into the component doesn't work

### ISSUE THREAD

**Issue by jdavis-software** [wbkd/react-flow#2213]
### Describe the Bug

**Problem:** Passing nodes and edges down into a component will not draw edges to my nodes... and gives the following error.

**Error:** [React Flow]: Couldn't create edge for target handle id: undefined; edge id: e103-107, [Reference Link](https://reactflow.dev/docs/guides/troubleshooting/#couldnt-create-edge-for-sourcetarget-handle-id-some-id-edge-id-some-id).

Why doesn't this work as expected...

### Your Example Website or App

https://codesandbox.io/s/restless-platform-uobo6b?file=/src/App.js

### Steps to Reproduce the Bug or Issue

Run the code sandbox

### Expected behavior

The nodes and edges would render as they do in the example.

### Screenshots or Videos

**Edges:**
<img width="1227" alt="edges" src="https://user-images.githubusercontent.com/21320194/172966340-cfc8eb73-d0c3-4a65-b101-f29fb4437714.png">

**Nodes:**
<img width="1225" alt="nodes" src="https://user-images.githubusercontent.com/21320194/172966344-2a12dd08-cc31-4e19-aacc-71c015ee0994.png">

**Rendered:**
<img width="400" alt="again" src="https://user-images.githubusercontent.com/21320194/172964894-99e962c1-be48-4bfb-a122-f1ae0e30289f.png">

**Error:**
<img width="1290" alt="Screen Shot 2022-06-09 at 5 24 50 PM" src="https://user-images.githubusercontent.com/21320194/172966434-060fd833-a159-4092-a5f8-a769b98b218b.png">

### Platform

Mac  (latest)
Chrome (latest)

**Comment by zyh374892663** [comment]
Grammatical errors
error
```
const ReactFlowRender = (initialNodes, initialEdges) => {}
```
success
```
const ReactFlowRender = ({nodes: initialNodes, edges: initialEdges}) => {}
```

**Comment by moklick** [comment]
Hey @jdavis-software 

I get an error `e.forEach is not a function` when I try to run your codesandbox.
