### ISSUE TITLE
Unable to wheel scroll on overflowed custom node

### ISSUE THREAD

**Issue by whilelfo** [wbkd/react-flow#2215]
### Describe the Bug

Unable to wheel scroll on overflowed custom node
if zoomOnScroll={true}, flow is zoomed
if zoomOnScroll={false}, nothing happens at all

### Your Example Website or App

https://codesandbox.io/s/react-flow-scroll-problem-u4m98l

### Steps to Reproduce the Bug or Issue

1. Go to the informed codesandbox
2. Try to wheel scroll the overflowed custom node
3. If you will, change zoomOnScroll to true, and try again

### Expected behavior

Somehow be able to wheel scroll the overflowed custom node

### Platform

- OS: Windows
- Browser: Chrome and MS Edge
- Version: Chrome: 102.0.5005.115 (Official Build) (64-bit)
                MS Edge: 102.0.1245.39 (Official Build) (64 bits)

**Comment by whilelfo** [comment]
Added className="nowheel" to the overflowed custom node, as described at https://reactflow.dev/docs/api/nodes/custom-nodes/#allow-scrolling-inside-a-node
and it worked.

**Comment by bqle** [comment]
Absolutely beautiful

**Comment by rtr-dnd** [comment]
To prevent panning to stop suddenly when hovered on scrollable contents, this worked for me.

```
const [nowheelClassName, setNoWheelClassName] = useState('scrollable');
const onMoveStart = useCallback(() => {
  setNoWheelClassName('scrollable_disabled');
}, []);
const onMoveEnd = useCallback(() => {
  setNoWheelClassName('scrollable');
}, []);

...

<ReactFlow
  ...
  panOnScroll
  panOnScrollSpeed={1.0}
  panOnDrag={false}
  noWheelClassName={nowheelClassName}
  onMoveStart={onMoveStart}
  onMoveEnd={onMoveEnd}
>
```

**Comment by matthewvines1** [comment]
> Added className="nowheel" to the overflowed custom node, as described at https://reactflow.dev/docs/api/nodes/custom-nodes/#allow-scrolling-inside-a-node and it worked.

While this works, that now prevents ctrl + mouse wheel to zoom
