### ISSUE TITLE
Use onNodesChange to change nodes, causing nodes to be overwritten

### ISSUE THREAD

**Issue by zyh374892663** [wbkd/react-flow#2220]
### Describe the Bug

When using onNodesChange to change the nodechange of type reset, the existing nodes are overwritten by the item of the reset nodechange

### Steps to Reproduce the Bug or Issue

1. During initialization, map nodes and edges to the source data and cache them
2. After connecting, remap the nodes and edges, compare the cached data, find out the node that needs to be changed, and set the nodechanges array (because the custom data will carry some necessary data, the node needs to be reset)
3. Process nodechanges through onNodesChange

### Expected behavior

The original number of nodes remains unchanged, and the data data of the corresponding node in the reset is updated

### Screenshots or Videos

Uploading 20220615_103320.mp4…

### Platform

- OS: Windows
- Browser: Electron
- Version: ^10.3.4

**Comment by zyh374892663** [comment]
Replenish：During initialization, the nodes are mapped out through the source data, and then converted into nodechanges through nodes, and new nodes are added through onNodesChange
![image](https://user-images.githubusercontent.com/33707926/173725824-d2be878b-ee24-4d66-90e6-801162b8c846.png)
![image](https://user-images.githubusercontent.com/33707926/173724632-b200ec40-9333-48d1-a5f0-4dd1f26de121.png)
![image](https://user-images.githubusercontent.com/33707926/173724710-7b2698d7-c56b-423c-a3d5-7776ab06f2d4.png)
![image](https://user-images.githubusercontent.com/33707926/173724885-9ac95d6d-091b-435f-93db-1e4e344e4205.png)
![image](https://user-images.githubusercontent.com/33707926/173724855-6484e9a2-1745-4371-a86c-8d152c67132c.png)
![image](https://user-images.githubusercontent.com/33707926/173725006-8b197749-eeb5-4502-bef5-ba5b428defb2.png)
![image](https://user-images.githubusercontent.com/33707926/173725683-2f45319c-72d6-4537-9604-1127c3f21262.png)
![image](https://user-images.githubusercontent.com/33707926/173725649-ee49252f-05fe-49f5-bd21-a90ec7e2090c.png)
![image](https://user-images.githubusercontent.com/33707926/173725734-7a46c61c-4669-42c7-bf8b-f0056422f209.png)

**Comment by zyh374892663** [comment]
The problem may be here: after filtering nodeChanges, return directly, elements give up directly
![image](https://user-images.githubusercontent.com/33707926/173752857-a0076b08-4f4e-4552-b63b-4678ce01a9f4.png)

**Comment by moklick** [comment]
Hey @zyh374892663 

thanks for the report. Could you explain the issue here? Sorry, but I don't get it.

**Comment by zyh374892663** [comment]
@moklick 
This picture is ugly, please forgive m
![无标题](https://user-images.githubusercontent.com/33707926/174214162-2baa24d0-8b4d-4682-b12c-d6282571b9c4.png)
e

**Comment by moklick** [comment]
Thanks for the explanation but I think a codesandbox would be more helpful here. Could you create a simplified example?

**Comment by zyh374892663** [comment]
@moklick https://codesandbox.io/s/elastic-surf-zocuhj?file=/src/ReactFlow.js 
This is an online demo, hope it helps

**Comment by moklick** [comment]
What are you trying to achieve here? Normally you don't need to care about node changes and you don't need to trigger them. They are meant to be used by the library to communicate changes to user land. In you case you could do something like: 

```js 
const add = (nodeId) => {
  setNodes(nds => nds.map((node) => {
    if (node.id === nodeId) {
      node.data = {
        ...node.data,
        count: node.data.count + 1;
      };
    }

   return node;
  }));
}
```

**Comment by zyh374892663** [comment]
@moklick 
For example: if `current` needs to be displayed on the node title, the `current` that simply modifies the source data cannot be updated to the view, and it is expected to update the current node through `reset`
```js
export function sourceMapNode(source) {
  return source.map((item) => {
    return {
      id: item.id,
      type: "new-node",
      data: {
        label: "id: " + item.id + ", current:" + item.count,
        count: item.count
      },
      position: item.position
    };
  });
}
```
Examples are updated, please follow the TODO comments

**Comment by zyh374892663** [comment]
https://user-images.githubusercontent.com/33707926/174569073-ed939d0a-fe44-4923-9456-b420b803d823.mp4

**Comment by moklick** [comment]
using a change event from type `reset` is not the way to update nodes. You should use the `setNodes` function and not use the internal events for that kind of task.

**Comment by zyh374892663** [comment]
![image](https://user-images.githubusercontent.com/33707926/174706304-d537077d-e09c-4a89-9559-a623a856eca9.png)
As shown above, if `changes` contains `NodeAddChange`, `NodeRemoveChange`, `NodeResetChange` at the same time, it only takes effect for `NodeResetChange`
