### ISSUE TITLE
nodesDraggable not working as expected

### ISSUE THREAD

**Issue by TamaraPK** [wbkd/react-flow#2225]
### Describe the Bug

Hello :)

I am trying out ReactFlow for a feature but I am having issues with panning when there is large node/group. One cannot pan on drag (pan on scroll works fine). 

I hope you can help out.

Thank you,
Best regards,
Tamara

### Steps to Reproduce the Bug or Issue

When I try to set this by code using nodesDraggable=false, the lock icon changes from unlocked to locked as expected put the panning does not work (and the hand cursor is still there) as when it is done via the control.

### Expected behavior

When one uses the controls specifically the lock button (toggle interactivity) and changes it to the locked state (disable interaction), the panning works fine on drag (the hand cursor goes away and one can pan on drag).

### Platform

- OS: MacOS
- Browser: Chrome

**Comment by moklick** [comment]
Hey! Do you need to select the nodes? If not, you can also set `elementsSelectable={false}` and it should work as expected.

**Comment by TamaraPK** [comment]
> Hey! Do you need to select the nodes? If not, you can also set `elementsSelectable={false}` and it should work as expected.

Thanks! This works for now (version 1 of the feature is not interactive) but the thing is, that soon we will need it to become interactive. So I am guessing in that case one needs to change both values for toggling (nodesDraggable & elementsSelectable).

BTW thanks for the super fast response, I was trying all options all morning just to figure a way to make it work :'D

**Comment by moklick** [comment]
Yes. It's not possible to have a graph with selectable nodes that are not stopping the drag behaviour.

**Comment by Keanottesen** [comment]
@moklick are there no workarounds for this?
