### ISSUE TITLE
Controls and Minimap ignore classNames in production but not in dev

### ISSUE THREAD

**Issue by rayoverweij** [wbkd/react-flow#2228]
### Describe the Bug

When setting classNames directly on the `Controls` and `MiniMap` components, such as Tailwind classes in this example, they are applied in dev mode but overridden when creating a build.

For example:

```
<Controls className="bottom-4 bg-gray-10 shadow" />
```

gives in dev:
<img width="85" alt="image" src="https://user-images.githubusercontent.com/24462089/174319241-d5501ae4-a3eb-41ab-a159-285b4fbb0609.png">

and in prod:
<img width="82" alt="image" src="https://user-images.githubusercontent.com/24462089/174319305-bb798e1a-b57b-414f-bf8a-ff3793406f6f.png">

Hardly heartbreaking but still kinda odd.

### Steps to Reproduce the Bug or Issue

1. Add `<Controls>` and/or `<MiniMap>` to `<ReactFlow>`
2. Add some classes to the component
3. Make a production build

### Expected behavior

I expected the way classes are applied to these components to be consistent between development and production environments.

### Platform

- OS: Windows 11
- Browser: Chrome 102
- React Flow: v10.3.5

**Comment by moklick** [comment]
I am relatively sure that this is an issue with your build system. We don't do anything special here.

**Comment by moklick** [comment]
Please re-open if this issue still persists.

**Comment by MossPalmer-POL** [comment]
Did you find a solution? I am seeing the same thing.
