### ISSUE TITLE
Vertical scrollbar inside custom node does not work on mouse interaction

### ISSUE THREAD

**Issue by TamaraPK** [wbkd/react-flow#2229]
### Describe the Bug

We have nodes with content that can extend vertically. When one sets the container to have a max height and overflow y to scroll, you can see the scroll bar but you cannot interact with it using the mouse. In order to scroll down the node internal content, only the up and down arrows on keyboard works. Same happens if I use a third party panel with built-in scrolling.

### Steps to Reproduce the Bug or Issue

1. Create custom node
2. Add long text content with container having max height and overflow y scroll.

### Expected behavior

To be able to have inner scroll and interact with it mouse and keyboard (and possible touch).

### Platform

- OS: macOS
- Browser: Chrome and Firefox

**Comment by moklick** [comment]
try to add the class `nowheel` to the container in your custom node.

**Comment by whilelfo** [comment]
Possible duplicate of #2215

**Comment by TamaraPK** [comment]
@moklick @whilelfo  nowheel solves part of the problem (now i can scroll inside the node using the scroll gesture e.g. on touch pad). Thank you for helping out with this. However, I am still not able to interact with the scrollbar using the mouse (i.e. click and hold the bar and drag it to scroll up and down). Is there a way to make this work too?

**Comment by TamaraPK** [comment]
Closing issue. Thanks again!

**Comment by krishnapraveen7** [comment]
Beautiful. Chefs kiss

**Comment by favger** [comment]
@moklick thanks!!

**Comment by tombowman12** [comment]
> try to add the class `nowheel` to the container in your custom node.

Thanks!

**Comment by ghost** [comment]
Absolutely beautiful! Thank you!
