### ISSUE TITLE
OnConnectStop doesn't access the external state correctly

### ISSUE THREAD

**Issue by mdmag** [wbkd/react-flow#2230]
### Describe the Bug

OnConnectStop doesn't access the external state correctly. It doesn't trigger changes in external state immediately. 
It seems that it is memoized by some dependencies only.

### Steps to Reproduce the Bug or Issue

I will provide codesandbox if needed.

### Expected behavior

onConnectStop should access the external state correctly.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by louis-cf-lin** [comment]
This also occurs with `onDragStop`. The function passed to `onDragStop` retains the external state at the time that dragging starts, instead of when the drag stop function is triggered.

**Comment by moklick** [comment]
the connect and drag handlers should work as expected with v10.3.11.
