### ISSUE TITLE
Group node children's extent positions are no longer relative

### ISSUE THREAD

**Issue by joeyballentine** [wbkd/react-flow#2232]
### Describe the Bug

I explained this issue on discord already https://discord.com/channels/771389069270712320/859774873500778517/987177142112645140

But basically a recent update made child node extents no longer relative positioning, and instead are absolute positioned. So if you set an extent to [[0, 100], [0, 100]], isntead of being a 100x100 box in the group node, its a 100x100 box relative to the canvas, regardless of where you move the group.

Codesandbox: https://yxwsfh.csb.app/

### Your Example Website or App

https://yxwsfh.csb.app/

### Steps to Reproduce the Bug or Issue

Set an extent that isn't just 'parent' and it will be very obvious what's wrong 

### Expected behavior

The extent should be relative to the parent group node, but constrained in the area you set 

### Platform

- Version: most recent

**Comment by moklick** [comment]
thanks @joeyballentine ! Fixed in v10.3.8
