### ISSUE TITLE
Resize example code does not work well with React 18

### ISSUE THREAD

**Issue by hgeldenhuys** [wbkd/react-flow#2233]
### Describe the Bug

I copied and pasted the example code, tried running it and the resize effects are jerky and not very responsive.

### Your Example Website or App

https://stackblitz.com/edit/react-ts-eqeek3?file=index.html

### Steps to Reproduce the Bug or Issue

Copy paste example code into new React 18 app

### Expected behavior

Nodes should resize smoothly

### Platform

- OS: MacOS
- Browser: Chrome
- Version: latest

### Additional context

I think it has to do with the new way useEffect works... mounting twice

**Comment by chrtze** [comment]
Thanks for reporting, I'll look at this asap.

**Comment by chrtze** [comment]
This should be fixed in the current version of the example. Please let me know if there are still issues with React 18.
