### ISSUE TITLE
Resize and Rotate example's select div not positioned correctly

### ISSUE THREAD

**Issue by hgeldenhuys** [wbkd/react-flow#2234]
### Describe the Bug

The select div for a node is offset incorrectly in the resize and drag example. This side-effect leaves a clickable div so selection of nodes interfere with other nodes that overlap this div

### Your Example Website or App

https://stackblitz.com/edit/react-ts-baealr?file=App.tsx

### Steps to Reproduce the Bug or Issue

Copy-paste the example code

### Expected behavior

The selected div should not interfere with other nodes' selection 

### Screenshots or Videos

<img width="730" alt="image" src="https://user-images.githubusercontent.com/179999/174680881-19eb1de4-f621-40f4-b099-05d228a01cd7.png">

### Platform

- Browser: Chrome latest
- reactflow latest

**Comment by chrtze** [comment]
#2156 https://github.com/wbkd/react-flow/issues/2156

**Comment by chrtze** [comment]
#2156

**Comment by mlndshh** [comment]
Any update on this? I'm trying to implement resizing to my custom nodes and running into this issue as well. Thanks

**Comment by chrtze** [comment]
This will be fixed with the release of v11.

**Comment by chrtze** [comment]
This is fixed in the new version of the Pro example: https://reactflow.dev/docs/examples/nodes/resize-rotate/
