### ISSUE TITLE
Active selection multiselection box doesn't always appear after dragging a multiselection box across nodes

### ISSUE THREAD

**Issue by emik** [wbkd/react-flow#2235]
### Describe the Bug

When dragging a multiselection box over nodes, sometimes the multiselection occurs and the nodes become highlighted and you can drag the selected nodes around, but the box that normally shows up does not. I believe this primarily happens when you do a fairly quick selection.

### Your Example Website or App

https://reactflow.dev/docs/examples/overview/

### Steps to Reproduce the Bug or Issue

1. Go to any react flow example 
2. Shift click multiselect quickly around multiple nodes
3. Sometimes the post-selection active selection box does not show

### Expected behavior

As a user I expect the post-multiselection active selection box to show.

### Screenshots or Videos

https://user-images.githubusercontent.com/2894097/174695554-4b9493dc-7c2a-4fc5-9a79-d8d35e8a8013.mp4

### Platform

- OS: Windows
- Browser: Chrome
- Version: 102.0.5005.115

**Comment by moklick** [comment]
Your mouse is outside of the pane when you release the button. You can't reproduce this on a full screen pane so I wouldn't call it an issue.

**Comment by emik** [comment]
Ah yes that explains it, thanks @moklick . It's still an issue for users of my app though because use of fullscreen is secondary usage. Is there a simple way of forcing the selection rectangle to show up when multiple things are selected like that?

**Comment by emik** [comment]
@moklick after testing, it even happens in fullscreen mode when the attribution is present (dragging over the attribution cancels the selection drag). This would also be the case with any overlays e.g. menus.
