### ISSUE TITLE
Cannot assign to read only property 'selected' of object

### ISSUE THREAD

**Issue by SergioTx** [wbkd/react-flow#2240]
### Describe the Bug

When I added a onSelectionChange function a new error started happening after the first selection of nodes.

```ts
 const onSelectionChange: OnSelectionChangeFunc = useCallback(
    (params) => {
      dispatch(selectionChanged(params));
      return params;
    },
    [dispatch]
  );

 return (<ReactFlow
  onSelectionChange={onSelectionChange}
  multiSelectionKeyCode={null} // disable ctrl/meta selection
  {/* ... */}
/>);
```

### Steps to Reproduce the Bug or Issue

1. Add onSelectionChange property with a useCallback calling redux.
2. Shift drag to select a few nodes.
3. Click outside to unselect.
4. Shift drag again.

### Expected behavior

It's an internal function changing an internal property, it should not happen.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/22587994/175275242-817c6cc2-2ebd-4d11-81c9-aaedaf03c323.png)

### Platform

- OS: macOS Monterrey 12.4
- Browser: Chrome
- Version: 102.0.5005.115 (Official Build) (x86_64)

**Comment by SergioTx** [comment]
I realized that this is caused by adding the state directly to redux, making it an inmutable object. My bad.

**Comment by goliney** [comment]
Why it's considered wrong? React-flow recommends using state management and it's common practice to make store immutable. I don't get it.

**Comment by bcakmakoglu** [comment]
@goliney If the state is immutable you can't start reassigning properties on object in that state - so there's nothing wrong with having an immutable state, there's something wrong with trying to mutate objects in that state.
