### ISSUE TITLE
Node level problem

### ISSUE THREAD

**Issue by zyh374892663** [wbkd/react-flow#2242]
### Describe the Bug

The selected node should be in the upper layer, and the unselected node should be in the lower layer. When the focus is lost, the hierarchical relationship is not maintained

### Your Example Website or App

https://reactflow.dev/docs/examples/nodes/update-node/

### Steps to Reproduce the Bug or Issue

When part of the area of two nodes overlaps, select the lower node, the node will float to the upper layer, when the node is deselected, the node will return to the lower layer

### Expected behavior

The selected hierarchy should be maintained

### Screenshots or Videos

![20220624_111818](https://user-images.githubusercontent.com/33707926/175455778-c817f11a-50de-4966-9aad-7ca316cffe4d.gif)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [^10.4.7]

**Comment by moklick** [comment]
I understand that this might not perfect for everyone but this is the expected behaviour. Nodes are always displayed in the order you pass them to React Flow. If you want to change the hierarchy, you need to sort them.
