### ISSUE TITLE
ZoomPane freezes but still pans when selection key is pressed during pan

### ISSUE THREAD

**Issue by potrepka** [wbkd/react-flow#2244]
### Describe the Bug

Pressing the selection key (default: Shift) while panning causes the `ZoomPane` to not update even though it is still panning. Viewport will "jump" once the selection key is released.

Perhaps this can be fixed by replacing `selectionKeyPressed` `ZoomPane` property with `nodesSelectionActive`?

### Steps to Reproduce the Bug or Issue

1. Begin left mouse drag to start panning.
2. Press the selection key (default: Shift).
3. Release the left mouse button.
4. Release the selection key.
5. Press left drag again, and observe the viewport "jump".

OR

1. Begin left mouse drag to start panning.
2. Press the selection key (default: Shift).
3. Release the selection key.
4. Continue left mouse dragging, and observe the viewport "jump".

### Expected behavior

The `ZoomPane` should not freeze unless node selection becomes active, which does not happen when the user is panning.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 102.0.5005.115

**Comment by moklick** [comment]
Thanks! Fixed in v10.3.9
