### ISSUE TITLE
Edge drawing is not updated during edge update

### ISSUE THREAD

**Issue by ysds** [wbkd/react-flow#2245]
### Describe the Bug

If the connection mode is set to loose, the edge being dragged may not be displayed during edge update.

### Steps to Reproduce the Bug or Issue

1. Go to https://reactflow.dev/docs/examples/edges/updatable-edge/
2. Add `connectionMode="loose"` to the `<ReactFlow>`
3. Reload the right result view.
4. Update edges

### Expected behavior

Edges are drawn correctly while draggin

### Screenshots or Videos

https://user-images.githubusercontent.com/4065765/175919005-bf73b7a8-a21f-43ec-9d04-75562ba77de7.mov

### Platform

- OS: [macOS]
- Browser: [Chrome]

**Comment by moklick** [comment]
Thanks for the report. It seems to be an issue with source -> source and target -> target connections. I'll check how we can fix it.

**Comment by ysds** [comment]
I've confirmed this issue does not occur in 11.3.
