### ISSUE TITLE
`onNodeClick` prop prevents nodes from being locked

### ISSUE THREAD

**Issue by louis-cf-lin** [wbkd/react-flow#2247]
### Describe the Bug

When a function is passed to `onNodeClick`, it prevents `pointer-events: none` from being applied. 

I have `nodesDraggable=false`, `nodesConnectable=false`, and `elementsSelectable=false` and expect `pointer-events: none` on all nodes. However, `onNodeClick` is preventing this. When I don't set `onNodeClick` or set it to `undefined`, the issue is fixed.

In my opinion, `nodesDraggable`, `nodesConnectable`, `elementsSelectable` and other interactive props should override `onNodeClick`, as is currently the case with all other event handler props.

Would be good to have this resolved or get an explanation for the current behaviour. Thanks!

### Steps to Reproduce the Bug or Issue

1. Pass any function to `onNodeClick`
2. Set `nodesDraggable=false`, `nodesConnectable=false`, `elementsSelectable=false`

### Expected behavior

When the interactive properties are set to `false`, I expect to be able to pan around by dragging on the background or the nodes themselves. The nodes should not be selectable, should not move, and should allow panning when clicked on and dragged.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey! This was the behaviour in a previous version. We changed it, because users expect the `onNodeClick` event to work when they pass it. With `pointer-events: none` this wouldn't work and it feels broken. Does this answer your question?

**Comment by louis-cf-lin** [comment]
@moklick Gotcha, thanks for the info!

For anyone looking for a solution, I've just set
```ts
onNodeClick={isEditing ? onNodeClick : undefined}
```

**Comment by croissantspectacular** [comment]
Could this be re-opened please? I'm in a very similar problem. I need to enable the click functionality, while at the same time also having disabled the nodesDraggable, nodesConnectable and elementsSelectable configurations (so the later fix given by louis wouldn't help in my case). Any ideas?
