### ISSUE TITLE
Custom node's input element doesn't auto focus upon node creation.

### ISSUE THREAD

**Issue by bsaranga** [wbkd/react-flow#2258]
### Describe the Bug

I have a custom node with an input element within it. I would like to autofocus on the input element when the node is first created. I have taken the callback ref approach here, but earlier I tried `useRef` along with `useEffect`; no luck there as well.

`const inputRef = useCallback((ref: HTMLInputElement) => {
    if (ref != null) {
      ref.focus();
    }
  }, []);`
  
  Please refer to my minimal example.
  
  Thanks.

### Your Example Website or App

https://codesandbox.io/s/admiring-wave-ul6zei?file=/src/CustomNode.tsx

### Steps to Reproduce the Bug or Issue

1. Click on 'Add Node' button.
2. Verify that the input element in the node doesn't get focused upon creation.

### Expected behavior

Input element should get focused.

### Platform

- OS: [WSL2 Windows 10]
- Browser: [Chrome]
- Version: [latest]

**Comment by bsaranga** [comment]
Using a class component for the custom node resolved my issue.

**Comment by Saraphite** [comment]
I'm not entirely well versed with React enough to know why a class component would have worked vs a functional one - but it doesn't seem right that that's the correct fix. Are there any other resolutions to this issue? I'd prefer to not convert this node over to a class component while the others remain functional components just because I want to autofocus on the text input field after creation.

**Comment by miguoliang** [comment]
I have the same trouble, and I can't fix it by a class component. Could you update the code in your sandbox? Thank you! @bsaranga

**Comment by miguoliang** [comment]
> I have the same trouble, and I can't fix it by a class component. Could you update the code in your sandbox? Thank you! @bsaranga

I fixed that by hook `useNodesInitialized`. The function component works fine.

**Comment by dglazkoff** [comment]
In my case I was still catching the problem with input focus, but it helped me to useLayoutEffect and requestAnimationFrame. maybe React.StrictMode also affects it.

```
  useLayoutEffect(() => {
    if (nodesInitialized && inputRef.current) {
      inputRef.current.focus({ preventScroll: true });

      const id = requestAnimationFrame(() =>
        inputRef.current?.focus({ preventScroll: true }),
      );

      return () => cancelAnimationFrame(id);
    }
  }, [nodesInitialized]);
```
