### ISSUE TITLE
Detect changes when navigating with keyboard

### ISSUE THREAD

**Issue by ShahriarKh** [wbkd/react-flow#2261]
### Describe the Bug

I have a custom edge, which has an input. When I click on the input, or when I click outside the, the `onEdgesChange` can correctly detect which edge is `selected: true` and which one is not. However, when I use <kbd>Tab</kbd> to move through inputs, it seems like that `onEdgesChange` doesn't detect it and the previously selected edge stays `selected: true`.

Here's my code:
```jsx
 const onChange = (changes) => {
    console.log("edge change", changes);
    const selectionChange = changes.find(
        (change) => change.selected === true
    );
    if (selectionChange) {
        console.log(selectionChange);
        setEdges((currentEdges) => {
            return currentEdges.map((edge) => {
                if (edge.id === selectionChange.id) {
                    return { ...edge, animated: true };
                } else {
                    return { ...edge, animated: false };
                }
            });
        });
    } else {
        setEdges((currentEdges) =>
            currentEdges.map((edge) => ({ ...edge, animated: false }))
        );
    }
    onEdgesChange(changes);
};
```
###### Custom Edge
I'm using react-hook-form and some of the code is related to it.)
```jsx
import css from "./CustomEdge.module.scss";
import { getBezierPath, getBezierEdgeCenter } from "react-flow-renderer";
import { useFormContext } from "react-hook-form";
import { useEffect, useRef, useState } from "react";

const foreignObjectSize = 40;

export default function CustomEdge({
    id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    style = {},
    markerEnd,
}) {
    const { register, unregister } = useFormContext();

    const [isMounted, setIsMounted] = useState(false);

    useEffect(() => {
        setIsMounted(true);
        return () => {
            unregister(id);
            setIsMounted(false);
        };
    }, []);

    const edgePath = getBezierPath({
        sourceX,
        sourceY,
        sourcePosition,
        targetX,
        targetY,
        targetPosition,
    });

    const [centerX, centerY, offsetX, offsetY] = getBezierEdgeCenter({
        sourceX,
        sourceY,
        targetX,
        targetY,
        curvature: 0.25,
    });

    return (
        <>
            <path
                id={id}
                style={style}
                className="react-flow__edge-path"
                d={edgePath}
                markerEnd={markerEnd}
            />
            <foreignObject
                width={foreignObjectSize}
                height={foreignObjectSize}
                x={centerX - foreignObjectSize / 2}
                y={centerY - foreignObjectSize / 3.5}
                className="edgebutton-foreignobject"
                requiredExtensions="http://www.w3.org/1999/xhtml"
            >
                {isMounted && (
                    <input
                        className={css.cost}
                        {...register(id)}
                        defaultValue={1}
                    />
                )}
            </foreignObject>
        </>
    );
}
```

### Your Example Website or App

https://operations-research.vercel.app/transportation

### Steps to Reproduce the Bug or Issue

1. Go to the live version of the website
2. Click on an edge input (the input in the middle of the edge)
3. Click on another input, or click another part of the graph container
=> The selected edge is correctly detected and the line becomes animated

2. Click on an edge input
3. Use <kbd>Tab</kbd>  to navigate between edge inputs, or click another part of the page (outside the graph container)
=> The previously selected edge stays selected

### Expected behavior

`onEdgesChange` should detect keyboard events (and if possible, detect events outside the React Flow container. at least it should be able to detect loss of focus)

### Platform

- OS: Windows 10
- Browser: Firefox Developer Edition v103 + Chrome v103

**Comment by moklick** [comment]
The edges get selected because of the click event. If you also want to support to select edges via tab, you need to implement that by yourself. You could listen to the focus event and then set the corresponding edge to `selected:true` and the de-select the other ones.
