### ISSUE TITLE
Nodes are too far away from each other. How to reduce it?

### ISSUE THREAD

**Issue by naveenpaul** [wbkd/react-flow#2262]
### Describe the Bug

All my nodes are too far away from each other. How to reduce it?
Attaching screenshot for reference.

### Steps to Reproduce the Bug or Issue

Attaching screenshot

### Expected behavior

Attaching screenshot

### Screenshots or Videos

<img width="808" alt="Screenshot 2022-07-04 at 11 50 39 PM" src="https://user-images.githubusercontent.com/1685291/177203450-4706778f-9cb0-4ac7-93ad-9b27733323ed.png">

### Platform

- OS: Mac
- Browser: Chrome
- Version: 103.0.5060.53

**Comment by myatniy** [comment]
@naveenpaul do you use the auto layout algorithm?
