### ISSUE TITLE
React Flow not rendering correctly in Next JS application

### ISSUE THREAD

**Issue by AndrewWildDataJoey** [wbkd/react-flow#2269]
### Describe the Bug

When trying to use React Flow with Next JS, the React Flow component does not get rendered on the page. 
If I use the react-flow-renderer package, nothing gets rendered.
If I use the react-flow-renderer/nocss, I get strange shapes rendering on the page.
I've included my simple example in the GIT repo below and a screen recording of the shapes.

### Your Example Website or App

https://github.com/AndrewWildDataJoey/ReactFlowNextJSExample

### Steps to Reproduce the Bug or Issue

The repo above follows the basic example on the Next JS website: https://nextjs.org/learn/basics/create-nextjs-app/setup. 
I then installed ReactFlow using `yarn add react-flow-renderer`. 
The localhost:3000/reactflownextjs page then uses a simple example from the React Flow website.
If you keep clicking the buttons on the top right of the page, different shapes will be rendered.

### Expected behavior

As a user, I expected to see a simple example of React Flow with Next JS. However, the React Flow component does not get correctly rendered on the page.

### Screenshots or Videos

https://user-images.githubusercontent.com/100970470/177481946-4a8d51ff-8e65-4c17-8055-422e6294bb06.mov

### Platform

- OS: MacOS
- Browser: Chrome

### Additional context

Thanks!

**Comment by bcakmakoglu** [comment]
Pretty sure you forgot to import the necessary styles for React Flow to work.
If you're using the `nocss` version you need to import some styles (or overwrite them yourself) otherwise you will see the output above.

```
// you need these styles for React Flow to work properly
import 'react-flow-renderer/dist/style.css';

// additionally you can load the default theme
import 'react-flow-renderer/dist/theme-default.css';
```

Or just switch to the regular version and import from `react-flow-renderer` instead of `react-flow-renderer/nocss`

**Comment by AndrewWildDataJoey** [comment]
With the additional imports, nothing gets rendered on the page.

Here's what it looks like with 'react-flow-renderer/dist/style.css' and 'react-flow-renderer/dist/theme-default.css' added.

<img width="1605" alt="Screen Shot 2022-07-06 at 4 33 37 pm" src="https://user-images.githubusercontent.com/100970470/177484387-b0872edd-3603-4b36-8bb9-a75e920ff3c8.png">

If I use the react-flow-renderer package, nothing gets rendered either.

**Comment by bcakmakoglu** [comment]
Did you wrap your flow in a container with any height/width?
React Flow needs a container with a height/width otherwise you'll end up with a blank screen.
E.g.

```jsx
<div style={{ height: 300 }}>
	<ReactFlow ... />
</div>

**Comment by AndrewWildDataJoey** [comment]
Yep, that's fixed it. Thanks and sorry for the inconvenience!
