### ISSUE TITLE
On IE 11 and Edge SyntaxError: Expected identifier, string or number

### ISSUE THREAD

**Issue by SvetoslavSlavov** [wbkd/react-flow#227]
number  -2146827274
`SyntaxError: Invalid character  at ./node_modules/react-flow-renderer/dist/ReactFlow.esm.js `.  I'm using 1.3.2 version. Thank you for your help in advance. :)

**Comment by moklick** [comment]
Hey @SvetoslavSlavov,

for now IE11 is not supported. You might be able to get it run if you configure babel to transpile to es5 with Promises polyfilled.
