### ISSUE TITLE
Setting the viewport when minimized causes node/edge misalignment

### ISSUE THREAD

**Issue by joeyballentine** [wbkd/react-flow#2276]
### Describe the Bug

Initial discord conversation for context: https://discord.com/channels/771389069270712320/859774873500778517/995439004969353246

If the viewport gets set when the window is minimized, edges and nodes become misaligned. I have a useEffect that sets nodes, edges, and viewport to cached values when refreshing, and if I refresh, minimize, wait a bit, then open the window again, I can consistently get this bug. It does seem to be misaligned by the amount the viewport changed while minimized as well.

### Your Example Website or App

The current main version (not release version) of chaiNNer has this problem 

### Steps to Reproduce the Bug or Issue

1. Have code to set nodes, edges, and viewport on start/mount
2. Refresh page
3. Minimize page immediately after refresh
4. Wait a bit for refresh to finish 
5. Open the window back up

### Expected behavior

I would expect this to not happen 

### Screenshots or Videos

![unknown-12](https://user-images.githubusercontent.com/34788790/178284105-0f1a33f4-9a18-481f-9233-950c3d8e3313.png)

### Platform

- OS: windows
- Browser: chrome

**Comment by joeyballentine** [comment]
I'll try to recreate it in a codesandbox.

**Comment by joeyballentine** [comment]
https://nfj1y4.csb.app/

Refresh, minimize, wait, and open again. It'll be misaligned.

![image](https://user-images.githubusercontent.com/34788790/178313318-3b2daba8-e555-41a7-9383-73565c41654c.png)

**Comment by joeyballentine** [comment]
I believe the misalignment is caused by state batching from react 18. In that CSB I replaced the root rendering with the legacy version that does not batch state updates, and it was no longer misaligned (the viewport did lock up still though, at least until I put everything back in the setViewport and got rid of zoomTo).

**Comment by joeyballentine** [comment]
Yes I will test as soon as I can, which won't be until much later today.

**Comment by joeyballentine** [comment]
@moklick it does appear to be fixed now! The viewport locking up issue I mentioned (and replicated by doing that zoomTo) still happens though. But the edges thing is definitely fixed. Thanks!

**Comment by moklick** [comment]
Ok, that's good. I haven't looked into the `zoomTo` bug. Will do later!

**Comment by moklick** [comment]
Thanks! Fixed in v10.3.9.

1. We no longer rely on the zoom level for calculating the handle positions.
2. `setViewport` doesn't break anymore when you pass a part of a viewport.
