### ISSUE TITLE
edge don't adapte to screen resolution

### ISSUE THREAD

**Issue by Jasminou** [wbkd/react-flow#2281]
### Describe the Bug

Hi,

I'm using a dagre layout with custom node with svg icon's + custom edges.

I'm trying to make the react flow path fit the parent container. I guess FitView will help with that.

but I've another issue when the resolution of the screen change ( for example from 1080 P to 1440P) the svg icon used in the custom node will grow/decrease/zoom based on the resolution of the screen to keep a proprtional dimension. but for the edge it's another story. setting an edge width with dagre doesn't seems to allow the edge to adapte to the new screen dimensions. is there anyway to set min-width to the edge path so it can grow/reduce the edge width based on the availble space using dagre.

thanks 

### Your Example Website or App

https://reactflow.dev/docs/examples/layout/dagre/

### Steps to Reproduce the Bug or Issue

using https://reactflow.dev/docs/examples/layout/dagre/ with cutom resolution I can see that the level of zoom change.
but the edge width is still the same.

### Expected behavior

As user, I expect that the path can fit the parent container and the edge path should adapte to the resoutions using a min-width logic, so the path edge can't shrink less than the edge min-width but can grow to max-width if space is available.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey @Jasminou 

I didn't get the issue. When I change my resolution and zoom in this example https://reactflow.dev/docs/examples/layout/dagre/  everything works as expected. What do you mean "setting an edge width with dagre"?

**Comment by Jasminou** [comment]
thank you for your answer
I mean  graph.setEdge(source, target, { width: 50 });
in the example it looks like when we change the resolution of the browser the zoom level change but the edge with it still the same I want to know if it's possible to keep the same zoom level but change the width of the edge based on my current resolution for example width 50 it's okay for 1080 p but it's too small for 4K. or is there any hook that I can use to get the view port info and update my layout 

thank you again

**Comment by Jasminou** [comment]
@moklick here you can see the difference : 

for 1080 resoution:
<img width="805" alt="Screen Shot 2022-07-18 at 17 23 25" src="https://user-images.githubusercontent.com/14798195/179620019-20d3960f-d281-42cd-96e9-a8ad25743e90.png">

for 4k resolution:

<img width="805" alt="Screen Shot 2022-07-18 at 17 23 44" src="https://user-images.githubusercontent.com/14798195/179620072-60ecf134-c66d-4058-aaec-0b198d178af9.png">

the svg path don't adapt the new resolution so it looks super tiny compare to svg used in the custom node

**Comment by moklick** [comment]
Is this an issue with React Flow or dagre? Do you want to set a dynamic width based on the resolution? If so you could try to use the screen resolution (`window.screen.width * window.devicePixelRatio`) to calculate the width.
