### ISSUE TITLE
useReactFlow causes runtime error

### ISSUE THREAD

**Issue by jiun0507** [wbkd/react-flow#2284]
### Describe the Bug

When I run this line of code
`const { setViewport } = useReactFlow();` inside of my flowchart component,
it returns this error on the browser console, `Uncaught Error: Seems like you have not used zustand provider as an ancestor.`. Essentially, I am trying to use useReactflow API in order to manipulate the viewport, but I can't use it due to this error. If there is a solution or any other way or setting the x y coordinate of the viewport, please let me know.

### Steps to Reproduce the Bug or Issue

1. Create a react component for flowchart
2. Instantiate useReactflow API after importing from the 'react-flow-renderer'
import {useReactFlow} from 'react-flow-renderer'
3. npm start
4. render the component on the browser
5. check the browser console

### Expected behavior

I expect "Uncaught Error: Seems like you have not used zustand provider as an ancestor." error to show on the browser console.

### Screenshots or Videos

![Screen Shot 2022-07-12 at 11 17 26 AM](https://user-images.githubusercontent.com/22138357/178525210-7c434e36-dbde-4582-a92c-2efbd7e872d9.png)

### Platform

- macOS
- Firefox
- 91.10.0esr (64-bit)

**Comment by moklick** [comment]
Hey @jiun0507 

please check https://reactflow.dev/docs/guides/troubleshooting/#warning-seems-like-you-have-not-used-zustand-provider-as-an-ancestor
