### ISSUE TITLE
Add boolean prop to remove attribution, delete proOptions?

### ISSUE THREAD

**Issue by chrtze** [wbkd/react-flow#2288]
The attribution is causing confusion (how to remove it, when to show it, etc..). We want to clear this up in the next major release.

**Comment by keller35** [comment]
Hi @chrtze , how is it going? This determines whether we use it or not.

**Comment by chrtze** [comment]
Hey @keller35, we hope to release v11 in August.

**Comment by danielecaggiari** [comment]
@moklick It seems that `account` was (unintentionally?) reintroduced with https://github.com/wbkd/react-flow/commit/aef8b477c243638665ca407d6216cbea48bf8921.

**Comment by moklick** [comment]
It was intentionally in order to prevent another breaking change due to a type change but it should be optional. We will fix it. thanks @danielecaggiari
