### ISSUE TITLE
Performance issues when running in development mode

### ISSUE THREAD

**Issue by mirkolenz** [wbkd/react-flow#2289]
### Describe the Bug

When running my application locally, I experience severe lags when dragging nodes. When opening this issue, I deployed the app on Netlify and noticed that the performance problems are vanished. I have attached videos that show this issue. The deployed version is available at <https://react-flow--arguemapper.netlify.app>.

### Your Example Website or App

https://github.com/recap-utr/arguemapper/tree/react-flow

### Steps to Reproduce the Bug or Issue

1. Run the app locally.
2. Click on `Load Demo` on the right sidebar.
3. Move the nodes around on the canvas.

### Expected behavior

The expected behavior can be seen on the deployed version.

### Screenshots or Videos

https://user-images.githubusercontent.com/5160954/178964220-46fca166-2d9e-4bcb-9c0a-a646d9d4cd93.mp4

https://user-images.githubusercontent.com/5160954/178964304-45c1613c-1c1c-41ea-a7b3-5962b2f331b5.mp4

### Platform

- OS: macOS
- Browser: Safari (also happens with the newest version of Chrome, but to a much lesser extent)
- Version: 15.5

**Comment by mirkolenz** [comment]
I had the time to perform some additional investigation on this matter. The problem seems to be tied to the mode React is running in. If I set `NODE_ENV=production`, then the lags do also not occur when running locally.

My impression is that the lags are caused by updates to the viewports when the nodes are dragged by the user. Here is an error message that is shown after moving a node around for a few seconds:

`react-dom.development.js:86 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`

```txt
printWarning		@	react-dom.development.js:86
error			@	react-dom.development.js:60
checkForNestedUpdates	@	react-dom.development.js:27300
scheduleUpdateOnFiber	@	react-dom.development.js:25475
dispatchSetState	@	react-dom.development.js:17527
(anonymous)		@	Graph.tsx:131
updateNodePositions	@	slicedToArray.js:7
(anonymous)		@	useViewport.js:18
call			@	dispatch.js:57
gesture			@	drag.js:148
mousemoved		@	drag.js:71
(anonymous)		@	on.js:3
```

**Comment by moklick** [comment]
Hey @mirkolenz 

thanks for the additional information and the repo. I will see if I can find something. Does this happen with our examples as well or in your code base?

**Comment by mirkolenz** [comment]
@moklick I just cloned the [stress test example](https://reactflow.dev/docs/examples/nodes/stress/) to run it locally. I did not experience this problem at all: It is just as fluid as on the web page and the error regarding the maximum update depth is not thrown when dragging nodes around. So it seems to be something related to my codebase. I created my own context provider for managing states of the graph. Could "nested context providers" be related to this issue?

**Comment by moklick** [comment]
This is not an issue with React Flow. I would put the nodes and edges in a separate context or better use a library like Zustand. It's 1.1kb minified and gzipped and saves you a lot of work and headaches :D Right your context changes whenever you drag a node. That means that the `Inspector`component for example re-renders while you drag a node, even if it doesn't request the `nodes` array.

**Comment by mirkolenz** [comment]
Thank you for having a look. I migrated everything to Zustand and did not observe a major performance boost. What did the trick for me was to use a local state for the nodes. Now only the canvas is rerendered when dragging nodes.

Thank you so much for looking into my issue even though it was not caused by a bug in React Flow!

**Comment by moklick** [comment]
In most cases it's possible to achieve this even if the nodes and edges are stored in the global store. Only the components get re-rendered on drag where you import the nodes from the store. This isn't always necessary. There are two ways to prevent this.

1. You only need specific information of the nodes: Let's say you want to display the names of the nodes, then you could write a selector that only selects this information:

```js 
const nodeNames = useStore(s => s.nodes.map(n => n.data.name));
``` 

2. You need the nodes in an event handler: You can access the store with help of the `useStoreApi` without triggering re-renderings in an event handler for example:

```js 
const store = useStoreApi();

const onClick = () => {
  const { nodes } = store.getState();
  console.log(nodes);
}
```

**Comment by mirkolenz** [comment]
I am learning so many things, thank you 😃 

Just one question regarding `useStoreApi()`: Is this a special hook exposed by Zustand? I am only aware of the `set, get, api` utilities within a store but am unable to find references to `useStoreApi()`

**Comment by moklick** [comment]
We are using Zustand with a Provider (because there might be multiple RFs on a page or a user want to put the ReactFlowProvider somewhere higher in the tree) but if you are using Zustand the normal way you can just do:

```js 
const useStore = create(() => ({ nodes:[] }));

// somewhere in an event handler or useEffect
useStore.getState().nodes;
```

https://github.com/pmndrs/zustand#readingwriting-state-and-reacting-to-changes-outside-of-components

**Comment by mirkolenz** [comment]
Ah, ok. Thank you for the clarification. I will try to get rid of my "local" states with these tips 😄

**Comment by Pegasus2212** [comment]
Good Afternoon, Im using Redux Toolkit with react flow, and while using "onNodesChange" from the library itself in the store, the node lags like hell and if I use use useNodesState in the component itself then it works fine. Early help would really be appreciated.

**Comment by moklick** [comment]
@Pegasus2212 could you create a codesandbox for this?
