### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by bcburak** [wbkd/react-flow#2295]
### Describe the Bug

Hi all,

After downloaded all source code, I have mapped example folder and install all required npm packages.
While trying to build or start command I'm getting a module not found error. Any suggestion?
By the way ,even try to create new react template and use sample overview components, it has run but I see black pages with no error.

![image](https://user-images.githubusercontent.com/6598220/179289118-57bf37e5-222b-4fa2-a6b6-ac8cd6012694.png)

### Steps to Reproduce the Bug or Issue

1. example folder
2. npm install
3. npm run 
4. module not found error

### Expected behavior

run localhost page

### Screenshots or Videos

![Uploading image.png…]()

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows 10
Chrome
Latest version

**Comment by moklick** [comment]
You need to do `npm install` and `npm run build` or `npm start` (for developing) in the root folder as well.
