### ISSUE TITLE
If the node contains a textarea component, after selecting all the content through the shortcut key or js, the mouse clicks the selected area, and the selection state cannot be canceled

### ISSUE THREAD

**Issue by zyh374892663** [wbkd/react-flow#2297]
### Describe the Bug

If the node contains a textarea component, after selecting all the content through the shortcut key or js, the mouse clicks the selected area, and the selection state cannot be canceled

### Your Example Website or App

https://reactflow.dev/docs/examples/nodes/resize-rotate/

### Steps to Reproduce the Bug or Issue

1. textarea gets focus
2. Double-click the textarea content or drag the mouse to select, or select all by shortcut keys
3. Click on the selected area

### Expected behavior

I expect the select all to fail, the cursor is at the clicked position，but no response

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [^10.3.7]

**Comment by chrtze** [comment]
Hey, this example is a demo for how to implement the rotate and drag behaviour. If you want to have the textarea behave as usual, you can add the `nodrag` class to it which will prevent react flow from capturing events from that element.
