### ISSUE TITLE
Unable to center align the workflow in the document

### ISSUE THREAD

**Issue by jayanthbondi** [wbkd/react-flow#2326]
### Describe the Bug

I'm Unable to center align the Workflow in center.
Nodes are also not center aligned.
Could you please help me out.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-co2olb?file=/nodes-edges.js

### Steps to Reproduce the Bug or Issue

1.Open the Sandbox link and see the generated workflow.
2.You'll observe that Nodes are center aligned & workflow is also not center aligned in the document.

![image](https://user-images.githubusercontent.com/35721161/181778899-042218f0-8de8-4a4e-9ae5-b222d9c1cdcb.png)

### Expected behavior

As a user I'm expecting the workflow layout would be center aligned in the document at the same time Nodes also should be center aligned.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
This is not an issue with React Flow. The node anchor point is top left. If you want to center the nodes, in this case you need to do:

```js 
node.position = {
   x: nodeWithPosition.x - node.style.width / 2,
   y: nodeWithPosition.y
};
```

**Comment by jayanthbondi** [comment]
Hi @moklick ,
Thanks for the help, but still my workflow is not center aligned in the document.
Could you please suggest on that.

**Comment by frankdou** [comment]
> Hi @moklick , Thanks for the help, but still my workflow is not center aligned in the document. Could you please suggest on that.
> 
> I tried passing fitView as true, but that's increasing the width of nodes, so it doesn't help me.

In my case, need to wait for the wrapping div to fully appear before running the flow code.
