### ISSUE TITLE
How Can we get the children of a Node?

### ISSUE THREAD

**Issue by jayanthbondi** [wbkd/react-flow#2334]
### Describe the Bug

Hello,
I'm using dagre for auto layouting of nodes in React flow.
There's a use case where if a node is deleted all the children of that node have to be deleted.

I tried using children method in dagre, but it's not giving expected result.

Is there a way to get the children of a node?

### Steps to Reproduce the Bug or Issue

Below is my getLayoutElements method

const getLayoutedElements = (_elements) => {
  const elements = _.cloneDeep(_elements);
  const dagreGraph = new dagre.graphlib.Graph();

  dagreGraph.setDefaultEdgeLabel(() => ({}));
  dagreGraph.setGraph({ rankdir: "TB" });

  elements.forEach((el) => {
    if (isNode(el)) {
      dagreGraph.setNode(el.id, { width: nodeWidth, height: nodeHeight });
      console.error({ children: dagreGraph.children(el.id) });
    } else {
      dagreGraph.setEdge(el.source, el.target);
    }
  });

  dagre.layout(dagreGraph);

  return elements.map((el) => {
    if (isNode(el)) {
      const nodeWithPosition = dagreGraph.node(el.id);
      el.targetPosition = "top";
      el.sourcePosition = "bottom";
      el.position = {
        x: nodeWithPosition.x - nodeWidth / 2 + Math.random() / 1000,
        y: nodeWithPosition.y - nodeHeight / 2,
      };
    }
    return el;
  });
};

### Expected behavior

As a user, I'm expecting to get the child nodes of the given node.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/35721161/182372353-ae9fda37-864d-446e-8477-0f98ed2861d2.png)

### Platform

- OS: Windows
- Browser: Chrome

**Comment by chrtze** [comment]
Hey, I think you would need to call the method to get the children after the forEach loop because it has not generated the whole graph at that point. React Flow includes a `getOutgoers` method that you can call recursively to get all children of a node: https://reactflow.dev/docs/api/graph-util-functions/#getoutgoers
