### ISSUE TITLE
How to center align the Layout in the document ?

### ISSUE THREAD

**Issue by jayanthbondi** [wbkd/react-flow#2335]
### Describe the Bug

I'm unable to center align the generated layout in the document.
I tried giving fitView as true, it's aligned to the center but the nodes widths and heights are changing.

Could you please tell how to center align the generated layout without changing widths and height?

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-30v5sn?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Open the Sandbox link.
2. You'll observe that layout is not center aligned.

### Expected behavior

As a user, I'm expecting the layout to be center aligned.

### Platform

- OS: Windows
- Browser: Chrome

**Comment by chrtze** [comment]
Please do not use Github Issues for questions about the usage of React Flow, instead please refer to the Discord channel or Stackoverflow to get help from the community.

You are probably looking for the `fitView` prop.

**Comment by jayanthbondi** [comment]
If I give fitView as true, 
The widths and height of Nodes are being changed.
So I can't use fitView

**Comment by moklick** [comment]
When you use `fitView` the viewport gets zoomed. The size doesn't change. please stop spamming.

**Comment by jayanthbondi** [comment]
Okay @moklick , But is there a way to center align without zooming of viewport?

**Comment by moklick** [comment]
yes, you can set the viewport https://reactflow.dev/docs/examples/interaction/zoom-transitions/ .
