### ISSUE TITLE
How to provide scroll for generated layout?

### ISSUE THREAD

**Issue by jayanthbondi** [wbkd/react-flow#2336]
### Describe the Bug

In my use case, the generated layout is complex and that doesn't fit in the window, it overflows.
I should be able to give a scroll to scroll up and down and see the layout.

How can we achieve that?

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-30v5sn?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Open Codesandbox link.
2. You'll not be able to scroll the layout.

### Expected behavior

As a user, I expected the scroll option and I should be able to scroll and see the overflown content, similar to scrolling any page which has hidden content.

### Platform

- OS:  Windows
- Browser: Chrome

**Comment by chrtze** [comment]
Please do not use Github Issues for questions about the usage of React Flow, instead please refer to the Discord channel or Stackoverflow to get help from the community.

You are setting `panOnScroll` to false. That's why you can't scroll inside the viewport.

**Comment by jayanthbondi** [comment]
Hi @chrtze ,
I tried giving panOnScroll to true,
But I see so much empty space being added on the top and bottom of the layout.
Could you please check and let me know.

**Comment by chrtze** [comment]
By default, the canvas is infinite. This is the expected behaviour. To limit the canvas, please use translateExtent.

**Comment by YumiJson** [comment]
How to do it? I encountered the same problem
