### ISSUE TITLE
React-Flows scrolls to inifinity with Remix

### ISSUE THREAD

**Issue by jason-weise** [wbkd/react-flow#2342]
### Describe the Bug

When used with Remix the react-flow "map" scrolls off down the page to infinity by itself.

I was trying to solve the issue on the Remix discord channel and a member provided an example on twitter that has the same issue.
The odd thing is that react-flow works fine in incognito mode yet not in normal mode in Chrome.

The sample:
[https://twitter.com/kiliman/status/1555175514167558144](https://twitter.com/kiliman/status/1555175514167558144)

It has been suggested it might be a hydration issue with React and react-flow.
Unfortunatley this would not lead to a great customer experience if they had to use incognito to use the application so I am hoping someone might know the cause.

Thanks in advance :)

### Your Example Website or App

https://twitter.com/kiliman/status/1555175514167558144

### Steps to Reproduce the Bug or Issue

1. Go to the CodeSandbox example
2. Notice on the right side where it is rendered the react-flow map disappears off the screen by itself.

NOTE:
This also happens if you create a brand new Remix app locally and add react-flow

### Expected behavior

I expect the same output in normal mode as incognito mode.

### Platform

- OS: Windows 10
- Browser: Chrome
- Version: Version 103.0.5060.134

### Additional context

It has been suggested that a chrome extension is causing the hydration issue but I am not sure if that would be the case - plus we don't want to have to tell customers to not use extensions in Chome :/

Thanks team!

**Comment by moklick** [comment]
The codesandbox and also a local Remix app work fine for me. Could you provide any more information here?

**Comment by moklick** [comment]
Please re-open if the issue still persists. I can't reproduce this.
