### ISSUE TITLE
Providing a defaultZoom below the default minZoom of 0.5 does not set the zoom correctly, even when a minZoom is provided

### ISSUE THREAD

**Issue by phinch** [wbkd/react-flow#2343]
### Describe the Bug

Hello! I am running into some interesting behavior when providing a `defaultZoom` to react-flow in my application. We set a `minZoom={0.1}` and `maxZoom={4}`, beyond the defaults of `minZoom={0.5}` and `maxZoom={2}`. This works well when zooming in and out in the flow. But when providing a `defaultZoom`, if I provide a `defaultZoom` of, say, 0.3, the flow still initially renders with a zoom of 0.5, the default minZoom prop, even though we have set the minZoom prop ourselves. The same happens with `maxZoom` if I provide a `defaultZoom` of something like 3 - the flow just renders with a zoom level of 2, the default value for `maxZoom`.

It's a little hard to describe all the numbers effectively 😅 i was able to reproduce this in the CodeSandbox listed below, and also listed some repro steps. I'm wondering if there is some unexpected defaulting behavior happening when the flow first mounts or something? Ideally, we'd like to be able to render the `defaultZoom` anywhere within our custom `minZoom` and `maxZoom` range.

### Your Example Website or App

https://codesandbox.io/s/festive-drake-ki5zn1

### Steps to Reproduce the Bug or Issue

1. Create a `ReactFlow` component with a `minZoom` below the default minZoom of 0.5 and a `defaultZoom` of less than 0.5 (but greater than the provided `minZoom`) 
2. Observe that when the form renders, the zoom level is set to 0.5, even though the `defaultZoom` is in the permitted range 
3. Altnerately, if a `defaultZoom` of greater than 0.5 is provided, the `defaultZoom` is respected when the form renders
4. This is also true on the upper bound of `maxZoom` - if a `defaultZoom` and `maxZoom` greater than 2 are provided, then the flow renders with a zoom level of 2

### Expected behavior

I was expecting that once i provide a `minZoom` and `maxZoom` range, the `defaultZoom` would work anywhere within that range, not just in the default range of `minZoom={0.5}` and `maxZoom={2}`

### Screenshots or Videos

The codesandbox link provided above should quickly show the issue - i added some simple display info to show what the zoom level is when the flow renders

### Platform

- OS: macOS
- Browser: Chrome
- Version: 103.0.5060.134

**Comment by moklick** [comment]
Thanks! Fixed in v10.3.13

**Comment by phinch** [comment]
amazing! thanks for getting to this so quickly, appreciate it :)
