### ISSUE TITLE
Projected position is wrong

### ISSUE THREAD

**Issue by Wiz1991** [wbkd/react-flow#2360]
### Describe the Bug

After making use of `react-dnd` and adding simple drag and drop support, i found that the projected position I am getting is completely off. What makes it even more irregular is that it doesnt always happen. So when not moving the camera/view at all, sometimes it would project correctly sometimes not. But as soon as  you move around and the transform changes form [0,0,1], the projected position starts to jump around. 

I've included a sandbox, just open it up and try dropping. If it doesnt happen, try refreshing once or twice and try again. Its very irregular and doesnt always happen. 

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-2pwdnu?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Open sandbox
2. Try dropping once
3. If it doesnt project wrong, refresh
4. Try again
5. Repeat from steps 2-4 with diferent usecases, such as first panning or zooming then dropping. 

### Expected behavior

It should calculate the correct position

### Screenshots or Videos

https://user-images.githubusercontent.com/45233935/184307094-06069039-1a75-4b60-ab43-cb83bf5509ff.mov

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
Seems like your position calculation is not correct.

This works completely fine for me in the sandbox you linked:

```js
const offset = monitor.getClientOffset();

const position = {
        x: offset.x,
        y: offset.y
	};
```

**Comment by Wiz1991** [comment]
> Seems like your position calculation is not correct.
> 
> This works completely fine for me in the sandbox you linked:
> 
> ```js
> const offset = monitor.getClientOffset();
> 
> const position = {
>         x: offset.x,
>         y: offset.y
> 	};
> ```

Are you sure? Try refreshing after removing the bounding box subtraction. It only works for a moment

**Comment by Wiz1991** [comment]
https://user-images.githubusercontent.com/45233935/184310793-f866f8e2-3826-493b-a81a-6a853b8648a2.mov

Here is a video

**Comment by bcakmakoglu** [comment]
> > Seems like your position calculation is not correct.
> > This works completely fine for me in the sandbox you linked:
> > ```js
> > const offset = monitor.getClientOffset();
> > 
> > const position = {
> >         x: offset.x,
> >         y: offset.y
> > 	};
> > ```
> 
> Are you sure? Try refreshing after removing the bounding box subtraction. It only works for a moment

I'll try again later - currently on the road 😅

**Comment by moklick** [comment]
The issue here is that `reactflow.project` gets updated after the first render but not the `reactflow` object itself.

Easiest way to fix this: 

```js
const { project } = useReactFlow();
```

pass that `project` function to the `onDrop` deps array => everything works as expected.

**Comment by Wiz1991** [comment]
> The issue here is that `reactflow.project` gets updated after the first render but not the `reactflow` object itself.
> 
> Easiest way to fix this:
> 
> ```js
> const { project } = useReactFlow();
> ```
> 
> pass that `project` function to the `onDrop` deps array => everything works as expected.

Yeah, was about to update the issue with this. 
Did not notice the `react-dnd` hook was memoized. Works as expected.
