### ISSUE TITLE
couldn't create edge for target handle id: undefined; edge id: edge-1 

### ISSUE THREAD

**Issue by talor1981** [wbkd/react-flow#2364]
### Describe the Bug

Hi,
In the useEffect hook I'm building the nodes element and saving them to the state by setNodes.
In another useEffect that's listening to setNodes state change, I'm building the edge and saving them to setEdge state.
the id for the nodes is based on foreach loop, and I've created it like this: id: 'rel-' + count (count increase in each iteration)
in the edge logic, I did like that:

```js         
const ServiceRelations = () => {
    const { selectedService } = useContext(DataContext);

    const [nodes, setNodes, onNodesChange] = useState([]);
    const [edges, setEdges, onEdgesChange] = useState([]);

    const onConnect = (params) => setEdges((eds) => addEdge(params, eds));

    const nodeStyle = {
        background: '#F2F2F2', color: '#333', border: '1px solid #222138',
        width: 'auto',
        fontSize: '1rem'

    }

    useEffect(() => {
        if (selectedService) {

           
            if (selectedService && selectedService.serviceRelations.length) {

                let padding = 300;
                let height = 0;
                let nodes = [];

                let count = 0;

                selectedService.serviceRelations.forEach(relationItem => {

                    if (count === 0) {
                        nodes.push(createNode(relationItem, 0, 80, true, count));

                    }
                    else {
                        nodes.push(createNode(relationItem, padding, height, false, count));
                        height = height + 160;

                    }
                    count++;
                });
                setNodes(nodes);
            }
        }

    }, [selectedService]);

    const createNode = (nodeItem, x, y, isRoot, itemId) => {


        let obj = {
            id: String(itemId),
            type: 'input',           
            data: { label: (<div>{nodeItem.service}</div>) },
            position: { x: x, y: y },
            style: nodeStyle
        }       

        if (isRoot) {
            obj.sourcePosition = 'right';
        }
        else {
            obj.sourcePosition = 'left';
            obj.targetPosition = 'right';

        }

        return obj;

    }



    useEffect(() => {

        if (nodes && nodes.length > 0) {


            let count = 0;
            let edges = [];
            let staticNodeId = {};
            nodes.forEach(node => {
                if (count > 0) {
                    let edge = {
                        id: 'edge-' + count,
                        source: staticNodeId,
                        type: 'input',
                        target: node.id,
                        animated: true
                        /*label: 'bezier edge (default)',*/
                    }
                    edges.push(edge)

                }
                else {
                    staticNodeId = node.id
                }
                count++;
            });
            setEdges(edges)

        }
    }, [nodes])




    return (
        <>
            <div className="sc-main">

                <div style={{ height: '500px', width: '50vw' }} >
                    <ReactFlow
                        nodes={nodes}
                        edges={edges}
                        onNodesChange={onNodesChange}
                        onEdgesChange={onEdgesChange}
                        onConnect={onConnect}
                        zoomOnScroll={false}
                        zoomOnPinch={false}
                        zoomOnDoubleClick={false}
                        nodesDraggable={false}
                        panOnDrag={false}
                        /*  nodesConnectable={false}*/
                        attributionPosition="top-center"
                        preventScrolling={false}
                        fitView
                    />
                </div>
            </div>
        </>
    );


}

export default ServiceRelations
```

All the Ids are type of string
however, I'm still getting this error:
couldn't create edge for target handle id: undefined; edge id: edge-1 

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

.

### Platform

.

**Comment by moklick** [comment]
Can you put everything that is in ` if (nodes && nodes.length > 0) { ... ` in the first `useEffect` where you create the nodes?
Having a `useEffect` with `nodes` in the deps array is really bad because it gets triggered whenever the nodes change (on drag, on select, ..)

**Comment by moklick** [comment]
Please re-open if the issue still persists.

**Comment by kahboom** [comment]
@moklick - What could be a potential cause of this error? I'm getting the same, when trying to create a new node and edge. It's not something with React Flow I don't think, because it was working for me before, but I'm having a hard time debugging it.

The `nodes` and `edges` arrays both look correct: `Couldn't create edge for source handle id: undefined; edge id: e-aws-ddb-streams-source0_0>dns-lookup-action1_1.`

The source handle `id` is hardcoded, like this, so I wouldn't think it was that:
```
<Handle
              isConnectable={false}
              type="source"
              position={Position.Right}
              id="b"
              style={{ borderRadius: 0 }}
            />
```

If that's not enough information though I can create a new issue.

**Comment by moklick** [comment]
which version are you using @kahboom ?

**Comment by kahboom** [comment]
@moklick - I'm on 10.3.6, should I upgrade to 11?

**Comment by moklick** [comment]
No, you don't need to update to v11. You could try to 10.3.17, but I am not sure if that helps. How are you creating your nodes and edges. And since when is this broken for you?

**Comment by kahboom** [comment]
@moklick Thanks for the quick response. I figured it out, but I'm not sure if this is a bug of some sort? Basically, I started passing an argument to the `getId()` function that generates the node `id` like this (commented out the original):

```
let id = 0;
// const getId = () => `dndnode_${id++}`;
const getId = (uuid: string) => `${uuid}_${id++}`;

const currentStep: IVizStepPropsNode = buildNodeDefaultParams(
  step,
  // getId(),
  getId(step.UUID), // <-- this broke it
  currentStepPosition
);
```

Uncommenting and reverting back fixed it. I could be wrong, but I don't think the `buildNodeDefaultParams` function is relevant here as it just returns an object for each node:

```
export function buildNodeDefaultParams(
  step: IStepProps,
  newId: string,
  position: { x: number; y: number }
): IVizStepPropsNode {
  return {
    data: {
      icon: step.icon,
      kind: step.kind,
      label: truncateString(step.name, 14),
      step,
      UUID: step.UUID,
    },
    id: newId,
    position,
    type: 'step',
  };
}
```

Having said that, this doesn't happen all the time. It seems to only happen for the first step I try to append to a new step to. So perhaps it is related to my code elsewhere, as I've been doing a lot of refactoring, but hopefully it can help someone. If I get a chance later in the day I will create a CodeSandbox to try to reproduce it.

**Comment by kahboom** [comment]
and the other main issue was adding a conditional that hid the handle

**Comment by paulodeon** [comment]
The cause of this issue for me was the fact that the handles on a custom node had a `type="source"` instead of `type="target"`. It became an issue when I migrated from 9 > 10

**Comment by dgattey** [comment]
I'm seeing this on latest - it's because I'm expanding/contracting nodes and adding edges as I do so. The custom node in question goes from having no handles to having two handles, and it looks like the edges are recreated/reconnected before the node has a chance to re-render, so I see this warning.

Changing this JSX for my custom node:
```typescript
     {['node', 'target'].includes(type) && (
        <Handle
          type="target"
          position={Position.Top}
          id="top"
          isConnectable={isConnectable}
          style={handleStyle}
        />
      )}
      {children}
      {['node', 'source'].includes(type) && (
        <Handle
          type="source"
          position={Position.Bottom}
          id="bottom"
          isConnectable={isConnectable}
          style={handleStyle}
        />
      )}
```
to this, instead rendering the handle _all_ the time, fixes it. Not an ideal solution, so I'm just going to ignore the error for now.
```typescript
      <Handle
          type="target"
          position={Position.Top}
          id="top"
          isConnectable={isConnectable}
          style={handleStyle}
        />
      {children}
      <Handle
          type="source"
          position={Position.Bottom}
          id="bottom"
          isConnectable={isConnectable}
          style={handleStyle}
        />
```

**Comment by MianAizaz6** [comment]
> o try to rep



> @moklick Thanks for the quick response. I figured it out, but I'm not sure if this is a bug of some sort? Basically, I started passing an argument to the `getId()` function that generates the node `id` like this (commented out the original):
> 
> ```js
> let id = 0;
> // const getId = () => `dndnode_${id++}`;
> const getId = (uuid: string) => `${uuid}_${id++}`;
> 
> const currentStep: IVizStepPropsNode = buildNodeDefaultParams(
>   step,
>   // getId(),
>   getId(step.UUID), // <-- this broke it
>   currentStepPosition
> );
> ```
> 
> Uncommenting and reverting back fixed it. I could be wrong, but I don't think the `buildNodeDefaultParams` function is relevant here as it just returns an object for each node:
> 
> ```js
> export function buildNodeDefaultParams(
>   step: IStepProps,
>   newId: string,
>   position: { x: number; y: number }
> ): IVizStepPropsNode {
>   return {
>     data: {
>       icon: step.icon,
>       kind: step.kind,
>       label: truncateString(step.name, 14),
>       step,
>       UUID: step.UUID,
>     },
>     id: newId,
>     position,
>     type: 'step',
>   };
> }
> ```
> 
> Having said that, this doesn't happen all the time. It seems to only happen for the first step I try to append to a new step to. So perhaps it is related to my code elsewhere, as I've been doing a lot of refactoring, but hopefully it can help someone. If I get a chance later in the day I will create a CodeSandbox to try to reproduce it.

Hey I am having the same issue, and I am not able to debug it. The version I am using is 11.11.4,

**Comment by rjpower** [comment]
FWIW, I found I was triggering this message by trying to have edges connecting between 2 input nodes - changing the node type to "default" resolves the issue.

The failure wasn't unreasonable in this case, but a nicer error message might be useful!
