### ISSUE TITLE
@types/react and @types/react-dom dependencies moved from dev to prod and are forcing usage of react v18

### ISSUE THREAD

**Issue by barneaoren** [wbkd/react-flow#2368]
### Describe the Bug

Starting latest version, the devDependencies of @types/react and @types/react-dom were relocated to the dependencies section, forcing the installation of React v18 types which are breaking any v16 application.

This is a breaking change and should be (1) reverted and (2) pushed to the next major release of React Flow.

### Steps to Reproduce the Bug or Issue

Install latest version of React Flow with a React v16 application.

### Expected behavior

One of the many issues we are facing is:

TS2786: 'Component' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<T, any, any> | null' is not a valid JSX element.
    Type 'Component<T, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<T, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.

### Platform

- OS: Any
- Browser: N/A
- Version: Latest

**Comment by moklick** [comment]
This slipped through. Thanks for bringing it up so quickly. Fix is released with v10.3.16

**Comment by barneaoren** [comment]
Thank you @moklick for fixing it promptly !
I already tested the new version and it seems to be working as expected
