### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by miclegoden** [wbkd/react-flow#2369]
### Please describe the feature that you want to propose

Warning message

"It looks like you have created a new nodeTypes or edgeTypes object. If this wasn't on purpose please define the nodeTypes/edgeTypes outside of the component or memoize them."

**Comment by moklick** [comment]
you can find the answer in the docs: https://reactflow.dev/docs/guides/troubleshooting/#it-looks-like-you-have-created-a-new-nodetypes-or-edgetypes-object-if-this-wasnt-on-purpose-please-define-the-nodetypesedgetypes-outside-of-the-component-or-memoize-them
