### ISSUE TITLE
panOnDrag on elements not working when onNodeClick is also active

### ISSUE THREAD

**Issue by croissantspectacular** [wbkd/react-flow#2370]
### Describe the Bug

I'm currently writing a page that requires to click on elements while also allowing to drag the view even from inside those elements. This is because I'm using some pretty large elements, therefore not being able to drag the view by dragging from inside the node makes the page very difficult to navigate. 

### Your Example Website or App

https://codesandbox.io/s/jk3jng?file=/App.js:2810-2821&from-sandpack=true

### Steps to Reproduce the Bug or Issue

1. Enable both panOnDrag and capture elementOnClick, disable everything else. 
2. Try to drag the view by dragging from inside one of the nodes (start the drag by pressing the left mouse key inside a node, then move the mouse without releasing the left mouse key). 
3. The view won't move, even though it's not activating the onClickFunction either (clicking the node activates the console.log onNodeClick function, but dragging from inside the node neither activates the onNodeClick function nor does it drag the view). 

### Expected behavior

The expected behavior is allowing to drag the view by dragging from inside an element. 

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 103

**Comment by moklick** [comment]
What do you mean with "click on elements"? Should it select the node or is it about an element within the node (like a button)? I am sure there is a way to achieve this with a custom node implementation.

**Comment by croissantspectacular** [comment]
I mean when selecting the node itself, it just won't let me. The example I described from the code sandbox link above is pretty much the exact problem I'm having. 

I don't think a custom node implementation would fix this, or would it? In any case, the case I'm describing is definitely an unexpected behavior. 

Thanks for the response by the way.

**Comment by croissantspectacular** [comment]
I can confirm that #1457 is the same problem I described, and also that the latest version of React Flow 11 fixes this problem. Thanks for all the help.
