### ISSUE TITLE
Restore flow  working not well with custom nodes and edges

### ISSUE THREAD

**Issue by nhannt97** [wbkd/react-flow#2371]
### Describe the Bug

I had an array nodes and an array edges
`[
    {
        "id": "node_0",
        "type": "trigger",
        "height": 78,
        "width": 643,
        "position": {
            "x": 100,
            "y": 50
        },
        "data": {
            "label": "Trigger",
            "concurrentCallsTrigger": false,
            "transitions": [
                {
                    "id": "reactflow__edge-Triggerincomming message-node_1input",
                    "source": "Trigger",
                    "sourceHandle": "incomming message",
                    "target": "node_1",
                    "targetHandle": "input",
                    "type": "custom",
                    "style": {
                        "strokeWidth": 3,
                        "stroke": "rgb(0, 62, 130)"
                    }
                },
                {
                    "id": "reactflow__edge-Triggersubflow-node_7input",
                    "source": "Trigger",
                    "sourceHandle": "subflow",
                    "target": "node_7",
                    "targetHandle": "input",
                    "type": "custom",
                    "style": {
                        "strokeWidth": 3,
                        "stroke": "rgb(0, 62, 130)"
                    }
                }
            ]
        }
    },
    {
        "id": "node_1",
        "type": "split_based_on",
        "height": 143,
        "position": {
            "x": -20,
            "y": 220
        },
        "data": {
            "label": "node_1",
            "input": "{{flow.channel.address}}",
            "transitions": [
                {
                    "id": "reactflow__edge-node_1node_1condition_0-set_variables_1input",
                    "source": "node_1",
                    "sourceHandle": "node_1condition_0",
                    "target": "set_variables_1",
                    "targetHandle": "input",
                    "type": "custom",
                    "style": {
                        "strokeWidth": 3,
                        "stroke": "rgb(117, 100, 196)"
                    }
                },
                {
                    "id": "reactflow__edge-node_1node_1condition_2-node_6input",
                    "source": "node_1",
                    "sourceHandle": "node_1condition_2",
                    "target": "node_6",
                    "targetHandle": "input",
                    "type": "custom",
                    "style": {
                        "strokeWidth": 3,
                        "stroke": "rgb(117, 100, 196)"
                    }
                }
            ],
            "outputs": [
                {
                    "tranId": "reactflow__edge-node_1node_1condition_0-set_variables_1input",
                    "event": "noMatch",
                    "id": "node_1condition_0",
                    "label": "No Condition Matches"
                },
                {
                    "event": "match",
                    "id": "node_1condition_1",
                    "condition": {
                        "type": "equal_to",
                        "value": "dasd"
                    }
                },
                {
                    "tranId": "reactflow__edge-node_1node_1condition_2-node_6input",
                    "event": "match",
                    "id": "node_1condition_2",
                    "condition": {
                        "type": "equal_to",
                        "value": "dfas"
                    }
                },
                {
                    "event": "match",
                    "id": "node_1condition_3",
                    "condition": {
                        "type": "not_equal_to",
                        "value": "gsdfg"
                    }
                }
            ]
        },
        "width": 520
    },
    {
        "id": "node_2",
        "type": "gather_input_on_call",
        "width": 258,
        "height": 120,
        "position": {
            "x": 300,
            "y": 640
        },
        "data": {
            "label": "node_5",
            "transitions": [],
            "speechRecognitionHints": "ddd",
            "sayOrPlay": "say",
            "say": "fsad",
            "profanityFilter": {
                "value": "true",
                "label": "True"
            },
            "speechRecognitionLanguage": {
                "label": "English (United States)",
                "value": "en-US"
            }
        }
    },
    {
        "id": "node_3",
        "type": "say_or_play",
        "width": 258,
        "height": 120,
        "position": {
            "x": 160,
            "y": 450
        },
        "data": {
            "label": "node_6",
            "transitions": [
                {
                    "id": "reactflow__edge-node_6audio complete-node_5input",
                    "source": "node_6",
                    "sourceHandle": "audio complete",
                    "target": "node_5",
                    "targetHandle": "input",
                    "type": "custom",
                    "style": {
                        "strokeWidth": 3,
                        "stroke": "rgb(42, 151, 98)"
                    }
                }
            ],
            "sayOrPlayOrDigit": "play",
            "play": "dsasd"
        }
    },
    {
        "id": "node_4",
        "type": "enqueue_call",
        "width": 290,
        "height": 120,
        "position": {
            "x": 600,
            "y": 240
        },
        "data": {
            "label": "node_7",
            "transitions": [
                {
                    "id": "reactflow__edge-node_7call complete-node_8input",
                    "source": "node_7",
                    "sourceHandle": "call complete",
                    "target": "node_8",
                    "targetHandle": "input",
                    "type": "custom",
                    "style": {
                        "strokeWidth": 3,
                        "stroke": "rgb(0, 62, 130)"
                    }
                }
            ],
            "holdMusicTwimlUrl": "sdf",
            "queueName": "dasd",
            "queueOrTaskRouter": "queue"
        }
    },
    {
        "id": "node_5",
        "type": "make_http_request",
        "width": 258,
        "height": 120,
        "position": {
            "x": 530,
            "y": 570
        },
        "data": {
            "label": "node_8",
            "transitions": [],
            "requestUrl": "gfd",
            "contentType": "application/x-www-form-urlencoded;charset=utf-8",
            "requestBody": "{a: 234}",
            "parameters": [
                {
                    "value": "54",
                    "key": "a",
                    "id": 0
                }
            ]
        }
    },
    {
        "id": "node_6",
        "type": "set_variables",
        "width": 258,
        "height": 120,
        "position": {
            "x": -80,
            "y": 420
        },
        "data": {
            "label": "set_variables_1",
            "transitions": [],
            "variables": [
                {
                    "id": 0,
                    "key": "asd",
                    "value": "r"
                }
            ]
        }
    }
]
[
    {
        "id": "reactflow__edge-Triggerincomming message-node_1input",
        "source": "Trigger",
        "sourceHandle": "incomming message",
        "target": "node_1",
        "targetHandle": "input",
        "type": "custom",
        "style": {
            "strokeWidth": 3,
            "stroke": "rgb(0, 62, 130)"
        }
    },
    {
        "id": "reactflow__edge-Triggersubflow-node_7input",
        "source": "Trigger",
        "sourceHandle": "subflow",
        "target": "node_7",
        "targetHandle": "input",
        "type": "custom",
        "style": {
            "strokeWidth": 3,
            "stroke": "rgb(0, 62, 130)"
        }
    },
    {
        "id": "reactflow__edge-node_1node_1condition_0-set_variables_1input",
        "source": "node_1",
        "sourceHandle": "node_1condition_0",
        "target": "set_variables_1",
        "targetHandle": "input",
        "type": "custom",
        "style": {
            "strokeWidth": 3,
            "stroke": "rgb(117, 100, 196)"
        }
    },
    {
        "id": "reactflow__edge-node_1node_1condition_2-node_6input",
        "source": "node_1",
        "sourceHandle": "node_1condition_2",
        "target": "node_6",
        "targetHandle": "input",
        "type": "custom",
        "style": {
            "strokeWidth": 3,
            "stroke": "rgb(117, 100, 196)"
        }
    },
    {
        "id": "reactflow__edge-node_6audio complete-node_5input",
        "source": "node_6",
        "sourceHandle": "audio complete",
        "target": "node_5",
        "targetHandle": "input",
        "type": "custom",
        "style": {
            "strokeWidth": 3,
            "stroke": "rgb(42, 151, 98)"
        }
    },
    {
        "id": "reactflow__edge-node_7call complete-node_8input",
        "source": "node_7",
        "sourceHandle": "call complete",
        "target": "node_8",
        "targetHandle": "input",
        "type": "custom",
        "style": {
            "strokeWidth": 3,
            "stroke": "rgb(0, 62, 130)"
        }
    }
]`

and my function to restore:
`const handleImport = useCallback((data) => {
    const restoreFlow = async () => {
      setNodes(data.nodes)
      setEdges(data.edges)
    };
    restoreFlow();
  }, [handleNewCondition, setEdges, setNodes]);`

and result : the edges not correct as data I imported!!!!

![image](https://user-images.githubusercontent.com/25659972/185466859-99bf251e-da7c-4d0d-9f05-e859abcd9ef1.png)

### Your Example Website or App

https://github.com/nhannt97/test-react-app

### Steps to Reproduce the Bug or Issue

Import flow from custom data

### Expected behavior

The edges are correct as imported data

### Platform

- OS: Windows
- Browser: Chrome
- Version: 10

**Comment by moklick** [comment]
do you have a json, that I could import, to test that import function?

**Comment by nhannt97** [comment]
@moklick 
Thank for your response!
I'm really sorry!
It's just my bad with customizing nodes. I fixed!
I'll close this issue right now!

**Comment by nhannt97** [comment]
Thank for your review!
