### ISSUE TITLE
Cannot interact with the node content if elementsSelectable and nodeDraggable are false

### ISSUE THREAD

**Issue by MrDesjardins** [wbkd/react-flow#2385]
### Describe the Bug

With `elementsSelectable` to `false` and `nodesDraggable` to `false` the content of a node is not clickable. 

I have a use case where I let the user configure the node and then "save" which turn all the edition (pan, zoom, drag, etc) to `false`. I still want to user to interact with the content of the node like buttons, select, grid or any other HTML components inside the node, just not altering the node positions.

The bug is that turning `elementsSelectable` to false make the node not selectable (that is expected) but also the content which is not expected. The node should be not selectable but React-Flow should not block interaction of the content of the node.

### Steps to Reproduce the Bug or Issue

I have a full repro available here: 

[https://codesandbox.io/s/sandpack-project-forked-sjd5zs?file=/App.js](https://codesandbox.io/s/sandpack-project-forked-sjd5zs?file=/App.js)

It is from the example in the documentation (https://reactflow.dev/docs/examples/nodes/custom-node/) with a small change:
```
    <ReactFlow
      nodes={nodes}
      edges={edges}
      ... 
      elementsSelectable={false}
      nodesDraggable={false}
    >
```

### Expected behavior

As a user, I expect to turn off the node selection and the node drag to not impact the content of the node.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 104.0.5112.101 (Official Build) (arm64)

**Comment by bcakmakoglu** [comment]
To remedy the issue you could just wrap your custom node content in a div and set `pointer-events: all`

Using the custom node of the sandbox

```js
import React, { memo } from "react";

import { Handle } from "react-flow-renderer";

export default memo(({ data, isConnectable }) => {
  return (
    <div style={{ pointerEvents: "all" }}>
      <Handle
        type="target"
        position="left"
        style={{ background: "#555" }}
        onConnect={(params) => console.log("handle onConnect", params)}
        isConnectable={isConnectable}
      />
      <div>
        Custom Color Picker Node: <strong>{data.color}</strong>
      </div>
      <input
        className="nodrag"
        type="color"
        onChange={data.onChange}
        defaultValue={data.color}
      />
      <Handle
        type="source"
        position="right"
        id="a"
        style={{ top: 10, background: "#555" }}
        isConnectable={isConnectable}
      />
      <Handle
        type="source"
        position="right"
        id="b"
        style={{ bottom: 10, top: "auto", background: "#555" }}
        isConnectable={isConnectable}
      />
    </div>
  );
});
```

**Comment by MrDesjardins** [comment]
Thank you @bcakmakoglu
The temporary solution to rely on CSS to click works! I also modified the cursor to not always be "grab," and the illusion is perfect.

Have a great day.

**Comment by moklick** [comment]
Thanks for sharing a solution @bcakmakoglu !

**Comment by mtuchi** [comment]
> Thank you @bcakmakoglu The temporary solution to rely on CSS to click works! I also modified the cursor to not always be "grab," and the illusion is perfect.
> 
> Have a great day.

Can share an example on how i can change the grab cursor to the default cursor ?

**Comment by bcakmakoglu** [comment]
@mtuchi 

Basic solution for that would be something like this

```css
.react-flow__node {
   cursor: default;
}
```

**Comment by mtuchi** [comment]
> @mtuchi 
> 
> Basic solution for that would be something like this
> 
> ```css
> .react-flow__node {
>    cursor: default;
> }
> ```

I have tried this but it didn't work, I will try again

**Comment by mtuchi** [comment]
> ```css
> .react-flow__node {
>    cursor: default;
> }
> ```
@bcakmakoglu 
I have managed to change the cursor from `grab` to `default` Thanks for the suggestion. I had to 
specify the height of the node that I was trying to make changes to `<div className="h-full cursor-default"></div>`
