### ISSUE TITLE
Make target field optional for an edge

### ISSUE THREAD

**Issue by KumarilDave** [wbkd/react-flow#2386]
### Please describe the feature that you want to propose

I have a unique  use case at work where I am configuring many nodes with n number of edges at first. This list of nodes are stored in a DB. When user want to configure, they add this node to the canvas,  then let the user create new types of node and connect them to these edges. Is there any way currently that can be handled or any plans of providing such an option ?

**Comment by moklick** [comment]
I think you could create a data model to store this information but there is no need for ReactFlow to render those unconnected edges.
