### ISSUE TITLE
`onEdgeClick` does not work if either target or source node is in subflow

### ISSUE THREAD

**Issue by dominiczy** [wbkd/react-flow#2389]
### Describe the Bug

`onEdgeClick` does not trigger for any edge where either target or source node is in subflow. Setting a higher `z-index` doesn't solve it neither.

Minimal example of bug:
https://codesandbox.io/s/sandpack-project-forked-jubz3o?file=/App.js

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-jubz3o?file=/App.js

### Steps to Reproduce the Bug or Issue

Go to https://codesandbox.io/s/sandpack-project-forked-jubz3o?file=/App.js
Click on the Edge between the two nodes.
Verify that the `onEdgeClick` callback (which logs to console) is not triggered

### Expected behavior

I expected `onEdgeClick` to trigger but it does not

### Platform

MacOS Chrome

**Comment by moklick** [comment]
In your example the edge is below the group. You can set a `zIndex` for an edge in order to render it on top of a group/node: https://codesandbox.io/s/sandpack-project-forked-g1rqyr
