### ISSUE TITLE
Callback on Node Middle-Click

### ISSUE THREAD

**Issue by mycoalchen** [wbkd/react-flow#2395]
### Please describe the feature that you want to propose

Would it be possible to add a callback function on middle-clicking a node? I'm currently using the nodes as links, and I want users to be able to open them in a new tab on middle click. The `onElementsClick` event doesn't trigger on middle click.

**Comment by moklick** [comment]
You can implement a custom node and add an `onClick` handler that checks `event.button === 1` for this.
