### ISSUE TITLE
Difference between click and drag

### ISSUE THREAD

**Issue by CarlosADLRT** [wbkd/react-flow#241]
I want to open model when user click a node. But if the user drag the node the model will pop up. Any suggestion on what can I do?

**Comment by moklick** [comment]
Hey @CarlosADLRT 

you are right. The `onClick` handler is actually a `onDragStart` handler. I will try to implement an `onClick` handler and rename the current `onClick` handler to `onDragStart`.

**Comment by moklick** [comment]
should work with v1.4.0

**Comment by CarlosADLRT** [comment]
Tks
