### ISSUE TITLE
`snapGrid` misalignment when initial position is not multiple of `snapGrid` value

### ISSUE THREAD

**Issue by bcakmakoglu** [wbkd/react-flow#2415]
### Describe the Bug

When `snapToGrid` and `snapGrid` are provided, the snapping pattern of nodes can be misaligned if the nodes initial position is not a multiple of the snapGrid value.

This makes it sort of impossible to properly align two nodes that might have "mismatched" initial positions and thus can't snap onto the same lines.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-bj7bhe?file=/initial-elements.js

### Steps to Reproduce the Bug or Issue

1. Open the sandbox
2. Try aligning the two nodes over one another.

### Expected behavior

Expected the nodes to be exactly over each other / be able to align them correctly.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
fixed in v10.3.17
