### ISSUE TITLE
can not use Attribute contentEditable in react-flow

### ISSUE THREAD

**Issue by feweblee** [wbkd/react-flow#2434]
### Describe the Bug

tag div set contentEditable Attribute can not input,.
has select border
has not cursor
![image](https://user-images.githubusercontent.com/113905024/191010418-177f0fb5-286d-4f0b-be2a-d2f720a141a6.png)

you can use code in react-flow's project, path:example/src/Overview/index.tsx line: 115
```
  {
    id: '6',
    type: 'output',
    data: {
      label: (
        <div 
          contentEditable={true} onSelect={() => {
            console.log('selectHandle is not exec')
          }}

          dangerouslySetInnerHTML={{__html: 'test contentEditable'}}
        ></div>
        // or <div 
        //   contentEditable={true} onSelect={() => {
        //     console.log('selectHandle is not exec')
        //   }}
        //   suppressContentEditableWarning={true}
        // >test contentEditable</div>
      ),
    },
    position: { x: 100, y: 480 },
  },
```

### Steps to Reproduce the Bug or Issue

1.clone react-flow
2. change example/src/Overview/index.tsx line 115
```
  {
    id: '6',
    type: 'output',
    data: {
      label: (
        <div 
          contentEditable={true} onSelect={() => {
            console.log('selectHandle is not exec')
          }}

          dangerouslySetInnerHTML={{__html: 'test contentEditable'}}
        ></div>
        // or <div 
        //   contentEditable={true} onSelect={() => {
        //     console.log('selectHandle is not exec')
        //   }}
        //   suppressContentEditableWarning={true}
        // >test contentEditable</div>
      ),
    },
    position: { x: 100, y: 480 },
  },
```
3.npm install & npm start
4. cd example & npm install & npm start
5. open localhost:3000 in chrome

### Expected behavior

div set contentEditable can input, div selected has cursor

### Platform

- OS: [ macOS]
- Browser: [Chrome, Safari]

**Comment by moklick** [comment]
please create a codesandbox. Did you try to add the class name "nodrag" to the div with contentEditable=true?

**Comment by feweblee** [comment]
> please create a codesandbox. Did you try to add the class name "nodrag" to the div with contentEditable=true?

'nodrag' can solve it,thank you~

**Comment by tscislo** [comment]
@andrew-longmore-tessella 
Try setting it conditionally
![image](https://user-images.githubusercontent.com/2109390/206784028-9b7e4124-2cf2-4e5b-9cab-e14d45dad1ea.png)
