### ISSUE TITLE
Dragging of nodes group doesn't work if node mouse handler is set

### ISSUE THREAD

**Issue by Ihtion** [wbkd/react-flow#2438]
### Describe the Bug

If child node (node that has `parentNode` field) has `draggable` property as `false` and node mouse event handler (e.g. `onNodeMouseLeave`) is set, it's impossible to  drag group of nodes if you pressed left button over child node.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-5cgf76?file=/App.js

### Steps to Reproduce the Bug or Issue

1.  Create group of nodes (via parentNode).
2. Make child nodes undraggable (`draggable: false`).
3. Add node mouse event handler for ReactFlow (e.g. `onNodeMouseLeave`).
4. Group of nodes can't be dragged if you pressed left button over child nodes (but works as expected if left button is pressed over parent node). 

### Expected behavior

It should be possible to drag a group of nodes with mouse event handler and undraggable child nodes.

### Screenshots or Videos

https://user-images.githubusercontent.com/64694520/191267295-7ed39dca-1fd7-4bbb-859b-f545f44729bd.mov

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [10.3.14]

**Comment by moklick** [comment]
This is fixed in the next v11 release:

https://codesandbox.io/s/sandpack-project-forked-lv8d3b?file=/App.js
