### ISSUE TITLE
Have a toggle between the old snapGrid and the new one

### ISSUE THREAD

**Issue by WillBaker2017** [wbkd/react-flow#2440]
### Please describe the feature that you want to propose

I would like a toggle between the old snapGrid and the new one. I was using the old one in my code and with this update it broke everything. I understand why users would like the snapGrid[10, 10] to move in increments of 10 based off of 0, 0. But I also like the idea of moving over 545 for where it is now, but snapGrid[545, 30] now does it in reference to 0, 0. That is what I use in my code. If things are not aligned at 0, 0. it completely throws off the dragging feature.  I have made a temporary fix :

```
const handleDragStart = (node, event) => {
// 545 is what the snapGrid is set to and where the node goes to on drag
     if (node.position.x == 545){
         // 625 is the actual node.position.x that I want it to be at. 
         node.position.x = 625
      }
 }
```

This is temporary and only works for some of my nodes. I hope that this feature can be created so I don't have to look into a more permanent fix. I believe that the toggle could look something like:     snapGridAtZero={true/false}

**Comment by moklick** [comment]
Sorry, I don't understand the issue. Do you want to use a snap grid or not?

**Comment by wardoost** [comment]
@moklick We could allow switching between snapping modes by allowing more values for the `snapToGrid` boolean. So change https://github.com/wbkd/react-flow/blob/7a909e942527daecb01fb78a4cfc00d5f46330ab/src/types/component-props.ts#L95 to `snapToGrid?: boolean | 'absolute' | 'relative'` to avoid breaking changes.

**Comment by WillBaker2017** [comment]
> @moklick We could allow switching between snapping modes by allowing more values for the `snapToGrid` boolean. So change
> 
> https://github.com/wbkd/react-flow/blob/7a909e942527daecb01fb78a4cfc00d5f46330ab/src/types/component-props.ts#L95
> 
> to `snapToGrid?: boolean | 'absolute' | 'relative'` to avoid breaking changes.



@wardoost @moklick I like that a lot

**Comment by moklick** [comment]
@WillBaker2017 I don't like it :D The old version was broken, because it was not one grid but multiple ones. If you want a special snap behaviour you can use `onNodesChange` or alter nodes when dragging is false for example.
