### ISSUE TITLE
Dragging node out and back inside the graph with onlyRenderVisibleElements=true makes dragging false

### ISSUE THREAD

**Issue by NikolMarg** [wbkd/react-flow#2444]
### Describe the Bug

In version 10.3.17, if you set `onlyRenderVisibleElements` to `true` and drag a custom node outside - and then back inside the graph, sets the `dragging` prop of the node to `false`, despite it still being dragged.

### Your Example Website or App

https://codesandbox.io/s/react-flow-drag-issue-with-onlyrendervisibleelements-2ckeqx?file=/src/FlowExample.jsx

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/s/react-flow-drag-issue-with-onlyrendervisibleelements-2ckeqx?file=/src/FlowExample.jsx
2. Drag the custom node inside the graph
3. See that the `dragging` prop (logged in the console) is `true`
4. Drag the node outside the graph and then back inside
5. See that the `dragging` prop is now `false` 

### Expected behavior

As a user, I expected `dragging` to be `true` whenever a node is being dragged, regardless if it was temporarily out of bounds.

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome]
- Version: [e.g. 10.3.17]

**Comment by moklick** [comment]
Thanks @NikolMarg this is a bug. We will check how we can fix it.

**Comment by NikolMarg** [comment]
Thanks a ton! For now I bypassed this issue by keeping a local state flag for a node's selection status that starts as true if the node is selected when it enters the graph. Then doing a cross check between `dragging` and this flag.

It feels really hacky however so I'd love to see this fixed.

**Comment by moklick** [comment]
Thanks @NikolMarg 

this is fixed in v11.1.2 :)
