### ISSUE TITLE
Prop for "dragMode" to be either "pan" or "select" (or something similar)

### ISSUE THREAD

**Issue by cgross** [wbkd/react-flow#2450]
### Please describe the feature that you want to propose

Some diagramming tools default to panning on drag, others to selection on drag.  Today, react-flow allows `panOnDrag` but `selectNodesOnDrag` requires the user holding shift.  I'm proposing a new prop that allows react-flow to work in either way by passing in the appropriate option.  So if `dragMode="pan"` (or something similar), it works like `panOnDrag` does today.  If `dragMode="select"`, dragging starts the selection box without requiring shift.  Then developers can configure however they wish, and they could also create a toolbar/button so users could toggle the behavior themselves.

**Comment by bcakmakoglu** [comment]
Might be a duplicate of #2167

**Comment by cgross** [comment]
Yes you're right.  Closing this one.
