### ISSUE TITLE
v11 build errors

### ISSUE THREAD

**Issue by fr1n63** [wbkd/react-flow#2453]
### Describe the Bug

I've just had a go at upgrading to v11 from v10 - I'm seeing 3 build errors. Current react version is 17.0.2, which you've indicated should be compatible? I don't think I should be having to add new loaders no?

```
✖ ｢wdm｣:
ERROR in /node_modules/@reactflow/core/dist/esm/index.js 16:19
Module parse failed: Unexpected token (16:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| function Attribution({ proOptions, position = 'bottom-right' }) {
>     if (proOptions?.hideAttribution) {
|         return null;
|     }

ERROR in /node_modules/@reactflow/minimap/dist/esm/index.js 36:31
Module parse failed: Unexpected token (36:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| function MiniMap({ style, className, nodeStrokeColor = '#555', nodeColor = '#fff', nodeClassName = '', nodeBorderRadius = 5, nodeStrokeWidth = 2, maskColor = 'rgb(240, 242, 243, 0.7)', position = 'bottom-right', }) {
|     const { boundingRect, viewBB, nodes, rfId } = useStore(selector, shallow);
>     const elementWidth = style?.width ?? defaultWidth;
|     const elementHeight = style?.height ?? defaultHeight;
|     const nodeColorFunc = getAttrFunction(nodeColor);

ERROR in /node_modules/@reactflow/controls/dist/esm/index.js 43:17
Module parse failed: Unexpected token (43:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const onZoomInHandler = () => {
|         zoomIn();
>         onZoomIn?.();
|     };
|     const onZoomOutHandler = () => {
ℹ ｢wdm｣: Failed to compile.
```

### Steps to Reproduce the Bug or Issue

1. Remove `react-flow-renderer`
2. Add `reactflow`
3. Change import package names
4. Rebuild

### Expected behavior

I expected my application to build as before

### Platform

- OS: Linux
- Browser: Chrome - n/a

**Comment by moklick** [comment]
Thanks for the report. How does the build setup look like?

**Comment by fr1n63** [comment]
We're slightly non-standard, but at the root it's just webpack ^4.44.1 and babel ^7.12.3

**Comment by moklick** [comment]
Are you excluding all node_modules from being transpiled with babel?

**Comment by fr1n63** [comment]
Babel loader is below - looks to be excluding `node_modules`

```
{
  test: /\.(js|ts|tsx)$/,
  exclude: /node_modules/,
  use: [
    {
      loader: 'babel-loader',
      options: {
        cacheDirectory: true,
        presets: [
          [
            '@babel/preset-env',
            {
              targets: targetNode ? {node: 'current'} : BROWSERS_LIST,
              useBuiltIns: 'usage',
              corejs: 3.12,
              bugfixes: true,
              debug: true,
              modules: targetNode ? 'commonjs' : 'auto',
            },
          ],
          ['@babel/preset-typescript', {allowDeclareFields: true}],
          '@babel/preset-react',
        ],
        plugins: [
          'babel-plugin-lodash',
          '@babel/plugin-syntax-import-meta',
          '@babel/plugin-proposal-nullish-coalescing-operator',
          '@babel/plugin-proposal-optional-chaining',
          '@babel/plugin-proposal-json-strings',
          ['@babel/plugin-proposal-class-properties', {loose: false}],
          '@babel/plugin-proposal-export-default-from',
        ],
      },
    },
  ],
},
```

**Comment by moklick** [comment]
can you try: `exclude:  /node_modules(?!\/reactflow)/` for now?

**Comment by moklick** [comment]
my fault. Try this: `exclude: /node_modules(?!\/@reactflow)/`

**Comment by fr1n63** [comment]
Ok that's built now - not getting any diagrams but I expect that will be something else entirely! Thanks

**Comment by moklick** [comment]
are you including the styles? `import 'reactflow/dist/style.css'`

**Comment by fr1n63** [comment]
Yeah - that's fine - there seems to have been a subtle shift in the way `defaultNodes` and `defaultEdges` are being used - in v10 you could update them and the diagram would update - I was using that as a cheap/hack way of managing the nodes externally, but not having to handle `onNodesChange` - The sort of work thing you always expect to bite later.

**Comment by moklick** [comment]
This is weird. There should not be a different behaviour. How are you updating the nodes?

**Comment by fr1n63** [comment]
I have an external immer reducer that I keep the nodes/edges in, they're provided to the component via context. This is mostly because I have a text editor that allows me to simultaneously edit the flow in json. Any updates would come just update into the `defaultNodes` and `defaultEdges` props - It worked fine in v10.

I wasn't using the normal process of `nodes`/`edges`/`onNodesChange` because the drag became laggy with an additional update eating a frame.

**Comment by moklick** [comment]
I would really try to understand this, because this change wasn't intended and we haven't change anything about the defaultNodes / nodes handling in general. With an uncontrolled flow you should always use the `setNodes`, `setEdges` functions or the store to update the elements but I am wondering why your hack isn't working anymore. You are mutating the nodes array that is used for `defaultNodes`?

**Comment by fr1n63** [comment]
Yes - that's correct. I would modify the `defaultNodes` prop and this would effectively reset the graph to a new state. That doesn't appear to be happening anymore.

I have a fix for my code using `nodes`/`onNodesChange` now - It felt like the method I was using was most likely a bug/oversight - rather than intended behaviour.

**Comment by cgross** [comment]
I'm having the same build issues now too.  I'm excluding the reactflow lib from babel but its still complaining.  Although after adding the exclude, it stopped complaining about the `onZoomIn?.();` in `controls` and started complaining about the `if (proOptions?.hideAttribution) {` in `core`.  Here's my babel config:

```
                        {
                            test: /\.(js|mjs)$/,
                            exclude: [
                                /@babel(?:\/|\\{1,2})runtime/,  
                                /node_modules(?!\/@reactflow)/
                            ],
                            loader: require.resolve('babel-loader'),
                            options: {
                                babelrc: false,
                                configFile: false,
                                compact: false,
                                presets: [[require.resolve('babel-preset-react-app/dependencies'), { helpers: true }]],
                                cacheDirectory: true,
                                cacheCompression: isEnvProduction,

                                // If an error happens in a package, it's possible to be
                                // because it was compiled. Thus, we don't want the browser
                                // debugger to show the original code. Instead, the code
                                // being evaluated would be much more helpful.
                                sourceMaps: false,
                            },
                        },
```

Any help would be appreciated.

**Comment by Bartel-C8** [comment]
For the ones using `electron-webpack` (using webpack 4, but obscuring config (which _should_ make it easier, most of the time) some fixing code:

In your `webpack.renderer.additions.js` file:
```
module.exports = (config) => {
  config.module.rules.push({
    test: /\.(js|ts|tsx)$/,
    include: /node_modules\/@reactflow/,
    use: {
      loader: 'babel-loader',
      options: { presets: ['@babel/preset-env'] } // Presets used for env setup
    }
  });
}
 ```
 
 If you don't have a `webpack.renderer.additions.js` yet, create it and enable it in your `package.json`:
 ```
 ...
   "electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.additions.js"
    }
   },
  ...
  ```

**Comment by cgross** [comment]
Thanks @Bartel-C8.  I was able to get around it by padding the necessary babel plugins to process reactflow rather than excluding it.

**Comment by Jasminou** [comment]
@moklick I still getting the same errors with v11.5.6. even with your suggestions for this thread:

I've this below in my storybook main.js and still getting the errors below:

      config.module?.rules.push({
        test: /\.(ts|js)x?$/,
        exclude: '/node_modules/',
        include: '/node_modules/react-flow-renderer/',
        use: ['babel-loader', 'source-map-loader']
      });

I'm using:
 "babel-loader": "8.1.0",
 "webpack": "4.44.2"
 "react-scripts": "^4.0.3",
  "storybook": "^6.5.13", (can't update to latest for now).
 "react": "^17.0.2",

<img width="1379" alt="Screenshot 2023-02-23 at 22 04 35" src="https://user-images.githubusercontent.com/14798195/221082069-a04d109b-7112-490d-8c5a-684419c116f1.png">

<img width="1379" alt="Screenshot 2023-02-23 at 22 04 42" src="https://user-images.githubusercontent.com/14798195/221082088-c026afa3-610c-496e-9ba0-263eeb26331a.png">

**Comment by moklick** [comment]
@Jasminou can you try `exclude: /node_modules(?!\/@reactflow)/`?

**Comment by Jasminou** [comment]
@moklick I did try with `exclude: /node_modules(?!\/@reactflow)/` same thigs I also tried some of the suggestions with the include but didn't work

**Comment by saeedhemmati** [comment]
I use CRA and craco for override the default configuration. i get the same error. how can i set babel config in craco for solve this problem?

**Comment by ChristopherTeague** [comment]
We are also having the same issue and using the babelrc file. Can someone let us know how to get this working.

**Comment by sumengwang** [comment]
Will webpack v5 automatically resolve this issue?

**Comment by Vladislav747** [comment]
For those who use CRA and react-rewired you can create config-overrides.js file and put it there(it worked for me)


```code

module.exports = function override(config, env) {
    // Exclude /node_modules(?!\/reactflow) from babel-loader
    const babelLoaderRule = config.module.rules.find((rule) => rule.oneOf);
    if (babelLoaderRule) {
        babelLoaderRule.oneOf.forEach((rule) => {
            if (rule.loader && rule.loader.includes("babel-loader")) {
                rule.exclude = [/node_modules[\\/](?!@reactflow[\\/])/];
            }
        });
    }

    // Add separate rule for @reactflow/controls package
    config.module.rules.push({
        test: /\.js$/,
        include:
            /@reactflow[\\/](controls|core|node-resizer|node-toolbar|minimap)[\\/]/,
        use: {
            loader: "babel-loader",
            options: {
                presets: ["@babel/preset-env", "@babel/preset-react"],
                plugins: [
                    "@babel/plugin-proposal-optional-chaining",
                    "@babel/plugin-proposal-nullish-coalescing-operator",
                ],
            },
        },
    });

  
    return config;
};
```

**Comment by moklick** [comment]
If you are using webpack 4, you need to install

```
npm i --save-dev babel-loader@8.2.5 @babel/preset-env @babel/preset-react @babel/plugin-proposal-optional-chaining @babel/plugin-proposal-nullish-coalescing-operator
```

and configure the loader like this:

```js
{
      test: /node_modules[\/\\]@?reactflow[\/\\].*.js$/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env', "@babel/preset-react"],
          plugins: [
            "@babel/plugin-proposal-optional-chaining",
            "@babel/plugin-proposal-nullish-coalescing-operator",
          ],
        },
      },
    }
```

in order to transpile reactflow correctly. With webpack 5 there shouldn't be any issues.

**Comment by AustinMKerr** [comment]
So I'm having this same issues. I have created - react- app 4 and react-scripts is being used I can't figure out how to set any sort of config with babel that holds. 

I'd be happy to use the older version 10 for my needs but can't find the documentation live any where. 

here's my package.json


},
    "engines": {
        "node": "^15.10.0"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject",
        "heroku-prebuild": "npm i -f",
        "heroku-postbuild": "npm run build"
    },
    "devDependencies": {
        "@babel/plugin-proposal-optional-chaining": "^7.21.0",
        "@babel/preset-env": "^7.23.9",
        "react-bootstrap-slider": "^3.0.0",
        "react-error-overlay": "6.0.9"
    },
    "eslintConfig": {
        "extends": [
            "react-app",
            "react-app/jest"
        ]
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    }

**Comment by Anguimru** [comment]
> For those who use CRA and react-rewired you can create config-overrides.js file and put it there(it worked for me)

For React Flow v12 I've used this solution successfully without ejecting the CRA (create-react-app) using react-rewired

- Install dependencies
`npm install --save-dev react-app-rewire@babel/plugin-proposal-optional-chaining @babel/plugin-proposal-nullish-coalescing-operator @babel/plugin-proposal-logical-assignment-operators`

- Create **config-overrides.js** in you project with the content
```
module.exports = function override(config, env) {
    // Exclude /node_modules(?!\/@xyflow\/react) from babel-loader
    const babelLoaderRule = config.module.rules.find((rule) => rule.oneOf);
    if (babelLoaderRule) {
        babelLoaderRule.oneOf.forEach((rule) => {
            if (rule.loader && rule.loader.includes("babel-loader")) {
                rule.exclude = [/node_modules[\\/](?!@xyflow[\\/])/];
            }
        });
    }

    // Add separate rule for @xyflow packages
    config.module.rules.push({
        test: /\.js$/,
        include: /@xyflow[\\/]/,
        use: {
            loader: "babel-loader",
            options: {
                presets: ["@babel/preset-env", "@babel/preset-react"],
                plugins: [
                    "@babel/plugin-proposal-optional-chaining",
                    "@babel/plugin-proposal-nullish-coalescing-operator",
                    "@babel/plugin-proposal-logical-assignment-operators"
                ],
            },
        },
    });

    return config;
};
```
- Modify in **package.json** the **start** and **build** scripts
```
"start": "react-app-rewired start",
"build": "react-app-rewired build",
```

**Comment by scottsut** [comment]
https://github.com/dagrejs/dagre/issues/436
