### ISSUE TITLE
Edge with Button Docs example not working

### ISSUE THREAD

**Issue by tauling** [wbkd/react-flow#2456]
### Describe the Bug

The Docs include an [Edge with Button](https://reactflow.dev/docs/examples/edges/edge-with-button/) example that does not run due to the import of `getEdgeCenter`.

### Your Example Website or App

https://codesandbox.io/s/cuj7lk?file=%2FApp.js&from-sandpack=true

### Steps to Reproduce the Bug or Issue

1. Visit https://reactflow.dev/docs/examples/edges/edge-with-button/

### Expected behavior

Sandbox executes without error message.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/10166345/192967742-742f0462-ba90-43aa-9ab1-afdc87a53d2c.png)

### Platform

- OS: [Linux]
- Browser: [Chromium]

**Comment by moklick** [comment]
thanks @tauling !
