### ISSUE TITLE
Prevent dragging beyond react-flow container

### ISSUE THREAD

**Issue by mohannva** [wbkd/react-flow#2459]
### Please describe the feature that you want to propose

Hi team,

Great seeing some of the new updates come through. Recently have been trying to limit where nodes can be dragged in the application and have been using the "nodeExtent" props. With the goal being nodes can only be dragged in the react-flow container and not neighboring divs. To do so, I took the x/y coordinates of the container div and and passed them through to nodeExtent.

The issue then becomes when I zoom in or out/scroll, the nodes will not drag all the way around the viewable canvas (stopped by the nodeExtent prop). Is there any props that can be used to bind the nodeExtent to the "current max dimensions" of the viewable canvas (i.e., can't drag nodes past the boundaries of the react-flow container...to drag nodes further you must zoom out?)

**Comment by mohannva** [comment]
For

**Comment by moklick** [comment]
This is not built-in. To achieve this, you would always need to do some custom calculations for the nodeExtent and maybe also re-position the nodes on resize.
