### ISSUE TITLE
Need help understanding the raw Implementation

### ISSUE THREAD

**Issue by agrawal-rohit** [wbkd/react-flow#247]
Hey, I was trying to create a visual scripting framework using node graphs and react when I stumbled upon your library. It was exactly what I was looking for, however, it had such high abstraction that I had to stop using it. I tried implementing one on my own but ran into various issues and thus I'm stuck.

Can you help me understand what libraries are you under the hood and for what purpose? I'd like the create my own version of it. Also, any helpful resources towards understanding the implementation would be greatly appreciated :))

**Comment by moklick** [comment]
Hey @agrawal-rohit 

thanks for your interest. We are using `d3-zoom` for the zooming and panning, `react-draggable` for the dragging and `easy-peasy` for the state handling. 

I hope you understand that we cannot discuss the raw implementation here. The code is open source and you can see the details for yourself.

Maybe you can find another library that fits your needs. For example https://rete.js.org/#/

**Comment by agrawal-rohit** [comment]
Thanks for all the help :). I checked out Rete.js, it looks much more suitable for my purposes.
