### ISSUE TITLE
Sub Flow group node & TypeScript: 'className' does not exist

### ISSUE THREAD

**Issue by kahboom** [wbkd/react-flow#2470]
### Describe the Bug

Hello! I can't seem to use the `className` property for Sub Flow groups, as shown in the example [here](https://reactflow.dev/docs/examples/layout/sub-flows/), with TypeScript.

```bash
Type '{ width: number; height: number; className: string; style: { backgroundColor: string; width: number; height: number; }; }' is not assignable to type 'Properties<string | number, string & {}>'.

Object literal may only specify known properties, and 'className' does not exist in type 'Properties<string | number, string & {}>'.  nodes.d.ts(10, 5): The expected type comes from property 'style' which is declared here on type 'IVizStepNode'
```

Where `IVizStepNode` is as follows:

```js
export interface IVizStepNodeData {
  icon?: string;
  kind?: string;
  label: string;
  step?: IStepProps;
  ...
}

// "extend" React Flow's `Node` type
export type IVizStepNode = Node & {
  data: IVizStepNodeData;
};
```

### Your Example Website or App

https://github.com/kahboom/kaoto-ui/tree/branching

### Steps to Reproduce the Bug or Issue

Create a `Node` for a Sub Flow group with properties similar to these:

```js
export function insertBranchGroupNode(
  stepNodes: IVizStepNode[],
  originStepNode: IVizStepNode,
  branch: IStepPropsBranch,
  position: { x: number; y: number },
  groupHeight: number,
  groupWidth: number
) {
  return stepNodes.unshift({
    id: getRandomArbitrary(100, 999).toString(),
    type: 'group',
    position,
    data: {
      parentUuid: originStepNode.data.UUID,
      branch,
    },
    style: {
      width: groupWidth,
      height: groupHeight,
      className: 'light',
      style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 200, height: 200 },
    },
  });
}
```

### Expected behavior

I should be able to use the `className` property without a TS warning

### Screenshots or Videos

![Screen Shot 2022-10-04 at 2 39 12 pm](https://user-images.githubusercontent.com/3844502/193836384-47744545-780d-4e76-a4fa-1033c1b87490.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 11.0.0-next.13
- IDE: WebStorm

**Comment by moklick** [comment]
no worries :)
