### ISSUE TITLE
Error: Failed to compile after install reactflow 11.1.0

### ISSUE THREAD

**Issue by thanhvk** [wbkd/react-flow#2475]
### Describe the Bug

Hi,

After install reactflow version 11.1.0 in my app and run 'yarn start' I get this error in log

```
./node_modules/@reactflow/controls/dist/esm/index.js 107:13
Module parse failed: Unexpected token (107:13)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const onZoomInHandler = () => {
|     zoomIn();
>     onZoomIn?.();
|   };
|
```

I use react version 17.0.2, react-scritps 4.0.3

### Steps to Reproduce the Bug or Issue

1. Add reactflow: yarn add reactflow
2. Use reactflow in component (can use example)
3. Start app: yarn start

### Expected behavior

App start & build normally

### Platform

- OS: Ubuntu
- Browser: Chrome

**Comment by thanhvk** [comment]
After upgrade reactscripts from 4 to 5 and delete yarn.lock & node_modules it work well. So I close this issue.

**Comment by moklick** [comment]
We are not transpiling React Flow anymore. You need to make sure to transpile it.
