### ISSUE TITLE
useOnSelectionChange never fires

### ISSUE THREAD

**Issue by royletron** [wbkd/react-flow#2484]
### Describe the Bug

I am attempting to use the examples for `<ReactFlowProvider>` and `useOnSelectionChange` but never get the selection change to fire

### Your Example Website or App

https://codesandbox.io/s/green-worker-pz6fvj?file=/src/App.tsx

### Steps to Reproduce the Bug or Issue

The console should print the selected node. I can tell the node is selected because the border is thicker...

### Expected behavior

I expect the console to fire with the selected node

### Platform

- OS: macOS
- Browser: Chrome
- Version: 105

**Comment by saad995** [comment]
Dear @royletron , as mentioned in the documentation 'useOnSelectionChange' is a hook that listens to selection changes.

Therefore a onSelectionChange must be defined which gets triggered when you select your node.
Just for an example I have modified your provided sandboxcode a little: https://codesandbox.io/s/infallible-frog-3v11j9?file=/src/App.tsx

Moreover for a better understanding use more than one node.

**Comment by royletron** [comment]
@saad995 appreciate the help. It's actually not all that clear from the docs - in fact I see nowhere that mentions that it's dependant on the presence of a `onSelectionChange` prop. Do you know if this was a conscious choice? It seems quite anit-pattern to have to have a `prop` that determines whether a `context` based hook can be used... They're typically used as an alternative to one another.

**Comment by saad995** [comment]
Hmm, you might be right on this.

I just checked their source code, they haven't set the state 'onSelectionChange' in their initial state, and may be that's the reason why UseOnSelectionChange makes no impact.

Let's see what the library developers say about this.

**Comment by moklick** [comment]
This is a bug! Will be fixed tomorrow :) Thanks for the report.
