### ISSUE TITLE
Detecting changes made in Flow Diagram i.e. Adding node, deleting edge.

### ISSUE THREAD

**Issue by jamshaidbutt055** [wbkd/react-flow#2486]
### Please describe the feature that you want to propose

Library should expose a method to get the changes made in Nodes or Edges array. For example if I load a Flow in library and then add or delete node or edge there after calling a method, library should return me changes made in actual Data and that data must be filterable, like if we want to check only if nodes are added or deleted etc.

**Comment by bcakmakoglu** [comment]
That sounds exactly like what `onNodesChange` and `onEdgesChange` already do.
Check out the examples and play around a bit: https://reactflow.dev/docs/examples/overview/.

You can see the following piece of code
```js
const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

return (
	 <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange} // <---
      onEdgesChange={onEdgesChange} // <---
      onConnect={onConnect}
      onInit={onInit}
      fitView
      attributionPosition="top-right"
    >
```

`onNodesChange` that is provided by `useNodesState` will apply the default change handlers whenever a change event is emitted (i.e. adding, dragging, removing & selecting nodes).
You can just hook into that process and do whatever you need before applying those handlers.
```ts
const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

const onNodesChangeHandler = (changes: NodeChange[]) => {
	changes.forEach((change) => {
		if (change.type === 'remove') {
			console.log(change.id) // id of the node to be removed
		}
	})

	onNodesChange(changes)
}

 <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChangeHandler} // <--- add your own handler
      onEdgesChange={onEdgesChange} // <---
      onConnect={onConnect}
      onInit={onInit}
      fitView
      attributionPosition="top-right"
    >
```

**Comment by moklick** [comment]
thanks @bcakmakoglu 🙏
