### ISSUE TITLE
Image is behaving weird

### ISSUE THREAD

**Issue by Keanottesen** [wbkd/react-flow#2499]
### Describe the Bug

When I take an image with the suggested method in the documentation some of the labels inside nodes jumps to a new line.

### Your Example Website or App

https://app.juristic.io/public/koncerndiagrammer/U2FsdGVkX1%2FwFgQhj1dd5%2FAhhZemQFv2rvVNbdTbuaA%3D?cvr=42353639

### Steps to Reproduce the Bug or Issue

Take an image in the top left corner

<img width="1436" alt="Screenshot 2022-10-14 at 15 19 53" src="https://user-images.githubusercontent.com/47158972/195857056-80e6f911-f5a1-4807-b98c-0d5acf968eac.png">

### Expected behavior

I expect the image to look like what it does in the browser.

### Screenshots or Videos

[Uploading 42353639.pdf…]()

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
OS: macOS
Browser: Chrome
Version: 105.0.5195.125

**Comment by moklick** [comment]
I can't reproduce it. If you find any bugs with html-to-img, please open an issue in the corresponding repository. One thing you could try is to only make a screenshot from the flow and the whole app. Maybe it helps.

**Comment by chrtze** [comment]
@Keanottesen could this happen because the font is different in the screenshot than in the app? Maybe you need to configure html-to-img to render the same font?

**Comment by moklick** [comment]
Please re-open if the issue still persists.
