### ISSUE TITLE
Error: Cannot find module 'react/jsx-runtime

### ISSUE THREAD

**Issue by flexfranklin** [wbkd/react-flow#2501]
### Describe the Bug

While I run `yarn dev`, it said `error - Error: Cannot find module 'react/jsx-runtime'`.

I am new to react-flow. I try to use it in my project with next-js, typeScript and react.

I tried to upgrade react and re-general node_modules, but it doesn't work.

I am blocked here, could you provide help? Thanks.

Following is what I tried:
```
# 👇️ with NPM
npm install react@latest react-dom@latest

# 👇️ ONLY If you use TypeScript
npm install --save-dev @types/react@latest @types/react-dom@latest

# ----------------------------------------------

# 👇️ with YARN
yarn add react@latest react-dom@latest

# 👇️ ONLY If you use TypeScript
yarn add @types/react@latest @types/react-dom@latest --dev

# 👇️ delete node_modules and package-lock.json
rm -rf node_modules
rm -f package-lock.json

# 👇️ clean npm cache
npm cache clean --force

npm install
```

### Steps to Reproduce the Bug or Issue

My package.json

```
{
  "name": "baton",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.3",
    "@heroicons/react": "^2.0.12",
    "next": "^12.3.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/node": "18.8.2",
    "@types/react": "^18.0.5",
    "@types/react-dom": "^18.0.1",
    "autoprefixer": "^10.4.12",
    "eslint": "8.24.0",
    "eslint-config-next": "12.3.1",
    "postcss": "^8.4.17",
    "tailwindcss": "^3.1.8",
    "typescript": "4.8.4"
  }
}

```

### Expected behavior

`yarn dev` run without error.

Webpage display as expected in browser.

### Screenshots or Videos

<img width="1331" alt="Screen Shot 2022-10-16 at 00 21 19" src="https://user-images.githubusercontent.com/104409087/195997154-1c03290c-b7d7-47f9-8cb1-6a44aee498a8.png">

<img width="1082" alt="Screen Shot 2022-10-16 at 00 22 01" src="https://user-images.githubusercontent.com/104409087/195997173-d9da4fe6-c847-4d4a-bec7-c7097579b202.png">

### Platform

- OS: max-os
- Browser: Crhome
- Version: [e.g. 91.1]

**Comment by nikkidurkin** [comment]
I'm having the same issue. How did you resolve it @flexfranklin ? Thanks!

**Comment by moklick** [comment]
@nikkidurkin you need React 17 or 18 to use React Flow.

**Comment by nikkidurkin** [comment]
Ugh, duh. I'm so silly. Thanks for replying!

**Comment by moklick** [comment]
@nikkidurkin no need to feel bad :)
