### ISSUE TITLE
React flow components display not as expected

### ISSUE THREAD

**Issue by flexfranklin** [wbkd/react-flow#2502]
### Describe the Bug

I am new to the React Flow. I want to use it in my project.

While I tried the example in website, but it didn't work as expected. Could you help me to figure it why?

<img width="659" alt="Screen Shot 2022-10-16 at 12 21 29" src="https://user-images.githubusercontent.com/104409087/196017856-ac2267f8-c725-4529-82a6-c21bc787bcbc.png">

### Steps to Reproduce the Bug or Issue

1. Install nextJS
2. Create nextJS project with TypeScript, React and tailwind css. Following is library and related versions I am using:
<img width="360" alt="Screen Shot 2022-10-16 at 12 30 17" src="https://user-images.githubusercontent.com/104409087/196018135-1039d2cb-a3b4-44e9-855a-e2a1b9c0c73f.png">

3. Install ReactFlow
4. Use below code
Below is the example code I used:
```
import {useCallback} from "react";
import ReactFlow, {
  MiniMap,
  Controls,
  Background,
  useNodesState,
  useEdgesState,
  addEdge,
} from "reactflow";

const initialNodes = [
  {id: "1", position: {x: 0, y: 0}, data: {label: "1"}},
  {id: "2", position: {x: 0, y: 100}, data: {label: "2"}},
];

const initialEdges = [{id: "e1-2", source: "1", target: "2"}];

export default function ProcedureFlow() {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onConnect = useCallback(
    (params) => setEdges((eds) => addEdge(params, eds)),
    [setEdges]
  );

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
    >
      <MiniMap />
      <Controls />
      <Background />
    </ReactFlow>
  );
}

```

### Expected behavior

UI display like example:
<img width="1064" alt="Screen Shot 2022-10-16 at 11 33 25" src="https://user-images.githubusercontent.com/104409087/196016675-b7561a9b-6350-4ddc-add2-da5e573fea14.png">

### Screenshots or Videos

My UI screenshot:
<img width="659" alt="Screen Shot 2022-10-16 at 12 21 29" src="https://user-images.githubusercontent.com/104409087/196017818-5ca97a66-a8c8-4d3d-8cc4-760250b6cccd.png">

### Platform

- OS: macOS (
ProductVersion:	12.6
BuildVersion:	21G115)
- Browser: Chrome (Version 106.0.5249.119 (Official Build) (x86_64))

**Comment by moklick** [comment]
Hey! Are you importing the styles in _app.tsx like this: https://github.com/wbkd/react-flow-example-apps/blob/main/reactflow-nextjs/src/pages/_app.tsx#L4

**Comment by flexfranklin** [comment]
Thank you @moklick ! Yeah I think it works now!
