### ISSUE TITLE
How to add node programmatically?

### ISSUE THREAD

**Issue by edhyah** [wbkd/react-flow#2506]
### Describe the Bug

Based on [this](https://codesandbox.io/s/react-flow-add-node-button-l9rcu) link. The idea is to have a button generate a new node and I can't seem to add any nodes. Specifically, when I press the "add" button, nothing happens.

To build my code, simply install a fresh template via:
```
npx create-react-app my-app
cd my-app
npm install reactflow
```

Then, use the following code for `App.js`.
```
import React, { useCallback, useRef } from "react";
import 'reactflow/dist/style.css';

import ReactFlow, {
  useNodesState,
} from 'reactflow';
const initialNodes = [
  {
    id: "1",
    type: "input", // input node
    data: { label: "Input Node" },
    position: { x: 100, y: 0 }
  }
];

export default function App() {
  const yPos = useRef(0);
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);

  const addNode = useCallback(() => {
    yPos.current += 50;
    setNodes((nds) => nds.concat({
      id: Math.random(),
      position: { x: 100, y: yPos.current },
    }));
  }, [setNodes]);

  return (
    <div className="App">
      <div style={{ height: 300 }}>
        <ReactFlow
          nodes={nodes}
          onNodesChange={onNodesChange}
        />
      </div>
      <button onClick={addNode}>Add</button>
    </div>
  );
}
```

I believe the problem is that the `nodes` array isn't triggering a re-render. What am I doing wrong?

### Steps to Reproduce the Bug or Issue

Listed above

### Expected behavior

Outlined above

### Platform

- OS: Linux
- Browser: Firefox
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
You need to use a string as the node id.
Change `id: Math.random()` to 
```
id: `${Math.random()}`
```
 and your code works fine.

**Comment by edhyah** [comment]
Ahhh thank you! Really appreciate the helpful + quick response :)
