### ISSUE TITLE
how to use viewport left-top point (0, 0) as zoom reference point, not current mouse position

### ISSUE THREAD

**Issue by zackshen** [wbkd/react-flow#2509]
Hello dear react-flow team,

I have working with react-flow several days, it's an awesome library to draw diagram. now i have a feature, but i can not find any solution in react-flow document or github issues. 
the feature is , when zooming the diagram, I want to use the viewport's left-top point (0, 0) as zoom reference point, so the diagram will not move, only the diagram's width and height changed. I want the viewport position is always stay at point (0, 0)。

**Comment by zackshen** [comment]
Hello react-flow team,

After reading the react-flow source code，I have resolved this problem，thx。

**Comment by zackshen** [comment]
Please close this issue

**Comment by moklick** [comment]
Hey @zackshen 

how did you solve it?

**Comment by zackshen** [comment]
react-flow `11.1.1`.
My hacking progress.

1. disable `zoomOnScroll`, `panOnDrag`
```jsx
      <ReactFlow
        onWheelCapture={handleWheel}
        panOnDrag={false}
        zoomOnScroll={false}
      >
        <Background />
      </ReactFlow>
```
2. wrap a container for react-flow , and add `onWheel` event listener
```jsx
<div onWheel={handleWheel}>
      <ReactFlow
        onWheelCapture={handleWheel}
        panOnDrag={false}
        zoomOnScroll={false}
      >
        <Background />
      </ReactFlow>
</div>
```

3. handler `handleWheel`
```js
const handleWheel = () => {
      const { d3Zoom, d3Selection } = store.getState();
      if (!d3Zoom || !d3Selection) {
        return;
      }
      const currentZoom = d3Selection.property('__zoom').k || 1;
      const { deltaY } = event;
      const ratio = deltaY / 1500;
      const getD3Transition = (selection: any, duration = 0) => {
        return selection.transition().duration(duration);
      };

      // set the reference point argument.
      d3Zoom.scaleTo(getD3Transition(d3Selection), currentZoom + ratio, [0, 0]);
}
```

4. I add two button for controll `zoomIn`, `zoomOut`
```js
setZoom(zoomLevel:  number) {
    const getD3Transition = (selection: any, duration = 0) => {
      return selection.transition().duration(duration);
    };

    const { d3Zoom, d3Selection } = this._store.getState();

    // set the reference point argument.
    d3Zoom.scaleTo(getD3Transition(d3Selection), zoomLevel, [0, 0]);
}
```
