### ISSUE TITLE
Docs: Edge with Button outdated

### ISSUE THREAD

**Issue by stefanpl** [wbkd/react-flow#2512]
### Describe the Bug

The [Edge with Button](https://reactflow.dev/docs/examples/edges/edge-with-button/) example seems outdated.

## `getBezierPath`

Inside ButtonEdge.js, `getBezierPath` is called but then destructured:
```javascript
// does not work. edgePath will just be one character.
const [edgePath, labelX, labelY] = getBezierPath({
    // ...
  });
```
This does not work, since getBezierPath returns the path as a string.

I think it needs be combined with `getBezierEdgeCenter` in order to get values for `labelX` and `labelY`, but the path needs be obtained directly:

```javascript
const edgePath = getBezierPath({ 
  // … 
})
const [labelX, labelY] = getBezierEdgeCenter({
 // ... same params
})
```

## `<body>`

In addition, my setup (Next.js 12, react 18) did not like at all the `<body>` tag inside `<foreignObject>`. I just removed it and it seems to work fine.

### Steps to Reproduce the Bug or Issue

Copy the "Edge with Button" example and try to run it.

### Expected behavior

Edges not showing when copying code from docs.

### Platform

React 18
Next.js 12
react-flow-renderer 10

**Comment by bcakmakoglu** [comment]
In v11 `getBezierPath` has been changed to return the centerX and centerY positions as well as the path string, furthermore the `getEdgeCenter` utility has been removed.

So if you're using v10, yes you need to use those two separately.
In v11 it's exactly as shown in the examples, you destructure `getBezierPath` (or `getSmoothStepPath`) to receive the path string and center values.

**Comment by stefanpl** [comment]
Aaaah, I see. I completely was not aware of v11. I event to npm to check if I'm on the latest version.

May I then propose that a hint of some form is added [here](https://www.npmjs.com/package/react-flow-renderer), indicating that this is an outdated package and the new one has a different name?

Thanks for the quick reply 🙏

**Comment by moklick** [comment]
@stefanpl good point! we will add a deprecated message or something like that.
