### ISSUE TITLE
ERROR in [eslint] Package subpath './dist/types' is not defined by "exports"

### ISSUE THREAD

**Issue by 32teeth** [wbkd/react-flow#2527]
### Describe the Bug

```
npm i react-flow-renderer
npm run start
```

> error

```
ERROR in [eslint] Package subpath './dist/types' is not defined by "exports" in node_modules/react-flow-renderer/package.json
```

### Steps to Reproduce the Bug or Issue

```
npm i react-flow-renderer
npm run start
```

> error

```
ERROR in [eslint] Package subpath './dist/types' is not defined by "exports" in node_modules/react-flow-renderer/package.json
```

### Expected behavior

No error

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey. The react-flow-renderer package is deprecated. Could you update to the latest version and check if the error still occurs? https://reactflow.dev/docs/guides/migrate-to-v11/
