### ISSUE TITLE
Edge update with simple floating edge disappear when is clicked to update to another handle. 

### ISSUE THREAD

**Issue by DiegoLibonati** [wbkd/react-flow#2529]
### Describe the Bug

When you try to grab the arrow from the source it disappears but if you grab it from the target it shows up.

I need to know if this behavior is normal, I'm using simple floating edge + edge update

I leave a video of how to replicate this in the documentation.

Have a nice day!

### Steps to Reproduce the Bug or Issue

1. Follow the steps on video.

### Expected behavior

When you try to take the arrow from the source it disappears but it has to be displayed.

### Screenshots or Videos

https://user-images.githubusercontent.com/99032604/199021604-571ee75a-f2d4-4c7f-8560-65fd54f7797c.mp4

### Platform

- OS: Windows
- Browser: Chrome
- Version: Last version

**Comment by moklick** [comment]
Thanks for the report! One issue could already be fixed by specifying `sourceHandle` and `targetHandle` (that's necessary when there are multiple handles, the example wasn't correct). The other issue with the disappearing connection line will be fixed in the next release.

**Comment by moklick** [comment]
Fixed in v11.3.0 🚀
