### ISSUE TITLE
Minimap interrupts multi-select sweep box

### ISSUE THREAD

**Issue by satyasinha** [wbkd/react-flow#2533]
### Describe the Bug

Hello!

We found an issue where when multi-selecting nodes via click + dragging, the selection box is interrupted when the mouse is over the minimap. Is it possible to not interrupt the box? or close the selection box when the mouse reaches the minimap with the existing selections?

### Steps to Reproduce the Bug or Issue

1. Hold down shift on a react flow instance to start drawing a box around multiple entities
2. With SHIFT and mouse button down, mouse over the minimap
3. Hovering over the mini-map aborts the multi-select process and nothing is selected.

### Expected behavior

We would prefer multi-selection box continuous to be drawn.

### Screenshots or Videos

![multi-select-mini-map](https://user-images.githubusercontent.com/4054185/199359860-aef382dd-9b1a-47b6-9481-e9b7c056a797.gif)

### Platform

This is happening on all modern browser/OS combinations.

**Comment by moklick** [comment]
Hey @satyasinha ! This was fixed in 11.1.1. Your app looks nice :)

**Comment by satyasinha** [comment]
thank you on both accounts! :)

your library is great, keep up the good work!
