### ISSUE TITLE
I cannot find EdgeLabelRenderer component  from reactflow

### ISSUE THREAD

**Issue by wuyz-harder** [wbkd/react-flow#2540]
### Describe the Bug

when I want to import the EdgeLabelRenderer  from the reactflow，the VSCODE info that it can't find EdgeLabelRenderer ；
I don't know whether it is my mistake,could you give me some suggestions?my reactflow version is ^11.1.2.Thank you!

### Steps to Reproduce the Bug or Issue

1.import {EdgeLabelRenderer} from "reactflow" 

### Expected behavior

maybe I can import EdgeLabelRenderer  

### Platform

Windows 10

**Comment by wuyz-harder** [comment]
ok,maybe it is just about my version! respect!!

**Comment by bcakmakoglu** [comment]
The renderer was released with `11.2.0` so it's your version :) Try updating it to the latest and you should be fine.

**Comment by wuyz-harder** [comment]
> The renderer was released with [`11.2.0`](https://github.com/wbkd/react-flow/releases/tag/11.2.0) so it's your version :) Try updating it to the latest and you should be fine.

Thank you

**Comment by moklick** [comment]
@bcakmakoglu thanks, that's it.
