### ISSUE TITLE
Props that are generated when you start dragging new connection are missing for <StepEdge /> in react flow v11

### ISSUE THREAD

**Issue by DraksBG** [wbkd/react-flow#2541]
### Describe the Bug

On previous version of ReactFlow v10 whenever you start dragging new connection (Edge) to connect towards a new node the props that were coming and that were needed for were sourceX sourceY and targetX targetY everything was working as it should be, while as after updating to ReactFlow v11 and StepEdge component  when you start to create a connection the line is disappearing and you can't see it until you connect it, and the props that are specified are missing you got an error as well because of that.

### Steps to Reproduce the Bug or Issue

Update to ReactFlow v11
Select and Edge and start dragging new connection
The connection is not visible
Until you connect it to the new node and props are missing

### Expected behavior

Expected behavior
The connection should be visible from the begging of the dragging and props shouldn't be missing
Actual behavior
The connection is disappearing and the props are missing

### Screenshots or Videos

React flow v10 and StepEdge component  in that version
![React_flow_v10](https://user-images.githubusercontent.com/52380770/199694458-eb192aaf-5438-4ff6-bdd3-c4ca2456879f.png)
https://user-images.githubusercontent.com/52380770/199692811-140fe4b3-1109-406f-88e1-b3ecb8e4cc76.mp4

React flow v11 StepEdge component  in that version
React_flow_v11
![React_flow_v11](https://user-images.githubusercontent.com/52380770/199694492-5123bc8f-13f3-465f-908f-98a14688cad2.png)

https://user-images.githubusercontent.com/52380770/199694503-78e81fd4-8896-41fa-a1fb-9dfb67bd1eef.mp4

### Platform

OS: [Windows 10-11]
Browser [chrome, firefox]
Version [latest]

**Comment by moklick** [comment]
Hey @DraksBG 

is this about the [smart edge package](https://github.com/tisoap/react-flow-smart-edge) or React Flow?

**Comment by DraksBG** [comment]
@moklick this is regarding the update to React Flow v11 and how the props are changing when you start dragging a new connection, this don't happen if you at won react flow v10 and the new beta of SmartEdge.

**Comment by DraksBG** [comment]
@moklick Sorry for misunderstanding the problem is regarding <SmartEdge /> coming from react-flow  library in previous version it is receiving props that I have describe when you start to draw a new connection but in v11 those props are stop being created and <SmartEdge /> is expecting them. Could you please suggest a fix ?

**Comment by DraksBG** [comment]
@moklick I found a way to fix the issue but it was a bit hacky the props that are missing are now passed either as 0 0 0 0 value or as the fromX and fromY which are corresponding to sourceY and sourceX this is fixing the issue and you can now see the draw of the connection but when you get two nodes close to each other the connection is defaulting to 0 0 0 0 which are passed down as default value because (sourceX, sourceY, targetX and targetY) are missing as explained in this issue here


![screen_1](https://user-images.githubusercontent.com/52380770/199924324-98cc19b8-5899-4e07-a271-3dab5cbbf469.png)
![Screen_2](https://user-images.githubusercontent.com/52380770/199924327-694be3b5-46bd-4244-870f-565ce45e1912.png)

I am solving the issue as it follows 
![image](https://user-images.githubusercontent.com/52380770/199924901-f8c9bfd2-1d22-4927-83f9-0d9ef8c11d38.png)
that's because (sourceX, sourceY, targetX and targetY) are coming as undefined when you start dragging the connection tho I am gonna repeat my self in the older version those parameters where coming on drag as usual and what is StepEdge expecting now I am passing them as additional data because they are missing and the newProps are actually all the props coming from react flow.

**Comment by moklick** [comment]
hm thats's weird. I think that we just renamed those props. I'll have a look.

**Comment by DraksBG** [comment]
@moklick thank you, can you please check the first two screen shots at the begging of the issue, just for better understanding between the difference from v10 and v11.

**Comment by moklick** [comment]
could you create a codesandbox for this? Is this an issue with a custom connection line implementation?

**Comment by moklick** [comment]
Pease re-open if the issue still persists.
