### ISSUE TITLE
Add support for svg's `marker-mid` 

### ISSUE THREAD

**Issue by akhil-accuknox** [wbkd/react-flow#2542]
### Please describe the feature that you want to propose

We already have support for markerStart and markerEnd which is great and I would want to put forward this feature request to support `marker-mid`

screenshot - 
![image](https://user-images.githubusercontent.com/88323652/199701896-e8e82e73-bf5a-4e4e-9175-cdb36769afa4.png)

**Comment by chrtze** [comment]
Hi @akhil-accuknox, thanks for your request. I didn't know about the `marker-mid` property until now ;). Need to check if that's something we can and want to support. It would require to add some more default markers I guess because the current ones only make sense for markerStart and markerEnd.

**Comment by chrtze** [comment]
@akhil-accuknox could you provide some more details on why you would need support for this? I am trying to understand the value of such a property. These are my thoughts:

- We already have a convenient option to add elements such as icons, text etc. to the center of an edge by using edge labels
- It's also possible with custom edges where you add the `marker-mid` property to the path element of the edge

Please let me know your thoughts on this 🚀

**Comment by moklick** [comment]
It would be a great feature but unfortunately marker-mid doesn't work out of the box with complex paths. So as @chrtze said, the only option is to implement a custom edge.
