### ISSUE TITLE
Background state issues with multiple flows

### ISSUE THREAD

**Issue by rChaoz** [wbkd/react-flow#2546]
### Describe the Bug

When creating multiple flows, it seems like the background state is shared across the flows.
Duplicate of #1037

### Your Example Website or App

https://cxh0oz.csb.app/

### Steps to Reproduce the Bug or Issue

Check the website, and try to pan the 2 flows.

### Expected behavior

-

### Screenshots or Videos

Check video of #1037

### Platform

Browser: Firefox

**Comment by liuruenshen** [comment]
According to the codes, you need to specify a unique ReactFlow.id value for each ReactFlow; then, the issue can be solved.

```
<ReactFlow id="a"/>
<ReactFlow id="b"/>
```

I suggest the approach can be written into the document when multiple ReactFlow components are present.

**Comment by chrtze** [comment]
Thanks @liuruenshen, I have added this to our docs: https://github.com/wbkd/react-flow-docs/commit/beabb9ee161e098801a36368890be12caeefade9
