### ISSUE TITLE
Deleted custom-node still getting rendered

### ISSUE THREAD

**Issue by AlexW00** [wbkd/react-flow#2548]
### Describe the Bug

When deleting a node from the state, it still gets rendered, which results in an undefined error.

Here is the render part of my [EditorComponent](https://github.com/AlexW00/obsidian-flow/blob/main/src/components/ui/organisms/Editor.tsx) which deletes the node:

```ts
// ...

const [nodes, setNodes] = useNodes(flowName);

// ...

return (
  <ReactFlow
    nodeTypes={nodeTypes}
    nodes={nodes}
    edges={edges}
    onNodesChange={(nodeChanges) => {
      const newNodes = applyNodeChanges(nodeChanges, nodes);
      setNodes(newNodes);
    }}
    onEdgesChange={(edgeChanges) => {
      const newEdges = applyEdgeChanges(edgeChanges, edges);
      console.log("newEdges", newEdges);
      setEdges(newEdges);
    }}
    onConnect={handleConnect}
  >
    <MiniMap />
    <Controls />
    <Background />
  </ReactFlow>
);
```

setNodes simply updates the state (implemented with Zustand + Immer) by replacing the existing nodes with the new ones (see [useNodes](https://github.com/AlexW00/obsidian-flow/blob/main/src/react/hooks/state/useNodes.ts) and [setNodes](https://github.com/AlexW00/obsidian-flow/blob/3148ddff586a4ece2a9736e84b787b40ae0d0c89/src/data/setters/editor/setNodes.ts#L5))

Deleting the node works fine. However, after it has been deleted from the state object, the node still gets rendered, which results in undefined errors. This is the [CustomNode](https://github.com/AlexW00/obsidian-flow/blob/main/src/components/ui/molecules/nodes/CustomNode.tsx) in which no error occurs:
```ts

export const CustomNodeComponent: FunctionComponent<
  NodeProps<CustomNodeData>
> = (props: PropsWithChildren<NodeProps<CustomNodeData>>, _context?: any) => {
  console.log("rendering CustomNodeComponent", props.id);
  console.log(props);
  const updateNodeInternals = useUpdateNodeInternals();

  useEffect(() => {
    updateNodeInternals(props.id);
  }, []);

  // rendering content first because
  // at first render, the definition of the handles gets initialized
  const content = props.data.component(props.id);
  return (
    <div className="custom-node react-flow__node-default">
      <CustomNodeHandles nodeId={props.id} isInput={true} />
      <div>{content}</div>
      <CustomNodeHandles nodeId={props.id} isInput={false} />
    </div>
  );
};
```

This is the [ExampleNode](https://github.com/AlexW00/obsidian-flow/blob/main/src/components/ui/molecules/nodes/ExampleNode.tsx)(=content) in which the undefined error occurs:

```ts
export const ExampleNodeComponent = (id: string) => {
  const flowName = useContext(FlowNameContext);
  console.log("Rendering " + id + " in flow named", flowName);

  const setNodeDefinition = useNodeDefinition(id, flowName)[1];
  useEffect(() => {
    setNodeDefinition(ExampleNode);
  }, []);

  const inputs = useInputs(id, flowName);
  const [outputs] = useOutputs(id, flowName);
  const setOutput = useOutput("output1", id, flowName)[1];
  const setInput2HandleType = useNodeHandleType(
    true,
    "input2",
    id,
    flowName
  )[1];
  const setOutput2HandleType = useNodeHandleType(
    false,
    "output2",
    id,
    flowName
  )[1];

  console.log("CustomNodeComponent", id, inputs, outputs);

  const onClickButton = () => {
    console.log("onClickButton", outputs);
    const newOutput = (outputs.output1 ?? "") + "!";
    setOutput(newOutput);
  };

  const changeOutputType = () => {
    setInput2HandleType(NumberHandle);
    setOutput2HandleType(NumberHandle);
  };

  return (
    <div>
      <h3>MyCustomNode</h3>
      <div>Input: {inputs?.input1 ?? "empty"}</div>
      <div>Output: {outputs?.output1 ?? "empty"}</div>
      <button onClick={onClickButton}>Increment</button>
      <button onClick={changeOutputType}>Change output type</button>
    </div>
  );
};

export const ExampleNode: CustomNodeDefinition = {
  io: {
    inputs: {
      input1: {
        name: "Input 1",
        type: StringHandle,
      },
      input2: {
        name: "Input 2",
        type: ObjectHandle,
      },
    },
    outputs: {
      output1: {
        name: "Output 1",
        type: StringHandle,
      },
      output2: {
        name: "Output 2",
        type: ObjectHandle,
      },
    },
  },
};
```

The undefined error occurs in one of the hooks, which tries to return objects from the `data` property of the node. Although the whole node should have been deleted, the data object still exists **in pieces**, which can be seen when printing it out:

```
{
    "id": "5",
    "data": {
        "definition": {
            "io": {
                "inputs": {
                    "input1": {
                        "name": "Input 1",
                        "type": {
                            "name": "string",
                            "color": "#00ff00",
                            "allowedInputs": [
                                {
                                    "name": "any",
                                    "color": "#000000"
                                }
                            ]
                        }
                    },
                    "input2": {
                        "name": "Input 2",
                        "type": {
                            "name": "object",
                            "color": "#0000ff"
                        }
                    }
                },
                "outputs": {
                    "output1": {
                        "name": "Output 1",
                        "type": {
                            "name": "string",
                            "color": "#00ff00",
                            "allowedInputs": [
                                {
                                    "name": "any",
                                    "color": "#000000"
                                }
                            ]
                        }
                    },
                    "output2": {
                        "name": "Output 2",
                        "type": {
                            "name": "object",
                            "color": "#0000ff"
                        }
                    }
                }
            }
        },
        "outputs": {}, // <- this is suprisingly empty now, throws undefined error
        "inputs": {}
    },
    "type": "custom",
    "xPos": 2,
    "yPos": 267,
    "selected": true,
    "isConnectable": true,
    "sourcePosition": "bottom",
    "targetPosition": "top",
    "dragging": false,
    "zIndex": 1000
}
```

### Your Example Website or App

https://github.com/AlexW00/obsidian-flow

### Steps to Reproduce the Bug or Issue

Steps have been explained in description.

### Expected behavior

Expected: After deleting a node, it should not be rendered anymore at all

### Platform

- OS: macOS
- Browser: Chromium 

### Additional context

It is a plugin for Obsidian.

**Comment by chrtze** [comment]
hi, could you provide a minimal codesandbox that reproduces the error? Just looking at you code, I could imagine it has something to do with the way you are rendering the content (` const content = props.data.component(props.id);`). But it's hard to tell without running the code.

**Comment by AlexW00** [comment]
> hi, could you provide a minimal codesandbox that reproduces the error? Just looking at you code, I could imagine it has something to do with the way you are rendering the content (` const content = props.data.component(props.id);`). But it's hard to tell without running the code.

I created a codesandbox project, so you can see it for yourself. The bug occurs when deleting one of the custom nodes.
You can find the project [here](https://codesandbox.io/p/github/AlexW00/obsidian-flow-debug/draft/immutable-hill?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522cla9snh0s0007l0g72cxdbkls%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cla9snr0l00a02e6pxjm0p2vp%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cla9snoyr007f2e6ppqjbgbjb%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by AlexW00** [comment]
I was able to "fix" this issue, by checking in my CustomNode, whether the returned node object is undefined, and rendering an empty node instead:

```ts
export const CustomNodeComponent: FunctionComponent<
  NodeProps<CustomNodeData>
> = (props: PropsWithChildren<NodeProps<CustomNodeData>>, _context?: any) => {
  const updateNodeInternals = useUpdateNodeInternals();
  const flowName = useContext(FlowNameContext);
  const node = useNode(props.id, flowName); // <- get the node, may be undefined

  console.log("rendering CustomNodeComponent", props.id);

  useEffect(() => {
    updateNodeInternals(props.id);
  }, []);

  const ContentComponent = node?.data?.component;

  return (
    <NodeIdContext.Provider value={props.id}>
      {node ? ( // <- conditionally render the content
        <div className="custom-node react-flow__node-default">
          <CustomNodeHandles isInput={true} />
          <ContentComponent />
          <CustomNodeHandles isInput={false} />
        </div>
      ) : null}
    </NodeIdContext.Provider>
  );
};
```

However, that solution is suboptimal, I would expect the CustomNode component to not get rendered at all...

**Comment by chrtze** [comment]
Hey @AlexW00, I can't run the codesandbox. I get the following error:

```
[plugin:vite:esbuild] Transform failed with 1 error:
/project/obsidian-flow-debug/src/data/setters/editor/setNodes.ts:11:0: ERROR: Unexpected "<<"
/project/obsidian-flow-debug/src/data/setters/editor/setNodes.ts:11:0
Unexpected "<<"
8  |    appModel: AppModel
9  |  ): void => {
10 |    const flow = appModel.flows.find((f) => f.name === flowName);
   |                                                                  ^
11 |  <<<<<<< Updated upstream
   |  ^
12 |    if (flow) {```

**Comment by AlexW00** [comment]
> Hey @AlexW00, I can't run the codesandbox. I get the following error:
> 
> ```
> [plugin:vite:esbuild] Transform failed with 1 error:
> /project/obsidian-flow-debug/src/data/setters/editor/setNodes.ts:11:0: ERROR: Unexpected "<<"
> /project/obsidian-flow-debug/src/data/setters/editor/setNodes.ts:11:0
> Unexpected "<<"
> 8  |    appModel: AppModel
> 9  |  ): void => {
> 10 |    const flow = appModel.flows.find((f) => f.name === flowName);
>    |                                                                  ^
> 11 |  <<<<<<< Updated upstream
>    |  ^
> 12 |    if (flow) {
> ```

Fixed, works now.

**Comment by chrtze** [comment]
@AlexW00 could you provide the steps for reproducing? If I try to delete a custom node, the whole graph gets deleted (I tried via selection with shift and then backspace). Thanks!

**Comment by AlexW00** [comment]
> @AlexW00 could you provide the steps for reproducing? If I try to delete a custom node, the whole graph gets deleted (I tried via selection with shift and then backspace). Thanks!

1. Click a custom node
2. Press backspace to delete it
3. (the app actually crashes because of the error)

I just added the "fix" to the code sandbox project, so it does not crash anymore (see CustomNode.tsx).

**Comment by chrtze** [comment]
Ah, I see ;) sorry!

**Comment by chrtze** [comment]
I assume it has something to do with the state management here. Maybe you can try to get the node from React Flow instead of your local state? You can either do it with the `useNodes` hook or the `getNode` function from the React Flow instance.

**Comment by AlexW00** [comment]
> I assume it has something to do with the state management here. Maybe you can try to get the node from React Flow instead of your local state? You can either do it with the `useNodes` hook or the `getNode` function from the React Flow instance.

So any node state should be handled by React Flow itself? I was under the assumption that it was possible to completely use a local state by using Zustand as shown in the Docs.

The "minimal" example I gave to exemplify the problem wasn't really minimal. I created a second (this time really) minimal example, based on the Color-Chooser node example from the docs.

The only changes I made are:
- add a `selectNode: (nodeId: string) => Node<NodeData> | undefined;` to the store
- retrieve that node in the Color chooser node

The result is the same:
After deleting a node, the Color chooser node gets rendered again, and `selectNode` returns undefined. However, I would expect that the node does not get rendered at all.

Here is the Code-Sandbox link:
https://codesandbox.io/s/sad-burnell-uiq1xo?file=/ColorChooserNode.tsx

**Comment by chrtze** [comment]
Hey @AlexW00, thanks for creating this more minimal version ;) I am not sure actually if it's an intended behavior. We will take a closer look in the next days. Thanks for pointing this out!

**Comment by AlexW00** [comment]
> Hey @AlexW00, thanks for creating this more minimal version ;) I am not sure actually if it's an intended behavior. We will take a closer look in the next days. Thanks for pointing this out!

Awesome. Thanks for your efforts, I really appreciate it.

**Comment by RAFA3L** [comment]
I have a similar use of zustand, did you tray memoizing the custom node? for example

export default memo(({ data }) => {
...
});

**Comment by moklick** [comment]
I think this happens, because the store update is faster than the next render cycle. The custom node re-renders because the return value of the hook changes (which is undefined) and then the update is finished and it doesn't re-render again because it's unmounted. I don't think that this is something we can fix within the library but you need to add add a condition that prevents a rendering of the node if the returned value is undefined. Does this make sense to you?

**Comment by AlexW00** [comment]
> I think this happens, because the store update is faster than the next render cycle. The custom node re-renders because the return value of the hook changes (which is undefined) and then the update is finished and it doesn't re-render again because it's unmounted. I don't think that this is something we can fix within the library but you need to add add a condition that prevents a rendering of the node if the returned value is undefined. Does this make sense to you?

But the nodes and edges from the store are also passed to the ReactFlow component. Why doesn't the ReactFlow component update (and remove the custom node) before the custom node?

**Comment by chrtze** [comment]
> But the nodes and edges from the store are also passed to the ReactFlow component. Why doesn't the ReactFlow component update (and remove the custom node) before the custom node?

This is because you are using the hook inside your custom node which listens to an internal state change. When you pass the nodes to the React Flow component and delete a node, the internal state will change first (so your hook will trigger the re-render immediately with the undefined value) and only after that the node will be unmounted because the internal state change triggers the rendering of the node.

Could you provide some more details on what you are trying to achieve? Maybe a more specific selector with only the properties that you need would help here.

**Comment by moklick** [comment]
Closed due to inactivity. Please re-open if the issue still persists.

**Comment by solastley** [comment]
Bumping this thread as I seem to have run into the same issue. Been pulling my hair out for hours trying to figure it out but I guess it seems like it is actually expected?
