### ISSUE TITLE
Problem with customizing multiple selection of nodes and conncetion

### ISSUE THREAD

**Issue by DraksBG** [wbkd/react-flow#2552]
### Describe the Bug

Whenever you have a graph of nodes and connection and add nodeOrigin in order to specify the postion and try to select multiple nodes and connections  the selected field is not matching the actual one. Also you can see on the video that the problem is affecting and the fitView as well 

### Your Example Website or App

https://codesandbox.io/s/w6t3yt?file=/App.js&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

Add nodeOrigin={[0.5,0.5]}
Try to select multiple nodes 
The selected field is out of scope 

### Expected behavior

The selected field should be exactly the same that you have drawn 

### Screenshots or Videos

https://user-images.githubusercontent.com/52380770/201087695-c1bd062f-b054-4f2e-bb36-97c0b8dc13e5.mp4

![nodeOrigin_set_to_(0 5, 0 5)](https://user-images.githubusercontent.com/52380770/201087732-e16deb9c-6bc6-41f6-bf3a-cf73388fafe0.png)
![Default_nodeOrigin(0, 0)](https://user-images.githubusercontent.com/52380770/201087737-d40bde2d-b0b4-4337-b89d-4375ff8e5139.png)

### Platform

Windows
Chrome, Firefox, Safari

**Comment by moklick** [comment]
Thanks @DraksBG ! This is fixed in 11.3.0.
