### ISSUE TITLE
reactFlowInstance.deleteElements() returns the error "deleteElements is not a function"

### ISSUE THREAD

**Issue by josielqogit** [wbkd/react-flow#2553]
### Describe the Bug

On Version 11.1.2 reactFlowInstance.deleteElements() returns the error "deleteElements is not a function". reactFlowInstance don't contains the function.

### Steps to Reproduce the Bug or Issue

1. Get the instance of reactFlow
2. Execute the function reactFlowInstance.deleteElements()

### Expected behavior

As a user I expect a function execution but I am seeing a error : "deleteElements is not a function".

### Screenshots or Videos

![image (1)](https://user-images.githubusercontent.com/55516015/201409303-70eb7877-a881-41da-b5b9-efbfde39e3e3.png)
![image (2)](https://user-images.githubusercontent.com/55516015/201410608-61ba97ac-dc4c-44d8-918b-726fbd5ddc88.png)

### Platform

- OS: [ Windows]
- Browser: [Chrome]

**Comment by chrtze** [comment]
The `deleteElements` function is available from version 11.2.0 onwards. More information here: https://github.com/wbkd/react-flow/releases/tag/11.2.0
