### ISSUE TITLE
Bad publish (?) of 10.3.17 -  Property 'defaultViewport' does not exist

### ISSUE THREAD

**Issue by AndrewRayCode** [wbkd/react-flow#2555]
### Describe the Bug

```
mkdir test
cd test
npm install react-flow-renderer
cat node_modules/react-flow-renderer/dist/esm/types/component-props.d.ts | grep defaultViewport
```
`defaultViewport` is not exported in `component-props.d.ts`. Trying to use it:
```
<ReactFlow
  defaultViewport={{ x: 0, y: 0, zoom: 0.1 }}
```
Results in typescript error:
```
Type '{ children: Element; defaultViewport: { x: number; y: number; zoom: number; }; style: { height: string; background: string; }; nodeTypes: Record<NodeType | GraphDataType | EngineNodeType, any>; ... 16 more ...; onInit: Dispatch<...>; }' is not assignable to type 'IntrinsicAttributes & ReactFlowProps & RefAttributes<HTMLDivElement>'.
  Property 'defaultViewport' does not exist on type 'IntrinsicAttributes & ReactFlowProps & RefAttributes<HTMLDivElement>'.ts(2322)
```

So `dist/esm/types/component-props.d.ts` isn't getting published properly? Maybe?

It also appears the prop doesn't do anything. 
```

        <ReactFlow
          defaultViewport={{ x: 1000, y: 0, zoom: 100 }}
```

still always places my graph viewport in the same place when it mounts. The full code if it matters:

```
    <ReactFlow
          defaultViewport={{ x: 1000, y: 0, zoom: 100 }}
          style={flowStyles}
          nodeTypes={nodeTypes}
          edgeTypes={edgeTypes}
          nodes={nodes}
          edges={edges}
          onMoveEnd={onMoveEnd}
          onConnect={onConnect}
          onEdgeUpdate={onEdgeUpdate}
          onEdgesChange={onEdgesChange}
          onNodesChange={onNodesChange}
          onNodesDelete={onNodesDelete}
          onNodeDoubleClick={onNodeDoubleClick}
          onEdgesDelete={onEdgesDelete}
          connectionLineComponent={ConnectionLine}
          onConnectStart={onConnectStart}
          onEdgeUpdateStart={onEdgeUpdateStart}
          onEdgeUpdateEnd={onEdgeUpdateEnd}
          onConnectStop={onConnectStop}
          onInit={setRfInstance}
        >
          <Background
            variant={BackgroundVariant.Lines}
            gap={25}
            size={0.5}
            color="#333333"
          />
        </ReactFlow>
```

### Your Example Website or App

Open https://reactflow.dev/docs/examples/overview/

Change `fitView` to `defaultViewport={{x:-100, y:-100, zoom: 1}}`. Nothing happens.

### Steps to Reproduce the Bug or Issue

None

### Expected behavior

None

### Screenshots or Videos

None

### Platform

- OS: MacOS
- Browser: None
- Version: `10.3.17`

**Comment by bcakmakoglu** [comment]
The prop `defaultViewport` is available in v11 onwards: https://github.com/wbkd/react-flow/issues/2313.

**Comment by AndrewRayCode** [comment]
My confusion was from not realizing there was a new package publish with a new version. The v10 npm page does not show a deprecation warning, sounds like it will soon https://discord.com/channels/771389069270712320/1041183558976421979/1041429606986682388

**Comment by moklick** [comment]
Good point @AndrewRayCode I added a deprecation warning for the react-flow-renderer package.
