### ISSUE TITLE
Getting zoom level and other state in child components

### ISSUE THREAD

**Issue by bartvanremortele** [wbkd/react-flow#257]
When building additional components outside of this project (e.g.: a different implementation for background / grid rendering) there currently is no way to access the state because it's not being exported. 

I'm not familiar with easy-peasy and perhaps there is a way but I was unable to find it.

A simple solution would be to export the `useStoreState` from `store/hooks` to be able to pull in state from react-flow.

What are your thoughts on this?

**Comment by moklick** [comment]
Good idea :) We need that too. It's available in v2.2.1
