### ISSUE TITLE
Programmatically changing positions messes up selection 

### ISSUE THREAD

**Issue by MrSpijker** [wbkd/react-flow#2579]
### Describe the Bug

So I followed the dagreJS example to distribute the nodes accordingly. 

```
for (let i = 0; i < _nodes.length; i++) {
    const node = _nodes[i];
    const nodeWithPosition = dagreGraph.node(node.id);

    if (nodeWithPosition) {
      const position = {
        x: nodeWithPosition.x - nodeWithPosition.width / 2 ?? 0,
        y: nodeWithPosition.y - nodeWithPosition.height / 2 ?? 0,
      };

      yield* put(
        TopologyAction.nodePositionChange({
          id: node.id,
          positionData: {
            id: node.id,
            type: "position",
            position,
          },
        })
      );
    }
  }
```

Keeping in mind that I have to substract half of the width. 
So things look ok but when I shift-drag-select the result is a tad off.
If I drag the rectangle with more space, the node gets selected.

This must be something related to the internal state not being in line with my store state.
I use a (kinda simple) redux store where it had an Array of Nodes and for the updates (as seen above) I do a simple map operation that switches between the original, and if the node has changed, uses the spread operator to merge both.

Things I have tried: 
- updateNodesInternal -> no difference
- using state and useEffect when some of my  store kept nodes change
- adding half width//height

Before the dagrejs sorting the selection behaves accordingly.

Any help would be greatly appreciated. 
Best answer would be a react-flow internal store update that can be triggered from outside. Redux saga for example.
Cheers!

### Steps to Reproduce the Bug or Issue

- Redux store with nodes
- dagreJS distribution
- update nodes in store with corresponding positions
- shift select
- frown

### Expected behavior

Correctly selected nodes.

### Platform

- OS: Windows
- Browser: Electron (chrome)
- Version: "reactflow": "^11.2.0",

**Comment by moklick** [comment]
Hi!

Do I get it right, that you are just updating your node positions and then you can do a proper selection anymore?

**Comment by moklick** [comment]
please re-open with a codesandbox or repo, so that we can understand the issue better.
