### ISSUE TITLE
Set edge does not correctly update the edges.

### ISSUE THREAD

**Issue by mariancristivrabie** [wbkd/react-flow#2580]
### Describe the Bug

I have a chart that has parent nodes and subFlows in each parent.

I try to highlight all edges connected to a specific child node when hovering over the node. I do this by adding a specific stroke to the edges with the specific node as the source or target when the user hovers over the node (using the onNodeMouseEnter helper). 

The issue is that I can not remove the stroke when the user leaves the child node and the. The update only happens when the user leaves the entire parent node and gets to the background. If there are multiple nodes one beside another and the user does not get to the background then the highlighted edges will not be removed.

### Steps to Reproduce the Bug or Issue

1. The chart should have at least 1 parent node with a subflow.
2. onNodeMouseEnter I call the following function:
```js
const onNodeMouseEnter = useCallback(
    (event: any, node: any) => {
      const id = node.id;

      const updatedEdges: any = (edges || []).map((edge: any) => {
        if (edge.source === id || edge.target === id) {
          return {
            ...edge,
            style: {
              stroke: red,
              strokeWidth: getEdgeStrokeWidth(edge.value),
            },
          };
        }

        return edge;
      });

      setEdges(updatedEdges);
    },
    [edges, setEdges]
  );
```
3. The related edges are highlighted.
4. Then leave the inner node.
5. OnMouseLeave function look like this
```js
const onNodeMouseLeave = useCallback(() => {
    const updatedEdges: any = (edges || []).map((edge: any) => {
      return {
        ...edge,
        style: {
          strokeWidth: getEdgeStrokeWidth(edge.value),
        },
      };
    });

    setEdges(updatedEdges);
  }, [edges, setEdges]);
```
6. If the user is with the mouse on the parent node then the edges will not be updated. They will update only when user gets to the chart background.

### Expected behavior

As a user, I expect the edges to be updated (to remove the highlight) when I leave the current node no matter what node I get.

### Screenshots or Videos

![Hover state over the inner node](https://user-images.githubusercontent.com/34236223/203306753-d057abd6-edb3-49bf-9ec6-54f8106dc9a0.jpg)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 11.0.2

**Comment by moklick** [comment]
I can't reproduce this. `onNodeMouseLeave` gets triggered when you leave a child node. Can you provide a codesandbox for this?

**Comment by mariancristivrabie** [comment]
https://codesandbox.io/s/affectionate-feather-sxuhlb?file=/src/App.js

Here is the codesandbox. You can see that the stroke will change back to 1 only when we you leave the parent node, not the child node.

**Comment by moklick** [comment]
@mariancristivrabie thanks this was helpful! 

The issue is that you are overwriting the changes of the leave handler immediately in the enter handler. To fix this, you should check if there is a change and only then apply the new edges. I updated the csb for you:

https://codesandbox.io/s/elastic-elion-dbqwty?file=/src/App.js:1360-1422

I am also using the store api to get the current edges inside the handlers. This makes sure that you always have the current edges and you don't need to re-create the handlers when the edges change.

**Comment by mariancristivrabie** [comment]
thank you for clarifying this!
