### ISSUE TITLE
MarkerEnd color doesn't support css color variable

### ISSUE THREAD

**Issue by Jasminou** [wbkd/react-flow#2588]
### Describe the Bug

when trying to define the markerEnd color for the arrow type on edge object it's won't display when using a variable css color.

color: var(--text-color); -> won't work
color: 'red' or '#fffff'-> work

### Steps to Reproduce the Bug or Issue

you can try it on any edge example on your website

### Expected behavior

It should be able to support css variable like var(--text-color)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: v10.3.17

**Comment by moklick** [comment]
We can't fix this, because you can't use css variables as SVG attributes.

**Comment by Jasminou** [comment]
@moklick thank you for the response, I tired to use markerDef instead for each one the color I need in my flow. but it doesn't seems to be supported by every broswer. do u by any chance have any example about how we can definde marker to use as markerEnd for edges.

Thank you
