### ISSUE TITLE
Problem importing css with autoprefixer

### ISSUE THREAD

**Issue by paulodeon** [wbkd/react-flow#2599]
### Describe the Bug

I've just migrated from v10 to v11. 

On adding the css import line `import 'reactflow/dist/style.css'` or `import 'reactflow/dist/base.css'`

I get the following compile error: 

`RangeError: Maximum call stack size exceeded` at `node_modules/reactflow/dist/style.css:81:13`

I have postcss and autoprefixer installed It looks like autoprefixer is choking there. 

The reactflow css is already prefixed so that could be the cause (although I would think autoprefixer would be more robust) and the way I can fix it is by adding the line `/* autoprefixer: off */` to the css file in the node_modules dir. 

Any ideas how I can fix this in a more sustainable way?

### Steps to Reproduce the Bug or Issue

1. in project with postcss and autoprefixer installed 
2. add reactflow v11
3. add css import line
4. compile fails

### Expected behavior

Compile should succeed

### Platform

- OS: MacOS
- Browser: Chrome but not relevant
- Version: 11.3

**Comment by chrtze** [comment]
Hi @paulodeon, which version of autoprefixer and postcss are you using? Did you try to upgrade autoprefixer to the latest version? Otherwise, maybe there is some configuration option to disable autoprefixer for `node_modules`?

**Comment by moklick** [comment]
please re-open if issue persists.
