### ISSUE TITLE
snap to grid is not behaving correctly

### ISSUE THREAD

**Issue by bartvanremortele** [wbkd/react-flow#261]
Hi again,

When using snap to grid everything works as expected on the initial zoom level scale of 1. If you zoom in by a fraction (e.g.: scale 1.2) the grid snapping is not working correctly. As soon as you hit scale(2) it starts snapping back to the grid but with a double offset from your mouse position. I believe the reason is that the grid snapping is scaling the snapping based on the current zoom factor which is not required. The node's translation is being scaled by the parent container (the graph) and should not be manually scaled to the zoom factor.

See this loom video for more context: https://www.loom.com/share/e1b71b244f33436c91d29ef156f6c12c

**Comment by moklick** [comment]
hey @bartvanremortele! 

Thanks for the detailed bug report :) Good catch! We just fixed it.
