### ISSUE TITLE
Edges start to bend right after leaving/entering the marker 

### ISSUE THREAD

**Issue by sn1c3** [wbkd/react-flow#2610]
### Describe the Bug

In the examples on the website and older versions of react-flow edges start to bend not right after leaving/entering a marker. Therefore it always was clear where they originate from. 
With newer versions this bending distance does not exist anymore. 

### Your Example Website or App

https://codesandbox.io/s/qg590?file=/src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the codesandbox example (https://codesandbox.io/s/qg590?file=/src/App.tsx)
2. Drag nodes around
3. Edges bend in a way which is not clear where they originate from

### Expected behavior

Edges should not bend right after leaving marker. (As seen in the custom node example https://reactflow.dev/docs/examples/nodes/custom-node/)

### Screenshots or Videos

Expected behavior from the color picker example:
![image](https://user-images.githubusercontent.com/12408751/204335462-7229a29b-5818-4d64-acc6-b22c4c03eec1.png)

Actual behavior from the code-sandbox example:
![image](https://user-images.githubusercontent.com/12408751/204335793-6d24fe26-3d3e-42df-9ee8-06b537b33b25.png)

### Platform

- OS: [Linux Ubuntu 20.04]
- Browser: [Chrome]

**Comment by moklick** [comment]
You are using a very old version. Please upgrade to v11.x 

- migrate to v10 https://reactflow.dev/docs/guides/migrate-to-v10/
- migrate to v11 https://reactflow.dev/docs/guides/migrate-to-v11/
