### ISSUE TITLE
Minimap layout is broken on 11.3.1

### ISSUE THREAD

**Issue by lounsbrough** [wbkd/react-flow#2611]
### Describe the Bug

The minimap layout seems to be broken starting with release `11.3.1`. The minimap still shows nodes, but they are not in the correct layout.

### Your Example Website or App

https://codesandbox.io/s/pensive-golick-une37b

### Steps to Reproduce the Bug or Issue

1. Go to link where I simply updated version to `11.3.1` and see incorrect layout of minimap.

### Expected behavior

Minimap layout should match the real layout

### Platform

- OS: macOS
- Browser: Chrome
- Version: 11.3.1

### Additional context

Problem was introduced here: https://github.com/wbkd/react-flow/compare/6bbc0043152c249197cf92fba12d994514b061c1...main

**Comment by lounsbrough** [comment]
I think this will fix it: https://github.com/wbkd/react-flow/pull/2612

**Comment by moklick** [comment]
oh man .. how could this slip through :/ Thanks for fixing it! Released in v11.3.2

**Comment by lounsbrough** [comment]
Thanks for releasing so fast 👍🏼 confirmed resolution in our app after pulling `11.3.2`.
