### ISSUE TITLE
Panning the Interactive Minimap ignores `translateExtent` prop on ReactFlow component

### ISSUE THREAD

**Issue by rllyy97** [wbkd/react-flow#2613]
### Describe the Bug

I wasn't sure if this classified as a bug or a missing feature, but setting the `translateExtent` prop on your ReactFlow component has no pan-limiting effect when you drag-pan on the new interactive minimap.

### Steps to Reproduce the Bug or Issue

1. Set up a ReactFlow component with the `translateExtent` prop set
2. Also enable the new react flow interactive minimap, make it pannable
3. Drag the interactive minimap and it will ignore the translateExtent prop

### Expected behavior

Panning on the interactive minimap should have the same `translateExtent` limitations that panning on the canvas has, either by passing the same property to the minimap or just automatically.

### Screenshots or Videos

My `translateExtent` prop is preventing the canvas-pan from moving the nodes off the left of the canvas as expected, but when I pan with the minimap there is no limitation.
![pan_clamping_issue](https://user-images.githubusercontent.com/25409734/204366384-1fcfa0ea-7cd8-4721-8f0e-1ca05b733a0c.gif)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 107.0

**Comment by moklick** [comment]
fixed in 11.4.0
