### ISSUE TITLE
Middle-mouse dragging doesn't work on edges

### ISSUE THREAD

**Issue by RunDevelopment** [wbkd/react-flow#2621]
### Describe the Bug

RF recently added the feature to drag the pane from anywhere using the middle mouse button. This is a very useful feature, but it seems to not work when hovering over an edge. 

This issue can be seen with any graph on https://reactflow.dev/

### Steps to Reproduce the Bug or Issue

1. Have any chain with edges.
2. Try to drag the pane with the middle mouse button while hovering over an edge.
3. No dragging.

### Expected behavior

Just like with nodes and the pane itself, dragging on edges should work.

### Platform

- OS: Any
- Browser: Any
- Version: 11.3.2

**Comment by moklick** [comment]
Thanks @RunDevelopment we will check that.

**Comment by RunDevelopment** [comment]
Thanks for the fix @moklick!

**Comment by moklick** [comment]
Thanks for the report @RunDevelopment  :)
