### ISSUE TITLE
`onNodeDragStop` triggered on node click

### ISSUE THREAD

**Issue by danielgek** [wbkd/react-flow#2622]
### Describe the Bug

Hey, I'm having some problem wrapping my head around the `onNodeDragStop` callback
Our current setup uses redux to store the nodes and edges on our side(controlled flow), and we have a redux action that updates the nodes position when the `onNodeChanges` callback fires changes of type `position` and a thunk action to actually save the position on the server once the drag ends, for this i'm using `onNodeDragStop`

The problem with this is that `onNodeDragStop` is triggered on node click when for example selecting a node

### Your Example Website or App

https://codesandbox.io/s/restless-dust-f07gxl?file=/store/boardSlice.js

### Steps to Reproduce the Bug or Issue

1. select a node
2.  `onNodeDragStop` is triggered

### Expected behavior

`onNodeDragStop` is only triggered on a drag end

### Platform

- OS:  macOS
- Browser: Chrome
- Version: [11.3.2]

**Comment by danielgek** [comment]
I made a workaround this: https://codesandbox.io/s/frosty-meadow-6j8m65

but it still feels like a hack imho

**Comment by danielgek** [comment]
yes a threshold for firing `onNodeDragStop` would be enough i think

**Comment by moklick** [comment]
Since 11.9.0 it's possible to use the [`nodeDragThreshold` prop](https://reactflow.dev/docs/api/react-flow-props/#nodedragthreshold) to delay / prevent the drag events on click.

**Comment by noah-jun-521** [comment]
As of 2024 Jan 31, it is still causing both onNodeClick and onNodeDragStop with nodeDragThreshold being 5.

**Comment by kevjin** [comment]
> As of 2024 Jan 31, it is still causing both onNodeClick and onNodeDragStop with nodeDragThreshold being 5.

works for me, maybe your screen resolution?
