### ISSUE TITLE
Drag to disconnect/remove connection

### ISSUE THREAD

**Issue by pedrocatalao** [wbkd/react-flow#2623]
### Please describe the feature that you want to propose

Hi, is it possible to add an option/flag per endpoint to enable drag to disconnect or in other words, delete the connection by dragging the line away, like this:

https://user-images.githubusercontent.com/5308797/204818091-c204907a-f19b-4d86-833f-423453bbf04c.mov

**Comment by moklick** [comment]
You can't enable this with a flag, but we've built an example for this use case: https://reactflow.dev/docs/examples/edges/delete-edge-on-drop/

**Comment by pedrocatalao** [comment]
Thank you very much for helpful example @moklick
