### ISSUE TITLE
Plugins aren't working with multiple Zustand instances

### ISSUE THREAD

**Issue by arguiot** [wbkd/react-flow#2624]
### Describe the Bug

I have a setup with multiple Zustand instances. When I disable the plugins like this:
```tsx
<ReactFlow
	nodes={nodes}
	edges={edges}
	onNodesChange={onNodesChange}
	onEdgesChange={onEdgesChange}
	onConnect={onConnect}
	onConnectStart={onConnectStart}
	onConnectEnd={onConnectEnd}
	nodeTypes={nodeTypes}
	edgeTypes={edgeTypes}
	proOptions={proOptions}
	// Interactive
	elementsSelectable={!running}
	nodesDraggable={!running}
	nodesConnectable={!running}
	>
	{/* <MiniMap />
	<Controls showInteractive={false} />
	<Background /> */}
</ReactFlow>
```

I get no error. (Note that my `<Reactflow />` component is wrapped around a `<ReactFlowProvider />` as I am using `useReactFlow()` in the same component.

But when I activate the plugins, this is the error I am getting:

<img width="980" alt="Capture d’écran 2022-11-30 à 09 10 27" src="https://user-images.githubusercontent.com/18022260/204817733-e45ddafb-02e6-4c4b-a3c1-cf1fe6d6d1d5.png">

Also note that the errors are actually happening inside the plugin components themselves:
<img width="1440" alt="Capture d’écran 2022-11-30 à 09 11 28" src="https://user-images.githubusercontent.com/18022260/204817985-6c91f8d9-2e7e-402f-af68-7ed1d89fb221.png">

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

I expect the plugins not to throw this error.

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Safari]
- Version: [e.g. 16.1]

**Comment by moklick** [comment]
can you provide a codesandbox so that we can reproduce this?

**Comment by arguiot** [comment]
Here is a copy of the project I'm working on:
[Eula-Reactflow.zip](https://github.com/wbkd/react-flow/files/10126406/Eula-Reactflow.zip)

Just type `yarn dev` to start the web server.

You'll find the `<ReactFlow />` instance in `packages/editor/src/Editor.tsx`

**Comment by moklick** [comment]
The problem is that you installed different versions of React Flow. Update the RF version of the editor to "^11.3.2" and it should work.
