### ISSUE TITLE
Ability to Turn Off Node Z-Index Manipulation Similar to "elevateEdgesOnSelect" Flag

### ISSUE THREAD

**Issue by AustinGilliam** [wbkd/react-flow#2625]
### Please describe the feature that you want to propose

In #2560 functionality was introduced that forces an increase in the z-index of nodes when selected. However, my application is very opinionated about z-index, and so this creates breaking changes. Would it be possible to get a flag similar to [elevateEdgesOnSelect](https://reactflow.dev/docs/api/react-flow-props/#elevateedgesonselect-1) but for nodes?

**Comment by moklick** [comment]
added in 11.4.0
