### ISSUE TITLE
Edges connect to wrong handles in ConnectionMode.Loose

### ISSUE THREAD

**Issue by michaelspiss** [wbkd/react-flow#2630]
### Describe the Bug

The problem occurs when `ConnectionMode.Loose` is used and nodes have target as well as source nodes. Once two sources get connected, the edge is displayed as connected to the target handle of the target node, despite specifying the source handle correctly in the edge data.

Just having a quick glance at the source code, I believe the following lines to cause the problem:
https://github.com/wbkd/react-flow/blob/6526e3297e67c57c2e9be0654be3792c6cc04483/packages/core/src/container/EdgeRenderer/index.tsx#L116-L121
target handles exist, so the source handles array gets disregarded. `getHandle` then chooses the first target, because it's the only one available (at least in my case it is). Maybe a `.concat` instead of `||` would fix this. 

### Your Example Website or App

https://github.com/michaelspiss/berry-sethi-tutor

### Steps to Reproduce the Bug or Issue

- Have a react flow with `connectionMode={ConnectionMode.Loose}`.
- Have two default nodes in the graph
- Connect source to source -> will display as source to target, despite being source to source in the data

### Expected behavior

Edge should connect to handle specified in its data

### Screenshots or Videos

s: source handle, t: target handle (`visibility: hidden` here). Windows screen recorder messed up the pointer position a bit, just assume it's on point.

https://user-images.githubusercontent.com/17252710/205444554-557faa6d-9b2d-4dee-9fb0-c6021cf67a74.mp4

### Platform

- OS: all
- Browser: all
- Version: 11.3.2

**Comment by moklick** [comment]
Thanks @michaelspiss I'll check this.

**Comment by moklick** [comment]
I just checked this bug and unfortunately it's not fixable with the current implementation. When you are using connection mode loose, all handles should be of type source. 

The problem is, that we only get this information from an edge:

```js 
{
    "source": "3",
    "sourceHandle": null,
    "target": "4",
    "targetHandle": null,
    "id": "reactflow__edge-3-4"
}
```

We only know the node id, but have no information if the handle was a source or target.

**Comment by michaelspiss** [comment]
Thanks for looking into this @moklick! 
I see why that wouldn't be fixable for unnamed handles, but in the example above all handles have unique ids, which are set in the edge props as `sourceHandle` and `targetHandle`. Nonetheless, the edge connects to the wrong one.

**Comment by bcakmakoglu** [comment]
^Are you using numbers as ids? That might cause the issue (for example you use some index as the id).
Convert them into strings something like `handle_0` and see if that works.

**Comment by bcakmakoglu** [comment]
If I use the custom node example in the docs, an assign the handles a number like `id={0}` the edges don't connect properly either. Even if the handle id that I use in the edge definition matches that number.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/78412429/206467409-60aac368-1c07-4d0c-b4b0-fa3b95fd8ee4.png">

They both just go to the first handle as you can see.

**Comment by michaelspiss** [comment]
They are strings - I use `step1t`, `step1b`, `step2l`, `step2r`

**Comment by bcakmakoglu** [comment]
Ok :) It was just an idea 😅

**Comment by michaelspiss** [comment]
Thanks anyway, would have been an easy solve 😅
