### ISSUE TITLE
Bounding box does not update on child node (or parent node) modifications

### ISSUE THREAD

**Issue by unredundant** [wbkd/react-flow#2633]
### Describe the Bug

Hi! Got a weird issue when it comes to updating the width of a parent node.  It seems that, once a child node is attached to a parent, the bounding box breaks, and will not update when new updates come in.  

https://user-images.githubusercontent.com/5607577/205497162-866eab0e-f5d3-4c80-82fa-0c7780adfaaf.mov

As you can see here, I go and make a table (parent) node.  I then update the name, and the width of the node updates as expected.  I then add a column (child) node.  I would ideally like the parent size to update as well when the child is added, but I just haven't figured out how to do that.  

However, when I go back and try to edit the parent name again, the width of the node no longer updates :( 

### Steps to Reproduce the Bug or Issue

Ah man IDK this is so hard with web dev stuff :( I can't post my code b/c it is a private repo.  But essentially my set up is that i am trying to dynamically add child nodes, and have the parent and children always have the same width of the largest parent / child.  

I'm also using tailwind if that helps 

### Expected behavior

The parent node should still update width when input is received despite having a child node

### Screenshots or Videos

see above

### Platform

- OS: MacOS Ventura
- Browser: Arc
- Version: 0.79

**Comment by moklick** [comment]
Parent nodes behave a bit differently. You need to pass the correct dimensions via `style.width` and `style.height`. Are you sure that you need a parent node here? Why are you not just adding divs for the columns? Can you drag them out of the parent?

**Comment by unredundant** [comment]
> Why are you not just adding divs for the columns

This would be the ideal solution, but when I tried this, I had a bad time trying to figure out the deal w/ handlers, positioning them correctly, etc. etc. Particularly when it came to dealing with nested content (Ie modeling out a nested structure inside a node, with handlers on certain nested fields).  

Is there a way to position a handler relative to a specific div inside of a node?? it seemed from the docs to be required to position manually :(

**Comment by moklick** [comment]
Sure that's possible. We are doing it here: https://reactflow.dev/docs/examples/overview/.

I built a little example: https://codesandbox.io/s/dynamic-handles-71dc9v 

Does it help?

**Comment by moklick** [comment]
please re-open if the issue persists.
