### ISSUE TITLE
Skip assigning the ID property a unique value

### ISSUE THREAD

**Issue by liuruenshen** [wbkd/react-flow#2639]
### Please describe the feature that you want to propose

The user doesn't need to specify a unique ID value in multiple-flow conditions after this [PR](https://github.com/wbkd/react-flow/pull/2638).

**Comment by moklick** [comment]
This doesn't work for SSR. We will change this with the next major release where we will only support React18 so we can use [`useId`](https://beta.reactjs.org/apis/react/useId).
