### ISSUE TITLE
Add onEdgeDrop method

### ISSUE THREAD

**Issue by Julia-Alberici** [wbkd/react-flow#2640]
### Please describe the feature that you want to propose

I want to break a connection when dropping a node on it, and reconnect everything with the new node auto, but rn theres no native way to identify the edge in the DOM. A method for it would be great! Thanks in advance.

**Comment by moklick** [comment]
This is not an easy thing to do. We don't know where the edges are drawn. I would create an area in the center of an edge and then use the helper function [isNodeIntersecting](https://reactflow.dev/docs/api/react-flow-instance/#isnodeintersecting) to find out if a dragged node is intersecting with one or the edge center areas.

Does this make sense to you?

**Comment by moklick** [comment]
please re-open if it's still an issue.

**Comment by Julia-Alberici** [comment]
I'm sorry for took so long to answer. Actually i'm able to get the HTML edge element on the area, i just wanted an attribute to connect the HTML edge element with the Edge object, something like `data-edgeid`. Rn i'm inserting the id through the edge className, it works but i don't think it's the best approach. I'm not sure of how clear i was here, so let me know if you have any doubts. Again, thank you!
