### ISSUE TITLE
Unable to use multiselect or box select when an input is focused

### ISSUE THREAD

**Issue by maclockard** [wbkd/react-flow#2650]
### Describe the Bug

This is happening with `@reactflow/core@11.3.1`.

Whenever you have an input focused outside of the react flow, clicking on nodes with the multi select key held down does not result in nodes being multi selected. 

### Your Example Website or App

https://codesandbox.io/s/morning-worker-61fs24?file=/src/Flow.js

#### Repro 1:

1. Click on any input in the left column
2. Hold the 'meta' key
3. Click on a node for any input other than the currently selected one in react flow in the right column

#### Repro 2:

1. Click on any input in the left column
2. Hold the 'shift' key
3. Click and drag on react flow in the right column

#### Repro 1:

I would expect the node clicked would be added to the existing selection state.

#### Repro 12:

I would expect the box select to be rendered, instead the graph pans.

### Platform

- OS: macOS
- Browser: Firefox
- Version: 107.0

### Additional context

From what I can tell, this is happening because of these lines here: https://github.com/wbkd/react-flow/blob/5e916ba2db0729ef082200df26899471c6515092/packages/core/src/hooks/useKeyPress.ts#L46-L48

I think for some cases this behavior makes a lot of sense, for example when using the delete key etc to prevent issues like this: https://github.com/wbkd/react-flow/issues/2254. However, I would not expect holding the meta key for multi select to be prevented like this.

A couple possible solutions I can think of:
1. Allow for consumers to add a special class to inputs that prevents this swallowing behavior. (Kinda an inverse of `.nokey`).
  - This would work for my use case, but might cause issues if folks are trying to do deletion from the graph as well
2. Add an argument to `useKeyPress` for whether or not inputs should swallow the key press. For multi select and box select, this value would be false and for deletion this value would be true.

I _think_ that solution 2 would be preferable.

I'm also very willing to contribute a fix here if any of these solutions are acceptable!

**Comment by maclockard** [comment]
@moklick where are you thinking of ignoring them? in `useKeyPress` for `isInputDOMNode`?

**Comment by moklick** [comment]
Exactly.

**Comment by maclockard** [comment]
That feels very reasonable to me!
