### ISSUE TITLE
Deleting selected node does not trigger useOnSelectionChange

### ISSUE THREAD

**Issue by unredundant** [wbkd/react-flow#2651]
### Describe the Bug

Hello 👋 I am deleting a node via a button click in a component.

```ts
// ...

const deleteTable = () => setNodes((nds) => nds.filter((n) => n.id !== node.id));
```

My diagram updates as expected, however, I have a panel that shows the displayed node (the same panel that the delete button is in) which is shown only when a certain node is selected.  This, unfortunately, does not update when a node is deleted.  

It seems to me that a node (if currently selected) should trigger a `useOnSelectionChange` upon deletion.  

Is there another way to emulate this behavior? Perhaps I can simply call `unselectNode(id)` or something similar, but I couldn't find any such method in the docs :( 

### Steps to Reproduce the Bug or Issue

1. Select node
2. have component displayed only when node is selected
3. delete node
4. watch in utter dismay as your component remains :'( 

### Expected behavior

Deleting a selected node should trigger the selection update hook

### Screenshots or Videos

https://user-images.githubusercontent.com/5607577/206061387-9d46b5bf-5366-4c13-99fe-dc4845b73c11.mp4

### Platform

- OS: macos
- Browser: Arc
- Version: 0.79

**Comment by moklick** [comment]
Every node has a selected flag. For the sidebar I would do something like this:

```js
const selectedNodeNames = useStore(s => Array.from(s.nodeInternals.values()).filter(n => n.selected).map(n => n.data.name));
````

I think for this you don't need to listen to the selection changes.
