### ISSUE TITLE
Fitview after changing nodes and edges

### ISSUE THREAD

**Issue by amintabrizi** [wbkd/react-flow#2654]
### Please describe the feature that you want to propose

FitView doesn't seems to fit the View after the nodes and edges has been updating.

**Comment by chrtze** [comment]
Are you using the `fitView` prop (https://reactflow.dev/docs/api/react-flow-props/#fitview-1) or the `fitView` method from the React Flow instance (https://reactflow.dev/docs/api/react-flow-instance/#fitview)?

The prop only centers all nodes when React Flow is mounted. For doing this after updating, you should use the method from the instance.

**Comment by amintabrizi** [comment]
> Are you using the `fitView` prop (https://reactflow.dev/docs/api/react-flow-props/#fitview-1) or the `fitView` method from the React Flow instance (https://reactflow.dev/docs/api/react-flow-instance/#fitview)?
> 
> The prop only centers all nodes when React Flow is mounted. For doing this after updating, you should use the method from the instance.

That works perfect!
