### ISSUE TITLE
Hidden nodes always included in box selection

### ISSUE THREAD

**Issue by maclockard** [wbkd/react-flow#2679]
### Describe the Bug

When using shift-click to drag select, hidden nodes are always included in the resulting selection changes.

### Your Example Website or App

https://codesandbox.io/s/competent-curie-rvi51b?file=/src/initial-elements.js

### Steps to Reproduce the Bug or Issue

1. Hold shift
2. Click on graph and hold mouse down
3. Create a drag selection of Node 1 and Node 2

In the left hand sidebar you will notice that Node 3 is always included despite being hidden

### Expected behavior

I would expect only visible nodes to be selectable with a box selection

### Screenshots or Videos

<img width="841" alt="Screen Shot 2022-12-13 at 1 23 16 PM" src="https://user-images.githubusercontent.com/7308388/207436153-8156d97f-53e0-4c39-86a5-83cfce7bcd6f.png">

### Platform

- OS: macOS
- Browser: Firefox
- Version: 108

### Additional context

FWIW I'm only running into this issue since I'm trying to synchronize an external selection state with React Flow and trying to render hidden nodes to represent selectable entities outside of React Flow.

**Comment by moklick** [comment]
What is happening here 😳 thanks! I will check it.
