### ISSUE TITLE
Background pattern moves along all react-flow instances

### ISSUE THREAD

**Issue by Pronink** [wbkd/react-flow#2685]
### Describe the Bug

Background pattern moves along all react-flow instances. Always the first rendered react-flow moves all patterns of all the rest of instances. This is due all `<pattern>` dom nodes uses the same id, and the rect next to it always reference the first encounter, due the dom ids should be unique.
It is reproducible at my project and in your official webpage https://reactflow.dev/

### Your Example Website or App

https://reactflow.dev/

### Steps to Reproduce the Bug or Issue

1. Go to [https://reactflow.dev/](https://reactflow.dev/)
2. Scroll down until you see the first and the second example at the same time
3. Drag the first react-flow example: all the background patterns moves
4. Drag the second react-flow example: none background pattern moves
5. Execute this code at developer tools console: 
```js 
document.querySelectorAll('#pattern-1')
document.querySelectorAll('rect[fill="url(#pattern-1)"')
```
Theese returns 4 elements each, when dom ids whould be unique.
To fix this issue, simply change the `id` attribute of `<pattern>` to `pattern-X` and the `fill` attribute of `<rect>` to `url(#pattern-X)`, where X should be an unique number

### Expected behavior

Each react-flow component has their unique background movement

### Screenshots or Videos

[video-13277758-32282fe554f8608d3b1ee85df4abbabd.webm](https://user-images.githubusercontent.com/17512287/207563124-d05aeaf5-d84e-4973-95db-6841f4ddbebd.webm)
PD: I edit the pattern color to black to make it more visible

### Platform

- OS: Windows, Linux
- Browser: Chrome
- Version: 11.1.1

**Comment by Pronink** [comment]
Oh, I will try it thx 😀 !!. 
I don't know if the `id` should be in the `<ReactFlow>` or in the `<ReactFlowProvider>`. I didn't see any example of code when the `id` is setted, and it doesn't appear in the prop list at [https://reactflow.dev/docs/api/react-flow-props/](https://reactflow.dev/docs/api/react-flow-props/). I don't think that a React component should have an `id`. The use of `id`s isn't recommended in React (we have `useRef`). `id`s and `class` attributes is for jquery, bootstrap or vanilla web programing.
Can't react-flow handle it internally? Using a random id to reference the `<pattern>` with the `<rect>` url

**Comment by moklick** [comment]
It's fine to use an id. You need to pass it to the `<ReactFlow />` component. In the next major release we will use Reacts `useId` hook. But for now we can't use it. Random ids don't work for SSR.

**Comment by moklick** [comment]
yep, the website is fixed.
