### ISSUE TITLE
Tailwind CSS not working with nextjs-reactflow(v11)

### ISSUE THREAD

**Issue by Julianwoolf** [wbkd/react-flow#2687]
### Describe the Bug

We are currently working on integrating tailwind CSS (v3) into our _nextjs(v13)-reactflow(v11)_ project. 

After a lot of trial and error, we concluded that tailwind currently only works with reactflow v10 versions. We also forked the following publicly available repo that uses nextjs-reactflow **(v10)** -tailwindCSS, and then upgraded the project to reactflow **v11**, which then also did not show any flowchart elements anymore (similiar to our own project). 

- Original repo using reactflow v10: https://github.com/tkcel/react-flow-demo. 
- Our fork upgraded to reactflow v11 not showing any elements anymore: https://github.com/Julianwoolf/react-flow-demo

Any ideas why this might be the case or how to fix this?

Thanks in advance!

 

### Your Example Website or App

Original: https://github.com/tkcel/react-flow-demo
Upgraded: https://github.com/Julianwoolf/react-flow-demo

### Steps to Reproduce the Bug or Issue

1. pull original repo from tkcel: https://github.com/tkcel/react-flow-demo. 
2. change reactflow version to v11 in package.json
3. npm install
4. minor code adjustments (e.g., changing "react-flow-renderer" to "react-flow", cf. forked repo: https://github.com/Julianwoolf/react-flow-demo)
5. npm run dev

### Expected behavior

Reactflow only shows dotted background, but no nodes or any other reactflow elements anymore.

### Screenshots or Videos

![reactflow_v10](https://user-images.githubusercontent.com/56506866/207627548-0b1b13ba-c01a-4a28-b08e-3dffaa717c7c.png)
![reactflow_v11](https://user-images.githubusercontent.com/56506866/207627559-2302651a-d9c7-4a51-9a33-1077168febb5.png)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 108.0. (newest version)

**Comment by moklick** [comment]
Are you loading the ReactFlow styles in _app.js? 

```js
import 'reactflow/dist/style.css';
```

**Comment by Julianwoolf** [comment]
Omg, yes, that made it work! Many thanks for the fast reply!
