### ISSUE TITLE
Maximum update depth exceeded at <StoreUpdater> component when I use useNodes()

### ISSUE THREAD

**Issue by Pronink** [wbkd/react-flow#2691]
### Describe the Bug

I have issues relating infinite loops, that can be caused by `useNodes()` hook. I come from [this issue](https://github.com/wbkd/react-flow/issues/2571) but my problem seems diferent. Im using `<ReactFlowProvider>` because I want to put some instances in the same page. Then I play with the codesandbox of the other issue and I can reproduce the error with and without `<ReactFlowProvider>`. I simplified too much the code to discard possible code bugs.
¿Can you take a look please? I don't know if if is it a bug.
Thank you so much!

### Your Example Website or App

https://codesandbox.io/s/reactflow-forked-q8g20r?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/s/reactflow-forked-q8g20r?file=/App.js
2. Open console to view the 2 lines of error
![image](https://user-images.githubusercontent.com/17512287/207814279-bdcf7568-5acf-4d98-8c2e-ae5ed4187865.png)
3. Comment `export default Flow;` and uncomment next lines: `export default function FlowWithProvider() { ...`
4. The error still ocurrs

### Expected behavior

The react-flow renders without infinite loops

### Screenshots or Videos

Codesandbox:
![image](https://user-images.githubusercontent.com/17512287/207814798-3e5dc806-d9a9-497e-9ac1-415cab1c6e52.png)

In my project:
![image](https://user-images.githubusercontent.com/17512287/207814706-724d1d7c-11ee-4cda-a13e-7b5ba39bd0ed.png)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 11.2.0

**Comment by moklick** [comment]
You want to use:

```js
const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
```

The `useNodes` and `useEdges` hook can be used in other components to access the nodes and edges but they are not meant to help you with managing your local state.

**Comment by Pronink** [comment]
There is no webpage in the documentation for useNodesState. It's only mentioned on a couple of pages. `useNodes()` should work without strange infinite loops. Why does that happen? Is `useNodesState()` compatible with multiple react-flow instances in the same web?
Thank you!
