### ISSUE TITLE
Connection curve preview generates always generates from "source" handle

### ISSUE THREAD

**Issue by natsu-k** [wbkd/react-flow#270]
Hi @moklick

I noticed today after updating to the latest release that when connecting nodes from target to source rather than source to target the curve preview is attached to the node's source rather than the target.

This can be replicated in the [example pages](https://react-flow.netlify.app/) by clicking on the target handle for the **You can find the docs on Github** node and trying to connect to **This is a default node** node.

You can see the preview is attached to the  **You can find the docs on Github** node's source handle, rather than the target handle.

This doesn't appear to impact the result once you create it. It only makes the preview incorrect.

![89390768-E079-4EB4-A7D6-BE3A9ACFDD5B](https://user-images.githubusercontent.com/22218632/83387527-37d03980-a430-11ea-8efd-966f24cc45bf.GIF)

**Comment by moklick** [comment]
Oh. That’s not nice. Thanks for the report we will check that
