### ISSUE TITLE
isInteractive is preventing custom click handlers

### ISSUE THREAD

**Issue by bartvanremortele** [wbkd/react-flow#271]
I have a use-case where I want to disable the graph from being changed. (E.g: nodes being dragged) but I still want to be able to click them to trigger UI changes elsewhere (E.g: a sidebar being opened with node information). 

I believe is-interactive is a good solution for this but the implementation of it is causing some issues. Because it's setting `pointer-events: none` on the nodeWrapper, click handlers in custom nodes are not being triggered. I can override it by setting `pointer-events: all` on the inner element that I want to attach a click listener to but for some reason this prevents panning, zooming, ... all interactivity when hovering on a node.

Steps to reproduce:
- Disable interactivity
- Adjust a node's style to have `pointer-events: all`
- Notice that only on this node you will not be able to zoom/pan/...

My suggestion is to add a flag that only disables the dragging / modification of the graph but keeps all attached listeners active.

Another option could be to drive the interactivity from CSS and be able determine as the implementor which `pointer-events: none | all | auto` are getting set based on the class given to the parent graph.

**Comment by moklick** [comment]
Hey,

I disabled the pointer events for inactive graphs in order to be able to zoom and pan even if the pointer is above a node. 

Maybe we could introduce another option like ‘disablePointerEventsWhenInactive’ or something like that.

What do you think about that?

**Comment by bartvanremortele** [comment]
Hey,

Yes, I did some further digging and now understand why it's implemented in the way it is. The zoom layer has a lower `z-index` than the nodes and the `pointer-events: none` makes it possible to trigger the handlers on the zoom layer because the node's events are disabled. 

As far as I understood (by reading [this issue](https://github.com/d3/d3-zoom/issues/66) on d3-zoom, the UX I want is probably not a good idea. 

That being said, I believe react-flow should still give a user the choice of enabling/disabling pointer-events in a straightforward manner. I'm not a fan of `disablePointerEventsWhenInactive`, I would inverse this by adding an option to disable the dragging. `enableDragging` which defaults to true seems like a better option in my opinion.

That being said, I have decided to take a different path for now and re-introducing the `pointer-events: all` inside of the node and improving the UX around the zooming/panning by highlighting the hovered node and changing to cursor to give a clearer indication as to which actions are accessible on his current cursor position.

**Comment by bartvanremortele** [comment]
perhaps we can figure out a better solution using [d3-zoom's filter](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_filter)

**Comment by moklick** [comment]
Maybe ‘enablePointerEvents’ would be a good option. And yes I would like to drop d3-zoom and d3-selection.

**Comment by bartvanremortele** [comment]
@moklick I did some searching to improve the zooming / panning behaviour in conjunction with click handlers on nodes and came across https://github.com/prc5/react-zoom-pan-pinch#readme this implementation. I believe this might be a good contender to replace d3-zoom. 

Your thoughts?

**Comment by moklick** [comment]
I will have a look, thanks!

**Comment by dekelb** [comment]
Another feature that is related to this is an option to allow drag & drop the elements (nodes), but prevent creating new edges.
As far as I understand this is not possible atm.

@moklick is there an option for this out-of-the-box?

**Comment by moklick** [comment]
hey @dekelb 

sorry I can't follow you. What do you want to achieve?

**Comment by dekelb** [comment]
thanks for the super fast reply @moklick !
I want to be able to move the nodes (drag and drop), but in my case - the creation of new edges (create new connection between nodes) should be disabled.

Maybe I missed something in the docs, but from what I understand there is no simple way to do this.

**Comment by moklick** [comment]
@dekelb can you open a new issue for this? thanks!

**Comment by dekelb** [comment]
@moklick just opened #291 - let me know what you think.

**Comment by moklick** [comment]
Hey,

we just released v.4.0.0. There we dropped `isInteractive` and added `nodesDraggable`, `nodesConnectable` and `elementsSelectable`. This use case should be working with `nodesDraggable` = `false` and `nodesConnectable` and `elementsSelectable` = true. Can you confirm @bartvanremortele ?

**Comment by emielwit** [comment]
If you use `nodesDraggable={false}` then the `onElementClick` is not working anymore.

**Comment by moklick** [comment]
Good catch @emielwit! The bug should be fixed with version 4.2.2

**Comment by moklick** [comment]
hey @bartvanremortele I will close this issue for now. Feel free to open a new one for discussing the switch from d3-zoom to another zoom/pan library.

**Comment by pfidelus-dev** [comment]
Hi, I met issue similar to @emiel-betty but for onNodeDoubleClick event. I Opened a bug https://github.com/wbkd/react-flow/issues/2525
