### ISSUE TITLE
dynamic grouping error

### ISSUE THREAD

**Issue by lexoring** [wbkd/react-flow#2713]
### Describe the Bug

Hello. Grouping error at https://reactflow.dev/docs/examples/nodes/dynamic-grouping/
I made a video, everything is clearer there.

### Steps to Reproduce the Bug or Issue

At the beginning I add blocks and then a group block. Then I move these blocks to the group block and when I click on the block on the last one, the menu does not appear where it is needed. And when I delete the block, a general error occurs because of this.

### Expected behavior

In my video, when I click on the last block, the menu should appear above it. This bug is in chrome and opera. I couldn't replicate the error in firefox.

### Screenshots or Videos

[recording.webm](https://user-images.githubusercontent.com/74623056/209584422-e42d0ca6-305c-4914-ac83-f9760da21162.webm)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [108.0.5359.125]

**Comment by moklick** [comment]
thanks @lexoring! It was an issue with the node sorting. I just fixed it.
