### ISSUE TITLE
Edge seems to be shortened depending on the parent div

### ISSUE THREAD

**Issue by RichestYoo** [wbkd/react-flow#2721]
### Describe the Bug

Hello, 
Firstly, I appreciate the maker of this project for this good work.
I've almost reached what I've wanted with this, but found one problem.

When I made a small diagram, I didn't notice the problem, but when the contents to be drawn got bigger, 
I found that the edges do not connect nodes fully, if the wrapping div's height is not 100%.

### Steps to Reproduce the Bug or Issue

Here I attach s a simple source code to draw 100 nodes that goes from top to bottom.
Near the end of the code, you'll see one div with height:60% and another with height:100%.
You can reproduce what I mean by switching the two lines:

```
import React, { useEffect, useState, useRef } from "react";
import ReactFlow, { Controls, Background } from 'react-flow-renderer';


export default function ModelDesign(props) {
	const [layerNodes, setLayerNodes] = useState([]);
	const [layerEdges, setLayerEdges] = useState([]);

	useEffect(()=>{

		const tmpLayerNodes = [];
		for (let i=0;i<100;i++)
		tmpLayerNodes.push({
			id: "N"+i, 
			type: i===0 ? "input": (i===100 ? "output":"default"),
			data: {label: `layer ${i}`}, 
			position:{x:60, y:i * 70 + 10},
			width:150, height:40,
			style:{ width:"150px", height:"40px", borderStyle:"solid"},
		});
		setLayerNodes(tmpLayerNodes);
		
		const tmpLayerEdges = [];
		for (let i=0;i<99;i++){
			tmpLayerEdges.push({
			id: i+"_0_"+(i+1)+"_0",
			type: 'smoothstep',
			source:"N"+i, sourceHandle:"h0",
			target:"N"+(i+1), targetHandle:"h0"
			});
		}
		setLayerEdges(tmpLayerEdges);
		
	},[]);

	return (
		<div style={{ width: "100%", height: "100%" }}>
                        {/*<div style={{ border: "1px solid #d5d5d5", width: "100%", height: "60%"}}>  */}
			<div style={{ border: "1px solid #d5d5d5", width: "100%", height: "100%"}}> 
				<ReactFlow defaultNodes={layerNodes} defaultEdges={layerEdges}
					panOnScroll={true} zoomOnScroll={false}
				>
					<Controls />
				</ReactFlow>
			</div>
		</div>
	);
}
```

### Expected behavior

All the nodes should be connected via edges, but they aren't when I apply a certain percentage or vh as the height of the DIV,
as you can see the screenshot.

Can anyone help me with this symptom?

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/51534815/210208916-b9d6bd6e-aa85-4d6d-bdcc-d6671f84d270.png)

### Platform

- OS: [Windows11 Pro]
- Browser: [Chrome]
- Version: [Chrome 108.0.5359.125(Official Build) (64bit)]

**Comment by moklick** [comment]
Hey! Can you create a codesandbox for this one?

**Comment by RichestYoo** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you for your quick response.
It's my first time to make codesandbox; the following is the link.

https://codesandbox.io/s/funny-architecture-mip769?file=/src/App.js

One small change I've made is:
In local environment, 60% worked, but in codesandbox, parent div of Reactflow didn't appear.
so I changed % to vh, then it appeared with the same symptom I mentioned.

Thank you.

																																																																																																																														유경석																																										㈜소이넷, 인공지능 전문회사 | 개발팀장																																											***@***.***																																																						a 성남시 분당구 성남대로331번길 8, 킨스타워 1503호Homepage soynet.io 
YouTube https://www.youtube.com/channel/UC1BESOUWv1wqSByyCDwG0Bg																																																																														

--------- 원본 메일 ---------

    
        보낸사람: Moritz Klack ***@***.***>
        받는사람: wbkd/react-flow ***@***.***>
        
            참조: RichestYoo ***@***.***>, Author ***@***.***>
        
        날짜: 23.01.02 20:02 GMT +0900
        제목: Re: [wbkd/react-flow] Edge seems to be shortened depending on the
 parent div (
        
        
    
    
        
Hey! Can you create a codesandbox for this one?

**Comment by moklick** [comment]
I can't see any issue here. The edges looking good.

**Comment by RichestYoo** [comment]
p{margin-top:0;margin-bottom:0}
    


    Hi,

At the top, it looks no problem.
But going all the way down, you can see that the edge is not connected to the node.
You can see the difference as in the red box in the below:


Thank you.																																																																																																																														유경석																																										㈜소이넷, 인공지능 전문회사 | 개발팀장																																											***@***.***																																																						a 성남시 분당구 성남대로331번길 8, 킨스타워 1503호Homepage soynet.io 
YouTube https://www.youtube.com/channel/UC1BESOUWv1wqSByyCDwG0Bg																																																																														

--------- 원본 메일 ---------

    
        보낸사람: 유경석 ***@***.***>
        받는사람: wbkd/react-flow ***@***.***>
        
        날짜: 23.01.02 21:50 GMT +0900
        제목: RE: Re: [wbkd/react-flow] Edge seems to be shortened depending on the parent div (
        
        
    
    
        
    Thank you for your quick response.
It's my first time to make codesandbox; the following is the link.

https://codesandbox.io/s/funny-architecture-mip769?file=/src/App.js

One small change I've made is:
In local environment, 60% worked, but in codesandbox, parent div of Reactflow didn't appear.
so I changed % to vh, then it appeared with the same symptom I mentioned.

Thank you.

																																																																																																																														유경석																																										㈜소이넷, 인공지능 전문회사 | 개발팀장																																											***@***.***																																																						a 성남시 분당구 성남대로331번길 8, 킨스타워 1503호Homepage soynet.io 
YouTube https://www.youtube.com/channel/UC1BESOUWv1wqSByyCDwG0Bg																																																																														

--------- 원본 메일 ---------

    
        보낸사람: Moritz Klack ***@***.***>
        받는사람: wbkd/react-flow ***@***.***>
        
            참조: RichestYoo ***@***.***>, Author ***@***.***>
        
        날짜: 23.01.02 20:02 GMT +0900
        제목: Re: [wbkd/react-flow] Edge seems to be shortened depending on the
 parent div (
        
        
    
    
        
Hey! Can you create a codesandbox for this one?

**Comment by moklick** [comment]
![Screenshot 2023-01-02 at 16 29 17](https://user-images.githubusercontent.com/2857535/210251681-7d62fa70-bd39-4b74-a28e-cb738fa2def7.png)

also the nodes at the very bottom look good to me

**Comment by RichestYoo** [comment]
p{margin-top:0;margin-bottom:0}
    


    I see the problem on my side is not visible to you T.T

Just in case to make sure we're working on the same environment, 
can OS / browser make a difference like this?

I tried with Chrome, Edge, and Opera, but couldn't with Safari because it's not available on Windows.

																																																																																																																														유경석																																										㈜소이넷, 인공지능 전문회사 | 개발팀장																																											***@***.***																																																						a 성남시 분당구 성남대로331번길 8, 킨스타워 1503호Homepage soynet.io 
YouTube https://www.youtube.com/channel/UC1BESOUWv1wqSByyCDwG0Bg																																																																														

--------- 원본 메일 ---------

    
        보낸사람: Moritz Klack ***@***.***>
        받는사람: wbkd/react-flow ***@***.***>
        
            참조: RichestYoo ***@***.***>, Author ***@***.***>
        
        날짜: 23.01.03 00:29 GMT +0900
        제목: Re: [wbkd/react-flow] Edge seems to be shortened depending on the parent div (Issue #2721)
        
        
    
    
        

also the nodes at the very bottom look good to me

**Comment by moklick** [comment]
I can't reproduce this. Please re-open if the issue still persists.
