### ISSUE TITLE
couldn't create edge for target handle id...  with Custom Node

### ISSUE THREAD

**Issue by kyworkspace** [wbkd/react-flow#2727]
### Describe the Bug

Hi
I tried to use this beatiful library to make small size erd.
so I made Custom Node type "entity" and "Floating Connection Line" Following Docs.
But It doesn't work well. 

![image](https://user-images.githubusercontent.com/45280952/210517707-af28caa2-2677-48f3-9494-410691227396.png)

Alse I read other issue.
[](https://github.com/wbkd/react-flow/issues/2364)

Unfortunately, It was not helpful for me.

in Conclusion,
1. I want draw Custom Node with Floating Line.
2. What did I miss?

Thanks for beatiful library and sorry about my english description.

### Your Example Website or App

https://codesandbox.io/s/keen-kepler-19twsd

### Steps to Reproduce the Bug or Issue

1. click the any "◀" button 
2. click the any "▶" button 

If I draw component as Node Label, It work well.
But it's not my purpose...

### Expected behavior

I expect like this pic.
![image](https://user-images.githubusercontent.com/45280952/210518958-70b3b799-c85d-41cc-8c36-3e7205e58789.png)

But  it show
![image](https://user-images.githubusercontent.com/45280952/210519260-ed62d70c-885b-4f56-aa3b-e5628267208f.png)

### Platform

- OS: [Windows]
- Browser: [Chrome, ]
- Version: [11]

**Comment by moklick** [comment]
It seems that your custom node doesn't have a target handle. Tr to replace your source handle with these two handles:

```js 
<Handle type="source" position={Position.Right} />
<Handle type="target" position={Position.Left} />
```

You only need to an id to a handle if you have multiple source or target handles.
