### ISSUE TITLE
onSelectionContextMenu doesn't work with selectionOnDrag

### ISSUE THREAD

**Issue by rayoverweij** [wbkd/react-flow#2733]
### Describe the Bug

The `onSelectionContextMenu` handler doesn't work when right-clicking a selection created with `selectionOnDrag` set to true, even though it does work when `selectionOnDrag` is set to false (or not set).

### Your Example Website or App

https://codesandbox.io/s/brave-firefly-d5zjbf?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

See the CodeSandbox. I have a (rudimentary, stripped version of my) custom context menu implemented that should show up when a user right-clicks a selection.

When `selectionOnDrag` is false, it works (Shift+select then right-click on the selection); when `selectionOnDrag` is true, it doesn't work and the browser context menu shows.

### Expected behavior

`onSelectionContextMenu` should work regardless of how a selection came to be.

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 108
- React Flow 11.4.0

**Comment by bcakmakoglu** [comment]
Your sandbox works fine for me (aside from a missing `position: absolute` on the ctx menu element, so it actually uses the top, left values).
When `selectionOnDrag` is true, the `onSelectionContextMenu` event is still fired and the context menu shown.
Did I miss something? :)

**Comment by rayoverweij** [comment]
You must have, because it really doesn't work for me. What browser are you on? If you're also on Chrome I'll make a screen recording.

(I updated the Codesandbox with `position: absolute` on the menu (thanks, it's still early here) and an `onPaneClick` handler to hide the menu when clicking anywhere.)

**Comment by bcakmakoglu** [comment]
I tried it in FF and Chrome, both worked fine, here's a quick clip.

https://user-images.githubusercontent.com/78412429/211290964-a9995df8-fd77-40b5-ac35-ef2cb76cfdff.mov

**Comment by rayoverweij** [comment]
And what were your values for `panOnDrag` and `selectionOnDrag` there? Because it works for me if they are set to true and false, respectively (and you drag using Shift), but not when set to false and true (in that order).

**Comment by bcakmakoglu** [comment]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/78412429/211291449-0e20ed6c-a124-49d1-b5a0-1184f0d0494a.png">

**Comment by rayoverweij** [comment]
https://user-images.githubusercontent.com/24462089/211293809-42f6d2a9-c41b-4629-b0e5-d140bc99e73d.mp4

Can't seem to get the context menu to actually show up on the Windows screen recording (it does appear for me) but at least this shows the custom menu isn't appearing. Last guess - are you on macOS?

**Comment by bcakmakoglu** [comment]
Yeah, I'm using a Mac.

Have you tried logging if the event ever fires?

**Comment by rayoverweij** [comment]
Then I'm guessing there's some difference in how (Chrome on) Windows and macOS implement the context menu? I couldn't see what else would cause this.

(Yes, I verified with logging that the event never fires, and edited down the Codesandbox to remove some of my custom context menu code as just the logging shows the problem as well. Now in the sandbox with `panOnDrag=false` and `selectOnDrag=true` the message "hi!" does not appear on selection context click, but with the reverse settings it _does_ appear.)

**Comment by moklick** [comment]
Could you try to install the latest version 11.4.2 and add `event.preventDefault()` in your event handler?

**Comment by rayoverweij** [comment]
That worked, thanks so much for the two quick fixes!
