### ISSUE TITLE
onPaneContextMenu fires when dragging with panOnDrag set to the right mouse button

### ISSUE THREAD

**Issue by rayoverweij** [wbkd/react-flow#2734]
### Describe the Bug

Hi, me again, ten minutes later.

When `panOnDrag` is set to `[2]` (or `[1, 2]`) and you pan the Flow with the right mouse button, when releasing it, `onPaneContextMenu` fires.

### Your Example Website or App

https://codesandbox.io/s/muddy-glitter-wvjq8t?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

Open the Codesandbox console window, pan around with the right mouse button, and see the log ("What?") appear.

### Expected behavior

`onPaneContextMenu` should only fire when clicking with the right mouse button, not dragging.

(I realise this is different to the default browser behaviour, where the context menu will appear when releasing the right mouse button after dragging it, but it is similar to web apps like Miro, where the drag-on-right-mouse paradigm comes from.)

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 108
- React Flow 11.4.0

**Comment by moklick** [comment]
Thanks for the report. I will check it!

**Comment by moklick** [comment]
It's a bug. The button is always zero while zooming/panning.
