### ISSUE TITLE
Request: dynamically updating handles

### ISSUE THREAD

**Issue by natsu-k** [wbkd/react-flow#275]
Hi,

I wanted to build an in-app editor to be able to build out the node graphs using this library. To record the toggle state of the 4 potential handles on a node, I store this in the elements JSON array.

I then use the custom node to render the handle as either a source or target handle (or no handle) depending on the state in the array.

Today I noticed, unfortunately the internal **__rg.handleBounds.source** and **__rg.handleBounds.target** for an element only currently recalculate on the **updateNodeDimensions** action.

https://github.com/wbkd/react-flow/blob/3445c5f967405de26d88102700fda7bcba096526/src/store/index.ts#L165-L181

This results in the edge renderer failing to identify the handles for a curve, and defaulting to Bottom and Top positions.
https://github.com/wbkd/react-flow/blob/115ba4fd3cd16adaeb4f167cd510ae16c58fcfc5/src/container/EdgeRenderer/index.tsx#L143-L146
I know this sort of fall outside the scope of what your making. But is there a way to recalculate the handleBounds for a node on demand? Even if it was possible to call the **updateNodeDimensions** action, it would return early if the dimensions have not changed.

As a last result, I could probably do something awful by changing the size of the element for a frame to allow the resize observer trigger and update automatically, but I was hoping for a more elegant solution.

So not a bug, and you are free to close this issue off. But if you had any advice that would be great 😄 

Thanks

**Comment by moklick** [comment]
Hey @natsu-k 

you can call internal actions like this:

```javascript
import { useStoreActions } from 'react-flow-renderer';

const SomeReactFlowChildren = () => {
  const updateNodeDimensions = useStoreActions(actions => actions. updateNodeDimensions);
  

  return null:
}

```

Does it help?

**Comment by natsu-k** [comment]
Hey @moklick 

I tried something similar earlier but I got an error, I don't think I can access the store from the same functional component that I render ReactFlow in? This is my first time using react so learning as I go along. I might be able to access it in the custom node functional component though, I'll have to have a look tomorrow.

I think that the check you have in updateNodeDimensions will effectively stop me from using it anyway https://github.com/wbkd/react-flow/blob/3445c5f967405de26d88102700fda7bcba096526/src/store/index.ts#L170-L177

**Comment by bartvanremortele** [comment]
@natsu-k correct, the provider of the store is wrapping everything inside the main graph component and only descendants of that provider can call the `useStoreActions`. I do believe we can make it possible to approach the store from higher level components but it would require additional changes.

**Comment by natsu-k** [comment]
@bartvanremortele @moklick   - thanks for the feedback so far, really helpful.
I had a bit of a look into it and I was able to get to a point where I can call updateNodeDimensions through a child functional component and pass down the which nodeElement to retrigger through a state. Although I have to do some pretty hacky code directly editing the __rg.height to bypass the the if statement in the function.
```javascript
    if (!matchingNode || matchingNode.__rg.width === dimensions.width && matchingNode.__rg.height === dimensions.height) {
      return;
    }
```
It would be nice if calculating/updating the __rg.handlebounds wasn't tied directly to updating the node dimensions. If it was a separate function/action then it could be accessed through the store and utilised a lot more easily.

I don't think you should worry about making it possible to access the store from the higher level component, unless that's something that would directly benefit the core project.

**Comment by moklick** [comment]
Hey,

you can now wrap the `ReactFlow` component with a `ReactFlowProvider` in order to be able to call actions and use store outside of the `ReactFlow` component. It is used in the [provider example](https://github.com/wbkd/react-flow/blob/master/example/src/Provider/index.js)

**Comment by rusakovStas** [comment]
Hi! 
Thanks for your component! It's really cool) 
I'm not sure that it's related to this issue, but i have a problem with refresh) 
Is there a way to update 'width' props on that component?  
`<svg width="1400" height="543" class="react-flow__edges"></svg>`
I have a form with dynamic area, and when that area is appeared/disappeared outer container have changes its size, but that svg width property doesn't changes. And when i call FitView via Controls it uses old sizes(

**Comment by moklick** [comment]
hey @rusakovStas 

thanks! Could you open a new issue for that?

**Comment by rusakovStas** [comment]
Of course)
