### ISSUE TITLE
Duplicate x button in search field

### ISSUE THREAD

**Issue by kahboom** [wbkd/react-flow#2750]
### Describe the Bug

There is a duplicate clear button in the search field of the catalog.

### Steps to Reproduce the Bug or Issue

1. Open Kaoto
2. Click on the Catalog button
3. Type into the search field
4. See the duplicate x button

### Expected behavior

There should only be one x (clear) button.

### Screenshots or Videos

![x-button](https://user-images.githubusercontent.com/3844502/212371410-3afe39ec-88a7-4a35-838b-1b78d0b7afeb.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: v0.5.0

**Comment by kahboom** [comment]
Sorry I'm losing my mind, please ignore this issue :joy

**Comment by moklick** [comment]
👀
