### ISSUE TITLE
Warning: Maximum update depth exceeded on empty node array

### ISSUE THREAD

**Issue by iyobo** [wbkd/react-flow#2758]
### Describe the Bug

Whenever ReactFlow gets an empty node array
```
 <ReactFlow
        nodes={[]}
       edges={[]}
        ...
```

It starts repeatedly throwing this error.
<img width="1775" alt="image" src="https://user-images.githubusercontent.com/5804246/213234928-ae2729a9-dd3d-4d80-997a-0ccb13fbea2a.png">

It only seems to happen on empty arrays in the `nodes` param and not the `edges` param.

You might say, "just feed undefined if the array is empty." The problem with that is:
-  in a multi-page react app, the nodes/edges from the previous display do not clear up when switching to a page with an undefined `nodes` param. The "empty" graph view is still populated with old data. The graph view only clears up when switching to it from a page that did not have a previous reactflow initialized in it.
- using null or undefined can lead to other internal state errors. The ReactFlow component should be updated to be able to gracefully handle an empty array.

### Steps to Reproduce the Bug or Issue

```
 <ReactFlow
        nodes={[]}
       edges={[]}
```

Open browser dev console and see scrolling maximum depth error 

### Expected behavior

There should be no maximum depth error with empty node array.

### Screenshots or Videos

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/5804246/213234928-ae2729a9-dd3d-4d80-997a-0ccb13fbea2a.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 10.3.17

**Comment by moklick** [comment]
Please upgrade to the latest version. I can't repro this. Feel free to re-open if the issue still persists.
