### ISSUE TITLE
Connection Radius

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#2759]
I would like to drag a connection line close to a handle to connect it (and not necessarily directly above it). This makes it easier to connect nodes.

**Comment by moklick** [comment]
released in v11.5.0

**Comment by italodeandra** [comment]
I'm having this issue where it does snaps from the sides, but not from inside of it.

https://github.com/wbkd/react-flow/assets/19225266/062de0b5-b53f-4a43-a0fa-f31c00eafc82

How do I fix this?

**Comment by bcakmakoglu** [comment]
@italodeandra You might want to check the latest comment on [this issue](https://github.com/wbkd/react-flow/issues/3378#issuecomment-1723256009).

>The reason for this behaviour is that we always use the handle below the mouse when we find one. If there is none, we check if we are inside the connection radius and only if that's the case you get the snapping. This means that you should be able to display a 1x1px handle and just increase the connection radius based on the size of your nodes. Does this solve your issue?

**Comment by italodeandra** [comment]
Thanks @bcakmakoglu

That's a nice workaround. It worked.
