### ISSUE TITLE
How add Icon to Custom Edge

### ISSUE THREAD

**Issue by Yogendra-Telus** [wbkd/react-flow#276]
Hi 

I can see we can add CustomEdge as well under Edge type but how can we add Icon in CustomeEdge(Let's suppose i want to add remove icon over edge).
   <>
      <path id={id} style={style} className="react-flow__edge-path" d={`M ${sourceX},${sourceY}L ${targetX},${targetY}`} fill="url(#img1)" />
      <text>
    --->  < img tag><----
      <textPath href={`#${id}`} style={{ fontSize: '12px' }} startOffset="50%" textAnchor="middle">
          {label} 
      </textPath>
      </text>
    </>
when i am adding <img/> tag below textpath getting compilation error can you add support to add  icon or image over the edge.

Email:- er.yogendra.17@gmail.com

Thank
Yogendra

**Comment by moklick** [comment]
Hey,

the edges are SVG based so you need to use the SVG image tag like `<image xlinkHref={imageSrc} x={centerX} y={centerY} height="50px" width="50px" />`.
