### ISSUE TITLE
Option to restrict zoom axis

### ISSUE THREAD

**Issue by elijahbenizzy** [wbkd/react-flow#2774]
### Please describe the feature that you want to propose

Amazing library. Thank you!

One quick Q -- I often have flows that are potentially really long -- its nice to view the whole thing, but it would also be nice to restrict zoom to just one axis. E.G. zoom just on the left axis. In this case its representing a dependency graph with x-size of nodes specifying time, so I'd like to zoom in just on particular timeframes while keeping the entire Y-axis in view.

(1) does anyone know of a workaround that could enable this now?
(2) is this a feature you'd consider supporting?

Cheers!

**Comment by AJNandi** [comment]
https://reactflow.dev/docs/api/react-flow-props/#panonscrollmode-1

**Comment by elijahbenizzy** [comment]
> https://reactflow.dev/docs/api/react-flow-props/#panonscrollmode-1

Oh, awesome! Thanks! Didn't see it. 

I have not been able to get it to work. Tried locally in my complex use-case and there was no effect. Then I tried the example on this page: https://reactflow.dev/docs/examples/overview/, with this code:

Am I missing something?

```typescript
import React, { useCallback } from 'react';
import ReactFlow, {
  addEdge,
  MiniMap,
  Controls,
  Background,
  useNodesState,
  useEdgesState,
  PanOnScrollMode
} from 'reactflow';

import { nodes as initialNodes, edges as initialEdges } from './initial-elements';
import CustomNode from './CustomNode';

import 'reactflow/dist/style.css';
import './overview.css';

const nodeTypes = {
  custom: CustomNode,
};

const minimapStyle = {
  height: 120,
};

const onInit = (reactFlowInstance) => console.log('flow loaded:', reactFlowInstance);

const OverviewFlow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const onConnect = useCallback((params) => setEdges((eds) => addEdge(params, eds)), []);

  // we are using a bit of a shortcut here to adjust the edge type
  // this could also be done with a custom edge for example
  const edgesWithUpdatedTypes = edges.map((edge) => {
    if (edge.sourceHandle) {
      const edgeType = nodes.find((node) => node.type === 'custom').data.selects[edge.sourceHandle];
      edge.type = edgeType;
    }

    return edge;
  });

  return (
    <ReactFlow
      nodes={nodes}
      edges={edgesWithUpdatedTypes}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      panOnScrollMode={PanOnScrollMode.vertical}
      onConnect={onConnect}
      onInit={onInit}
      fitView
      attributionPosition="top-right"
      nodeTypes={nodeTypes}
    >
      <MiniMap style={minimapStyle} zoomable pannable />
      <Controls />
      <Background color="#aaa" gap={16} />
    </ReactFlow>
  );
};

export default OverviewFlow;

```

**Comment by moklick** [comment]
You also need to set `panOnScroll` - this changes the default behaviour so that you pan the canvas while scrolling. Is that what you are looking for?

**Comment by moklick** [comment]
please re-open if this is still unsolved.
