### ISSUE TITLE
Edges cannot be created after dragging a node

### ISSUE THREAD

**Issue by xsmithdev** [wbkd/react-flow#2786]
### Describe the Bug

When dropping a node and another, I can create a connection. But whenever I drag a node, I can no longer create any connections, and click-connect fails. Afterward, when dragging nodes, the console repeatedly logs the same connection error. And when dragging a handle, nothing happens.

```
"[React Flow]: Couldn't create edge for source handle id: "0c77482c-1d2e-4569-8312-0a04987a5ab5", 
edge id: reactflow__edge-0e1900ff-8429-4a76-a70e-8fa26e004bd20c77482c-1d2e-4569-8312-0a04987a5ab5-7b665c4d-cb57-4074-9f8f-3b94ca114e8854e75d08-1e69-43f2-bb55-689c68f3d126."
```

### Your Example Website or App

https://github.com/Blackfall-Labs/visualizr/tree/refactor-implementation

### Steps to Reproduce the Bug or Issue

1. Drop 2 nodes onto the area
2. Without moving anything, create a connection from one node to another
3. Move a node
4. Attempt to create a connection
5. Nothing happens
6. Attempt to click one handle, then another
7. Nothing happens

### Expected behavior

I expect much like the initial connection, the other connections should happen seamlessly.

### Screenshots or Videos

https://user-images.githubusercontent.com/11479772/215638636-beffc703-2eff-4ade-9604-772b42dae4b8.mp4

### Platform

- OS: Windows
- Browser: Microsoft Edge (chromium)
- Version: 11.5

### Additional context

With additional testing, just clicking on a node is enough to disable connections.

**Comment by xsmithdev** [comment]
Using a `dragHandle` works, but once the node is moved, handles no longer respond.

**Comment by xsmithdev** [comment]
Okay so `useUpdateNodeInternals` on the child component that handles the connection handles now allows for connections (after a rerender or two), but as soon as I move a node, the connections disappear. And when adding more columns to my table node, all connections disappear as well.

**Comment by moklick** [comment]
this has nothing to do with React Flow. You are creating a new id for the handles on every render https://github.com/Blackfall-Labs/visualizr/blob/refactor-implementation/src/components/table/table-column.tsx#L24 

You could do `${nodeid}-${columnIndex}` to fix this.

**Comment by xsmithdev** [comment]
I hadn't thought of that! Thank you, I was using UUIDs for each, and I thought `useMemo` would stop the re-rendering issue.
