### ISSUE TITLE
useOnSelectionChange does not support custom node types

### ISSUE THREAD

**Issue by xsmithdev** [wbkd/react-flow#2789]
### Describe the Bug

When using `useOnSelectionChange` with custom nodes such as `export type TableNode = Node<ITable, "table">`, typescript complains that "Type 'string' is not assignable to type '"table"'". 

### Steps to Reproduce the Bug or Issue

```ts
import { Node } from "reactflow";
export type TableNode = Node<ITable, "table">;
...
useOnSelectionChange({
    onChange: ({ nodes, edges }: { nodes: TableNode[]; edges: Edge[] }) => {
      setSelectedNodes(nodes);
      setSelectedEdges(edges);
    },
  });
...
```

### Expected behavior

There should be no error, the code works fine but the types are incompatible.

### Platform

- OS: Windows
- Browser: Edge (chromium)
- Version: 11.5

### Additional context

Possibly allow `useOnSelectionChange` to be generic to pass our own custom node types.

**Comment by moklick** [comment]
You can use the following typing and cast the nodes on your side:

```ts
const onChange = useCallback(({ nodes, edges }: OnSelectionChangeParams) => {
  const tableNodes = nodes as TableNode[];
}, []);
```

**Comment by xsmithdev** [comment]
Yes, thank you.
