### ISSUE TITLE
Handling of the outer container's size changes 

### ISSUE THREAD

**Issue by rusakovStas** [wbkd/react-flow#279]
Hello! 
I have a form with react-flow. 
That form have an "optional" area. 
When ReactFlow component mounts on form it works like a charm. 
But when an optional area appear outer component of ReactFlow have changes its size, but FitView works as if sizes remain the same. And i have to re-unmount the whole ReactFlow component to fix this. 
Is there any way to handle such size's changes?

**Comment by rusakovStas** [comment]
![Screen Shot 2020-06-02 at 9 55 19 PM](https://user-images.githubusercontent.com/21197242/83558921-6aeff700-a51c-11ea-8346-df55326baaec.png)

**Comment by moklick** [comment]
Thanks for the report. I think we need a resize observer for the pane or something like that.

**Comment by moklick** [comment]
Hey @rusakovStas 

should work with v.3.2.1

**Comment by rusakovStas** [comment]
Hey @moklick! 
Confirm! Now it works) 
You are the best! Thank you so much!)
