### ISSUE TITLE
Don't snap Connection Line to Handles where `isValidConnection` returns false

### ISSUE THREAD

**Issue by cmd-johnson** [wbkd/react-flow#2793]
### Please describe the feature that you want to propose

Right now, the connection line snaps to the closest handle inside the configurable `connectionRadius`.
This is great, however it makes for a somewhat strange UX when the connection line snaps to handles it cannot actually connect to.

For example: I have nodes that all have multiple source and target handles. Each of those handles has a specific data type, and only sources and targets with the same data type can be connected to each other. For each of those handles, calling `isValidConnection` returns `false` when the data types of the two handles are different.

When dragging a connection from any of those handles the connection line sticks to handles of incompatible data types. When dragging from a source handle, the line also snaps to other source handles.

This UX feels a bit strange. I would expect that the line only snaps to handles that actually allow for a connection to be made.

I think it'd be nice if there was a way to disable snapping for certain dragged connections. Either through the `isValidConnection` callback, or some other way.

I'd also be happy to make a PR for this if you can point me in the right direction!

**Comment by moklick** [comment]
That's a very good point - will be fixed with the next release #2802
