### ISSUE TITLE
Custom Node with contenteditable and nodrag is not editable on safari

### ISSUE THREAD

**Issue by ted-marozzi** [wbkd/react-flow#2796]
### Describe the Bug

Hello,
contenteditable divs can't be edited when used in a custom node. This is really unfortunate as input and textarea don't fit my needs. I have attached a repro below showing this. Even stranger my slightly more complicated custom node with contenteditable works on chrome but not safari.

### Your Example Website or App

https://codesandbox.io/s/young-surf-wju1qn?file=/TextUpdaterNode.js

### Steps to Reproduce the Bug or Issue

1. Go to the code sandbox
2. Edit the contenteditable div outside of the react flow component: it should edit
3. Edit the contenteditable div INSIDE of the react flow component: it doesn't edit

### Expected behavior

on step 3, I am seeing it should be editable but it is not.

### Platform

- OS: [e.g. macOS, Windows]
- Browser: [e.g. Chrome, Safari]
- Version: [latest]
Didn't try other combos

**Comment by moklick** [comment]
You can't have it all I guess :D However if you want parts of your custom node to be editable you can add the class name "nodrag".

**Comment by ted-marozzi** [comment]
Thanks for looking @moklick.
Okay so now its not working on safari but is working on chrome (this is the behavior my more complicated node is seeing as it already had nodrag). 

Here is the new link: https://codesandbox.io/s/wizardly-rosalind-ofkls8
This can be edited on chrome but not safari.

**Comment by ted-marozzi** [comment]
If you need me to open another issue, let me know.

**Comment by bcakmakoglu** [comment]
Strange, I can edit the `I can't be edited` box on FF, Chrome and Safari.

Here's me trying it on Safari:

https://user-images.githubusercontent.com/78412429/216325211-2dd58efa-da9b-4edd-a79a-038ab137c76f.mov

**Comment by ted-marozzi** [comment]
https://user-images.githubusercontent.com/38032037/216328846-1b36725d-e3f0-4542-b891-a3df4ec668b3.mov

Here is me reproducing on safari

**Comment by ted-marozzi** [comment]
If you don't mind, what is your os and machine version? @bcakmakoglu

**Comment by bcakmakoglu** [comment]
I'm on Safari Version 16.3 (18614.4.6.1.5)
My Macbook is running on Ventura 13.2

**Comment by ted-marozzi** [comment]
I'm on Safari Version 15.1 (17612.2.9.1.20)
Mac mini (M1, 2020) is running on Monterey 12.0.1.
I will update my os (and hence safari) to the latest. I wonder if somewhere we are using an unsupported (or buggy) browser api that got added (or fixed) in later versions of safari.

**Comment by bcakmakoglu** [comment]
[Might this be related?](https://stackoverflow.com/questions/20435166/contenteditable-not-working-in-safari-but-works-in-chrome)

**Comment by ted-marozzi** [comment]
It definitely could be. I downloaded Version 14.0 (15610.1.28.1.9) to try and reproduce but I can't. Couldn't see where to download 15.1 either.

**Comment by ted-marozzi** [comment]
https://user-images.githubusercontent.com/38032037/216461818-454e0802-8b33-4cad-a95e-f1a38b035022.mov

Okay on browserstack i confirmed that that is the issue. Nice find. For my code I will add this in the css. I not sure if that's something you want to do at the library level from your top level component and it only happens inside your component.

Thanks very much for you help.

**Comment by ted-marozzi** [comment]
Closing this as a workaround is provided and it doesn't make sense for the Lib to override globals.
Add this to your CSS or don't care about semi old versions of Safari.
```
[contenteditable] {
    -webkit-user-select: text;
    user-select: text;
}
```
