### ISSUE TITLE
EdgeClick on reactflow's subflow doesn't trigger

### ISSUE THREAD

**Issue by dancingflames** [wbkd/react-flow#2798]
### Describe the Bug

I have the same problem, is it a bug?

https://stackoverflow.com/questions/73766239/edgeclick-on-reactflows-subflow-doesnt-trigger

"I have my nodes like this:
```
const nodes = [
  {
    id: 'A',
    type: 'group',
    data: { label: null },
    position: { x: 0, y: 0 },
    style: {
      width: 170,
      height: 140,
    },
  },
  {
    id: 'B',
    type: 'input',
    data: { label: 'child node 1' },
    position: { x: 10, y: 10 },
    parentNode: 'A',
    extent: 'parent',
  },
  {
    id: 'C',
    data: { label: 'child node 2' },
    position: { x: 10, y: 90 },
    parentNode: 'A',
    extent: 'parent',
  },
];

export default nodes;
```
..and have connection between them

```
export default [{ id: 'b-c', source: 'B', target: 'C' }]
```

A is a parent node and B,C are its child nodes. But when clicking on edges with in a subflow group, the `onEdgeClick` does not trigger. But the same prop works when the edge is not inside a group ( subflow ).

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/lbi0ep?file=/nodes.js&utm_medium=sandpack

### Expected behavior

`EdgeClick ` triggers inside the subflow group

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey! 

The reason for this are the z-indices. The edges are behind the nodes. If you want to change that you can pass a `zIndex` higher than 0 to an edge. Example: https://codesandbox.io/s/wild-river-uhxq9w?file=/App.js:2065-2077
