### ISSUE TITLE
CustomNode work with 'antd' cannot be clicked

### ISSUE THREAD

**Issue by UNIkeEN** [wbkd/react-flow#2799]
### Describe the Bug

I placed some components from ‘antd’ on the node, such as a 'Select', but clicking the drop-down arrow button on the right did not respond. 
We received the following feedback when we submitted an issue to 'antd': 'There is no magic code on the antd side. It is all the event processing of the React life cycle. You can give feedback to reactflow or see if their documents have any configurable options. '
It seems that the onClick event has responded, such as the onMouseDown event is blocked (because it can be clicked normally on the mobile device)

### Your Example Website or App

https://codesandbox.io/s/antd-reproduction-template-forked-445lzi

### Steps to Reproduce the Bug or Issue

Click the right drop-down arrow button of Select in the node

### Expected behavior

The drop-down box of Select pops up normally

### Platform

<html>
<body>

Environment | Info
-- | --
reactflow | 11.5.2
React | 18.2.0
System | Windows 10
Browser | Chrome 109.0.5414.120

</body>
</html>

**Comment by moklick** [comment]
You need to add the class name "nodrag" to the Select component https://codesandbox.io/s/antd-reproduction-template-forked-tfn6mi?file=/components/Flow/CustomNodes/ActivationFunction.js:727-758 , docs: https://reactflow.dev/docs/api/nodes/custom-nodes/#prevent-dragging--selecting

**Comment by UNIkeEN** [comment]
thanks~
