### ISSUE TITLE
Reactflow + MaterialUI Select when drag enabled = Broken Select

### ISSUE THREAD

**Issue by MrDesjardins** [wbkd/react-flow#2804]
### Describe the Bug

If you are using the latest version of reactflow (11.5.3) and the latest of Material-UI (5.11.7) there is a scenario where the Material UI Select component does not display the options. Clicking the dropdown perform the action but does not show the _floating_ items. Material-UI puts these floating items at the root of the website. 

Reactflow blocks Material UI to display the options only if the `ReactFlow` components has these two properties to `true`:

```
  panOnDrag={true}
  nodesDraggable={true}
```
performs

### Your Example Website or App

https://codesandbox.io/s/reactflow-materialui-select-bug-3txn43?file=/src/Example.tsx:922-980

### Steps to Reproduce the Bug or Issue

1. Open the [CodeSandbox](https://codesandbox.io/s/reactflow-materialui-select-bug-3txn43?file=/src/Example.tsx:922-980)
2. Click the "Age" combo, it should show 3 items
3. BUG: It does not show the item
4. Co in the `Example.tsx` file and uncomment line 45 and 46 (panOnDrag={false} and nodesDraggable={false})
5. Try again, the select component shows its item

### Expected behavior

As a user, I expect that what is inside a node displays as intended. The option of drag/no-drag shouldn't have an impact on the content of the node.

### Screenshots or Videos

https://user-images.githubusercontent.com/1014796/216717904-a14cc8d8-a74f-4096-87a9-74c8c88bc57a.mp4

### Platform

- OS: macOS and Windows
- Browser: Chrome
- Version: Latest 109.0.5414.120

**Comment by moklick** [comment]
You need to add the class name "nodrag" to the select component.

**Comment by MrDesjardins** [comment]
Thank you @moklick I completely forgot about that property. 

For future people, here is the [CodeSandbox ](https://codesandbox.io/s/reactflow-materialui-select-bug-fix-n3968g?file=/src/CustomNode.tsx)with the fix.

**Comment by pfebrer** [comment]
Hi @moklick! This works if the control is inside the node, but not if it is in the toolbar. Is there a similar fix for controls that are inside `NodeToolbar`?

Thanks!
