### ISSUE TITLE
[Easy Connect] example was fixed in this repository (#2778), but example on the website still has this bug

### ISSUE THREAD

**Issue by evgenius1424** [wbkd/react-flow#2807]
### Describe the Bug

To reproduce:

Navigate to: 
https://reactflow.dev/docs/examples/nodes/easy-connect/ 

Try to connect one node to another one. If you move cursor to the middle of the target node you will see that it can be connected, but if you move cursor to the corner of the target node you can't create edge.

The description in #2778 was good enough so I think you will understand root cause.

### Steps to Reproduce the Bug or Issue

The same as #2778 

### Expected behavior

The same as #2778 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
thanks! Fixed with the latest release 11.5.4.

**Comment by evgenius1424** [comment]
@moklick I see that it's fixed at 11.5.4 but example with 11.5.5 has this bug again.
