### ISSUE TITLE
Strange behavior when using html input of number type inside custom node

### ISSUE THREAD

**Issue by MiriFurman** [wbkd/react-flow#2808]
### Describe the Bug

When using HTML input of type number inside a custom node in the flow and clicking the input arrows to increase/decrease it makes the numbers "run" and dowsn't stop after the click - unless clicking outside of the input.

### Your Example Website or App

https://codesandbox.io/s/flow-number-input-kpl4kx?file=/src/Flow.tsx

### Steps to Reproduce the Bug or Issue

1. add a custom node with input type='number' 
2. try to increase/decrease the numbers using the arrows inside the input

### Expected behavior

same as <input> outside the reactflow - the click on the arrows should only increase/decrease by 1.

### Screenshots or Videos

https://user-images.githubusercontent.com/38907017/216821868-d372d752-f81a-4faa-a2bf-98e3e3d61428.mov

### Platform

- OS: [macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

macOS, Chrome version 109.0.5414.119, reactflow version 11.5.2

**Comment by moklick** [comment]
Hey! You need to add the class name "nodrag" to the input field.

**Comment by MiriFurman** [comment]
hey @moklick this worked for a while but now the issue is back..any suggestions?

**Comment by moklick** [comment]
LGTM with the latest version: https://codesandbox.io/s/flow-number-input-forked-nrse3e?file=/src/CustomNode.tsx:562-591

**Comment by MiriFurman** [comment]
@moklick it happens when you add nodesDraggable={false}

**Comment by moklick** [comment]
If `nodesDraggable={false}`, you need to add the class name "nopan" to prevent panning behaviour. Not the best DX :/
