### ISSUE TITLE
Type '"right"' is not assignable to type 'Position'.ts

### ISSUE THREAD

**Issue by eiiot** [wbkd/react-flow#2812]
### Describe the Bug

When using the example configuration for the feature overview (https://reactflow.dev/docs/examples/overview/) and typescript, typescript throws the following error for the `Handle` element:

```Type '"right"' is not assignable to type 'Position'.ts(2322)```

As far as I can tell, this is an issue with the typing, specifically that `Handle.position`  takes an enum `Position` as opposed to some sort of tuple-string type.

```
export declare enum Position {
    Left = "left",
    Top = "top",
    Right = "right",
    Bottom = "bottom"
}
```

Any guidance on this would be appreciated.

### Your Example Website or App

https://codesandbox.io/s/bold-chatelet-6s7op6?file=/components/CustomNode.tsx

### Steps to Reproduce the Bug or Issue

- Go to `components/CustomNode.tsx` to see the typeerror.

### Expected behavior

I am able to use a string to set the position, or the example is updated to use the `enum`.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by yevgeniy-belov** [comment]
I found a way to fix the TS error:
`sourcePosition: Position.Right`

But it does nothing...

**Comment by eiiot** [comment]
> I found a way to fix the TS error: `sourcePosition: Position.Right`
> 
> But it does nothing...

Yeah that seems to be one solution. The docs should probably be updated to use the `Position` enum, if this is the intended behavior.

**Comment by moklick** [comment]
Thanks! I just updated the docs.
