### ISSUE TITLE
Even with nodesConnectable prop set as false, connections are getting created in easy connect mode.

### ISSUE THREAD

**Issue by ratnajeetshyamkunwar** [wbkd/react-flow#2814]
### Describe the Bug

When the canvas is in easy connect mode, even with the `nodesConnectable` prop set to **false**, the connections are getting created. 

### Steps to Reproduce the Bug or Issue

1. set nodesConnectable prop to false
2. go to canvas
3. drag and drop to create a connection

### Expected behavior

The new edge between nodes should not be created via drag and drop the connection

### Screenshots or Videos

https://user-images.githubusercontent.com/36529897/216982690-1f303df7-5861-4204-aaa8-9777c5259866.mov

### Platform

- OS: macOS
- Browser: Chrome
- Version: 109.0.5414.87 (Official Build) (x86_64)
- App version: 11.4.0

**Comment by bcakmakoglu** [comment]
In the docs examples, if you're changing the code, it does not *hot reload*. 
You have to press the refresh button on the bottom right for it to refresh.

[This sandbox works fine.](https://codesandbox.io/s/awesome-mestorf-314h5w?file=/App.js)

**Comment by ratnajeetshyamkunwar** [comment]
> In the docs examples, if you're changing the code, it does not _hot reload_. You have to press the refresh button on the bottom right for it to refresh.
> 
> [This sandbox works fine.](https://codesandbox.io/s/awesome-mestorf-314h5w?file=/App.js)

@bcakmakoglu I tried it in this sandbox as well. The same issue can be replicated here as well. The trick is to drop it exactly over the text which says **Drop here**

https://user-images.githubusercontent.com/36529897/217160170-59b365e4-a0ee-4ad1-90a6-357adc5da429.mov

**Comment by moklick** [comment]
This was an issue with the example. When you are implementing a custom node you need to pass `isConnectable` to the handles.

**Comment by ratnajeetshyamkunwar** [comment]
@moklick Thanks for the solution.
