### ISSUE TITLE
Unable to use css from react flow when style height is 100%

### ISSUE THREAD

**Issue by bepp-boop** [wbkd/react-flow#2815]
### Describe the Bug

Typescript React
<div style={{height:'100%' }}> will result in 
[React Flow]: The React Flow parent container needs a width and a height to render the graph. Help: https://reactflow.dev/error#004
 

### Steps to Reproduce the Bug or Issue

just create react app
npm react flow
...

### Expected behavior

I follow the intro but the way around it is to give plat number instead

### Platform

- OS: [ Windows, ]
- Browser: [ Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
You need to give all parents a height of 100% if you want to create a full screen app. 

```css
html, body, #root {
   height: 100%;
}
```

Create React App example: https://github.com/wbkd/react-flow-example-apps/tree/main/reactflow-create-react-app 
CSS: https://github.com/wbkd/react-flow-example-apps/blob/main/reactflow-create-react-app/src/index.css#L10-L14
