### ISSUE TITLE
Ctrl/Cmd Shortcuts Cause Next Delete To Fail

### ISSUE THREAD

**Issue by griffins-planera** [wbkd/react-flow#2826]
### Describe the Bug

Whenever you use a shortcut involving control or command (such as cmd+c), the next time you try to delete a node nothing will happen. `onNodesDelete` will not fire until you press the delete key a second time.

This can be seen directly on the example website. I have linked the code sandbox from feature overview.

### Your Example Website or App

https://codesandbox.io/s/x59dbq?file=/App.js&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

1. Have a node on the canvas
2. Click anywhere on the canvas
3. Press command + c
4. Select the node
5. Press the delete key: nothing happens
6. Press the delete key again: node is removed

### Expected behavior

Expected behavior is that the delete key will remove the node on the first attempt

### Platform

- OS: macOS
- Browser: Chrome
- Version: 11.5.5

### Additional context

Also note that arrow keys appear to work as the nodes are moved on the canvas. Though even after testing with the arrow keys delete will not work until you press it twice. 

This has become a frequent issue for us as users will often copy and paste nodes using our own custom shortcuts.

**Comment by transmissions11** [comment]
Still reproducing this on 11.5.6...

**Comment by bcakmakoglu** [comment]
@griffins-planera I can't reproduce the issue in the sandbox you linked.
I followed the steps described by OP and everything worked fine.

Did you do something differently to reproduce the issue?

**Comment by griffins-planera** [comment]
@bcakmakoglu I have not changed anything about my setup or steps since the original post. Are you on the same platform as me? MacOS + chrome

Here is a loom: https://www.loom.com/share/8cb39bef5a1d418cab2a3eddf02de4eb

**Comment by bcakmakoglu** [comment]
I'm on MacOS but was using FF, let me re-try on Chrome :)

**Comment by bcakmakoglu** [comment]
I was able to reproduce this issue *but* only when doing command + c twice and then selecting and trying to delete a node 🤔
Very strange

**Comment by bcakmakoglu** [comment]
Alright, so

After doing a bit of research it seems this is a MacOS related issue (https://stackoverflow.com/questions/11818637/why-does-javascript-drop-keyup-events-when-the-metakey-is-pressed-on-mac-browser - Post is rather old but the top answer from 2019 seems to still hold up sadly)

So what happens is, when I press cmd + c for example, it stores that the keys `Meta` and `c` were pressed

When I release `c` it does not trigger a keyup event and thus, the `c` key isn't removed from the pressedKeys set
Now I release `Meta` but this time the key is removed from the `pressedKeys` set *but* `c` is still in the set
When I press `Backspace` now, after selecting a node, the set contains `c` *and* `Backspace` so the keys don't match up and the node deletion doesn't fire

**Comment by griffins-planera** [comment]
@bcakmakoglu Appreciate the thorough investigation. Will this ticket be re-opened and resolved? I recognize the OS level behavior mentioned, but other javascript based libraries/products do not share this issue. This appears to be a limitation of the `pressedKeys` implementation in react flow. 

As you mentioned the `c` keyup event does not fire while `Meta` is held, but somehow that state is corrected after the first `Backspace` press. Do we understand why the second `Backspace` works even when a keyup for `c` never fired, and could that lead to a correction at the time `Meta` is released instead?

`c` being erroneously marked pressed while `Meta` remains held down is a much smaller issue than the delete callback experiencing a failure any time the user performs a shortcut on MacOS.
