### ISSUE TITLE
Be able to select/highlight text inside a node

### ISSUE THREAD

**Issue by bdhmin** [wbkd/react-flow#2828]
### Please describe the feature that you want to propose

Currently, nodes are draggable and elements can be interacted with, but text inside a node is not selectable, even when disabling drag for the node.

**Comment by dabdine** [comment]
interestingly I had just been searching for this when I saw the issue appear, then get closed. Is there an existing solution?

**Comment by dabdine** [comment]
Nevermind! My issue was panning. I just added the `nopan` class to the div that contains the input fields in my custom node.
