### ISSUE TITLE
onNodeClick doesn't seem to fire for Custom Nodes

### ISSUE THREAD

**Issue by TomVance** [wbkd/react-flow#2830]
### Describe the Bug

When using a custom node it doesn't appear to fire the onNodeClick method supplied to the root `ReactFlow` component. Apologise if this is not-supported or I'm just missing it somewhere in the docs.

I had a brief dig around the code base and can see some conditionals around the wrapNode HOC, but couldn't quite work out how to get the onNodeClick method to flow through as I'd expect

### Steps to Reproduce the Bug or Issue

1. Use a custom node for rendering
2. Supply a onNodeClick method to the base ReactFlow component
3. Note that it does not fire when clicking on the custom node

### Expected behavior

Some way to get the onNodeClick method to fire

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by TomVance** [comment]
This seems to be some issue with having nodes in react state and having `onNodesChange={onNodesChange}` set. For now this is okay as I wont need it, but worth noting

**Comment by moklick** [comment]
I can't repro this. The click handler works for custom nodes too. Check this codesandbox: https://codesandbox.io/s/hardcore-chatelet-fwf4h8?file=/src/Flow.tsx (Node4 is a custom node). Please provide a csb, if the issue still persists.
