### ISSUE TITLE
Couldn't create edge for source handle id: "undefined"

### ISSUE THREAD

**Issue by dev-zero** [wbkd/react-flow#2840]
### Describe the Bug

I am trying to get a project from someone else to run: https://github.com/zachdoty/BrainPress/ and run into the issue that the edges are not drawn and on the console I get the error 

```
[React Flow]: Couldn't create edge for source handle id: "undefined", edge id: a412cc99e1ebcd66. Help: https://reactflow.dev/error#008
```

Downgrading from 11.5.5 to 11.4.2 resolves the issue.

### Steps to Reproduce the Bug or Issue

Install [BrainPress](https://github.com/zachdoty/BrainPress) with the latest ReactFlow and try with a small Canvas.

### Expected behavior

Edges to be drawn

### Platform

- OS: macOS
- Browser: Firefox
- Version: 11.5.5

### Additional context

Unfortunately I do not have much experience in React (or React Flow), but the app seems to be simple enough such that maybe someone has an idea on how to fix it :-)

**Comment by moklick** [comment]
The issue here is that there is a custom node with multiple handles but the edges don't use the `sourceHandle` id (or at least I can't find it in the repo). The previous behaviour was not correct, but we might change it again, so that there is a warning and a connected edge to the first handle we can find.

**Comment by dev-zero** [comment]
@moklick thanks a lot, together with the [documentation](https://reactflow.dev/docs/guides/custom-nodes/) I think I see the problem. The [edges (in the BrainPress code) ](https://github.com/zachdoty/BrainPress/blob/ea22f3183239c9a570546886beb3058fec1d406e/src/utils/index.ts#L86-L90) define only source and target but not the specific handles on which to attach. The original data (the Canvas) from Obsidian has it:

```
    "edges": [
        {"id": "abc", "fromNode: "def", "fromSide": "bottom|right|left|top", toNode: "ghi", "toSide": "bottom|right|left|top"}
```

Which should therefore be rather straightforward to add: name the handles in the custom node types properly, then load `fromSide` and `toSide` as `sourceHandle` and `targetHandle`.

The only problem might be: a handle can be both source and target in the original data.
Does this matter for ReactFlow when creating the edges programmatically?

**Comment by moklick** [comment]
you can specify all handles as type "source" and set connectionMode to "loose" https://reactflow.dev/docs/api/react-flow-props/#connectionmode

**Comment by dev-zero** [comment]
@moklick thank you very much for the help, closing since this was really an issue with the application
