### ISSUE TITLE
onConnectEnd points to old reference

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#2841]
### Describe the Bug

onConnectEnd doesn't seem to have the latest reference when it's called. 

### Expected behavior

onConnectEnd should always have the latest reference. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jonschlinkert** [comment]
Was just coming to report this.

**Comment by moklick** [comment]
Hey @jonschlinkert 

can you check if it still happens with the latest version 15.5.6? It should be fixed.

**Comment by ERuseckas** [comment]
@moklick based on npmjs.com latest version is 15.5.5. Is it not published?

**Comment by moklick** [comment]
@ERuseckas this is the package: https://www.npmjs.com/package/reactflow Current version is 11.5.6

**Comment by moklick** [comment]
Please re-open if the issue persists.
