### ISSUE TITLE
Node tooltip <MiniMap/>

### ISSUE THREAD

**Issue by fitterfizzle** [wbkd/react-flow#2858]
### Please describe the feature that you want to propose

It would be extremely helpful to display the node label for example on mouse enter when hovering a node in the minimap.

**Comment by chrtze** [comment]
Hey,

this is currently not possible with the default Minimap node. A quick solution would be to take the minimap component out of the library and add your own implementation of the [MiniMapNode](https://github.com/wbkd/react-flow/blob/main/packages/minimap/src/MiniMapNode.tsx).

We are planning on adding a new prop to the MiniMap component to solve this problem and letting you pass your own SVG component to the MiniMap directly. You can follow the development here: https://github.com/wbkd/react-flow/blob/main/packages/minimap/src/MiniMapNode.tsx

**Comment by chrtze** [comment]
Closing this issue in favor of https://github.com/wbkd/react-flow/issues/2867

**Comment by chrtze** [comment]
@fitterfizzle it's now possible to pass a `nodeComponent` to the `MiniMap` component to implement custom functionality. You need to install [React Flow version 11.6.0](https://github.com/wbkd/react-flow/releases/tag/11.6.0).

**Comment by fitterfizzle** [comment]
> @fitterfizzle it's now possible to pass a `nodeComponent` to the `MiniMap` component to implement custom functionality. You need to install [React Flow version 11.6.0](https://github.com/wbkd/react-flow/releases/tag/11.6.0).

Thanks, how can we disable the default label on hover for the minimap?

![image](https://user-images.githubusercontent.com/96863959/225582533-aff8f02b-609a-4244-83b9-888890641e72.png)

**Comment by moklick** [comment]
@fitterfizzle you can set `ariaLabel={null}`.
