### ISSUE TITLE
Doc Example: Add more example(s) for Edge Label Renderer

### ISSUE THREAD

**Issue by cliffordfajardo** [wbkd/react-flow#2864]
Hi I am a reactflow pro subscriber 🙏

## What is the suggestion?
Add more example(s) for Edge Label Renderer (`<EdgeLabelRenderer>`)
Currently there is only 1 example for the [<EdgeLabelRenderer />](https://reactflow.dev/docs/api/edges/edge-label-renderer/) on the docs page for it

![image](https://user-images.githubusercontent.com/6743796/221391335-8375b046-c24b-44b9-a051-881afdc5ef40.png)

Perhaps a few more sandpack code examples for the following common would be good:
1. Render <EdgeLabelRenderer> at the beginning of edge an path
2. Render <EdgeLabelRenderer> at the end of an edge path

## Motivation for Changes?
`<EdgeLabelRenderer>` is one of the new powerful APIs introduced in react-flow 11.2 that allows userzs to create custom Edge Labels with React code instead of SVG; since this is becoming a common utility, some more examples would be helpful 🙏 

## Related References
- https://github.com/wbkd/react-flow/discussions/2863
- https://discord.com/channels/771389069270712320/1046759869409140748/1046759872907182160

**Comment by moklick** [comment]
That's a good idea :) I just added a configurable start-end label edge.
