### ISSUE TITLE
`ariaLabel` prop does not work for the node and edge

### ISSUE THREAD

**Issue by Max-ChenFei** [wbkd/react-flow#2883]
### Describe the Bug

Hi, from the doc, the [arialLabel](https://reactflow.dev/docs/api/edges/edge-options/#arialabel) of the edge is from `${source}` to `${target}` at default. but when I hover the mouse on edge in the [overview example](https://reactflow.dev/docs/examples/overview/), this label does not show. The buttons on the control do show the label.

I also add the `arialLabel` to the node data in the `initial-elements.js` as the following example, but it still does not work.
```
 {
    id: '1',
    type: 'input',
    data: {
      label: 'Input Node',
    },
    position: { x: 250, y: 0 },
    ariaLabel: "This is a input node"
}
```

### Your Example Website or App

https://codesandbox.io/s/wm2vrx?file=/initial-elements.js&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

This example is the copy of the [official overview example](https://reactflow.dev/docs/examples/overview/) with little change.
1. Hover the edge, no ariaLabel
2. Add the ariaLabel pros in the `inittial-elements.js`the node, 
3. Hover the node,  no ariaLabel

### Expected behavior

We can see the ariaLabel for the edge and node as the minimap or control buttons.

### Platform

- OS: [Windows]
- Browser: [Microsoft Edge]
- Version: [Version 110.0.1587.46 (Official build) (64-bit)]

### Additional context

Thanks for your help.

**Comment by moklick** [comment]
Hey! An aria label is meant to be used by screen readers. It's not a tooltip equivalent. If you want that, you can create a custom node and use the `title` prop. `ariaLabel` prop for nodes and edges work as expected.

**Comment by Max-ChenFei** [comment]
Thanks a lot:)
