### ISSUE TITLE
onSelect function for ReactFlow

### ISSUE THREAD

**Issue by devdevsu** [wbkd/react-flow#2901]
### Please describe the feature that you want to propose

Hello, I am trying to change the zIndexes of group nodes and attached nodes.
I create a function onNodeClick
```
const onNodeClick = useCallback(
		(event: MouseEvent, node: Node) => {
			if (node.type === 'layerNode') {
				const nodes = getNodes();
				const children = nodes.filter((n) => n.parentNode === node.id).map((n) => n.id);
				setNodes((nds) => {
					return nds.map((n) => {
						if (n.data.pinned) {
							return {
								...n,
								className: children.includes(n.id) ? 'pinned groupSelected' : 'pinned',
							};
						}
						return n;
					});
				});
				console.log(children);
			}
		},
		[getNodes, setNodes],
	);
```
When I click on the group node, the nodes flicker because the group node becomes selected before the attached node,
Is there any solution to run this code before or at the same time as selecting the node.
Perhaps you have a solution to get onNodeSelect

**Comment by chrtze** [comment]
Hey @devdevsu, did you try using the [`onSelectionChange`](https://reactflow.dev/docs/api/react-flow-props/#onselectionchange-nodes-edges--onselectionchangeparams) callback?

**Comment by devdevsu** [comment]
Thank you for not noticing this feature, issue resolved
