### ISSUE TITLE
Dynamic Grouping examle bug

### ISSUE THREAD

**Issue by devdevsu** [wbkd/react-flow#2902]
### Describe the Bug

If you first add a new group and then move the group so that it touches the neighboring one, the node from the new group will be moved to the neighboring one
I made a small fix for myself, which I describe below, but maybe you will be interested to know about this bug, because perhaps the problem is deeper than I think, and maybe not

### Your Example Website or App

https://reactflow.dev/docs/examples/nodes/dynamic-grouping/

### Steps to Reproduce the Bug or Issue

Create a new group, put any node in it, move the new group so that it intersects with the old group, move node5 (in my case) to the intersection of these groups and it will belong to the old group

### Expected behavior

I solved this problem by changing the condition in onNodeDragStop 

```
if (node.type === 'node' && !node.parentNode) {
// code
}
```

instead of

```
if (node.type !== 'node') {
        return;
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/119572534/223564692-13cbf262-36ef-47ff-ace4-9909ac02ef19.png)
![image](https://user-images.githubusercontent.com/119572534/223565210-f65eec7d-009d-4154-8088-a9e782b9df9c.png)
![image](https://user-images.githubusercontent.com/119572534/223565287-18d9032f-215b-488c-8800-2e04ddaa245d.png)

### Platform

- OS: Linux
- Browser: all
- Version: all

**Comment by ted-marozzi** [comment]
Nested subflows could be a feature not a bug. In my app I am using them on purpose.

**Comment by devdevsu** [comment]
In this case, it is not an obvious pattern of behavior and was not originally implied, so it is a bug

**Comment by ted-marozzi** [comment]
Ah right, I miss understood what the issue was, that does look like a bug.

**Comment by moklick** [comment]
Hey @devdevsu 

yep, the condition should be the same as in onNodeDrag. Thanks, we just fixed it.
