### ISSUE TITLE
[Feature request] New edge style between "straight" and "smoothstep"

### ISSUE THREAD

**Issue by rsamp** [wbkd/react-flow#2907]
### Please describe the feature that you want to propose

Hi, I'm working on a project where we're deciding whether to migrate from mxGraph to React Flow. Any chance I can request a new edge style that lands somewhere between `"straight"` and `"smoothstep"`? I guess it's also similar to the `"default"` edge style, but a little less curvy.

I do see https://reactflow.dev/docs/examples/edges/custom-connectionline/ and https://reactflow.dev/docs/api/edges/custom-connection-line/, but wondering if this might be worth making available as built-in option.

I'm hoping for something similar to the "HierarchicalLayout" Storybook example from [maxGraph](https://github.com/maxGraph/maxGraph#development):

<img width="919" alt="image" src="https://user-images.githubusercontent.com/12284336/224107318-edc35fa9-58ed-4827-8e29-ec860651e929.png">

**Comment by moklick** [comment]
Hey @rsamp 

we will not add edge routing to the core of react flow. In your image the edges are aware of the other node positions. This is too complex for the core. You can implement something similar with a custom edge https://medium.com/swlh/routing-orthogonal-diagram-connectors-in-javascript-191dc2c5ff70 or use a layouting library like elkjs https://github.com/kieler/elkjs

**Comment by tisoap** [comment]
For people interested, I've build [react-flow-smart-edge](https://github.com/tisoap/react-flow-smart-edge) using A* pathfinding to route edges around other nodes, avoiding intersections. It has smart equivalents for every type of edge React Flow has.
