### ISSUE TITLE
Handle useNodeId(); context null - early return - breaks my custom node tests

### ISSUE THREAD

**Issue by fr1n63** [wbkd/react-flow#2910]
### Describe the Bug

There has been a recent update to the Handle component to clean up and rationalise.

```
    if (!nodeId) {
      store.getState().onError?.('010', errorMessages['010']());

      return null;
    }
```

I have a complex custom node with multiple input/output handles that I was able to test previously just by wrapping the node with `ReactFlowProvider` - this no longer works because it looks like I need to stand up a complete ReactFlow instance just to test that a `Handle` is rendered. I can't see any easy way of just rendering the NodeProvider - none of that appears to be accessible externally.

Is this early return necessary? There is a developer warning.

### Steps to Reproduce the Bug or Issue

Render a custom `Node` within a `ReactFlowProvider` with a `Handle` inside it.

```
<ReactFlowProvider>
      <FlowNode {...nodeProps} />
 </ReactFlowProvider>
```

### Expected behavior

I expected to be able to render a Handle within a Node in isolation for testing purposes

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
We removed that condition. You should be able to render a custom node within a provider again.
