### ISSUE TITLE
ConnectionLine Disappearing

### ISSUE THREAD

**Issue by dotsinspace** [wbkd/react-flow#2911]
### Describe the Bug

i can tell what is the problem and i have tried all possible solution.

i have added the edge connecting my two custom nodes. now there are two issue which i am encountering.

1. ConnectionLine doesnt appear when i start dragging from source until i leave the click when reached on the target.

2. I have two custom nodes with default edge connecting both. now that too not appearing.

### Steps to Reproduce the Bug or Issue

Seriously dont know why it is happening.

### Expected behavior

ConnectionLine should be visible when there is any short of intention to connect two nodes.

### Screenshots or Videos

<img width="1719" alt="Screenshot 2023-03-11 at 2 30 54 AM" src="https://user-images.githubusercontent.com/76559517/224427420-04b8e1ad-f182-456d-b471-16db432f03d7.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
can you provide a codesandbox for this?

**Comment by LIJUN-XU** [comment]
I also have this problem, have you found the reason?

**Comment by moklick** [comment]
@LIJUN-XU please provide an example: https://new.reactflow.dev
