### ISSUE TITLE
Looking for usage syntax change by a consumer

### ISSUE THREAD

**Issue by imvetri** [wbkd/react-flow#2912]
### Please describe the feature that you want to propose

**TDLR**: code to configuration. configuration catch up, just like webpack.

**Mind voice:** : I think currently all the examples are separated, and the provided description about the files can be wrapped into an abstract or an interface so that, user like me, a consumer do have to change or create a new file while taking inspiration from the given example, instead, I'd like to just change a json property, examples like auto resize, automatic new node, automatic new handle, automatic backgrounds etc.

Please convert the provided samples in form of configuration enabled so that all examples look like a different configuration instead of looking like different file dependencies.

**Behaviour**

As an user, I expect to create dynamic handles for a node - number of handles.
As an user, I expect automatic creation of next node when an user clicks, drags, drops an handle - creates one new node, of same type.
As an user, I expect to reduce the node data that gets passed to react-flow to be automatically generated and stored to localStorage when I release, when I reload page, it automatically loads from localStorage.
As an user, I expect to be able to save the configuration of the page after I dynamically create new nodes, from dynamic handles, and be able to reload the configurationin in form of a  json file. 

**P.S,** code to configuration is a best practice.

Please feel free to prompt me with your questions if you have doubts.

**Comment by imvetri** [comment]
For example
`
<ReactFlow
      showControls: true | false
      showBackground: true | false
      
  `
![Screenshot 2023-03-13 at 10 49 27 PM](https://user-images.githubusercontent.com/6542274/224777836-9ac63366-a484-46e5-bd73-9f2202905765.png)


Next example provided is about customNodes - this is not needed as the nodes attribute already takes in a type attribute of node type


Just like node type, an edge can also be given a type such as flowing or static.

![Screenshot 2023-03-13 at 10 52 58 PM](https://user-images.githubusercontent.com/6542274/224778619-b9a030bb-8b40-4aae-aeec-82b134cbaa73.png)

Make all the node's label editable by default when user clicks on the Node. For example, this screenshot says it is editable only when I choose the input field, mouse on hover, click, then change the text.

https://reactflow.dev/docs/examples/nodes/update-node/


![Screenshot 2023-03-13 at 10 53 50 PM](https://user-images.githubusercontent.com/6542274/224779172-d5d69212-d58b-4446-869d-11b0a8f484e3.png)


Move stress node testing to performance section from the docs https://reactflow.dev/docs/examples/nodes/stress/



these examples and my opinion may be because I'm influenced towards configs than code, mostly because, configs can be converted to check box or drop down on the html, in my circle, I believe less code is a new trend because what I believe is less code is easy, because backend is just read and write where as frontend is show or hide.

**Comment by moklick** [comment]
Hey @imvetri 

thanks for your suggestions. 

You can already do all the things you described with React Flow. If all those cases would be supported through props we would have to maintain way more complex code. IMHO we have too many props already and should try to strip out some and replace them with components or hooks wich are composable. We try to keep React Flow low level and flexible and this is not possible with your config driven approach. If you want to have something like that you can build it on top of React Flow but the library itself is not the right place for that.
