### ISSUE TITLE
we need new state

### ISSUE THREAD

**Issue by frantallukas10** [wbkd/react-flow#2913]
### handling state when reactflow finish every render

hello,

this state should be false before react flow was rendered. if react flow was rendered and it should change state true.

we have problem with auto layouting where we have to define useEffect connection when autolayout should be rendered. if we will have state from react flow we can use it there and say autolayout render after react flow was rendered

please help us!

**Comment by moklick** [comment]
Not 100% sure if I get your question right, but maybe you are looking for `useNodesInitialized` https://reactflow.dev/docs/api/hooks/use-nodes-initialized/ ?

**Comment by frantallukas10** [comment]
I need call autolayout after react flow was rendered and every nodes and edges was rendered

**Comment by moklick** [comment]
yep, then useNodesInitialized should work. Something like

```ts
const nodesInitialized = useNodesInitialized();

useEffect(() => {
  if (nodesInitialized) {
    // do layout
  }
 }, [nodesInitialized]);
```

**Comment by moklick** [comment]
After which user action do you want to do another layouting?

**Comment by frantallukas10** [comment]
After every action, if React Flow was re-rendered, I need to call auto layout if React Flow has finished rendering.

**Comment by moklick** [comment]
If you know the actions and if those actions are event handlers, like onNodeDragStop or clicking a button, you can call your layouting function inside those actions. That's better than using useEffect trying to listen to changes.

**Comment by strblr** [comment]
@moklick What is the way to proceed if we need to `fitView` when the nodes array passed to the graph changes in length?
We can't listen to `nodes.length` changes in a `useEffect` because `fitView` would be called too early, before the nodes are actually in sync within react-flow.

**Comment by moklick** [comment]
did you try to use `useNodesInitialized` https://reactflow.dev/docs/api/hooks/use-nodes-initialized/ ?

```js 
const { fitView } = useReactFlow();
const nodesInitialized = useNodesInitialized();

useEffect(() => {
  if (nodesInitialized) {
   fitView()
  }
}, [nodesInitialized, fitView]);

```

**Comment by strblr** [comment]
I will give it a try !
