### ISSUE TITLE
Set ReactFlow readonly / Set toggle interactivity On/off programmatically

### ISSUE THREAD

**Issue by Pronink** [wbkd/react-flow#2914]
### Please describe the feature that you want to propose

Like through the `'Toggle interactivity'` button of the `<Controls>` component, a way to activate or deactivate it through a prop in the `<ReactFlow>` component

**Comment by moklick** [comment]
Hey @Pronink 

the interactivity button toggles `nodesDraggable`, `nodesConnectable` and ˚elementsSelectable`.

**Comment by saswatac** [comment]
one small observation - i was looking to only disable element selection, but it was not enough to set elementsSelectable=False. i needed to set all the three props to false.
