### ISSUE TITLE
Unable to interact with Select component within node

### ISSUE THREAD

**Issue by MarkFuller1** [wbkd/react-flow#2920]
### Describe the Bug

I am unable to open a <@mui/material/Select> component rendered within a custom node type. 

#### Sandbox
https://codesandbox.io/embed/flamboyant-water-gthbwr?fontsize=14&hidenavigation=1&theme=dark

### Your Example Website or App

https://codesandbox.io/embed/flamboyant-water-gthbwr?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce the Bug or Issue

1. Open the sandbox 
2. Click on the select dropdown within the flow 
3. It will not respond or open. 

### Expected behavior

I expect the Select within the flow to behave like one outside the flow, it should open and allow the user to select an element from the dropdown. 

### Platform

- OS: Windows
- Browser: Chrome
- Version: 11.5.6

**Comment by moklick** [comment]
You need to add the class name "nodrag" to your select component. You also need to memoize your nodeTypes or define them outside the component. When you do:

```js 
<ReactFlow
  nodeTypes={{ custom: CustomNode }}
```

a new object gets created on every render which really slows down the performance of your app. This fixes it: https://codesandbox.io/s/wonderful-babycat-4gzd16?file=/src/Flow.js:409-447
