### ISSUE TITLE
Background movement is bounded to single flow when using multiple flows

### ISSUE THREAD

**Issue by KacperPaszkowski** [wbkd/react-flow#2930]
### Describe the Bug

When creating multiple flows with `ReactFlowProvider` background movement is bounded to the first flow. Background is using `pattern-$rfId` for fill's url, but `rfId` is set to `'1'` in initial store. It probably should have unique ID or at least store action to change it. 

### Steps to Reproduce the Bug or Issue

1. Create two `ReactFlowProvider`s with flow and background.
2. Move around on first flow.

### Expected behavior

Background should move independently but instead first flow controls both backgrounds.

### Platform

- OS: Windows 10
- react-flow: 11.6.1

### Additional context

Same bug as here https://github.com/wbkd/react-flow/issues/1037#issue-842279348

**Comment by moklick** [comment]
You need to pass an unique id to the <ReactFlow /> component. This will change when we'll drop React17 support and be able to use `useId` :)

**Comment by gwing33** [comment]
> You need to pass an unique id to the component. This will change when we'll drop React17 support and be able to use useId :)
It'd be great if `id` is documented in your API docs. Ended up code diving for this.

Additionally, while you can wait for `useId` to be available, writing a custom `useId` hook is pretty trivial/light:
```js
let useIdCount = 0;
function useId() {
    return React.useMemo(() => {
        useIdCount++;
        return `${useIdCount}`;
    }, []);
}
```
