### ISSUE TITLE
Ant design <Select/> doesn't open when used inside a custom node

### ISSUE THREAD

**Issue by CKanishka** [wbkd/react-flow#2936]
### Describe the Bug

I have a custom node where I am using the `Select` component from **antd** and the dropdown doesn't open when I click on it rather it opens when I right-click on it. 

I tried the same thing with a native HTML select element where the things seem to be working as expected
<img width="231" alt="image" src="https://user-images.githubusercontent.com/30779692/226335278-b346f40a-ff30-4fcd-8ccf-9b2f9b68f036.png">
but when I replace it with the antd component it doesn't behave as expected.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/30779692/226335109-8d13cb14-8a86-4370-a707-ed52112c1d7c.png">

### Your Example Website or App

https://codesandbox.io/s/tender-ishizaka-l7659x?file=/ColorSelectorNode.js

### Steps to Reproduce the Bug or Issue

1. Go to the **Custom node** in the flow
2. Click on the Select dropdown
3. The dropdown should open on click, but it doesn't
4. Rather, if we right-click on the dropdown then it opens up

### Expected behavior

The Select dropdown should open up on clicking.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 110.0

**Comment by moklick** [comment]
You have to add the class name "nodrag": https://codesandbox.io/s/damp-tree-0xorro?file=/ColorSelectorNode.js:948-975

**Comment by CKanishka** [comment]
Thank you so much for the prompt response @moklick. And for building and actively supporting this amazing library.

**Comment by afishhhhh** [comment]
> You have to add the class name "nodrag": https://codesandbox.io/s/damp-tree-0xorro?file=/ColorSelectorNode.js:948-975

@moklick doesn't work, if I set `nodesDraggable={false}`

**Comment by moklick** [comment]
If nodes are not draggable you need to prevent panning by adding the class name "nopan"

**Comment by jonvaljonathan** [comment]
Are there other classes like nodrag and nopan? I can't find them in the docs anywhere.

I'm having an issue where the sizing of the MUI Select dropdown doesn't work well. It gets smaller as I zoom in and bigger as I zoom out.

**Comment by AkileshRao** [comment]
For folks working on MUI Select inside a react flow node, it's the same solution. Without the "nodrag" className on the Select tag, it won't let you open the popover(internally used by MUI to open the list of options). 

```
<Select value="==" className="nodrag">
    <MenuItem value="==">==</MenuItem>
    <MenuItem value="!=">!=</MenuItem>
    <MenuItem value=">=">&lt;=</MenuItem>
    <MenuItem value="<=">&gt;=</MenuItem>
    <MenuItem value=">">&lt;</MenuItem>
    <MenuItem value="<">&gt;</MenuItem>
</Select>
```
This should work.

**Comment by ayushgundecha** [comment]
@AkileshRao thanks buddy, it worked!

> For folks working on MUI Select inside a react flow node, it's the same solution. Without the "nodrag" className on the Select tag, it won't let you open the popover(internally used by MUI to open the list of options).
> 
> ```
> <Select value="==" className="nodrag">
>     <MenuItem value="==">==</MenuItem>
>     <MenuItem value="!=">!=</MenuItem>
>     <MenuItem value=">=">&lt;=</MenuItem>
>     <MenuItem value="<=">&gt;=</MenuItem>
>     <MenuItem value=">">&lt;</MenuItem>
>     <MenuItem value="<">&gt;</MenuItem>
> </Select>
> ```
> 
> This should work.

Thanks buddy, it worked. 
Was solving this issue since hours

**Comment by Brandons404** [comment]
I was fighting this issue for hours with MUI Select component inside a custom node, I couldn't get the dropdown to appear. Adding the "nodrag" classname fixed it, no need to manage the open state of the popover. Thanks!
