### ISSUE TITLE
Re-render cause lost in styles of custom nodes

### ISSUE THREAD

**Issue by sidgangs99** [wbkd/react-flow#2945]
### Describe the Bug

I have custom nodes, using tailwind. When I try to update the nodes, react flow re renders and updates the styles. Most of the styles are removed.

I'm using zustand and update nodes in there, and have an useEffect if the nodes change then setNodes is called with new nodes.

As soon as setNodes is called, custom nodes looses its style.

### Your Example Website or App

[Web app](https://db-designer-381205.web.app)

### Steps to Reproduce the Bug or Issue

setNodes set new nodes re reders and looses styles

### Expected behavior

The styles should remain same for custom nodes which is not happening

### Platform

- OS: [macOS]
- Browser: [eChrome]
- Version: [11.6.1]

**Comment by moklick** [comment]
hey @sidgangs99 ! Could you create a codesandbox for this?

**Comment by sidgangs99** [comment]
You can check it out at: https://db-designer-381205.web.app

If you try to click on node and change the data type and save it. It will re render and loose it's style

**Comment by sidgangs99** [comment]
> hey @sidgangs99 ! Could you create a codesandbox for this?

You can check it out at: https://db-designer-381205.web.app

If you try to click on node and change the data type and save it. It will re render and loose it's style

**Comment by sidgangs99** [comment]
<img width="786" alt="Screenshot 2023-03-21 at 11 42 30 PM" src="https://user-images.githubusercontent.com/32275795/226703125-354167f8-9544-4abd-968d-63808fa90f28.png">

Might be helpful !!!!

**Comment by moklick** [comment]
I would need to see the code. Where does this useNodes and useEdges come from?

**Comment by sidgangs99** [comment]
<img width="693" alt="Screenshot 2023-03-22 at 8 31 19 AM" src="https://user-images.githubusercontent.com/32275795/226791029-adbaa6e4-c152-4b4f-906a-78f452c1738d.png">

This is coming for zustand
<img width="604" alt="Screenshot 2023-03-22 at 8 32 06 AM" src="https://user-images.githubusercontent.com/32275795/226791130-fdb88082-a0ed-468e-a046-d2ff4cca5968.png">
b9bb63308ec.png">

<img width="780" alt="Screenshot 2023-03-22 at 8 32 40 AM" src="https://user-images.githubusercontent.com/32275795/226791202-c0d428f6-3930-4887-b95f-ef6a6b956963.png">

**Comment by sidgangs99** [comment]
> I would need to see the code. Where does this useNodes and useEdges come from?

let me know if you need something else.

**Comment by moklick** [comment]
You should not create a local component state on top of the zustand state. Then you have to sync your two states which seem to be causing problems. You can follow our Zustand + React Flow guide here: https://reactflow.dev/docs/guides/state-management/ 


Please re-open if the issue still persists.
