### ISSUE TITLE
getSmoothStepPath return wrong label position for specific non-usual scenarios

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#2972]
### Describe the Bug

I tried to track most of scenarios but probably I miss something

### Steps to Reproduce the Bug or Issue

1. Create smooth step edge with those sources and targets

### Expected behavior

I expected to the label be aligned in the center of the edge instead of in wrong positions

### Screenshots or Videos

<img width="645" alt="image" src="https://user-images.githubusercontent.com/36650520/229152405-439eabcf-e37d-4f4f-8717-a0623d90ba43.png">

### Platform

- OS: macOS
- Browser: Chrome

**Comment by ArturMakly** [comment]
Any updates on this? @moklick  thanks!

**Comment by moklick** [comment]
@ArturMakly will be fixed in the next release

**Comment by moklick** [comment]
fixed in v11.8.0
