### ISSUE TITLE
`⇧ Shift` selection works on click instead of holding 

### ISSUE THREAD

**Issue by h0tw4t3r** [wbkd/react-flow#2974]
### Describe the Bug

The `⇧ Shift` selection works on click instead of holding.

Might be not a problem at all, but I think the all-known UX for `⇧ Shift` is selection while the key is held pressed.

### Your Example Website or App

flux.paradigm.xyz

### Steps to Reproduce the Bug or Issue

1. Go to flux.paradigm.xyz
2. Create multiple nodes
3. Select a node and hit `⇧ Shift` key.
4. Click on another node, and it will start a selection, although a `⇧ Shift` key is not held.

### Expected behavior

As a user, I expected the `⇧ Shift` key to be required to be held to select multiple nodes

### Screenshots or Videos

https://user-images.githubusercontent.com/35642018/229347679-4be3888c-0a4a-45b1-8773-e77a627a0a25.mov

### Platform

- OS: macOS
- Browser: Chrome
- Version: 111.0.5563.146
- Reactflow: ^11.5.6,

### Additional context

- https://github.com/transmissions11/flux/issues/37

**Comment by moklick** [comment]
This is built in. You can use the [`multiSelectionKeyCode`](https://reactflow.dev/docs/api/react-flow-props/#multiselectionkeycode) to configure this.

**Comment by h0tw4t3r** [comment]
> This is built in. You can use the [`multiSelectionKeyCode`](https://reactflow.dev/docs/api/react-flow-props/#multiselectionkeycode) to configure this.

I apologise, but you have not answered to my question.

The description states:
**While pressing** the `multiSelectionKeyCode` you can select multiple nodes and edges with a click. You can set it to null to disable functionality.

I interpret **while pressing** as holding a key, right? Or am I wrong?

As in the video I've attached to the issue, the described behaviour is not met.

Selection starts not **while pressing** a `multiSelectionKeyCode`, but rather clicking once on it, the selection mode is toggled.

I must disagree with the issue closure and would like to see it reopened.

**Comment by h0tw4t3r** [comment]
cc @moklick

**Comment by bcakmakoglu** [comment]
@h0tw4t3r What's your configuration look like?
I can't really reproduce this issue in a sandbox, could you outline the steps a bit more?
With the steps you gave above it works perfectly fine, I select a node, hit `Shift` and tried to select another node. The previously selected node becomes unselected and the new one selected.

I have *not* configured anything, so I'm using the defaults for key codes, so `Shift` wouldn't be the `multiSelectionKeyCode` but the `selectionKeyCode` which triggers the selection *box* that can be used to select multi elements at once using a blueish box to wrap them visually, whereas the `multiSelectionKeyCode` is the key code you would hold and click each node you want to select.

[Here's the sandbox I used.](https://codesandbox.io/s/stupefied-bohr-4ywh2n?file=/src/Flow.tsx)

**Comment by bcakmakoglu** [comment]
https://user-images.githubusercontent.com/78412429/229362824-517c31e1-7b5f-4bcc-a8d2-dd46b9650a39.mov

Here's a short clip just to clarify what I mean and what the difference between `selectionKeyCode` (the blue box) and `multiSelectionKeyCode` is.

In the clip the first action is done through `selectionKeyCode` (`Shift` by default). I hold `Shift` and click-drag until I select all nodes I want.
The second one through `multiSelectionKeyCode` (`Meta` by default), I hold the `command` key on my Mac and click each node.
The third is just not holding any key at all and clicking each node.

**Comment by h0tw4t3r** [comment]
@bcakmakoglu, thanks for a deep explanation!

I've checked out the sandbox you've provided, and it indeed works as intended.

The flux.paradigm.xyz repository can be found at https://github.com/transmissions11/flux,
and the specific configuration I'm referring to can be found [here](https://github.com/transmissions11/flux/blob/e0c9f471cfcfdb2a2b18a301836d7d0bbddb5fe9/src/components/App.tsx#L1035-L1070), and is next:
```jsx
<ReactFlow
  proOptions={{ hideAttribution: true }}
  nodes={nodes}
  maxZoom={1.5}
  minZoom={0}
  edges={edges}
  onInit={setReactFlow}
  onNodesChange={onNodesChange}
  onEdgesChange={onEdgesChange}
  onEdgesDelete={takeSnapshot}
  onNodesDelete={takeSnapshot}
  onEdgeUpdateStart={onEdgeUpdateStart}
  onEdgeUpdate={onEdgeUpdate}
  onEdgeUpdateEnd={onEdgeUpdateEnd}
  onConnect={onConnect}
  nodeTypes={REACT_FLOW_NODE_TYPES}
  // Causes clicks to also trigger auto zoom.
  // onNodeDragStop={autoZoomIfNecessary}
  onSelectionDragStop={autoZoomIfNecessary}
  selectionKeyCode={null}
  multiSelectionKeyCode="Shift"
  panActivationKeyCode={null}
  deleteKeyCode={null}
  panOnDrag={false}
  selectionOnDrag={true}
  zoomOnScroll={false}
  zoomActivationKeyCode={null}
  panOnScroll={true}
  selectionMode={SelectionMode.Partial}
  onNodeClick={(_, node) => {
    setLastSelectedNodeId(selectedNodeId);
    setSelectedNodeId(node.id);
  }}
>
```

I would appreciate if you could give an advice with a possible caveat that can cause the issues on **flux** side.

@moklick, the issue won't require a reopening, sorry for bothering. It's a user side error.

**Comment by moklick** [comment]
@h0tw4t3r no worries. You've set `multiSelectionKeyCode` to "Shift" and `selectionKeyCode` to "null". So you disabled the selection box and use Shift as a multi selection key code. You could set both props to "Shift" Not sure if that's what you want to achieve.

**Comment by bcakmakoglu** [comment]
From playing around with the website you linked it seems there's *is* some issue with your multi select, though I really can't identify why it's happening from the code.
Could there be anything else catching the keyup event on your end?
Have you tried using a different key, does it behave the same way? If you were to use some key like `A` instead of `Shift` just to see if the behavior differs?
It feels like`keydown` is caught but when you hold it for a little bit and release the key there is no keyup being caught and the multi select acts like it's still being held even though the key was released.

**Comment by h0tw4t3r** [comment]
I suppose this could have been fixed with https://github.com/wbkd/react-flow/pull/2892.

Can't reproduce it with an upgraded `reactflow`.

The version used before: `^11.5.6`, after upgrading to `^11.7.0` issue is not reproducible.

Thanks for your help!
