### ISSUE TITLE
Tailwind example doesn't work

### ISSUE THREAD

**Issue by gooonar** [wbkd/react-flow#2976]
### Describe the Bug

The tailwind example found here https://reactflow.dev/docs/examples/styling/tailwind/

Doesnt work, even in the sanbox 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/97283127/229613618-79ee873e-8603-4d51-9c45-2756123b733f.png">

Not sure if this link will be an use but here we are:

https://codesandbox.io/s/2y08k5?file=/App.js&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

1.  Go to https://reactflow.dev/docs/examples/styling/tailwind/
2. Click on sanbox

### Expected behavior

As a user I expect to be able to use the tailwind example and sandbox to learn how react-flow can be styled using tailwind css. 

### Platform

- OS: Mac OS
- Browser: Chrome
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Thanks for bringing this up again. I already opened an issue in the sandpack repo https://github.com/codesandbox/sandpack/issues/624 . I also removed the "Open Sandbox" in the tailwind example on our website.

**Comment by nicoprofe** [comment]
tailwind-config.js 
module.exports = {
    important: true,
}

GPT solved this in no time jajaj
