### ISSUE TITLE
Expose the handle bounds

### ISSUE THREAD

**Issue by andsav** [wbkd/react-flow#2978]
### Please describe the feature that you want to propose

Hi all 👋 

I see that [nodes are storing the position of their handles internally](https://github.com/wbkd/react-flow/blob/29790476d800269e363c8a5cae69cb3cbb39b3bf/packages/core/src/store/index.ts#L83-L88), but this is not exposed currently.

I have a use case where it would be very helpful to get the position of those handles (custom handles sticking out of the node + custom ConnectionLine that has a placeholder node on the tip snapping to the node when the cursor is either over the handle or the node itself). 

Any reason to not expose this information, or is there any other way to access it that I am missing? I am currently using `node[Symbol.for('internals')]?.handleBounds?.target` which works but feels very hacky.

Thank you!

**Comment by moklick** [comment]
That's the way! You could import the symbol like:

```js
import { internalsSymbol } from 'reactflow'
```

and then do:

```js
node[internalsSymbol]?.handleBounds?.target
```
