### ISSUE TITLE
Add NodeUpdateChange.

### ISSUE THREAD

**Issue by zta7** [wbkd/react-flow#2979]
### Please describe the feature that you want to propose

I want to use `triggerNodeChanges` to update the properties of a Node, and I can see this single change in the `onNodesChange` function. The existing NodeChangeType does not seem to be feasible, should  add a NodeUpdateChange?

**Comment by moklick** [comment]
we are only using the onNodeChange for internal events like dragging or removing a node for example. For this we can trigger the callback when an event happens. We don't want to observe nodes for property changes so we won't add something like a node update change event. For what do you need this?

**Comment by moklick** [comment]
Please re-open if the issue persists.
