### ISSUE TITLE
"Seems like you have not used zustand provider as an ancestor" error when using Background or Controls components

### ISSUE THREAD

**Issue by stanislav-grin** [wbkd/react-flow#2982]
### Describe the Bug

Hi guys, 

first of all, thank you for your great work and amazing product! 

Just updated to v11.7.0 and started to experience the error `Seems like you have not used zustand provider as an ancestor`, which occurred when Background or Controls components are included in ReactFlow as children. The ReactFlow component is wrapped with ReactFlowProvider. Using v11.5.x does not lead to this error.

<img width="400" alt="" src="https://user-images.githubusercontent.com/16938843/229778396-ab388639-4fab-4ac3-a780-932112158222.png">

Is this something I can fix in my code or it is a bug?

### Steps to Reproduce the Bug or Issue

1. Create a basic ReactFlow (no need for elements etc)
2. Wrap it with ReactFlowProvider
3. Out Controls or Background components into ReactFlow as children
4. See the error in console logs

### Expected behavior

No errors is expecting :)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 111.0.5563.146
- Version of ReactFlow: 11.7.0

**Comment by bcakmakoglu** [comment]
Are you using the `reactflow` package or the separate ones, i.e. `@reactflow/core` & `@reactflow/background` etc.?
If you're using the separate ones, try updating all of them to the latest version :)

**Comment by stanislav-grin** [comment]
Hi @bcakmakoglu, thanks for the answer. I'm using only `reactflow` package, everything is imported from it.

**Comment by moklick** [comment]
I can't repro this issue. Please try to remove node_modules and package-lock and install again.

**Comment by stanislav-grin** [comment]
> try to remove node_modules and package-lock and install again

That did the trick. Thank you!
