### ISSUE TITLE
Node resize and rotate not working as in the example

### ISSUE THREAD

**Issue by imvetri** [wbkd/react-flow#2988]
### Describe the Bug

The visual appearance is not the same as the example provided though I used the same code.

### Steps to Reproduce the Bug or Issue

Use the example code and render the node in the local setup

<img width="433" alt="Screenshot 2023-04-06 at 6 03 10 PM" src="https://user-images.githubusercontent.com/6542274/230380017-eedc8f73-0f7e-4a9b-acad-ba39cd90aeda.png">
<img width="334" alt="Screenshot 2023-04-06 at 6 03 31 PM" src="https://user-images.githubusercontent.com/6542274/230380041-9ebd8d8c-070b-4bfe-b5e0-47dc8169e77c.png">

### Expected behavior

Example code to work as expected

### Platform

Attached screenshot of the bug and the package.json dependencies.

**Comment by chrtze** [comment]
did you add the style.module.css file, too?

**Comment by imvetri** [comment]
yes I did.

Here is the demo - you can see the resize rotate at bottom left - https://ui-editor.github.io/flow/ 
Here is the PR with sample code - https://github.com/ui-editor/flow/pull/2/files#diff-b6bd901cffee9b25570471f8c88396dcd7bfbf47cacfd9cdeec396a043bb21ac 

https://user-images.githubusercontent.com/6542274/233209767-d091657c-1743-482b-a6c3-7329cf2ec349.mov

**Comment by imvetri** [comment]
@bcakmakoglu would you know how to troubleshoot this one ?

**Comment by bcakmakoglu** [comment]
My best guess is that the style attribute on your wrapping div is causing an issue

```jsx
<div
		<!-- this is breaking the node resizer -->
        style={{
          transform: `rotate(${rotation}deg)`,
        }}
        className={styles.node}
      >
```

[Here's a sandbox where I re-produce the problem.](https://codesandbox.io/s/optimistic-parm-6rk9rd?file=/ResizableNode.js)
I just added this to the wrapping div

```jsx
    <div style={{ transform: "rotate(1deg)" }}>
```

and the resizer stopped working correctly. As soon as this style attribute is removed, it works fine again 🥲

**Comment by bcakmakoglu** [comment]
You could try adding the rotation to the node itself instead of your wrapping div.

So something like this
```ts
setNodes(nodes => {
	return nodes.map(node => {
		if (node.id === id) {
			return {
				...node,
				style: { ...node.style, transform: `rotate(${rotation}deg)`
			}

			return node
		}
	}
})

**Comment by imvetri** [comment]
@bcakmakoglu  I ended up using ResizeSelectedNode

**Comment by moklick** [comment]
Can we close this @imvetri ?

**Comment by imvetri** [comment]
@moklick thanks for following up. Closing it.
