### ISSUE TITLE
Mouse wheel will not change zoom if cursor is on node

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#299]
Mouse wheel will trigger zoom in both direction if the cursor is placed on the background.
This will not be the case if the cursor is on a node.

From a technical point of view I think this is caused by the way scroll events work.
From the user perspective I'd assume this isn't wanted behavior. So it would be nice if zooming would work anywhere on the graph.

### How to reproduce

1. Open https://react-flow.netlify.app
2. Place cursor on node
3. Scroll with mouse wheel
4. Nothing happens (Expectation: Zoom is changed)

**Comment by moklick** [comment]
I never thought about it but I think it's a good point. We might replace [d3-zoom](https://github.com/d3/d3-zoom) with [react-zoom-pan-patch](https://github.com/prc5/react-zoom-pan-pinch/). With that library it would be relatively easy to achieve this. We could use the `disableOnTarget` option for nodes and would have the behaviour that you describe here.

**Comment by nileshlande12** [comment]
@moklick - This is the most awaiting feature for this library, are you planing to enhance this, or is there any other workaround for zooming.

**Comment by nileshlande12** [comment]
Is there any way to achieve this in customization ?

**Comment by moklick** [comment]
Unfortunately I can't tell you any way to achieve this right now. The nodes and and edges consume the scroll event. We would need a solution that works with [d3-zoom](https://github.com/d3/d3-zoom). That's what we are using for dragging and zooming the pane.

**Comment by chrtze** [comment]
Released in [6.1.0](https://github.com/wbkd/react-flow/releases/tag/6.1.0)
