### ISSUE TITLE
Elevate all edges on edge selected

### ISSUE THREAD

**Issue by ted-marozzi** [wbkd/react-flow#2996]
### Please describe the feature that you want to propose

Basically I have some code doing this
```
  const elevateEdgesOnEdgeSelected = useCallback(() => {
    const edgeSelected = edges.findIndex((edge) => edge.selected === true);
    const anyEdgeSelected = edgeSelected !== -1;

    const edgeContainers = document.querySelectorAll(".react-flow__edges");
    for (const container of edgeContainers) {
      const containsElevate = container.classList.contains("elevate");
      if (!containsElevate && anyEdgeSelected) {
        container.classList.add("elevate");
      } else if (containsElevate && !anyEdgeSelected) {
        container.classList.remove("elevate");
      }
    }
  }, [edges]);
  
        <ReactFlow
        onEdgesChange={(changes) => {
          onEdgesChange(changes);
          elevateEdgesOnEdgeSelected();
        }}
        />
  ```
  
  This is kind gross so I would like to propose an api that supports this. Some api suggestions:
  * A boolean such as elevateEdgesOnSelection
  * A callback that runs only when one edge is selected
  * A boolean that elevates only the selected edge on selection elevateEdgeOnSelection.
 I also implemented the last one in a different iteration but it didn't work because it seems like there is a bug with the react-flow__edges z-indexing. As you can see in the video below when an edge is selected but another edge was previously selected the zIndex is still set to zero and content is hidden. When an edge is selected but no other edge was selected before everything works properly.
 
 The bug fix would be nice but I have decided on elevating everything on selection so not as necessary as a cleaner way to achieve elevating all edges on selection. Thanks.

https://user-images.githubusercontent.com/38032037/231440477-2ab131bd-b3c1-4b2a-99c1-fd0a9e04c1de.mov

**Comment by bcakmakoglu** [comment]
Aren't you just looking for [`elevateEdgesOnSelect`](https://reactflow.dev/docs/api/react-flow-props/#elevateedgesonselect) which already exists?

**Comment by ted-marozzi** [comment]
Unfortunately as per the docs of that api, this elevates edges when a connected node is selected, not the edge itself.
```
Edges get a higher zIndex if this is true and a connected node is selected
```

**Comment by bcakmakoglu** [comment]
Mh... I see.
Naming could become confusing though if there's a prop called `elevateEdgesOnSelect` and `elevateEdgesOnSelection`; It wouldn't be too clear what the difference is.
Changing `elevateEdgesOnSelect` to another prop like `elevateEdgesOnNodeSelect` would be possible but also a breaking change.

Though you can still just elevate edges yourself by using zIndex on edges.
Basically what you did but without all the classList stuff.

```ts
onEdgesChange={(changes) => {
        const selectionChanges = changes.filter(
          (change) => change.type === "select"
        );

        if (selectionChanges.length > 0) {
          instance.setEdges((edges) =>
            edges.map((edge) => {
              edge.zIndex = selectionChanges.some(
                (change) => change.id === edge.id && change.selected
              )
                ? 1000
                : 0;

              return edge;
            })
          );
        }

        onEdgesChange(changes);
      }}
```

[Here's a sandbox demonstrating this.](https://codesandbox.io/s/exciting-thunder-utqdjt?file=/App.js:2478-3019)

**Comment by ted-marozzi** [comment]
Thanks I have solved my issue but perhaps some kind of variable that elevates selected edges would be useful, I manually implemented it here if you want a real world use case: https://www.mermaidflow.app/flowchart

**Comment by moklick** [comment]
We adjusted `elevateEdgesOnSelect` in v11.7.3 - it should now elevate the edge when a connected node or the edge itself is selected.

**Comment by ted-marozzi** [comment]
This is great, I just tried it and deleted some unneeded effects and fixed a bug. Thank you.

**Comment by GitHdu** [comment]
> We adjusted `elevateEdgesOnSelect` in v11.7.3 - it should now elevate the edge when a connected node or the edge itself is selected.

how to elevateEdgesOnhover
