### ISSUE TITLE
add onRightClick/onContextMenu handler

### ISSUE THREAD

**Issue by dekelb** [wbkd/react-flow#301]
I hope I didn't miss it in the docs, but I couldn't find any option to handle right-click (contextmenu) on the nodes/edges.
If not implemented - this is a feature request (I'll be happy to open a PR on it if needed).

**Comment by moklick** [comment]
Hey @dekelb 

there is no right-click handler for now. Feel free to open a PR :)

**Comment by moklick** [comment]
We added `onNodeContextMenu` in v4.0.0. Used in the [horizontal example](https://react-flow.netlify.app/horizontal) (check the logs).

**Comment by sonam-diwate-invimatic** [comment]
is this pushed?

**Comment by Ankitupa007** [comment]
Here is the example of `onNodeContextMenu` in [horizontal examples](https://react-flow.netlify.app/examples/horizontal/)

**Comment by mickbigblue** [comment]
This seems to be gone. Is there any other example for ContextMenu?

**Comment by whtitefall** [comment]
The example seems gone,  if there's a new example for the right-click on edge?
