### ISSUE TITLE
Handle property isConnectableStart={false} breaks interaction width with handle

### ISSUE THREAD

**Issue by semenilchuk** [wbkd/react-flow#3010]
### Describe the Bug

I have a custom node that has only one target handle.
If you use a handle in this custom node that has a height and width of 100% of the size of the node, you expect to be able to connect to that node over its entire area.
This works, but if you add the `isConnectableStart={false}` property, it doesn't work anymore, and now the distance over which you can connect to that node is limited.
Here's an example, if you can go to [this example](https://reactflow.dev/docs/examples/nodes/easy-connect/) , and add `isConnectableStart={false}` property to handle with `type="target"`, there is no possibility to connect nodes anymore

### Steps to Reproduce the Bug or Issue

1. Make custom node with one target handle
2. Make handle style={{width: '100%', height: '100%', opacity: 0.5}}
3. Make other default node and try to connect near the edge of previously created custom node
4. It gets connected
5. Add `isConnectableStart={false}` property to custom node handle
6. Now try to make connection from default node to custom node (also, near the edge).
7. Now they don't connect

### Expected behavior

Expected behavior is:
I add `isConnectableStart={false}` prop to handle, it disables possibility to make connections from it (it's ok now),
and I can connect other nodes to this custom node over its entire area

### Platform

- OS: Linux
- Browser: Every modern browser
- reactflow: 11.7.0

**Comment by moklick** [comment]
This issue is a bit tricky but it will be resolvable in user land with the next minor release. For this you will need to hide the source handle while connecting (for now only possible on the next-release branch).

I will update the issue as soon as the new version is released.

**Comment by moklick** [comment]
The example is fixed: https://reactflow.dev/docs/examples/nodes/easy-connect/ It's now possible to use the easy connect example with connection radius by only displaying the source handle while the user is not connecting nodes.

**Comment by Reflejo** [comment]
There is a variation of this problem, which is when, say you want to receive anywhere in the node but start with a small handler on the right. Then you'd set ```isConnectableStart={false}``` to the big handler. But the problem is that sets `pointer-events: none` which then makes the handler ignored in `getEventPosition(..)` at connecting time.

As a workaround I'm doing `isConnectableStart={isConnecting}` but it's a bit hacky.

Thanks!
