### ISSUE TITLE
Children nodes of collapsed nodes disappearing in the Expand and Collapse pro example.

### ISSUE THREAD

**Issue by dryng** [wbkd/react-flow#3011]
### Describe the Bug

I think there is a bug with setNodes loosing reference to nodes in a flow when the nodes are not rendered. This is can be seen in the Expand and Collapse pro example (https://reactflow.dev/docs/examples/layout/expand-collapse/). 

In the example, if a child node is added, the children nodes of any nodes who are not expanded disappear.

### Your Example Website or App

https://reactflow.dev/docs/examples/layout/expand-collapse/

### Steps to Reproduce the Bug or Issue

1. Go to https://reactflow.dev/docs/examples/layout/expand-collapse/
2. Collapse a node that has children (is expandable)
3. Add a child node to another node
4. The node that had children and was collapsed no longer has children

### Expected behavior

I expect non rendered nodes to remain part of the flows nodes via setNodes and getNodes from useReactFlow. If this was the case, non expanded nodes would not lose their child nodes.

### Platform

- OS: macOS
- Browser: Chrome and Safari
- Version:  11.6.1

**Comment by hayleigh-dot-dev** [comment]
Thank's for opening this @dryng, fix should be live soon!

**Comment by dryng** [comment]
Awesome, thanks!

**Comment by chrtze** [comment]
fixed. thanks @dryng for opening the issue and @hayleigh-dot-dev for solving it :)
