### ISSUE TITLE
Do we have undo/redo action in React Flow.

### ISSUE THREAD

**Issue by sasimarudhuri** [wbkd/react-flow#3013]
### Please describe the feature that you want to propose

Trying to implement undo/redo functionality in React-flow.
Can anyone suggest the reference. 
Expecting the similar functionality i.e available in React Flow Pro
https://pro.reactflow.dev/examples/undo-redo

**Comment by moklick** [comment]
This is a custom built pro example. Maybe this helps to get started https://redux.js.org/usage/implementing-undo-history
