### ISSUE TITLE
Add an onConnectionRadius prop

### ISSUE THREAD

**Issue by Maquinours** [wbkd/react-flow#3016]
### Please describe the feature that you want to propose

A new ReactFlow prop that allow to pass a function that fires when an handle is selected with help of connectionRadius while connecting nodes.

It could be useful, for example, to change the color of the connectionLine depending on if the two handles are connectables.

**Comment by moklick** [comment]
You can already do this https://reactflow.dev/docs/examples/interaction/validation/ we are adding different class names to the handle based on the connection status.

"connecting" - while handle is in connection radius
"valid" - if connection is valid
