### ISSUE TITLE
Selecting another Edge while an Edge is selected does not update the selection status.

### ISSUE THREAD

**Issue by kikucyo** [wbkd/react-flow#3017]
### Describe the Bug

In my application, I am drawing an Edge with a custom edge.
With multiple Nodes and Edges placed in ReactFlow, if I make an Edge selected and then select another Edge, it does not become selected.
If you click elsewhere in the ReactFlow (other than a Node) or update the ViewPort in this state, the later selected Edge will be notified of the selected state.

In other words, there is a one-tempo delay in the notification of selected updates passed to CustomEdge's EdgeProps, which is very troubling.
This problem occurs not only when passing the selected from EdgeProps, but also when using a combination of useStore and useCallback to obtain the selected as follows.
```
  const selected = useStore(
    useCallback(
      (store) => store.edges.find((x) => x.id === id && x.selected),
      [id]
    )
  );
```

This event occurs only when an Edge is in the selected state, and does not occur when a Node is in the selected state or when no other Edge is in the selected state.

Translated with www.DeepL.com/Translator (free version)

### Steps to Reproduce the Bug or Issue

1. Place multiple Nodes and CustomEdges. (For clarity (For clarity, apply a style to CustomEdge, such as changing its color when it becomes selected.)
2. Click on a CustomEdge to make it selected.
3. Click another CustomEdge.

In this case, it is assumed that the custom Edge clicked on later will become selected, but it does not.

### Expected behavior

If another Edge is selected after an Edge is in the selected state, the selected Edge should become selected.

### Platform

- OS: [macOS, ]
- Browser: [Chrome, ]
- Version: [11.7.0]

**Comment by moklick** [comment]
Hey! I can't reproduce this issue. Can you create a codesandbox for this https://new.reactflow.dev/react-js ?

**Comment by moklick** [comment]
This doesn't work because you haven't implemented a `onEdgesChange` handler. If you are working with the `nodes` and `edges` props you also have to define an `onNodesChange` and `onEdgesChange` handler as described here https://reactflow.dev/docs/concepts/core-concepts/#basic-functionality
