### ISSUE TITLE
Edge position doesn't get updated when node updates handle position based on data

### ISSUE THREAD

**Issue by 0xR** [wbkd/react-flow#3025]
### Describe the Bug

My node has some data that determines where the handles are positioned. Sometimes the handles get moved. When that happens reactflow doesn't update the edges. It appears there is some internal state for edges that doesn't update when the nodes update.

### Your Example Website or App

https://codesandbox.io/s/reactflow-edge-state-khieid

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/s/reactflow-edge-state-khieid?file=/Node.js
2. Update the handle position input
3. See that the handle and its edge don't move together

### Expected behavior

The edge should rerender when the data of a node changes. Since data can update the position of the handles.

Alternatively there should be a way to reset the internal edge position state.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/6420016/235438260-14affdc0-6a88-4ab9-bc6a-eac3e7d8431f.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context
In my real application the problem occurs when redrawing the entire flow. Then handles have different positions and some edges are still going to positions of the old flow. What is weird that the `id` of the edge did change. I guess the state is based on the position of the edge in `edges` prop.

But even if the id of the edge stays the same I expect the edge to be redrawn if the node changes since it can move its handles.

**Comment by moklick** [comment]
as @bcakmakoglu pointed out, you need to use `useUpdateNodeInternals` when you change handles programatically https://codesandbox.io/s/reactflow-edge-state-forked-txnr9c?file=/App.js:3258-3296
