### ISSUE TITLE
It cannot detect node's delete change

### ISSUE THREAD

**Issue by Xiaotong713986** [wbkd/react-flow#3040]
### Describe the Bug

![image](https://user-images.githubusercontent.com/23744239/236989806-8c076cb6-9e67-43a2-bcb5-7fa0e0c2634b.png)
![image](https://user-images.githubusercontent.com/23744239/236989862-e1773fc0-e852-43d0-8b5a-3aa718ca7ef6.png)
Here is the console log output
![image](https://user-images.githubusercontent.com/23744239/236989718-debb1666-3afd-42c2-8176-d9687be0ee44.png)

I have some operation in initialTransformationCanvas function, now the onNodeChange can be called when nodes' number is increased, but when i delete some nodes, the onNodeChange can not be called. It's strange.

### Steps to Reproduce the Bug or Issue

1.delete nodes
2.onNodeChange is not called

### Expected behavior

When i delete some nodes in initialTransformationCanvas, onNodeChange should be called.

### Platform

- OS: window
- Browser: Chrome
- Version: 11.3.2

**Comment by moklick** [comment]
how are you deleting the nodes? Can you create a codesandbox for this https://new.reactflow.dev/react-ts ?

**Comment by Xiaotong713986** [comment]
> how are you deleting the nodes? Can you create a codesandbox for this https://new.reactflow.dev/react-ts ?

Hi, I just re-generate the nodes by some json data, the item number of json data is decrease, so it look like some nodes are deleted; I just feel stranger that, when the item number of json data is increase, onNodeChange can be called with dimensions change, why when the item number is decreased and the onNodeChange isn't called.

**Comment by Xiaotong713986** [comment]
I have write in codesandbox:
https://codesandbox.io/s/hungry-swanson-0ihu36?file=/src/Flow.tsx

**Comment by moklick** [comment]
The `onNodeChanges` handler is only used for internal events. When you remove a node via Backspace key for example, the handler gets called. When you alter your nodes on your own, the `onNodeChanges` handler is not used. What do you want to do when a user removes a node? Why do you need to know about it in the `onNodeChanges` handler ?

**Comment by Xiaotong713986** [comment]
> The `onNodeChanges` handler is only used for internal events. When you remove a node via Backspace key for example, the handler gets called. When you alter your nodes on your own, the `onNodeChanges` handler is not used. What do you want to do when a user removes a node? Why do you need to know about it in the `onNodeChanges` handler ?

I want to auto fitView when I adding or decreasing node, so I want to receive adding change or deleting change from onNodeChanges.

**Comment by moklick** [comment]
you could try:

```js 
const nodeCount = useStore(s => s.getNodes().filter(node => node.width && node.height).length);

useEffect(() => {
  fitView();
}, [nodeCount])
```

**Comment by Xiaotong713986** [comment]
> 

Nice~It all work! Thank you!
