### ISSUE TITLE
Edges between a custom group and its children

### ISSUE THREAD

**Issue by FedkoAnastasiia** [wbkd/react-flow#3042]
### Please describe the feature that you want to propose

There are two types of custom nodes in our application: 

- "customGroup" - a node that is a container, a parent element for other nodes formed into a group; 
- "custom" - a custom node that can be a member of a group.

Application connection mode - Loose.

[Sandbox](https://codesandbox.io/s/custom-group-loose-03w746)

The sandbox has one node of type "custom" with label "Child" and one node of type "customGroup" with label "Group", which is the parent of the previous one. 

If you try to connect the child left handle with the parent left handle or the child right handle with the parent right handle, you will see that the edges that appear as a result of the connection go from the parent node to the other side of the child node, and then return to it. 

<img width="396" alt="Screenshot 2023-05-09 at 10 10 41" src="https://github.com/wbkd/react-flow/assets/96294351/f524e5fd-61b8-48fc-afe3-8abbe45c864a">

Is it possible to build edges in such a way that if a child and a parent node are connected and the child node is inside the parent node, then the edge will be built directly to the parent handle without going beyond its borders?

Expected behavior in the screenshot:

<img width="296" alt="Screenshot 2023-05-09 at 10 10 06" src="https://github.com/wbkd/react-flow/assets/96294351/a9138236-fdd5-4806-8f62-0feb53baaf90">

**Comment by moklick** [comment]
I can think about two options how you could solve this:

1. create a custom edge that checks if it's a child - parent connection and then renders the edge differently
2. overwrite the displayed position and switch left and right handles - a handle with position = left gets displayed on the right side and vice versa. Example: https://codesandbox.io/s/custom-group-loose-forked-qdddje?file=/src/components/CustomGroupNode.tsx:1020-1232  

Does it help?

**Comment by FedkoAnastasiia** [comment]
> I can think about two options how you could solve this:
> 
> 1. create a custom edge that checks if it's a child - parent connection and then renders the edge differently
> 2. overwrite the displayed position and switch left and right handles - a handle with position = left gets displayed on the right side and vice versa. Example: https://codesandbox.io/s/custom-group-loose-forked-qdddje?file=/src/components/CustomGroupNode.tsx:1020-1232
> 
> Does it help?

1. Please explain what did you mean by "enders the edge differently"?
2. No, this will not work for me, because in addition to the group => child connections, the application will also have group => another node connections, for example:

<img width="770" alt="Screenshot 2023-05-09 at 15 30 28" src="https://github.com/wbkd/react-flow/assets/96294351/bffed080-160b-44ac-b2d6-c074e550cfa0">
<img width="748" alt="Screenshot 2023-05-09 at 15 32 50" src="https://github.com/wbkd/react-flow/assets/96294351/9885a7fb-d021-4fe3-a1ee-5c9462f4686f">

And with the solution proposed by you, we get the following behavior:
<img width="491" alt="Screenshot 2023-05-09 at 16 01 02" src="https://github.com/wbkd/react-flow/assets/96294351/d17cfd2f-13d1-48f5-9201-c1d710064a73">

**Comment by moklick** [comment]
1. our edge rendering uses the position (`Position.Left` for example) of a handle to decide in which direction the edge should start . You could come up with a different logic that also takes the type of connection (child - child, child - parent) into account 

2. you would need to render to handles above each other here. I am not sure if you use case could be solved with this solution.

**Comment by FedkoAnastasiia** [comment]
> Using a custom edge this should be possible: https://codesandbox.io/s/ecstatic-kilby-bzolq0?file=/src/Flow.tsx
> 
> Though the example I linked _does not_ use a custom connection line (the line you see while dragging a connection), which you probably would want to implement as well to have the right orientations during edge creation :)

It works, thank you!
