### ISSUE TITLE
My app so laggy when use 10k nodes

### ISSUE THREAD

**Issue by tuannguyenhoangit-droid** [wbkd/react-flow#3044]
### Describe the Bug

![IMG_0027](https://github.com/wbkd/react-flow/assets/56645054/f684987c-1bba-431b-ac3a-f1be2442e0f8)
I use react flow to render nodes as a matrix with WIDTH and LENGTH (100x100) => 10k nodes.
To show connect line  between node, I custom node to manage at 2 handle (source and target).  => 20k handles

My react flow laggy now, any suggestion to improve performance?

My code bellow

```
const nodes = createNodes(100, 100);
const nodeTypes  = {point: Point};

<ReactFlow
          minZoom={0.5}
          onEdgeClick={onEdgeClick}
          nodeTypes={nodeTypes}
          nodes={nodes}
          edges={[...edges, ...projectRuns, ...autoRuns]}
          fitView>
          <Background className='background' variant={'dots'} />
        </ReactFlow>
```

```
// Points.js
function Point({ data, isConnectable = true, id }) {

  return (
    <div>
      <Handle type="target" isConnectable={isConnectable} />
      <Handle type="source" isConnectable={isConnectable} />
    </div>
  );
}

export default React.memo(Point);

```

```
// create node
export function createNodes (inWidth, inLength, onChangePointValue = () => {}, pixelUnit = 44) {
    const width = Math.floor((inWidth - 3) / 3);
    const length = Math.floor((inLength - 3) / 3);
    const nodes = [];
    for (let L = 0; L <= width; L+=1) {
        for (let V = 0; V <= length; V+=1) {
           const node = {
                type: 'point',
                draggable: false,
                selectable: false,
                id: ['n',L,V].join('-'),
                position: { x: L * pixelUnit, y: V*pixelUnit },
                style: { width: 1, height: 1, background: 'transparent', border: 'none'},
                data: {L: undefined, V: undefined, position: {L, V}, onChangePointValue},
              }
              if (V === 0) {
                node.data.L = L
              }
              if (L === 0) {
                node.data.V = V;
              }  
            nodes.push(node)
        }
    }
    return nodes;
}
```

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
React Flow is DOM based and therefore not the best choice for displaying thousands of nodes. You probably want to use a canvas based solution like https://github.com/vasturiano/react-force-graph . 

You could try to set [`onlyRenderVisibleElements`](https://reactflow.dev/docs/api/react-flow-props/#onlyrendervisibleelements ), define `const nodeTypes  = {point: Point};` outside of the component, remove the background. But I think that you just have too many nodes for React Flow.

**Comment by tuannguyenhoangit-droid** [comment]
@moklick you save my year

many thanks

**Comment by piesuke** [comment]
@moklick  I faced similar problem. 
When there are around 200 nodes and edges, the memory usage exceeds 1GB, and it becomes quite laggy. Is 200 the limit for ReactFlow?

**Comment by bcakmakoglu** [comment]
There isn't a hard limit like "200 is max" or anything, it depends on various factors like the complexity of your nodes/edges etc.

You can see on the [Stress example](https://reactflow.dev/examples/nodes/stress) that 450 basic nodes are no issue at all.
It might be you're over-using useEffects or something that cause your app to become laggy.

**Comment by akrv7591** [comment]
In stress test example after clicking change position everything becomes laggy

**Comment by nickvanlandschoot** [comment]
https://reactflow.dev/examples/interaction/contextual-zoom

Contextual zoom was recently added and can do a lot to help with performance at scale I have found.
