### ISSUE TITLE
Screen recording breaks pan on scroll

### ISSUE THREAD

**Issue by tarrcimar** [wbkd/react-flow#3048]
### Describe the Bug

The canvas works fine in most cases, although when I start a screen recording multiple functionalities break.

- Pan on scroll does not work, instead it just adjusts the zoom level
- Sometimes no actions get registered (e.g., pan, zoom, click, drag)

This issue persists until I stop the recording and refresh the screen

### Steps to Reproduce the Bug or Issue

1. Start a screen recording
2. The above mentioned issues appear

### Expected behavior

The canvas continues to function as expected even during screen recording

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/78320332/16f998d9-b37c-43bc-babd-ed170571d5ff

### Platform

- OS: macOS
- Browser: Chrome, Edge
- Version: newest versions

**Comment by bcakmakoglu** [comment]
Strange, works fine for me if I test it in a sandbox (both in FF and Chrome)

https://github.com/wbkd/react-flow/assets/78412429/b96ef327-fba4-4f08-a2e1-be1c84945d04

**Comment by moklick** [comment]
If you are doing a screen recording, you should start to record, reload the page and everything should work fine. I will close in favour of #824
