### ISSUE TITLE
`isInteractive` from <Controls /> shows locked button incorrectly

### ISSUE THREAD

**Issue by sushantdhiman** [wbkd/react-flow#3050]
### Describe the Bug

When `<Controls />` is used with `nodesConnectable={false} elementsSelectable={false}`, `isInteractive` incorrectly displays "locked" icon.

![ReactFlowControlStateIssue](https://github.com/wbkd/react-flow/assets/9989487/84c03c73-c3eb-42a1-9c77-43387f727a5b)

This is controlled here https://github.com/wbkd/react-flow/blob/c3681fffcef5502d476d0f27a196b922e87ae666/packages/controls/src/Controls.tsx#L16

I think this logic should use OR operator instead of AND operator.

### Steps to Reproduce the Bug or Issue

Start a empty flow with the following code

```tsx
<ReactFlow nodesConnectable={false} elementsSelectable={false} nodes={[]} edges={[]}>
    <Controls />
</ReactFlow>
```

### Expected behavior

With given options, interactive button should not appear "locked" as `nodesDraggable` is still `true` (by default)

### Platform

- OS: `Linux`
- Browser: `Chromium`
- Version: `111.0.5563.64 (Official Build) Arch Linux (64-bit)`

**Comment by moklick** [comment]
good catch. I think this is broken since v1 👀
