### ISSUE TITLE
NodeResizer does not pass children props to resizeControl

### ISSUE THREAD

**Issue by imvetri** [wbkd/react-flow#3055]
### Describe the Bug

resizeControl takes children props, but node resizer does not pass it to it 

https://github.com/wbkd/react-flow/blob/main/packages/node-resizer/src/ResizeControl.tsx#L33

### Steps to Reproduce the Bug or Issue

na

### Expected behavior

As an user I expect nodeResize to allow me to pass children react component to it so that it can render from within it.

### Screenshots or Videos

NA

### Platform

Na

**Comment by moklick** [comment]
You can pass children and they also get rendered https://github.com/wbkd/react-flow/blob/main/packages/node-resizer/src/ResizeControl.tsx#L236 - we are also doing it in the node resizer example on the website https://reactflow.dev/docs/examples/nodes/node-resizer/

Please only ask a question once (#3053). It's super annoying to have an issue and the same thing as a discussion.

**Comment by imvetri** [comment]
I apologies for opening this as an issue. I found that NodeResizer does not pass children props to ResizeControl. How is the children are passed ?

**Comment by moklick** [comment]
The NodeResizer is a high level helper component that renders resizers on all sides of a node. You can build your own resizer component by using one or multiple ResizeControl components as seen here https://reactflow.dev/docs/examples/nodes/node-resizer/ (CustomResizerNode.js)

**Comment by imvetri** [comment]
@moklick I think it's a right opportunity for the project to introduce an extra more prized plan for AI. Nodes are neurons, I checked that your tool is used to build ai pipelines, in my belief if it is being used for AI it shall be priced more
