### ISSUE TITLE
Getting "It looks like you have created a new nodeTypes or edgeTypes object" warning despite correct use.

### ISSUE THREAD

**Issue by claritise** [wbkd/react-flow#3065]
### Describe the Bug

I am getting the https://reactflow.dev/docs/guides/troubleshooting/#it-looks-like-you-have-created-a-new-nodetypes-or-edgetypes-object-if-this-wasnt-on-purpose-please-define-the-nodetypesedgetypes-outside-of-the-component-or-memoize-them error despite correctly defining my nodes using memoization, or declaring outside of the component. 

```  
const nodeTypes = useMemo(
    () => ({
      pllum: PllumNode,
      interface: InterfaceNode,
      prompt: PromptNode,
      display: DisplayNode,
    }),
    []
);
```

Currently using `next@13.4.2` and `reactflow@11.7.0`

### Steps to Reproduce the Bug or Issue

Make a reactflow in nextjs 13 and declare your nodeTypes using the recommended ways.

### Expected behavior

No warning.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bluesock** [comment]
If you turn off next strict mode does it stop?

**Comment by ted-marozzi** [comment]
@bluesock yes that did remove the warning, would love a real fix for this to be able to keep strict mode on
<img width="888" alt="Screenshot 2023-05-30 at 7 04 58 pm" src="https://github.com/wbkd/react-flow/assets/38032037/628c862e-55b5-4b01-b344-9bd9ba63dcf1">

**Comment by bluesock** [comment]
@ted-marozzi would be nice - presumably the double rendering in strict mode is triggering the warning as everything is running twice and the second time the edges and nodes have already been defined.

**Comment by moklick** [comment]
You can safely ignore the warning. You also get it when you do a change for node or edge types on purpose. It's only visible in dev mode.

**Comment by ted-marozzi** [comment]
Thanks very much for the reply @moklick,
If possible it would be great if we could suppress this warning somehow.
The error takes up so much space that I am worried my app will start throwing real errors before this one that I will miss it. I have turned off strict mode to prevent this but would like to leave strict mode on.
<img width="1840" alt="Screenshot 2023-05-30 at 8 02 56 pm" src="https://github.com/wbkd/react-flow/assets/38032037/88c4b337-d0ea-44bb-8635-76ffa288df41">

**Comment by moklick** [comment]
We have an `onError` prop but that is not being used there :/ (it's a bug). We will fix that, then you can easily overwrite it / filter it.

**Comment by bluesock** [comment]
@moklick thank you - and thanks for React Flow

**Comment by ted-marozzi** [comment]
Agreed! Thank you and thanks for React Flow 🚀

**Comment by moklick** [comment]
It's now possible to suppress by passing a custom `onError` function:

```js
const onError = (msgId, msg) => {
  if (msgId === '002') {
    return;
  }

  console.warn(msg);
}
```

Error message codes: https://github.com/wbkd/react-flow/blob/main/packages/core/src/contants.ts

**Comment by bluesock** [comment]
Thank you - I can get this working for error003  but not error002.

https://codesandbox.io/s/new-water-x2vwj4?file=/src/Flow.tsx:1155-1176

I've triggered the error 003 but  const nodeTypes = {}; which is getting handled by

 const onError = (msgId: string, msg: any) => {
  console.warn("custom handler", msg);
};

but if you move  const nodeTypes = {}; inside BasicFlow to trigger 002 - the custom handler doesn't trigger..

![image](https://github.com/wbkd/react-flow/assets/940438/9a8a7a27-619c-41c6-bb7b-9eb6aa0147e5)

**Comment by bluesock** [comment]
> @bluesock you need to use the latest version 11.8.2

perfect thank you.
