### ISSUE TITLE
Clicking a `nodrag` element with `selectNodesOnDrag: false` selects the node

### ISSUE THREAD

**Issue by solidprinciples** [wbkd/react-flow#3069]
### Describe the Bug

Despite using `nodrag` - when using `selectNodesOnDrag: false` - the node still gets selected when `nodrag` element is clicked on. Is this intentional behavior?

Repro code - based off the custom node example - just using `selected` prop to show issue via text - as well as using `selectNodesOnDrag`: https://codesandbox.io/s/unruffled-rain-jbf5f1

### Your Example Website or App

https://codesandbox.io/s/unruffled-rain-jbf5f1

### Steps to Reproduce the Bug or Issue

1. Have clickable/focusable element wrapped with parent using `nodrag` classname - to prevent selection state.
2. Use `selectNodesOnDrag: false` to prevent selection state when dragging a node.
3. Interact with rendered element wrapped in parent with `nodrag`.
4. Selection state gets triggered, when not dragging, despite `nodrag` being present.

### Expected behavior

`nodrag` should prevent the selection state.

### Platform

- OS: [Windows]
- Browser: [Edge]
- Version: [Version 113.0.1774.42 (Official build) (64-bit)]

**Comment by solidprinciples** [comment]
@moklick - would `noselect` as a class work to block selection on interaction events?

**Comment by moklick** [comment]
Hey @solidprinciples

you can stop the event propagation on click in order to prevent the selection state https://codesandbox.io/s/cocky-bas-qnlpd5?file=/ColorSelectorNode.js:671-705
