### ISSUE TITLE
Removing the copyright text by default

### ISSUE THREAD

**Issue by sovetski** [wbkd/react-flow#3070]
### Please describe the feature that you want to propose

![image](https://github.com/wbkd/react-flow/assets/13520683/05afb857-36a0-42f0-9bfb-33bf666417ce)

Anyone can hide this with a simple CSS code, and by making it the default, many people will end up doing so.

I have respect for your work, and I understand how challenging it can be to maintain a project. However, when you look at this project, it gives the impression that everything is designed to encourage people to "buy" the PRO version, which goes against the essence of "open-source."

Imagine if every open-source project added a link to their website solely because it's "free" or "open source"...

Just this link alone discourages me from using this project. It's not a big loss for you, one user less or more doesn't make a difference, but I simply wanted to tell you that if you're going to do an open-source project, do it all the way.

Anyway, that remains my opinion, and I hope you understand it.

Thanks regardless for this project.

**Comment by moklick** [comment]
I really don't get your point here. React Flow is MIT licensed, so you can do whatever you want with it without paying anything. We didn't want to keep it as a side project but ensure that we are able to maintain and develop it further. How should one finance a project like this in your opinion? I also don't get your point that "everything is designed to encourage people to "buy" the PRO version". Did you check out the website? We have ~100 sites with docs, guides and resources where we do not talk about the pro version at all. And even if we would have a banner on every site that would say "get a sub to support us" that would be totally fine imho. If you want to understand our model and philosophy better, this blog post could help https://reactflow.dev/blog/asking-for-money-for-open-source/
