### ISSUE TITLE
Can we make an element inside a node zoom independent? #3072

### ISSUE THREAD

**Issue by shahbazshoukat** [wbkd/react-flow#3073]
### Please describe the feature that you want to propose

I am developing a text widget within Node where I want to ensure that the Text Editor Toolbar remains independent of the zoom level. Do you have any suggestions on how to achieve this? Thank you in advance.

**Comment by shahbazshoukat** [comment]
I have discovered a workaround for this issue. It can be resolved by utilizing the CSS `transform` property. To begin, you need to obtain the current zoom level by using the following code:

`const zoom = useStore((store) => store.transform[2]);`

Next, apply a style property to the desired element as shown below:

`<div style={{ transform: ``scale(${1 / zoom})`` }}>Some Content</div>`

By using the scale transformation with a value calculated by dividing 1 by the zoom level, you can ensure that the element remains zoom independent.

Use `transform-origin` to set the origin of the target element.

**Comment by Pankaj-birla** [comment]
@shahbazshoukat Thank you for providing this solution! I just wanted to clarify— is this approach of using the CSS transform property with the zoom level an official feature or recommendation within React Flow, or is it more of a custom workaround?

Understanding whether this is natively supported or a community-driven solution would help me decide how to approach similar scenarios.
