### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by RainShas** [wbkd/react-flow#3076]
### Describe the Bug

import React, { useState } from 'react';
import { Handle } from 'reactflow';
import { Select } from 'antd';
import './index.css';
import { shallow } from 'zustand/shallow';
import useStore from '../../store';

const selector = (state) => ({
  nodes: state.nodes,
  edges: state.edges,
  onNodesChange: state.onNodesChange,
  onEdgesChange: state.onEdgesChange,
  onConnect: state.onConnect,
  onAddNodes: state.onAddNodes
});

export default function Formation (props) {
  const { id, isConnectable = true } = props;
  const { nodes, onAddNodes } = useStore(selector, shallow);
  const [Topoffset, setTopoffset] = useState([]);
  const handleChange = (value) => {
    let lengths = nodes.map(item => item.id == id);
    // nodes嵌套对象
    const AddNode = {
      id: `${new Date().getTime()}`,
      data: {
        label: value
      },
      type: 'input',
      position: {
        x: 15,
        y: lengths.length * 50
      },
      draggable: false,
      parentNode: id,
      extent: 'parent',
      targetPosition: 'top'
    }
    // 为reactflow添加嵌套子节点
    onAddNodes([...nodes, AddNode]);
    // 更新该父节点下的所有子节点，从而根据length属性更新dom的marginTop间距
    setTopoffset(lengths);
  }

  return (
    <div className='FormationNode'>
      <h4>xxx</h4>
      <div className='FormationNodeContent' style={{ marginTop: Topoffset.length * 100 }}>
        <Select
          defaultValue="lucy"
          style={{ width: 120 }}
          onChange={handleChange}
          options={[
            { value: 'jack', label: 'Jack' },
            { value: 'lucy', label: 'Lucy' },
            { value: 'Yiminghe', label: 'yiminghe' },
            { value: 'disabled', label: 'Disabled', disabled: true }
          ]}
          className="nodrag"
        />
        <button onClick={() => { handleChange('sss') }}>asd</button>

      </div>
      <Handle type="target" position="top" isConnectable={isConnectable} />
      <Handle type="source" position="bottom" isConnectable={isConnectable} />
    </div>
  )
}

这个文件是一个自定义节点，我希望在选择选项时添加新的嵌套节点，通过zustand新增node，这成功了，然后通过nodes的长度改变div的外边距头部，但是就在这里动态改变margintop时报错了。我已经被折磨一天了。

 

### Steps to Reproduce the Bug or Issue

在一个自定义节点中添加另一个子节点时，改变其父节点的高度/间距时报错

### Expected behavior

因为子节点是脱离文档流的，所以我希望能够通过改变css间距来改变父节点高度

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
could you create a codesandbox for this https://new.reactflow.dev/react-js

**Comment by sunilravilla** [comment]
Any update on this me too facing the same issue 🥲

**Comment by moklick** [comment]
@sunilravilla please provide a codesandbox if you are facing this issue

**Comment by sunilravilla** [comment]
![image](https://github.com/wbkd/react-flow/assets/111700167/cf3817dc-be92-471e-9ca7-67facaed7bed)

Error Screen in mean time i'll create a sandbox or vercel app i'll share it with you.

**Comment by moklick** [comment]
Please make sure that you are using the latest version 11.7.2

**Comment by sunilravilla** [comment]
https://uxc4n7.csb.app/

in sandbox i'm not able to simulate

**Comment by moklick** [comment]
you can update the version here:

![Screenshot 2023-05-24 at 14 29 57](https://github.com/wbkd/react-flow/assets/2857535/00c4911a-2b8b-49d8-889b-7bd07f403189)

If you are not able to simulate it, I would assume that the issue is somewhere else in your code. Are you using the nodes in other components outside the flow?

**Comment by sunilravilla** [comment]
Only in local i'm still facing issue in my deployed i'm not having any issue

**Comment by moklick** [comment]
and you are using 11.7.2 locally?

**Comment by sunilravilla** [comment]
yes

**Comment by joneswe** [comment]
Also have this issue. Im on version 11.7.4. But also had it versions before.

**Comment by moklick** [comment]
@joneswe can you create a codesandbox for this? Most of the times it happens because `nodes` is passed to a `useEffect` or `useCallback` for example.

**Comment by dPacc** [comment]
Here is a temporary fix that I found, if you can add a slight delay to loading the ReactFlow, the error seems to disappear

```
const tBuilderFlow = () => {
  const nodes = [
    {
      id: NodeTypes.Text,
      label: "Text Message",
      type: NodeTypes.Text,
    },
    {
      id: NodeTypes.Image,
      label: "Image Message",
      type: NodeTypes.Image,
    },
  ];

  return (
    <>
      <div
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Header />
        <DndProvider backend={HTML5Backend}>
          <ReactFlowProvider>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "3fr 1fr",
                gridAutoRows: "1fr",
                flex: 1,
              }}
            >
              <FlowZone />
              <Sidebar nodes={nodes} />
            </div>
          </ReactFlowProvider>
        </DndProvider>
      </div>
    </>
  );
};

export default BuilderFlow;
```

I was getting the ResizeObserver loop limit error. I added 2 seconds delay to loading the ReactFlow component and the error disappeared.

```

const BuilderFlow = () => {
  const nodes = [
    {
      id: NodeTypes.Text,
      label: "Text Message",
      type: NodeTypes.Text,
    },
    {
      id: NodeTypes.Image,
      label: "Image Message",
      type: NodeTypes.Image,
    },
  ];

  return (
    <div
      style={{
        height: "100%",
        width: "100%",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Header />
      <DndProvider backend={HTML5Backend}>
        <ReactFlowProvider>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "3fr 1fr",
              gridAutoRows: "1fr",
              flex: 1,
            }}
          >
            <FlowZone />
            <Sidebar nodes={nodes} />
          </div>
        </ReactFlowProvider>
      </DndProvider>
    </div>
  );
};

const DelayedBuilderFlow = () => {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 2000);
  }, []);

  return (
    <div
      style={{
        height: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      {isLoading ? (
        <div className="builder-dual-ring"></div>
      ) : (
        <BuilderFlow />
      )}
    </div>
  );
};

export default DelayedBuilderFlow;
```

Hope this helps

**Comment by brendon-boldt** [comment]
> @joneswe can you create a codesandbox for this? Most of the times it happens because `nodes` is passed to a `useEffect` or `useCallback` for example.

@moklick Would you be able to elaborate on this a bit (or point me to where it is in the docs)?  This makes it sound like it should be avoided.  I am running into this issue in multiple places in my project, although here is a minimal example (triggers the error overlay when you mouse over the node very quickly):

```tsx
const nodeMap = {
  "custom": ({data}: {data: any}) => (
    <div
      style={{
        border: "solid",
        width: data.hovered ? "100px" : undefined,
      }}
      onMouseEnter={() => data.setHovered(true)}
      onMouseLeave={() => data.setHovered(false)}
    >
      test
    </div>
  ),
};

export const Flow = (props: any) => {
  const [hovered, setHovered] = useState(false);
  const nodeTypes = useMemo(() => nodeMap, []);

  const nodes = [
    {
      id: "0",
      position: { x: 100, y: 100},
      data: { hovered, setHovered },
      type: "custom",
    },
  ];

  return <ReactFlow nodes={nodes} nodeTypes={nodeTypes} />;
};
```

**Comment by dPacc** [comment]
This is what worked for me:

```
// Remove the resizeObserver error
  useEffect(() => {
    const errorHandler = (e: any) => {
      if (
        e.message.includes(
          "ResizeObserver loop completed with undelivered notifications" ||
            "ResizeObserver loop limit exceeded"
        )
      ) {
        const resizeObserverErr = document.getElementById(
          "webpack-dev-server-client-overlay"
        );
        if (resizeObserverErr) {
          resizeObserverErr.style.display = "none";
        }
      }
    };
    window.addEventListener("error", errorHandler);

    return () => {
      window.removeEventListener("error", errorHandler);
    };
  }, []);
```

Hope it helps

**Comment by bojalive** [comment]
> This is what worked for me:
> 
> ```
> // Remove the resizeObserver error
> useEffect(() => {
>   const errorHandler = (e: any) => {
>     if (
>       e.message.includes(
>         "ResizeObserver loop completed with undelivered notifications" ||
>           "ResizeObserver loop limit exceeded"
>       )
>     ) {
>       const resizeObserverErr = document.getElementById(
>         "webpack-dev-server-client-overlay"
>       );
>       if (resizeObserverErr) {
>         resizeObserverErr.style.display = "none";
>       }
>     }
>   };
>   window.addEventListener("error", errorHandler);
> 
>   return () => {
>     window.removeEventListener("error", errorHandler);
>   };
> }, []);
> ```
> 
> Hope it helps

Thanks

this finally worked for me

appreciate the help

**Comment by moklick** [comment]
This is not recommended. You should try to find out why this error occurs and then try to fix it. Most of the times it happens because you are passing `nodes` to an `useEffect` dependency array and create a infinite loop.

**Comment by brendon-boldt** [comment]
> This is not recommended. You should try to find out why this error occurs and then try to fix it. Most of the times it happens because you are passing `nodes` to an `useEffect` dependency array and create a infinite loop.

@moklick In my minimal example (https://github.com/wbkd/react-flow/issues/3076#issuecomment-1698018489), I do not use `useEffect` at all, so it seems like this would not be the problem,.

**Comment by 1yasa** [comment]
+1, this indeed a bug

**Comment by andrewvlgafc** [comment]
same problem. work with lib a week.
Have custome node with NodeResizer. If resize using mouse - ResizeObserver loop limit exceeded

**Comment by mengjie-apromore** [comment]
+1

**Comment by johnw3d** [comment]
+1 me too, this is quite a critical flaw

**Comment by kkx64** [comment]
+1

**Comment by Module32** [comment]
+1, i encounter the error while setting a state for some reason:
```
useEffect(() => {
    async function setupNode() {
      const journalId = props.data.journalId;
      const res = await getJournal({
        where: {
          id: journalId,
        },
      });

      if (!res.id) return console.log("failed to fetch", res); // ! todo err handling

      return setJournal(res);
    }

    setupNode();
  }, []);
  ```
  
  removing setJournal() seems to work.

**Comment by solastley** [comment]
+1 this is happening for us too. Adding the listener on the window to handle the error gracefully is a good enough workaround for now, but I would not be surprised if there is some underlying issue with the `ResizeObserver` being used in React Flow.

Notably, I have found that this only happens on Chrome.

There is a related issue for another popular library [here](https://discuss.codemirror.net/t/resizeobserver-loop-completed-with-undelivered-notifications/7300), in case that possibly helps.

**Comment by hemlata-pathak** [comment]
+1

**Comment by catorresc** [comment]
+1 
---
Current versión: 11.11.3

**Comment by TrySpace** [comment]
Still having the same issue with 12.0.4.

Anyone found a workaround of fix?

**Comment by kkx64** [comment]
@TrySpace @catorresc For anyone looking at this, check that you don't have something that is constantly re-rendering the nodes. In the code I was debugging I found a place which had something similar to this:

```ts
const nodes = JSON.parse(JSON.stringify(data));
```

Which would constantly re-render and wreak havoc on the library. Try to find a place where you're re-rendering a lot and fix it, in any case this works fine if you can't identify the problem:

> This is what worked for me:
> 
> ```
> // Remove the resizeObserver error
> useEffect(() => {
>   const errorHandler = (e: any) => {
>     if (
>       e.message.includes(
>         "ResizeObserver loop completed with undelivered notifications" ||
>           "ResizeObserver loop limit exceeded"
>       )
>     ) {
>       const resizeObserverErr = document.getElementById(
>         "webpack-dev-server-client-overlay"
>       );
>       if (resizeObserverErr) {
>         resizeObserverErr.style.display = "none";
>       }
>     }
>   };
>   window.addEventListener("error", errorHandler);
> 
>   return () => {
>     window.removeEventListener("error", errorHandler);
>   };
> }, []);
> ```
> 
> Hope it helps

**Comment by adelriosantiago** [comment]
+1

Is there any solution to this? Still happening in @xyflow/react@12.3.2

**Comment by Azim-Ahmed** [comment]
> +1
> 
> Is there any solution to this? Still happening in @xyflow/react@12.3.2

useEffect(() => {
  const errorHandler = (e: any) => {
    if (
      e.message.includes(
        "ResizeObserver loop completed with undelivered notifications" ||
          "ResizeObserver loop limit exceeded"
      )
    ) {
      const resizeObserverErr = document.getElementById(
        "webpack-dev-server-client-overlay"
      );
      if (resizeObserverErr) {
        resizeObserverErr.style.display = "none";
      }
    }
  };
  window.addEventListener("error", errorHandler);

  return () => {
    window.removeEventListener("error", errorHandler);
  };
}, []);


this should work

**Comment by bencoates08** [comment]
I'm running into a similar issue when trying to auto layout a graph in NextJS. FYI this issue only seems to be surfaced when running in dev mode or when running cypress tests against a production deployment.

I have created a minimal reproduction in the following [CodeSandbox](https://codesandbox.io/p/devbox/modern-wind-r967rc) 

Would appreciate any help I can get on this matter. Struggling to find a solution

**Comment by bencoates08** [comment]
I'm running into a similar issue when trying to auto layout a graph in NextJS. FYI this issue only seems to be surfaced when running in dev mode or when running cypress tests against a production deployment.

I have created a minimal reproduction in the following [CodeSandbox](https://codesandbox.io/p/devbox/modern-wind-r967rc).

Would appreciate any help I can get on this matter. Struggling to find a solution.

**Comment by DavdGao** [comment]
The same issue for me in version 12.3.5

**Comment by gatanaso** [comment]
We started running into this issue on v12.3.5 and v12.3.6. 

We use redux for state management (configured as provided in the example here: https://github.com/xyflow/xyflow/tree/main/examples/react/src/examples/Redux). The above issue occrus when the `onNodesChange` triggers.

A temporary (and not ideal) workaround is to wrap the dispatch in a `setTimeout`:
```
onNodesChange={(changes) => {
  setTimeout(() => dispatch(onNodesChange(changes)));
}}
```
as this seems to prevent the `ResizeObserver` loop.

Hopefully this is helpful to others.

**Comment by BenElferink** [comment]
> We started running into this issue on v12.3.5 and v12.3.6.
> 
> We use redux for state management (configured as provided in the example here: https://github.com/xyflow/xyflow/tree/main/examples/react/src/examples/Redux). The above issue occrus when the `onNodesChange` triggers.
> 
> A temporary (and not ideal) workaround is to wrap the dispatch in a `setTimeout`:
> 
> ```
> onNodesChange={(changes) => {
>   setTimeout(() => dispatch(onNodesChange(changes)));
> }}
> ```
> 
> as this seems to prevent the `ResizeObserver` loop.
> 
> Hopefully this is helpful to others.

I can confirm this fixed it for me 😸
```tsx
<NodeDataFlow
        nodes={nodes}
        edges={edges}
        onNodeClick={handleNodeClick}
        onNodesChange={(changes) => setTimeout(() => onNodesChange(changes))} // Timeout is needed to fix this error: "ResizeObserver loop completed with undelivered notifications."
        onEdgesChange={(changes) => setTimeout(() => onEdgesChange(changes))} // Timeout is needed to fix this error: "ResizeObserver loop completed with undelivered notifications."
      />
```

**Comment by TrySpace** [comment]
@BenElferink does wrapping it in `useCallback` work?
