### ISSUE TITLE
Holding shift and dragging to select nodes doesn't select everything intended

### ISSUE THREAD

**Issue by noah-wardlow** [wbkd/react-flow#3082]
### Describe the Bug

When you hold shift and drag, in order for nodes or edges to be selected you have to increase the size of box around what you want selected significantly. It should be that if the drawn box touches a node or edge at all , it is included in the selection.

We have had customer complaints with this tool that dragging to select is unpredictable and leaves out elements they attempted to select.

### Your Example Website or App

https://github.com/PickNikRobotics/moveit_studio

### Steps to Reproduce the Bug or Issue

- Hold shift and drag to select
- Note that if you don't give a lot of padding to your dragged box, elements in the box are not selected

### Expected behavior

 It should be that if the select  box touches a node or edge at all , it is included in the selection.

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/108752030/f931fd2c-45c3-4202-9040-3a95ddabc1fa

### Platform

- OS: macOS
- Browser: Chrome
- Version: ^11.5.

**Comment by bcakmakoglu** [comment]
[You might want to change the selection mode from full to partial.](https://reactflow.dev/docs/api/types/#selectionmode)

```tsx
<ReactFlow selectionMode={SelectionMode.Partial} ...>
```

**Comment by noah-wardlow** [comment]
Thanks @bcakmakoglu . I didn't see this in the docs

**Comment by moklick** [comment]
maybe a bit hard to find with all those props :D https://reactflow.dev/docs/api/react-flow-props/#selectionmode
