### ISSUE TITLE
Graph update event (nodes + edges)

### ISSUE THREAD

**Issue by noah-wardlow** [wbkd/react-flow#3088]
### Please describe the feature that you want to propose

Currently edge updates and node updates are two separate events.

If I delete an edge and node, I'd like to be able to undo / redo both of those at the same time in the same state

**Comment by moklick** [comment]
How are you handling undo / redo in your app?

**Comment by noah-wardlow** [comment]
@moklick similar to the demo on the site, but running the ``takeSnapshot`` onEdgesChange and on onNodesChange, since there are special cases where we prevent deletion we block in that event
