### ISSUE TITLE
elevateEdgesOnSelect not work when selected Edge

### ISSUE THREAD

**Issue by h1orz** [wbkd/react-flow#3094]
### Describe the Bug

When I selected red edge, i thank it will be change like selected “Node B”.
Red edge do not cover blue edge.
Did i do something wrong?
I also tried setting zIndex in each line. It's work.

### Your Example Website or App

https://codesandbox.io/s/objective-minsky-rltrh4?file=/App.js

### Steps to Reproduce the Bug or Issue

Click red edge.

### Expected behavior

Red edge cover blue edge.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 103

**Comment by chrtze** [comment]
Hi @h1orz, I think this is a misunderstanding of the `elevateEdgesOnSelect` prop due to bad naming. The prop actually controls if edges are elevated when a **connected node** is selected, not the edge itself. In your example, if you select node B, the red edge gets above the blue edge.

If you want to apply a higher zIndex when the edge gets selected, you can do it within the [onNodesChange](https://reactflow.dev/docs/api/react-flow-props/#onedgeschange) callback.

**Comment by moklick** [comment]
That's a good point. I think we should adjust the internal zIndex handling for edges so that we elevate an edge when a connected node or the edge itself gets selected.

**Comment by h1orz** [comment]
> Hi @h1orz, I think this is a misunderstanding of the `elevateEdgesOnSelect` prop due to bad naming. The prop actually controls if edges are elevated when a **connected node** is selected, not the edge itself. In your example, if you select node B, the red edge gets above the blue edge.
> 
> If you want to apply a higher zIndex when the edge gets selected, you can do it within the [onNodesChange](https://reactflow.dev/docs/api/react-flow-props/#onedgeschange) callback.

Thank you for your suggestion.
Actually, I have already done that, but when changing the zIndex of the edge, I also need to handle the hierarchy of the EdgeLabelRenderer content, which is very frustrating for me.

**Comment by h1orz** [comment]
![image](https://github.com/wbkd/react-flow/assets/18734825/9898041f-b5c3-4776-800f-309d2b2581e5)
@moklick The edges in my project have overlays on them, and I want the overlays to be raised along with the edge when the edge's zIndex is increased.
When edge "Node 4" line to "Node 2" be selected, I want "False" be covered, and "Right" are on top of others.

**Comment by h1orz** [comment]
@moklick You are right, I have done it already. Your case has less code, and I have learned new knowledge from it. Thanks a lot!

**Comment by moklick** [comment]
We changed the behaviour in v11.7.3 - it should now elevate the edge when a connected node or the edge itself is connected
