### ISSUE TITLE
selection.interrupt is not a function 

### ISSUE THREAD

**Issue by SourceCipher** [wbkd/react-flow#3105]
### Describe the Bug

We are upgrading the package to the latest v11 and even with v10 we had the same issue every time the component initiates, we are getting this `selection.interrupt is not a function` error. Seems like its coming from the d3-zoom library but the bug is actually within this component.

We got rid of any code and just basically render the very basic sample code with 2 sample nodes and its keeps crashing. If we remove the component, everything works just fine.

### Steps to Reproduce the Bug or Issue

Cant seem to replicate this on codesandbox

### Expected behavior

Should initiate the view with the nodes

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/351018/1bd5574c-ac75-43c5-a7d6-ca9373c9686a)

And this is a sample component we try to render:
![image](https://github.com/wbkd/react-flow/assets/351018/e4726963-0319-4f44-95c6-2afa116475cd)

### Platform

- OS: [win 10]
- Browser: [Brave v1.51.118]

**Comment by moklick** [comment]
are you using different versions of d3-selection? what does `npm list d3-selection` say?

**Comment by SourceCipher** [comment]
Yes, in fact this is whats causing it as I could replicate this crash by adding the library in codesandbox.
https://codesandbox.io/s/angry-ramanujan-04nuj6

**Comment by SourceCipher** [comment]
So I managed to upgrade to the latest version, all works okay. Just had to add overrides to the package.json.

```
"overrides": {
   "d3-selection": "3.0.0"
}
```
