### ISSUE TITLE
Optimization when you have a lot of nodes and edges

### ISSUE THREAD

**Issue by Vladislav747** [wbkd/react-flow#3110]
### Describe the Bug

I have more than 365 edges and more than 500 edges in my react-flow. I use custom nodes. I also use onlyRenderVisibleElements option. 

I memoized my custom nodes this way https://reactflow.dev/docs/guides/migrate-to-v10/ (  const nodeTypes = useMemo(() => ({ specialType: SpecialNode }), []);)

The problem that it starts to work really slow then there are such amount of nodes and edges. 

### Steps to Reproduce the Bug or Issue

1. Create more than 370 **CUSTOM** nodes
2. Create more than 500 edges
3. Add onlyRenderVisibleElements flag
4. Try to move inside pan
5. Try to change zoom

### Expected behavior

- library render only nodes and edges in viewport. 

### Platform

- OS: Linux
- Browser: Chrome

### Additional context

What i already tried
- Optimized all logic of custom node - the only thing custom node is doing now - is gettings data and render it.(no use effect or any calculations)
- I reduce amount of data when i zoom to 0.5 (i rererender no data just color of nodes)

Extra Questions
- Is there difference in optimization for such cases in version 11? Is there reason to migrate on this version to get boost of speed?
- Maybe i didn't tried something to optimize react-flow for big amount of elements - any other memoization?

**Comment by Vladislav747** [comment]
UPD i have calculated that problems with Performance starts when i have 50 nodes at the viewport

**Comment by geohuz** [comment]
@Vladislav747 I suggest you to try react-render-if-visible if you are using react.

**Comment by Vladislav747** [comment]
This issue can be closed. The problem was not in your library. I have mixed custom Hook and Canvas in one component that was a mistake. For optimization you should split them separately
