### ISSUE TITLE
tsc check error TS1005: ',' expected

### ISSUE THREAD

**Issue by janarvaezkng** [wbkd/react-flow#3111]
### Describe the Bug

I added reactflow to my project, and everything works fine. It also builds fine. But when type-checking with `tsc` I get the following issues:

```vim
node_modules/@reactflow/controls/dist/esm/Controls.d.ts:1:15 - error TS1005: ',' expected.
1 import { type PropsWithChildren } from 'react';

node_modules/@reactflow/core/dist/esm/components/Handle/index.d.ts:2:15 - error TS1005: ',' expected.
2 import { type HandleProps } from '../../types';

node_modules/@reactflow/core/dist/esm/index.d.ts:25:47 - error TS1005: ',' expected.
25 export { default as useOnViewportChange, type UseOnViewportChangeOptions } from './hooks/useOnViewportChange';

node_modules/@reactflow/core/dist/esm/index.d.ts:26:48 - error TS1005: ',' expected.
26 export { default as useOnSelectionChange, type UseOnSelectionChangeOptions } from './hooks/useOnSelectionChange';

node_modules/@reactflow/core/dist/esm/index.d.ts:27:47 - error TS1005: ',' expected.
27 export { default as useNodesInitialized, type UseNodesInitializedOptions } from './hooks/useNodesInitialized';
```

They all seem to be coming from `.d.ts` files, and whenever doing `import { type xxx }`. 
Adding `skipLibCheck: true` doesn't fix the issue.

Typescript: 4.4.4
React: 17.0.2
Reactflow: 11.7.2

### Steps to Reproduce the Bug or Issue

Create a project with the dependencies specified.
Create a random flow.
Run `tsc`

### Expected behavior

`tsc` to compile without issues

### Platform

- OS:  macOS
Issue is within terminal, both in local and in a linux jenkins environment

**Comment by kike721** [comment]
I have exact the same problem in my project.

Typescript: 4.4.4
React: 17.0.2
Reactflow: 11.7.2

**Comment by kike721** [comment]
@janarvaezkng I updated my typescript version to 5.1.3 and my project works

**Comment by janarvaezkng** [comment]
> @janarvaezkng I updated my typescript version to 5.1.3 and my project works

Thanks @kike721 ! We ended up upgrading to 4.9.4 and it worked as well.

**Comment by guguji5** [comment]
I face the same issue, but I do not want to upgrade typescript (which leads to more type error )

**Comment by SchmidtWongxn** [comment]
> I face the same issue, but I do not want to upgrade typescript (which leads to more type error )

I have the same problem, how did you solve it in the end?

**Comment by SchmidtWongxn** [comment]
@guguji5 I have the same problem, how did you solve it in the end?
