### ISSUE TITLE
Unexpected Handle ID Behaviour When Creating New Connections

### ISSUE THREAD

**Issue by teith** [wbkd/react-flow#3129]
### Describe the Bug

Dear React Flow team,

I am using your library for a project that includes nodes with multiple handles. I've encountered an issue related to handle connection functionality that I believe could be a bug.

The issue arises when a node with multiple handles has at least one handle already connected. I would expect to be able to draw a new connection line from a specific handle and receive the ID of that handle. However, the handle ID returned seems to be random and doesn't correspond to the handle I'm attempting to connect.

I am currently unable to achieve the expected behavior with the current API and have been unable to find a workaround in the documentation or past issues.

This behavior seems to be inconsistent with the intuitive way the connections should be handled, and it has become a roadblock in my project. I would be very grateful if you could investigate this issue or provide some guidance on how to handle such scenarios.

Best regards,
Ar Te

### Steps to Reproduce the Bug or Issue

Create a node with multiple handles.
Connect one of the handles to another node.
Attempt to create a new connection from the node with an already connected handle.
Draw a connection line to a specific handle on the node.
Check the handle ID that the isValidConnection function returns.

Actual Result:

The isValidConnection function returns a random handle ID, regardless of which handle the connection line was drawn to.

This behavior does not match the expected behavior and leads to incorrect operation of the application.

### Expected behavior

The isValidConnection function returns the ID of the handle to which the connection line was drawn.

### Platform

Version of React Flow: 11.6.0
Browser: Chrome 115.0.5762.4
OS: Mac OS Ventura

**Comment by bcakmakoglu** [comment]
Are you sure it's a *random* handle id? That really makes very little sense as the code doesn't just use a "random" handle id to pass.
What `isValidConnection` receives as it's arg is an object of type `Connection`, which contains the source and target node ids as well as the source and target handle ids (if no id is specified for a handle, it will return `null`).
Did you
1. Make sure all of your handles have a *unique* id?
2. Make sure that, if you add/remove handles dynamically, you call `updateNodeInternals`?

Also a sandbox with a reproduction of this issue would be helpful as just replicating what you described causes 0 issues for me.
You can find a template for a sandbox here: https://new.reactflow.dev/react-ts

**Comment by moklick** [comment]
As @bcakmakoglu pointed out, you need to call updateNodeInternals when you add or remove handles dynamically: https://reactflow.dev/docs/api/hooks/use-update-node-internals/

Please re-open if the issue still exists.
