### ISSUE TITLE
How to handle onHover event on each node?

### ISSUE THREAD

**Issue by Shubham-luv2code** [wbkd/react-flow#313]
I would like to show some tooltip/popup over each node hover. How to deal with it?

**Comment by moklick** [comment]
You could create custom nodes with `onMouseMove` / `onMouseEnter` handlers but we will also add these events for the standard node types in near future.

**Comment by Shubham-luv2code** [comment]
Thanks for your response. I already tried using it on the ReactFlow component directly but it was not working. So I started sending mouse events under data for each node. It works fine. Now I've a minor concern that whenever I'm hovering on an element, the tooltip is showing always on a set position and not on each particular node. Attached image for your reference.
![react-flow-render-img](https://user-images.githubusercontent.com/65558868/85991852-a85b7d80-ba11-11ea-94cb-c5f670d73825.png)

**Comment by moklick** [comment]
Could you share some code? It's hard to figure out what is going on here.

**Comment by moklick** [comment]
Hey @Shubham-luv2code 

we just released v.4.0.0. There we added `onNodeMouseEnter` and `onNodeMouseLeave`callbacks. You need to adjust the position of the tooltip by your self depending on the event `clientX`, `clientY` position, I guess.
