### ISSUE TITLE
Get Intersecting Edges

### ISSUE THREAD

**Issue by FedkoAnastasiia** [wbkd/react-flow#3130]
### Please describe the feature that you want to propose

In my application, I want to split an edge if I drop a node to it. I looked through the documentation and didn't find a way to find the intersecting edge. Is it possible now or is it planned in the future?

<img width="806" alt="Screenshot 2023-06-10 at 17 43 53" src="https://github.com/wbkd/react-flow/assets/96294351/2d50f459-d9a6-4f12-ba62-5553abffd226">

**Comment by FedkoAnastasiia** [comment]
Hey 
Do you have any thoughts on how this could be implemented?

**Comment by moklick** [comment]
We won't add a feature to detect edge intersections, however you can use the existing [`isNodeIntersecting` helper](https://reactflow.dev/docs/api/react-flow-instance/#isnodeintersecting) to check if a node intersects a certain area. In your case, that area would be the space between the two nodes.

**Comment by FedkoAnastasiia** [comment]
Thank you!
