### ISSUE TITLE
Drag events not fired when dragging range selection

### ISSUE THREAD

**Issue by strblr** [wbkd/react-flow#3131]
### Describe the Bug

`onNodeDrag` and `onNodeDragStop` are never called when dragging a range selection (shift + right-click selection). This makes it impossible to use of the strategy described here: https://github.com/wbkd/react-flow/issues/3028#issuecomment-1532639125

These events are correctly fired when selecting the same items one by one with consecutive clicks and then moving them.

### Your Example Website or App

https://codesandbox.io/s/node-drag-bug-2tkw7q?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

1. Go to the example: https://codesandbox.io/s/node-drag-bug-2tkw7q?file=/src/Flow.js
2. Select multiple nodes with a selection range (shift + right-click drag)
3. Move them around
4. `console.log`s from inside `onNodeDrag` and `onNodeDragStop` are not called

### Expected behavior

It's expected to work just like moving a selection that was done with sequential clicks.

### Screenshots or Videos

![CPT2306102240-1078x1037](https://github.com/wbkd/react-flow/assets/30187797/cec012b2-5535-4c02-aea5-87cb8127b38c)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 112.0.5615.121

**Comment by moklick** [comment]
Hey! 

For that you need to use `onSelectionDrag` and `onSelectionDragStop`. I updated your codesandbox here: https://codesandbox.io/s/node-drag-bug-forked-c6n482?file=/src/Flow.js:1042-1120 

(You also need to wrap all handlers with a useCallback that you are passing to React Flow).

**Comment by strblr** [comment]
@moklick Thank you!

**Comment by hriveraMeltStudio** [comment]
OnSelectionDragStop does not work even in your codesanbox example, there is anything I can do to have this event ?

**Comment by bcakmakoglu** [comment]
@hriveraMeltStudio works perfectly fine for me (btw the sandbox uses a rather old version of react flow).
Are you sure you're not misunderstanding the event?


https://github.com/user-attachments/assets/043b17ca-59d6-428c-a51e-74868fcdf404

**Comment by hriveraMeltStudio** [comment]
@bcakmakoglu you're right this is another event, I believe this event could help me to check when a drag selection ends (start selecting nodes and end this selection using shift + right click), but the name of the other event is pretty much the same, so I will find another solution. Thank you.

**Comment by bcakmakoglu** [comment]
Are you maybe looking for these events instead?
<img width="907" alt="image" src="https://github.com/user-attachments/assets/0a0747b7-d719-4ed7-bf72-dd9f949596dd">

**Comment by hriveraMeltStudio** [comment]
Yeah, those I'm currently using, however I need to know which nodes are selected at the exact moment, and those methods just give me the mouse event, so I need to use another one (`onSelectionChange`) to deal with that and hopefully don't have a race condition
