### ISSUE TITLE
The "Easy Connect" example promotes a fragile practice (conditional handle)

### ISSUE THREAD

**Issue by feliksik** [wbkd/react-flow#3135]
### Describe the Bug

The [easy connect example](https://reactflow.dev/docs/examples/nodes/easy-connect/) renders Handles *conditionally*, in line 21 of CustomNode.js. 

```
        {!isConnecting && (
          <Handle
            className="customHandle"
            position={Position.Right}
            type="source"
          />
        )}
```

This works, but is fragile; seemingly it works only when on initialization the handle is rendered/registered. If there would be a condition that does not be true on init, it will break: the Handle will be shown and connection crosshair will be rendered, but it will not work. After long  debugging, I found the documentation on updateNodeInternals. 

I suggest to add a comment above that code as follows: 

```
// warning, if handles are conditionally rendered and not present initially; see https://reactflow.dev/docs/api/hooks/use-update-node-internals/
```

### Steps to Reproduce the Bug or Issue

As an example, see [sandbox](https://codesandbox.io/s/hardcore-swirles-z8ppw8?file=/CustomNode.js:643-813): The target is now drawn conditionally (initially false), and will not work properly as a target anymore

### Expected behavior

I tried the following, but changing isConnectable after render is also problematic.    

```
          <Handle
            className="customHandle"
            position={Position.Right}
            type="source"
            style={{visibility: evaluateCondition() }}
            isConnectable={evaluateCondition()} />
          />
```

### Platform

- OS: macOS
- Browser:  Chrome
- Version: 114.0.5735.106

**Comment by moklick** [comment]
Very good point. I will add a comment to the docs.
