### ISSUE TITLE
React-Flow with Controlled Position/Dimension using NodeResizer Keep Growing

### ISSUE THREAD

**Issue by pdesjardins-jumptrading** [wbkd/react-flow#3142]
### Describe the Bug

When using a controlled state (for nodes) when using the NodeResizer the width and height are not updating accordingly. I see two behaviors: one is that on selection the node grows and the second is in some situation it keeps growing non-stop.

The first behaviors: selection or reposition of the node that grow the widget is reproducible in the sandbox.

The second behavior is yet reproduced outside the main application but append when selecting the user uses the NodeResizer with the same code as the sandbox but is able to select the corner and drag. This make the node increasing in width and height infinitely. 

### Your Example Website or App

https://codesandbox.io/s/reactflowresize-t5m8kg?file=/ResizableNodeSelected.js

### Steps to Reproduce the Bug or Issue

1. Open the Sandbox (https://codesandbox.io/s/reactflowresize-t5m8kg?file=/ResizableNodeSelected.js)
2. Click the node (you can click or drag it)
3. The node grows in size.
4. Looks at the console, you see the `onNodesChange` to trig a `dimensions` type. But, no dimension is triggered.

### Expected behavior

As a user, I expect that the size change only when selecting one corner and dragging.

### Platform

- OS: macOS
- Browser: Chrome 
- Version: 114

### Additional context

If you can provide an example of how to have a controlled node with custom position and dimension that would be great. Otherwise, feel free to use the provided Sandbox.

**Comment by moklick** [comment]
what are you trying to achieve here? There is no need to store the width and height in data. We are measuring the nodes and store the dimensions in node.width/ node.height. Everything works fine when you use those properties https://codesandbox.io/s/reactflowresize-forked-twrr4v?file=/ResizableNodeSelected.js:194-251  .

**Comment by pdesjardins-jumptrading** [comment]
Hi @moklick,

> what are you trying to achieve here? 
I am trying to apply a new width/height using the `NodeResizer`.

>There is no need to store the width and height in data.

That is right! Thanks for letting me know. I tried at first not using the `data` but it wasn't working. That is a good recommendation to avoid duplicating the values since they are already available directly in the props.

>  Everything works fine when you use those properties

Actually, the piece that make the whole example work is this line in your example: `setNodes((nds) => applyNodeChanges(changes, nds));` Using the duplicated width and height in the `data` works (even though not smart).

The `applyNodeChanges` in my example was missing! Interestingly, if you look at my _bad_ repro, the Minimap does has the width and height changing. Thus, the `applyNodeChanges` apply the change for the actual node but the Minimap width and height are affected without it 🤔 This part escape me but it might be just fine.

I appreciate the quick response. Thanks a lot @moklick 

If you want a piece of feedback, it might be great to add in the [documentation page](https://reactflow.dev/docs/examples/nodes/resize-rotate/) on the "Resize and Rotate" a reminder that if the developer is under a controlled environment to use the `applyNodeChanges`. A small detail that people less familiar with the framework might forget.

Have a great day and thanks again.

**Comment by pdesjardins-jumptrading** [comment]
@moklick My reproduction might not be exactly the real case I have which explain also why I wasn't using the `applyNodeChanges`. In my real case scenario, the nodes are stored in a custom storage (e.g. Zustand). The store apply the changes (update function that change the value in the store). The React-Flow component is then fed using the store collection of node.

I have created a more accurate representation of my real case scenario here: https://codesandbox.io/s/reactflowresize-zustand-t5m8kg?file=/App.js

You can notice that it works for the position but not the width/height change.

**Comment by pdesjardins-jumptrading** [comment]
I see in the [guide](https://codesandbox.io/s/reactflowresize-zustand-forked-yk25yw?file=/App.js) a mention of Zustand! I might have skip that part. Let me give it a shot since it uses the applyNodeChanges inside the store. So far, the store is "unaware" of the visual (e.g. React-Flow) libraries.

**Comment by pdesjardins-jumptrading** [comment]
Okay, so I found a fix which might be interesting for other folks in a similar situation.

Instead of using the `onNodeChanges` you can handle the resize in your custom node (where you use the `NodeResize`).

The idea is to update the Zustand store using the callback `onResize`. You can calculate the change of the resize by capturing the `x` and  `y` on the `onResizeStart` and then, debounce the resize to update the store. Something like:

```
<NodeResizer
          isVisible={props.selected}
          onResizeStart={(r) => {
            initialX = r.x;
            initialY = r.y;
          }}
          onResize={debounce((r) => {
             const newWidth =  node.width + r.x - initialX;
             const newHeight =  node.height + r.y - initialY;
             const newNode = {
                  ...node,
                  width: newWidth,
                  height: newHeight,
                };
             updateNode(newNode);
          }, 10)}
/>
```

The bonus is that if you had CSS animation on the node that the debounce make it still happen properly. Overall, that might not be the main way to use the `ResizeNode` but it works well for the scenario that you cannot easily use the `applyNodeChanges`.

**Comment by irfanhathoti** [comment]
Hello all,Iam trying to increase the height of the node using NodeResizer iam enable to resize i can  able to resize width only could you please help me this
