### ISSUE TITLE
Initiate edge "edit mode" after button click

### ISSUE THREAD

**Issue by csenn** [wbkd/react-flow#3143]
### Please describe the feature that you want to propose

First off, love this library. But I've been scouring the docs and issues and can't seem to find a solution to initiating an edge in "edit mode" programmatically.

My use case is I would like to create an edge that is either "true" or "false" based on a button click. So after clicking a specific button in a node-toolbar (that shows up when the node is selected), a new edge in edit mode should be created.

The source handle should be the bottom handle on the box. This should then connect to the cursor which could be dragged to another target handle.

I was able to sort of get it working by creating a temporary handle that overlaps the menu, but it feels a bit awkward to be dragging from the menu to another node. It feels more natural to drag from node to node. Another possibility is to just have standard handle to handle connecting, the issue then is the user has to choose true/false for the edge type after the fact which is a little clunky as well.

<img width="318" alt="Screenshot 2023-06-15 at 7 51 42 AM" src="https://github.com/wbkd/react-flow/assets/5788448/f12efff3-8d4b-4f6d-9966-e1a69ce9e4f0">

**Comment by moklick** [comment]
I like the idea with the temporary handle :D I will let this issue open and discuss with the team if we could offer a better API for use cases like this.

**Comment by csenn** [comment]
hey @moklick, did you happen to have any updates on whether an API like like this could make sense?

**Comment by csenn** [comment]
Just as an update, I was able to get this working using the CustomConnectionLine. I put a <Handle> in the pop-up itself, and as soon as I start to drag the cursor I calculate the start position of the CustomConnectionLine being one of handles on the box itself. So the UX is probably an 8or 9 out of 10 now.

**Comment by moklick** [comment]
Ok, I will close this, since it's solved. Maybe we can use it as an example for a custom connection line.
