### ISSUE TITLE
Straight edges are not connecting to the right position

### ISSUE THREAD

**Issue by chance-sematic** [wbkd/react-flow#3144]
### Describe the Bug

Please see examples on this page:

https://reactflow.dev/docs/examples/edges/edge-types/

<img width="1397" alt="image" src="https://github.com/wbkd/react-flow/assets/133257643/834efcca-dc4a-40db-8942-b73fb0ae89dc">

The straight edge is not connected to the center of the handles.

### Your Example Website or App

https://reactflow.dev/docs/examples/edges/edge-types/

### Steps to Reproduce the Bug or Issue

Please go to the official example to see a repro.

### Expected behavior

The straight edges should be connected to the center of the handles.

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest or whatever the official example is using.

**Comment by moklick** [comment]
I never thought about this. All edges behave in the same way but you have a point here that it looks a bit weird for a straight edge. I will look into it.

**Comment by moklick** [comment]
We decided not to change the default behaviour. The round handle is just an example. If you use a rectangle for example this might work better than using the center. That said, if you need a different behaviour, you need to work with a custom edge. Here is a simplified example https://codesandbox.io/s/eager-fermat-8686ng?file=/CustomEdge.tsx:190-312
