### ISSUE TITLE
There is an error in the connections between CustomNodes.

### ISSUE THREAD

**Issue by NINTING** [wbkd/react-flow#3146]
## description
I have created two CustomNodes and customized the Handle positions. However, when I connect them, I noticed that the endpoints of the connection line do not align with the rendered positions, but rather with the initial Handle positions.

## there is my code:
The ParamHandle controls the position and style of the Handle, __with the topOffset parameter specifically affecting the Handle's position__. However, it seems that when performing endpoint connections, the Edge is not reading the actual computed position, but rather a different position.
```
 function ParamHandle({name, id, type ,isSource}: any) {
    /** @type {React.RefObject<HTMLDivElement>} */
    const [flowInstance] = useAtom(flowInstanceAtom)
    const topOffsetAtom = useMemo(() => atom(0), [])
    const ref: React.MutableRefObject<HTMLDivElement | undefined> = useRef<HTMLDivElement>();
    const updateNodeInternals = useUpdateNodeInternals();
    const [topOffset, setTopOffset] = useAtom(topOffsetAtom);
    useEffect(() => {
        if (ref.current && ref.current.offsetTop && ref.current.clientHeight) {
            setTopOffset(ref.current.offsetTop + ref.current.clientHeight / 2);
            updateNodeInternals(id);
        }
    }, [id,ref, ref.current, ref.current?.offsetTop, updateNodeInternals])

    useEffect(() => {
        updateNodeInternals(id);
    }, [topOffset, updateNodeInternals])

    return (
            // @ts-ignore
       <div ref={ref}  className="w-full flex flex-wrap justify-between items-center bg-gray-50 dark:bg-gray-800 dark:text-white mt-1 px-5 py-1">
         <div className={classNames("text-sm truncate w-full " , isSource? "text-end" : "text-start")}>{name}</div>
            <Handle type={isSource ? "source" : "target"} id={id} position ={ isSource ? Position.Right : Position.Left}
                    className={`-mr-0.5  w-3 h-3  border-2 dark:bg-gray-800`} style = {{top:topOffset}}
                isValidConnection = {(connection)=>valideConnect(connection,flowInstance)}
            />
       </div>
    );
};
```

ActorNode use ParamHandle
```
function ActorNode({id}:any){

    const updateNodeInternals = useUpdateNodeInternals();


    return (
        <div className="  shadow-md rounded-md bg-white border-2 border-stone-500 py-1" style={{width: 300, height: "auto"}}>
            <div> Actor </div>
             {/*<ParamHandle name={PromptComponentEnum[PromptComponentEnum.prompt]} id={ParamTypeToNodeType(PromptComponentEnum.prompt)} isSource = {false} />*/}
            <ParamHandle name = "A" id={ParamTypeToNodeType(PromptComponentEnum.prompt)} isSource = {false}/>
        </div>
    );
}
```

Please help me, I've spent an entire day trying to figure out why this is happening. I couldn't find the answer I was looking for on the official website or Google. I'm a beginner in React and React Flow.

### Steps to Reproduce the Bug or Issue

1. When I connect two nodes using the drag-and-drop method, an error occurs. However, when I use the click method to connect them, it works correctly.

2. When I drag the Edge, it snaps to a position,but the snapped position is not aligned with the rendered Handle position.  __Instead, it snaps to the initial position, which is the incorrect position.__

### Expected behavior

I would like to see the two Handles correctly connected together.

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/31238314/b2f08b95-c8b8-4b9f-b62c-aabc467c2b34)

### Platform

Chrome

**Comment by moklick** [comment]
I could imagine that you don't need to calculate anything in order to position the handles. I am also pretty sure that that's the root of the issue here. The new position isn't rendered yet and updateNodeInternals is called to early. Why are you not overwriting the default handle location with a fixed value? Check this example: https://reactflow.dev/docs/examples/overview/ (overview.css).

**Comment by moklick** [comment]
Please re-open with a codesandbox (https://new.reactflow.dev/react-ts) or repo.
