### ISSUE TITLE
Updatable Edges with Floating Edges corrupt the position of Anchor

### ISSUE THREAD

**Issue by maramichal** [wbkd/react-flow#3158]
### Describe the Bug

I ran into this problem while creating FloatableEdges whith UpdatableEdge. The element (EdgeAnchor) that is used to move with the edge is drawn in a place that is internally defined, and does not take into account the curve that is created using CustomEdge. So the user is unable to find the element to drag.

### Your Example Website or App

https://codesandbox.io/s/eloquent-ardinghelli-qgkv3h

### Steps to Reproduce the Bug or Issue

1. Try to drag the EdgeAnchor
2. You find that EdgeAnchor isn´t on the line path.

EdgeAnchor is rendering next to the Node´s Handle, depending on data-handlepos. (class="react-flow__edgeupdater")
But the real path of Edge can be different.

### Expected behavior

As proggrammer creating Custom Edge. I would like to have some possibilities to adjust the position of these EdgeAnchors from my Custom Edge, because there I know the real source & target positions.

### Screenshots or Videos

![PrintScreen](https://github.com/wbkd/react-flow/assets/43316825/03fdda27-49e4-43cc-be3a-7a1e0c910eb1)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 11.7.3]

**Comment by maramichal** [comment]
It is possible to adjust their position with your own not REACT code. But it's not a completely clean solution.
`  if(lineElement.current){ //Some element with react reference in custom node
    const source = lineElement.current.parentElement?.querySelector(".react-flow__edgeupdater-source");
    const target = lineElement.current.parentElement?.querySelector(".react-flow__edgeupdater-target");

   // sy, sy, tx, ty - Positions of start and end of path.
    if(source){
      source.setAttribute("cx",String(sx));
      source.setAttribute("cy",String(sy));
    }
    if(target){
      target.setAttribute("cx",String(tx));
      target.setAttribute("cy",String(ty));
    }
  }`

**Comment by moklick** [comment]
good catch. We are drawing the anchors before you are drawing your custom edge so currently there is no clean way to do this right. Not sure if we will change it. Thanks for sharing your workaround!
