### ISSUE TITLE
Edge not appearing on rerender, if it is attaching to a source handle

### ISSUE THREAD

**Issue by AlanJereb** [wbkd/react-flow#3171]
### Describe the Bug

When updating data with new nodes and edges and running the changes through the `setNodes` and `setEdges`, only the nodes get rendered, but not the edges that use the **sourceHandle** property.

The edge renders correctly if I reload the page (reinitialize react-flow).

### Your Example Website or App

/

### Steps to Reproduce the Bug or Issue

Relavant code
```
useEffect(() => {
    if (props.data?.components.length) {
      setNodes([..updatedNodes]);
      setEdges([...modified.edges]);
  }, [props.data]);
```

Before the change state:
![slika](https://github.com/wbkd/react-flow/assets/24469472/96b1afd5-9abe-4b10-8168-272ad7478fa5)

Before the change render:
![slika](https://github.com/wbkd/react-flow/assets/24469472/63061a05-1024-436b-aef5-e7c6423371de)

After the change state:
![slika](https://github.com/wbkd/react-flow/assets/24469472/c5f27c7e-14aa-4b6a-8eab-9b5277060489)

After the change render (wrong - edge is missing):
![slika](https://github.com/wbkd/react-flow/assets/24469472/679549a6-48f4-4244-b807-204089b53e3a)

### Expected behavior

Edges should render the same as nodes do when using setEdges.

### Platform

- OS: Windows 10
- Browser: Firefox 114.0.1 (64-bit)
- Version: ^11.7.0

**Comment by moklick** [comment]
Hey @AlanJereb 

I am not able to reproduce this: https://codesandbox.io/s/upbeat-kowalevski-hsnjnl?file=/src/Flow.tsx:1182-1264 

Do you have a repo or codesandbox, I could check out?

**Comment by MarkChenYutian** [comment]
I am also experiencing a similar issue. I am generating (and updating) a flow diagram programmatically using ReactFlow, however, even with valid source Handle ID, I'm still receiving the warning

```
Couldn't create edge for source handle id: s-val-ptr-16; edge id: heap-41@s-val-ptr-16>heap-33. Help: https://reactflow.dev/error#800 
...
```

<img width="920" alt="image" src="https://github.com/wbkd/react-flow/assets/47029019/4521679e-f630-4996-82d3-03d05434905c">

The screenshot above shows that the EdgeIDs (in form of `sourceNodeID@sourceHandleID>targetNodeID`). The component tree from ReactDev debugger shows that the handle do exist and is in the correct node.

<img width="783" alt="image" src="https://github.com/wbkd/react-flow/assets/47029019/8d5dd307-a6ee-4b57-8a7e-5f41ac88a680">

The updates to Nodes and Edges is applied using following `useEffect` hooks.

<img width="922" alt="image" src="https://github.com/wbkd/react-flow/assets/47029019/6b379df2-fb18-4141-b26b-6280dd19bf28">

**Comment by MarkChenYutian** [comment]
Unfortunately, similar to the discussion above, when I tried to extract this specific component and build a minimum reproducible case, the problem disappears magically.

Full code is available in https://github.com/MarkChenYutian/C0VM-ts in `/src/components/debug_console/graphical_debugger.tsx`

**Comment by moklick** [comment]
You are using an old version of React Flow. Please use the new package `reactflow` with v11. When that's done, I can check this issue again.

**Comment by moklick** [comment]
Please re-open this issue if you can provide a repo or codesandbox that reproduces it. 

@MarkChenYutian I will provide feedback under MarkChenYutian/C0VM-ts#41
