### ISSUE TITLE
Save and Restore example not working

### ISSUE THREAD

**Issue by Altomand** [wbkd/react-flow#3175]
### Describe the Bug

```js
import React, { useState, useCallback } from 'react';
import ReactFlow, {
  ReactFlowProvider,
  useNodesState,
  useEdgesState,
  addEdge,
  useReactFlow,
  Panel,
} from 'reactflow';
import 'reactflow/dist/style.css';

const flowKey = 'example-flow';

const getNodeId = () => `randomnode_${+new Date()}`;

const initialNodes = [
  { id: '1', data: { label: 'Node 1' }, position: { x: 100, y: 100 } },
  { id: '2', data: { label: 'Node 2' }, position: { x: 100, y: 200 } },
];

const initialEdges = [{ id: 'e1-2', source: '1', target: '2' }];

const SaveRestore = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const [rfInstance, setRfInstance] = useState(null);
  const { setViewport } = useReactFlow();

  const onConnect = useCallback((params) => setEdges((eds) => addEdge(params, eds)), [setEdges]);
  const onSave = useCallback(() => {
    if (rfInstance) {
      const flow = rfInstance.toObject();
      localStorage.setItem(flowKey, JSON.stringify(flow));
    }
  }, [rfInstance]);

  const onRestore = useCallback(() => {
    const restoreFlow = async () => {
      const flow = JSON.parse(localStorage.getItem(flowKey));

      if (flow) {
        const { x = 0, y = 0, zoom = 1 } = flow.viewport;
        setNodes(flow.nodes || []);
        setEdges(flow.edges || []);
        setViewport({ x, y, zoom });
      }
    };

    restoreFlow();
  }, [setNodes, setViewport]);

  const onAdd = useCallback(() => {
    const newNode = {
      id: getNodeId(),
      data: { label: 'Added node' },
      position: {
        x: Math.random() * window.innerWidth - 100,
        y: Math.random() * window.innerHeight,
      },
    };
    setNodes((nds) => nds.concat(newNode));
  }, [setNodes]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
      onInit={setRfInstance}
    >
      <Panel position="top-right">
        <button onClick={onSave}>save</button>
        <button onClick={onRestore}>restore</button>
        <button onClick={onAdd}>add node</button>
      </Panel>
    </ReactFlow>
  );
};

export default () => (
  <ReactFlowProvider>
    <SaveRestore />
  </ReactFlowProvider>
);
```
`Compiled with warnings.

[eslint] 
src/App.js
  Line 50:6:  React Hook useCallback has a missing dependency: 'setEdges'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 82:1:  Assign arrow function to a variable before exporting as module default                                         import/no-anonymous-default-export

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/App.js
  Line 50:6:  React Hook useCallback has a missing dependency: 'setEdges'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 82:1:  Assign arrow function to a variable before exporting as module default                                         import/no-anonymous-default-export

webpack compiled with 1 warning`

### Steps to Reproduce the Bug or Issue

1. open new react project
2. paste code in https://reactflow.dev/docs/examples/interaction/save-and-restore/ in app.js
3. get error and blank screen

### Expected behavior

Should look like https://reactflow.dev/docs/examples/interaction/save-and-restore/

### Platform

- OS: [ macOS ]
- Browser: [ Chrome ]
- Version: {
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@mui/material": "^5.13.6",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-ace": "^10.1.0",
    "react-dom": "^18.2.0",
    "react-flow-renderer": "^10.3.17",
    "react-scripts": "5.0.1",
    "reactflow": "^11.7.4",
    "web-vitals": "^2.1.4"
  },

**Comment by moklick** [comment]
what does "open new react project" mean? Do you get some console output in the dev tools?

**Comment by moklick** [comment]
please re-open with a codesandbox or repo.
