### ISSUE TITLE
Handle `position` prop is marked as required in types, but it optional in documentation

### ISSUE THREAD

**Issue by Tenkir** [wbkd/react-flow#3177]
### Describe the Bug

The `position` property of the `Handle` component throws a type error if not included in the component properties, but is marked as optional in the documentation. I assume this is what the `?` after the property indicates at least.

Documentation: https://reactflow.dev/docs/api/nodes/handle/#position-3

### Steps to Reproduce the Bug or Issue

1. Add a handle with the following properties: `<Handle type="target" position={Position.Top} />`
1. Observe typescript error is thrown: `Property 'position' is missing in type '{ type: "target"; }' but required in type 'HandleProps'.ts(2741)`

### Expected behavior

`position` should be an optional property, or the documentation should be updated to indicate it is required.

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/3649828/a817a623-8ce8-4722-958f-d553f7ab23b2)

### Platform

- OS: Linux
- Browser: N/A
- Version: 11.7.2

**Comment by moklick** [comment]
I updated the docs. Thanks!
