### ISSUE TITLE
Arrows cannot be rotated automatically

### ISSUE THREAD

**Issue by tjxtjxtjx** [wbkd/react-flow#3181]
### Describe the Bug

For example.
https://reactflow.dev/docs/examples/edges/custom-edge/
![1](https://github.com/wbkd/react-flow/assets/135824302/9fd9089a-9209-4aa5-a6cc-1a0381028dfd)

↑  I just want this effect, arrows can automatically rotate with the angle of the edge. But after deleting an edge, the arrow does not rotate automatically.

![2](https://github.com/wbkd/react-flow/assets/135824302/4942f3d6-a354-405c-bbdb-2f065f868f4d)

The arrow is fixed there and will not rotate automatically.
Even if I change the orient attribute, the arrow cannot automatically rotate.https://reactflow.dev/docs/examples/edges/markers/

![3](https://github.com/wbkd/react-flow/assets/135824302/be364cfb-caf2-44e5-8d1b-85501949e6f0)

### Steps to Reproduce the Bug or Issue

1、Add egde's arrow
2、Set the orient property to "auto"
3、Arrows cannot be rotated automatically

### Expected behavior

Arrows can automatically rotate with the angle of the edge

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey @tjxtjxtjx It's the default SVG marker-end attribute behaviour https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-end It depends how you draw the edge. We are not going to change how we draw the default edges.
