### ISSUE TITLE
Globally disabling Resizer

### ISSUE THREAD

**Issue by bodinsamuel** [wbkd/react-flow#3188]
### Please describe the feature that you want to propose

Hey team,

Since `<NodeResizer>` is part of the core installation it would be great to have an option to disable resizing at the `<ReactFlow/>` component level.
With a props `resizable={boolean}` or `nodesResizable={boolean}` or something similar to what you did to deletable, draggable, etc...

It would help reduce the boilerplate needed when implementing a custom Node with `<NodeResizer>`.
Currently I have a ReadOnly mode that prevents all action but user can still accidentally resize nodes. 

The current alternative is to have a shared state somewhere with a hook that you use on every custom nodes, which is not ideal. And can create desync if badly done.

Thanks,

**Comment by moklick** [comment]
I agree that it would be nice, but it would also imply that nodes are resizable when `nodesResizable={true}`. Unfortunately I don't have a solution for this. Currently the only way is to work with a global store / shared state.
