### ISSUE TITLE
is there any way to disable and enable  lock button of react flow controls plugin using react state variable

### ISSUE THREAD

**Issue by kumarnishu** [wbkd/react-flow#3191]
### Please describe the feature that you want to propose

Is there any way to disable and enable  lock button of react flow controls plugin based on react state variable.
[](url)
![Screenshot from 2023-07-02 19-50-31](https://github.com/wbkd/react-flow/assets/45355788/6aa4887f-4cd9-4581-86bb-31cc2d6e968e)

**Comment by kumarnishu** [comment]
i want to disable interaction on the flows for normal users.

**Comment by rzvxa** [comment]
@kumarnishu 
But i think you can find what you are looking for over [here](https://github.com/wbkd/react-flow/blob/993a778b80cc1e80a47983ed75407b579313a73c/packages/controls/src/Controls.tsx#L65).
I think you can achieve this by making nodes non-dragable, non-connectable and non-selectable like what is happening in Controls component.
```
  const onToggleInteractivity = () => {
    store.setState({
      nodesDraggable: !isInteractive,
      nodesConnectable: !isInteractive,
      elementsSelectable: !isInteractive,
    });

    onInteractiveChange?.(!isInteractive);
  };
```
You can also do this by ignoring all of the changes that are firing via `onNodesChange` and `onEdgesChange` props.

I hope this helps, I'm not a project maintainer nor developer so feel free to wait for an official answer. Have a nice day!

**Comment by kumarnishu** [comment]
i understand

> @kumarnishu I think you can find what you are looking for over [here](https://github.com/wbkd/react-flow/blob/993a778b80cc1e80a47983ed75407b579313a73c/packages/controls/src/Controls.tsx#L65). You can achieve this by making nodes non-dragable, non-connectable and non-selectable like what is happening in Controls component.
> 
> ```
>   const onToggleInteractivity = () => {
>     store.setState({
>       nodesDraggable: !isInteractive,
>       nodesConnectable: !isInteractive,
>       elementsSelectable: !isInteractive,
>     });
> 
>     onInteractiveChange?.(!isInteractive);
>   };
> ```
> 
> You can also do this by ignoring all of the changes that are firing via `onNodesChange` and `onEdgesChange` props.
> 
> I hope this helps, I'm not a project maintainer nor developer so feel free to wait for an official answer. Have a nice day!

i got it , think i should remove lock btn from default controls panel, and implement custom lock button for my self.

**Comment by kumarnishu** [comment]
> i understand
> 
> > @kumarnishu I think you can find what you are looking for over [here](https://github.com/wbkd/react-flow/blob/993a778b80cc1e80a47983ed75407b579313a73c/packages/controls/src/Controls.tsx#L65). You can achieve this by making nodes non-dragable, non-connectable and non-selectable like what is happening in Controls component.
> > ```
> >   const onToggleInteractivity = () => {
> >     store.setState({
> >       nodesDraggable: !isInteractive,
> >       nodesConnectable: !isInteractive,
> >       elementsSelectable: !isInteractive,
> >     });
> > 
> >     onInteractiveChange?.(!isInteractive);
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also do this by ignoring all of the changes that are firing via `onNodesChange` and `onEdgesChange` props.
> > I hope this helps, I'm not a project maintainer nor developer so feel free to wait for an official answer. Have a nice day!
> 
> i got it , think i should remove lock btn from default controls panel, and implement custom lock button for my self. thanks sir.

this is the best way ,i want to hide the lock icon for the normal users, and it is working.
 <Controls showInteractive={interaction} position="top-left" />

**Comment by rzvxa** [comment]
You can also change state of the control button itself, you can change isInteractive property in the store(it will also trigger the toggle). But writing your own controls is the best approach.
