### ISSUE TITLE
Custom edges are not included when downloading image

### ISSUE THREAD

**Issue by leolorenzoluis** [wbkd/react-flow#3199]
### Please describe the feature that you want to propose

Referring to the sample for TurboFlow. When downloading image the custom edges are not shown. Is it currently a limitation or we have to rely to built in edges?

**Comment by moklick** [comment]
Which library are you using to download the image?

**Comment by leolorenzoluis** [comment]
html-image I tried combining the sample download image + turbo build and it didn't export it with its custom svg

**Comment by leolorenzoluis** [comment]
@moklick Absolutely! https://codesandbox.io/s/cocky-keldysh-gnd3kz?file=/App.tsx

See the attached downloaded image. This is again just a combination from the demo download image + turboflow.
![reactflow](https://github.com/wbkd/react-flow/assets/15150044/bf51337a-6986-4e10-bf80-730a0c782315)

**Comment by moklick** [comment]
This is a special case. The edges are using linear gradients and the library can't handle this. There are two options to solve this:

1. don't use a linear gradient for the edges but a regular fill
2. apply a regular fill before you create the image and then switch back to the linear gradient

**Comment by beautyfree** [comment]
@moklick I found that this works if the svg with the gradient is inside the `viewport` from which we are taking the picture.

I want to know if it is possible to place React component (with svg) inside an element with a `viewport `class?

**Comment by beautyfree** [comment]
my current workaround looks like:

```js
  const handleInit = useCallback(() => {
    const viewport = document.querySelector(".react-flow__viewport")!;
    const defs = document.querySelector("#defs")!;

    viewport.append(defs);
  }, []);
 ```
 
 ```jsx
     <ReactFlow
      onInit={handleInit}
    >
      <svg id="defs">
        <defs>
          <linearGradient id="edge-gradient">
            <stop offset="0%" stopColor="#ae53ba" />
            <stop offset="100%" stopColor="#2a8af6" />
          </linearGradient>

          <marker
            id="edge-circle"
            viewBox="-5 -5 10 10"
            refX="0"
            refY="0"
            markerUnits="strokeWidth"
            markerWidth="10"
            markerHeight="10"
            orient="auto"
          >
            <circle stroke="#2a8af6" strokeOpacity="0.75" r="2" cx="0" cy="0" />
          </marker>
        </defs>
      </svg>
    </ReactFlow>
    ```

**Comment by sklinov** [comment]
@moklick I'm experiencing the same issue - I have properly drawn nodes, but no edges, or funky-looking arrows (no edge "body"). 
I have custom nodes and a combination of standard and custom edges (plain color strokes, no gradients).
Pretty much, I've copied the [example from docs](https://reactflow.dev/examples/misc/download-image) to try things out.

This is what I see on the screen and expect to get

<img width="1071" height="639" alt="Image" src="https://github.com/user-attachments/assets/8236ac7c-f292-4af6-9fd7-cf02cafef619" />

This is what I get:
<img width="1000" height="808" alt="Image" src="https://github.com/user-attachments/assets/a7235ba1-0783-4bf9-86c1-4e11c4f86e6f" />

**Comment by cygnuson** [comment]
It's late but I found that pinning the version of html-to-image to **html-to-image@1.11.11** fixes the issue with custom edges not showing. This version also is called out as working in the example page here https://reactflow.dev/examples/misc/download-image

cc @sklinov @leolorenzoluis
