### ISSUE TITLE
NodeResizeControl breaks when used with "zustand": "4.3.9"

### ISSUE THREAD

**Issue by navanshu** [wbkd/react-flow#3200]
### Describe the Bug

There is an issue with NodeResizeControl maybe because of the way zustand is imported

### Steps to Reproduce the Bug or Issue

Install "zustand": "4.3.9" with latest of any version of reactflow, if you use NodeResizeControl within a custom node it says zustand was not provided

### Expected behavior

It should remain compatible

### Platform

- OS: Windows
- Browser: Microsoft Edge
- Version: 114.0.1823.67 (Official build) (64-bit)

**Comment by moklick** [comment]
I can't reproduce this. Could you create a codesandbox or a repo for this issue?

Here I am using a `NodeResizeControl` within a custom node. The installed zustand version is 4.3.9 https://codesandbox.io/s/bold-mcclintock-2dpmvf?file=/CustomResizerNode.js:223-300
