### ISSUE TITLE
Support for how to show horizontal expand/collapse. 

### ISSUE THREAD

**Issue by haritbrightness** [wbkd/react-flow#3203]
### Describe the Bug

I bought the pro version and used the example: https://pro.reactflow.dev/examples/expand-collapse 

I want to show this tree in horizontal flow. I tried with { sourcePosition: 'right',
        targetPosition: 'left',} on the node, and   I added handle position accordingly right and left but it's not working as expected.
        (See attached file
![Screenshot from 2023-07-07 18-02-24](https://github.com/wbkd/react-flow/assets/20592195/eb6a372d-77ae-4a96-9d12-a29fa327ad37)
)
Would anyone help me on this?
Thanks

### Your Example Website or App

http://localhost:8081/intelligence

### Steps to Reproduce the Bug or Issue

Steps I described above:

`export const nodes = [
    {
        id: 'A',
        sourcePosition: 'right',
        position: {x: 0, y: 0},
        data: {expanded: true,label:'MLK kili',class:['simple-root-node', 'text-center']},
    },
    {
        id: 'B',
        position: {x: 0, y: 0},
        sourcePosition: 'right',
        targetPosition: 'left',
        data: {expanded: false,label:'Netherlands',class:['child-node', 'text-left']},
    },
];

`

### Expected behavior

As a user I expect the behaviours like attached Screenshot.
![localhost_8081_intelligence](https://github.com/wbkd/react-flow/assets/20592195/222890d8-4bfe-4201-b9fb-1effe0243db0)

### Platform

- OS: [ Linux]
- Browser: [Chrome]
- Version: [Version 114.0.5735.198 (Official Build) (64-bit)]

### Additional context

Check above issue

**Comment by haritbrightness** [comment]
I find something to set horizontal, that I don't know proper or not? After I set positions dynamically I got horizontal layout but it does not support separation between nodes.

Code:

`function useExpandCollapse(
    nodes, edges,
    {layoutNodes = true, treeWidth = 220, treeHeight = 100}) {

    return useMemo(() => {
        const hierarchy = stratify()
            .id((d) => d.id)
            .parentId((d) => edges.find((e) => e.target === d.id)?.source)(nodes);

        hierarchy.descendants().forEach((d) => {
            d.data.data.expandable = !!d.children?.length;
            d.children = d.data.data.expanded ? d.children : undefined;
        });

        const layout = tree()
            .nodeSize([treeWidth, treeHeight])
            .separation(() => 1);

        const root = layoutNodes ? layout(hierarchy) : hierarchy;

        let mXstep = 50;
        let mYstep = 50;
        return {
            nodes: root.descendants().map((d) => ({
                ...d.data,
                // This bit is super important! We *mutated* the object in the `forEach`
                // above so the reference is the same. React needs to see a new reference
                // to trigger a re-render of the node.
                data: {...d.data.data},
                // targetPosition : 'left',
                // sourcePosition : 'right',
                type: 'custom',
                // position: isHierarchyPointNode(d) ? {x: d.x, y: d.y} : d.data.position,
                position: {  // dynamic position added OR using from initial nodes data.
                    x:d.data.position.x,
                    y:d.data.position.y + mYstep,
                },
            })),
            edges: edges.filter((edge) => root.find((h) => h.id === edge.source) && root.find((h) => h.id === edge.target)),
        };
    }, [nodes, edges, layoutNodes, treeWidth, treeHeight]);`

**Comment by moklick** [comment]
If you want to display a horizontal flow, you need to swap x and y. 

```js 
position: isHierarchyPointNode(d) ? {x: d.y, y: d.x} : d.data.position
```

We will update the pro example soon, in order to show a vertical and horizontal direction.
