### ISSUE TITLE
onNodeMouseDown (and family) support?

### ISSUE THREAD

**Issue by sgrove** [wbkd/react-flow#3214]
### Please describe the feature that you want to propose

I've been really struggling to capture an option-click on a node (this was certainly possible in an older version in 2021, but I suspect the way I was using it has since been deprecated). It'd be great to be able to capture the onMouseEnter/Leave/Up/Down events for a node!

**Comment by moklick** [comment]
hey @sgrove 

do you want to add the event listeners to the whole node?

**Comment by moklick** [comment]
Does `onMouseDownCapture` work for you in this case? If not, please re-open!
