### ISSUE TITLE
Propagate event handlers to edge components

### ISSUE THREAD

**Issue by Goldziher** [wbkd/react-flow#3224]
### Please describe the feature that you want to propose

Hi, so what I am trying to do is attach an event listener to an edge - basically just a wrapper around the builtin edges. The problem is that standard svg props, such as event handlers, or any other custom prop for that matter, is not propagated to the edges. 

So instead of being able to do something like this:

```typescript
export function CustomEdge(props: EdgeProps<any>) {
	const onClick = () => console.log("clicked")

	return (
		<BezierEdge id={edgeId} onClick={onClick}  {...props} />
	);
}
```

I am forced to do some very hacky stuff:

```typescript
export function CustomEdge(props: EdgeProps<any>) {
	const onClick = () => console.log("clicked")

	useEffect(() => {
		// in order to set an event listener on the edge, we have to do some hacky stuff here.
		const element = document.getElementById(`${edgeId}-marker`)!;
		const parent = element?.parentElement!;
		const interactionContainer = Array.from(parent.childNodes).filter(
			(node) => {
				console.log('here');
				return (node as HTMLElement).classList.contains(
					'react-flow__edge-interaction',
				);
			},
		)[0];
		interactionContainer.addEventListener('contextmenu', onClick);
	});

	return (
		<>
			<EdgeComponent id={edgeId} pathOptions={{ abc: 1 }} {...props} />
			<span id={`${edgeId}-marker`} />
		</>
	);
}
```

Note - i have to do this weird hack in `useEffect` and add a marker span, because the edgeID is not actually propagated to the path in the DOM. Thus i cannot get the path by ID, and I am not happy using the `data-testid` which is in place there. 

It would be great if you allow propagating props to the path component - or to the interaction path component.

**Comment by moklick** [comment]
You don't need those hacks, but you can wrap the edge component with a `<g>` element an apply the event handlers there https://codesandbox.io/s/epic-ellis-n9l7dd?file=/CustomEdge.tsx:371-427

**Comment by Goldziher** [comment]
wow thanks! TIL
