### ISSUE TITLE
How to Lock on/off In react flow using props

### ISSUE THREAD

**Issue by shahbaazaliSatschel** [wbkd/react-flow#3230]
### Describe the Bug

Lock on/off

### Steps to Reproduce the Bug or Issue

1-open react flow
2- lock button on the left side bottom

### Expected behavior

I want to lock on 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Lock on/off

**Comment by moklick** [comment]
The flow is locked when `nodesDraggable`, `nodesConnectable` or `elementsSelectable` is `false` https://github.com/wbkd/react-flow/blob/main/packages/controls/src/Controls.tsx#L16.

If you want to start with a closed lock you should set all those three props to `false`:

```js 

<ReactFlow
   nodesDraggable={false}
nodesDraggable={false}
