### ISSUE TITLE
Edges broken when scaling flow renderer

### ISSUE THREAD

**Issue by Elringus** [wbkd/react-flow#3231]
### Describe the Bug

When applying `transform: scale()` animation to the flow renderer element the edges are positioned with offset:

![img](https://github.com/wbkd/react-flow/assets/2056864/0e71ce29-16c9-4078-baae-8b72b890264c)

Related discussion: https://github.com/wbkd/react-flow/discussions/3229

### Your Example Website or App

https://codesandbox.io/s/reactflow-scale-repro-gxspht?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

Open the repro sandbox and notice the edges are rendered with offset due to:

```js
  useEffect(() => {
    document
      .querySelector(".react-flow__renderer")
      .animate([{ transform: "scale(10)" }, { transform: "scale(1)" }], {
        duration: 666,
        easing: "ease"
      });
  }, []);
```

### Expected behavior

Edges should be rendered correctly, independent of the animation.

### Platform

- OS: any
- Browser: any
- Version: latest

**Comment by Elringus** [comment]
I would be happy to help with the fix, but not really sure where to dig. I've initially guessed that edges are rendered in an async manner after `setEdges` is invoked, but after examining the sources it doesn't seem the case.

**Comment by Elringus** [comment]
Thank you for the insight! It doesn't completely solve the issue though, as the edges are still positioned incorrectly while the animation is running. Is there a way to force the positioning before the animation starts (given the scale is 1 at that moment)? I've tried:

```js
 useEffect(() => {
    const nodeIds = store
    .getState()
    .getNodes()
    .map((node) => node.id);
    updateNodeInternals(nodeIds);

    document
      .querySelector(".react-flow__renderer")
      .animate([{ transform: "scale(10)" }, { transform: "scale(1)" }], {
        duration: 1000,
        easing: "ease"
      });
  }, [updateNodeInternals, store]);
``` 

— but it didn't work.

**Comment by moklick** [comment]
What are you trying to achieve here? I think it would be better to work with the viewport instead of scaling the whole renderer. Is this about a zoom effect?

**Comment by Elringus** [comment]
I need to animate the graph so that "camera" dives in to a node when it's expanded (transitioning to the graph stored inside the node) and dives out of the same node when returning back. I'm using 2 graph instances to achieve that. Here is a demo: 

https://github.com/wbkd/react-flow/assets/2056864/c8a523dc-4c7a-4dc6-aaa8-f4c765810183

Basically, I just need a way to force react-flow calculate the positions / initialize at the moment when no transformations are applied and everything is valid, then run the animations.

**Comment by moklick** [comment]
That's a super nice effect 👌 Did you try to animate the viewport instead of using transform scale?

**Comment by Elringus** [comment]
That's what I've initially tried with `ViewportHelperFunctions.zoomIn/Out`, but for this effect to work correctly I actually need two animations running with unique timing functions and durations: one for translate and another for zoom/scale. Since css won't allow that on a single element, I have to apply them on 2 parent elements of the viewport (pane and renderer).

**Comment by moklick** [comment]
did you try to use `setCenter` for this [https://codesandbox.io/s/gifted-glade-wkc993?file=/App.js:1069-1182 (button is on the top right)](https://codesandbox.io/s/gifted-glade-wkc993?file=/App.js:973-1210) ?

**Comment by Elringus** [comment]
Yep, I've played with all the available funcs, but it didn't work just right for me. Eg, `setCenter` starts zooming with a delay, while I need translation and scale happen in parallel, but with different easings and durations.

**Comment by Elringus** [comment]
Just to clarify, I'm really just want react-flow to position the edges/handles in a predictable/consistent manner. Currently, it seems the evaluation happens in an undefined order. For example, if we add a delay before running the animation, the edges are placed correctly: 

```js
  useEffect(() => {
    setTimeout(
      () =>
        document
          .querySelector(".react-flow__renderer")
          .animate([{ transform: "scale(10)" }, { transform: "scale(1)" }], {
            duration: 666,
            easing: "ease"
          }),
      100
    );
  }, []);
```

Either changing it to work in sync or adding a hook for when edges/handles calculation is complete (so that we can then run our custom transformations) will resolve the issue here.

**Comment by moklick** [comment]
The `useNodesInitialized` hook returns `true` when all measurements are done. Could you try to use that one?

```js
const nodesInitialized = useNodesInitialized();

 useEffect(() => {
    if (nodesInitialized) {
      document
        .querySelector(".react-flow__renderer")
        .animate([{ transform: "scale(10)" }, { transform: "scale(1)" }], {
          duration: 666,
          easing: "ease"
        });       
    }
  }, [nodesInitialized]);
```

**Comment by Elringus** [comment]
That was it! `useNodesInitialized` was exactly the hook I was looking for :) Had to fight with react shenanigans a bit (handling the state when graph props are changed, but `nodeInitialized` is in stale true state), but now it's working perfectly w/o any hacks. That you very much for the help!

https://github.com/wbkd/react-flow/assets/2056864/9f11e0ea-9e87-40c2-87d3-6f8e702e7a81

**Comment by moklick** [comment]
I am glad we could solve it :) Looks super dope 🔥🔥🔥

**Comment by maikelvanmaurik** [comment]
This indeed looks super dope. I'm trying to do something similar. @elringus can you share how you made this work? Or do you know @moklick how this effect can be achieved? Looking at the code example it looks like the `react-flow__renderer` is transformed, but that will change the whole flow?
