### ISSUE TITLE
Custom handle positioning does not work

### ISSUE THREAD

**Issue by Goldziher** [wbkd/react-flow#3232]
### Describe the Bug

I followed the custom shapes (pro) guide and now I have a bunch of SVG based shapes. The handles position though are problematic - for any shape that does not fill the entire container, the default handler positions are weird. 

See for example this:

<img width="639" alt="Screenshot_2023-07-14_at_08 42 35" src="https://github.com/wbkd/react-flow/assets/30733348/90f789df-2bb8-4bc4-ac73-87caee4822ce">

And this:

<img width="712" alt="Screenshot_2023-07-14_at_08 45 12" src="https://github.com/wbkd/react-flow/assets/30733348/e0334bf1-c0e6-42cb-b4ad-47096bed6716">

Obviously, the handlers are positioned with an aboslute positioning on the extenal div container. This makes sense. So I moved the handler positioning, but the result is a bug - as you can see in the two following videos:

https://github.com/wbkd/react-flow/assets/30733348/42f3e904-f2d1-43cd-a3c1-25530716a327

https://github.com/wbkd/react-flow/assets/30733348/eb869cb2-f691-4a33-904b-2a264358e8f0

It seems that the connection line is calculated to emerge also from an absolute position, which is the position that the handler is *assumed* to take, and not from the handler's concrete bounding box as it's written to the DOM. 

Please instruct me if there is a way for me to achieve what I am trying to achieve in the current implementation. Otherwise, I'd like to file this as a bug report basically. 

### Steps to Reproduce the Bug or Issue

1. Reposition a handler using the `style` attribute and place it at an absolute position.
2. Reproduce the behavior in the videos. 

### Expected behavior

I would like to be able to reposition a handler on the screen and have the connecting line begin and connect to it correctly. 

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest

**Comment by moklick** [comment]
Hey @Goldziher 

this is the expected behaviour. The node wrapper is always a div. When you place a SVG shape inside of it, this won't change. In this case you would need to position the handles manually by using left/right/top/bottom or translate. https://codesandbox.io/s/morning-haze-lg664l?file=/src/CustomNode.tsx:88-174
