### ISSUE TITLE
Multi select does not respect the boundaries of the canvas

### ISSUE THREAD

**Issue by chrtze** [wbkd/react-flow#3239]
### Discussed in https://github.com/wbkd/react-flow/discussions/3233

<div type='discussions-op-text'>

<sup>Originally posted by **varghesethomase** July 17, 2023</sup>
I would like to understand if there is a way to limit dragging of the nodes towards the canvas boundary when a multi select is performed. 
Currently, when two widgets are selected, and is moved to the canvas boundary, it forces the farthest element from the canvas boundary to move towards it till they overlap. What is more desirable should be that when multi select is performed, the selected boundaries of the "multi selected" area is respected when moved towards the canvas boundary and retains intact how it is when the canvas boundary is touched by the selected element closest to it. I am attaching a video of how it behaves currently. I would appreciate your support on how to achieve it. 

https://github.com/wbkd/react-flow/assets/5429756/214b3e98-69b3-457a-9dfa-36fe6fc9b6c6

</div>

**Comment by bcrudolp** [comment]
I'm curious about the reference to "boundaries of the canvas". By this, are you referring to nodeExtent / translateExtent? In working with `reactflow`, I never found a clearly documented option to actually have hard "boundaries" or a "size" for the canvas. There's a finite _viewport_ for it, but the `ReactFlow` itself seems always to be an infinitely panning surface (of course subject to `translateExtent` and `nodeExtent`) like Google Maps or similar.

**Comment by moklick** [comment]
fixed in v11.8.0

@bcrudolp this refers to `nodeExtent`.
