### ISSUE TITLE
Is it possible to disable the warning for "It looks like you have created a new nodeTypes or edgeTypes object"?

### ISSUE THREAD

**Issue by JackWH** [wbkd/react-flow#3243]
### Describe the Bug

> It looks like you have created a new nodeTypes or edgeTypes object. If this wasn't on purpose please define the nodeTypes/edgeTypes outside of the component or memoize them.

As expected, I'm getting this warning when dynamically changing the edge types after React Flow has initialised.

I've [read the docs](https://reactflow.dev/docs/guides/troubleshooting/#it-looks-like-you-have-created-a-new-nodetypes-or-edgetypes-object-if-this-wasnt-on-purpose-please-define-the-nodetypesedgetypes-outside-of-the-component-or-memoize-them), and as suggested, am memoizing the edge types with `useMemo`.

When a dependency in the `useMemo` hook changes, as I would expect, React Flow re-renders the graph with the updated edge types. But I still get warnings logged to the console every time.

Is it possible to prevent/disable these warnings? Thanks!

### Steps to Reproduce the Bug or Issue

Memoize edge types in `useMemo`, change a dependency, check the console.

### Expected behavior

Ideally there would be some way to tell React Flow an edge type change was "intentional".

### Platform

- OS: macOS
- Browser: Chrome
- Version: Latest

**Comment by moklick** [comment]
I will look into it.

**Comment by moklick** [comment]
It's now possible to suppress by passing a custom `onError` function:

```js
const onError = (msgId, msg) => {
  if (msgId === '002') {
    return;
  }

  console.warn(msg);
}
```

Error message codes: https://github.com/wbkd/react-flow/blob/main/packages/core/src/contants.ts

**Comment by Ankoge** [comment]
With an updated version and this change implemented, it still prints this warning. onError function does not get called when this warning is printed.
version: "reactflow": "11.8.3",
Do you have any suggestion what can go wrong in this case?

**Comment by mockbirds** [comment]
I also had the same problem with Next.js. I looked at the react-flow code base and found some error handling code in
`react-flow/packages/core/src/container/GraphView/utils.ts`

For me, for now, this quick fix works in my component that renders ReactFlow:

```ts
const store = useStoreApi();
if (process.env.NODE_ENV === "development") {
  store.getState().onError = (code, message) => {
    if (code === "002") {
      return;
    }
    console.warn(message);
  };
}
```

**Comment by njarraud** [comment]
Same issue here on Nextjs 14.1

**Comment by acronymor** [comment]
I meet the same error

```json
    "next": "14.1.1",
    "react": "^18",
    "react-dom": "^18",
    "reactflow": "^11.11.0",
```

```typescript
import 'reactflow/dist/style.css';

import React from 'react';
import ReactFlow, {Controls, MiniMap, useEdgesState, useNodesState} from 'reactflow';

import CanvasNode from '@/app/unit/canvas/node';
import CanvasEdge from "@/app/unit/canvas/edge";

const nodeTypes = {node: CanvasNode}
const edgeTypes = {edge: CanvasEdge}

export default function Flow() {

    const [nodes, setNodes, onNodesChange] = useNodesState([]);
    const [edges, setEdges, onEdgesChange] = useEdgesState([]);

    return (
        <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            nodeTypes={nodeTypes}
            edgeTypes={edgeTypes}
            snapToGrid={true}
            fitView
            attributionPosition="bottom-left"
        >
            <MiniMap style={{backgroundColor: '#363636'}}/>
            <Controls/>
        </ReactFlow>
    );
};
```

![image](https://github.com/xyflow/xyflow/assets/24858758/5448e7fc-7656-4a43-974d-87b3a23375dc)

**Comment by kasince2k** [comment]
Same issue here.

**Comment by sclinard-3s** [comment]
Still getting this issue even with the custom error handler, and the custom error handler doesn't seem to actually work as I'm not able to dump any logs out of it. Using Next 14.2.3 and reactflow 11.11.3

`
'use client';
import styles from './FormulaContainer.module.css';
import ReactFlow, { Background, Controls, useStoreApi } from 'reactflow';

export function FormulaContainer() {

  const onError = (msgId, msg) => {
    if (msgId === '002') {
      return;
    }

    console.warn(msg);
  }

  return (
    <div className={`cell ${styles.FormulaContainer}`}>
      <div className={styles.FormulaContainer__inner}>
        <h2>Formula</h2>
        <div className={styles.FormulaContainer__flow} style={{ height: '100%' }}>
          <ReactFlow onError={onError}>
            <Background />
            <Controls />
          </ReactFlow>
        </div>
      </div>
    </div>
  );
}
`
<img width="956" alt="image" src="https://github.com/xyflow/xyflow/assets/131201946/508bdc12-3519-4fad-9e49-88d34815c6fb">

**Comment by michal-boruczkowski** [comment]
Same here, I'm still getting this warning

**Comment by nichism** [comment]
Using custom onError method worked for me. A bit annoying though.

**Comment by ckpearson** [comment]
You could also likely get around this by supplying a key to the component that you regenerate whenever you need to modify your node / edge type objects and force react to remount the flow.

**Comment by dooaansarig** [comment]
I am getting the same error in next.js 15.3 version, I have tried everthing possible

**Comment by techcoder2007** [comment]
Same here, I'm still getting this warning, 
```powershell
    "reactflow": "^11.11.4",
    "next": "14.2.3",

``` 

<img width="1240" height="391" alt="Image" src="https://github.com/user-attachments/assets/f7e23959-44d4-42d3-99ed-2bc03df3aea3" />

**Comment by moklick** [comment]
@techcoder2007 please migrate to the new package @xyflow/react https://reactflow.dev/learn/troubleshooting/migrate-to-v12
