### ISSUE TITLE
sourceHandle and targetHandle types for DefaultEdge

### ISSUE THREAD

**Issue by gpkc** [wbkd/react-flow#3246]
### Describe the Bug

According to [the docs](https://reactflow.dev/docs/api/edges/edge-options/#sourcehandle-1), the type for these properties is just `string | undefined`. However, [from the code](https://github.com/wbkd/react-flow/blob/main/packages/core/src/types/edges.ts#L22), they appear as `string | undefined | null`.

Also, from testing, it doesn't seem that they actually become `undefined`, but instead are just `null` when there isn't multiple handles.

This is also consistent with the type for [Connection](https://github.com/wbkd/react-flow/blob/main/packages/core/src/types/general.ts#L60), and from a short code investigation seems to be the general case in the code that those handles are never 'undefined`, but I am not fully certain

### Steps to Reproduce the Bug or Issue

Check docs and code as per description

### Expected behavior

It seems that the type should just be `string | null` from testing, but it's unclear

### Platform

Not relevant

**Comment by moklick** [comment]
Hey. Thanks for the report and your PR. If we would require a `sourceHandle` and `targetHandle`, the user would always need to define those attributes. I would leave it like it is and just update the docs.

**Comment by gpkc** [comment]
@moklick Why not just have it be `string | undefined` then? Is there a semantic difference between the handle being `undefined` and `null`?

**Comment by moklick** [comment]
I would like this to be different, but I don't want to introduce a breaking change here. Some apps might use `sourceHandle: null`, because we offered this API (unfortunately).
