### ISSUE TITLE
Stick selected node positions on scroll

### ISSUE THREAD

**Issue by Basantrajshakti** [wbkd/react-flow#3249]
### Please describe the feature that you want to propose

I am creating a gantt-chart using react-flow. I need to implement a feature such that if I scroll the pane, selected nodes should not move where as non-selected nodes should move as per the scroll. Is it possible now? If not, please add it.

**Comment by moklick** [comment]
This is a very specific use case that we won't add to the library. If you need it, you can implement it by using the current transform or `useOnViewportChange` for example. You could check if there is one or multiple selected nodes. If so, you would need to adjust their positions based on the viewport change.

**Comment by Basantrajshakti** [comment]
Thanks, I did it with CSS positioning.
