### ISSUE TITLE
Add Scrollbar

### ISSUE THREAD

**Issue by Hardiklodhari12** [wbkd/react-flow#3252]
**Problem**
When users are viewing large flows, it can be difficult to pan the viewport to see all of the content.

**Solution**
A scrollbar would allow users to easily scroll through the content of a flow, regardless of its size. The scrollbar could be vertical or horizontal, depending on the flow's orientation.

**Benefits**

A scrollbar would provide a number of benefits for users, including:

1. Increased usability: Users would be able to easily scroll through large flows, regardless of their device.
2. Improved accessibility: Users with disabilities who may have difficulty panning the viewport would be able to use the scrollbar to navigate through the content.
3. Enhanced design: A scrollbar can add a touch of polish to the overall design of a flow.

**Comment by moklick** [comment]
Hey @Hardiklodhari12 

we will not add a scrollbar for React Flow. We are working with an infinite pane and the scrollbar feature doesn't fit very well into that concept. If you need one, you can calculate the current height of the flow, set the actual height to that number and put it in a container with a fixed height. I created a simplified example to explain the solution: https://codesandbox.io/s/pedantic-bhabha-jwsg48?file=/src/styles.css
