### ISSUE TITLE
Ensures buttons have discernible text.

### ISSUE THREAD

**Issue by msftedad** [wbkd/react-flow#3258]
### Describe the Bug

Test Environment:
OS: Windows 11 Version 22H2(OS build 22621.1992)
Browser:  Edge Browser version 115.0.1901.183

Repro Steps:
1. Open the URL https://v9.reactflow.dev/examples/.
2. Navigate to the buttons present in the page using keyboard tab key.
3. Open F12 developer tools and verify whether buttons are provided with discernible text or not.

Actual Result:
Buttons are not provided with discernible text.

Expected Result:
Buttons should be provided with discernible text.
Attachment: <img width="889" alt="Ensures buttons have discernible text" src="https://github.com/wbkd/react-flow/assets/93735775/f7df27ce-846b-4751-9158-5988d1b9797a">

### Steps to Reproduce the Bug or Issue

Repro Steps:
1. Open the URL https://v9.reactflow.dev/examples/.
2. Navigate to the buttons present in the page using keyboard tab key.
3. Open F12 developer tools and verify whether buttons are provided with discernible text or not.

### Expected behavior

Buttons should be provided with discernible text.

### Screenshots or Videos

<img width="889" alt="Ensures buttons have discernible text" src="https://github.com/wbkd/react-flow/assets/93735775/b9e6467e-3ff6-47eb-a4e8-c99ce771ade4">

### Platform

Test Environment:
OS: Windows 11 Version 22H2(OS build 22621.1992)
Browser:  Edge Browser version 115.0.1901.183

**Comment by moklick** [comment]
You are referring to a very old version of React Flow. In the current version v11, all buttons have title attributes.
