### ISSUE TITLE
useOnSelectionChange with mobx

### ISSUE THREAD

**Issue by ChenBonBon** [wbkd/react-flow#3269]
### Describe the Bug

I use mobx as my state management tool, and I find that when I use 'useOnSelectionChange' hook, the onChange function will not console the latest value.

```typescript
import { observer } from "mobx-react-lite";
import { useRef } from "react";
import ReactFlow, { MiniMap, useOnSelectionChange } from "reactflow";
import "reactflow/dist/style.css";

const nodes = [
  {
    id: "adcabdbb-fc8a-468b-a6e0-a9cb6250a4ab",
    position: {
      x: 273,
      y: 277
    },
    data: {
      title: "Board1",
      label: "Board1",
      width: 196,
      height: 204,
      attributes: []
    },
    width: 196,
    height: 204,
    selected: false
  }
];

const Diagram = observer(() => {
  const reactFlowWrapper = useRef(null);

  useOnSelectionChange({
    onChange: ({ nodes, edges }) => {
      console.log(nodes, edges);
    }
  });

  return (
    <div style={{ width: 800, height: 600 }} ref={reactFlowWrapper}>
      <ReactFlow nodes={nodes} edges={[]}>
        <MiniMap position="bottom-left" />
      </ReactFlow>
    </div>
  );
});

export default Diagram;
```

### Your Example Website or App

https://codesandbox.io/s/reactflow-dnd-mobx-forked-86r49w?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1. Open the console
2. Click on the node 'Board1' 
3. Click on the node 'Board1' again

### Expected behavior

The console will display the latest info of clicked node.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 115.0.5790.114

**Comment by ChenBonBon** [comment]
I found your reply from [2651](https://github.com/wbkd/react-flow/issues/2651), and I have changed my code to below:

```typescript
get selectedEdges() {
    return this.edges.filter((edge) => edge.selected);
  }
```

with mobx computed, this problem resolved.

**Comment by moklick** [comment]
This doesn't work because you haven't implemented `onNodesChange` and `onEdgesChange`. If you want to work with a controlled flow, those props are mandatory https://reactflow.dev/docs/concepts/core-concepts/
