### ISSUE TITLE
Node disappears when I don't set width

### ISSUE THREAD

**Issue by alex-malyita** [wbkd/react-flow#3270]
### Describe the Bug

Some of my nodes doesn't have width, there is a dynamic content.
Initial render is fine, zooming... but if I change content inside such Node (There is a content editable element) - then Visibility: hidden is applied automatically.
I tried to setup min-width, width: 'auto', it didn't help.
And no matter if onlyRenderVisibleElements applied or not

### Steps to Reproduce the Bug or Issue

1. Add node and don't set width, just height
2. Add content editable inside
3. Change content (using some state managers to trigger React rerender)

### Expected behavior

The node stays visible

### Screenshots or Videos

<img width="985" alt="image" src="https://github.com/wbkd/react-flow/assets/12501584/d462effc-6987-455b-a5b9-fd596a54d542">

### Platform

- OS: macOS
- Browser: Chrome
- Version: last

**Comment by bcakmakoglu** [comment]
A proper reproduction would be helpful to debug this.

[A template can be found here.](https://codesandbox.io/s/react-flow-starter-typescript-j8lkh)

**Comment by alex-malyita** [comment]
I'm trying to build it... but simple case works) can't figure out what exactly causes this

**Comment by chirag-thirstydevs** [comment]
Have you solved this issue, I am also facing similar issue, node is not visible as visibility is set to hidden when I load data from API

**Comment by alex-malyita** [comment]
I've found the bug in the core..

1
```
packages/core/src/container/NodeRenderer/index.tsx
initialized={!!node.width && !!node.height}
```

2
```
packages/core/src/components/Nodes/wrapNode.tsx
visibility: initialized ? 'visible' : 'hidden',
```

**Comment by moklick** [comment]
@alex-malyita that's not a but, but the expected behaviour. We measure the node, set the dimensions and then make it visible.

**Comment by alex-malyita** [comment]
@moklick okay, let me check the call stack, will be easier to identify the issue..

**Comment by alex-malyita** [comment]
@chirag-thirstydevs I just hardcoded `visible  !important` in styles. I use onlyRenderVisibleElements - so it's not an issue for me

**Comment by moklick** [comment]
If you could provide a codesandbox I might be able help here. I am sure that you don't need the `!important` workaround

**Comment by alex-malyita** [comment]
I can't share my project codebase.. And couldn't reproduce with simple setup.

**Comment by gwing33** [comment]
Not sure if this will help, but I was having the same issue (`visibility: hidden` was being applied). Our issues was that the `node.id` was a number. Forcing it to a string resolved the issue.

**Comment by moklick** [comment]
Please re-open with a codesandbox or repo example: https://new.reactflow.dev/react-ts

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Malyita Alexandr I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-6500406.Share your review here

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Moritz Klack I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-2998105.Share your review here

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Malyita Alexandr I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-2684014.Share your review here

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Malyita Alexandr I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-7590687.Share your review here

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Moritz Klack I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-5282277.Share your review here

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Gerald Leenerts I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-8478073.Share your review here

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Moritz Klack I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-6620666.Share your review here

**Comment by mortenson** [comment]
I'm still seeing this when trying out svelteflow - nodes don't show up without a width and height, and edges also aren't showing up but I'm still trying to debug that.

**Comment by Shinyhero36** [comment]
I have the issue, here is a minimal [stackblitz](https://stackblitz.com/~/github.com/Shinyhero36/sk5-flow-invisible-nodes) using svelte 5.

**Comment by tMathaiou** [comment]
I have the same problem, visibility i set to hidden but i have width and height and edges are gone
