### ISSUE TITLE
PanOnScrollMode.Horizontal seems to be broken

### ISSUE THREAD

**Issue by bcrudolp** [wbkd/react-flow#3272]
### Describe the Bug

I set `zoomOnScroll={false}` and then set the `panOnScroll` prop on my `ReactFlow` and set the `panOnScrollMode` using ternary logic according to a state value that is modified when I hold down `Shift` (to intuitively match behavior of a plain old HTML web page section's scrolling) but it doesn't work. The logic: `shiftHeld ? PanOnScrollMode.Horizontal : PanOnScrollMode.Vertical`

I searched on the Discussions tab and found this [discussion](https://github.com/wbkd/react-flow/discussions/1288). I accordingly updated the `panOnDrag` prop (newer version equivalent of `paneMoveable` mentioned in that thread) to be false when `Shift` is held down. It still doesn't work. Am I missing something? Can anyone point me to a place that demonstrates a working example that causes horizontal panning when `Shift` is held down?

Note: I can verify my state is being conveyed correctly because it no longer pans in the vertical direction when I hold down `Shift`, but neither is it panning horizontally like it's supposed to.

### Steps to Reproduce the Bug or Issue

Attempt to configure a `ReactFlow` to panOnScroll horizontally with react-flow@11.7.0

### Expected behavior

I wanted to have the diagram pan horizontally like simple web pages scroll horizontally when you perform a `Shift`+`<mouse-wheel>` action.

### Screenshots or Videos

![ReactFlowPanOnScrollHorizontalProps](https://github.com/wbkd/react-flow/assets/97194517/494cd81f-5ef9-4a5a-b3f0-4f0f3af1a38c)

### Platform

- OS: Windows 10 Enterprise
- Browser: Chrome
- Version: Version 115.0.5790.110 (Official Build) (64-bit)

### Additional context

I have no idea what version of react-flow is used for this [demo app](https://react-flow-dev.netlify.app/interaction) and I doubt they have the specific key handling , but it at least demonstrates that PanOnScrollMode.Horizontal does not achieve out-of-the-box what I intuitively thought it should (that is, `Shift`+`mouse-wheel` panning side-to-side).

**Comment by checkomkar** [comment]
Hey @bcrudolp I have raised a PR for this issue you can test it by checking out in [this](https://github.com/wbkd/react-flow/pull/3276) branch. Thanks.

**Comment by bcrudolp** [comment]
This must be a Windows issue then. I was actually using `PanOnScrollMode.Horizontal` only as a workaround when I found I couldn't use `Shift`+mousewheel-scroll to pan sideways with `PanOnScrollMode.Free`.

**Comment by bcrudolp** [comment]
@checkomkar this fix does seem to fix being able to horizontally scroll, and would work with my current strategy of catching the `Shift` key manually to switch between `PanOnScrollMode.Horizontal` and `PanOnScrollMode.Vertical`. But it does not establish the behavior where `PanOnScrollMode.Free` allows horizontal panning when `Shift`+mousewheel-scroll is used.

@moklick are you in agreement that it should pan horizontally in `PanOnScrollMode.Free` with a `Shift`+mousewheel-scroll action?

**Comment by moklick** [comment]
@bcrudolp I can pan horizontally with Shift + mousewheel scroll when I use `panOnScroll` + `PanOnScrollMode.Free`.

**Comment by bcrudolp** [comment]
@moklick on Mac, right?

**Comment by moklick** [comment]
Yep, macOS. I need to check a windows machine

**Comment by moklick** [comment]
For now I couldn't find a solution for this. On Windows the middle mouse key activates horizontal scroll for IE, Firefox and Chrome (Shift is the macOS default) https://q8gsdq.csb.app/.  

Middle mouse should already work but a mouseup event gets triggered as soon as the user moves the mouse (while holding middle mouse) on Windows. I need to figure out why.
