### ISSUE TITLE
Can we use other component library like MUI to create custom nodes?

### ISSUE THREAD

**Issue by DeveshChauhan** [wbkd/react-flow#3278]
### Describe the Bug

Dropdown list is not appearing on focus of the mui Select component, though it works fine using arrow keys.

### Your Example Website or App

https://codesandbox.io/s/relaxed-nash-44zmkr?file=/TextUpdaterNode.js

### Steps to Reproduce the Bug or Issue

Click on "Select" dropdown.

### Expected behavior

As a user, I should be able to see the dropdown list, but I am not able to see the dropdown list on focus of the Select component.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey @DeveshChauhan 

you need to add the class name "nodrag" to the select component https://codesandbox.io/s/affectionate-https-lpj3rd?file=/TextUpdaterNode.js

**Comment by DeveshChauhan** [comment]
@moklick Can you please have a look here, added class name "nodrag". It is not working as expected.

Though it worked well in the above link you shared.

Thanks

https://codesandbox.io/s/eloquent-architecture-g89n6q?file=/CustomNodes.js

**Comment by moklick** [comment]
If you set `nodesDraggable={false}`, panning is the default action. You need to prevent this by adding the class name "nopan". This API could be better .. 

https://codesandbox.io/s/icy-dream-ndk65h?file=/TextUpdaterNode.js:728-758
