### ISSUE TITLE
Move canvas when hitting canvas edge while dragging an item

### ISSUE THREAD

**Issue by Vladislav747** [wbkd/react-flow#3281]
### Please describe the feature that you want to propose

Hello! i`ve watched your issues and already found these similiar issues https://github.com/wbkd/react-flow/issues/460

https://github.com/wbkd/react-flow/issues/392

but i didn`t understand - had you fixed it in 10.3.17 version or not? Or maybe you have found good solutions for these problem. I have mine which work not so optimized in 9v but now it doesn`t work in 10v.

**Comment by moklick** [comment]
This feature is available since v11.5.0 - I will update the other issues. Thanks for bringing this up.
