### ISSUE TITLE
[DEPRECATED] Use `createWithEqualityFn` from 'zustand/traditional'. https://github.com/pmndrs/zustand/discussions/1937

### ISSUE THREAD

**Issue by kmlcnclk** [wbkd/react-flow#3295]
When I try to use react-flow, I am getting a warning like that. Probably, Zustand deprecated it at the last update. Can you fix it please ?

[DEPRECATED] Use `createWithEqualityFn` from 'zustand/traditional'. https://github.com/pmndrs/zustand/discussions/1937

**Comment by EnzoGehlen** [comment]
same here

**Comment by Pyotato** [comment]
same issue. My console is getting flooded with the warning.

**Comment by gilneto8** [comment]
Same here.

![image](https://github.com/wbkd/react-flow/assets/15315355/9e0f3794-663b-4b00-aa20-f1adabe593af)

**Comment by shikharx06** [comment]
Same here
![Screenshot 2023-08-05 at 5 29 14 PM](https://github.com/wbkd/react-flow/assets/41422987/ade5c524-4c77-4d61-89e0-4ce97114ed5a)

**Comment by kmlcnclk** [comment]
I have solved the problem. You have to download Zustand manually. As in the image, reactflow using zustand version 4.3.1 but zustand version 4.4.0 automatically downloading when we downloaded reactflow.

![image](https://github.com/wbkd/react-flow/assets/56474929/248ddf4e-e770-4265-98b1-560f1b95e1de)

**Comment by gilneto8** [comment]
Downgrading seems more like a workaround than a fix, but it works for now.

**Comment by kmlcnclk** [comment]
> Downgrading seems more like a workaround than a fix, but it works for now.

You are right bro.

**Comment by moklick** [comment]
It's just a warning. You can ignore it for now or pin the zustand version to `4.3.9` if it's too annoying. This will be fixed with the next release.

**Comment by howion** [comment]
For anyone who want to suppress this warning, it is possible to do so in Developer Tools via Console > Custom Levels > (Uncheck) Warnings.

**Comment by moklick** [comment]
fixed in v11.8.0
