### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by lancemao** [wbkd/react-flow#3297]
### Describe the Bug

typo in doc

### Steps to Reproduce the Bug or Issue

https://reactflow.dev/docs/examples/nodes/add-node-on-edge-drop/

doc says:
You can create a new node when you drop the connection line on the pane by using the onConnectionStart and **onConnectionStop** handlers.

but in code sample it is actually 
**onConnectEnd**={onConnectEnd}

### Expected behavior

should be consistant

### Platform

- OS: [macOS, Windows, Linux]
- Browser: [Chrome, Safari, Firefox]
- Version: [91.1]

**Comment by checkomkar** [comment]
Fixed the typo in [this](https://github.com/wbkd/react-flow-docs/pull/132) PR

**Comment by moklick** [comment]
thanks @lancemao for the report and @checkomkar for the fix :)
