### ISSUE TITLE
الاسكندريه 

### ISSUE THREAD

**Issue by Salaheldean** [wbkd/react-flow#3299]
### Please describe the feature that you want to propose

تكنولوجيا فائقه التطور مدينه كامله تعمل بالنظام الذكاء الاصطناعي

**Comment by Salaheldean** [comment]
اسمي صلاح سيف من اسكندريه

**Comment by moklick** [comment]
hey! we can't speak Arabic - please re-open in English, if there is an issue to report.

**Comment by Salaheldean** [comment]
I would like to join the auditors in my country
