### ISSUE TITLE
Connnot click on element in EdgeLabelRenderer of CustomEdge

### ISSUE THREAD

**Issue by tuannguyenhoangit-droid** [wbkd/react-flow#3303]
### Describe the Bug

I have a custom edge component called Runs.

```
import '../App.css'
import React from 'react';
import { EdgeLabelRenderer, getStraightPath } from 'reactflow';

const Runs = (props) => {
  const {id, sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, data} = props;
  const [edgePath, labelX, labelY] = getStraightPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });

  return (
    <>
      <path id={id} d={edgePath} stroke={data?.stroke || '#222344'} />
      <EdgeLabelRenderer>
        <div
          onClick={(e) => {
            e.preventDefault();
            alert(`remove ${id}`);
            // sendActionToMobileApp('LOG', {message: 'clicked'})
          }}
          style={{
            position: 'absolute',
            transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
            justifyContent: 'center',
            alignItems: 'center',
            display: 'flex',
            color: data.color || 'white',
            backgroundColor: 'white',
            paddingLeft: 2,
            paddingRight: 2,
            zIndex: 99,
          }}
        >
          {!!data?.runName ? <div>{data.runName || ''}</div>: null}
        </div>
      </EdgeLabelRenderer>
    </>
  );
};

export default Runs;
```

It appears in bellow image with label A11. I facing issue that i cannot click on label, onClick of div element doesn't trigger.

<img width="1592" alt="Screenshot 2023-08-07 at 21 34 45" src="https://github.com/wbkd/react-flow/assets/56645054/99f87a79-ae30-43b2-8a7e-452ffb289f28">

### Steps to Reproduce the Bug or Issue

See above description

### Expected behavior

Able to trigger onClick function of div element

### Platform

- OS: MacOS
- Browser: Chome

**Comment by moklick** [comment]
Please check the docs https://reactflow.dev/docs/api/edges/edge-label-renderer/ 

> The <EdgeLabelRenderer /> has no pointer events by default. If you want to add mouse interactions you need to set pointerEvents: all and add the class name nopan on the label or the element you want to interact with.

**Comment by moklick** [comment]
You need to set `pointerEvents: all` for the EdgeLabelRenderer.

**Comment by tuannguyenhoangit-droid** [comment]
Thank @moklick, it works
