### ISSUE TITLE
Edge not rendered and Node z-index is set to 0

### ISSUE THREAD

**Issue by chirag-thirstydevs** [wbkd/react-flow#3310]
### Describe the Bug

If i use simple react-flow without backend integration then it is working perfectly find but if I use backend api and load data from server at that time edge is not being rendered neither previous one loaded from the server nor new, also node is not visible as style is automatically set z index to 0 when integrating with backend api but without integration it is being set as 1000.
What I am missing here?

### Steps to Reproduce the Bug or Issue

![image](https://github.com/wbkd/react-flow/assets/106539944/bcaff415-0a13-48c5-8f78-5ea66f59a30e)

### Expected behavior

Edge should be visible while connecting or when loading previous data from API

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/106539944/eee3949e-ac03-4b8a-8ab0-b5a593b86bb5)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Please provide a repo or a codesandbox https://new.reactflow.dev/react-ts. Those screenshots doesn't help.

**Comment by chirag-thirstydevs** [comment]
I managed to resolve the issue. It turned out that the problem was caused by using integer node IDs. Once I switched those IDs to strings, everything started working smoothly.

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Moritz Klack I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-4855460.Share your review here
