### ISSUE TITLE
[ReferenceError]: navigator is not defined

### ISSUE THREAD

**Issue by Reflejo** [wbkd/react-flow#3315]
### Describe the Bug

Getting this error after updating. Seems to be introduced by https://github.com/wbkd/react-flow/commit/32101dde66cccbbd64b4486e47e9441182d93e7b#diff-4dc1db8ddcb4b4ab77751f196ddc803c80c059ce3fe31281ad41d13c6b091b57R130

(I'm using nextJS)

I believe that code should be checking for `typeof window !== "undefined"`.

### Steps to Reproduce the Bug or Issue

1. Update to 11.8.0
2. Render the `<ReactFlow />` element

### Expected behavior

It works on nextJS

### Platform

- OS: macOS
- Browser: Chrome

**Comment by moklick** [comment]
Thanks @Reflejo !

Fixed in 11.8.1
