### ISSUE TITLE
Edge angle is broken for vertically or horizontally aligned nodes

### ISSUE THREAD

**Issue by GenaRazmakhnin** [wbkd/react-flow#3326]
### Describe the Bug

I believe the bug is related to this one:
https://github.com/wbkd/react-flow/issues/3205

### Steps to Reproduce the Bug or Issue

1) Create 2 nodes vertically aligned or horizontally
2) Create an edge between them left sourceHandle + left targetHandle or right sourceHandle + right targetHandle

### Expected behavior

As a user, I want to see the correct 90 degree angle for "step" nodes and rounded 90 degree angle for "smoothstep" nodes
1) in the case when 2 nodes vertically aligned and sourceHandle / targetHandle placed on left+left or right+right sides 
2) in the case when 2 nodes horizontally aligned and sourceHandle / targetHandle placed on top+top or bottom+bottom sides 

### Screenshots or Videos

<img width="492" alt="Screenshot 2023-08-15 at 11 50 54" src="https://github.com/wbkd/react-flow/assets/9819783/0c6db9ac-eb47-4c51-9e80-18dae12a8a2e">

**Comment by phongman** [comment]
i also face this after update reactflow to 11.8.0

**Comment by moklick** [comment]
How can I reproduce this. Isn't this the case you are describing https://codesandbox.io/s/laughing-hodgkin-xrs3zq?file=/src/Flow.tsx ?

**Comment by phongman** [comment]
i edited your csb and this is my case https://codesandbox.io/s/elastic-colden-5wphdd?file=/src/Flow.tsx

**Comment by moklick** [comment]
should be fixed in 11.8.3
