### ISSUE TITLE
Child node is node detecting parent node area after rotation

### ISSUE THREAD

**Issue by bilalkhan13** [wbkd/react-flow#3329]
### Describe the Bug

Child node is node detecting parent node area after rotation
`https://raul-r.tinytake.com/msc/ODU3MDk1MF8yMTkxNDY4NQ`

### Your Example Website or App

(https://react-flow-kappa.vercel.app/)

### Steps to Reproduce the Bug or Issue

Create a Parent & child node, then rotate the parent node and drag child node init.

### Expected behavior

Child node should detected parent area after parent rotation

### Platform

- OS: [ Windows, Linux]
- Browser: [Chrome, Firefox]
- Version: [11.7.4]
https://raul-r.tinytake.com/msc/ODU3MDk1MF8yMTkxNDY4NQ

**Comment by moklick** [comment]
Please re-open with a codesandbox or repo that reproduces the issue.
