### ISSUE TITLE
BaseEdge (BaseEdgeProps) does not have id prop as not pulled from Pick on EdgeProps. But given in Edge Label Renderer example

### ISSUE THREAD

**Issue by iw-nallen** [wbkd/react-flow#3332]
### Describe the Bug

In the example for [Edge Label Renderer](https://reactflow.dev/docs/examples/edges/edge-label-renderer/) the BaseEdge component is passed an `id` prop. 

I get a typescript error from this as `id` is not matched in BaseEdgeProps, which in turn does a Pick on EdgeProps. Can you add `id` to this Pick please.

`export type BaseEdgeProps = Pick<EdgeProps, 'style' | 'markerStart' | 'markerEnd' | 'interactionWidth'> & EdgeLabelOptions & {
    labelX?: number;
    labelY?: number;
    path: string;
};`

### Steps to Reproduce the Bug or Issue

1. Create custom edge using Edge Label Renderer example.
2. Should get error on id prop in <BaseEdge /> component.

### Expected behavior

As a user I expect `id` field to be included in BaseEdgeProps.

### Screenshots or Videos

![Screenshot 2023-08-16 at 10 00 15](https://github.com/wbkd/react-flow/assets/142392321/e2d20b81-a266-4e02-a62a-305e5910078a)

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome]
- Version: [11]

### Additional context

I see in [docs](https://reactflow.dev/docs/api/edges/base-edge/) for BaseEdge, `id` doesnt exist as a prop, so why is it used in the [Edge Label Renderer example](https://reactflow.dev/docs/examples/edges/edge-label-renderer/)

**Comment by moklick** [comment]
`id` prop should be available in the latest version of React Flow, I just updated the docs. Thanks for the report @iw-nallen !
