### ISSUE TITLE
Handles that can be both a source and a target

### ISSUE THREAD

**Issue by emilbon99** [wbkd/react-flow#3335]
### Please describe the feature that you want to propose

I'm working on implementing a plumbing and instrumentation diagram builder using Reactflow (great so far!). I'm running into an issue where I'd like to connect two sources together. I've attached a screenshot where I want to add a valve that I'd like to attach an arbitrary source/target to and from any point on the tank. Right now, I need to add a mix of source and target handles on the tank when I'd like to have them serve both purposes.

<img width="1500" alt="Screenshot 2023-08-16 at 1 46 49 PM" src="https://github.com/wbkd/react-flow/assets/56323762/677644a6-87f4-4760-a09b-ccd5a571b037">

**Comment by moklick** [comment]
you can use type="source" for all handles in combination with connectionMode={ConnectionMode.Loose} https://reactflow.dev/docs/api/react-flow-props/#connectionmode

**Comment by emilbon99** [comment]
Can't believe I missed that. Thank you so much!

**Comment by moklick** [comment]
I would blame the bad API design 😅

**Comment by livwvil** [comment]
> I would blame the bad API design 😅

It would be great to clarify this point in the documentation. It I get an error if I use 'target' instead of 'soure'.
```[React Flow]: Couldn't create edge for source handle id: "terminal_2", edge id: xy-edge__mimic-11terminal_2-mimic-12terminal_1. Help: https://reactflow.dev/error#008```
