### ISSUE TITLE
svelte-flow (xyflow) Node selected declaration re-runs for all Nodes

### ISSUE THREAD

**Issue by adamdva** [wbkd/react-flow#3336]
### Describe the Bug

Using the CustomNode example in the svelte-flow branch (xyflow), declare a local declaration to run when the Node is selected:
`
export let selected: $Props['selected'] = false;
$: selected, console.log(selected, data.name);
`
This works and runs when a Node is selected/unselected, however, if many Nodes are in the flow, like the stress example, the declaration is re-run for every Node. So all unselected Nodes indicate 'false' every time the selection is changed.

### Steps to Reproduce the Bug or Issue

1. Setup a svelte flow that displays multiple CustomNodes.
2. Add the selected declaration to the CustomFlow script
3. Load page and look at console load for re-runs

### Expected behavior

I expected to see two (2) re-runs of the 'selected' declaration, one for the node unselected (false) and one for the node selected (true),
but I am seeing every node declaration re-run, with one(1) selected (true), and the rest unselected (false)

### Platform

- OS: [Linux server, Windows 11 client]
- Browser: [Chrome]
- Version: [xyflow branch, latest]

### Additional context

(I can put some example svelte scripts if this is needed later)

**Comment by adamdva** [comment]
Updated the code example.
When the declaration log contains the `data.name`, the declaration is re-run on all Nodes. If I only log the `selected` value, it works, so seams related to the `data` declared prop.
I'm also new to svelte, so not sure if this is a general svelte issue, will try to test, and let you know.

**Comment by peterkogo** [comment]
@adamdva This issue is fixed in the upcoming version of svelte flow. 

For anyone wondering how this was prevented:
You can use <svelte:options immutable /> inside a component to make svelte perform additional equality checks on incoming props that are treated as mutable and thus always re-rendered by default (objects, arrays).

**Comment by moklick** [comment]
released in 0.0.22
