### ISSUE TITLE
getIntersectingNodes doesn't work properly when using Elkjs

### ISSUE THREAD

**Issue by Toukassay** [wbkd/react-flow#3339]
### Describe the Bug

I've fork you ElkJS example and add a simple onDragNode function to show you : https://codesandbox.io/s/cold-sun-kznqln
```js
  // When dragging a node, if it intersects with another, console.log the id
  const onNodeDrag = useCallback(
    (_, node) => {
      const intersections = getIntersectingNodes(node).map((n) => n.id);
      console.log("intersections", intersections);
    },
    [getIntersectingNodes]
  );
  ```
  By dragging the node 4 on another one, you will see that this doesn't seems to be intersecting, although is it : 
![image](https://github.com/wbkd/react-flow/assets/8450100/7ea71f37-17fd-4306-bb34-636c9e0fb373)

But if you move it on his previous place, you will see that it's intersecting with itself (!), based on his previous position.
![image](https://github.com/wbkd/react-flow/assets/8450100/61a231c0-c388-4f95-b0ed-d0d1fee69bfa)

That scenario can be made with every other nodes of course.

Do you have a clue on how to resolve this ?

### Your Example Website or App

https://codesandbox.io/s/cold-sun-kznqln

### Steps to Reproduce the Bug or Issue

1. Move `node 4` on another one
2. The intersecting node ID isn't console logged
3. Move `node 4` back to his position
4. `node 4` id is console logged as intersecting with itself based on his initial position

### Expected behavior

I expected to be working as when non using ElkJS

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
haha, this is a funny bug. The d3 layout adds an "x" and "y" prop. Then React Flow things that your are [passing a rect](https://github.com/wbkd/react-flow/blob/main/packages/core/src/utils/index.ts#L81-L82) . You can fix it, by just passing the node id like this: https://codesandbox.io/s/great-fire-tlrsf7?file=/App.js:2808-2885

**Comment by Toukassay** [comment]
Perfect, thanks
