### ISSUE TITLE
expandParent nope option not allowing children nodes to expand parent nodes when set to true

### ISSUE THREAD

**Issue by rperendy** [wbkd/react-flow#3340]
### Describe the Bug

This is a beautiful project so thank you for developing it!

I'm a pro subscriber and when playing around with the dynamic grouping example I noticed some odd behavior. First, the initial parent node can be expanded upon by its children, but the expandParent node option is not set to true or any state for any of its children nodes. When I drag and drop a new group node onto the canvas, and then drag an existing node into the new group node it assigns properly but I cannot expand the parent extent by dragging the children to the group node's boundary. 

The latter makes sense as the expandParent node option isn't set for any of the initial nodes. 

To further diagnose I hardcoded the expandParent node options (true/false) in the initial elements and noticed the same phenomena. 

I'm wondering if this has something to do with the nodes array and how they are sorted since the initial group node always comes first then the second group node. 

### Steps to Reproduce the Bug or Issue

1. Use Dynamic Grouping Pro Example
2. Drag an already existing child node in the initial group node to see that the group node's extent can expand.
3. Verify node options for initial nodes do not have expandParent set to true. 
4. Hardcoded initial node option expandParent for all simple node types to false results in the same phenomena. Verified Node Options on console log. 
5. Hardcoded initial node option expandParent for all simple node types to true results in the same phenomena. Verified Node Options on console log. 

### Expected behavior

dragging of children nodes should not expand parent node extent with current settings, yet does so only in the demo for the initial group node. Dragging and dropping a new group node shows behaviors as expected. 

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/67077261/8f6705f4-f554-4b51-83a8-94fa9d2cb263

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey @rperendy 

this is not a bug, but an example of how you can implement custom functionality based on child nodes. In this case we are calculating the group node dimension based on the child nodes. It's this part of the custom group node implementation:


```js
const { minWidth, minHeight, hasChildNodes } = useStore((store) => {
  const childNodes = Array.from(store.nodeInternals.values()).filter((n) => n.parentNode === id);
  const rect = getRectOfNodes(childNodes);

  return {
    minWidth: rect.width + padding * 2,
    minHeight: rect.height + padding * 2,
    hasChildNodes: childNodes.length > 0,
  };
}, isEqual);
```

If you don't like that behaviour, you can safely remove the `minWidth` and `minHeight` code.
