### ISSUE TITLE
Prevent edge and node intersection

### ISSUE THREAD

**Issue by yunusyavuz16** [wbkd/react-flow#3341]
How to prevent edge and node intersection

I need a edge type that does not intersect with a node. I use source node and target node handles vertically as a business rule. When I connect one node bottom handle that is below of the another node to another node up handle, the edge intersect with both two nodes. This makes it difficult to understand the workflow.

My edge code:

`import {BaseEdge, EdgeLabelRenderer, EdgeProps, getBezierPath} from 'reactflow'

import './styles.scss'
import {useDispatch} from 'react-redux'
import {setSelectedWorkflowItem} from '../../../../redux/slices/WorkflowReducer'

function CustomEdges(props) {
  const {
    id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    style = {},
    markerEnd,
    data,
    selected,
  }: EdgeProps = props
  const dispacth = useDispatch()
  const [edgePath, labelX, labelY] = getBezierPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  })

  const onEdgeClick = (evt, id) => {
    evt.stopPropagation()
    dispacth(setSelectedWorkflowItem({item: props}))
  }
  
  const styleProps = data.isDefault
    ? {...style, strokeWidth: 3}
    : data.selected
    ? {...style, strokeWidth: 2}
    : {...style, strokeWidth: 1.5}

  return (
    <>
      <BaseEdge path={edgePath} markerEnd={markerEnd} style={styleProps} />
      <EdgeLabelRenderer>
        <div
          style={{
            position: 'absolute',
            transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
            fontSize: 12,
            // everything inside EdgeLabelRenderer has no pointer events by default
            // if you have an interactive element, set pointer-events: all
            pointerEvents: 'all',
          }}
          className='nodrag nopan'
        >
          <button
            className={`edgebutton background-workflow ${
              data.selected && 'background-workflow-active'
            }`}
            onClick={(event) => onEdgeClick(event, id)}
          >
            {data?.displayName}
          </button>
        </div>
      </EdgeLabelRenderer>
    </>
  )
}

export default CustomEdges
`

What I got:

<img width="447" alt="Screenshot 2023-08-20 at 20 51 07" src="https://github.com/wbkd/react-flow/assets/76525954/b31c354a-d5d7-4f16-b321-0b127b93e83f">

What I expected:

<img width="447" alt="Screenshot 2023-08-20 at 20 51 07 2" src="https://github.com/wbkd/react-flow/assets/76525954/08bc5308-918c-425d-a9c6-606c85dad365">

In the same time, it should not break the edge relation with other nodes:

<img width="855" alt="Screenshot 2023-08-20 at 21 11 48" src="https://github.com/wbkd/react-flow/assets/76525954/c6983cf1-25cf-4b67-ab51-d0dc8a30dded">

**Comment by moklick** [comment]
Hey @yunusyavuz16 

edge routing is not built in. We have a section in our layouting guide that should help you to get started: https://reactflow.dev/docs/guides/layouting/#routing-edges

**Comment by johannbuscail** [comment]
Hey @yunusyavuz16 ! Have you found a solution for this issue ? I'm facing a similar problem

**Comment by yunusyavuz16** [comment]
> Hey @yunusyavuz16 ! Have you found a solution for this issue ? I'm facing a similar problem

I gave up using the feature I wanted. Because the library does not provide this feature, you can provide it by integrating a different library, but it spoils the beauty of the application because it is overwhelmed with mathematical operations.

**Comment by Yelmor** [comment]
Instead of implementing a custom edge, I have a compromised/simpler solution: add a custom node between two normal nodes when connecting them. Also, delete the custom node when its edge is deleted.

Demo code:
https://codesandbox.io/s/react-flow-edge-adjust-h3qx4h?file=/src/Flow.js

**Comment by Streen9** [comment]
did anyone find the solution how can we solve this?

**Comment by yunusyavuz16** [comment]
> did anyone find the solution how can we solve this?

Adding a hidden node on the path is a way to prevent intersections. On the other hand, there are some libraries you can integrate to find the best route avoiding intersection. But, libraries make some heavy calculations to find the best route, which it makes the application slow.

> Hey @yunusyavuz16
> 
> edge routing is not built in. We have a section in our layouting guide that should help you to get started: https://reactflow.dev/docs/guides/layouting/#routing-edges
> 
> If you only need to handle some cases, you can also implement a custom edge that handles those cases.

**Comment by saulshanabrook** [comment]
I was able to implement edge routing using the edges provided by the ELK layout:

[![Screenshot 2024-08-23 at 5 02 22 PM](https://github.com/user-attachments/assets/52ab9328-55a9-476e-8ecd-94b4f9c40281)](https://github.com/saulshanabrook/egraph-visualizer)


I created [a custom edge](https://github.com/saulshanabrook/egraph-visualizer/blob/2c7e96ebdf53b8c3690f4f729a46ae69ecbbf70e/src/Visualizer.tsx#L347-L351) that made an edge path and copied the path from [the laid out ELK edges](https://github.com/saulshanabrook/egraph-visualizer/blob/2c7e96ebdf53b8c3690f4f729a46ae69ecbbf70e/src/Visualizer.tsx#L279-L284).

**Comment by imabp** [comment]
So you can use a hacky way as last resort to use code implant of the [archived smart edge repository](https://github.com/tisoap/react-flow-smart-edge/tree/main/src) 

But, you can just re-use the existing code from the source files,  (https://github.com/tisoap/react-flow-smart-edge/tree/main/src) in your codebase and render it. It definitely works.

**Comment by awaisshah228** [comment]
I created a package that prevents edge-node intersection: **[avoid-nodes-edge](https://www.npmjs.com/package/avoid-nodes-edge)**

It routes edges orthogonally around nodes — edges never cross through any node. Uses libavoid (C++ WASM) in a Web Worker for performance.

**[Live Demo](https://avoid-nodes-pro-example.vercel.app)** | **[GitHub](https://github.com/awaisshah228/react-flow-avoid-nodes-routing)**

```bash
npm install avoid-nodes-edge libavoid-js
```

Works with React Flow v12+.

**Comment by poojavarma01** [comment]
@awaisshah228 If three nodes are placed in a straight line(both horizontal or vertical), where A is connected to C and B is also connected to C, all edges appear as straight lines, making it hard to distinguish the connections.

Is it possible to visually differentiate these connections in React Flow?
I am already using Bezier edges by default, but since the nodes are aligned, the edges still look straight.

Can this be handled using the avoid-node-edge library?

**Comment by awaisshah228** [comment]
Yes it do wasm.based support othagnol lines for brazier i released another package 
https://github.com/awaisshah228/avoid-edge-routing
https://avoid-edge-routing-example.vercel.app/ u can check demo here

**Comment by poojavarma01** [comment]
Thanks @awaisshah228,

**Comment by tisoap** [comment]
For people interested, I've build [react-flow-smart-edge](https://github.com/tisoap/react-flow-smart-edge) using A* pathfinding to route edges around other nodes, avoiding intersections. It has smart equivalents for every type of edge React Flow has.
