### ISSUE TITLE
Set Viewport on the New dynamically Created Node position

### ISSUE THREAD

**Issue by serudda** [wbkd/react-flow#3342]
### Please describe the feature that you want to propose

I'm not sure if you guys have an example of this implementation, or it could be a new feature... the ability to set the viewport at the position where a new Node is dynamically created.

**Comment by moklick** [comment]
Hey @serudda 

you can use [`setCenter`](https://reactflow.dev/docs/api/react-flow-instance/#setcenter) for this. Example: https://codesandbox.io/s/musing-cdn-g5g5v9?file=/src/Flow.tsx:1672-1739
