### ISSUE TITLE
Compiling error when migrating to V11

### ISSUE THREAD

**Issue by AntonioGally** [wbkd/react-flow#3358]
### Describe the Bug

I'm using `react-flow-renderer@9.6.6` and I need to upgrade to V11, when I do that, I receive this error:
```
./node_modules/@reactflow/minimap/dist/esm/index.js 152:84
Module parse failed: Unexpected token (152:84)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     rfId
|   } = useStore(selector, shallow);
>   const elementWidth = (style === null || style === void 0 ? void 0 : style.width) ?? defaultWidth;
|   const elementHeight = (style === null || style === void 0 ? void 0 : style.height) ?? defaultHeight;
|   const scaledWidth = boundingRect.width / elementWidth;
```

I already saw some issues about it but couldn't solve the problem
Some issues related: 
- [Reactflow bundling error in storybook](https://github.com/wbkd/react-flow/issues/2652) 
- [Importing reactflow v11 causes error "module parse failed: unexpected token"](https://stackoverflow.com/questions/74423572/importing-reactflow-v11-causes-error-module-parse-failed-unexpected-token)
- [V11 Build Errors with Webpack & Gastby](https://github.com/wbkd/react-flow/issues/2705)

Here our dependencies list:
```json
"dependencies": {
    "@react-pdf-viewer/core": "^2.3.0",
    "@react-pdf-viewer/default-layout": "^2.3.0",
    "@sentry/react": "^7.56.0",
    "ace-builds": "^1.4.12",
    "antd": "4.14.0",
    "axios": "^0.21.0",
    "d3": "^7.8.5",
    "dangerously-set-html-content": "^1.0.8",
    "date-fns": "^2.17.0",
    "es5-shim": "^4.5.15",
    "es6-shim": "^0.35.6",
    "identity-obj-proxy": "3.0.0",
    "immer": "^9.0.6",
    "jschardet": "^3.0.0",
    "lodash": "4.17.19",
    "object.entries": "^1.1.4",
    "object.values": "^1.1.4",
    "papaparse": "^5.4.1",
    "pdfjs-dist": "2.5.207",
    "plotly.js": "^1.58.4",
    "promise.prototype.finally": "^3.1.2",
    "randexp": "^0.5.3",
    "rc-color-picker": "^1.2.6",
    "rc-select": "^14.4.0",
    "re-resizable": "^6.9.0",
    "react": "17.0.1",
    "react-ace": "9.3.0",
    "react-app-polyfill": "^1.0.6",
    "react-avatar-editor": "^11.1.0",
    "react-copy-to-clipboard": "^5.0.3",
    "react-dnd": "^15.1.2",
    "react-dnd-html5-backend": "^15.1.3",
    "react-dnd-touch-backend": "^16.0.1",
    "react-dom": "17.0.1",
    "react-dropzone": "^11.2.4",
    "react-flow-renderer": "^9.6.6", //Older version
    "react-grid-layout": "1.3.0",
    "react-highlight-words": "^0.16.0",
    "react-jsx-parser": "^1.28.1",
    "react-number-format": "^4.4.1",
    "react-phone-input-2": "^2.15.1",
    "react-plotly.js": "^2.5.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scroll": "^1.8.2",
    "react-select": "^5.7.4",
    "react-slick": "^0.28.1",
    "react-textarea-autosize": "^8.3.2",
    "react-toastify": "^7.0.4",
    "react-typist": "^2.0.5",
    "reactflow": "^11.8.3", //New version
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "sanitize-html": "^2.3.0",
    "slick-carousel": "^1.8.1",
    "sockjs-client": "^1.5.0",
    "stompjs": "^2.3.3",
    "typescript": "^4.7.4",
    "uuid": "^8.3.2",
    "xlsx": "https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz"
  },
```

### Steps to Reproduce the Bug or Issue

I couldn't reproduce this error

### Expected behavior

It's expected that the project compiles the new version of reactflow

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/68209906/bf2159dc-6b25-488d-bf2f-12af586836da)

### Platform

- OS: macOS
- Browser: Chrome
- Version: Latest

### Additional context

This React code is ejected and we use storybook, but the error happens when we try to run `yarn start`

**Comment by moklick** [comment]
Are you using an older version of create-react-app? If so, you need to transpile React Flow as described here https://github.com/wbkd/react-flow/issues/2453#issuecomment-1620059828

**Comment by AntonioGally** [comment]
> Are you using an older version of create-react-app? If so, you need to transpile React Flow as described here [#2453 (comment)](https://github.com/wbkd/react-flow/issues/2453#issuecomment-1620059828)

It works!! Thanks man <3 u're the best

Thats why I wasn't able to reproduce the error. I was creating a new project with a upgraded version of CRA
