### ISSUE TITLE
React does not recognize the `maxConnections` prop on a DOM element - ReactFlow

### ISSUE THREAD

**Issue by rishabhgist** [wbkd/react-flow#3366]
### Describe the Bug

While I am trying set maxConnections Prop for a node I am getting react error by using the template on  - https://reactflow.dev/docs/examples/nodes/connection-limit/ 

![error](https://github.com/wbkd/react-flow/assets/26601304/33d20d7a-94f5-4a05-aa9b-f6782b9390ba)

### Steps to Reproduce the Bug or Issue

1. Add Template from - https://reactflow.dev/docs/examples/nodes/connection-limit/

### Expected behavior

Can anyone help me on this issue ?

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [116.0]

**Comment by hayleigh-dot-dev** [comment]
Hey there thanks for this, looks like a simple bug in the example :) If you're copying the example directly just destructure `maxConnections` from the props first:

```js
const CustomHandle = ({ maxConnections, ...props }) => {
  ...
```

I'll fix the example now.
