### ISSUE TITLE
Background grid looks not good when zoomed out

### ISSUE THREAD

**Issue by lancemao** [wbkd/react-flow#3374]
### Describe the Bug

when zoomed out, ReactFlow's background grid seems too strong (bold)

### Steps to Reproduce the Bug or Issue

set up background as follow:

```xml
<Background id="1" gap={10} color="#353535" variant={BackgroundVariant.Lines} />
<Background id="2" gap={80} offset={1} color="#000" variant={BackgroundVariant.Lines} />
```

after zoomed out, it looks like this:
![Screenshot 2023-09-07 193037](https://github.com/wbkd/react-flow/assets/5020396/d4a2164b-e3a1-4809-8bb7-8eed14e01128)

compare to Unreal Engine, when zoomed out to the maximum level which is -12 (top right corner shows the level), it looks like this:
![Screenshot 2023-09-07 193030](https://github.com/wbkd/react-flow/assets/5020396/9e4d8994-2cdc-4ebc-b371-6ded554426a0)
which looks reallly good

### Expected behavior

background grid should look soft similar like Unreal Engine's blueprint editor. Maybe do some inside-out flipping?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Could you fix it on your own by passing a different `lineWidth` (maybe depending on the current zoom level)? I don't want to do this on library side, because it might lead to unexpected results.

**Comment by lancemao** [comment]
OK. I will try
But any idea how to receive Zoom events?

**Comment by moklick** [comment]
you can use `useViewport` for this https://reactflow.dev/docs/api/hooks/use-viewport/

**Comment by moklick** [comment]
closed because it can be addressed on user side.
