### ISSUE TITLE
Node id must be a string to handle the connection.

### ISSUE THREAD

**Issue by skokonozi** [wbkd/react-flow#3383]
### Describe the Bug

Hello , while i was stuck on implementing nodes with endpoints i figured out that while i was giving to the node the id as a number , it wont connect with other nodes and the path would be disabled. To make this work i used to turn id .toString().

### Steps to Reproduce the Bug or Issue

![Screenshot 2023-09-13 at 12 19 57 PM](https://github.com/wbkd/react-flow/assets/114394420/d15d9698-9ebe-4858-ae9f-9bf2af0654c8)

### Expected behavior

 i figured out that while i was giving to the node the id as a number , it wont connect with other nodes and the path would be disabled. To make this work i used to turn id .toString().

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
[As documented,](https://reactflow.dev/docs/api/nodes/node-options/#id) a node id *has to be a string* and can't be a number.

So I don't see what this issue is supposed to address?
Is this a feature request to support numbers? 🤔

**Comment by moklick** [comment]
This is solved. **Ids need to be strings**, because we are also attaching them as data attributes and there we can't distinguish between numbers and strings.
