### ISSUE TITLE
[Svelte Flow] Edge Types are not updated correctly

### ISSUE THREAD

**Issue by peterkogo** [wbkd/react-flow#3386]
### Describe the Bug

Dynamically updating edge types does not update the visible edges.

### Steps to Reproduce the Bug or Issue

In a Svelte Flow example with some edge like 
```
const edges = writable([{
	id: '1-2',
	type: 'default',
	source: '1',
	target: '2',
	label: 'Edge Text'
}]);
```
try updating the edge type

```
$edges[0].type = 'smoothstep';
$edges = $edges;
```

### Expected behavior

Edgetype should update accordingly

### Platform

- OS: macOS
- Browser: Chrome
- Version: 116

**Comment by moklick** [comment]
fixed in 0.0.19
