### ISSUE TITLE
Get the center of the current viewport

### ISSUE THREAD

**Issue by lajtmaN** [wbkd/react-flow#3391]
### Please describe the feature that you want to propose

Currently there is a way to get the viewport (getViewport), but that will only output the x,y for the topleft corner of the currently shown viewport. 

It would be nice to be able to get the center of the viewport as well, which would be calculated based on the size of the DOM node, zoom level, etc.

My purpose is to automatically add nodes to the center of the current viewport.

**Comment by moklick** [comment]
You can use the [`project` function](https://reactflow.dev/docs/api/react-flow-instance/#project) to transform a screen coordinate to a React Flow coordinate. 

```js 
const center = project({ x: flowContainerCenterX, y: flowContainerCenterY });
```

**Comment by lajtmaN** [comment]
Awesome, didn't think of that. Thanks!

**Comment by lukecivantos** [comment]
I'm currently having the same issue, but it seems that project function no longer exists. What's the new best way to do this?

**Comment by chr-loe** [comment]
To transform a screen coordinate to a React Flow coordinate you can now use this (since v11.10.0, [See release notes](https://reactflow.dev/whats-new/2023-11-10))
`const center = screenToFlowPosition({ x: flowContainerCenterX, y: flowContainerCenterY })`

To get the container center (flowContainerCenterX, flowContainerCenterY) I guess you can still use `reactFlowWrapper.current.getBoundingClientRect().width/2` and `.height/2` with a ref. With this implementation I can spawn nodes in the center of the screen.

**Comment by Rob-Fletcher** [comment]
Im pretty new to react and reactflow. Can someone give me an example of this? I cant seem to get it to work. I am trying to use the `getViewport()` function and pass the returned position in to `screenToFlowPosition()` but what I get back is always (0, 0) no matter where the screen is or what zoom. I just want to create a new node in the center of the current viewport.

**Comment by av** [comment]
Here's a sample code on adding a node to the center of the current viewport:

```typescriptreact
  const store = useStoreApi()
  const { addNodes, screenToFlowPosition } = useReactFlow()

  const handleAddNode = () => {
    const { domNode } = store.getState()
    const boundingRect = domNode?.getBoundingClientRect()

    if (boundingRect) {
      const newNode = createNode()
      const cneter = screenToFlowPosition({
        x: boundingRect.x + boundingRect.width / 2,
        y: boundingRect.y + boundingRect.height / 2,
      })

      newNode.position = {
        x: cneter.x - newNode.width / 2,
        y: cneter.y - newNode.height / 2,
      }

      addNodes([newNode])
    }
  }
```
