### ISSUE TITLE
Add custom data to Handle similar as Node and Edge

### ISSUE THREAD

**Issue by lancemao** [wbkd/react-flow#3396]
### Please describe the feature that you want to propose

https://reactflow.dev/docs/api/nodes/handle/

Currently there is data prop for node and edge, but no custom data for handle. It would be great if we can also have data for Handles

**Comment by moklick** [comment]
why do you need this? You can create a custom handle and pass everything you want.

**Comment by lancemao** [comment]
I will go with custom handle. Thanks

**Comment by moklick** [comment]
perfect!
