### ISSUE TITLE
[svelte-flow] base.css: controls not styled

### ISSUE THREAD

**Issue by peterkogo** [wbkd/react-flow#3399]
### Describe the Bug

...

### Steps to Reproduce the Bug or Issue

...

### Expected behavior

...

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
...

**Comment by moklick** [comment]
fixed in 0.0.20

**Comment by totoago** [comment]
Controls set the background
？
