### ISSUE TITLE
Background pattern doesn't pan or zoom when dragging with mouse

### ISSUE THREAD

**Issue by taylorrobert** [wbkd/react-flow#3405]
### Describe the Bug

I've got a fresh ReactFlow install in a React app. Clicking and dragging in the flow will pan, and zooming will zoom the viewport. But the background pattern (no matter which variant) is static and doesn't move, either through panning or zooming. 

Here's the smallest bit of code that still shows the issue. Nothing fancy. According to the documentation, and examples I've found online, this code should cause the background to respond.

`<ReactFlow
                    nodes={nodes}
                    edges={edges}
                >
                    <Background />
                </ReactFlow>`

### Steps to Reproduce the Bug or Issue

1. Copy the installed code into a fresh React app.
2. (Optional) Add nodes if you'd like to see that panning them works.
3. Pan by clicking and dragging (outside of a node).

### Expected behavior

I expected the pattern in the background to pan with the mouse, but it stays stationary.

### Platform

- OS: Ubuntu 22.04
- Browser: Chrome
- Version: 11.8.3

**Comment by moklick** [comment]
Are you importing the styles?

```js
import 'reactflow/dist/style.css';
```

**Comment by taylorrobert** [comment]
@moklick Indeed I am.

**Comment by moklick** [comment]
can you create a codesandbox that reproduces this issue? There must be something off with your code 

[can you create a codesandbox that reproduces this issue? ](https://codesandbox.io/s/competent-feather-j2pyvz?file=/src/Flow.js:242-338)

**Comment by taylorrobert** [comment]
@moklick Finally figured it out... I was instantiating the flow within the the <Routes> tag. When I took it out of the router, it worked just fine, even though it's the same control being instantiated with the same properties... Not sure if it's a bug or not in how it interacts with routing, but my issue is fixed for now. Thanks.
