### ISSUE TITLE
onSelectionEnd does not trigger with ctrl-click mode

### ISSUE THREAD

**Issue by anovazzi1** [wbkd/react-flow#3406]
### Describe the Bug

every time I select nodes with the ctrl button pressed and click on each node for selection the onSelectionEnd hook never triggers, just when I select dragging the mouse over the nodes.

### Steps to Reproduce the Bug or Issue

1. add some function on onSelectionEnd on flowProps
2.  select the nodes by clicking on each holding the ctrl button.
3. nothing happens
4

### Expected behavior

onEndSelection triggers on the end of the process or everyTime the selection changesat

### Platform

- Ubuntu 22.04 lts
- 11.8.3

**Comment by moklick** [comment]
The `onSelectionStart` and `onSelectionEnd` event handlers are meant for the selection box. If you want to track a multiselection you need to use `onSelectionChange` https://reactflow.dev/docs/api/react-flow-props/#onselectionchange
