### ISSUE TITLE
Allow Custom Selection Box Component

### ISSUE THREAD

**Issue by andrewkrippner** [wbkd/react-flow#3407]
### Please describe the feature that you want to propose

It would be nice if we could provide React Flow with a custom component to be used for the selection box, similar to how we can define custom components for nodes and edges. My use case would be to wrap the div with a context menu target so a right-click on the box could provide a menu to delete all the selected nodes.

**Comment by moklick** [comment]
Hey @andrewkrippner 

that's not necessary. As you can see in this example, you can use `onSelectionContextMenu` in combination with the `<NodeToolbar />` for that https://codesandbox.io/s/tender-lewin-4dxn4w?file=/src/Flow.js:1550-1603

The `<NodeToolbar />` is just as a convenient helper here, but you can also use your own component.
