### ISSUE TITLE
[svelte-flow] dragging outside the specified dragHandler pans the flow

### ISSUE THREAD

**Issue by peterkogo** [wbkd/react-flow#3413]
### Describe the Bug

...

### Steps to Reproduce the Bug or Issue

1. Create a node with a custom drag handler
2. Try to drag the node outside the draghandler (but inside the node itself)

### Expected behavior

...

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
...

**Comment by moklick** [comment]
fixed in 0.0.21
