### ISSUE TITLE
Duplicate edges not clearing out

### ISSUE THREAD

**Issue by sardormajano** [wbkd/react-flow#3414]
### Describe the Bug

Hi react-flow team,

When I pass new `nodes` and `edges` down `ReactFlow` component, it is not able to clear the old `edges` - keeps rendering them along with new ones, but without nodes.

It should also be noted, that in our old `edges`, in some cases there are duplicate edges - they have the same target, source and id. Don't get me wrong, but I think it must be fixed on both sides - us filtering out duplicate edges, and you guys clearing out old edges regardless of duplicates.  

### Your Example Website or App

https://codesandbox.io/s/serene-sara-rgxzry?file=/src/Components/Flow.js

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/s/serene-sara-rgxzry?file=/src/Components/Flow.js
2. Look closely into `initial-elements.js` and `eventual-elements.js`. As their names suggest, initial elements show first, and then the graph switches to eventual ones. `initial-elements.js` has a set of `nodes` and `edges` where there is 1 duplicate edge (`id: "ia-b"`). 
3. Refresh the page - the application starts off with `initial-elements.js` and switched to `eventual-elements.js` 2 seconds later.
4. You can still see the old `ia-b` edge in the graph. 

### Expected behavior

When a new set of `nodes` and `edges` is fed into react-flow, it must delete the old onesa

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/9404229/787ddf06-3b80-4da0-a2a6-548f6ffcb1d1)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by chrtze** [comment]
Hi @sardormajano, this error occurs because `initial-elements.js` and `eventual-elements.js` contain edges with similar `id` properties (`ia-b` and `e1-2`). The ids of the nodes and edges need to be unique at all times for React Flow to work properly. Here is an adjusted sandbox: https://codesandbox.io/s/practical-kate-h3lwly?file=/src/initial-elements.js:1395-1413

Please reopen if this error persists.

**Comment by sardormajano** [comment]
@chrtze please read the description carefully. I am aware that it works as expected when there is no duplicate edge, but when there is, it must either silently keep working properly or fail. Showing orphan edges can't by an expected behavior in any way.

**Comment by moklick** [comment]
@sardormajano you are breaking React and should get a warning in the dev tools that describes the issue:

> Encountered two children with the same key, `dupliate-edge-key`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted ...

This describes the issue and gives you a hint how to fix it.

**Comment by sardormajano** [comment]
@moklick is react-flow behavior consistent with react behavior?

1. pass down an array of components with duplicate ids to react - it gives a warning, but still renders
2. pass down a new array of components to react - it REMOVES ALL OLD components, and renders new ones (no carry-overs)

So no, it's not consistent with react.
