### ISSUE TITLE
nopan doesn't work when used with panOnScroll

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#3418]
### Describe the Bug

"nopan" class name doesn't work when used with `panOnScroll`

### Steps to Reproduce the Bug or Issue

1. add "nopan" to element x
2. try to pan over element x
3. it pans

### Expected behavior

nopan should work as expected

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
fixed in 11.9.0

**Comment by gzzhanghao** [comment]
broken in 12.4.4 again
