### ISSUE TITLE
Error occurs when attempting to delete a node that has child nodes under certain conditions

### ISSUE THREAD

**Issue by asfman** [wbkd/react-flow#3432]
### Describe the Bug

When node A in reactflow has the `parentNode` property, if the node B pointed to by `parentNode` has an index position greater than node A in the `nodes` array, an error will be thrown when node B is deleted: `throw new Error(`Parent node ${node.parentNode} not found`)`.

### Example Website

https://openai-red.vercel.app/reactflow

### Steps to Reproduce the Bug or Issue

1. go to https://openai-red.vercel.app/reactflow
2. click "change nodes order".
3. delete "parent node 1"
4. reproduce the error "Error: Parent node 1 not found"

### Expected behavior

No matter whether I change the order of nodes or not, deletion should not result in an error.

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/169468/b39b098e-a18f-4431-b398-accda24c2e30

The error occurs when I change the order of nodes and place the parent node after the child node.

### Platform

- OS: macOS
- Browser: Chrome
- Version: Version 116.0.5845.179

**Comment by asfman** [comment]
https://github.com/wbkd/react-flow/pull/3433

**Comment by moklick** [comment]
As explained in the docs, the nodes array has to be sorted when you are working with subflows.
