### ISSUE TITLE
expandParent is not compatible extent: 'parent'

### ISSUE THREAD

**Issue by bodinsamuel** [wbkd/react-flow#3434]
### Describe the Bug

Pretty much the title, when a node has both option `expandParent: true` and `extent: "parent"` only the later will be used.
Which might be a fair choice, but it's not documented and no warning in the console.

Proposed solutions: 
- Update the types so the options are mutually exclusive (not possible to set them at the same time) 
This is nice in term of IDE but might confuse the user looking for the option
- Update the doc saying both options are incompatible
- Warn when both options are set
- Let `expandParent` always act when specified. One could argue that if the parent expand then `extent: parent` is always respected so no surprises.

Or all at the same time :D

### Your Example Website or App

https://stackblitz.com/edit/react-ts-c5y34b?file=Flow.tsx

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
That's a good point. We will add it to the docs.

**Comment by moklick** [comment]
I also agree that expandParent should just work because it doesn't violate the extent parent option.

**Comment by bodinsamuel** [comment]
Amazing thanks for the quick PR <3

**Comment by moklick** [comment]
you can now use both options together since `extent: parent` doesn't violate `expandParent: true`.
