### ISSUE TITLE
`panOnDrag={false}` doesn't work with middle mouse over a node

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#3445]
### Describe the Bug

If you set `panOnDrag={false}`, you can still pan over a node with middle mouse.

### Steps to Reproduce the Bug or Issue

...

### Expected behavior

...

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
fixed in 11.9.0

**Comment by alexkrolick** [comment]
It looks like this regressed. Seeing this on v12.3.5
