### ISSUE TITLE
defaultEdgeOptions not used while dragging edge

### ISSUE THREAD

**Issue by dbeckwith** [wbkd/react-flow#3452]
### Describe the Bug

I used the `defaultEdgeOptions` prop to set the default style of edges to `{ type: 'smoothstep', animated: true }`, which works for actual edges in the graph, but it doesn't seem to apply to edges that are being "edited", such as when creating a new edge or updating an existing edge (while you are dragging one end of the edge with the pointer). While editing an edge, it uses the default-default style of `{ type: 'bezier', animated: false }`.

### Steps to Reproduce the Bug or Issue

1. Set up a basic `ReactFlow` element with at least editable edges.
2. Set the `defaultEdgeOptions={{ type: 'smoothstep', animated: true }}` prop on `<ReactFlow>`.
3. Start creating a new edge, see that it uses the "bezier" style and is not animated.
4. Finish creating the edge, see that it now uses the "smoothstep" style and is animated.

### Expected behavior

The `defaultEdgeOptions` should apply to edges while being edited.

### Platform

- OS: Linux
- Browser: Firefox
- ReactFlow: 11.8.3

**Comment by bcakmakoglu** [comment]
`defaultEdgeOptions` only apply to *edges* - what you're talking about is the *connection line* which uses a separate set of props.
[You can find those here.](https://reactflow.dev/docs/api/react-flow-props/#connection-line).

**Comment by moklick** [comment]
It's a bit confusing, but as @bcakmakoglu pointed out, we differentiate between edges and a connection line.

**Comment by dbeckwith** [comment]
Ah okay, I see they aren't really edges then, I guess that makes sense. Thank you!
