### ISSUE TITLE
Custom Handles to allow for Greater Control of Handle Specific Behaviors

### ISSUE THREAD

**Issue by enJerneering** [wbkd/react-flow#3476]
### Please describe the feature that you want to propose

Currently we have access to the <Handle /> component with the ability to customize the styling, denote Handle ID, and set the type. An extension of this feature would be supporting Custom Handles in the same way that Custom Nodes are dealt with, using a set of standard props that get passed into the Handle for usage in the custom component. A new HandleTypes will be required with a corresponding React Flow Instance prop to introduce the custom handles to the underlying React Flow system. This addition will allow for greater control over the Node instance on the Flow, providing deeper integration opportunities.

**Comment by bcakmakoglu** [comment]
What exactly would this improve though? Can you give an example what this "CustomHandle" is supposed to do?
Technically you can already customize handles as much as you want, so I don't really see what this proposal is going for 🤔

**Comment by enJerneering** [comment]
I am able to style the handle with CSS and Tailwind (sort of), but when I need to append custom data or properties to the handle through configuration, the current setup gets us close. This can be worked around by storing handle data on the Node 'data' field through an event handler on the Node, as long as the Handle onClick is an exposed option. When I want to fetch data, maintain state, or embed custom hooks on the Handle.. I do not find any documentation that gets me there. If this all has already been solved, I am curious to see how you embed the custom data and hooks onto the handle.

**Comment by bcakmakoglu** [comment]
But how would a custom handle component that you pass to ReactFlow solve your issue of needing to have some handle-related data?
Handles are not "elements" that are stored in the state, hence there is no `handle.data` option.

You can simply wrap your handle in basically an "empty" div and add whatever listeners, like `onClick` on there.

If you're looking for an example of a "Custom Handle", the [Connection Limit Example](https://reactflow.dev/docs/examples/nodes/connection-limit/) uses one.

**Comment by JerrodSmithFlex** [comment]
Okay, I see where you are coming from with handles not being elements in state. The example you have provided does help me out. Ultimately, I wanted to store counter variables onto a dynamic # of handles on a custom node that keeps track of iterations in a process flow. Then having that data be available from the instance.toObject() as a handle.data property of the Node, so I don't have to manage a busy Node.data, which is probably lazy of me. Given your insight, I believe I can get what I want from the examples.
