### ISSUE TITLE
Add support for "bidirectional" Handle Type

### ISSUE THREAD

**Issue by JerrodSmithFlex** [wbkd/react-flow#3477]
### Please describe the feature that you want to propose

The current build of React Flow supports "source" and "target" Handle Types, which handles a majority of use cases. A limitation of this system becomes apparent in the case where the desired design requires bidirectional Handles that allow for both source and target type connections. This Feature Request proposes an addition of a "bidirectional" Handle type to be supported in React Flow. The experts must weigh in, but I believe that the current Edge system can handle this with the "source""sourceHandle" and "target""targetHandle" data fields. This helps a use case in a Process Flow where a common CustomNode component is using a single "fallback" handle on the node that will originate from a node downstream in the flow sequence, and end up on the same "fallback" handle of a separate CustomNode type earlier in the flow.  Hopefully this is a easy-to-implement types as I believe this is an opportunity to enhance the Handle capabilities.

**Comment by bcakmakoglu** [comment]
Are you, maybe, just looking for [`ConnectionMode`](https://reactflow.dev/docs/api/types/#connectionmode)? 

Using `ConnectionMode.Loose` allows you to connect to whatever handles regardless of their `type` (though optimally, you'd just define all of them as `source`).

**Comment by JerrodSmithFlex** [comment]
Ah, ConnectionMode does allow for the behavior, however this seems to be global for all handles when I only want specific handles to have the behavior. By setting the ConnectionMode to Loose globally, the typical connection validation that I still desire would be lost. Is there a way to pass this ConnectionMode as a prop on the Handle instance?

**Comment by bcakmakoglu** [comment]
Well, you can just use `isValidConnection` (which can be used globally, or per handle) to also validate your connections as you wish 😄 

And no, `ConnectionMode` is not usable on a per handle basis.

**Comment by JerrodSmithFlex** [comment]
I see what needs to be done, thank you for the help!

**Comment by jpfortier** [comment]
If I use `ConnectionMode.Loose` should this error still get thrown?

```
Couldn't create edge for source handle id: "env_id-left", edge id: myEdgeId. Help: https://reactflow.dev/error#008 
    at EdgeRenderer (/reactflow.js)
```

My nodes can have both parent and child (source and target) edges attached to them.
