### ISSUE TITLE
`nodeDragThreshold` delay selection unexpectedly

### ISSUE THREAD

**Issue by FindDefinition** [wbkd/react-flow#3487]
### Describe the Bug

If I set `nodeDragThreshold` to a positive number, the selection delayed unexpectedly, single click event can't trigger selection (both `selected` in node prop and `onSelectionChange`) anymore. Is this expected?

### Your Example Website or App

https://codesandbox.io/s/quiet-snow-f53wt4?file=/CustomNode.jsx:1407-1485

### Steps to Reproduce the Bug or Issue

click the custom node, then drag the custom node.

### Expected behavior

selection can be triggered by click event

### Platform

- OS: Linux
- Browser: Chrome
- Version: 117.0.5938.92

**Comment by moklick** [comment]
🧐 what is happening here? And why is this only an issue for custom nodes? I will check it! In the meantime you can set ` selectNodesOnDrag={false}` as a workaround.

**Comment by moklick** [comment]
Thanks! This is fixed in 11.9.3
