### ISSUE TITLE
قم بدعوة الأصدقاء للإنضمام إلى باي نتورك

### ISSUE THREAD

**Issue by Salaheldean** [wbkd/react-flow#3489]
الباي هي عملة رقمية جديدة تم تطويرها من طرف فريق من حاملي الدكتوراه من جامعة ستانفورد، مع أكثر من 
47 مليون فرد حول العالم. للمشاركة معنا في باي ، إختر هذا الرابط https://minepi.com/01202028263 وإستخدم إسم المستخدم الخاص بي 01202028263 ككود دعوة

**Comment by moklick** [comment]
this is spam
