### ISSUE TITLE
removeElements explanation needed

### ISSUE THREAD

**Issue by Harish-Hk** [wbkd/react-flow#349]
hey there,
I'm new to this wbkd react-flow
I was wondering how do I remove a node.

the docs say, it needs two arrays: elementsToRemove and Elements
removeElements
Returns elements without the elements from elementsToRemove

removeElements = (elementsToRemove: Elements, elements: Elements): Elements

Im pretty confused how to use it.

here's what I'm trying to do.

Instead of nodes, im taking functional components and passing the functions via props.

> `function Cardcomp(props) {
>   return (
>     <div className="card">
>       <div className="card-header">
>         <strong>Text Prompt</strong>
>       </div>
>       <div className="card-body">
>         Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea, quas impedit reiciendis ad distinctio exercitationem.
>         <div className="prompt-options mt-3">
>           <button className="btn btn-outline-primary btn-sm" onClick={props.addNew}>
>             <i className="fa fa-plus mr-2"></i>
>               Add
>           </button>
>           <button className="btn btn-outline-danger btn-sm ml-2" onClick={props.remove}>
>             <i className="fa fa-minus mr-2"></i>
>               Remove
>           </button>
>         </div>
>       </div>
>     </div>
>   );
> }`
> 

`this.state = {
      modal: false,
      elements: [
        { id: '1', data: { label: <PromptComponent addNew={this.addNewNode} **remove={this.removeNode}** /> }, position: { x: 400, y: 10 }, style: this.basicNodeStyles },
        { id: 'e1-2', source: '1', target: '2', animated: true },
        { id: 'e1-3', source: '1', target: '3', animated: true },
        { id: '2', data: { label: <div><Cardcomp addNew={this.addNewNode} remove={this.removeNode} /></div> }, position: { x: 100, y: 350 }, style: this.basicNodeStyles },
        { id: '3', data: { label: <PromptComponent addNew={this.addNewNode} remove={this.removeNode} /> }, position: { x: 750, y: 350 }, style: this.basicNodeStyles },
        { id: 'e3-4', source: '3', target: '4', animated: true },
        { id: '4', data: { label: <div><Cardcomp addNew={this.addNewNode} remove={this.removeNode} /></div> }, position: { x: 500, y: 650 }, style: this.basicNodeStyles },
        { id: 'e3-5', source: '3', target: '5', animated: true },
        { id: '5', data: { label: <div><Cardcomp addNew={this.addNewNode} remove={this.removeNode} /></div> }, position: { x: 1100, y: 650 }, style: this.basicNodeStyles },
      ]
    };`

> `  <ReactFlow
>             elements={this.state.elements}
>             onElementsRemove={this.removeNode}
>             onConnect={this.onConnect}
>             onNodeDragStart={this.onNodeDragStart}
>             onNodeDragStop={this.onNodeDragStop}
>             style={this.graphStyles}
>           />
> `

`removeNode = (node) => {
    console.log('removeNode called', node)
    this.setState({
      elements: removeElements(node, this.state.elements)
    })
  }
`
in the above function => the node needs to be an array, how do I get its value?
when I try to log it, it shows me a class with some values like bubble, target, clientX, clientY etc.

Can anyone help me understand how its done, 
or an example would suffice.
thanks in advance

**Comment by moklick** [comment]
Hey @Harish-Hk 

better docs are on our list ;)

The function takes two parameters (both are arrays of Elements). The first parameter includes the elements you want to remove and the second one contains all elements of your flow. The functions then returns a list of all elements that are still part of your flow.
You can't use your `removeNode` function for the internal `onElementsRemove` callback and for your `CardComp` `remove` function. For the `CardComp` function you should implement something like:

<button onClick={() => props.addNew([props.node])}>Add</button>

As described above the `removeElements` function expects an array of elements. When you call it with a normal `onClick` handler it gets the mouse event.

Does it help?

**Comment by Harish-Hk** [comment]
thank you for the response @moklick 
I was able to implement the addNew function like this,

`onClick={props.addNew}`


 ```
 addNewNode = () => {
    let tempElem = this.state.elements
    tempElem.push(
      {
        id: (this.state.elements.length + 1).toString(),
        data: {
          label: <PromptComponent />
        },
        position: { x: Math.random() * window.innerWidth, y: Math.random() * window.innerHeight },
        style: this.basicNodeStyles
      }
    )
    this.setState({ elements: tempElem })
  }
```



 where I'm calling the the callback functions via props,
I'm using my custom functions in which I'm calling the callback API functions.

but im trying to know how to send array of elements to onElementsRemove callback.

**Comment by Harish-Hk** [comment]
sorry if I'm not clear,
when I click on remove button in the image below,
Here's the actual error I'm facing.
elementsToRemove.map is not a function.

![nodeError](https://user-images.githubusercontent.com/28500085/87944521-21a03a80-cabd-11ea-93f6-7e85e0bcdb0b.JPG)
![nodeError1](https://user-images.githubusercontent.com/28500085/87944527-2369fe00-cabd-11ea-8948-79660c5fee81.JPG)

**Comment by moklick** [comment]
when you call `removeElements` you always need to pass arrays of elements. So if you only want to remove one specific node, you can do: `removeElements([node], this.state.elements)`.

Can you show the code where you are using it?

**Comment by moklick** [comment]
I guess because you are doing `onClick={removeNode}` somewhere. You need to do something like `onClick={() => removeNode(node)}`. You only need the id at that point. So you could pass the id as a prop and then do `onClick={() => removeNode({ id: props.id })}`
