### ISSUE TITLE
Node handle drag not working with panOnScroll

### ISSUE THREAD

**Issue by aleib** [wbkd/react-flow#3499]
### Describe the Bug

If the canvas is set to `panOnScroll=true` node handles aren't draggable anymore.

Noticed in a recent update maybe `v11.9.3` (or `v11.9.x`), works in `v11.8.3`
Not sure if this is intentional or bug.

### Your Example Website or App

https://codesandbox.io/s/panonscroll-cant-drag-handle-8n53ck?file=/App.js

### Steps to Reproduce the Bug or Issue

Try to drag a node handle.

### Expected behavior

Connector should still appear.

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/4955513/db4aa371-5f5f-42e6-9102-244b65a0321d

### Platform

- OS: macOS
- Browser:Chrome
- Version: v11.9.3

**Comment by moklick** [comment]
fixed in 11.9.4
