### ISSUE TITLE
how to make flow group?

### ISSUE THREAD

**Issue by Eye12** [wbkd/react-flow#350]
how to make flow group?

**Comment by moklick** [comment]
What do you mean with flow group?

**Comment by Eye12** [comment]
how to make two nodes module become a group

**Comment by Eye12** [comment]
A container contains two nodes. The two nodes can be dragged to connect

**Comment by moklick** [comment]
You can select multiple elements while pressing shift but you can not group elements data-wise.

**Comment by moklick** [comment]
This feature is not planned for now.

**Comment by moklick** [comment]
We now collection feature ideas in the "Discussions/New Features" section #1022
