### ISSUE TITLE
After migrating to V11 I'm getting this error

### ISSUE THREAD

**Issue by Faizantanveer550** [wbkd/react-flow#3505]
### Describe the Bug

I just upgraded my Reactflow version.

### Steps to Reproduce the Bug or Issue

Just upgraded Reactflow version

### Expected behavior

It shouldn't give this error

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/41286767/5f2eb4d2-2498-4301-9563-d8cd33f25027)

### Platform

- OS: Windows
- Browser: [e.g. Chrome, Safari, Firefox]
React 17
React script 4.0.3

**Comment by moklick** [comment]
We are not transpiling React Flow anymore. If you are working with an older version of create-react-app or webpack 4 for example, you need to configure babel, so that the reactflow package gets transpiled. You can find a more detailed answer here #2453
