### ISSUE TITLE
 Uncaught Error: The React Flow parent container needs a width and a height to render the graph.

### ISSUE THREAD

**Issue by Harish-Hk** [wbkd/react-flow#351]
Hey there,

I'm getting this error, though Im using `container` or `container-fluid` classes for the react flow parent container.
I'm using a bootstrap tabbed Approach, 
and the React flow is used in second tab.
Im getting this issue if I load/ setActive tab to the first tab.
and if im loading the second tab(react flow) then its not givin me this error.

  ```
                 <div className="container-fluid">
                    <ReactFlow
                      elements={this.state.elements}
                      onElementsRemove={this.removeNode}
                      onElementClick={this.elementClick}
                      onConnect={this.onConnect}
                      onNodeDragStart={this.onNodeDragStart}
                      onNodeDragStop={this.onNodeDragStop}
                      style={this.graphStyles}
                    />
                  </div>
```
even if I explicitly set the container height and width, Im still facing the error.

**Comment by moklick** [comment]
Hey @Harish-Hk 

this is not related to react-flow. Maybe you are trying to render the Flow component before the parent gets a height or is visible.
