### ISSUE TITLE
onNodeHandleMouseEnter and onNodeHandleMouseLeave

### ISSUE THREAD

**Issue by simonharrer** [wbkd/react-flow#3510]
### Please describe the feature that you want to propose

I can register a callback for `onNodeMouseEnter` and `onNodeMouseLeave` which is great. But when having multiple handles within that node, I want to highlight different parts of the graph depending on whether which handle the user hovers. But there is no callback available for hovering over a handle.

I propose to have two new callbacks available at the <reactflow> component:
- `onNodeHandleMouseEnter`
- `onNodeHandleMouseLeave`

Or this something like this already available? Or is there a workaround to get this functionality?

**Comment by bcakmakoglu** [comment]
You could simply wrap your handle in a div and bind mouse over event listeners on there.

```jsx
<div
  onMouseEnter={() => console.log("mouseenter")}
  onMouseLeave={() => console.log("mouseleave")}
>
  <Handle
    type="target"
    position={targetPosition}
    isConnectable={isConnectable}
  />
</div>
```

**Comment by moklick** [comment]
This is already possible. You don't even have to wrap the handles, but you can pass the event handlers directly like:

```js 
<Handle
  type="target"
  position={Position.Top}
  onMouseEnter={onMouseEnter}
  onMouseLeave={onMouseLeave}
/>
```

https://codesandbox.io/s/condescending-yalow-3mnjnq?file=/src/CustomNode.tsx:535-607
