### ISSUE TITLE
react-flow and content security policy 

### ISSUE THREAD

**Issue by kpetrov92** [wbkd/react-flow#3520]
I'm using react-flow and I need to implement CSP header that allows style tags to be executed if they have nonce. 
For that goal, I'm using CacheProvider. For all other styles far it works out of the box. 

Where are styles loaded after import? 
The current version of the library: 11.8.3
import styles in components like this:
`import 'reactflow/dist/style.css'; `

**Comment by moklick** [comment]
Hey @kpetrov92 we are not importing any styles. You need to do that in your app. How does your setup look like?

**Comment by kpetrov92** [comment]
Yes, I did that In the app. I found that when it was a dev build, the imported CSS ended up like a style tag. For production, build css ended up like link tag with static CSS. So, it has nothing to do with the library.
