### ISSUE TITLE
Scrolling a page make the flow zoom in and zoom out

### ISSUE THREAD

**Issue by dhruvchandak30** [wbkd/react-flow#3545]
### Describe the Bug

I am facing this issue, I have made a react flow component where the div's width is 100% and Height is around 30rem.
When I scroll the page and my cursor is on that particular div it makes the react flow element zoom in and out, which I dont wish to. I want it to be fixed. Is there anything which I could do or I have missed something in the documentation.

### Steps to Reproduce the Bug or Issue

Create any React-Flow element

### Expected behavior

It should Not zoom when I scroll.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
That's the default behaviour. You can turn it off by setting `zoomOnScroll={false}` https://reactflow.dev/docs/api/react-flow-props/#zoomonscroll
