### ISSUE TITLE
Performance issues with dotted background when zoomed out

### ISSUE THREAD

**Issue by emielwit** [wbkd/react-flow#356]
Hey,

When i use the build in background component with dots `<Background color="#888" gap={16} />` and i zoom out the performance of moving the canvas drops.

**Comment by moklick** [comment]
Hi @emielwit

we are rendering a SVG with a path node for the background. It seems that the calculations or the rendering are taking too long. We will check this.

**Comment by moklick** [comment]
I created a new branch "background-performance" where I am using a repeating inline SVG as a background image. It works fine in Chrome but unfortunately it's flickering in Firefox. Maybe we need another solution here or can we fix the flickering somehow?

**Comment by moklick** [comment]
I think I found a way. I am now using the same inline SVG and change the `background-position`. There is no more flickering in Firefox or Safari and it's rendering faster.

**Comment by moklick** [comment]
can you confirm @emielwit ?

**Comment by emielwit** [comment]
Yes much better thank you!
