### ISSUE TITLE
Event handler for moving the graph

### ISSUE THREAD

**Issue by aludewig** [wbkd/react-flow#358]
### Hi, it would be really helpful if there was an event handler that fires when you move (or zoom) the graph, so you can save the current transformation of the graph. And of course you would need the option to hand in the transformation of the graph as props so you can render the graph with the saved transformation.

And I have some more ideas for possible add-ons, that would help to customize the graph:
- option to move the graph when scrolling on the mouse (instead of zooming) -> maybe that you can choose if you either want to move, zoom or do nothing when scrolling
- possibility to disable a certain direction for moving, e.g. that you only allow to move the graph vertically
- when mouse scrolling triggers to move the graph, you could add the option to zoom on scroll+keypress

**Comment by moklick** [comment]
Hey @aludewig 

this is a good input, thanks 👍 

There is already an `onMove` handler but no `onZoom` handler. The `onMove` callback does not receive any params for now. I could change this to the current `transform` variable. We could also add new prop types like `initialCenter` (x,y) and `initialZoom`. What do you think about that?

I also like the other ideas but could you open a new issue for that? it would make this a little bit more organized, I think.

**Comment by aludewig** [comment]
Oh, I actually didn't see that handler - it's kind of what I need but as I see, it will fire a lot of times during moving the graph. I think something like `onMoveStop` would be helpful as I'd like to save the transformation in the redux store and otherwise it might generate too much overhead. Yes, it would be great if that callback receives the current `transform` variable.
A prop type like `initialCenter` or `initialTransformation` would be great! So that handing in the transformation values, that you receive by the `onMoveStop` handler, will reproduce the same position of the graph! And I think there already is a prop type like `initilalZoom` (-> `defaultZoom`)

Sure, I will do that 🙂

**Comment by moklick** [comment]
Oh! How could I forget about the `defaultZoom` prop type 🙈

I will add a `defaultPosition` prop and a `onMoveEnd` and `onZoomEnd` handler.

**Comment by aludewig** [comment]
Thanks! ☺️

**Comment by moklick** [comment]
Hey @aludewig 

the new props are released in v4.5.0.

I added `defaultPosition`, `onMoveStart` and `onMoveEnd`. They are triggered when transform changed (x,y or zoom).

**Comment by aludewig** [comment]
@moklick Wow, thanks for adding that so fast!

But as it seems the `defaultPosition` prop only applies on the first render of the graph.

In my case I have different 'files' that each include a graph and I want to independently save the position of the graph (what now is possible with `onMoveEnd`) and then want to reproduce that saved transformation when I switch between files. I thought that I could save the transformation in the redux store with onMoveEnd (which works!) and then I could just hand in the saved transformation as `defaultPosition`, which doesn't seem to work. Do you know what I mean?
Maybe if it's not possible to do that with the props, it would be an option to add a function for the `reactFlowInstance` that sets the transformation, so you could set the transformation in the `onLoad` handler?
Hope you understand my problem 😄

**Comment by moklick** [comment]
Hey @aludewig 

that's correct. Now it's an uncontrolled component like when you use `defaultValue` for an input element. It's only the default and then the component itself controls the changes. We could add a `position` prop type but then you would have to apply all changes (panning/ zooming) by yourself.  

I added a `setTransform` function to the reactFlowInstance. This should work for you. You could also use the internal actions with a helper component (must be a children of your ReactFlow component) like this:

```javascript
import React, { useEffect } from 'react';
import { useStoreActions } from 'react-flow-renderer'

const TransformUpdater = ({ x, y, zoom }) => {
  const setTransform = useStoreActions(a => a.setInitTransform);

  useEffect(() => {
    setTransform({ x, y, k: zoom })
  }, [x, y, zoom])
});
```

**Comment by aludewig** [comment]
That works! I didn't know there also is an useStoreAction hook - maybe you could add that to the documentation 🙈 
Thanks for your help! :)

**Comment by moklick** [comment]
cool :) The `setTransform` function comes with the next release.. but I think you don't need it anymore. Yep, I will add it to the docs.

**Comment by moklick** [comment]
The `setTransform` function is released in v.4.6.0

**Comment by adammo94** [comment]
@moklick Can't find onZoomEnd handler, was it added?

**Comment by moklick** [comment]
You can use the `onMoveEnd` event for that. The second param is the viewport `{ x: number, y: number, zoom: number }`.
