### ISSUE TITLE
Option to disable selectable for edges

### ISSUE THREAD

**Issue by emielwit** [wbkd/react-flow#360]
Hey,

Is there a setting like for nodes to set `selectable: false` or do this on a higher level `selectableEdges={false}`?

**Comment by moklick** [comment]
There is no edge option `selectable`. Do you need to set a specific edge to selectable false? If not you could use the `elementsSelectable` option.

**Comment by emielwit** [comment]
I found a solution, i have set `elementsSelectable` to `false` and added `selectable: true` to the nodes that needs to be selectable.
