### ISSUE TITLE
Bug: onConnect won't be updated

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#372]
`onConnect` is set here:

https://github.com/wbkd/react-flow/blob/991863f2ae0a04a903baa0fe2dd3ab82924db832/src/container/GraphView/index.tsx#L145-L147

It's inside of:

https://github.com/wbkd/react-flow/blob/991863f2ae0a04a903baa0fe2dd3ab82924db832/src/container/GraphView/index.tsx#L139-L166

I think because the code is using `useEffect(() => { }, [ ])` it's only run once. `onConnect` will never be updated.

A fix could be:

```javascript
useEffect(() => { }, [onConnect])
```

or to move calling the `setOnConnect` function outside.

This issue is missing a concrete example. Let me know if you have trouble reconstructing the bug and I'll try to come up with an example.

**Comment by moklick** [comment]
Hey @andys8 

I never thought that one would need to change this function. What is the use case for this? I could put it into it's own useEffect hook.

**Comment by andys8** [comment]
Use Case: One can select different graphs that will be shown. If the selection changes the graph will be changed just fine. Any new connection is added somewhere, but depending on the selected graph and therefore using the graph name in onConnect. But onConnect never gets updated.

There might be workarounds, but it's quite unexpected. Therefore the fix :)

**Comment by moklick** [comment]
Are the ids of the elements unique across all graphs?

**Comment by andreas-ebot7** [comment]
> Are the ids of the elements unique across all graphs?

Yes, I think so.

> Your fix is released in v.4.7.1

Thanks :)
