### ISSUE TITLE
need help with using elements array in a custom node handler

### ISSUE THREAD

**Issue by MatthieuJnon** [wbkd/react-flow#376]
Hi, I have a custom node with a plus button attached to the node. I want the button to add a new node right below the one with the plus.

I'm creating the handler in the same way as in your example, [Custom node example](https://github.com/wbkd/react-flow/blob/master/example/src/CustomNode/index.js)

This issue is that, for me to add a Node, I have to pass the addNode helper an array of the `elements` state, but because of the way the handler is passed, `elements` is always equal to `[]` (because of closures, the function is passed only when it goes through the useEffect, and thus captures it's surrounding scope at that time). 

Do you have any idea about how to use the `elements` array state in a custom node handler ? Thank you for your help

**Comment by moklick** [comment]
Hey @MatthieuJnon 

could you open a code sandbox or something like that? This makes it easier to understand your problem.

I am not sure if I get it right but maybe you could use the internal state in your custom node like this:

```
import ReactFlow, { useStoreState } from 'react-flow-renderer';

const CustomNode = () => {
  const nodes = useStoreState(state => state.nodes);
  // if you also need the edges: 
  // const elements = useStoreState(state => state.elements); 

  console.log(nodes);

  return <>custom node content</>:
}
```

**Comment by MatthieuJnon** [comment]
Ok, so I've found a way to have an up to date handler using this method

```jsx
<ReactFlow
    elements={elements.map((element) => {
        if (!element.start) {
            return {
                ...element,
                data: {
                    ...element.data,
                    onAddChild: handleAddChild,
                },
            };
        }
        return element;
    })}
    snapGrid={[10, 10]}
    snapToGrid
    nodeTypes={nodeTypes}
    onNodeDragStop={handleNodeMove}
>
```

But it seems suboptimal to me ? Do you know of any  better way ?

**Comment by MatthieuJnon** [comment]
Thank you for your answer, I'm creating a sandbox right now to share my issue

**Comment by MatthieuJnon** [comment]
https://codesandbox.io/s/modest-wiles-o5z9q?file=/src/Graph.jsx

Here you go, you can see on the console that when you click on the icon next to the node, it doesn't have the up to date elements

**Comment by moklick** [comment]
You can pass a function to `setElements` like we are doing it in our [custom node example](https://github.com/wbkd/react-flow/blob/master/example/src/CustomNode/index.js#L25). The first parameter is the current `elements` value. Then you could do:

```javascript 
const handleAddChild = node => {
    setElements(els => {
      // do something with els
      
      return els;
    });
  };
```

Or you could receive the current elements with the way described above and pass it to the `handleAddChild`function:

```javascript
import { useStoreState } from 'react-flow-renderer';

const StartNode = props => {
  const elements = useStoreState(state => state.elements); 

  return (
    <>
      <span>Start of your form</span>
      <Icon name="plus circle" onClick={() => props.data.onAddChild(elements, props)} />
    </>
  );
};
```

**Comment by MatthieuJnon** [comment]
Thank you so much, I've been coding with hooks for > 1 year, and I didn't event know you could pass a function to the set state method...
Thank you for your reactivity and for your help
