### ISSUE TITLE
Events for creating new edge

### ISSUE THREAD

**Issue by pitkes22** [wbkd/react-flow#380]
Hi, I am trying to add custom behavior when a user starts (and stops) creating a new edge. 

Right now there is only `onConnect` event that fires when the connection is created. I think that it would be great to add events that will fire when a user starts and stops creating the new edge. For example something like `onEdgeDragStart({ source })` and `onEdgeDragStop()`. Stop event is needed because `onConnect` is not fired when a user stopped dragging but did not created a new edge.

**Comment by moklick** [comment]
Hey @pitkes22

thanks for your input! 

I added the handlers `onConnectStart({ nodeId, handleType })` and `onConnectStop()`. It's released in v4.9.0

**Comment by pitkes22** [comment]
Awesome! Thank you for the fast response and for your work on this absolutely awesome library :+1:
