### ISSUE TITLE
onConnectStop() not giving us Position where the user stopped dragging

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#384]
@moklick can we get the position on the canvas when onConnectStop event is triggered?

**Comment by moklick** [comment]
Hey @agarwal00s 

for now it's not possible. We could pass the normal mouse event. Would it help?

**Comment by agarwal00s** [comment]
@moklick if we can get an event which tells us the current mouse position, that will also work.

**Comment by moklick** [comment]
We might should pass the mouse event for all event handlers.. I will think about it.

**Comment by agarwal00s** [comment]
@moklick any update ?

**Comment by moklick** [comment]
We will continue the discussion in issue #399

**Comment by moklick** [comment]
released in v5.0.0

**Comment by agarwal00s** [comment]
@moklick which key values in mouseEvent gives us the position?
Actually I want to create a node whenever the user starts a connection and drop it in the canvas, need that position to create a new node
