### ISSUE TITLE
How to implement drag and drop?

### ISSUE THREAD

**Issue by pitkes22** [wbkd/react-flow#391]
Hi, I am trying to figure out how to implement drag and drop functionality.

Currently, I'm using HTML drag events. So I have  `draggable="true"` on the element that should be draggable and I am listening to `onDrop` event on wrapper component of the `ReactFlow` component (because this event was not triggered when I tried to listen for it on ReactFlow component). By doing this I am able to get a position where on the ReactFlow component was element dropped. 

Now I only need to transform this position into position inside ReactFlow "canvas".  For that, I found the `project` function in `src/utils/graph.ts` that I think does exactly what I need. But I have a problem with importing it because it is not exported from `react-flow-renderer` and when I tried to import it from `react-flow-renderer/dist/utils/graph.ts` I got error `Module not found: Can't resolve 'react-flow-renderer/dist/utils/graph' in '...'`.

I would like to ask if my approach to this is right. 
Also if `project` function really does what I think, if it would be possible to export it directly from  `react-flow-renderer`  as all other utils functions are?

**Comment by moklick** [comment]
Hey @pitkes22 

you are right. You can use the `project` function. We can't just export it, because it relies on the store of the specific react flow component. You get a `reactFlowInstance` when you are using the `onLoad` function. The `reactFlowInstance` exposes the `project` function you can use for getting the translated position. Let me know if it works for you.

**Comment by pitkes22** [comment]
It works, my bad I didn't realize it was available in `reactFlowInstance`.

One small problem I encountered is that in order to store the instance in the state, I needed its type. But `OnLoadParams` interface is not exported so I have to use `Parameters<OnLoadFunc>[0]` which is a little bit wild :smile:

**Comment by moklick** [comment]
Ok, cool! It gets exported in v4.9.1
