### ISSUE TITLE
Scroll the viewport as I draw the line

### ISSUE THREAD

**Issue by Vkrish-Nimmagadda** [wbkd/react-flow#392]
As I draw the line to connect a node that is down below the ViewPort, I want the canvas to scroll automatically so that I could connect to the node (which is down somewhere). 

Is there a known and easy workaround or this ?

Request kind help from someone. 

Cheers,
Krish

**Comment by moklick** [comment]
Since the pane is draggable there is no need for a pane that is higher than the window.

**Comment by Vkrish-Nimmagadda** [comment]
Didnt get that @moklick  !  That is the requirement, like if there is a node that is down below how do we connect it ? Because as I start drawing the line and the node is below, it won't auto-scroll.  How do we do it now ? May be I am missing something.

**Comment by Vkrish-Nimmagadda** [comment]
@moklick  should this is a new feature that we need to build ? Please let me know.

**Comment by moklick** [comment]
Hey @Vkrish-Nimmagadda 

I get it! It was a misunderstanding on my side.
Right now the nodes you want to connect have to be inside the viewport. There is no auto-scroll/auto-drag function yet.

**Comment by Vkrish-Nimmagadda** [comment]
Thank you much @moklick  ! Appreciate it. 

Any quick tips on a decent approach from either you and/or community will help. I will see how to help build that feature.

**Comment by moklick** [comment]
We would be happy if you find a way and do PR :)

**Comment by Vkrish-Nimmagadda** [comment]
Cool .. good ! Thank you @moklick  !

**Comment by moklick** [comment]
This feature is available since v11.5.0
