### ISSUE TITLE
Add or edit elements by using useStoreActions

### ISSUE THREAD

**Issue by fabianstrunz** [wbkd/react-flow#394]
Hello!

Is it possible to add elements by using useStoreActions?

```javascript
const nodes = {...}
const addElement = useStoreActions(store => store.setElements)
const node = {id: uuidv4(), type: 'customNode', data: {label: 'MyCustomNode'}, position: {x: 250, y: 5}}
const newNodes = nodes.concat(node)
addElement(newNodes)
```

I'm using this to add new elements from outside of the `ReactFlow` component, but unfortunately it doesn't work.

Consuming the nodes from outside the `ReactFlow` component does work.

```javascript
const nodes = useStoreState(store => store.nodes)
```

So, is there a way to add elements from outside the `ReactFlow` component? Or am i just doing it wrong :-)

Also, is it possible to edit existing elements?
Let's say i have a custom node with a label and an input field and i want to change the value of the label to the value of the input field. 
Is this possible? Do i have to use useStoreActions to save the changed value in the elements?

Thanks a lot!

Fabian

**Comment by moklick** [comment]
Hey @fabianstrunz 

you always pass the current elements as a prop. You can add or change nodes and edges from outside. You can find an example of how you could add a node in the [empty example](https://github.com/wbkd/react-flow/blob/master/example/src/Empty/index.js#L13-L21) and how you could change nodes in the [stress example](https://github.com/wbkd/react-flow/blob/master/example/src/Stress/index.js#L19-L35) or the [custom example](https://github.com/wbkd/react-flow/blob/master/example/src/CustomNode/index.js#L24-L43).

You don't need to use the internal state or actions. Just update your outside elements array.
