### ISSUE TITLE
When node have multiple outgoing edges all of them highlights when user selects one

### ISSUE THREAD

**Issue by pitkes22** [wbkd/react-flow#397]
When one node has multiple edges going into one other node, and the user selects(clicks) one of them, all of them will become highlighted. All handles in my example have a unique ID and also `onSelectionChange` is called with correct data (only one edge).

![image](https://user-images.githubusercontent.com/10003540/89266240-f3326b80-d635-11ea-972a-0626e4f558d3.png)

Example:
[![Edit nifty-tereshkova-udynb](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-tereshkova-udynb?fontsize=14&hidenavigation=1&theme=dark)

**Comment by pitkes22** [comment]
Also when edges are selected by group selection they are not highlighted. 

![image](https://user-images.githubusercontent.com/10003540/89267405-77d1b980-d637-11ea-821c-c5b372f0c777.png)

**Comment by moklick** [comment]
good catch 👍
