### ISSUE TITLE
Exposing Mouse Events

### ISSUE THREAD

**Issue by namack** [wbkd/react-flow#399]
Following the lead of `onNodeMouse*` and `onNodeContextMenu`, it would be helpful to expose the `MouseEvent` to the developer when something happens on the canvas. I can see this being useful for `onElementClick`, `onNodeDrag*`, `onMove*`, and `onPaneClick`. 

All of these functions (except for `onPaneClick`) already return values, however if we were to follow the pattern set by `onNodeMouse*`, the mouse event argument would come first. Adding this argument consistent with `onNodeMouse*` would cause a breaking change in the application.

I have an immediate need for returning the mouse event for `onPaneClick`. This would not require a breaking change, but I am also willing to add the mouse events to the other actions as well. 

What would be the best way to move forward with this?
Do you agree that exposing these events would be useful to the developer?

I can open a PR that adds the event to `onPaneClick` to allow for a minor release (I should have just exposed this initially 🤦) and then another PR for the other actions, which would require a major release. Or do them all at once! 😄

**Comment by moklick** [comment]
Hey @namack 

I thought about this too and there is another issue #384 regarding this one. I would prefer to do a major update with all handlers updated.

**Comment by moklick** [comment]
released in v5.0.0

**Comment by pitkes22** [comment]
Its abbreviation of `event` to `evt` really needed? It's subjective thing, but I think that word event is short enough to not be abbreviated and also everywhere in DOM and React API it is called `event`.

**Comment by moklick** [comment]
I don't have a strong opinion about that. But you are right, React also uses `event`. I think  I will refactor it I order to use `event` instead of `evt`.
