### ISSUE TITLE
Invalid type of onConnectStop prop

### ISSUE THREAD

**Issue by pitkes22** [wbkd/react-flow#403]
In new version, type of `onConnectStop` is `() => void`, I think it should be  `OnConnectStopFunc`.

https://github.com/wbkd/react-flow/blob/8544f9802fc3766a32836ba72635d0582a702fa5/src/container/ReactFlow/index.tsx#L47

**Comment by moklick** [comment]
thanks! Should work with v.5.1.1

**Comment by bathinaMounika** [comment]
> In new version, type of `onConnectStop` is `() => void`, I think it should be `OnConnectStopFunc`.
> 
> https://github.com/wbkd/react-flow/blob/8544f9802fc3766a32836ba72635d0582a702fa5/src/container/ReactFlow/index.tsx#L47

Why it should be OnConnectStopFunc ? Do you explain the reason?
