### ISSUE TITLE
Get the position of canvas onConnectStop()

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#404]
@moklick I want to add a new node where the user stops the connection on the canvas, now we have added mouse event, but how we can get the exact position on the canvas from that mouseEvent ?

**Comment by moklick** [comment]
This question is not specific about React Flow but has something to do with Javascript in general. Please ask questions like this on StackOverflow.

You can get the position of a mouse event by using the keys `clientX` and `clientY`.
