### ISSUE TITLE
onElementClick is not working on 5.1.1

### ISSUE THREAD

**Issue by kagia** [wbkd/react-flow#406]
In the Basic Demo there is no `click` message in the console if I click on a node..

**Comment by moklick** [comment]
Hy @kagia 

I can't reproduce this. When I go to [reactflow.dev](https://reactflow.dev/) (where the latest version is deployed) everything works as expected.

**Comment by kagia** [comment]
if you edit line 7 of the Basic Demo:

```ts
7: const onElementClick = (evt, element) => console.log('click', element);
```

to have some other message of your choosing

```ts
 7: const onElementClick = (evt, element) => console.log('blabla', element);
```

you will notice that the callback isn't being fired.

**Comment by moklick** [comment]
I still can't reproduce this. The basic example is deployed under https://reactflow.dev/basic. When you click on a node you see  the message `click`. The landing page displays the [Overview example](https://github.com/wbkd/react-flow/blob/master/example/src/Overview/index.js).

**Comment by kagia** [comment]
You're right, I'll go ahead and close the issue.

Thanks for the help!
