### ISSUE TITLE
React Component as Label

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#418]
First of all, thank you for all the amazing work on this library. I'm really enjoying using it. I was wondering if it would be possible to add the ability to use a React component as a label rather than just plain text. My use case is I would like to do some custom styling that just isn't easily supported with SVG elements. Thanks!

**Comment by moklick** [comment]
Hey @wdfinch 

Are you talking about an edge Label?

**Comment by wdfinch** [comment]
Yes. So creating a custom edge works fine for custom logic, but the issue is it seems like I can only use SVG elements to render the edge label. So for example, if I wanted to use a div, h1, img, or some combination of those like in a typical component, it doesn't seem like that's possible right now.

Additionally, if I want to use an existing edge type (for example the bezier edge) and I just want to make a small change to the label portion, I need to copy in all the logic for creating that edge. Would be much cleaner if I could just pass in a custom label component and not rewrite all the other logic for rendering the edge.

**Comment by moklick** [comment]
Right now the edges are drawn as SVG paths so we are already in a SVG context. You could use `foreignObject` for your custom label within your custom edge type. I will check how we can simplify the creation of new edge types / how we could re-use the existing ones.

**Comment by wdfinch** [comment]
Gotcha. Ok, I'll check that out. Thanks so much for the help. 

And yes I think it would be really nice to reuse logic from existing types as this would save a lot of copy and paste if you only want to change certain features of the edge like the label and not the path part.
