### ISSUE TITLE
Can not add className to edge

### ISSUE THREAD

**Issue by MatthieuJnon** [wbkd/react-flow#420]
Hi, adding a className to an edge doesn't seem to work.

Reproduced the issue in a codesandbox : https://codesandbox.io/s/objective-allen-w04y7?file=/src/Graph.jsx

Thank you for this otherwise amazing library.

**Comment by MatthieuJnon** [comment]
Side question: If I want to add a button instead of a label to a smoothstep edge, do I have to copy the whole smoothstep component in a file of my own , and write svg for that button ? (and thus losing future improvements on this component if I don't  manually copy it again)

**Comment by moklick** [comment]
Hey @MatthieuJnon 

I think you found a bug :) I will check it tomorrow. 
We are also releasing some edge utils in the next days (you can have a look on the `develop` branch). They should help you to create custom edges.

**Comment by moklick** [comment]
This should work with v5.2.0. We also exporting some edge utils now that should help you to implement a custom edge.

**Comment by MatthieuJnon** [comment]
Thank you so much. I can't believe how reactive and helpful you are!
