### ISSUE TITLE
Edge Props

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#421]
Would it be possible to add some additional options to edges to change:

1. The border-radius of the background rect (rx property)
2. The padding of the background rect. This is currently hardcoded in.

Would be great to changes these without having to create a custom edge.

**Comment by moklick** [comment]
1. Can you adjust the border-radius with the `labelBgStyle` option or by using the classname `react-flow__edge-textbg`?
2. Good idea, we will add that!

**Comment by wdfinch** [comment]
1. I don't think so because rx is an HTML attribute, not a CSS property. Unless there is some other way to change the border-radius of a vector that I'm not aware of, I think you need access to that attribute.

**Comment by moklick** [comment]
`labelBgBorderRadius` option is released in v5.3.0
