### ISSUE TITLE
Position Difference onPaneMove

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#422]
@moklick I need a position difference from the default position (0,0) when the user has moved the pane so that I can calculate accurate node position

**Comment by moklick** [comment]
Hey @agarwal00s 

can you exactly describe what you want to do? Why do you want to calculate node positions?

**Comment by agarwal00s** [comment]
I am trying to create a node when we start a node connection and drop it on the canvas. The node position depends on where the user stopped (onConnectStop), so I'm getting the mouse event onConnectStop, but if the user has moved the pane then my node position has to be changed depending on how much the pane is moved, that's why I want this difference value.

**Comment by moklick** [comment]
If you want to get the internal position from a screen position you can use the `project` function that is part of the `reactflowInstance` you receive in the `onLoad` callback. This function is meant to be used for drag and drop handling.

**Comment by agarwal00s** [comment]
Thanks @moklick it worked out.
