### ISSUE TITLE
Issue Edge Stacking Order

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#425]
Edges will stack in the order they are laid out in the page HTML. However, the edge labels will also follow this order. Therefore, edge lines will be placed on top of edge labels for edges with a lower stacking order.

I think the default behavior should be that edge labels should always be placed above edge lines regardless of their order in the HTML.

I tried changing the z-index of the edge labels, but this doesn't solve the issue.

**Comment by moklick** [comment]
Unfortunately there is no z-index in SVG world. The rendering order is based on document order so we would need to create another group that gets rendered after the edges. Maybe we could achieve this with portals? I would like to keep the edge texts inside the edge components 🤔

**Comment by moklick** [comment]
I think the best way would to refactor the edge label rendering that they get their own renderer which always renders the labels ob top of the edges. The advantage of a own renderer would be that we could use divs for the labels which would make it more flexible and easier to style.

**Comment by wdfinch** [comment]
That sounds like a good approach.

**Comment by moklick** [comment]
in v10 you will be able to pass a zIndex as an edge and node option.

**Comment by moklick** [comment]
We have a helper component for div based edge labels since v11.2.0 https://reactflow.dev/docs/api/edges/edge-label-renderer/
