### ISSUE TITLE
Distinguish overlapping Edges

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#427]
@moklick Is there any way we can show an overlap icon or a curved type of edge where 2 or more edges are overlapped?
Current: 
<img width="275" alt="Screenshot 2020-08-12 at 10 04 56 AM" src="https://user-images.githubusercontent.com/22545835/89975439-5c902b00-dc83-11ea-98b5-117ab6ff38b1.png">
Expected:
![0dd96942-b706-434b-9407-f54698323a45](https://user-images.githubusercontent.com/22545835/89975931-b5ac8e80-dc84-11ea-9f12-fa5864a38724.png)

**Comment by moklick** [comment]
Hey @agarwal00s 

this is a nice feature but very hard to implement. I'm not sure if we're going to implement this but I know it's not going to happen in the near future.

**Comment by Zn4rK** [comment]
For what it's worth, there exists an implementation [here](https://github.com/MrBlenny/react-flow-chart/blob/c27628b6a082f533ab0cea7e86415b0a48ed8ab1/src/components/Link/utils/generateCurvePath.ts#L80) that one could take inspiration from.

I have a slight feeling that it isn't that easy, but just posting it here just in case!

**Comment by hrishikesh2727** [comment]
Hi @moklick and @Zn4rK,

Any updates on this feature or any examples of how we can achieve this?
![image](https://github.com/user-attachments/assets/de2895f1-6cf4-4240-9a81-f9a62ac13e34)

**Comment by awaisshah228** [comment]
For distinguishing overlapping edges — **[avoid-nodes-edge](https://www.npmjs.com/package/avoid-nodes-edge)** automatically nudges parallel edges apart so they never overlap. Edges route orthogonally around nodes using libavoid WASM in a Web Worker.

**[Live Demo](https://avoid-nodes-pro-example.vercel.app)** | **[npm](https://www.npmjs.com/package/avoid-nodes-edge)** | **[GitHub](https://github.com/awaisshah228/react-flow-avoid-nodes-routing)** | **[Package source (turbo-package branch)](https://github.com/awaisshah228/react-flow-avoid-nodes-routing/tree/turbo-package)**

```bash
npm install avoid-nodes-edge libavoid-js
```

Works with React Flow v12+.

**Comment by tisoap** [comment]
For people interested, I've build [react-flow-smart-edge](https://github.com/tisoap/react-flow-smart-edge) using A* pathfinding to route edges around other nodes, avoiding intersections. It has smart equivalents for every type of edge React Flow has.

**Comment by Azim-Ahmed** [comment]
Hello @hrishikesh2727  , @agarwal00s  , 

I have created a custom npm package for this behavior. Please check this.
https://www.npmjs.com/package/react-flow-edge-overlapping

<img width="1287" height="521" alt="Image" src="https://github.com/user-attachments/assets/d8f5e032-4f4a-460c-866d-bf2291778a63" />

live link: https://www.visualflow.dev/paid-examples/edge-overlapping
