### ISSUE TITLE
Edge Hover Event

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#429]
@moklick I was trying to implement a feature, where on hover of edge I will show a delete icon and if the user clicks on that the edge will be deleted
It will be helpful if we can get an event when the mouse enters an edge and leaves an edge with the edge information.
Currently, we have only for node

**Comment by moklick** [comment]
@agarwal00s the easiest way for now would be to implement a custom edge. We are exporting edge utils and also the `EdgeText` component.

**Comment by moklick** [comment]
Does it work for you @moklick ?
