### ISSUE TITLE
elementsSelectable Additional Options

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#432]
Right now all elements are either selectable or not selectable. However, I would like to make my nodes selectable and my edges not selectable.

Can the ability be added to choose between edges vs nodes being selectable?

This could even go as far as passing in an array of all the element ids that are selectable for additional flexibility.

**Comment by moklick** [comment]
Hey @wdfinch 

you can already do this by using the edge option `selectable`.

**Comment by wdfinch** [comment]
So that works with controlling which nodes are selectable. The issue is I don't want my edges to be selectable. Would it be possible to add the `selectable` options to edges as well as nodes?

**Comment by moklick** [comment]
If you set the general option `elementsSelectable=false` the edges should not be selectable

**Comment by wdfinch** [comment]
Got it ok that works. It might be good to clarify this in the docs as `elementsSelectable=false` seems like it would make nothing selectable rather than being able to be overridden.

I guess the only case this doesn't cover is if the user wanted to only be able to select edges. Not sure if that's a common enough use case to add that in.

**Comment by moklick** [comment]
If you only want to select edges you can set all nodes `selectable=false`.

**Comment by kenjinp** [comment]
There doesn't seem to be the inverse. For example, it doesn't seem possible to have elementsSelectable but some or all edges unselectable
