### ISSUE TITLE
fitView does not fit for the actual shape of the graph

### ISSUE THREAD

**Issue by alexdawes** [wbkd/react-flow#442]
I've had mixed results using the `.fitView()` method - when both the graph and the space being drawn in are quite rectangular, the graph can end up zoomed out quite a bit.

I believe this is because the value being used to determine the (unclamped) zoom-level is the max of the width and height of the nodes rectangle, meaning actually its the smallest square that can contain the graph that is behind fitted to, rather than the graph itself.

```
    const bounds = getRectOfNodes(nodes);
    const maxBoundsSize = Math.max(bounds.width, bounds.height);
    const zoom = Math.min(width, height) / (maxBoundsSize + maxBoundsSize * padding);
    const clampedZoom = clamp(zoom, minZoom, maxZoom);
```

This can lead to a fit like the following:

![image](https://user-images.githubusercontent.com/16855719/90622455-01bf7c00-e20d-11ea-8ce4-0b463ba42ba7.png)

In this case, the graph would actually fit with a higher zoom level:

![image](https://user-images.githubusercontent.com/16855719/90622535-2287d180-e20d-11ea-9a4b-a5f205a5bec3.png)

I think the better way of calculating this zoom would be:

```
    const bounds = getRectOfNodes(nodes);
    const xZoom = width / (bounds.width * (1 + padding));
    const yZoom = height / (bounds.height * (1 + padding));
    const zoom = Math.min(xZoom, yZoom);
    const clampedZoom = clamp(zoom, minZoom, maxZoom);
```

**Comment by alexdawes** [comment]
PR opened: https://github.com/wbkd/react-flow/pull/443

**Comment by moklick** [comment]
I just merged the PR! Thanks a lot :)
