### ISSUE TITLE
How to Get Position of multiple dragged Nodes?

### ISSUE THREAD

**Issue by pulli7** [wbkd/react-flow#444]
Maybe it's just me being stupid, but i can't figure out how to get the modified coordinates of dragged nodes, when multiple nodes are selected and dragged to a new position together. (dragging itself works, but i cant get the positions into my local state)

For a single node onNodeDragStop() works fine, but it does not get called when dragging multiple nodes at once.

I tried to make use of onLoad using ReactFlowInstance.getElements() to figure out changed node positions by comparing to my local state, but there ran into the problem that the position object of Nodes in the Array returned by getElements() do not change, when moving Nodes around an just contains the initial values.

So i am wondering what is the intended way to handle the position change when multiple nodes are dragged at once?

**Comment by moklick** [comment]
Hey @pulli7 

Could you check out the [provider example](https://reactflow.dev/provider) ([source code](https://github.com/wbkd/react-flow/blob/master/example/src/Provider/Sidebar.js#L18-L22)). There we read out the updated node positions. Does it help?

**Comment by pulli7** [comment]
Thank you, i totally forgot about that option (even started out with the provider example at the very beginning)...

That indeed helps, i can now get the coordinates of the dragged nodes. Feels a bit strange to do it that way for my specific usecase though, as i would like to update my local state only when nodes are dropped, and not while still moving. (I am using your package to build a graphical editor, and constantly cache the data of the Nodes into database with session cookie to prevent users lose their drawed graph if they press F5 or something. So updates happening constantly while dragging are an performance issue for me in this case) But i think i could make it work with additional evaluation of mouse events.

An enhanched variant of onNodeDragStop() that returns array of Nodes and also fires when multiple Nodes are dragged would make it easier for that usecase. (would also be more consistent in my opinion, because why limit the drop event to dragging single Nodes?)

**Comment by moklick** [comment]
You are right. We might add `onSelectionDragStart`, `onSelectionDrag` and `onSelwctionDragStop`. What do you think about that?

**Comment by pulli7** [comment]
I think that would be a nice addition to the otherwise already great package.
Would make application code simpler an cleaner in usecases similar to mine.

**Comment by moklick** [comment]
The new event handlers are available in v5.6.0
