### ISSUE TITLE
How can I achieve 1-way connection between nodes?

### ISSUE THREAD

**Issue by buitrung** [wbkd/react-flow#451]
First of all, thank you for this awesome library, I can make my graph the way I want with ease.
However, I was trying to create a graph where every node only provides the 1-way connection: click & hold the mouse button on the "source Handle", drag to the target node (anywhere inside the target node, not only around its "target Handle") and release the mouse button to create the connection.
I figure out my way to achieve this: style the "target Handle" to be as large as its whole node, so that I can release the mouse anywhere inside the node, it will be a release on the "target Handle" to establish the connection.
But there are some problems:
- The "target Handle" now overlaying upon the node, so I can't move the node.
- The connection line can be started from both source & target Handle.

What I want are:
- When dragging the connection line, release it on the node will establish the connection
- Disable the drag gesture of the "target Handle", so 1-way connection must start from "source Handle"

Thanks in advance!

![screenshot](https://user-images.githubusercontent.com/22045606/90768154-7e8b4c80-e318-11ea-909d-23df952cfce0.png)

**Comment by moklick** [comment]
Hey @buitrung 

thanks for your kind words :)

You need to implement some custom behaviour here but I think it's possible.
I would try this:

1. Make all target handlers invisible by default
2. Make them visible by setting a with a flag or class in the `onConnectStart` handler
3. Unset the flag or class in the `onConnectStop` handler with a 1ms timeout (I just saw that `onConnectStop` gets called before `onConnect`. I think we should change this. Then you would not need the timeout).

**Comment by moklick** [comment]
I think you are right. I thought that we would need a function that gets called after `onConnect` but it makes no difference. You can use `onConnectStop`.

**Comment by buitrung** [comment]
Here is the order of method called:
`onConnectStart`
`onConnectStop`
`onConnect`
`onConnectEnd`

If the connection is not established then `onConnectEnd` will not be called, that's the difference.

In my case, using one over the other makes no difference. However it is still convenient to have these both methods, like when I want to make sure user has successfully dragged the connection line to a node.

**Comment by moklick** [comment]
Alright! I am glad it worked out for you :)

**Comment by CarlosSuarezJS20** [comment]
This looks very interesting. Sorry to try to revive this, but I'm struggling to update the class for the handle on onConnectStart. Any one can help? 
I created a custom node and the target handles are now invisible (through classes), I want to make them visible upon onConnectStart but I can't find the best way to do so. Should I just select the element via class? thanks!

**Comment by moklick** [comment]
@chandantiwari1 you can create a custom node and set `isConnectableStart` of the source handle to false if there is already a connection. 

```js
const isSourceConnected = useStore(s => s.edges.find((edge) => edge.source === id));
```

**Comment by kishan-getstarted** [comment]
Hi can you @buitrung can you share some code example here ?
