### ISSUE TITLE
React flow nodes not render in tab approach

### ISSUE THREAD

**Issue by Harish-Hk** [wbkd/react-flow#459]
Hey,

I'm using a tab approach in my project which is [Reactstrap Tabs](https://reactstrap.github.io/components/tabs/)
where I have three tabs by default and second tab consists of the react-flow rendering nodes/steps rendered from database.
If I load the first tab by default(which is usual) and switch to second tab, I don't see any nodes - the whole react-flow pane is empty.
but If I load the second tab(react-flow content) tab by default, nodes get rendered successfully. not sure what's the issue here. and when I switch to other tab and come to second tab(react-flow content), again poof - I dont see any nodes.
any help?

**Comment by moklick** [comment]
I could image that there is an issue with the dimensions of the parent container. The inactive tab is not rendered and has no width and height but you try to initialize the ReactFlow component inside of it. Could you try to only render the ReactFlow component when its tab is active?

**Comment by moklick** [comment]
I will close this issue. We can continue to discuss this in #494
