### ISSUE TITLE
is there away to find incoming and

### ISSUE THREAD

**Issue by pranithasri** [wbkd/react-flow#461]
Is there any helper function to find number  of incoming and outgoing edges?

**Comment by moklick** [comment]
Hey. There is a helper function `getOutgoers`. You can find it in the Readme. Unfortunately there is no `getIncomers`. We will add it soon

**Comment by pranithasri** [comment]
thank you

**Comment by moklick** [comment]
added in v5.9.0

**Comment by underGhost** [comment]
Hey @moklick 

I'm getting that `getIncomers` doesn't exist and I'm using `5.9.2`.

Also looks like the docs are using the same messaging as `getOutgoers`.

> `getOutgoers = (node: Node, elements: Elements): Node[]`

**Comment by moklick** [comment]
Oh! I will correct that. The function should work with v5.9.3.
