### ISSUE TITLE
V12 Migration: Nodes array missing provided order

### ISSUE THREAD

**Issue by shev7** [wbkd/react-flow#4610]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

According to the docs (https://reactflow.dev/learn/layouting/sub-flows) parent nodes should appear before the child nodes in the nodes array. But when I'm adding new node, for example to the end of the nodes array like this `setNodes(prevNodes => [...prevNodes, newNode])`. This somehow puts node to the beginning of the array, and when this node is attached to parent later, when I'm dragging this node, it feels laggy and it also gets out of the parent node sometimes.

Even if I add additional step of sorting like this `setNodes(prevNodes => [...prevNodes, newNode].toSorted(node => node.type === 'group' ? : -1 : 1))` (this should put all groups at the begginig of array) - still not works

Only thing that helped me to solve this is apply the same sorting in `onNodesChange`.

This all was working before V12.

### Steps to reproduce the bug or issue

-

### Expected behavior

-

**Comment by moklick** [comment]
This should be fixed in 12.2.0

**Comment by AquariusGodOfCookier** [comment]
Because of this problem, I tried to force the modification of the order of the nodes array and setNodes, but when I checked the data in the end, it did not actually take effect. The nodes were still restored to the order before the modification.
