### ISSUE TITLE
Backgrounds and grid snapping are misaligned

### ISSUE THREAD

**Issue by sebdvd** [wbkd/react-flow#4615]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: Since @xyflow/react@12.1.0
- Browser and version: Firefox 130
- OS and version: macOS 14.6.1

### Live code example

https://stackblitz.com/edit/vitejs-vite-xgdnyt?file=src%2FApp.jsx

### Describe the Bug

Since @xyflow/react@12.1.0 backgrounds and grid snapping are misaligned

### Steps to reproduce the bug or issue

1. Go to https://stackblitz.com/edit/vitejs-vite-xgdnyt?file=src%2FApp.jsx
2. Backgrounds and grid snapping are misaligned

### Expected behavior

Grid snapping and backgrounds were well working before @xyflow/react@12.1.0

### Screenshots or Videos

https://github.com/user-attachments/assets/96cb4b0c-0f3d-4e9b-a768-0a3c8eed1806

### Additional context

Dots backgrounds looks fine, but other ones are misaligned. I can confirm the regression was introduced by these changes https://github.com/xyflow/xyflow/pull/4501/files (I tested the grid without the changes coming from `packages/react/src/additional-components/Background/Background.tsx` file).

(Out of context: thanks for this great lib btw 👍)

**Comment by moklick** [comment]
Thanks for the report 🙏
