### ISSUE TITLE
Cant refresh type of node

### ISSUE THREAD

**Issue by piiok** [wbkd/react-flow#462]
I  have some nodes, and i change type of a element but not change.

**Comment by moklick** [comment]
There is no specific reason I guess but the `type` option is not dynamic. I will look into it.

**Comment by 100le** [comment]
I also tried to update the **animated** option for the edges but its not reflected/re-rendered on the graph automatically.
Example: 
`
const edges = useStoreState((store) => store.edges);

if (animateEdge) {
  const matchedEdge = edges.find((value) => value.id === 'edgeId');
  matchedEdge.animated = true;
}
`

**Comment by piiok** [comment]
I solved it with a component inside the ReactFlow component like this:

`
const Example= (props) => {
  const [elements, setElements] = useState([]);
  const StateUpdater = () => {
    const nodes = useStoreState(state => state.nodes);
    useEffect(() => {
      console.log(elements)
      nodes.forEach((n)=>{
         const e = elements.find((item) => ( item.id === n.id))
         if(e && e.type){
           n.type = e.type
         }
      })
    }, [elements])

    return null
  }
 return (
      <ReactFlow
        elements={elements}
      >    
        <StateUpdater/>
      </ReactFlow>
  )
}
`

I do not know if it is correct, any suggestion is welcome.

**Comment by 100le** [comment]
I did something similar as the example above just with the Edges as i want to dynamically control the **animated** property of the edges but it doesn't work as well..

**Comment by moklick** [comment]
The `animated` property is dynamic. It's important that you update your `elements` array and pass the updated array to the ReactFlow component (like we are doing it [in this example](https://github.com/wbkd/react-flow/blob/master/example/src/Stress/index.js#L18-L34)). If you just change a reference, ReactFlow can't detect the change immediately.

The `type` property is not dynamic but we will change that. i was not aware that it could be a use case to change the type of a node.

**Comment by 100le** [comment]
> There is no specific reason for this behavior but the `type` option is not dynamic. I will look into it.

Can you also please enable this feature for the edges. I really need to option to dynamically change the edge `type` as well as the `node`.

**Comment by moklick** [comment]
released in v5.7.1
