### ISSUE TITLE
How to update/re-render elements on click?

### ISSUE THREAD

**Issue by JamesyJi** [wbkd/react-flow#463]
Hi, I'm kind of new to react and very new to this library.

I've been playing around with the interaction example and I'm trying to get a node's name to change after clicking. However, the node doesn't visually reflect this new update and won't update unless I toggle the "connectable" checkbox. My hacky method was to just manually toggle "connectable" in onElementClick() but obviously this is not a good approach.

Another thing I tried was making onElementClick() concat a new element (with the changes) and then deleting the old element but again, this seems like a bad idea.

The blog says **"you need to pass all functions that change the displayed nodes and edges by yourself",** but I'm not sure how to do this : (. Any pointers would be appreciated thanks!

**Comment by moklick** [comment]
I could imagine that the problem is that you don't create a new data object but only change the `label` key.

Could you create a codesandbox or something like that so that I can have a look?

**Comment by JamesyJi** [comment]
https://codesandbox.io/s/sweet-shamir-mkuqs?file=/src/interact.js

It's essentially same as the interaction example but with changes to onElementClick() starting at line 21.

To reproduce, turn on capture element click, click on any node. Console will show the label has been updated but visually it isn't. Then toggle connectable to see change reflected in the node (note that none of the other toggles have this effect).

**Comment by moklick** [comment]
Ok, I see. You need to update your state in order to tell ReactFlow that you changed something. I updated your example here https://codesandbox.io/s/stoic-torvalds-ll6wo?file=/src/interact.js
