### ISSUE TITLE
Content inside node not able to select

### ISSUE THREAD

**Issue by Harish-Hk** [wbkd/react-flow#465]
Hey there,

I have few inputs inside a node and I want to be able to select the text inside that input.
But when I drag the mouse with left click, whole not is getting dragged, instead of selecting the text.

So, I was going through the node properties, and set **nodesDraggable={false}** which kind of works for my requirement mentioned above.

But there are some cases where nodes are overlapping on each other.
So I want the nodes to draggable and achieve the above requirement.

Or It would be also helpful for me if, an Icon on top somewhere, select that and drag the node,

can this be done? if yes, any help is appreciated.

Did anyone face this issue?
below is the node, with nodesDraggable to false, able to select text

Thanks in advance
![nodeDraggable-False](https://user-images.githubusercontent.com/28500085/91553672-6ab09d80-e94b-11ea-9fb7-58fb5197caad.JPG)

**Comment by moklick** [comment]
Hey @Harish-Hk 

this is not documented (I will add it soon :)) but you can use the additional class `nodrag` for your input elements and they should not be draggable anymore. I hope it helps.

**Comment by Harish-Hk** [comment]
Hey @moklick 
I'm so glad that you respond to queries super quick.

just have an other question.

the above class you mentioned ```nodrag``` works, is it more of a custom class for this ```react-flow``` package, or a normal class?

**Comment by moklick** [comment]
We are using `react-draggable` for the dragging of the nodes. We configured it that the class `nodrag` cancels the dragging behavior.
