### ISSUE TITLE
Positioning Handles in Centre of Node

### ISSUE THREAD

**Issue by JamesyJi** [wbkd/react-flow#467]
Hi, are there future plans to add "centre/middle" to position of Handles? It would make edge connections look a lot cleaner (especially in radial trees such as [https://en.wikipedia.org/wiki/Radial_tree#/media/File:Radial_tree_-_Graphic_Statistics_in_Management.svg](url) and just designs in general where nodes sprawl out in all directions with connections coming from all angles). 

For example, I'm making a tree which sprawls out in all directions. I've set the opacity of the handle to 1 for demonstration purposes. The grey line is the actual edge and the red dotted line is something I've drawn on to show what I would prefer the edge to be (if the handle was in the centre).

I could get it approximately close by changing the position to "left" for this node and styling it up a bit maybe, but then I would have to specifically alter the handle position for every single node.

![Screen Shot 2020-08-29 at 11 21 26 pm](https://user-images.githubusercontent.com/49261993/91637821-6faa4580-ea4e-11ea-9ce0-7c0621025a25.png)

Thank you for considering!

**Comment by hayeselnut** [comment]
Please implement this feature! I would really appreciate it too

**Comment by moklick** [comment]
This should already be possible. You can implement a custom node and add handles with an adjusted position via the `style` prop. It should also be possible to overwrite the position of a handle via CSS.

**Comment by JamesyJi** [comment]
For anyone with same problem in the future, just position="top", style: {top: '50%'} inside Handle should work

**Comment by hayeselnut** [comment]
Thanks!
