### ISSUE TITLE
Method `onElementsRemove` doesn't provide id of source handle if there're multiple ones

### ISSUE THREAD

**Issue by buitrung** [wbkd/react-flow#476]
I have node with 1 input handle & multiple subnodes (each subnode has 1 output handle). The application state looks like this:

```
nodes: [
  {
    id: 'node1',
    data: {
      subnodes: [
        { id: 'subnode1' },
        ...
      ]
    }
  },
  {
    id: 'node2',
    data: {}
  }
],
edges: [
  {
    id: 'edge1',
    source: 'node1__subnode1',
    target: 'node2'
  }
]
```
Output handle of each subnode uses the id of its subnode.

When I try to delete the edge `edge1` by pressing `Backspace`, which triggers `onElementsRemove`, I find out that source of the removed edge is `node1` (it should be `node1__subnode1`), so I can't detect which subnode the source was.

**Comment by moklick** [comment]
Are you passing the id `subnode1` to the specific handle (like we are doing it here https://github.com/wbkd/react-flow/blob/master/example/src/CustomNode/ColorSelectorNode.js)?

**Comment by buitrung** [comment]
Yes, that's right. In your example ColorSelectorNode, the `source` of the edge from `<Handle type="source" id="a" />` is `2__a` (I suppose that this is your internal convention style). But when removing the edge, the callback function doesn't give me that id, but only node id `2`.

**Comment by moklick** [comment]
We pass all selected elements to the `onElementsRemove` handler when you remove them. When you just want to remove an edge it is not important if it comes from a node with multiple handles. You only need the id of that edge. Are you still facing an issue here? If so, could you create a codesandbox?

**Comment by buitrung** [comment]
> When you just want to remove an edge it is not important if it comes from a node with multiple handles.

In my data structure, I store the `next_node_id` info in nodes & subnodes (if they have any, of course). So beside just removing the edge, I need to also clear that info if the edge has no longer existed, so it is necessary to know from which handle the edge is removed.

> You only need the id of that edge.

However, thanks for this suggestion I can still workaround by using id to find which edge is to be removed and do stuffs then.

What I concern here is the `source` id of edge is not in the same format: when created it is `nodeId__handleId`, but when removed it is only `nodeId` (I have misunderstood that my node didn't have multiple handles, which was not true). May you consider to uniform those ids or enrich the edge data to something like this:
```
edge: {
  id,
  source,
  sourceHandle,
  target,
  targetHandle
}
```
?

**Comment by moklick** [comment]
Ah! I got it. Thanks for the hint. I will fix this.

**Comment by moklick** [comment]
Could you check if the solution in v5.9.3 works for you? We now pass the original source and handle ids to the edge click handler.

**Comment by buitrung** [comment]
Yes it works!
However, after upgraded to v5.9.3 now I can't use `onElementClick`: sometimes it is called, sometimes it isn't. Not sure if this is a bug? Please check if it is also your situation.

**Comment by moklick** [comment]
I can't reproduce the problem with the `onElementClick` handler. If you can't solve it and you think there is a bug, please open a new issue. Thanks for the report 👍
