### ISSUE TITLE
Svelte5 Support for Svelte Flow

### ISSUE THREAD

**Issue by ravides19** [wbkd/react-flow#4764]
### Please describe the feature that you want to propose

Reqesting for a svelte5 support for svelte flow so we can utilise the best of both worlds of svelte and xyflow

**Comment by peterkogo** [comment]
Svelte Flow is already working with Svelte 5. The PR should land this week #4758. 

The proper Svelte 5 rewrite will take some time.

**Comment by peterkogo** [comment]
Pre-release of Svelte Flow 1.0 is out.

Some preliminary notes:
- install via `npm install @xyflow/svelte@next`
- requires Svelte 5
- take a look at the [migration guide](https://next.svelteflow.dev/learn/troubleshooting/migrate-to-v1)
- early, incomplete docs available at [next.svelteflow.dev](https://next.svelteflow.dev)

Please keep in mind that this is an alpha version and we are still in the process of migrating our API references and guides. *However,* [all examples](https://next.svelteflow.dev/examples) are already up to date!

We need your feedback! Are your experiencing any issues? What do you think about the new API?
Share your thoughts in our [Discord](https://discord.gg/RVmnytFmGW)!
