### ISSUE TITLE
Feature Request: Context Menu for Selection

### ISSUE THREAD

**Issue by pulli7** [wbkd/react-flow#478]
Now that we have _onNodeContextMenu(event: MouseEvent, node: Node)_, it would be cool to have the same also for Multiselections, so something like _onSelectionContextMenu(event: MouseEvent, node: Nodes[])_

Would be useful e.g. when you want to do actions like deleting or copying Nodes via Contextmenu.

**Comment by moklick** [comment]
Yep! Good idea :) we will add this feature soon.

**Comment by moklick** [comment]
added in v5.9.0
