### ISSUE TITLE
onPaneScroll event handler

### ISSUE THREAD

**Issue by emielwit** [wbkd/react-flow#480]
Hey,

What do you think of an `onPaneScroll` function like the `onPaneClick` to implement custom logic behind the scroll wheel? For example, you can move the canvas up and down with the `setInitTransform` with a custom function or any other logic.

Let me know how you think about this. If you want I can create a PR for this.

**Comment by moklick** [comment]
Hey @emielwit 

we could also think about adding a `useScrollToPan` option as it is suggested in #359. What do you think about that?

**Comment by emielwit** [comment]
I think `useScrollToPan` is a good solution. I don't think there is any other case for scrolling then zooming and panning. Do you already have a solution in mind to achieve this feature?

**Comment by moklick** [comment]
Unfortunately d3-zoom (which is used for zooming and panning) doesn't support this so we need to implement it by ourselves. Maybe this issue could help https://github.com/d3/d3-zoom/issues/46.

**Comment by EmielW** [comment]
I created a PR for the `onPaneScroll` i will take a look at the `useScrollToPan` if I have some time left. I think for now the `onPaneScroll` can help people to create a custom solution.
