### ISSUE TITLE
Custom nodes trigger on click events twice

### ISSUE THREAD

**Issue by JamesyJi** [wbkd/react-flow#482]
EDIT: On further testing, this seems to be a problem with dragging also triggering on click events. By toggling nodesDraggable={false}, the on click event will only trigger once.

To reproduce:
1. Run the custom nodes example provided
2. Click on one of the custom nodes.
3. Check console and notice that the output appears twice, suggesting the click event is triggered twice.
4. **Temporary Fix**: set nodesDraggable={false} inside <ReactFlow/> and check console output again. It should be fixed.

This problem doesn't exist with the provided nodes, only for custom nodes. 

I've tried pointerEvents: 'none' in the custom node style but it it just completely turns off click events.

**Comment by hayeselnut** [comment]
Hi, thanks for this library! If it's not too much to ask, could you provide an example of useStateActions and add it to the examples folder? I'm new to react and not sure how to get this working but I'm trying get my camera to centre on nodes I click. I've provided a basic template in code sandbox where clicking on the button should set the transform to 100, 100, 1. But it's giving me cannot getAction undefined. I'm assuming I would need to use ReactFlowProvider or something but I'm not sure. 

An example would be extremely helpful but if it takes too much time, I'd appreciate if you could point out where I'm going wrong in my sandbox.

https://codesandbox.io/s/floral-cache-kw3kg?file=/src/App.js:711-722

**Comment by moklick** [comment]
Thanks for the report! Should be fixed in v.5.8.0
