### ISSUE TITLE
useStateActions example?

### ISSUE THREAD

**Issue by hayeselnut** [wbkd/react-flow#485]
Hi, thanks for this library! If it's not too much to ask, could you provide an example of useStateActions and add it to the examples folder? I'm new to react and not sure how to get this working but I'm trying get my camera to centre on nodes I click. I've provided a basic template in code sandbox where clicking on the button should set the transform to 100, 100, 1. But it's giving me cannot getAction undefined. I'm assuming I would need to use ReactFlowProvider or something but I'm not sure. 

An example would be extremely helpful but if it takes too much time, I'd appreciate if you could point out where I'm going wrong in my sandbox.

https://codesandbox.io/s/floral-cache-kw3kg?file=/src/App.js:711-722

**Comment by EmielW** [comment]
Hey,

I have a working example for you: [https://codesandbox.io/s/hopeful-glitter-5dv2w](url)

You have to define the function inside the `ReactFlowProvider`

**Comment by moklick** [comment]
I added some example code of how to use an action in the provider example.
