### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by code-guru** [wbkd/react-flow#486]
Using the latest version of react-flow, I'm getting the following error the reac-flow without any extra settings or customizations. It seems to be related to the latest change with react-draggable. Is it any workaround to not get this warning?

```
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by NodeWrapper)
    in DraggableCore (created by NodeWrapper)
    in NodeWrapper (created by NodeRenderer)
    in div (created by NodeRenderer)
    in NodeRenderer (created by GraphView)
    in div (created by GraphView)
    in GraphView (created by ReactFlow)
    in StoreProvider (created by ReactFlowWrapper)
    in ReactFlowWrapper (created by ReactFlow)
    in div (created by ReactFlow)
    in ReactFlow (at HomePage/index.tsx:14)
    in HomePage (at loadable.tsx:27)
```

**Comment by moklick** [comment]
Hey @code-guru 

I am not able to reproduce this. Where do you get this error?

**Comment by chopfitzroy** [comment]
I am seeing this as well, using example code from README.

![image](https://user-images.githubusercontent.com/2978850/92230914-f902c180-eeff-11ea-8f74-7f7a51b4d723.png)

**Comment by moklick** [comment]
Ok, thanks. I will look into it. Maybe this helps https://github.com/STRML/react-draggable/pull/478

**Comment by code-guru** [comment]
@moklick exactly, there is also reference in their [changelog](https://github.com/STRML/react-draggable/blob/master/CHANGELOG.md) for v4.4.0 
It seems like a simple fix, I was looking into it, if you didn't get the time, maybe I can take a look and send a pull request during the weekend 🙂

**Comment by moklick** [comment]
Thanks! Feel free to do a PR :) I can't work on this this week.
