### ISSUE TITLE
shift + drag preventing from selecting edges

### ISSUE THREAD

**Issue by MatthieuJnon** [wbkd/react-flow#487]
Hi,
I have a custom edge that displays a button in the center of it, the button changes depending on if the shift button is pressed or not. The issue is, when shift is pressed, the edge is not selectable and the button is not clickable. Is there a way to disable the shift+drag behaviour ? (I set selectNodesOnDrag={false})

**Comment by EmielW** [comment]
I think you need `elementsSelectable={false}`

**Comment by moklick** [comment]
Did you try to set another selection key with the `selectionKeyCode` option?

**Comment by MatthieuJnon** [comment]
Yes thank you very much ! Don't know why I missed that, if anyone is looking at this issue later, I used the 183 key code, which corresponds to the calculator button on some keyboards, doubt any users will think of using that.
