### ISSUE TITLE
Feature-Request: Auto fit view

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#488]
Hi :)

In my use case, I initialize `react-flow` empty. After some time the elements change, also depending on user actions.

I want to center the graph in these cases. Currently one has to grab the `reactFlowInstance` object passed in `onLoad` and store the reference. If the graph is changed from outside, `reactFlowInstance.fitView()` has to be called. I'm not sure why, but due to timing it also needs to be delayed with `setTimeout` and work otherwise. This is also true when calling it directly in `onLoad`.

I was thinking if it would be possible to have a more declarative solution. There could be a parameter `autoFitView :: Boolean`, and `react-flow` could automatically make sure the graph is fitted.

It's currently not entirely clear to me, how this would work, if the user panned or zoomed.
* One could set this flag to `false` in case the state is dirty.
* Or leverage react's `key` to indicate graph changes.
* Or compare the elements argument with the previous state. 

Maybe you have an idea, how this feature could be implemented, or fit to view improved.

**Comment by moklick** [comment]
Hey,

I already thought about an `autoFitView` option but I am not sure which changes we should listen for.

**Comment by tafelito** [comment]
when using `fitView` if the graph is bigger than what it can actually zoom out, the default position is the middle of the graph, instead of the starting. It'd be great if aside of the autoFitView, to also add the possibility to always show the position [0,0]

**Comment by moklick** [comment]
We will not add a `autoFitView` because it's hard to implement / hard to know when the user would expect a fit view. On the first render (when would that even be?) or after every viewport change?

We also added the `useZoomPanHelper` hook that exports a `fitView` functions so it's already easier to do a fit view.
