### ISSUE TITLE
Modify node selection from outside

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#492]
There is a way to listen for selection changes `onSelectionChange` and to define if elements are `selectable`.

If I'm not mistaken, there is no way define or change which elements are selected from outside. Also there is no way to ask which elements are currently selected on `reactFlowInstance` or with  `ReactFlowProvider`.

If that's correct, it would be neat to add this :)

**Update**
I guess one could use `ReactFlowProvider` to listen for selected elements.
https://github.com/wbkd/react-flow/blob/f35ad054364baf605bad30471f0306f211a34055/src/container/EdgeRenderer/index.tsx#L202

This issue is about changing it from outside, though :)

**Comment by moklick** [comment]
I added an example in the [provider example](https://reactflow.dev/provider).

**Comment by zyaanbookee** [comment]
Hi how to select multiple node in the new reactflow??

**Comment by imvetri** [comment]
@zyaanbookee in mac, hold command button and click target nodes

**Comment by kartikk-k** [comment]
For developers who are coming after 2023, you can use [`useStoreApi`](https://reactflow.dev/docs/api/hooks/use-store/#usestoreapi) provided by **reactflow** to update node selection from outside.

**Example:**
update selection from outside when clicked on custom node:

```ts
import { useStoreApi } from 'reactflow';


const { addSelectedNodes } = store.getState()

// updating selection when clicked on custom node
const updateActiveNode = () => {
    const temp = nodes.find((node) => node.id === id)
    if (temp) addSelectedNodes([temp.id]) // provide array of node ids
}
```

**Comment by MatheusRoichman** [comment]
> For developers who are coming after 2023, you can use [`useStoreApi`](https://reactflow.dev/docs/api/hooks/use-store/#usestoreapi) provided by **reactflow** to update node selection from outside.
> 
> **Example:** update selection from outside when clicked on custom node:
> 
> ```ts
> import { useStoreApi } from 'reactflow';
> 
> 
> const { addSelectedNodes } = store.getState()
> 
> // updating selection when clicked on custom node
> const updateActiveNode = () => {
>     const temp = nodes.find((node) => node.id === id)
>     if (temp) addSelectedNodes([temp.id]) // provide array of node ids
> }
> ```

Does it concatenate the current selection with the provided array, or does it set the selection to the provided array?

**Comment by pourquoi** [comment]
the correct method is resetSelectedElements

```
import {
  useStore as useReactFlowStore,
} from "@xyflow/react";

const [resetSelectedElements, addSelectedNodes] = useReactFlowStore(
  (state) => [state.resetSelectedElements, addSelectedNodes]
);

const selectNode = (nodeId: string) => {
  resetSelectedElements();
  addSelectedNodes([nodeId]);
}
```
