### ISSUE TITLE
Having an issue with React and creating nodes from an array

### ISSUE THREAD

**Issue by Ixdane** [wbkd/react-flow#505]
I am attempting to use react-flow to create a diagram dynamically.  Basically I have a list of "fixes", each fix having 3 modules.  I have an array with the modules for a fix, and I am sending it to the .js to return the ReactFlow object.  My issue is, if I try to build the initial state inside the function and then assign it, I get a crash and it tells me React thought it was in an infinite loop.  But if I put the code inside a useEffect (like you did in the node example) it doesn't seem to have the Module data yet.

I am REALLY new to React, and I always seem to have this kind of issue with the data not being where I think it should be.

So, my ask is,  if I have something like this:
```javascript
const CustomNodeFlow = ({modules,firstm}) => {
const [elements, setElements] = useState([]);

const onElementsRemove = (elementsToRemove) => setElements((els) => removeElements(elementsToRemove, els));
  const onConnect = (params) =>
    setElements((els) => addEdge({ ...params, animated: true, style: { stroke: '#fff' } }, els));

  return (
    <ReactFlow
      elements={elements}
      onElementClick={onElementClick}
      onElementsRemove={onElementsRemove}
      onConnect={onConnect}
      onNodeDragStop={onNodeDragStop}
      onLoad={onLoad}
      nodeTypes={nodeTypes}
      connectionLineStyle={connectionLineStyle}
    >

    </ReactFlow>
  );
};

export default CustomNodeFlow;
```

where would I put the code to process the "modules" array into an array suitable for rendering?  Would I have to use an external function, or would I have to find a way to send the initial diagram state to this function?

**Comment by moklick** [comment]
When the `modules` array changes I would do:

```javascript
...

useEffect(() => {
  setElements(modules.map(m => ({ id: m.id, position: m.position, data: { label: m.label } })))
}, [modules])
```

otherwise you could use it directly as the default:

```javascript
const [elements, setElements] = useState(modules.map(
  m => ({ id: m.id, position: m.position, data: { label: m.label } }))
);
```
