### ISSUE TITLE
getIncomers function

### ISSUE THREAD

**Issue by benjamin-henry** [wbkd/react-flow#514]
please add the following code to your utils : 

const getIncomers = function (node, elements) {
    if (!isNode(node)) {
        return [];
    }
    var incomersIds = elements.filter(function (e) { return isEdge(e) && e.target === node.id; }).map(function (e) { return e.source; });
    return elements.filter(function (e) { return incomersIds.includes(e.id); });
};

And this to the exports : 
exports.getincomers = getIncomers;

Thanks. 
Amazing Package by the way.

**Comment by moklick** [comment]
This code is already part of ReactFlow and also gets exported.

**Comment by pSnehanshu** [comment]
The current `getIncomers` doesn't take into account edges incoming from custom nodes having multiple Handlers. These handlers have ids of the format `nodeid__handlerid`. I have included a regex tester to include them.

```javascript
const getIncomers = (node, elements) => {
  if (!isNode(node)) {
    return [];
  }

  const incomersIds = elements
    .filter((e) => isEdge(e) && e.target === node.id)
    .map((e) => e.source);

  return elements.filter((e) => incomersIds.map((id) => {
    const matches = /([\w-^]+)__([\w-]+)/.exec(id);
    if (matches === null) {
      return id;
    }
    return matches[1];
  }).includes(e.id));
};
```

**Comment by benjamin-henry** [comment]
Nice. Thanks buddy

Le lun. 19 oct. 2020 à 00:37, pSnehanshu <notifications@github.com> a
écrit :
