### ISSUE TITLE
Feature request: can customize connection path as with edge path

### ISSUE THREAD

**Issue by buitrung** [wbkd/react-flow#516]
I have customized the edge path (more curved bezier path) to fit my needs of how nodes & edges look in my graph.
However, I cannot do that with the connection line, so when I drag the connection it doesn't look like an unfinished edge, and when I release the mouse button, it becomes an edge and changes to a different curve.
Can you provide some way to customize the connection path or just unify it with the edge path?
Thanks in advance.

**Comment by moklick** [comment]
Hey @buitrung 

we can't unify it with the edge path, because we don't know which type of edge you are going to create. What we could do is to offer a `customConnectionLine` option. I will see how we can implement this feature.

**Comment by moklick** [comment]
I added a `connectionLineComponent` option in v5.10.0. You can find an example of how the implementation in the [custom connection line example](https://github.com/wbkd/react-flow/blob/master/example/src/CustomConnectionLine/index.js).

**Comment by buitrung** [comment]
Apologize for late response, I've updated to 5.10.0 and cannot be more content with the feature.
Really appreciate your work!
