### ISSUE TITLE
Issues with rendering curved edges

### ISSUE THREAD

**Issue by is343** [wbkd/react-flow#518]
I want to say thanks for creating this library! I really appreciate all that it offers with how simple it is to use! 

However, I'm running into graphical issues when rendering any edge other than the straight one. It seems to be drawing the negative space as well. I don't think it has to do with my browser or operating system, as the react-flow demo site seems to work fine. Have you run into this issue before? Any ideas on what's going on?

![Screen Recording 2020-09-18 at 12 10 28](https://user-images.githubusercontent.com/30599893/93620588-3e1aff00-f9a8-11ea-9fd6-1a927858c30a.gif)

**Comment by moklick** [comment]
Thanks! This is strange. We do a `fill:none` for `.react-flow__edge-path`. That should prevent the paths to get filled. Can you inspect an edge and check why `fill` is not `none` ?

**Comment by is343** [comment]
That was it! Upon inspecting, the parent container's class was overriding `fill`. Thanks so much for such a quick response!

**Comment by moklick** [comment]
Are you using some library around ReactFlow or why was it overwritten?

**Comment by is343** [comment]
It was from a class that I made for a parent div a couple layers up.
