### ISSUE TITLE
Doubt / Question : Do nodes get unmounted when they go out of sight : canvas or pane - react-flow-renderer

### ISSUE THREAD

**Issue by harish-madugula** [wbkd/react-flow#519]
Hey,

I want to know if the nodes get unmounted and mounted while they come and go out of sight? basically dragging the pane.

I set a height of some 1000px to the flow renderer, when I drag the pane up and down, the node gets unmounted. when I drag it back to top, it gets mounted. 

Inside each node, I'm checking the `componentDidMount() {}` and `componentWillUnmount() {}` lifecycle hooks where, I see a change of data.

before unmounting, suppose I see 2 objects in an array, and after it gets unmounted and mounted again(dragging the pane up and down until the node goes out of sight and gets back into sight) I see only 1 object in the array.

not sure why that happens.

**Comment by moklick** [comment]
For a better performance we are only rendering nodes that are inside the viewport. If you don't want this behaviour you can set `onlyRenderVisibleNodes={false}`. This does not explain the data change but I would suppose that it is not related to ReactFlow.

**Comment by harish-madugula** [comment]
hey @moklick , wow, I think that works for me.

But I have an other ques - will it have any issues if we have more number of nodes, which again have multiple states and data renders?

**Comment by moklick** [comment]
Depends on your implementation but it's more a nice to have option because even when it is turned on all nodes can be inside the view port.
