### ISSUE TITLE
Custom Center with Edge Utils

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#522]
First off really I like the added edge utils. This makes creating custom edges much easier. 

For my use case, I would like to be able to customize the center of the edge specifically for the smooth step edge. However, the getSmoothStepPath doesn't accept a custom centerX and centerY. Could this method be changed to accept these values?

**Comment by wdfinch** [comment]
@moklick Do you have advice here? Really would like to use the custom edge utils with a custom center.

**Comment by moklick** [comment]
Hey. I think we can add this option.

**Comment by moklick** [comment]
released in v5.11.1
