### ISSUE TITLE
getEdgeCenter return type issue

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#523]
In the docs, it states the getEdgeCenter method returns `[centerX, centerY]`. However, the method signature is `[number, number, number, number]`. Shouldn't it just be `[number, number]`? Can someone explain what `[number, number, number, number]` represents?

**Comment by moklick** [comment]
Thanks for the hint I will correct this. The params are centerX, centerY, offsetX and offsetY.

**Comment by wdfinch** [comment]
Thanks for the reply. Wouldn't offsetX and offsetY be something the user passed in rather than part of the return value? Shouldn't the return just be the final centerX and centerY?
