### ISSUE TITLE
Re-render nodes after setting the state

### ISSUE THREAD

**Issue by harish-madugula** [wbkd/react-flow#534]
Hey,

Is there any function that we can call, to re-render the nodes?

here is my what I'm trying to do, I have a node, inside that I have a switch, to show and hide nodes emerging from it based on some condition.
I'm setting its `isHidden` property to `true` and `false` and setting the elements state, but that doesn't re-render the nodes and hide the nodes emerging from it until I drag a card, which is causing the re-render I guess, for some reason.

any idea what might be going wrong here? or any better solution?

thanks in advance.

**Comment by moklick** [comment]
Can you create a codesandbox so that we can reproduce this issue? We are using the `isHidden` option in the [hidden example](https://reactflow.dev/hidden)

**Comment by harish-madugula** [comment]
Im doing the same, but I'm not getting the issue, is there any way to re-render the nodes, with the help of a function or something?

**Comment by moklick** [comment]
I think that you are not changing your state but references to the nodes. You need to update your internal state in order to let ReactFlow know about your changes.
