### ISSUE TITLE
get position of elements

### ISSUE THREAD

**Issue by weimin-wati** [wbkd/react-flow#540]
Hello, there!
Thanks for providing this amazing module!
I'm stuck on getting position of elements.
Please let me know the way to get the position of every single element.

My code getting the node is below.
```javascript
handleCopyNode = (node) => {
    let newItem = this.props.nodes;
    newItem = newItem.concat(
      {
        id: Math.random().toString(),
        type: 'mainQuestion',
        data: node.data,
        position: { x: Math.random() * 50 + 50, y: Math.random() * 50 + 50 }
      }
    );
    this.props.createNewQuestionItem(newItem);
    console.log('New Copy:', node)
  }
```
And I've attached the image of console result: 

![Screenshot_3](https://user-images.githubusercontent.com/71246962/94576586-1715d480-02a8-11eb-9c60-bf878d560109.png)

**Comment by moklick** [comment]
Hey!

We have an [example](https://reactflow.dev/provider) where we read out the node positions. You can find the source code [here](https://github.com/wbkd/react-flow/blob/main/example/src/Provider/Sidebar.js#L5-L27).

Does it help?

**Comment by dpankros** [comment]
Isn't it just the something like: `this.props.nodes.forEach(n => console.log(n.position.x, n.position.y))` from within your snippet there?

**Comment by weimin-wati** [comment]
Yeah, It's very helpful. 👍 
Would you like my asking if any questions else?
Thanks so much.
