### ISSUE TITLE
Error: 'non passive listener to "wheel' event

### ISSUE THREAD

**Issue by KutnerUri** [wbkd/react-flow#546]
I'm getting this error:

```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```
It is coming from `onAdd()`, and seems to be required for a smooth scroll-to-zoom effect.
I managed to remove the warning by applying `options = { passive: false }`.
I guess the error goes away when the event is explicitly active.

BTW, what about pinch-to-zoom?

**Comment by moklick** [comment]
The warning should be fixed with React17 when I get it right.
Unfortunately pinch-to-zoom is not supported by d3-zoom, that we are using for panning and zooming. We might change this in the future but it's not a high priority right now.

**Comment by daljeetv** [comment]
@moklick were you able to resolve this? im still getting:

```
ReactFlow.esm.js:3697 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```
