### ISSUE TITLE
[QA] Could I change the target of edge by drag-n-drop?

### ISSUE THREAD

**Issue by zcmgyu** [wbkd/react-flow#549]
I tried to drag the edge to point to another node. Does it seem like this isn't a feature?
Thanks in advance. (bow)

**Comment by moklick** [comment]
Hey @zcmgyu 

can you explain your question a little more precisely?

**Comment by zcmgyu** [comment]
@moklick Thank you for your quick reply.

An edge from A point to B, instead of deleting that edge and making a new edge from A to C. Could I drag that edge target to C?

<img width="428" alt="Screen Shot 2020-10-05 at 22 09 49" src="https://user-images.githubusercontent.com/13638569/95083848-03f77e80-0758-11eb-9140-fa39fa5db30c.png">


<img width="428" alt="Screen Shot 2020-10-05 at 22 10 37" src="https://user-images.githubusercontent.com/13638569/95083852-078b0580-0758-11eb-84e9-d3b53c7fd9ed.png">

**Comment by moklick** [comment]
Got it :) Unfortunately this is not possible at the moment.

**Comment by zcmgyu** [comment]
@moklick If I want to make a PR for this feature, could you give me a hint where can I start?

**Comment by moklick** [comment]
I would wait until we merge #543 ;) After that we can discuss how you could implement this feature.

**Comment by zcmgyu** [comment]
@moklick If you have some time please check out my PR

**Comment by agarwal00s** [comment]
@moklick @zcmgyu I also need this feature, can we please check on this, will be helpful.

**Comment by zcmgyu** [comment]
@agarwal00s Let's use my PR before merged.

**Comment by obaid** [comment]
> 
> <img alt="Screen Shot 2020-10-05 at 22 09 49" width="428" src="https://user-images.githubusercontent.com/13638569/95083848-03f77e80-0758-11eb-9140-fa39fa5db30c.png">
> 

@zcmgyu  Quick question.. is that a custom edge class that you are using?

**Comment by moklick** [comment]
Released in v8.1.0
