### ISSUE TITLE
[Feature request] Node grouping

### ISSUE THREAD

**Issue by lqmanh** [wbkd/react-flow#558]
This feature serves 2 use cases:
1. Grouping nodes sharing similar characteristics: same category, steps in a phase,...
2. Making it possible to build ERD-like diagrams

My personal need is to build an ERD tool like the image below. I initially thought about using custom nodes, but it's hard to synchronize the position of foreign keys with their ports (handle ends). If we view tables as groups of nodes, it seems easier to implement.

![image](https://user-images.githubusercontent.com/20436482/95298696-b2a9d500-08a6-11eb-9dbb-27d005e362d9.png)

**Comment by chrtze** [comment]
Hi, if I understand your request correctly, a diagram like this should already be possible to build. Have you tried using multiple handles like in this example: https://reactflow.dev/examples/custom-node ?

**Comment by lqmanh** [comment]
@chrtze,
It's ok to do that, but I want to have 2 ends of the the handle precisely point to the FK field and PK field (like in the image above), not just point arbitraryly to the side of tables.
In the custom node example, we have to manually set top and bottom css. It's hard to determine where should we place handle ends.

**Comment by chrtze** [comment]
For that, you have to place the Handles inside the table row and position it relative to it. Example: https://codesandbox.io/s/vigilant-montalcini-mwou6?file=/src/App.js
