### ISSUE TITLE
For arrowHeadColor and defaultZoom

### ISSUE THREAD

**Issue by weimin-wati** [wbkd/react-flow#561]
Hello, there.
How's it going?
I've updated to the new version ("react-flow-renderer": "^6.1.1") and It seems not working arrowHeadColor and defaultZoom properties.
I mean the scale of the panel is setted as default 2.
So I setted up it to defaultZoom={1.0}, but it wasn't working.
Please let me know what problem is.
Regards.

**Comment by moklick** [comment]
Hey @weimin-wati 

we can't reproduce your issue. `arrowHeadColor` and `defaultZoom` are working fine. The default zoom is `1`. Maybe you are using `fitView` on load? That would overwrite the `defaultZoom` and `defaultPosition` props. 

Please provide a running code example (codesandbox or something similar) if you want to re-open this issue.
