### ISSUE TITLE
Loading message while waiting for nodes to render

### ISSUE THREAD

**Issue by chiester** [wbkd/react-flow#562]
Is there a way to show a loading icon or message while react-flow is rendering? I have a graph if 400+ nodes and it takes a few seconds to render.

**Comment by moklick** [comment]
You could set all elements `hidden=true` and then update the elements in the onLoad callback and set `hidden=false`;

**Comment by chiester** [comment]
Wouldn't the result be the same--a blank zoompane until the render is finished?

**Comment by moklick** [comment]
You could add a variable `isLoading` which is `true` by default and then set this variable to `false` inside the onLoad callback. And display the loading message when `isLoading` equals `true`.
