### ISSUE TITLE
Controls issues

### ISSUE THREAD

**Issue by chiester** [wbkd/react-flow#563]
Did something change with controls in a recent update? I find that now, all of the controls (zoom in, zoom out, and fitView) all cause the graph to max zoom. Scroll to zoom stops working.

**Comment by moklick** [comment]
I can't reproduce this. Can you create a code sample (codesandbox or something similar)

**Comment by code-guru** [comment]
I'm also experiencing similar issue, not sure what cause it, and how to reproduce? I have scroll on zoom enabled. Something the zoom to the max, and controls stop working.

**Comment by code-guru** [comment]
You can produce the bug, with enabling `zoomOnScroll` and `maxZoom` at the same time. And it happen with the first scroll event.

**Comment by moklick** [comment]
Thanks for the hint. A fix is released in 6.1.3!
