### ISSUE TITLE
Custom events on nodes - double click?

### ISSUE THREAD

**Issue by bobbysciacchitano** [wbkd/react-flow#565]
Hi, I'm starting to get my head around react-flow and was wondering what would be the best way to trigger a double click event on a node, would I just do this on a custom node component or is there some why I can bubble up an event to the root component.

Thanks

**Comment by moklick** [comment]
The easiest way would be to pass a div element as a label and add your `onDoubleClick` handler there (you would need to change the styling a bit to receive the event not only on the label but on the whole node). The best way would be to create a custom node with a `onDoubleClick` handler.
