### ISSUE TITLE
Need more nodes

### ISSUE THREAD

**Issue by meltemgursoy** [wbkd/react-flow#566]
How can I create 3 target nodes and 3 source nodes?

**Comment by moklick** [comment]
Hey @meltemgursoy 

do you mean nodes or handles inside nodes?

**Comment by meltemgursoy** [comment]
Hi @moklick 

Actually, I found a solution. I want to create more than 1 connection. I checked your [custom node example](https://github.com/wbkd/react-flow/tree/main/example/src/CustomNode). I was trying to make implementation for my case. So, this is my basic custom node comp. Maybe will help for .tsx lover.

`import React, { memo } from 'react';
import { Handle, HandleProps } from 'react-flow-renderer';

interface Props {
  type: any
  position: any
  style: any
}
export default React.memo(props => {
  const node1 = {
    type: "target",
    position: "left",
    id: "t1"
  } as HandleProps

  const node2 = {
    type: "source",
    position: "right",
    style: { top: 10, background: '#555' },
    id: "s1"
  } as HandleProps

  const node3 = {
    type: "source",
    position: "right",
    style: { top: 'auto', background: '#555' },
    id: "s2"
  } as HandleProps

  return (
    <>
      <Handle {...node1}></Handle>
      <div>
        Custom Node
      </div>
      <Handle {...node2}></Handle>
      <Handle {...node3}></Handle>
    </>
  )
})`

**Comment by moklick** [comment]
ok, cool :)
