### ISSUE TITLE
Resizable nodes

### ISSUE THREAD

**Issue by SathishRaju** [wbkd/react-flow#570]
Can I resize a node? I don't see any options. Is this in the roadmap or is there any workaround?

**Comment by chrtze** [comment]
Hi, this should be possible with a custom node that implements the resize functionality. Internally, size changes of the nodes are already monitored and causing re-renders. Currently, we are not planning on making this a core feature or property.

**Comment by SathishRaju** [comment]
Thanks, will try that!

**Comment by shyam-infraon** [comment]
Hey @SathishRaju, were you able to get this done?
