### ISSUE TITLE
Grid lines or dots not rendering

### ISSUE THREAD

**Issue by dPacc** [wbkd/react-flow#577]
While moving the pane, the grid lines or dots do not render at certain points. This was working earlier in version 3.2.4, but the bug appears to be in the latest version.

![grid](https://user-images.githubusercontent.com/36117641/95840423-29d2e380-0d55-11eb-89a8-3b2dcb677179.png)

**Comment by moklick** [comment]
I already tried to fix this bug. It is really strange what is going here. We are dynamically creating a svg which is used as a repeated background image. The svg only includes a `<circle />` element. I can't explain why it is not always rendered and I don't see a pattern. Maybe these are rounding errors?

**Comment by Shaquu** [comment]
What is ETA to fix/merge PR it?

**Comment by dPacc** [comment]
Wondering the same, waiting for it to be merged, if the fix works.

**Comment by moklick** [comment]
Unfortunately the solution is not working. The PR is still open, because @AndyLnd is still working on it.

**Comment by ryanwr** [comment]
I've had a go at fixing this and appears to be working for me, would be good to get opinions/confirmation.

https://github.com/wbkd/react-flow/pull/835

**Comment by moklick** [comment]
Thanks @ryanwr! Works perfectly fine :) 

released in v8.3.6
