### ISSUE TITLE
On Deleting a custom node using removeElements doesnt remove the outgoing edges

### ISSUE THREAD

**Issue by shyam-infraon** [wbkd/react-flow#580]
Hi, I have made a custom node and when I am trying to delete a node, which has and incoming edge, it deletes properly.
When I am trying to delete the node which has an outgoing edge using removeElements, the edge doesnt get deleted.
Can you take a look at this.
Thanks in advance

![Screenshot_2020-10-14 React App](https://user-images.githubusercontent.com/52315201/95983372-2025aa80-0e3f-11eb-99fd-00d61503a4d5.png)

**Comment by shyam-infraon** [comment]
Also noticed that the edge which is created, the source id has "__b" attached to it, which might be causing the issue.

**Comment by moklick** [comment]
Hey @shyam-infraon 

probably there is an issue with your ids here? Could you create a code sample (for example a codesandbox)?

**Comment by shyam-infraon** [comment]
I created the following sandbox, try deleting the custom node.
[URL](https://codesandbox.io/s/musing-goldberg-8x3mu)

**Comment by moklick** [comment]
When I delete the custom node, all edges are deleted too. Which is the expected behaviour.

**Comment by shyam-infraon** [comment]
So did u check the sandbox that i created,i have recreated the scenario.
1. Click on the Custom node once to select it.
2. Click on the delete button at the top right.
The error should be visible.
Here is the sandbox link: [https://codesandbox.io/s/musing-goldberg-8x3mu](https://codesandbox.io/s/musing-goldberg-8x3mu)

**Comment by moklick** [comment]
Ok, got it (I didn't see the delete button). You also need to pass the connected edges the `removeElements` function:

```javascript
  const deleteNode = () => {
    console.log("currElements", elements);
    console.log("element", currElem);

    const edges = elements.filter(e => isEdge(e));
    const connectedEdges = getConnectedEdges([currElem], edges);
    const elementsToRemove = [currElem, ...connectedEdges];
    setElements((els) => removeElements(elementsToRemove, els));
  };
```

The function `getConnectedEdges` gets exported:

```javascript
import { getConnectedEdges } from 'react-flow-renderer';
```

**Comment by shyam-infraon** [comment]
Thank You, it worked. It would be better if this gets mentioned in the docs for people stuck at the same issue.
Summing up for future reference: 
removeElement usually removes a node and the corresponding edges attached to it, but when we use a custom node, we need to retrieve all the edges and pass it to the removeElement along with the current node.

Thanks again, its a wonderful library though.. !!
