### ISSUE TITLE
couldn't create edge for source id:

### ISSUE THREAD

**Issue by mehuljariwala** [wbkd/react-flow#581]
I use 2 ReactFlow render in different page in React some time is showing me this error can you help @moklick

**Comment by moklick** [comment]
When you have multiple flows you should wrap your flows with the `<ReactFlowProvider>` component. This ensures that every flow has its own store https://reactflow.dev/docs/api/components/provider/. Does this fix your issue?

**Comment by mehuljariwala** [comment]
It's work. Thanks for quick response.

**Comment by md-tasnim-adnan** [comment]
I am following the layouting example in one of my projects. The graph gets generated perfectly when the component renders but when I try to connect to another node or delete a node I am getting this same error. If you could please give me any idea what I am doing wrong @moklick
