### ISSUE TITLE
set new id to existing node or edge

### ISSUE THREAD

**Issue by yasserbouchareb** [wbkd/react-flow#584]
I wanna to assign a new id to my node and edge that I am getting from the server, but when I set the new id to the node
and try to create a new edge from that node I get the Error: Can't create edge. Node with id=... does not exist.

how can I set  a new id  to edge or node to avoid this error ?

I saw the function setConnectionNodeId from Action store. Is that function set the Id ? if yes how to use it, what is the input 
schema of that function ?

Thanks in advance

**Comment by meltemgursoy** [comment]
This error comes when the id is not string type. Please check that. Hope it will help.

**Comment by yasserbouchareb** [comment]
Thanks @meltemgursoy, the Id type one of Two mistakes that I made.
And my second mistake is that I didnt update the store elements with new IDs, I jsut update the elements IDs of the GrapgView component. 

Thanks a lot.
