### ISSUE TITLE
selectedElements can contain not existing elements

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#585]
## Issue

`selectedElements` has an element with id "43kWoKwibhR", but there is no element with this is in `elements`.

![image](https://user-images.githubusercontent.com/13085980/96169911-2ee58d80-0f23-11eb-9783-897f7b10f487.png)

## Reproduce

* Render nodes
* Select a node
* Replace the nodes with different nodes

I know this issue's description is dense. Please give me a first hint, if this is known, already solved, or clear as it is. Otherwise I can provide more details and maybe come up with a minimal example how to reproduce this state. Thanks a lot.

## Version

v4.7.1

## Related

Related issue: https://github.com/wbkd/react-flow/issues/492

**Comment by moklick** [comment]
The current version is 6.3.1 but you will encounter the same issue (I would update anyway ;)).

Did you try to clear the selected elements with `setSelectedElements([])` before you replace the nodes?

**Comment by andys8** [comment]
Yes, need to update at some point ;)

I didn't try, mainly because I think it was introduced in a later version.

But in case it works: Should the user need to use the state store hook to get a reference to `setSelectedElements`, then call it with an empty array to make sure the selection is resetter? I was surprised the state kept a selection that doesn't exist. So it might be possible to do this, but I think it would be better if the user wouldn't have to "reset" `react-flow` internal selection state.

**Comment by moklick** [comment]
Hey @andys8 

we will not fix this issue because the internal state and actions are are only a workaround for now. We will add more hooks and helpers that are documented and work as expected.
