### ISSUE TITLE
How can I change the actual shape of the node?

### ISSUE THREAD

**Issue by ralppppy** [wbkd/react-flow#586]
Basically, I want to make a basic flowchart shapes, is there any way to do it?

**Comment by yasserbouchareb** [comment]
You just need to provide a style option to your object like this :
`<ReactFlow
            elements={[
              {
                id: '1',
                type: 'input',
                data: { label: 'Node 1' },
                position: { x: 250, y: 5 },
                **style: {
                  border: '1px solid black',
                  width: '80px',
                  height: '80px',
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                },**
              },
            ]}
          ></ReactFlow>`

![image](https://user-images.githubusercontent.com/13304202/96225930-1f515d80-0f92-11eb-84df-72dd083c89c9.png)

**Comment by ralppppy** [comment]
I've tried this approach but I've encountered a problem, You need to use skew() to create a Parallelogram, but if you do it the Label text will also be affected. As you can see in the image, and I think we will encounter another problem in other shapes as well, I think this is a really good enhancement for this library if this will be done easily, Or even builtin shapes options will do. Maybe we can just add .{.., shape: "circle | rectangle | diamond | parallelogram | Document |, etc.." }. 
![image](https://user-images.githubusercontent.com/44341206/96228799-9c97c500-0fc8-11eb-9888-1d9b0ed066c8.png)

**Comment by yasserbouchareb** [comment]
As workaround, you can create your own custom node of new type (parallelogram), and pass a nodeTypes object to the ReactFlow component like that :  
```
nodeTypes={{
  parallelogram: YourCustomNode
}}
```
check Node Types & Custom Nodes section for more details [https://reactflow.dev/docs/api/node-types/](url)

Now you should create YourCustomNode using handles (check Handle Component section :  [https://reactflow.dev/docs/api/handle/](url) )

As example I create parallelogram custom node (Typography is material UI component) :

```
<>
      <Handle
        type="target"
        position="left"
        // style={{ background: '#555' }}
        onConnect={(params) => console.log('handle onConnect', params)}
      />
      {/* <Grid container justify="space-around">
        <ReceiptIcon />
        <Typography>{label}</Typography>
      </Grid> */}
      <Typography
        align="center"
        style={{ textTransform: 'capitalize', fontSize: '12px',  transform:'skew(-10deg, -10deg)' }}
      >
        {label}
      </Typography>
      <Handle
        type="source"
        position="right"
        // style={{ background: '#555' }}
        onConnect={(params) => console.log('handle onConnect', params)}
      />
    </>
```
And now just call you ReactFlow component with your custom element ( type: 'parallelogram' ) with skew(10deg, 10deg) and reverse the skew with  skew(-10deg, -10deg)  in your custom node Typography styling in above.

```
<ReactFlow
            elements={[
              {
                id: '1',
                type: 'parallelogram',
                data: { label: 'Node 1' },
                position: { x: 250, y: 5 },
                style: {
                  border: '1px solid black',
                  width: '150px',
                  height: '150px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  transform: 'skew(10deg, 10deg)',

                },
              },
            ]}
            nodeTypes={nodeTypes}
          ></ReactFlow>
```

This is just a workaround, maybe there is a way to handle this just with css, but I am not good in it, so I hope this help.

**Comment by ralppppy** [comment]
Thank you. I will try this.

**Comment by moklick** [comment]
thanks @yasserbouchareb 👍
