### ISSUE TITLE
onConnect doesn't fire for both handles of the Edge

### ISSUE THREAD

**Issue by nadenf** [wbkd/react-flow#588]
**Recreate:**
1) Drag two nodes onto the grid each with a handle.
2) Add onConnect handlers for both handles.
3) Create a new edge between the two nodes. 

**Expected:**
Both onConnect handlers should fire since a connection has been established between both nodes.

**Actual:**
Only the source onConnect handler will fire.

**Comment by chrtze** [comment]
For the custom handles, the onConnect event only fires for source handles. This is because we do not have a reference to other handles in that component itself. For listening to the onConnect event, you should use the onConnect handler on the top level `ReactFlow` component.

**Comment by Rob-Fletcher** [comment]
Sorry to revive this, but if this is the case for custom handles, how can you do custom onConnect behavior for different nodes? I have different node types that each need their own custom onConnect so I cant use just the top level onConnect from ReactFlow. Is there some workaround for this?

**Comment by ahodgk** [comment]
@Rob-Fletcher did you ever find a solution to this? I'm having the same problem and moving the logic up to the `ReactFlow` component seems cumbersome.
