### ISSUE TITLE
nodesDraggable property for ReactFlow component isn't working

### ISSUE THREAD

**Issue by tkao-cursive** [wbkd/react-flow#592]
I've set `nodesDraggable` to `false` in the `ReactFlow` component, but I'm still able to drag it around on the screen. Am I missing something or possibly setting that property incorrectly?

`
                                <ReactFlow
                                    className={styles.flowContainer}
                                    nodesDraggable={false}
                                    nodesConnectable={false}
                                    elementsSelectable={false}
                                    selectNodesOnDrag={false}
                                    elements={currentProcessMap.elements}
                                    nodeTypes={{
                                        decisionNode: DecisionNode,
                                        eventNode: EventNode
                                    }}
                                />
`

Thanks in advance!

**Comment by moklick** [comment]
Your setup seems fine. Nodes should not be draggable when you set  `nodesDraggable=false`. When you don't want to allow to drag the pane you need to set `paneMoveable=false`. Can you open a codesand box or something similar?

**Comment by tkao-cursive** [comment]
ah ok it looks like i just missed one of the configs in the node object 

`draggable: boolean - if option is not set, the node is draggable (overwrites general nodesDraggable option)`

so to make nodes not draggable, you have to set that for each node.

thanks for taking the time to help me @moklick

**Comment by nmilev-cursive** [comment]
@moklick 
I would say this is undesired behaviour.
If you don't set the individual `draggable` value for each node, the nodes do not inherit the `nodesDraggable` value from `ReactFlow` component but just set `true` and override any global behaviour, rendering `nodesDraggable` redundant.
