### ISSUE TITLE
State: isInitialized

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#60]
We need an initialized state internally that should be true after first render happened. We should not call `onLoad` until `isInitialized` is `true`.

Right now we can't call `fitView` on load for example because the graph is still empty.

**Comment by jeremypeters** [comment]
I've just run into this issue where I need to call `fitview` after the map has initialized - currently I'm having to use a timeout which is a tad nasty and also means I have to hide the map until `fitview` has been called.

**Comment by moklick** [comment]
You should be able to call `fitView` inside the `onLoad` callback https://github.com/wbkd/react-flow/blob/master/example/src/Stress/index.js#L40

**Comment by jeremypeters** [comment]
Hi @moklick 

I am - still need a timeout within it.

**Comment by moklick** [comment]
Do you get an error or has the `fitView` call no effect? Could you provide an example?

**Comment by moklick** [comment]
I’m closing this issue because it has been inactive for a few months.
