### ISSUE TITLE
request: graph serialization example

### ISSUE THREAD

**Issue by MadSciencist** [wbkd/react-flow#603]
Hey,

whats the proper way to serialize the graph elements (AKA graph export)?  Is there any high level API for that?
The only way I found is to take redux state and replace the 'position' object of flow element with __rf.position.

Thanks

**Comment by moklick** [comment]
Hey,

right now that would be the solution. I think it would be a good idea to do this inside the `getElements` function so that users don't have to do it.

**Comment by glebfeklistov** [comment]
> Hey,
> 
> whats the proper way to serialize the graph elements (AKA graph export)? Is there any high level API for that?
> The only way I found is to take redux state and replace the 'position' object of flow element with __rf.position.
> 
> Thanks

You need to operate all "on...End" events and serialize event if you want to save changed state, example when you want to send data to server

**Comment by qihuagao** [comment]
Thanks for the great work,  lookiing forward to this feature too.

**Comment by qihuagao** [comment]
better to have different kinds of shapes, but may conflict with other designs....

**Comment by moklick** [comment]
Hey @MadSciencist 

do you think it would be enough to get `elements` and `transform` (position + zoom) from the new serialize function? Or do you need any more information?
