### ISSUE TITLE
how to remove the elements？

### ISSUE THREAD

**Issue by llz30811** [wbkd/react-flow#604]
the examples have this method， but how to trigger this method。

**Comment by volkan-a** [comment]
Hello,

It's in the props.

`<ReactFlow onElementsRemove={handleRemoveElement} ...>`

**Comment by moklick** [comment]
The function is triggered when you press backspace. You can define any other key with the `deleteKeyCode` prop.

**Comment by llz30811** [comment]
ok, thank you
