### ISSUE TITLE
Custom node gets outdated version of elements

### ISSUE THREAD

**Issue by volkan-a** [wbkd/react-flow#605]
Hi there,

I have a custom node implementation:

```javascript
const node: Node = {
      id: shortid.generate(),
      position: getRandomCoordinates(),
      type: typeName,
      data: {
        handleRemove: function () {
          RemoveElement(elements.filter((e) => e.id === node.id));
        },
      },
}
```

Node has a context menu and an item which calls `handleRemove` I'm accessing an outdated find (only the elements added before that node).

So, how can I get or update actual elements?

**Comment by moklick** [comment]
Hey @volkan-a, 

could you open a codesandbox or something similar? You need to keep track of the elements. So you should have them in your state.

**Comment by volkan-a** [comment]
Hi @moklick 

Here you can find a [demo](https://codesandbox.io/s/customnodegetoutdatedelements-q63z9
).

When you add a new custom node and click on it you get an outdated copy of elements, not parents current state.

**Comment by moklick** [comment]
This is not really related to react-flow but to react in general. However If you need access to the current elements inside you custom node it is easier to access them via:

```javascript
import ReactFlow, { useStoreState } from 'react-flow-renderer';

const CustomNode = (props) => {
  const elements = useStoreState(state => state.elements);

  return <div>your custom node</div>;
}
```
