### ISSUE TITLE
Need onDropEvent

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#606]
@moklick I an developing a feature where user can drop a div on the canvas to create a node at that particular place. I will be needing an onDrop(e: MouseEvent) to get the position where the user has dropped the div.

Please let me know if there is any other way to implement this apart from onDropEvent.

**Comment by andys8** [comment]
What you can do, is add a wrapping div with `onDrop` listener. `clientX` and `clientY` from the event, project them with `projectPosition` and add the node to the graph data yourself.

**Comment by moklick** [comment]
Thanks @andys8 

that is the best solution for the current version.

**Comment by agarwal00s** [comment]
How to get the exact position when the pane is zoomed in or zoomed out?

**Comment by andys8** [comment]
Isn't `projectPosition` taking zoom into account?

**Comment by moklick** [comment]
The `project` function that you receive from the instance gives you the correct position https://reactflow.dev/docs/api/react-flow-instance/
