### ISSUE TITLE
Custom image node with label outside the shape 

### ISSUE THREAD

**Issue by prudhvi-a1** [wbkd/react-flow#607]
Is it possible to achieve the following using custom node 

1. Node (Circle, rectangle, diamond) with an image and label outside of the shape 
2. Icons menu similar to the one in the image below on selection of the node 
![image](https://user-images.githubusercontent.com/13631499/96582271-a8e98e00-12f8-11eb-8396-019198b2cc57.png)

**Comment by moklick** [comment]
Hey, yes you can do this with a custom node.
