### ISSUE TITLE
Custom Elements should have access to current state

### ISSUE THREAD

**Issue by austincondiff** [wbkd/react-flow#608]
Custom node and custom edge components should have access to current state via props. For example the custom edge component should get `sourceElement`, `targetElement`, and `elements` props. I'd like to be able to change the edge when a node it is connected to is selected.

**Comment by moklick** [comment]
When you need to access elements inside a custom edge component you can get them from the store:

```javascript
import ReactFlow, { useStoreState } from 'react-flow-renderer';

const CustomEdge =  () => {
  const elements = useStoreState(state => state. elements);

  return null;
}
```

I will add the props to the docs that get passed to a custom edge.

**Comment by moklick** [comment]
you can find the list of passed props here https://reactflow.dev/docs/api/edge-types/
