### ISSUE TITLE
Multi-select

### ISSUE THREAD

**Issue by austincondiff** [wbkd/react-flow#609]
It would be nice to select multiple nodes by clicking while holding the shift key. That would allow us to drag to move multiple nodes at once.

**Comment by amcdnl** [comment]
I think CMD/CTRL would probably be better since SHIFT usually indicates a range.

**Comment by austincondiff** [comment]
@amcdnl That is true when looking at a list such as a file explorer. Applications where there is a canvas like Photoshop, Illustrator, Sketch, Figma, etc., ctrl/cmd is a modifier and shift will select multiple objects.

**Comment by austincondiff** [comment]
I did notice that in the `storeState`, `selectedElements` is an array, so I assume this is already doable or in is planned?

**Comment by moklick** [comment]
Right now it's used for the dragging multi-selection. I think we will add a multi select by clicking too.

**Comment by moklick** [comment]
Multi selection is released in v7.1.0. You can define the key with the new `multiSelectionKeyCode` option.

**Comment by apurvns** [comment]
How to make multiselect work in mobile device ? As CTRL/SHIFT not possible in mobile..
