### ISSUE TITLE
Multiselection bug - not all nodes are selected

### ISSUE THREAD

**Issue by MadSciencist** [wbkd/react-flow#610]
Hey,

Under some very specific circumstances there appears to be bug with multiselection - sometimes not all nodes under the selection area are actually selected. 
GIF:
![multiselectBug2](https://user-images.githubusercontent.com/16021818/96601034-e3036180-12f1-11eb-88f4-3a25c6ec5c33.gif)

**Comment by moklick** [comment]
Should be fixed in v6.2.0
