### ISSUE TITLE
[FEATURE] Nested Nodes

### ISSUE THREAD

**Issue by amcdnl** [wbkd/react-flow#611]
## Request
I have a custom workflow component that I wrote that supports nested nodes/edges. I was wondering if this would be possible with your solution and if not if you are open to it.

## Example
![image](https://user-images.githubusercontent.com/227909/96731303-1a6f1e00-1385-11eb-80ce-a02dda9534d0.png)

In the above, it has a "loop" which a user can drag nodes into and connect nodes together from inside the loop.

**Comment by moklick** [comment]
Is this a kind of sub-flow inside a node?

**Comment by amcdnl** [comment]
Yes, this is using ELKJS for layout and my own react/svg component engine. Its essentially a node that contains another "canvas" / layout / etc in it. 

In that code I wrote, I essentially just see that the node has "children" and render a group positioned > rect outline > node/edge[] recursive render call.

**Comment by justrhysism** [comment]
Yeah, I've come up against this just now also (@amcdnl thanks for your suggestion of ELK in another issue, it's saved me a huge amount of time trying to generate bi-directional layouts!).

I've been able to emulate the appearane of groups; but unfortunately, I'm struggling to find a (non-hacky) way of moving all the child nodes when the group is dragged.

**Comment by nowachri-de** [comment]
Hello,

this feature would be awesome to have !!

**Comment by justrhysism** [comment]
I'd be happy if it wasn't part of the core, but had a plugin or function which facilitated it.

**Comment by amcdnl** [comment]
> Is this a kind of sub-flow inside a node?

Yes - I made a quick video of my app that uses ELK + React/SVG Components that I built to show how this works in my implementation. This implementation only supports 1 level though. https://www.screencast.com/t/50Luy02V9

**Comment by amcdnl** [comment]
> Yeah, I've come up against this just now also (@amcdnl thanks for your suggestion of ELK in another issue, it's saved me a huge amount of time trying to generate bi-directional layouts!).

@justrhysism - Glad to hear - the API is pretty awful but once you get it going you don't really need to tweak it much.

**Comment by moklick** [comment]
> > Is this a kind of sub-flow inside a node?
> 
> @moklick Yes - I made a quick video of my app that uses ELK + React/SVG Components that I built to show how this works in my implementation. This implementation only supports 1 level though. https://www.screencast.com/t/50Luy02V9

This looks pretty amazing! I think we won't add a nested flow functionality to the core but we could check if it would be already possible to implement this feature on top of react flow or if there is anything missing.

**Comment by amcdnl** [comment]
@moklick - Thanks! Ya, that would be helpful to know and maybe some guidance if possible.

**Comment by meatflavourdev** [comment]
+1 for this

**Comment by steinhardt21** [comment]
+1 for this too, much needed feature

**Comment by amcdnl** [comment]
I ended up writing my own library to support this - example here: https://reaflow.dev/?path=/story/demos-nested--edges

**Comment by steinhardt21** [comment]
@amcdnl amazing example! Did you integrate react-flow in your solution?

**Comment by amcdnl** [comment]
No - its not react-flow - I ended up building my own library - https://reaflow.dev

**Comment by steinhardt21** [comment]
Wow, I understand! Cuold be your library used in combination with react-flow to build nested nodes?

**Comment by mmairs9** [comment]
+1 would love to see this feature added. Would it be possible to achieve with creating another workflow within a custom node?

**Comment by JSLKM** [comment]
+ 1 for this!

**Comment by taufiqibrahim** [comment]
desperately +1 for this!

**Comment by Apap33** [comment]
+ 1. This would help separating a set of nodes in a flow.

**Comment by Apap33** [comment]
+1. This would help separating a set of nodes in a flow.

**Comment by moklick** [comment]
I will collect new feature ideas in the "Discussions/New Features" section. This issue will be closed in favour of #1024
