### ISSUE TITLE
[FEATURE] Keyboard Navigation

### ISSUE THREAD

**Issue by amcdnl** [wbkd/react-flow#616]
## Request
For a11y and general ease of use, it would be ideal for keyboard navigation for things like arrow keys and enter.

**Comment by moklick** [comment]
You would like to pan the flow with the arrow keys? What would the enter key trigger?

**Comment by amcdnl** [comment]
Ya - I think you could do something like if a node is NOT focused, then pan?

**Comment by moklick** [comment]
We will not add this feature to React Flow. iIn my opinion, there are too many different possibilities and ways of thinking about how keyboard handling could be used here.

**Comment by ks2211** [comment]
I know this issue is closed but if you still need to implement this, in reactflow v10, you can use the `useKeyPress` hook + set an instanceRef on the reactflow element to get the `instanceRef.current.setViewport({x: x, y: y, zoom: zoom})` to pan the canvas around

**Comment by dwjohnston** [comment]
@moklick I just found this issue searching for this. 

An argument for making drag and drop libraries accessible keyboard is also for _testing_. 

It's much easier to test your application with tools like Cypress if you can simulate interaction with it via keyboard presses.

**Comment by moklick** [comment]
Good point @dwjohnston thanks for bringing this up again! I'll think about it.
