### ISSUE TITLE
How to access selected prop of a node

### ISSUE THREAD

**Issue by jamesscaggs** [wbkd/react-flow#619]
Is it required to use the provider component to get access to the selected prop of a node?

For example if I want to render some data based on a selected node?

**Comment by moklick** [comment]
You can find the list of passed props [in the docs](https://reactflow.dev/docs/api/node-types/#custom-node-props). `selected` is part of it.

**Comment by jamesscaggs** [comment]
@moklick I see all of the other props but I'm not seeing the selected property available when logging out a demo component that is selectable and has a selected state.

https://cln.sh/PO2b8c

**Comment by jamesscaggs** [comment]
![image](https://user-images.githubusercontent.com/15598224/96902134-bf5b2b00-1459-11eb-9e03-803d93d9ba7f.png)

**Comment by moklick** [comment]
Ok, I thought that you are implementing a custom node. I am not sure about your use case here. Could you use the `onSelectionChange` handler to receive the selected node?

**Comment by jamesscaggs** [comment]
My use case is a user should be able to select a node and click a delete button to remove the selected node.

I am using the helper function below from the docs:
```
const onElementsRemove = (elementsToRemove) =>
    setElements((els) => removeElements(elementsToRemove, els));
```

I want to do something like this:
```
const elementsToRemove = elements.filter(el => el.selected === true)
```

**Comment by jamesscaggs** [comment]
@moklick Did you see this? Don't want to bug you if so but I'm not sure if closed issues are sending you notifications.

**Comment by moklick** [comment]
Hey @jamesscaggs 

no worries! I would recommend to use the `ReactFlowProvider`. Then you can get the `selectedElements` from the store. 

```javascript
import { useStoreState } from 'react-flow-renderer';

...

const selectedElements = useStoreState((store) => store.selectedElements);
```

Otherwise you would need to keep track of the selected elements by using `onSelectionChange`.

**Comment by jamesscaggs** [comment]
Great, thanks a ton for the awesome response times!

**Comment by wghglory** [comment]
How to get the styles for the selectedElements? I want to copy and clone a new one based on the selected, but couldn't find styles
