### ISSUE TITLE
Integration with Leaflet

### ISSUE THREAD

**Issue by austincondiff** [wbkd/react-flow#620]
It would be great to layer React Flow on top of a map to open this to location-based visualizations. Would this even be possible?

Here is an example without the map I put together.

https://codesandbox.io/s/networked-map-markers-bfcp4

Just imagine how it might look with a map underneath.

**Comment by chrtze** [comment]
wow! that is a crazy use case for react-flow. I am not sure if it is possible to abstract that functionality and build it into the core of the library. could you provide some pseudo code how you would expect react-flow to work in that case?

**Comment by chrtze** [comment]
I think this is not something that we can support from this library. Maybe a way of doing this would be to sync the positions of the elements with the map (`map.containerPointToLatLng`). There are also some network visualization plugins for leaflet already existing (for example https://github.com/danwild/leaflet-network).
