### ISSUE TITLE
[LOST FEATURE] onChange event

### ISSUE THREAD

**Issue by glebfeklistov** [wbkd/react-flow#621]
Can handle onChange event when change every think, node dragging, edge connected, elements added or removed?

**Comment by chrtze** [comment]
hi, can you give an example of how you would like to use an onChange property? which arguments should we hand to the listener?

**Comment by glebfeklistov** [comment]
Just return state on editor, for save graph.

**Comment by moklick** [comment]
You can use `onMove` (or better `onMoveEnd `) for checking panning and zooming behaviour in combination with `onNodeDragStop` to achieve this. We won't combine these events because they are different matters.

**Comment by glebfeklistov** [comment]
Its not usefull

**Comment by glebfeklistov** [comment]
I need one event for send to server updated graph state, else I needed to listen all "on...End" events and operate them all. It's not useful when we can haw one event
