### ISSUE TITLE
onChange event

### ISSUE THREAD

**Issue by glebfeklistov** [wbkd/react-flow#627]
I need one event for send to server updated graph state, else I needed to listen all "on...End" events and operate them all. It's not useful when we can haw one event

**Comment by chrtze** [comment]
https://github.com/wbkd/react-flow/issues/621#issuecomment-714322297

as @moklick pointed out, we will not implement an onChange in the near future. what you want to achieve is already possible by using `useStoreState` from `react-flow-renderer`.

**Comment by glebfeklistov** [comment]
useStoreState - change when interaction on progress, we needed event when interaction ended
