### ISSUE TITLE
Custom node types should default to react-flow__node-default className

### ISSUE THREAD

**Issue by jamesscaggs** [wbkd/react-flow#628]
It looks like it is required to specify styling for a custom node type explicitly. 

Am I missing something? It seems like a custom node type should inherit styles from the default nodes if not specified.

**Comment by moklick** [comment]
The default styles are just dummy styles. We think it's better to start with a unstyled node instead of having to overwrite a default style. Would it help if we add this information to the docs?

**Comment by jamesscaggs** [comment]
Yes it would be nice to have in the docs. Thx!
