### ISSUE TITLE
[BUG] Getting an error when I try to import ReactFlowProps

### ISSUE THREAD

**Issue by akernizan** [wbkd/react-flow#631]
I am trying to access the react flow props, but my application keeps throwing an error. Is there something I'm missing with this import?

**How I'm importing**
`import ReactFlow, {
  MiniMap,
  Controls,
  Background,
  ReactFlowProps,
} from 'react-flow-renderer';`

**Error**
`The requested module '../../web_modules/react-flow-renderer.js' does not provide an export named 'ReactFlowProps'`

**Comment by chrtze** [comment]
hi, which version are you using? the export was added in 6.1.1 https://github.com/wbkd/react-flow/issues/539

**Comment by akernizan** [comment]
I'm using version 6.1.3

**Comment by chrtze** [comment]
tried to reproduce it here: https://codesandbox.io/s/staging-wood-pmnlk?file=/src/App.tsx
