### ISSUE TITLE
Can't access position property in a Node type

### ISSUE THREAD

**Issue by ClaitonBarreto** [wbkd/react-flow#633]
### Issue:
If try access the position property of last item with node type rendered, typescript gives the follow error: 

> **Typescript error in path/to/file.ts
> Property 'position' does not exist on type 'Node | Edge'.
>  Property 'position' does not exist on type 'Edge'.  TS2339**

### Initial elements
```javascript
const initialElements:(Node|Edge)[] = [
  {
    id: '1',
    type: 'input',
    data: {
      label: (
        <>
          Welcome to <strong>React Flow!</strong>
        </>
      ),
    },
    position: { x: 0, y: 0 },
  }
```

if try read the position property, i catch the error. There is a limitation in relation the properties of Node type?

**Comment by moklick** [comment]
Hey,

could you try to use the `isNode` helper function to check if it's a node before you try to read the position?

**Comment by ClaitonBarreto** [comment]
> Hey,
> 
> could you try to use the `isNode` helper function to check if it's a node before you try to read the position?

Hey there, 

I'm actually doing the opposite.
Before trying to extract the position, i use the isEdge function for remove all Edge type items. But if you think necessary, i can do just that

**Comment by ClaitonBarreto** [comment]
![git](https://user-images.githubusercontent.com/34696974/97087260-41d11f80-15ff-11eb-9ee9-d6721fee71bd.jpg)

Using the vs code helper, these are apparently the only properties accessible

**Comment by moklick** [comment]
Could it be that these are the edge options?

**Comment by ClaitonBarreto** [comment]
> Could it be that these are the edge options?

it seems so, but i have certainly that i using this function to filter the elements:

```javascript
function removeEdgesElements(elements:(Node|Edge)[]) {
  return elements.filter(el => {
    return isNode(el)
  })
}
```

**Comment by moklick** [comment]
You you need to specify that the filtered elements is a `Node` array:

```javascript
function removeEdgesElements(elements:(Node|Edge)[]) {
  return elements.filter(el => {
    return isNode(el)
  }) as Node[]
}
```
