### ISSUE TITLE
Adding an ICON to a node + Styling

### ISSUE THREAD

**Issue by yaronrl** [wbkd/react-flow#634]
Newbie question, is there a guide (or examples) that show all the options of how to style the nodes?
I discovered through some trial and error and looking at the examples that I can add HTML code under the label like this:

`id: '3',
    data: {
      label: (
        <>
          <img src={browserIcon} alt="English" height="32" />
          This one has a <strong><i>custom style</i></strong>
        </>
      ),
    },`

But I can't figure out how to style it without styling the entire node. I tried some CSS but it didn't like it.
I am trying to create something similar to this.

![Screen Shot 2020-10-26 at 10 28 06 PM](https://user-images.githubusercontent.com/15719616/97253499-91b80e00-17da-11eb-829b-2e5d2327804d.png)

**Comment by moklick** [comment]
You can create a custom node or pass a React Node to the label option. Styling can be done with inline styles or class names. 

Please post questions about the general usage at stackoverflow with the tag `react-flow`, so that we can focus on bugs and feature requests in the github issues.
