### ISSUE TITLE
Unable to render two instances of react-flow on the same page

### ISSUE THREAD

**Issue by pSnehanshu** [wbkd/react-flow#640]
I am trying to render two instances of react-flow on to a page, but it doesn't work. Seems like there's some kind of infinite rendering loop. I have attached a codesandbox link to demonstrate.

https://codesandbox.io/s/zealous-jackson-rdm0x

**Comment by moklick** [comment]
When you have multiple flows on a page you need to wrap them with the `ReactFlowProvider` component. We will add this to the docs!

**Comment by pSnehanshu** [comment]
@moklick Nah! It still doesn't work. See https://codesandbox.io/s/pedantic-sanderson-idct7

**Comment by moklick** [comment]
You need to wrap each flow with the `ReactFlowProvider`.

**Comment by scasab** [comment]
I tryied with a provider and doesnt work for me... Do you have a sample?

**Comment by scasab** [comment]
Finally wors for me. The diference was in use two ReactFlowProvider: 


            <ReactFlowProvider>
                <ReactFlow
                    onLoad={onLoad}
                    elements={nodosVentaGenerica}
                    onElementClick={onElementClick}
                    onElementsRemove={onElementsRemove}
                    onConnect={onConnect}
                    onNodeDragStop={onNodeDragStop}
                    onLoad={onLoad}
                    snapToGrid={true}
                    nodeTypes={nodeTypes}
                    key="edges"
                    nodesDraggable={isDraggable}
                >
                    <Controls />


                </ReactFlow>
            </ReactFlowProvider>


            <ReactFlowProvider>
                <ReactFlow
                    onLoad={onLoad}
                    elements={elements}
                    onElementClick={onElementClick}
                    onElementsRemove={onElementsRemove}
                    onConnect={onConnect}
                    onNodeDragStop={onNodeDragStop}
                    onLoad={onLoad}
                    snapToGrid={true}
                    nodeTypes={nodeTypes}
                    key="edges"
                    nodesDraggable={isDraggable}
                >
                    <Controls />


                </ReactFlow>
            </ReactFlowProvider>

**Comment by pSnehanshu** [comment]
I can confirm that this works.
