### ISSUE TITLE
The edges doesn't work if we have __ ( 2 underscore ) in the source or target.

### ISSUE THREAD

**Issue by vineetvk01** [wbkd/react-flow#644]
Hey! First of all, React flow is amazing! I was trying it out for one of our project. 

The source value has two underscores ("__step1__" or "h__1__up") and because of that the edges are not working properly. What you suggest we can do to avoid this behaviour ??

**Comment by moklick** [comment]
hey @vineetvk01 

we are working on a new version taht you can find in the next branch. There we don't mix node ids and handle ids within the node id anymore. For now this only works if you don't have a `__` in your id.
