### ISSUE TITLE
Is there a way to pass  other properties other than data into custoNode?

### ISSUE THREAD

**Issue by pranithasri** [wbkd/react-flow#655]

**Comment by chrtze** [comment]
this is not possible at the moment, as we are only passing down specific properties to the custom node. what would be the use case for this? do you have an example of what other property you want to pass down to the custom node?

**Comment by shyam-infraon** [comment]
if we pass position we can have a custom node to be resized and then can set its position. So it would be good to pass position as well

**Comment by moklick** [comment]
Maybe we got the question wrong. Do you mean the props that get passed into a custom node? Since v7.1.0 we also pass the position to a custom node.

**Comment by shyam-infraon** [comment]
yeah, thats what i was asking for, will upgrade to the latest version.Thank You!

**Comment by jakespeare** [comment]
@pranithasri I was able to pass custom properties into my components by defining my nodeTypes as such 

```
const nodeTypes = {
    customNode: ({ id, data, selected, type }) => { // The typical data passed
      return (
        <CustomNode
          id={id}
          data={data}
          selected={selected}
          type={type}
          customProp={customProp} 
          customFunction={() => customFunction()}
        />
      )
    },
```

and then accepting all of those as parameters within my custom node component
```
const CustomNode = ({id, data, selected, type, customProp, customFunction}) => { 
    //custom node component code
}
```
My use case for this is to use my customFunction() to fetch things based on the data/id in that custom node (But I wanted this placed in a button and node in the onClick of that node).  At first my use case was so that I could pass setState hooks from my parent components to share data across components, but I was able to achieve that with the ReactFlowProvider component + storeState stuff.

**Comment by rlueder** [comment]
@jakespeare answer is great and would be useful if mentioned in the docs as it's not obvious from the examples it can be done, only tweak I made was to spread the default props on my custom node:

```
 const customNode = (props) => {
    return (
      <CustomNode {...props} customFunction={(val) => console.log(val)} />
    );
  };

<ReactFlow
    elements={elements}
    nodeTypes={{
        component: customNode,
    }}
/>
```

**Comment by bevinhex** [comment]
In above workaround,  it is not possible to assign customFunction as parent function, where parent props/stats are accessible, cause if you put the customNode within react component , you'll get  https://reactflow.dev/learn/troubleshooting#it-looks-like-you-have-created-a-new-nodetypes-or-edgetypes-object-if-this-wasnt, so the custom node has to be outside of the main component, where you cannot access props of main component for the customFunction

so we still need a better way to give custom property(functions) for the nodes
