### ISSUE TITLE
Visual grouping of nodes

### ISSUE THREAD

**Issue by RafaelCruzMarquez** [wbkd/react-flow#658]
Requested functionality.
I've been looking at the possibility of visually grouping nodes using a simple different background with some title. A simple rectangle that encompasses several nodes.
What would be its usefulness? Let's imagine an IoT sensor and actuator representation system in a home or industry. Suppose we need to visually group all the sensors in the same room, in the kitchen, bathroom, etc.
It would be about having the possibility of visual grouping of nodes.
The idea would be similar to the graphic in the following link: https://docs.cruncherlabs.com/cruncher

Special thanks to the library developers. Nice job.
 
![Captura de pantalla 2020-10-31 a las 12 38 53](https://user-images.githubusercontent.com/34137041/97874491-f9a5b180-1d10-11eb-8624-1dc373e17205.png)

**Comment by chrtze** [comment]
https://github.com/wbkd/react-flow/issues/658

**Comment by RafaelCruzMarquez** [comment]
Thanks a lot!

**Comment by glebfeklistov** [comment]
@RafaelCruzMarquez Just use https://github.com/flowhub/the-graph

**Comment by moklick** [comment]
I will collect new feature ideas in the "Discussions/New Features" section. This issue will be closed in favour of #1022
