### ISSUE TITLE
Bug: the new scrolling feature is not working on firefox

### ISSUE THREAD

**Issue by roywillemse** [wbkd/react-flow#664]
Hi guys, we are already have the new scrolling feature in production. We noticed that on firefox the scrolling doesn't seem to work, the edges seem to move away from the nodes when you're scrolling on the latest version of firefox: `82.0.2`. Only the scrolling seems to be an issue, the panning is working fine on firefox.

You can check this behaviour in this codesandbox: https://codesandbox.io/s/xhgq6

Thanks in advance.

**Comment by moklick** [comment]
Thanks for the hint! It should work with v7.1.1 but the scroll speed is not the same for firefox and chrome. We will leave this issue open until it is fixed. May be this helps https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js

**Comment by roywillemse** [comment]
@moklick Nice, it works on firefox now. It seems like the scrolling behaviour is inverted from the regular scrolling and the opposite of the scrolling implemented in `v7.0.0` is this done on purpose?

**Comment by chrtze** [comment]
@roywillemse, can you clarify this? we want the scrolling to behave similar to sketch, figma etc. Scroll speed in firefox has been fixed in [7.1.2](https://github.com/wbkd/react-flow/releases/tag/7.1.2).
