### ISSUE TITLE
panOnScroll: normalize scroll speed

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#665]
The scroll speed is different in Chrome and Firefox. We need to find a way to normalize it. May be this could help https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js

**Comment by chrtze** [comment]
Released in [7.1.2](https://github.com/wbkd/react-flow/releases/tag/7.1.2)
