### ISSUE TITLE
Need to know which node is dropped on which node

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#666]
I am trying to implement a feature where i need an event when a node is dropped on another node. (Need to know both the nodes id on drop).
Or, if I can get to know which nodes are present on the canvas at a particular location (x,y) given
Will be helpful if you can suggest me how to get that data.

**Comment by agarwal00s** [comment]
@moklick any suggestion ?

**Comment by chrtze** [comment]
hi @agarwal00s, just to clarify, do you want to drag and drop an **existing** node on another node, or an non-existant node (for example from a sidebar) onto an existing node?

**Comment by agarwal00s** [comment]
Hi @chrtze 
Thanks for the response.
I want both for implementing these different features:
Feature 1: A node should not be able to drop on top of another node
Feature 2: Dragging a node on top of another node (Both node inside the canvas, want to know which node is dropped on which node)
Feature 3: Dragging a node outside the canvas to the canvas

**Comment by code-guru** [comment]
you can listen to node position changes using onNodeDragStop, and go through all nodes and calculated bounds using w/h/x/y and see if there is overlaps. this is a very specific feature, and maybe kind of thing you need to implement yourself, rather than the chart library.

**Comment by agarwal00s** [comment]
Thanks @code-guru , will try that way
