### ISSUE TITLE
[Bug]: Zooming using controls does not trigger onMove event

### ISSUE THREAD

**Issue by code-guru** [wbkd/react-flow#674]
When zooming using controls component, the onMove/onMoveStart/onMoveEnd does not trigger as it is mentioned by documentation. is there another event available listening to zoom events? Can you confirm if it's bug, or am I missing something?

Thanks!

**Comment by chrtze** [comment]
thanks! this will be fixed in the next version: https://github.com/wbkd/react-flow/pull/676/commits/cf38388f149dadf3e9981d9b233f7aa1464d2ccd

you can already use it: `npm i react-flow-renderer@next`
