### ISSUE TITLE
[Performance] panOnScroll is not performing well on firefox with multiple nodes

### ISSUE THREAD

**Issue by EmielW** [wbkd/react-flow#677]

**Comment by chrtze** [comment]
hi @EmielW, which OS, FF version and react-flow version are you using?

**Comment by emielwit** [comment]
Hey @chrtze 

macOS Catalina, FF: 82.0.3 and react-flow: 7.1.2

It feels a bit laggy when using the touchpad. In Chrome I don't have this experience.

**Comment by chrtze** [comment]
I cannot really reproduce it. For me it runs quite smooth with the same versions. Do you have any idea why this might be happening? How many nodes do you render?

**Comment by emielwit** [comment]
I created a sandbox: https://codesandbox.io/s/reactflow-scrolling-implementation-using-next-xhgq6

If you move quickly with you touchpad I have a laggy behavior

**Comment by moklick** [comment]
Hey @EmielW 

I just released a new version. Could you try `react-flow-renderer@next`?

**Comment by emielwit** [comment]
Appreciate the quick response and help. It's solved in the current sandbox above. This was not exactly representing our use case. We have use cases where people have more than 100 nodes on the canvas I added one of those use cases in the following sandbox: https://kwng3.csb.app/. In this sandbox, it's noticeably slower than in chrome but in our actual use case, it's unusable its freezes the complete page in Chrome we don't have any problems also panning with mouse works fine only the scroll is creating this behavior. Not sure if you can improve this more or maybe you have some tips on what could cause this behavior.

Thanks!

**Comment by moklick** [comment]
For me it's working in firefox. When I do a lot of scrolls it's getting slower but it's not freezing. Did you set `onlyRenderVisibleElement=true`? Do you have complex nodes?

**Comment by emielwit** [comment]
Yes, it is set to `true` i think it has to do with our defaultNodes. Weird that it's so bad on Firefox 😕 .

**Comment by moklick** [comment]
Are you default nodes memoized?

**Comment by emielwit** [comment]
Yes all of them are wrapped inside a `React.memo`

**Comment by moklick** [comment]
Maybe you could prevent any other re-renderings inside the custom nodes? Do they include a lot of child nodes?

**Comment by emielwit** [comment]
I found the problem, it's something with my custom edges, I removed my edges, and now it's better, still not the same performance as in other browsers but acceptable. I'm calculating my own SVG path with `getSVGPath(sourceX, sourceY, targetX, targetY)` maybe it's too heavy for firefox to calculate the new SVG path every time with my custom function.. I need to sort that out.

**Comment by moklick** [comment]
I am glad you found the bug :) I think we could improve the performance by only rendering the visible edges. Right now the `onlyRenderVisibleElements` option has only influence on the nodes.

**Comment by moklick** [comment]
could you try `npm i --save react-flow-renderer@next` with the new `onlyRenderVisibleElements` option.

**Comment by emielwit** [comment]
Hey @moklick, 

This solves the laggy behavior awesome. It only creates a bug when I have nodes that are far under each other and both nodes are not in my viewport the edge between them will disappear 😕

**Comment by moklick** [comment]
Haha :D I didn't thought about this case. I will check how we can fix it.

**Comment by moklick** [comment]
I released a fix in `react-flow-renderer@next`

**Comment by emielwit** [comment]
Hey, thanks for the quick implementation, I found one problem when you hit the edge of the canvas on the left side the edges dissapear. See: https://kwng3.csb.app/

**Comment by moklick** [comment]
This is fixed in v8.0.0
