### ISSUE TITLE
Can't use zoom and initTransform from action store anymore

### ISSUE THREAD

**Issue by emielwit** [wbkd/react-flow#678]
Hey,

In version `8.0.0-next.2` i can't use the following functions any more from the `actionStore`

```
const { setInitTransform } = useStoreActions(actions => actions);
const { zoom } = useStoreActions(actions => actions);
```

**Comment by moklick** [comment]
Hey @emielwit 

there are some breaking changes.

We are now exporting a hook called `useZoomPanHelper`. That hook exports helper functions:

```
const { zoomIn, zoomOut, zoomTo, transform, fitView } = useZoomPanHelper();
```

Does it work for you?

**Comment by emielwit** [comment]
Thanks that works! Question why are the functions that I can extract from the `useZoomPanHelper();` possibly `null`?

**Comment by moklick** [comment]
Thats a bug. We will change this!

**Comment by moklick** [comment]
Should work with the latest next version (8.0.0-next.3). We also added an initialized flag:

```
javascript
const { zoomIn, zoomOut, zoomTo, transform, fitView, initialized } = useZoomPanHelper();
```
