### ISSUE TITLE
Allowing the user to save the view state

### ISSUE THREAD

**Issue by gazzza** [wbkd/react-flow#679]
I want to allow the user to move nodes around and then save the position of those nodes so that it looks the same when they come back to the graph. 

I am struggling to see an intuitive way to save the view state, and which are the necessary elements to store in order do this: there is the d3selection in the store but then also the transform state and the width/height etc. 

In addition, looking through the code I can see a way of transforming some arbitrary coordinates into the graph view state (transformXY etc.) but not a way of the doing the inverse operation (taking the .__rf.position of the nodes and turning them back into the initial arbitrary coordinates). 

I would appreciate any advice, guidance, or direction as to how to achieve this using the current code base.

**Comment by moklick** [comment]
In the next version the react flow instance has a function `toObject`. We will also add a hook that exports that function.
You can already use it when you install `react-flow-renderer@next`.

**Comment by gazzza** [comment]
Thank you - I'll take a look and see if I can get it working!

**Comment by moklick** [comment]
It is released in v8.0.0

**Comment by gazzza** [comment]
Thanks - I took a look. 

As far as I can tell, .toObject is only available when the Flow loads via the onLoad callback function. 

If the user moves the nodes around, or adds connections, I cannot see a way to expose the view state so that I can save it. 

In addition, I am not particularly sure how - even if I can figure out a way to save the view state - I can use it to load that view state again. 

I'd be grateful if you are able to point me in the right direction. 

Best wishes
