### ISSUE TITLE
connectionLineType prop on ReactFlow component not working?

### ISSUE THREAD

**Issue by JulienDemarque** [wbkd/react-flow#680]
Adding` connectionLineType={ConnectionLineType.Step}  ` to ReactFlow component seems to do nothing

**Comment by JulienDemarque** [comment]
Also addEdge helper doesn't seem to accept the property `type` on `params: Edge | Connection)`.

**Comment by moklick** [comment]
Hey @JulienDemarque 

I can't reproduce your issues. You can find a codesandbox here: https://codesandbox.io/s/wandering-tree-fqt4g?file=/src/Flow.tsx (using `type` option in the `addEdge` handler and `ConnectionLineType.Step`).

**Comment by JulienDemarque** [comment]
mmm I see. I thought `connectionLineType={ConnectionLineType.Step}` on ReactFlow component was supposed to make all edges type default to Step. It only affects newly created edges if I understand correctly?

and for addEdge I see now: `addEdge({ ...params, type: "step" }, els))` :+1:

**Comment by moklick** [comment]
The connection line is the line that gets drawn while you connect nodes with each other. I will try to make this more clear in the docs.
