### ISSUE TITLE
Pane movement through trackpad

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#682]
I want the pane to scroll while im scrolling on touchpad, also I want to zoom in and out on pinch in/out.

**Comment by code-guru** [comment]
nice feature to have, you can also implement it yourself https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures

**Comment by chrtze** [comment]
It would be cool if we could combine both functionalities but I am not sure if pinch is the best option for handling this as it works only with a trackpad. Maybe something as the zoom behaviour in Google Maps Embeds (Cmd+Scroll) would be an alternative.

**Comment by KutnerUri** [comment]
could this be solved by #11? 😄

**Comment by moklick** [comment]
This is possible by setting `panOnScroll={true}`
