### ISSUE TITLE
panOnScroll direction is opposite direction of expected behaviour

### ISSUE THREAD

**Issue by code-guru** [wbkd/react-flow#683]
I'm using mac and the scrolling/panning using trackpad in react-flow I experience opposite direction of what I experience in other apps and or when scrolling a web page. I'm not sure if this behaviour is by design or not. However as a user, I expect the same scrolling behaviour as I scroll down a webpage, it would be much less confusing. 

Thanks :-)

**Comment by moklick** [comment]
Hey @code-guru 

which version are you using? Could you try`react-flow-renderer@next`

**Comment by code-guru** [comment]
I was using 7.1.2, but tried 8.0.0-next.6, and the scrolling behaviour is the same. Here is example with pan on scroll enabled https://codesandbox.io/s/fragrant-monad-w4m40?file=/src/Overview/index.js 

If you compare the graph and code editor, I expect the content flow in the same direction using the same scroll gesture. When scroll gesture in the code editor shows the code below, the same scroll gesture on the graph also should displays the digram below. As a reference we can compare pan on scroll with draw.io https://app.diagrams.net/ 

Maybe the developer wanted to have mac scroll behaviour on windows, or vice versa, but it should only the follow the system scrolling behaviour. I mean scrolling the react flow graph should be similar as scrolling a text document or webpage.

**Comment by chrtze** [comment]
thanks @code-guru, we have taken a second look on the behaviour and it was confusing for us as well. we want to have the same logic as draw.io, sketch, etc. this should now be fixed and released in the next version.

**Comment by code-guru** [comment]
awesome, many thanks 🙂
