### ISSUE TITLE
Re-Distribute Nodes in graph

### ISSUE THREAD

**Issue by charithreddyv** [wbkd/react-flow#684]
Does the package support any kind of redistribution of nodes on basis of links hierarchy,
what i really mean is using some layout libraries like dagre, are they  directly built in or are there any examples how use if any, examples can you please place it here.

Thanks in Advance

**Comment by moklick** [comment]
Hey!

we don't have built-in layouting. You can find an example of how to use dagre here: https://github.com/wbkd/react-flow/issues/5#issuecomment-643805398
