### ISSUE TITLE
Animate on node position change

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#685]
I was wondering if it would be possible to add the ability to animate when a node's position changes (aside from dragging a node inside the library). 

So for example, in my app, a user can insert nodes with a drag and drop interaction (outside of the library). When this occurs, I give the library a new elements array with nodes and edges. The nodes are then redrawn and moved to the correct position. It would be really cool if rather than jump to the new positions, the nodes could smoothly animate to the new position from the previous position.

Is this possible?

**Comment by justrhysism** [comment]
I was hoping this might be as simple as adding `transition: transform ...` to the node CSS, but alas, it only animates the _nodes_ and not the _edges_ which are drawn with SVG. Not quite as simple as I'd hoped.

**Comment by chrtze** [comment]
maybe you can build something with custom edges: https://reactflow.dev/docs/api/edge-types/

**Comment by justrhysism** [comment]
@wdfinch I'll probably investigate this a bit further, but I do agree with @chrtze that it shouldn't be part of the core library.

**Comment by wdfinch** [comment]
Thanks! @justrhysism I did try adding a transform on the node and this helped a lot with the effect I was looking for. If it's possible to have the edges animate that would be cool, but having the node animate is really what I was looking for.

**Comment by raarts** [comment]
@justrhysism @wdfinch, could any of you provide an example of how to do this? I want to animate a node fading in/out, instead of suddenly appearing/disappearing.  

Also - having implemented undo - I would like to transition all undo.redo changes (which are performed by memoing the elements array, and just passing a previous one as the prop to ReactFlow).

I have zero experience with JS animations in React.

**Comment by wdfinch** [comment]
This issue was for animating position changing which is pretty easy. You can just add something like `transition: transform .1s linear` to the CSS class for the node to which the `translateX` and `translateY` property are being alerted. 

Fade-in is pretty easy. You can add some CSS to the node react component to animate the opacity using CSS animation keyframes with opacity. You can also use a React lib like [react-fade-in](https://www.npmjs.com/package/react-fade-in) to do this.

Fade-out is harder because the node is immediately removed from the DOM when you change the nodes/edges array. The library would need to do something like modal libraries typically do where a CSS class called `is-removing` or something is added to the node for some amount of time before it is removed from DOM. 

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations

**Comment by raarts** [comment]
Thanks! I tried it and got smooth resizing working easily. Undo/Redo doesn't work at all though. Maybe I should always pass the same elements array, and only apply the difference from the undo buffer to it. Guess I gotta up my JS skills ;-)

**Comment by ClementHoang-at** [comment]
> This issue was for animating position changing which is pretty easy. You can just add something like `transition: transform .1s linear` to the CSS class for the node to which the `translateX` and `translateY` property are being alerted.
> 
> Fade-in is pretty easy. You can add some CSS to the node react component to animate the opacity using CSS animation keyframes with opacity. You can also use a React lib like [react-fade-in](https://www.npmjs.com/package/react-fade-in) to do this.
> 
> Fade-out is harder because the node is immediately removed from the DOM when you change the nodes/edges array. The library would need to do something like modal libraries typically do where a CSS class called `is-removing` or something is added to the node for some amount of time before it is removed from DOM.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations

It seems tough to do this with longer durations since there will be a "lag" when you're dragging the node. Not sure how to deal with this yet since it'll involve adding this global CSS style only in specific states.

**Comment by johnhforrest** [comment]
@wdfinch did you end up finding a solution for edges animation or did you just fade them in/out? I was hoping they would have a `transform` property like the nodes to make it easy to add a CSS animation but it doesn't look like the edges follow quite the same logic as the nodes.

**Comment by vogelsgesang** [comment]
I have the same use case and would also want to use CSS transitions to smoothly animate the node positions.

I was wondering if support for this could be added to react-flow by:
1. Adding a [transitionstart](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionstart_event) event listener to all nodes
2. If [TransitionEvent.propertyName](https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent/propertyName) is `transform`. If it does, start injecting react-flow before the "repaint" event using [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)
3. In the callback passed to `requestAnimationFrame`, update the edges position based on the values returned by [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle). Afaict, this should give us the current node position as rendered on the screen
4. as soon as the [transitionend](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionend_event) fires, stop using `requestAnimationFrame`. It's no longer needed to update the edge positions.

I didn't try this approach, yet, so I am not sure if it actually works. Wanted to get your feedback on that idea first 🙂

**Comment by JohnPeng47** [comment]
@vogelsgesang's idea is interesting, we are running into a similar situation with animating nodes, has anyone tried this yet to see if it's viable?

**Comment by lee175** [comment]
Hi, you can easily do this using the framer-motion library. Wrap the custom node in the motion.div, and use shared layout property. This will smoothly animate a given node from the initial position to the final one. 
Make sure to have different IDs for each animating node.  
I tried it and it works

**Comment by keyserj** [comment]
> Hi, you can easily do this using the framer-motion library. Wrap the custom node in the motion.div, and use shared layout property. This will smoothly animate a given node from the initial position to the final one. Make sure to have different IDs for each animating node. I tried it and it works

Here's an [example sandbox](https://codesandbox.io/p/sandbox/zen-haze-g4flfm?file=%2Fanimated-node.js) with this solution (built off a layout [example](https://reactflow.dev/learn/layouting/layouting#dagre) in the reactflow docs). I also noticed that the nodes animated on render even though they weren't changing position, so I added a (hacky) state variable to only animate after initial render.
