### ISSUE TITLE
node.__rf is undefined

### ISSUE THREAD

**Issue by charithreddyv** [wbkd/react-flow#691]
Hai, 
I am trying to implement layout/Re-Distribute nodes in a graph as mentioned in https://github.com/wbkd/react-flow/issues/5#issuecomment-643805398  but accessing __rf is being undefined. 
here is [codesandbox](https://codesandbox.io/s/reactflowrenderer-jz7l0) to reproduce.
Thanks In Advance.

**Comment by chrtze** [comment]
hi, you are using elements from your local state there. the __rf is only available when using the nodes from useStoreState (https://reactflow.dev/docs/api/internal-state-actions/).

**Comment by charithreddyv** [comment]
@chrtze  thanks for a quick response is there no other way for me to access __rf on my current codebase ?
if any could you please explain how 

Thanks in advance

**Comment by chrtze** [comment]
the two options are using the internal state or the newly introduced `toObject` function which has the positions.
