### ISSUE TITLE
react-flow@next updateTransform issue

### ISSUE THREAD

**Issue by code-guru** [wbkd/react-flow#692]
In react-flow v8, setInitTransform action has been removed and it seems the implementation of updateTransform is different or has bugs. Here is the bug I'm experiencing: 
After updating pane position using `useStoreActions(actions => actions.updateTransform)`, when I get onMoveEnd event, the event `transform` parameters has the previous position of pane before setting the position using updateTransfrom.

Can you confirm the issue? I didn't have the issue with v7 setInitTransform.
Thanks!

**Comment by code-guru** [comment]
I can confirm I get the exact same bug if I use updateTransform instead of setInitTransform. Can you clarify what are the differences between these two functions? if they are different, can we have setInitTransform in v8?

**Comment by code-guru** [comment]
I find the solution mentioned here https://github.com/wbkd/react-flow/issues/678#issuecomment-725299327
It seems setInitTransform is now replaced with a separate hook `const { transform: updateTransform } = useZoomPanHelper();`, after using the new hook, it works fine. I think this is breaking change, worth mentioning in the release notes ;-)

**Comment by chrtze** [comment]
hi @code-guru, we are still working on the docs and release notes, should be mentioned in some minutes ;)
