### ISSUE TITLE
How can I force a rerender of the tree?

### ISSUE THREAD

**Issue by ejosafat** [wbkd/react-flow#693]
After the graph is rendered, some changes in the elements don't get the library to rerender it, even when the parent component is rerendered and passed a set of elements with some properties changed.

I have a set of nodes and edges with id's mapping their corresponding id's in the database. The tree gets rendered without problem. After rendered, from a form, I change the target of one of the edges to another node, pass the elements set with the new properties to the component but it still renders the same previous tree. Same happen if I modify styles and then pass the new set to the component.

I've seen in the code that React.memo is extensively used to cache the components, but shouldn't this change in properties force the rerender of the tree? 
What property changes in nodes and edges are considered real changes to avoid returning the memoised version of the component?

**Comment by ejosafat** [comment]
I've managed to solve it this way, but I think it's quite convoluted:
```
import React, { useState, useEffect, useRef } from "react";
import ReactFlow, {
  FlowElement as IFlowElement,
  OnLoadFunc as TOnLoadFunc,
  OnLoadParams as TReactFlowInstance,
} from "react-flow-renderer";
import styled from "styled-components";

const WrapperStyled = styled.div`
  width: 100vw;
  height: 80vh;
  overflow: hidden;
`;

interface IProps {
  elements: IFlowElement[];
}
const ReactFlowView: React.FC<IProps> = ({ elements }) => {
  const [receivedElements, setReceivedElements] = useState<
    IFlowElement[] | null
  >(null);
  const instanceRef = useRef<TReactFlowInstance | null>(null);

  const onLoad: TOnLoadFunc = reactFlowInstance => {
    instanceRef.current = reactFlowInstance;
  };

  useEffect(() => {
    setReceivedElements(elements);
  }, [elements, setReceivedElements]);

  useEffect(() => {
    if (instanceRef.current) {
      instanceRef.current.fitView();
    }
  }, [instanceRef, receivedElements]);

  return (
    <WrapperStyled>
      <ReactFlow
        elements={receivedElements ?? []}
        minZoom={0.1}
        defaultZoom={0.5}
        selectNodesOnDrag={false}
        nodesConnectable={false}
        onLoad={onLoad}
      />
    </WrapperStyled>
  );
};
```

**Comment by moklick** [comment]
Thanks for the hint. This is a bug. We don't check if the `source` or `target` change.

**Comment by JulienDemarque** [comment]
@moklick I get the same issue with Position, I implemented a basic auto-positioning algorithm. But the Canvas will sometimes re-render the elements in the right position, and sometimes not...

**Comment by JulienDemarque** [comment]
The hack I found is to do a clone of my elements before passing them as a prop

**Comment by smadapathi** [comment]
Thanks for the library. We are also facing the same issue.

**Comment by HarunOr** [comment]
> Thanks for the library. We are also facing the same issue.

Look at the snippet ejoysafat posted above. The essential part is this: 

```
const [receivedElements, setReceivedElements] = useState();

  useEffect(() => {
    setReceivedElements(elements);
  }, [elements, setReceivedElements]);

<ReactFlow elements={receivedElements}>
```

You basically assign your elements to a state and use useEffect to update it.

**Comment by moklick** [comment]
Hey!

I added an example of how to [update node attributes](https://reactflow.dev/examples/update-node/) and added a note on the [node options site](http://localhost:8000/docs/api/nodes/).

**Comment by jmgomezsoriano** [comment]
The only way to fix this issue I have had is changing the nodes ids each time.
