### ISSUE TITLE
[Feature] Screen Coordinates to Pane Coordinate Translation

### ISSUE THREAD

**Issue by gkeechin** [wbkd/react-flow#694]
Hey there, great library and we are starting to use it within our company to orchestrate workflows. Everything is pretty good so far, however, when we are trying to implement a way to add nodes dynamically onto the pane by a context menu, we will need to perform some translation as such:

```javascript
private flowTranslateCoordinateSystem = (x: number, y: number) => {
    const [transformX, transformY, scaleZ] = this.currentFlowState.transform;
    const NAVBAROFFSET = 50;
    return {
      x: x - transformX,
      y: y - transformY - NAVBAROFFSET,
    };
  };
```

We are using `useStoreState` to access the transform. The above calculations does not work when there is a zoom factor (scaleZ) because the clientX and clientY would referring to the scaled coordinate system. 

We can figure out the rough formula for this, however, I'd like to check if there's this feature on the roadmap in either `onPaneContextMenu` or `onPaneClick` to provide the pane coordinates (corrected to the zoom factor) instead? 

Happy to figure the math out and help with a PR if that's a feature that resonates with you!

**Comment by moklick** [comment]
Hey! 

the react flow instance has a [`project` function](https://reactflow.dev/docs/api/react-flow-instance/) you can use. Is this what you were looking for?

**Comment by gkeechin** [comment]
Hey @moklick - I must have missed such an important feature in the documentation. All good and working now! 

Thanks and our dev team appreciates this polished library that you are maintaining!

**Comment by moklick** [comment]
💯
