### ISSUE TITLE
How to find the ReactFow's grid `position` ?

### ISSUE THREAD

**Issue by jagadeeshpalaniappan** [wbkd/react-flow#695]
**Background:**
- I am building Toolbox which will have list of Nodes. 
- User can drag and drop Nodes into ReactFow component. 
- Using native `onDrop` function, I am able to add node into **ReactFow** - by updating the `setElements`
- **Now i would like to add node with position property (it should be exactly the dropped location)**
   - `onDrop` event object gives me `clientX, clientY`
   - but i am not sure how will i convert that position into ReactFow's grid `position`

**Question:**
How do i match the `drop location` with ReactFow's grid `position`?

Could you please help me

**Comment by YuriyKrasilnikov** [comment]
I am dealing with the same thing.
An example of adding a node can be seen [here](https://github.com/wbkd/react-flow/blob/main/example/src/Empty/index.js#L13-L21)

You can use `project` to convert positions. [Read here]( https://reactflow.dev/docs/api/react-flow-instance/)

Now I'm looking for how to catch `ref ` for root `div`.
