### ISSUE TITLE
Zoom Event

### ISSUE THREAD

**Issue by SathishRaju** [wbkd/react-flow#696]
How can I listen to the zoom in/out event? Is there an event to listen to? I can't find it in the docs.

**Comment by moklick** [comment]
You can use `onMove, `onMoveStart` and/or `onMoveEnd`. If you only want to react to zoom changes I would use the `onMoveEnd` event and check if the zoom has changed. Does it help?

**Comment by SathishRaju** [comment]
@moklick Thanks for the quick response. I am using the buttons( +/ - )in the zoom control but the onMoveEnd event is not getting triggered. Any idea?

**Comment by moklick** [comment]
which version are you using? The current version is 8.0.0

**Comment by SathishRaju** [comment]
Ok, I figured it out. I have to use the onZoomIn/onZoomOut events on the Controls component. Thanks for your assistance. Closing this issue.

**Comment by moklick** [comment]
you can also use the click handlers but the onMoveEnd handler also gets called when you press one of the buttons in the current version.
