### ISSUE TITLE
[Bug] Unable to stop node click propagation to prevent selection

### ISSUE THREAD

**Issue by justrhysism** [wbkd/react-flow#697]
When handling a click within a node, it's not possible to prevent the "click" from selecting the node using `event.stopPropagation()` as one might expect.

[![Edit react-flow-unable-to-stop-propagation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-thunder-d83ve?fontsize=14&hidenavigation=1&theme=dark)

It appears that both `onDragStart` and `onDragStop` (the latter when `selectNodesOnDrag: false`) will select the node.

Unfortunately, this has cost me a good few hours and I'm sure others might do the same.

--- 

### Workaround

To work around this issue, it is necessary to block the `mousedown` event from propagating.

```
<button onClick={handleClick} onMouseDown={event => event.stopPropagation()}>
```

I can work with this for now, but it might be worth adding some documentation around this so this is less likely to be raised as an issue by others.

**Comment by code-guru** [comment]
if you want to prevent the node from being selected and make it not draggable you can also set `pointer-events: none` css for your node

**Comment by justrhysism** [comment]
@code-guru I still need the nodes to be selectable and draggable, but don't want them to select when clicking controls within them.

**Comment by moklick** [comment]
Hey @justrhysism 

did you try to add a `nodrag` class to the button?

**Comment by justrhysism** [comment]
@moklick I didn't. This wasn't documented anywhere; at least, not anywhere obvious. I've updated the Codesandbox and can confirm adding the `nodrag` class to the button makes it work as expected.

**Comment by moklick** [comment]
It's documented here under "prevent dragging" https://reactflow.dev/docs/api/node-types/. Maybe we need to make this section better visible or change the title.

**Comment by justrhysism** [comment]
I think it also needs to be re-titled, as I wasn’t trying to prevent _dragging_, I was looking to prevent _selection_. Reading the docs there wouldn’t have helped me as it didn’t present the answer to the question I had.

**Comment by ianarawjo** [comment]
I also ran into this issue when using textareas inside a node. I want the rest of the node to be draggable, just not if they click into the text area. What worked was a slight modification of OP's suggestion, intercepting `onMouseDownCapture` instead:

`<textarea rows="4" cols="40" onMouseDownCapture={event => event.stopPropagation()}>`

**Comment by moklick** [comment]
@ianarawjo you should be able to fix this by adding the class name "nodrag" to the text area.

**Comment by superstes** [comment]
Just as a note:
This can also be useful when the node-toolbar should trigger a modal.
`e.stopPropagation()` for `onmousedowncapture` and `onwheelcapture` can give back control while inside it.

**Comment by ZahidChandio** [comment]
Nothing was working for me but adding "nopan" class did the work. Might be helpful for someone.
reactflow: "^11.11.4"

**Comment by bedzhist** [comment]
reactflow: ^12.8.2

`<button onClick={event => event.stopPropagation()}>`
