### ISSUE TITLE
Accessing toObject outside onLoad callback to save view state

### ISSUE THREAD

**Issue by gazzza** [wbkd/react-flow#699]
As far as I can tell, .toObject is only available when the Flow loads via the onLoad callback function.

If the user moves the nodes around, or adds connections, I cannot see a way to expose the view state so that I can save it.

In addition, I am not particularly sure how - even if I can figure out a way to save the view state - I can use it to load that view state again.

I'd be grateful if you are able to point me in the right direction.

**Comment by moklick** [comment]
Hey @gazzza 

you can store the reactFlowInstance in a variable. You can find an example here:
https://github.com/wbkd/react-flow/blob/main/example/src/Basic/index.js

**Comment by gazzza** [comment]
Thanks! That worked - don't know why I didn't think of that
