### ISSUE TITLE
is there an example of creating Diamond node for decision element?

### ISSUE THREAD

**Issue by naivefun** [wbkd/react-flow#700]
is it possible?

**Comment by code-guru** [comment]
Yes, it is possible. To my understanding the idea behind react-flow project is to make it as flexible as possible without adding use case specific features. The project provides you with surface/node/edges/... and you need to implements all of logic you need for your use case.

For making a diamond node, you need to create a custom node with custom styling with make it diamond shape, for use it as a decision element, you need to define handles with different handleId, and when you parse the graph data (elements) in your app based on the edge handle-id you can tell which path to follow. 

Here is a sneak-peak from the project, I'm working with ;-) 

![Screenshot 2020-11-20 at 18 42 48](https://user-images.githubusercontent.com/1493603/99832548-fdcf2d00-2b60-11eb-83a8-815034ae8475.png)

**Comment by chrtze** [comment]
as @code-guru said, you need to implement a node like this by yourself. you can create a custom node and style it using css for example: https://css-tricks.com/the-shapes-of-css/#diamond-square-shape-via-joseph-silber

@code-guru that screenshot looks super cool, when will we get a live demo of this ;) ?

**Comment by code-guru** [comment]
@chrtze I will share it soon, it will be an internal tool in a startup to be used by lawyers.

**Comment by ugrdursun** [comment]
> @chrtze I will share it soon 😀, it will be an internal tool in a startup to be used by lawyers.

Any update sharing code of that ? :)

**Comment by dosapati** [comment]
Hey @code-guru : We are working on a adding more shapes and extend this. Is there a way, you can share any sample of how you did this?

**Comment by code-guru** [comment]
Hey @dosapati, great that you remind me.

Here is a demo for the project I developed for a client in Nov 2020 till March 2021, before their budget for the project hit the limit.
[Bot Designer](https://lawly.levelste.ch/?builder).

It is a visual designer tool meant to be used to lawyer to create a question flow, and then the data from this tool is fed to another app which turns the data to chatbot conversation flow, you can also see the demo [here](https://lawly.levelste.ch/?user-ui). After the user answered the questions, a contract or a Will (testament) will automatically generated based on the answers and paragraph bindings.

This project is designed to work as library and to be embedded to their admin portal, and integrate with their existing "paragraph builder" tool and backend via events. 

The project only depend on react-flow for its graph/chart functionality. The last version of react-flow used was 9.0.4.

Thanks @chrtze and your team for this awesome project :)

**Comment by moklick** [comment]
Hey @code-guru thanks for the insights! The project looks great :)

@dosapati I created a codesandbox with a diamond shape: https://codesandbox.io/s/condescending-silence-lbzfd?file=/src/DiamondNode.js

**Comment by dosapati** [comment]
This is really cool and helps a lot in shaping custom node. Appreciate your response on this.

**Comment by dosapati** [comment]
> Hey @code-guru thanks for the insights! The project looks great :)
> 
> @dosapati I created a codesandbox with a diamond shape: https://codesandbox.io/s/condescending-silence-lbzfd?file=/src/DiamondNode.js

Here is the design I tried using images. Now I can introduce the diamond and other shapes. 
<img width="1557" alt="Screen Shot 2022-01-11 at 7 21 30 PM" src="https://user-images.githubusercontent.com/3864812/149042029-2dac24a1-ef89-4bde-a2fc-62ca13529af8.png">

I see it difficulty to design icons of same W*H, now I get the nodes can't have straight edge and ended up with smoothstep edge. Any suggestions on this approach or any other better way to do this?

**Comment by moklick** [comment]
@dosapati you could still layout the nodes in a way that you get straight edges. When you know the dimensions you can use that to position the nodes vertically centered.

**Comment by imsinghabhi** [comment]
> Yes, it is possible. To my understanding the idea behind react-flow project is to make it as flexible as possible without adding use case specific features. The project provides you with surface/node/edges/... and you need to implements all of logic you need for your use case.
> 
> For making a diamond node, you need to create a custom node with custom styling with make it diamond shape, for use it as a decision element, you need to define handles with different handleId, and when you parse the graph data (elements) in your app based on the edge handle-id you can tell which path to follow.
> 
> Here is a sneak-peak from the project, I'm working with ;-)
> 
> ![Screenshot 2020-11-20 at 18 42 48](https://user-images.githubusercontent.com/1493603/99832548-fdcf2d00-2b60-11eb-83a8-815034ae8475.png)

can u provide the code, as i have made the same shape but i m facing the stlying isssue, just need it for reference purpose
