### ISSUE TITLE
[FR] Custom props in ReactFlowProvider

### ISSUE THREAD

**Issue by MatiasCiccone** [wbkd/react-flow#701]
It'll be good if we can send props to ReactFlowProvider and make them available in useStoreState.

**Comment by code-guru** [comment]
You need to use your own state/store/context for you application data. Consider using react context or redux, https://reactjs.org/docs/context.html

**Comment by MatiasCiccone** [comment]
Yes, I'm doing that as a workaround, but since it already has a provider I thought it will be useful to use it.

**Comment by moklick** [comment]
This could work if it would be possible to extend our store and pass that one to the Provider. We will think about this.

**Comment by moklick** [comment]
We will not implement this feature, because it's too costly to implement and the use case is relatively rare.
