### ISSUE TITLE
[FR] New source/target handle type

### ISSUE THREAD

**Issue by MatiasCiccone** [wbkd/react-flow#702]
Have a Handle type that acts as source and target. In v6 I was able to create connections only with sources handles, but after upgrading to v8 the EdgeRenderer warns about `couldn't create edge for target handle id`. 
The use case behind this is the ability to connect any node handle with any other in another node.

**Comment by chrtze** [comment]
hi @MatiasCiccone, could you provide a code example to reproduce the issue? we also faced some problems when creating edges with handles that were added dynamically (see https://github.com/wbkd/react-flow/commit/7f4d76cc5cef234edb8cde7b81a7ba64d1df371e).

**Comment by moklick** [comment]
Hey @MatiasCiccone 

we are not allowing target to target or source to source connections anymore. I think we should add an option to enable this again. Any ideas for an option name? `allowTargetToTargetAndSourceToSourceConnections` seems a bit overwhelming :D. Maybe `connectionMode: 'loose' | 'strict'` ?

**Comment by MatiasCiccone** [comment]
@chrtze sorry, just see this. Do you still need a sandbox? I think @moklick explained it better than me. And yes, I like the connectionMode proposal

**Comment by moklick** [comment]
Is the new `connectionMode` option working for you @MatiasCiccone ?

**Comment by moklick** [comment]
you can now create graphs that only have handles with type `source` (since v8.3.1) when you set `connectionMode="loose"`.
