### ISSUE TITLE
[Query] How to show/hide Node Handle ports?

### ISSUE THREAD

**Issue by Gunner17** [wbkd/react-flow#703]
Is there a way to show/hide the Node Handle ports programmatically? Please see the illustration.

<img width="497" alt="Screen Shot 2020-11-20 at 4 13 00 PM" src="https://user-images.githubusercontent.com/11354728/99861678-ad99a000-2b4b-11eb-8096-347e9715d7c5.png">

**Comment by code-guru** [comment]
Use <Handle> component, and set custom styling, or use react_flow global css to override their style, then use opacity: 0 to hide them.
