### ISSUE TITLE
[Bug] 'arrowclosed' arrowHeadType goes missing for right -> left Node connections.

### ISSUE THREAD

**Issue by Gunner17** [wbkd/react-flow#704]
I tried connecting an edge from a **right node to a left node**. But after connecting, the arrow did not appear (type: 'smoothstep', arrowHeadType: 'arrowclosed'). When I moved down the right Node slightly, the arrow became visible. Also, this issue does not happen when I connect Node edges from **left to right**. 

FYI: All nodes and Custom nodes with Handle components.

Please see the below illustrations:

**Right to Left connection - 1 :**
<img width="573" alt="Screen Shot 2020-11-20 at 4 21 34 PM" src="https://user-images.githubusercontent.com/11354728/99862209-b4291700-2b4d-11eb-8c05-acc199e6944e.png">

**Right to Left connection - 2 :**
<img width="579" alt="Screen Shot 2020-11-20 at 4 21 55 PM" src="https://user-images.githubusercontent.com/11354728/99862214-b7bc9e00-2b4d-11eb-8184-1ef15da6c0a4.png">

**Left to Right connection :**
<img width="524" alt="Screen Shot 2020-11-20 at 4 22 28 PM" src="https://user-images.githubusercontent.com/11354728/99862228-bf7c4280-2b4d-11eb-85d3-77d753b117ca.png">

**Comment by moklick** [comment]
Hey @Gunner17 

thanks for the hint. This seems like a bug. We will look into it.

**Comment by pbravichandhar** [comment]
Any update on this? 

We need similar feature

**Comment by chrtze** [comment]
The arrows and markers for edges have been completely reworked in v10. Please re-open the issue if this problem persists.
