### ISSUE TITLE
`onConnectStart` event handler would benefit `handleId` in params

### ISSUE THREAD

**Issue by sinan** [wbkd/react-flow#718]
In my flowchart, I rely on the `handleId`s often, as many nodes have many handles. I need to know the `handleId` when the interaction begins, so that I can validate the interaction in certain cases while it's happening rather than it finishes. 

_e.g. say in your chart more than one connection per handle is not allowed; and when creating a new connection, if there is an existing connection I can remove the existing one if I knew the `handleId` on `onConnectStart`._

With the current api I can only get the `handleId` from the dom element as I demonstrated below. Yes, the data `attr` is there, I can use it as a workaround, and react supports it, but as we know it's not the recommended way in a react app. It'd be more idiomatic to pass the `handleId` in params just like the `nodeId`.

```ts
  const onConnectStart = (event, params) => {
      const { nodeId, handleType } = params
      console.log(nodeId, handleType) 
      // logs <nodeId>, "source|target"
      console.log(event.target.dataset) 
      // logs DOMStringMap {handleid: "<handleId>", nodeid: "<nodeId>", handlepos: "right|left|top|bottom"}
  }
```

so, do you plan to add these in the params, or would you accept a PR adding those?

**Comment by moklick** [comment]
Hey @sinan! 

good idea! We will add that :)
