### ISSUE TITLE
[bug] not possible to scroll inside custom node

### ISSUE THREAD

**Issue by chrtze** [wbkd/react-flow#719]
when scrolling inside an element of a custom node that has overflow, the graph is moved / zoomed instead of scrolling the element. one solution would be to add a `noscroll` or `nowheel` class, similar to `nodrag` to prevent the default behaviour.

**Comment by justinvdvelden** [comment]
Hey,

Is there already a solution for this problem?

**Comment by moklick** [comment]
You can add the class `nowheel` to the element that should be scrollable
