### ISSUE TITLE
[QA] Custom shortcut bindings

### ISSUE THREAD

**Issue by cqh963852** [wbkd/react-flow#727]
I'm new to react-flow.
Is there any example show how to do custom shortcut bindings?
Like bind `delete element` to `delete`, not `backspace` on mac os.
Or some combination shortcut key like:`alt + click` delete the element.

**Comment by moklick** [comment]
You can change the key with the `deleteKeyCode` prop. If you want to combine keys you need to implement it by yourself. You can get the selected elements from the store state via `selectedElements`. Does it help?

**Comment by cqh963852** [comment]
> You can change the key with the `deleteKeyCode` prop. If you want to combine keys you need to implement it by yourself. You can get the selected elements from the store state via `selectedElements`. Does it help?

Thank you.It was a great help to me.
