### ISSUE TITLE
Edge position is incorrect at initial rendering in custom node example in Firefox

### ISSUE THREAD

**Issue by mizkichan** [wbkd/react-flow#728]
Hello,

At initial rendering of [custom node example](https://reactflow.dev/examples/custom-node/), positions of edges are rendered incorrectly:
![Screen Shot 2020-11-27 at 19 36 29](https://user-images.githubusercontent.com/3472970/100440467-47cb8c00-30e8-11eb-86ae-b8fe2e240120.png)

Moving nodes or resizing window/element does not fix the edge layout problem. Revisiting the page without reloading after viewing other examples, it looks fine. Also, this problem does not occur in Chromium.
I am using Firefox 83 on Arch Linux.

**Comment by moklick** [comment]
Thank for the report! Unfortunately I can't reproduce this on MacOS with Firefox 83. We will keep an eye on it.

**Comment by moklick** [comment]
The problem was that we called fitView too early in the example.
