### ISSUE TITLE
(feature request) graph traversal

### ISSUE THREAD

**Issue by kaminskypavel** [wbkd/react-flow#729]
Hi Team, amazing work! loving it! ❤

I think providing a BFS/DFS traversal algorithm would be very beneficial.
I've looked up how you [resolve ](https://github.com/wbkd/react-flow-docs/blob/e699e4b82df3c360f299334b0c88f5b82d2192c3/src/components/HeroFlow/index.js#L49)the color RGB example (the one with the knobs) on the front page,
but this approach won't scale well. 

![image](https://user-images.githubusercontent.com/4253088/100528263-72e6d600-31e3-11eb-9568-0ffeb3f0d6d0.png)

**Comment by moklick** [comment]
Hey @kaminskypavel 

Thanks! We already have an open issue #5 about layouting. Since the use cases are very different and preferences for libraries vary we decided no to add any graph layouting algorithms. We (or someone else) might create a react-flow-layouter package :) That would be cool.
