### ISSUE TITLE
Issue with useZoomPanHelper

### ISSUE THREAD

**Issue by lomri123** [wbkd/react-flow#731]
I used an older version. So I first uninstalled it and installed the new version, now running 8.0.0
When I try to use the new useZoomPanHelper hook (as mentioned in your documents) I get an error:
`Error: An error occurred trying to map state in a useStoreState hook: can't access property "getState", o is undefined.`
Any reason why that is happening?

**Comment by moklick** [comment]
Is your App wrapped with the [`ReactFlowProvider`](https://reactflow.dev/docs/api/components/provider/)?

**Comment by lomri123** [comment]
Don't know how I missed that. thanks 👍
