### ISSUE TITLE
[FR] Ability to remove edge

### ISSUE THREAD

**Issue by michalochman** [wbkd/react-flow#738]
We can now update edges using drag&drop (#726), which is great!
How about we allow to remove them by dragging the target back to the source?

Related: #549 #576 #726

**Comment by moklick** [comment]
Hey @michalochman 

is this a common UX when working with connectable nodes? I think it's a bit random/unspecific.

**Comment by michalochman** [comment]
You are right it's not the best, but it's how it works in real life :)

We can be more explicit by selecting an edge and pressing `deleteKeyCode`, which will work similar to removing nodes.

**Comment by moklick** [comment]
> We can be more explicit by selecting an edge and pressing deleteKeyCode, which will work similar to removing nodes.

That's is the current behaviour. However you could also implement your draggable deleting approach is also possible when you set `connectionMode="loose"` (it's a new option in the next version).

**Comment by michalochman** [comment]
You are right, I have checked examples again and it's already working this way. I mistakenly assumed that edges are only removed with nodes and that `onElementsRemove` only applies to nodes, but it explicitly says in documentation that it is called for both nodes and edges.

Closing, as the UX of removing edges by dragging seems worse than the current behaviour. Thanks.
