### ISSUE TITLE
[FR] Add sourceHandle and targetHandle to selected edge object

### ISSUE THREAD

**Issue by michalochman** [wbkd/react-flow#739]
When selecting edge, information about `sourceHandle` and `targetHandle` is lost. Please add it to selected element object.

As a reference, a screenshot of selected edges coming with one node as a source and one node as a target, but with different handles.

<img width="555" src="https://user-images.githubusercontent.com/1628450/100624072-44701480-3323-11eb-9dde-d3c0019da67f.png" />

<img width="650" src="https://user-images.githubusercontent.com/1628450/100624036-3b7f4300-3323-11eb-85c4-6340ea741fa0.png" />

**Comment by moklick** [comment]
How do you get the selected edge? What do you want to do?

**Comment by michalochman** [comment]
I just click on the edge. The objects in developer tools are just outputs of using `useStoreState(state => state.selectedElements)`.

`sourceHandle` and `targetHandle` are available by querying `state.elements`, but lost when selecting element.

I want to be able to distinguish which handles the connection was connected to when removing it to trigger some side effect.

I could query `state.elements` and find edge by `id` before using `removeElements` util, but I wonder if I should traverse the whole graph or if it would easier if this information was provided already when selecting an edge.

**Comment by michalochman** [comment]
Please treat this feature request with low priority, because there is a workaround as described above. Feel free to close it if you think the workaround is sufficient.

**Comment by moklick** [comment]
added in v8.1.0
