### ISSUE TITLE
Fit to view does not consider edges as part of the graph which extend outside nodes

### ISSUE THREAD

**Issue by aswin-aach** [wbkd/react-flow#744]
In a large graph where edges extend beyond the nodes, after fit to screen the edges are cropped out from the graph.
It only considers the nodes for computing graph boundary for resizing.
Please see a screen shot of part of the graph, where the hidden edge is highlighted yellow.
![image](https://user-images.githubusercontent.com/6826530/100966839-dfe7cc00-3553-11eb-9db9-8eac6d153865.png)

**Comment by nileshlande12** [comment]
I'm also facing same issue, if graph vertically big and if any edges going over the top/bottom of nodes those edges are getting hidden outside the canvas.

**Comment by aswin-aach** [comment]
I am able to contain the edges by calling fitView with a padding argument, inside the onFitView callback.
Is there a simpler way to specify padding?

**Comment by nileshlande12** [comment]
Any way to provide margin for graph container canvas only ?

**Comment by aswin-aach** [comment]
Hey.

> I don't get the screenshot. Where are the edges coming from? 

Here are pictures before and after fit to view is clicked, side by side:
![image](https://user-images.githubusercontent.com/6826530/101592763-ce4f6a00-3a14-11eb-9296-e4a9d15582dc.png)

This is only a section of the graph. After fit to view, the top part of the highlighted edge gets hidden.
> How is it possible that there are edges outside of the nodes bounding box?

I customized the edges so that they do not go under the nodes but around them.

So, for fit to view, I need to specify a boundary larger than the nodes' bounds in order to include any outer edges.
Is this controllable through any props? Could something else like margins help?

**Comment by moklick** [comment]
As you already figured out this is possible by passing a padding to the fitView call: 

```javascript
reactFlowInstance.fitView({ padding: 0.2 });
```
