### ISSUE TITLE
Error on using useZoomPanHelper

### ISSUE THREAD

**Issue by aswin-aach** [wbkd/react-flow#745]
I tried to use  useZoomPanHelper() in the Provider example where
ReactFlow component is wrapped inside ReactFlowProvider

I got the following error -
map state in a useStoreState hook: Cannot read property 'getState' of undefined.

Version of react-flow-renderer - 8.1.1

Can you please suggest a solution for this problem.

**Comment by moklick** [comment]
Where exactly did you try to use it? Be aware that `example/src/Provider/index.js` is not wrapped, but inside `example/src/Provider/Sidebar.js` it should be possible to use it.

**Comment by aswin-aach** [comment]
It is working for me now, after I used useZoomPanHelper inside the ReactFlowProvider.
Thanks.
