### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by codingtract** [wbkd/react-flow#747]
May I know if such feature is available or not, like any function to rearrange the flow chart automatically, so any 2 nodes don't overlap & edges are connected in a cleaner way. If not, is there any alternative way or library which can be helpful for such task ?

Thanks,
Naveen Kumar

**Comment by moklick** [comment]
Hey @codingtract 

Thanks! We already have an open issue #5 about layouting. Since the use cases are very different and preferences for libraries vary we decided no to add any graph layouting algorithms. We (or someone else) might create a `react-flow-layouter` package :)
