### ISSUE TITLE
Edges not rendered after upgrade from v6 to v8

### ISSUE THREAD

**Issue by 100le** [wbkd/react-flow#749]
After i upgraded from version 6.2.1 to 8.1.2 my edges are not rendered at all.
I didn't have custom handles for any of them and everything was working fine and now i am constantly getting this error:
"couldn't create edge for source handle id: null; edge id: E42-F2".
After few hours of debugging i couldn't find more than that the bounds are missing when 'getHandleBounds' is calling `getHandleBoundsByHandleType`.
I didn't see anything mentioned that the Handle's are now mandatory with the new version.

Can you please check if there is some bug or breaking changes that were not documented and we need to consider?

**Comment by moklick** [comment]
Hey!

that sounds strange.. could you try to set `connectionMode="loose"`?

**Comment by nileshlande12** [comment]
I also faced same issue when I upgraded version from 6.1.3 to 8.1.1,
Then I figure out problem and changed my code.
Issue is with the way we are using edge id is changed in newer version

In 6.1.3 I was using ==>
[
	{ id: '1', className: 'dark-node', position: { x: 0, y: 0 }, ...getCustomeNodeData('1', 'Node 1')},
	{ id: '2', position: { x: 300, y: -150 }, ...getCustomeNodeData('2', 'Node 2')}
	{ id: 'e1-2', **source: '1__src_right_center'**, **target: '2__trg_left_center'**, ...getCustomeEdgeData(EdgeType.custom, true, '')},
]

in Newer version I had to change code to ==>
[
	{ id: '1', className: 'dark-node', position: { x: 0, y: 0 }, ...getCustomeNodeData('1', 'Node 1')},
	{ id: '2', position: { x: 300, y: -150 }, ...getCustomeNodeData('2', 'Node 2')}
	{ id: 'e1-2', **source: '1'**, **target: '2'**, **sourceHandle: 'src_right_center'**, **targetHandle: 'trg_left_center'**,, ...getCustomeEdgeData(EdgeType.custom, true, '')},
]

**Comment by 100le** [comment]
> Hey!
> 
> that sounds strange.. could you try to set `connectionMode="loose"`? We are not allowing source to source or target to target connections anymore. That can be changed with the connectionMode prop. When do you get this error?

I get this when the graph tries to render each edge. I don't have custom edges defined neither custom handles so i was relying on the default behavior so far. Example of 2 nodes and an edge between them:
![example-connection](https://user-images.githubusercontent.com/2078018/101192419-528f9f00-365b-11eb-9dfb-ec4146a48127.png)
``

**Comment by 100le** [comment]
> Hey!
> 
> that sounds strange.. could you try to set `connectionMode="loose"`? We are not allowing source to source or target to target connections anymore. That can be changed with the connectionMode prop. When do you get this error?

The 'connectionMode' didn't helped. I have custom nodes without any <Handle /> in them and with v6 that worked perfectly with some defaults (sourcePosition - bottom / targetPosition - top). Now after the upgrade to v8 i need to put <Handle /> in each Custom node i have in order to work, the defaults probably don't work anymore. 
Therefore, i wouldn't consider this as an issue maybe but a breaking change which should be mentioned in the documentation so other don't encounter the same problem.

**Comment by moklick** [comment]
I am glad that you found a solution but could you explain the finding once again? I didn't get it. How did you solve the problem?

**Comment by 100le** [comment]
With the old version there were default handles even for the custom nodes. After the upgrade i needed to define them for each custom node like:
![default_handles](https://user-images.githubusercontent.com/2078018/101209862-cb4f2500-3674-11eb-977f-dc387fc74924.png)

**Comment by moklick** [comment]
Thanks for clarification!
