### ISSUE TITLE
When diagram/nodes are not draggable, onElementClick does not trigger

### ISSUE THREAD

**Issue by harsohailB** [wbkd/react-flow#751]
When the diagram is set be not draggable either through passing props to the <Diagram /> component or by using the lock icon in the <Controls /> component, the onElementClick function no longer triggers. My application requirement is to block nodes to be draggable while they can be clicked on to make a pop up about the node. Is there any way to enable to onElementClick function while nodes are not draggable?

**Comment by moklick** [comment]
The `onElementClick` function should trigger even if `nodesDraggable=false`. You can test it in the [interaction example](https://reactflow.dev/examples/interaction/).
