### ISSUE TITLE
Can we get the current zoom level ?

### ISSUE THREAD

**Issue by shyam-infraon** [wbkd/react-flow#752]
Is there a way that we get the current zoom level, I just want to save the current zoom level so that next time I can re-render with the selected level. I can use onZoomIn and onZoomOut to set the level value and, zoomTo to set the zoom, but can we get the zoom in number.
Thanks in Advance

**Comment by moklick** [comment]
You can use the `toObject` function of the react flow instance https://reactflow.dev/docs/api/react-flow-instance/

**Comment by shyam-infraon** [comment]
is it supported in version 5.11?

**Comment by malcodeman** [comment]
If you're using version 8.0.0+ you can make use of `useStoreState` hook. https://reactflow.dev/docs/api/internal-state-actions/

`const zoomLevel = useStoreState((state) => state.transform[2]);`
