### ISSUE TITLE
[QA] How to get elements from redux-thunk

### ISSUE THREAD

**Issue by zcmgyu** [wbkd/react-flow#760]
I'm using **Redux** in my project. I've got base elements data from the redux store. In my case, I want to replace the last node with another node that has a different id. So, Could I get elements from `Easy-Peasy` directly from my current `Redux-Thunk` function? 
Since I couldn't handle the current position of the last node (could get it from _rf of a node), it's going to become the wrong position if I replace the last node with the position of the last node get from the store.

Thanks in advance.

<img width="686" alt="Screen Shot 2020-12-10 at 2 42 41" src="https://user-images.githubusercontent.com/13638569/101666588-c1bd2700-3a91-11eb-8c30-4bde1b79619b.png">

**Comment by moklick** [comment]
Could you write an action where you pass the data/position of the node you want to replace?

**Comment by zcmgyu** [comment]
@moklick Thanks for your suggestion. 
Currently, my workaround is after every time the user drag&drop or removes elements, I will sync the reducer. So, in order to replace the node, I just need to add it to the current reducer and remove the old node.
