### ISSUE TITLE
[FEATURE] Tooltip on control buttons

### ISSUE THREAD

**Issue by nileshlande12** [wbkd/react-flow#763]
It would be nice if we can pass custom tooltip to control buttons.

**Comment by moklick** [comment]
How would you like to pass a tooltip to the controls? I think we will not add this but we might find a way how we can pass a component/ref/whatever to the buttons.

**Comment by nileshlande12** [comment]
> How would you like to pass a tooltip to the controls? I think we will not add this but we might find a way how we can pass a component/ref/whatever to the buttons.

Passing component will be good idea, as we can send customized component for tooltip but we should also able to handle onhover event for that.

**Comment by moklick** [comment]
Hey @nileshlande12 

I thought about it and we will not add such a feature. The controls are very simple to re-implement. There are a lot of different ways of how you could add functionality like tooltips. I think it's better to create your own controls if you need special features.
