### ISSUE TITLE
Interaction Example shows blank page

### ISSUE THREAD

**Issue by ugrdursun** [wbkd/react-flow#773]
I am trying to work with this example [here ](https://reactflow.dev/examples/interaction/)but when i copy source code on the page to my app.js and go it shows me blank white page on browser. What am i doing wrong ?

this one is working fine by the way :   

`import React from 'react';
import ReactFlow from 'react-flow-renderer';
const elements = [
  { id: '1', type: 'input', data: { label: 'Node 1' }, position: { x: 250, y: 5 } },
  // you can also pass a React Node as a label
  { id: '2', data: { label: <div>Node 2</div> }, position: { x: 100, y: 100 } },
  { id: 'e1-2', source: '1', target: '2', animated: true },
];
export default () => <ReactFlow elements={elements} />;`

**Comment by ugrdursun** [comment]
Sorry for me being so amateur, width and height should have been defined on parent.

**Comment by sprajagopal** [comment]
I have the same issue. Not sure where exactly this width and height are to be mentioned. Is there documentation that you found on this?

**Comment by moklick** [comment]
You need to give the react flow wrapper a height. You can do this for example with CSS 

`.react-flow { width: 300px; height: 200px }`

or by passing a style prop to the ReactFlow component 

`style={{ width: 300, height: 300 }}`
