### ISSUE TITLE
How to prevent multi Node selection or disable selection using command key?

### ISSUE THREAD

**Issue by Gunner17** [wbkd/react-flow#774]
If I press 'Command' key and click on multiple Nodes, all of the Nodes gets selected. Is there a way to prevent this multi Node selection or disable the command key listener in the flowchart?

**Comment by moklick** [comment]
You can set the `multiSelectionKeyCode` prop to null or another key https://reactflow.dev/docs/api/component-props/

**Comment by harunurhan** [comment]
`TypeScript` users can just set a random string that can't be a keycode like `"DISABLED"`, since typing doesn't allow this prop to be`null`.

**Comment by coxato** [comment]
Hi, I'm using typescript and now there is no problem if you pass `null` to `multiSelectionKeyCode` 
https://reactflow.dev/api-reference/react-flow#keyboard-props
