### ISSUE TITLE
Connecting Nodes on Mobile

### ISSUE THREAD

**Issue by leejustin** [wbkd/react-flow#778]
I'm exploring how I can use this on a responsive application. Do you have any advice on how to best connect nodes on a mobile browser through the UI? I can't drag the connector as I would with a desktop application and I don't want to hack something together if there's a good approach. Thanks for any input!

**Comment by moklick** [comment]
This is a good point. Unfortunately for now we don't have this feature. You would need to come up with your own logic. You could remember when someone taps on a handle and then add an edge when the next handle is taped.

**Comment by mlguy123** [comment]
Hi @moklick , thanks for the wonderful work!
I'd like to ask which props in [Handle Component](https://reactflow.dev/docs/api/handle/) would detect taps by mobile users?

**Comment by moklick** [comment]
I will collect new feature ideas in the "Discussions/New Features" section. This issue will be closed in favour of #1021
