### ISSUE TITLE
Strange bug when integrating with react-router-dom: rfInstance doesn't seem to unmount?

### ISSUE THREAD

**Issue by gazzza** [wbkd/react-flow#779]
When navigating using react-router dom, if I render a React Flow component, press the back button, and then go to a new React Flow component the new component will have the reactFlowInstance of the previous component. 

I built a Code Sandbox to illustrate this:

[https://codesandbox.io/s/sleepy-benz-1rbkl?file=/src/index.js
](url)
please view the output of the console while clicking between the two Networks by going back to the Table using the back button. 

Hopefully the MWE is clear and self-documenting - I tried to make it as simple as possible. 

I am not sure whether the issue is with React Flow or with React-Router-DOM. 

It should be noted that if you type in the networks/0 directly into the URL, there is no issue - it is specifically with navigating using the back button. 

The reason I came across this is because I am building an App that picks a React Flow Network to render at random as a "feature network" and a table of other networks beneath. When I click one of the networks in the table the rfInstance from the feature network is loaded into that network, which is undesirable. 

Any insight would be appreciated.

**Comment by moklick** [comment]
When you have multiple flows you need to wrap each of them with the [ReactFlowProvider component](https://reactflow.dev/docs/api/components/provider/) so that they have their own store. We will add this information to the docs!
