### ISSUE TITLE
Icon on node

### ISSUE THREAD

**Issue by rajeshwari-differenz123** [wbkd/react-flow#780]
Hi,
i want to add different icons in each node.
how can i achive that?

**Comment by andrewdkim** [comment]
You can add icons to your node by creating a custom node: https://reactflow.dev/docs/api/node-types/

**Comment by rajeshwari-differenz123** [comment]
thanks for reply,
i also want to create node on drag and drop any solution for this?

**Comment by moklick** [comment]
I saw that you already opened a new issue regarding the drag and drop feature so I will close this one.
