### ISSUE TITLE
Bug: Drag a node, also drag the selected node

### ISSUE THREAD

**Issue by code-guru** [wbkd/react-flow#782]
When setting `selectNodesOnDrag` to `false`, dragging a non-selected node cause selected node to also get dragged. 

Here is how to reproduce the bug:
1. set selecNodesOnDrag to false
2. select a node by clicking on it
3. drag another node
4. you see two nodes are moving on the pane, where should only be one

Here I added selectedNodesOnDrag to the Overview example, so you can see for yourself.
https://codesandbox.io/s/gallant-moon-75fve?file=/src/Overview/index.js

Thanks!

**Comment by moklick** [comment]
Thanks for the report @code-guru !

Should work with 8.2.2
