### ISSUE TITLE
Connecting Two Nodes with only Hanlders of the same type can not be connected

### ISSUE THREAD

**Issue by DarthAmun** [wbkd/react-flow#783]
Even if you set the connectionMode to 'loose' you can not connect two nodes if their handlers all have the same type eg. "target" or "source".
I've made a custom Node where if set all handler types to "target" and tried to connect them which you can see in this codesandbox: https://codesandbox.io/s/cocky-water-0rkqy?file=/src/Flow.js

**Comment by Gunner17** [comment]
@moklick 
+1. This is a very useful fix and a great feature! 
- Just checking if there is any plan to add this fix in near future?
- Also, when the fix is complete, I guess it would work with **type: 'smoothstep'** and **arrowHeadType: 'arrowclosed'**? Just confirming.

**Comment by moklick** [comment]
Since v8.3.1 it's possible to create flows that only contain nodes with `source` handles when you set `connectionMode="loose"`. Can you confirm @DarthAmun?

**Comment by DarthAmun** [comment]
![Bildschirmfoto von 2020-12-27 14-19-15](https://user-images.githubusercontent.com/37881139/103171703-a2bee300-484e-11eb-8b2e-d4c6bb056030.png)
@moklick It works now! At least somewhat. In the picture above you can see that i can not connect to every handler. 
On the right node the left handler is not connectable by any of the handlers from the left node. They all get redirected to the top hendler of the right node.
There are no errors in the console.
