### ISSUE TITLE
drag and drop not working in new react app

### ISSUE THREAD

**Issue by rajeshwari-differenz123** [wbkd/react-flow#784]
Hi,
i got this warning 

> The React Flow parent container needs a width and a height to render the graph

by coping this code to new react-project

https://reactflow.dev/examples/drag-and-drop/
 do i need to height and width somewhere?

**Comment by moklick** [comment]
As the warning points out the parent container needs a width and height. The React Flow container takes the space of the parent when you don't set it explicitly.
