### ISSUE TITLE
Is the label editable for the node in the flow

### ISSUE THREAD

**Issue by sreeanthrds** [wbkd/react-flow#785]
I am trying to explore an option to edit the label that is displayed under the node. Also I need to validate it to have unique. Kindly help me if there is any option for this? 
Thanks in advance

**Comment by moklick** [comment]
you can find an example of how to update nodes on the website https://reactflow.dev/examples/update-node/

**Comment by sreeanthrds** [comment]
Thanks a lot for your quick response.
