### ISSUE TITLE
Is there any option to scroll automatically when we drag any node to the edge of the viewport

### ISSUE THREAD

**Issue by sreeanthrds** [wbkd/react-flow#786]
Hi All,

  I am exploring on an option to scroll the canvas down automatically when I drag any node till the bottom/top end. Kindly help me on this.

Thanks in advance

**Comment by moklick** [comment]
no, this is not built in. We might add it in the near future but it's not safe. @emielwit found a solution for this issue: https://github.com/wbkd/react-flow/issues/460#issuecomment-682438238

**Comment by sreeanthrds** [comment]
Thanks a lot for your quick response
