### ISSUE TITLE
How to get all direct and indirect incoming nodes of the passed node?

### ISSUE THREAD

**Issue by Gunner17** [wbkd/react-flow#787]
The **getIncomers** helper function returns all direct incoming nodes of the passed node. How can I have all **direct** as well as **indirect** nodes of the passed node?

<img width="561" alt="Screen Shot 2020-12-19 at 2 11 07 PM" src="https://user-images.githubusercontent.com/11354728/102700717-f0ab6980-4204-11eb-8c74-6869085fbb7e.png">

**Comment by moklick** [comment]
Hey @Gunner17 

you would need to call getIncomers recursively until there are no more incomers.
