### ISSUE TITLE
Smooth Panning Transition

### ISSUE THREAD

**Issue by JamesyJi** [wbkd/react-flow#791]
Hi, is it possible to have a smooth pan transition? Right now, when I click/search for a node, I want my view to centre on that node. Currently, I just set the coordinates and it abruptly teleports to that node. Is there a way to make this a smooth transition instead? (By smooth I mean like similar to when the user themselves drags around the pane and it moves really smoothly).

If not, could it be a possible feature request for when you have time? 

Thank you for considering!

**Comment by moklick** [comment]
Are you using the panZoomHelpers? A transition is not built in but you can use something like [tween.js](https://github.com/tweenjs/tween.js/) (the example in the readme fits to your use case) and call `transform` multiple times.

**Comment by moklick** [comment]
Hey @JamesyJi. I also added a `setCenter` function for the `useZoomPanHelper` today (v8.3.0). That should make it easier to center a node.
