### ISSUE TITLE
Pane Coordinates to Screen Coordinates

### ISSUE THREAD

**Issue by GDnsk** [wbkd/react-flow#795]
Hello, thank you for this excellent library. I am trying to implement a way to zoom in a specific node automatically, is there a way for me to translate the position of a node to use setTransform function from ReactFlow Instance?

Thank you.

**Comment by moklick** [comment]
You can use the `setCenter` function of the `useZoomPanHelper` hook https://reactflow.dev/docs/api/hooks/

**Comment by GDnsk** [comment]
Ooh thank you, i completely missed the focus node button. Thank you this is exactly what i needed.

**Comment by GDnsk** [comment]
> You can use the `setCenter` function of the `useZoomPanHelper` hook https://reactflow.dev/docs/api/hooks/ example implementation: https://reactflow.dev/examples/use-zoom-pan-helper-hook/

Hello again, i am using version 8.3.2 and it seens that setCenter function on useZoomPanHelper does not exist. I tried to use transform function but it goes off my flowMap.
```js
  const store = useStore();
  const { zoomIn, zoomOut,transform} = useZoomPanHelper();
  const { nodes } = store.getState();


  const handleFind = (id) => {
    if (nodes.length) {
      const node = nodes.find( el => el.id == id)
      const x = node.__rf.position.x + node.__rf.width / 2;
      const y = node.__rf.position.y + node.__rf.width / 2;
      const zoom = 1.85;
      transform({x,y,zoom});
    }
}

**Comment by moklick** [comment]
The `setCenter` function should still work. Do you get an error?

**Comment by moklick** [comment]
We closed this issue due to inactivity. Feel free to re-open it when the issue still occurs.
