### ISSUE TITLE
Drag and Drop Is being pushed by css margins

### ISSUE THREAD

**Issue by Nenry** [wbkd/react-flow#796]
Hello,
First of all. Wanted to say this library is absolutely wonderful and a real life savior for me. Thank you so much!!

Now onto the issue...
I have my own project where there is margin being added to the main content to account for a Navbar and Sidebar. Everything looks fine when I try to implement the exact component for the drag and drop example. When I attempt to drag and drop something from the side menu, the margin pushes it off. If there is no margin then it works properly.

**Steps to reproduce:**
https://github.com/wbkd/react-flow/blob/main/example/src/DragNDrop/index.js
1. add `style={{marginLeft: 200}}` to the outer div in that DragNDrop example
2. Attempt to drag and drop a node from pane menu onto the canvas
3. You will notice that the drop is offset by the margin

It seems to be affected by any type of margin. 

What is the best solution for this?

**Comment by Nenry** [comment]
Ooops. Spoke too soon. 
Just had to modify the X and Y coordinates according to margin in the onDrop function. Thank you. 😄 
const position = reactFlowInstance.project({ x: event.clientX, y: event.clientY - 40 });

**Comment by moklick** [comment]
Great that it worked out :) on the website you can find a generic solution for sour problem here (when I got it right) https://reactflow.dev/examples/drag-and-drop/

**Comment by Nenry** [comment]
> Great that it worked out :) on the website you can find a generic solution for sour problem here (when I got it right) https://reactflow.dev/examples/drag-and-drop/

WOOOH! Thank you so much!
