### ISSUE TITLE
Custom Icon support in Handle component

### ISSUE THREAD

**Issue by Gunner17** [wbkd/react-flow#799]
The [handle](https://reactflow.dev/docs/api/handle/) component currently allows us to style the dots using its' style attribute. But can we replace these source/target dots with some custom icon (e.g. Fontawesome Icons) or use a custom component in place of these dots?

<img width="239" alt="Screen Shot 2020-12-22 at 11 09 15 PM" src="https://user-images.githubusercontent.com/11354728/102969652-eca07580-44aa-11eb-988b-a4e86c40ebc3.png">

**Comment by moklick** [comment]
I never thought about this use case. It's not possible to pass any children to the `Handle` component but I think we could change that. Right now you could achieve it by using CSS and create a pseudo element with `::before` or `::after`.

**Comment by Gunner17** [comment]
Thanks for the info. 👍

**Comment by jonra1993** [comment]
Hello everyone after some time looking for a solution for this I followed @moklick suggestions. Maybe it can help others in the future.
```

import { Handle, Position, NodeProps, Connection, Edge, HandleType } from 'react-flow-renderer';
import styled from 'styled-components';

const CustomBottomHandle = styled(Handle)`
&& {
  left: calc(100% / 2 - 20px);
  bottom: -20px;
  transform: translateY(0px);
  background: #EF8354;
  border-radius: 20px 20px 20px 20px;
  height: 40px;
  width: 40px;
  &:after {
    position: absolute;
    top: calc(10%);
    left: calc(25%);
    font-family: 'Material Icons';
    font-size: 20px;        
    color: white;
    content: "add";
  }  
  &:hover {
    background: #ed956f;
  };
}`;



// use handle in your code
  <CustomBottomHandle
    type="source"
    position={Position.Bottom}
  />
```


![image](https://user-images.githubusercontent.com/23468720/129104921-ab4d33df-d0d1-484f-9d6a-808f97ef0b18.png)
