### ISSUE TITLE
Need space on the edge from source and target

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#800]
@moklick I want to make an edge something like this, where there is some space from source and target connectors.
![image](https://user-images.githubusercontent.com/22545835/102998004-4b69fb80-454c-11eb-9895-c52445d20f99.png)

**Comment by RickeyWard** [comment]
You can create custom nodes, start with the smooth step edge, and an extra bend if the target is behind the source + some arbitrary padding. It would be a great addition. When I get a chance I'm going to poke around with this myself.

This is more or less a duplicate of #503

**Comment by RickeyWard** [comment]
A quick and messy example would just have you modify the GetSmoothStepPath function to add a padding.
Not sure what issues this could cause, but It does do what you're asking.

```javascript
const padding = 50;
const halfPadding = padding/2;

export function getSmoothStepPath({
  sourceX,
  sourceY,
  sourcePosition = Position.Bottom,
  targetX,
  targetY,
  targetPosition = Position.Top,
  borderRadius = 5,
  centerX,
  centerY,
}: GetSmoothStepPathParams): string {
  const [_centerX, _centerY, offsetX, offsetY] = getEdgeCenter({ sourceX, sourceY, targetX, targetY });
  const cornerWidth = Math.min(borderRadius, Math.abs(targetX - sourceX));
  const cornerHeight = Math.min(borderRadius, Math.abs(targetY - sourceY));
  const cornerSize = Math.min(cornerWidth, cornerHeight, offsetX, offsetY);
  const leftAndRight = [Position.Left, Position.Right];
  const cX = typeof centerX !== 'undefined' ? centerX : _centerX;
  const cY = typeof centerY !== 'undefined' ? centerY : _centerY;

  let firstCornerPath = null;
  let secondCornerPath = null;

  let sourceHPadding = "";
  let targetHPadding = "";

  if (sourceX + padding <= targetX) {
    firstCornerPath =
      sourceY <= targetY ? bottomLeftCorner(sourceX, cY, cornerSize) : topLeftCorner(sourceX, cY, cornerSize);
    secondCornerPath =
      sourceY <= targetY ? rightTopCorner(targetX, cY, cornerSize) : rightBottomCorner(targetX, cY, cornerSize);
  } else { // here is the case specifically where new corners need introduced
    firstCornerPath =
      sourceY < targetY ? bottomRightCorner(sourceX + halfPadding, cY, cornerSize) : topRightCorner(sourceX + halfPadding, cY, cornerSize);
      sourceHPadding =
      `${sourceY <= targetY ? rightTopCorner(sourceX + halfPadding, sourceY, cornerSize) : rightBottomCorner(sourceX + halfPadding, sourceY, cornerSize)}` ;
      secondCornerPath =
      sourceY < targetY ? leftTopCorner(targetX - halfPadding, cY, cornerSize) : leftBottomCorner(targetX - halfPadding, cY, cornerSize);
      targetHPadding =
      `${sourceY < targetY ? bottomLeftCorner(targetX - halfPadding, targetY, cornerSize) : topLeftCorner(targetX - halfPadding, targetY, cornerSize)}` ;
  }

  if (leftAndRight.includes(sourcePosition) && leftAndRight.includes(targetPosition)) {
    if (sourceX + padding <= targetX) {
      firstCornerPath =
        sourceY <= targetY ? rightTopCorner(cX, sourceY, cornerSize) : rightBottomCorner(cX, sourceY, cornerSize);
      secondCornerPath =
        sourceY <= targetY ? bottomLeftCorner(cX, targetY, cornerSize) : topLeftCorner(cX, targetY, cornerSize);
    }
  } else if (leftAndRight.includes(sourcePosition) && !leftAndRight.includes(targetPosition)) {
    if (sourceX + padding <= targetX) {
      firstCornerPath =
        sourceY <= targetY
          ? rightTopCorner(targetX, sourceY, cornerSize)
          : rightBottomCorner(targetX, sourceY, cornerSize);
    } else {
      firstCornerPath =
        sourceY <= targetY
          ? bottomRightCorner(sourceX, targetY, cornerSize)
          : topRightCorner(sourceX, targetY, cornerSize);
    }
    secondCornerPath = '';
  } else if (!leftAndRight.includes(sourcePosition) && leftAndRight.includes(targetPosition)) {
    if (sourceX + padding <= targetX) {
      firstCornerPath =
        sourceY <= targetY
          ? bottomLeftCorner(sourceX, targetY, cornerSize)
          : topLeftCorner(sourceX, targetY, cornerSize);
    } else {
      firstCornerPath =
        sourceY <= targetY
          ? bottomRightCorner(sourceX, targetY, cornerSize)
          : topRightCorner(sourceX, targetY, cornerSize);
    }
    secondCornerPath = '';
  }

  return `M ${sourceX},${sourceY}${sourceHPadding}${firstCornerPath}${secondCornerPath}${targetHPadding}L ${targetX},${targetY}`;
}
```

**Comment by agarwal00s** [comment]
@RickeyWard Thank for the support. It is working as expected.

**Comment by moklick** [comment]
Thanks @RickeyWard! Looks good.

**Comment by RickeyWard** [comment]
Need to introduce a 2nd cornerSize to fix weirdness at some positions. I'll figure it out proper and do a PR that takes a optional padding.

**Comment by chenyphaaa** [comment]
> A quick and messy example would just have you modify the GetSmoothStepPath function to add a padding.
> Not sure what issues this could cause, but It does do what you're asking.
> 
> ```js
> const padding = 50;
> const halfPadding = padding/2;
> 
> export function getSmoothStepPath({
>   sourceX,
>   sourceY,
>   sourcePosition = Position.Bottom,
>   targetX,
>   targetY,
>   targetPosition = Position.Top,
>   borderRadius = 5,
>   centerX,
>   centerY,
> }: GetSmoothStepPathParams): string {
>   const [_centerX, _centerY, offsetX, offsetY] = getEdgeCenter({ sourceX, sourceY, targetX, targetY });
>   const cornerWidth = Math.min(borderRadius, Math.abs(targetX - sourceX));
>   const cornerHeight = Math.min(borderRadius, Math.abs(targetY - sourceY));
>   const cornerSize = Math.min(cornerWidth, cornerHeight, offsetX, offsetY);
>   const leftAndRight = [Position.Left, Position.Right];
>   const cX = typeof centerX !== 'undefined' ? centerX : _centerX;
>   const cY = typeof centerY !== 'undefined' ? centerY : _centerY;
> 
>   let firstCornerPath = null;
>   let secondCornerPath = null;
> 
>   let sourceHPadding = "";
>   let targetHPadding = "";
> 
>   if (sourceX + padding <= targetX) {
>     firstCornerPath =
>       sourceY <= targetY ? bottomLeftCorner(sourceX, cY, cornerSize) : topLeftCorner(sourceX, cY, cornerSize);
>     secondCornerPath =
>       sourceY <= targetY ? rightTopCorner(targetX, cY, cornerSize) : rightBottomCorner(targetX, cY, cornerSize);
>   } else { // here is the case specifically where new corners need introduced
>     firstCornerPath =
>       sourceY < targetY ? bottomRightCorner(sourceX + halfPadding, cY, cornerSize) : topRightCorner(sourceX + halfPadding, cY, cornerSize);
>       sourceHPadding =
>       `${sourceY <= targetY ? rightTopCorner(sourceX + halfPadding, sourceY, cornerSize) : rightBottomCorner(sourceX + halfPadding, sourceY, cornerSize)}` ;
>       secondCornerPath =
>       sourceY < targetY ? leftTopCorner(targetX - halfPadding, cY, cornerSize) : leftBottomCorner(targetX - halfPadding, cY, cornerSize);
>       targetHPadding =
>       `${sourceY < targetY ? bottomLeftCorner(targetX - halfPadding, targetY, cornerSize) : topLeftCorner(targetX - halfPadding, targetY, cornerSize)}` ;
>   }
> 
>   if (leftAndRight.includes(sourcePosition) && leftAndRight.includes(targetPosition)) {
>     if (sourceX + padding <= targetX) {
>       firstCornerPath =
>         sourceY <= targetY ? rightTopCorner(cX, sourceY, cornerSize) : rightBottomCorner(cX, sourceY, cornerSize);
>       secondCornerPath =
>         sourceY <= targetY ? bottomLeftCorner(cX, targetY, cornerSize) : topLeftCorner(cX, targetY, cornerSize);
>     }
>   } else if (leftAndRight.includes(sourcePosition) && !leftAndRight.includes(targetPosition)) {
>     if (sourceX + padding <= targetX) {
>       firstCornerPath =
>         sourceY <= targetY
>           ? rightTopCorner(targetX, sourceY, cornerSize)
>           : rightBottomCorner(targetX, sourceY, cornerSize);
>     } else {
>       firstCornerPath =
>         sourceY <= targetY
>           ? bottomRightCorner(sourceX, targetY, cornerSize)
>           : topRightCorner(sourceX, targetY, cornerSize);
>     }
>     secondCornerPath = '';
>   } else if (!leftAndRight.includes(sourcePosition) && leftAndRight.includes(targetPosition)) {
>     if (sourceX + padding <= targetX) {
>       firstCornerPath =
>         sourceY <= targetY
>           ? bottomLeftCorner(sourceX, targetY, cornerSize)
>           : topLeftCorner(sourceX, targetY, cornerSize);
>     } else {
>       firstCornerPath =
>         sourceY <= targetY
>           ? bottomRightCorner(sourceX, targetY, cornerSize)
>           : topRightCorner(sourceX, targetY, cornerSize);
>     }
>     secondCornerPath = '';
>   }
> 
>   return `M ${sourceX},${sourceY}${sourceHPadding}${firstCornerPath}${secondCornerPath}${targetHPadding}L ${targetX},${targetY}`;
> }
> ```

i'm sorry,where should i use the function `getSmoothStepPath` in customEdge?
```
import { FC } from 'react';
import { EdgeProps, getBezierPath, getSmoothStepPath, getMarkerEnd, EdgeText, getEdgeCenter } from 'react-flow-renderer';

const CustomEdge: FC<EdgeProps> = ({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  data,
  arrowHeadType,
  markerEndId,
}) => {
  const edgePath = getBezierPath({ sourceX, sourceY, sourcePosition, targetX, targetY, targetPosition });
  const markerEnd = getMarkerEnd(arrowHeadType, markerEndId);
  const [centerX, centerY] = getEdgeCenter({
    sourceX,
    sourceY,
    targetX,
    targetY,
  });
  

  return (
    <>
      <path id={id} className="react-flow__edge-path" d={edgePath} markerEnd={markerEnd} />
      <EdgeText
        x={centerX}
        y={centerY}
        label={data.text}
        labelStyle={{ fill: 'white' }}
        labelShowBg
        labelBgStyle={{ fill: 'red' }}
        labelBgPadding={[2, 4]}
        labelBgBorderRadius={2}
      />
      ;
    </>
  );
};

export default CustomEdge;

```

**Comment by RomanistNLX** [comment]
>
> I'm sorry,i want to use it,but i can't find the function topLeftCorner,bottomRightCorner
>

https://github.com/wbkd/react-flow/blob/main/src/components/Edges/SmoothStepEdge.tsx#L11
