### ISSUE TITLE
Remove Element on Delete Keypress

### ISSUE THREAD

**Issue by rajeshwari-differenz123** [wbkd/react-flow#801]
Hi,
can any one please tell me that keypress feature is there or not 
i want to remove element and edge on keypress

**Comment by moklick** [comment]
yes, this feature is built in. You can find the information in the docs how to set it up https://reactflow.dev/docs/getting-started/#basic-functionality

**Comment by MaartenBreeedveld** [comment]
Just for reference: Current version (10.3.11) supports a string array only.

```
     <ReactFlow
        deleteKeyCode={['Delete']}
      ></ReactFlow>
```
