### ISSUE TITLE
Manually emit onElementsRemove

### ISSUE THREAD

**Issue by charithreddyv** [wbkd/react-flow#808]
Currently whenever i hit on delete btn onElementsRemove is being emitted is there a way i cound click some button (html button on element/node) on a element/node and make it emit onElementsRemove.
Thanks in advance.

**Comment by moklick** [comment]
`onElementsRemove` is just the event handler when you delete an element by pressing the key that is configured by `deleteKey`. You could also use a button or any other user action to alter your elements array. To get the selected elements you can listen to the `onSelectionChange` event.

**Comment by dmitrycreator** [comment]
@moklick hello, do you have an example of delete by button?
