### ISSUE TITLE
How to make edge on itself in 8.3.1 version?

### ISSUE THREAD

**Issue by pavelturch** [wbkd/react-flow#809]
Hi! In 7.x version there was a next possibility: 
![image](https://user-images.githubusercontent.com/3693413/103265729-4d561380-49bf-11eb-9eab-73e7dd107daa.png)

Code from 7.x version for renderEdge method:

![image](https://user-images.githubusercontent.com/3693413/103266301-5c899100-49c0-11eb-9474-63e9b620d3aa.png)

And new code in 8.x version:

![image](https://user-images.githubusercontent.com/3693413/103266502-c4d87280-49c0-11eb-973f-61a81cb7b8cc.png)
![image](https://user-images.githubusercontent.com/3693413/103266522-d1f56180-49c0-11eb-803c-d80ec70abbe6.png)

sourceId and targetId are equals.

**Comment by moklick** [comment]
Can you try to set `connectionMode="loose"`?

**Comment by pavelturch** [comment]
`connectionMode="loose"` does not help. Main problem

**Comment by pavelturch** [comment]
connectionMode="loose" does not help. 
The main problem is that `edge.source === edge.target` and in the new library method getSourceTargetNodes:
`else if (node.id === edge.target)`. 
You should see a code 7th version. There no dependency from `edge.source` and target edge doesn't have a null-value.

**Comment by moklick** [comment]
Hey @pavelturch 

thanks for the hint. Could you try v8.3.2?

**Comment by pavelturch** [comment]
Thank you very much! It's OK )
