### ISSUE TITLE
ConnectionLine zIndex Problem

### ISSUE THREAD

**Issue by andrewdkim** [wbkd/react-flow#810]
Hello!
First off, thank you for making and actively updating this wonderful project.  It's absolutely one of the most amazing libraries I have ever worked with. 

I'm currently running into a problem where I want to render a custom made Connection Line on top of the nodes. 

Here's the current situation:
![pic1](https://user-images.githubusercontent.com/46148447/103334426-38b96000-4a3f-11eb-8592-05e4c7d40ea8.png)

What I want to achieve: 
![pic1 2](https://user-images.githubusercontent.com/46148447/103334443-4c64c680-4a3f-11eb-870b-9787a8f4794b.png)

I'm aware that z index is not an option for SVG, but is there a way to render the SVG on top of other nodes in the graph? Thanks!

**Comment by RickeyWard** [comment]
Edges are rendered as on SVG on a "layer" behind the nodes. If you wanted the edges to all be in front of the nodes, override the z-index of the whole svg.

```css
.react-flow__edges {
  z-index: 4 !important; /* normally 2, as nodes are 3 */
}
```

This could cause issues, but in a quick example it did work. From looking at the source code there's no library interface that allows you to put edges in front of nodes.

**Comment by moklick** [comment]
Thanks @RickeyWard
