### ISSUE TITLE
[bug]  When adding new handles dynamically, the edges do not remain in place. But when I add to the json and the screen and reload correctly.

### ISSUE THREAD

**Issue by washingtonklebio** [wbkd/react-flow#811]
Expected behavior

![Captura de tela de 2020-12-30 09-29-18](https://user-images.githubusercontent.com/37412752/103351320-a4bcb800-4a81-11eb-8282-9777ddb032d6.png)

What's happening

![Captura de tela de 2020-12-30 09-29-37](https://user-images.githubusercontent.com/37412752/103351326-aa1a0280-4a81-11eb-9518-a04de031c250.png)

I removed a handle and the edges continued as before

**Comment by moklick** [comment]
I will close this issue because we have a very similar one: #805 
You can add your screenshots in the 805 issue.
