### ISSUE TITLE
Examples with Data Passing

### ISSUE THREAD

**Issue by rahulbrahmal** [wbkd/react-flow#812]
Hi!

There is an example of your website (screenshot below) of a flow where data is getting passed from one node to another when connected. I can't seem to find the source code for this. Could anyone point me in the direction of where I could see this?

![image](https://user-images.githubusercontent.com/24690504/103412391-c9418e80-4b6c-11eb-8373-31c18475de6c.png)

**Comment by moklick** [comment]
Hi @rahulbrahmal 

you can find the source code in the react-flow-docs repo: https://github.com/wbkd/react-flow-docs/tree/main/src/components/HeroFlow

**Comment by rahulbrahmal** [comment]
Thank you! Sorry I didn't see that!

**Comment by eiiot** [comment]
The example on the homepage doesn't actually use the connections of nodes to pass data, just `useState`. (You can test this by deleting one of the edges, and the components still change the output) Are there any examples of actual data passing between nodes? For example, node `A` has some store variable set to `x` that is controlled by a slider, than can be accessed by node `B` when connected via an edge.

**Comment by pot-code** [comment]
@eiiot i managed to setup a flow just like you said. i have used rxjs for data subscription/streaming

it works but have one critical issue: race condition, because node data were set in listeners by calling setNodes, some updates would overwrite the others so that some nodes remain unchanged

**Comment by moklick** [comment]
React Flow 12 ([alpha already launched](https://github.com/xyflow/xyflow/discussions/3764)) has some helpers for handling data flow: `useHandleConnections`, `useNodesData` and `updateNodeData`. `setNodes`, `updateNode` etc is batched in React Flow 12.
