### ISSUE TITLE
Handle ids are not exposed to custom edges

### ISSUE THREAD

**Issue by ryanwr** [wbkd/react-flow#814]
It appears the source and target handle ids are not passed to the custom edge component when wrapped unless I'm missing something:

https://github.com/wbkd/react-flow/blob/4cb558403c9604395c9abbe2a3fb7e8dbc518e21/src/components/Edges/wrapEdge.tsx#L147

**Comment by moklick** [comment]
released in v8.3.4

**Comment by ryanwr** [comment]
Thank you!
