### ISSUE TITLE
resize-observer-browser

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [wbkd/react-flow#816]
Great to see such an awesome project I want to include !

Installed react-flow-renderer, started up my server, booom !

Failed to compile.

MY-PATH/node_modules/react-flow-renderer/dist/types/index.d.ts
Type error: Cannot find type definition file for 'resize-observer-browser'.  TS2688
    1 | /// reference types="resize-observer-browser" 
      |                       ^
    2 | import { CSSProperties, MouseEvent as ReactMouseEvent } from 'react';
    3 | export declare type ElementId = string;
    4 | export declare type FlowElement = Node | Edge;

**Comment by NilsBaumgartner1994** [comment]
Needed to install additionally:

npm install @types/d3@6.2.0
npm install @types/resize-observer-browser
 npm install typescript@4.1.3

**Comment by NilsBaumgartner1994** [comment]
After that all compiles but shows me nothin on the page.

Need to add specific height/width (had height=0 before, why ever)

<ReactFlow elements={elements} style={{height: 400, width: 500}}/>

**Comment by moklick** [comment]
Hey @NilsBaumgartner1994 

that is strange. All the packages devDependencies as you can see in the package.json. 
It's documented that the parent needs a width and height https://reactflow.dev/docs/getting-started/

**Comment by NilsBaumgartner1994** [comment]
Hello @moklick,

You're right with the height and width, my fault.
Well, with the dependencies for me its strange too. Well maybe someone will have the same problem.

Thank you for the fast reply

**Comment by moklick** [comment]
Yep, thanks for pointing it out. Are you using windows?

**Comment by NilsBaumgartner1994** [comment]
Unfortunately Mac (macOS Cataline 10.15.6)
