### ISSUE TITLE
Overlapping Edge Labels

### ISSUE THREAD

**Issue by jamal-ahmad** [wbkd/react-flow#819]
Quick question regarding edge labels.
Is there a way to make the edge labels not overlap? This issue arises when node A and B are connected to each other (see diagram below)

![Screen Shot 2021-01-04 at 1 24 34 PM](https://user-images.githubusercontent.com/24233389/103566583-3b2d1700-4e90-11eb-9c47-e7b1ab52ba6d.png)

**Comment by moklick** [comment]
Hey @jamal-ahmad 

You could implement a custom edge type that knows about the other edges (and edge labels). Then run a collision detection on the labels and rearrange them. Does it help?

**Comment by jamal-ahmad** [comment]
That makes sense, but i have two questions:
1. For accessing other edges inside a custom edge i would use the following?
```tsx
const graphEdges = useStoreState(flowStore => flowStore.edges);
```
2. The `Edge` objects accessed using the hook above don't have location or sizing info (i tried console logging it). Without those how would you calculate collisions?

Collision resolution I imagine would be simple, maybe something like move both edge labels closer to their edge source handles in increments of `0.1*edgeLength` until no collision is detected.

**Comment by moklick** [comment]
Hey!

1. Yes, but you also need the nodes `const nodes = useStoreState(store => store.nodes);`

2. The edges do not contain any information about the position but the nodes do. When an edge goes from node A to node B, you can take the handleBounds information of the regarding nodes to calculate the bounds. We are doing something similar in the edge renderer to check if an edge is visible https://github.com/wbkd/react-flow/blob/main/src/container/EdgeRenderer/utils.ts#L123-L151 

Is your graph interactive? Maybe we can find a simpler solution for your issue.

**Comment by moklick** [comment]
We will close this issue due to inactivity. Feel free to open it again if you still need help to solve this.

**Comment by sskanishk** [comment]
I have similar issue as above.
And one more is how to handle label which is stick to edge -> i want it horizontal in any condition.
![Screenshot 2021-03-13 at 10 11 43 PM](https://user-images.githubusercontent.com/29313203/111037885-1cc53800-844c-11eb-88c1-b61d0c743cc5.png)

**Comment by josealvarez97** [comment]
Hi @moklick, I feel like the `getBezierPath` function (and all other similar path functions) should return an automatically adjusted path for any edge that is connected to the same two nodes. This is the standard behavior in most graph visualization engines, such as the one of [https://console.neo4j.io/](https://console.neo4j.io/). As a user this was the behavior I was expecting when connecting two nodes. Alternatively, it would be nice if the documentation had an example addressing this use case of the library.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/21250471/218539043-19691c6e-624f-4c66-a890-ec21f1be1cd4.png">

**Comment by KriticaCelito** [comment]
Hi @josealvarez97 Do you have any solution of the above image how to get that, I'm having the same issue it's overlapping

**Comment by jakpren** [comment]
Hi @KriticaCelito, you can use this library to solve this issue

[react-flow-smart-edge](https://github.com/tisoap/react-flow-smart-edge)

**Comment by kvz** [comment]
react-flow-smart-edge is compatible with 'reactflow', but not with '@xyflow/react'. I tried and hit the same as this locked issue here: https://github.com/tisoap/react-flow-smart-edge/issues/61, doesn't look like they will fix this. Meanwhile it's the first thing I hit trying to make a diagram. When two components interact at multiple stages in a process, the labels will stack and you can't see them, without implementing custom collision detection logic.

**Comment by Ramkumar-r7** [comment]
Do we find any solution on this issue,it got closed??
![image](https://github.com/user-attachments/assets/a02f12cd-f32d-46f7-b246-65a19040b049)

**Comment by Faakhir30** [comment]
+1 for this issue

![Image](https://github.com/user-attachments/assets/8e93aa81-d7d4-4618-8776-31841e47346e)

Someone please fix this 🙏

**Comment by tisoap** [comment]
I'm the creator of [react-flow-smart-edge](https://github.com/tisoap/react-flow-smart-edge) , a library that uses using A* pathfinding to route edges around other nodes, avoiding intersections. It has smart equivalents for every type of edge React Flow has. It's been updated to work with React Flow 12.
