### ISSUE TITLE
How to delete node

### ISSUE THREAD

**Issue by sahilkhaire** [wbkd/react-flow#821]
I am new in react flow and started building new application. following are the issues I am facing
1. how to show delete icon or how to delete node in flow.
2. how to get click event of node so we can perform operations. i need to do like after clicking on node one popup will come for filling details regarding that node.

**Comment by leejustin** [comment]
1. You can delete a node with `removeElements` documented here: https://reactflow.dev/docs/api/helper-functions/
2. You can use `onElementClick` on `ReactFlow` and an example can be found here: https://reactflow.dev/examples/custom-node/
