### ISSUE TITLE
Multiple ReactFlow instances in a single page not working

### ISSUE THREAD

**Issue by bosskwei** [wbkd/react-flow#822]
Hi guys,

I need to draw multi flowcharts in one page, just like the index page of https://reactflow.dev/, but seems not working.

``` html
<ReactFlow id="react-flow-1" elements={elements_1} >
</ReactFlow>
<ReactFlow id="react-flow-2" elements={elements_2} >
</ReactFlow>
```

The code above generate 2 charts but all are react-flow-2 (seems react-flow-2 overlap all elements and config).

Why this happened, and how to fit it? (using iframe can fix this problem, but not a good solution)

Thanks

**Comment by moklick** [comment]
Hey @bosskwei 

you need to wrap each flow with a `ReactFlowProvider` https://reactflow.dev/docs/api/components/provider/ 
I will add the information to the docs.

**Comment by bosskwei** [comment]
Thank you ~ @moklick
