### ISSUE TITLE
Can we resize the chart based on parent container size?

### ISSUE THREAD

**Issue by Gunner17** [wbkd/react-flow#823]
Is there a way to resize or force fit the flow chart inside the parent container? For example, if I render the chart in a 500 * 500 container then the chart should occupy maximum available space. But if I resize the parent container to 250 * 250, then the chart should resize itself to fit into the smaller container? 

- May be this feature is not supported right now, but can we achieve it using something like 'zoom' or in any other way?

**Comment by moklick** [comment]
How are you resizing the chart? You could call a fitView after the resize event.

**Comment by Gunner17** [comment]
@moklick Thanks!! Exactly what I was looking for.

**Comment by Krithika3** [comment]
@Gunner17 is there an example you have for this? I would highly appreciate it
