### ISSUE TITLE
Smooth panning transition examples

### ISSUE THREAD

**Issue by dev-mish-mash** [wbkd/react-flow#825]
First of all, I thank you for this lib. It is really helpful to my application.

I needed the smooth panning transition, so I was able to successfully implement it using tween.js as your team previously mentioned in another issue #791.

Then, I reckon having some examples would be helpful to others who looking for similar features because it was little bit of work for me. So after I refine my work a bit, I would like to make a PR about smooth transition example, probably for zoom-in / zoom-out / fit-view 

What do you think of it?

**Comment by moklick** [comment]
Hey @dev-mish-mash 

good idea :) We would really appreciate that! 

Please open it in the website repo: https://github.com/wbkd/react-flow-docs/tree/main/src/example-flows
