### ISSUE TITLE
[BUG] fitView 1 and 2 elements

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [wbkd/react-flow#831]
Since ReactFlow its awesome I have some troubles in order to use fitView. I hope that its only my bad understanding.
When using fitView with more than 2 elements it works like a charm.
But when trying to display 1 or 2 elements, magic begins.

Information:
I started with the basic example from the tutorial. Gave the parent a height, since width is automaticly used max. I also tried to give it a specific width (in that case same as height).
But always the same result. 

3 Elements :-)
<img width="1218" alt="Bildschirmfoto 2021-01-11 um 09 11 37" src="https://user-images.githubusercontent.com/33295329/104158135-04558480-53ed-11eb-9001-e96c0c4fde0f.png">

2 Elements
<img width="1212" alt="Bildschirmfoto 2021-01-11 um 09 11 55" src="https://user-images.githubusercontent.com/33295329/104158150-0e778300-53ed-11eb-8cac-ec5856a8b9fc.png">

1 Element
<img width="1229" alt="Bildschirmfoto 2021-01-11 um 09 12 13" src="https://user-images.githubusercontent.com/33295329/104158173-19321800-53ed-11eb-8305-e97d60ed516d.png">

**Comment by moklick** [comment]
Could you check if this works with v8.3.7?

**Comment by NilsBaumgartner1994** [comment]
> Could you check if this works with v8.3.7?

Works :-)
Was a problem in v8.3.2
