### ISSUE TITLE
Support for children in Handle component

### ISSUE THREAD

**Issue by ryanwr** [wbkd/react-flow#833]
When creating a custom node it would be nice if the Handle component supported children to make it easier to use the Handle positioning whilst adding additional elements beside it.

My use case is for adding labels to the node handles, currently the way we have styled this is a bit hacky but works.

![image](https://user-images.githubusercontent.com/9446239/104236632-c5f0b180-544e-11eb-994f-14caaf879560.png)

**Comment by moklick** [comment]
good idea. We will add that.

**Comment by moklick** [comment]
released in v8.3.7. You can now pass children and also html attributes.
