### ISSUE TITLE
Is it possible to customize edges as starts out thick and gets thinner until reaching target?

### ISSUE THREAD

**Issue by ugrdursun** [wbkd/react-flow#837]
Is it possible to do [THIS ](https://i.stack.imgur.com/wQioJ.jpg) to edges ?

**Comment by moklick** [comment]
Yes, could achieve this by implementing a custom edge. In this example you can find an implementation: https://reactflow.dev/examples/edges/

**Comment by ugrdursun** [comment]
> Yes, could achieve this by implementing a custom edge. In this example you can find an implementation: https://reactflow.dev/examples/edges/

Thanks for your reply, actually i only need bezierpath with variable thickness [(like this)](https://www.mindmapping.com/img/mind-map-example-empathy.png) and could not figure out how to do that with custom edge.
