### ISSUE TITLE
Rendering multiple ReactFlow components

### ISSUE THREAD

**Issue by janketj** [wbkd/react-flow#839]
Hey wbkd,

we have encountered a problem using your library in our new application. 
Our tool builds around your library and we let the user create, edit, etc. Flows. Since our users work with more than one flow, we have created an overview for them.

It appears that rendering multiple `ReactFlow` components leeds to every flow displaying the same elements.
What I can imagine is that the `ReactFlow` library is re-setting it's own store via Redux action and therefore being able to only show one flow (the last in the iterated list).

Is there a way currrently to render multiple `ReactFlow` components? If not is it possible to add an identifier to the Redux store to be able to differentiate rendered flows?

If I'm missing something here or you have an idea, I would be very glad to hear from you.

Keep up the good work!

Cheers,

Janket

**Comment by moklick** [comment]
Hey @janketj 

you need to wrap each flow with a `ReactFlowProvider` https://reactflow.dev/docs/api/components/provider/
