### ISSUE TITLE
Add reset zoom button to Controls

### ISSUE THREAD

**Issue by jefvel** [wbkd/react-flow#841]
It would be nice to have

**Comment by moklick** [comment]
Hey @jefvel 

It's a good idea but we will not expand the controls component. It is simple to re-implement it with your own functionalities. You can find everything you need in the  `useZoomPanHelper` hook. https://reactflow.dev/docs/api/hooks/

**Comment by moklick** [comment]
You can now easily extend the controls: https://reactflow.dev/docs/api/components/controls/#extended-controls
