### ISSUE TITLE
Zoom with cmd+wheel / ctrl+wheel

### ISSUE THREAD

**Issue by jhroemer** [wbkd/react-flow#847]
Feature request: I'm currently using the `panOnScroll`, and I'm missing a convenient way to zoom. While the controls and plus/minus buttons do the trick, what would be really nice is if by default I could zoom with cmd+wheel / ctrl+wheel when `panOnScroll = true`. 

Thank you for developing a very nice package.

**Comment by moklick** [comment]
I added a `zoomActivationKeyCode` prop which is `Meta` by default. Documented here: https://reactflow.dev/docs/api/component-props/

**Comment by jhroemer** [comment]
That is really amazing. Thanks a lot for the incredibly fast response and implementation 👏
