### ISSUE TITLE
Selected edges are not placed last in SVG element

### ISSUE THREAD

**Issue by yard** [wbkd/react-flow#849]
Once an edge is selected and it's partially obscured by another edge, the selection would render in a bit weird way:

<img width="72" alt="Screen Shot 2021-01-20 at 11 34 33" src="https://user-images.githubusercontent.com/62775/105148483-7a579b00-5b13-11eb-9b85-22fdf6269513.png">

(in the above example the horizontal edge is selected and it's obscured by an edge turning 90 degrees down).

Given SVG doesn't support z-index (last defined, last rendered principle is in effect), I believe the SVG renderer should re-order the elements placing selected edges at the very end.

**Comment by moklick** [comment]
This is fixed in v10. We now have multiple edge renderers with different z indices. You can also pass a zIndex to an edge as an option since v10.

**Comment by moklick** [comment]
If you don't want to set z-indices manually you can use the `elevateEdgesOnSelect` prop https://reactflow.dev/docs/api/react-flow-props/#edges
