### ISSUE TITLE
Question: Is there a way to insert a custom arrow marker?

### ISSUE THREAD

**Issue by AntonSynytsia** [wbkd/react-flow#851]
Hello,

First of all, thank you for the awesome tool. I have a question about adding a custom marker id to node edges.

The docs suggest I can assign a custom marker Id to a path, but I cannot seem to find a way to define a custom marker. Is there a way to add a marker to the svg containing the edges? I believe I somehow need to access the svg `<defs>` and define the marker there but I do not know how to access it.

Thanks in advance!

**Comment by moklick** [comment]
Hey!

You need to define the defs somewhere in your app like this:

```jsx
<ReactFlow elements={initialElements} markerEndId="my-marker" />
<svg width="0" height="0">
  <defs>
    <marker
      className="react-flow__arrowhead"
      id="my-marker"
      markerWidth="12.5"
      markerHeight="12.5"
      viewBox="-10 -10 20 20"
      orient="auto"
      refX="0"
      refY="0"
    >
      <polyline
        stroke="#000"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1"
        fill="#000"
        points="-5,-4 0,0 -5,4 -5,-4"
      />
    </marker>
  </defs>
</svg>
```

does it help?

**Comment by AntonSynytsia** [comment]
That works perfectly. Thank you!
