### ISSUE TITLE
pointerEvents for read only Nodes blocks JSX interactions

### ISSUE THREAD

**Issue by vittoriozamboni** [wbkd/react-flow#856]
Hi, thank you for this amazing work, it's a great library! Well documented and with clear examples.

I am working on an organization chart that needs to be "read only" (no selectable nodes, no dragging, etc). 
I am using a custom node with some JSX inside, specifically a link to a person profile. 

However, I can't click the link because of `pointerEvents` value.
This is set to none if the element is not selectable, draggable or no onClick handler is passed: https://github.com/wbkd/react-flow/blob/main/src/components/Nodes/wrapNode.tsx#L55

It would be nice if there was a documentation note or a property to override this explicitly (rather than digging and override style), for example a `hasClickableContent`.

**Comment by moklick** [comment]
A note about it would be good, that's correct but we will not add something like `hasClickableContent`. I think it's OK in this case to overwrite it with `pointer-events: all` inside the custom node.

**Comment by vittoriozamboni** [comment]
That's great, thanks!
