### ISSUE TITLE
onSelectionDrag, onSelectionDragStart, onSelectionDragStop not Triggered

### ISSUE THREAD

**Issue by AntonSynytsia** [wbkd/react-flow#858]
I tried version 8.7.0, and initially 8.5.0, the events are not triggered when dragging multiple nodes

**Comment by AntonSynytsia** [comment]
Edit: I was using my own selection box with setSelectedElements to select multiple nodes. When dragging one node, which also drags the other customly selected noes, the onNodeDrag is called (for one node) but the onSelectionDrag is not. I see that using the built-in selection box does indeed call the onSelectionDrag events. This should probably not be an issue then since I can use the native selection box.

**Comment by moklick** [comment]
Hey @AntonSynytsia 

I will close this issue, since the events only work with the built-in selection area.

**Comment by sgarbesi** [comment]
@moklick On a Mac, if you hold in the command key to select multiple nodes, then drag those nodes, the `onSelectionDragStop` even never fires, however, the `onNodeDragStop` event does fire, but it only returns the node that you used to drag. Is this is a bug or is there another way to figure out what nodes have finished dragged when you before the selection by holding the command key and click each of the nodes?

**Comment by moklick** [comment]
The `selectionDrag` events are only working for the selection area. If you want to get the selected elements you can do:

```
js
const selectedElements = useStoreActions(actions => actions.selectedElements);
```
