### ISSUE TITLE
Resetting Dimensions

### ISSUE THREAD

**Issue by leejustin** [wbkd/react-flow#860]
I'm using React Router and logic adapted from the [Layouting Example](https://reactflow.dev/examples/layouting/) to organize my nodes.

This is a very simplified example of my code:
```js
const FlowContainer = ({ id }) => {

  // I use a separate state management with React Context.
  const {elements, setElements} = useContext(NodeContext);

  // `id` loads the elements used in React Flow
  useEffect(() => {
    const unorderedElements = getData(id);

    // use Layouting example to organize nodes before setting them in React Flow
    const orderedElements = orderElements(elements);

    setElements(orderedElements);
  }

  <ReactFlow
        elements={elements}
  >
  </ReactFlow>
}
```

## Problem
When I leave my `FlowContainer` component with `history.back` and load another `FlowContainer` with a different set of data (different `id`), the layout generated becomes very off.

### Example
1. Load the first `FlowContainer` with `id=1`
Everything looks good.
_transform: 0, 0, 1
width: 0
height: 0_
<img width="328" alt="Screen Shot 2021-01-28 at 1 19 04 PM" src="https://user-images.githubusercontent.com/2660448/106200269-912d6b80-616b-11eb-8256-ba7ab19a4951.png">

2. Use React Router's `history.back()` and load `FlowContainer` with `id=2`
The width is off and causes the layouting logic to render bad results
_transform: 0, 0, 1
width: 375
height: 812_
<img width="328" alt="Screen Shot 2021-01-28 at 12 58 08 PM" src="https://user-images.githubusercontent.com/2660448/106200303-a1dde180-616b-11eb-8a16-86a470170077.png">

3. Use React Router's `history.back()` and load `FlowContainer` with `id=1`
_transform: 87.5, 406, 1
width: 375
height: 812_
The layouting logic causes what had previously rendered properly to layout with bad results
<img width="332" alt="Screen Shot 2021-01-28 at 1 19 20 PM" src="https://user-images.githubusercontent.com/2660448/106200370-b7eba200-616b-11eb-9058-66f13484b428.png">

4. Refresh the page (reload everything) while still on `FlowContainer` with `id=1`
Everything looks good again
_transform: 0, 0, 1
width: 0
height: 0_
<img width="328" alt="Screen Shot 2021-01-28 at 1 19 04 PM" src="https://user-images.githubusercontent.com/2660448/106200443-d94c8e00-616b-11eb-8edc-645976da6a0b.png">

## What I've Tried
I've tried using some of the following actions to "reset" the width/transform of `FlowContainer` in `useEffect` so that it would get "reset" every load...but it doesn't work.
```js
const { transform, fitView, setCenter } = useZoomPanHelper();
const transformState = useStoreState((store) => store.transform);
const updateSize = useStoreActions((actions) => actions.updateSize);
```

## Question
If you have any ideas on how I can troubleshoot, I would greatly appreciate it. Is there an internal action that I could look into using? Or am I overlooking something completely obvious?

Thank you!

**Comment by moklick** [comment]
Hey @leejustin 

could you try to wrap each flow with its own ReactFlowProvider?

**Comment by leejustin** [comment]
In the example above, I had `ReactFlowProvider` wrapping all of the routes in my React router routes file. 

I've also tried wrapping with `ReactFlowProvider` inside of the component itself as shown below:
```
<ReactFlowProvider>
  <ReactFlow
        elements={elements}
  >
  </ReactFlow>
<ReactFlowProvider>
```

Both of these seem to have the same issue.

**Comment by moklick** [comment]
When you are working with react router it is important to wrap each flow with a provider. It is strange that it doesn't work here. We had similar issues on the docs website but the provider fixed it for us. Could you create a simplified codesandbox or repo so we could investigate this?

**Comment by leejustin** [comment]
Thanks for the response.I'll take a little bit of time to rule out any mistakes on my end first to make sure I'm not wasting your time. Else, I'll put together a runnable, simplified version of my application for troubleshooting thought it will take a little bit of time.

**Comment by jakespeare** [comment]
@leejustin I had the same trouble with the layout example, what helped me was changing the scope of the dagreGraph instance to be inside my "FlowContainer" component, so that it is instantiated when the FlowContainer is mounted.
```
const dagreGraph = new dagre.graphlib.Graph();
dagreGraph.setDefaultEdgeLabel(() => ({}));

```
So dagreGraph calculates where the nodes should be based on the nodes it has in its graph, and reactFlow shows you the graph with only the elements you gave it

**Comment by leejustin** [comment]
@jakespeare this is it! Really appreciate you pointing this out. I updated my code so that `dagreGraph` is initialized when the component mounts. This would have taken me so much more time to figure out 😄
