### ISSUE TITLE
Fix self-connected node not rendering an edge

### ISSUE THREAD

**Issue by jmcauhy** [wbkd/react-flow#861]
When connecting a node source to it's self target the edge is not rendered and we get this warning from `ReacFlow.esm.js` file on `var Edge`:

`if (!targetNode) {
        console.warn("couldn't create edge for target id: " + edge.target + "; edge id: " + edge.id);
        return null;
 }`

Suggestion that fixes this:

/ReactFlow.esm.js line 8492
`
var getSourceTargetNodes = function (edge, nodes) {
    return nodes.reduce(function (res, node) {
        if (node.id === edge.source) {
            res.sourceNode = node;
        }
        else if (node.id === edge.target) {
            res.targetNode = node;
        }
        return res;
    }, { sourceNode: null, targetNode: null });
};
`

By my testings, this issue is solved by removing the `else` on `else if (node.id === edge.target)`

**Comment by moklick** [comment]
Hey!

Can you update to the latest version 8.7.0? This issue is already fixed.
