### ISSUE TITLE
Are there examples using typescript?

### ISSUE THREAD

**Issue by choksz** [wbkd/react-flow#873]
Hi I've read the examples but unfortunately all of them is using javascript.
I tried to convert the code to typescript but it is giving me errors like this:

![image](https://user-images.githubusercontent.com/9478451/106524396-7b2dfb00-651d-11eb-84b8-01932eb75397.png)

**Comment by mumairofficial** [comment]
@choksz I am using react-flow with typescript and typescript errors are cryptic to understand most of the time.

So, what I have understood from this error is you are using the `string` type for the position prop. You should do the following instead.

```tsx
import { Position } from "react-flow-renderer";

// somewhere in your code
<Handle position={Position.Bottom} />
```

**Comment by moklick** [comment]
Thanks for your help @mumairofficial 

I also created a TS codesandbox template https://codesandbox.io/s/react-flow-starter-typescript-j8lkh
