### ISSUE TITLE
Typescript: Types for useActions hook

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#874]
Hey!

We want to switch from easy-peasy to redux in order to reduce bundle size (amongst other things). We are working on the `refactor/redux` branch and it is looking all good but we have some issues with the correct types here:

Can someone help us with this:

```ts 
export function useActions(actionSelector: (value: any) => any): any {
  const dispatch: ReactFlowDispatch = reduxUseDispatch();

  const action = useMemo(() => {
    // the actions variable is an object with all actions 
    const currAction: any = actionSelector(actions);
    return bindActionCreators(currAction, dispatch);
  }, [dispatch, actionSelector]);

  return action;
}
```
You can find the code here: https://github.com/wbkd/react-flow/blob/refactor/redux/src/store/hooks.ts#L17-L26

We want to use the hook like this but we are not sure which types we should use for the `actionSelector` function and the return type of the hook:

```js
// at this point TS should know which params we can pass to the "someAction" action
const someAction = useActions(actions => actions.someAction);
```

Thanks for your help.

**Comment by alexkuz** [comment]
I'll point out two things:
1. `useMemo` is kinda useless here, since `actionSelector` will probably be recreated with every call.
2. I would suggest not overthinking it with redundant wrappers and just call dispatch directly, so instead of
```js
const updateNodePosDiff = useStoreActions((actions) => actions.updateNodePosDiff);
...
updateNodePosDiff({
  isDragging: false,
});
```
use
```js
const dispatch = useDispatch();
...
dispatch(updateNodePosDiff({
  isDragging: false,
}));
```

**Comment by moklick** [comment]
Hey,

1. It is possible to define the selectors outside of the component so that the function gets re-used.
2. I would like to use `useDispatch` but this would be a major change for the react-flow API. Unfortunately people are using the internal actions (because we are exporting them and mention them in the docs :/). When we are OK with a breaking change we could also consider to use a library like recoil or use-context-selector.

**Comment by alexkuz** [comment]
1. True, but I can't see it defined that way anywhere in the code (or docs), so there's high chance no one would actually use that :) You could memoize with `currAction` instead, though - but I still not sure if it's really necessary.
2. Ah, didn't realize it's exported. It's a bit trickier then, yeah.

**Comment by alexkuz** [comment]
So anyway, the TS definition could look like this:

```ts
type ActionCreatorSelector<Action> = (acts: typeof actions) => ActionCreator<Action>;
type ActionMapObjectSelector<Action> = (acts: typeof actions) => ActionCreatorsMapObject<Action>;
type ActionSelector<Action> = (acts: typeof actions) =>
  | ActionCreatorsMapObject<Action>
  | ActionCreator<Action>;

// these overrides are in case you want to support both single action and map object of actions
// if not, you can get rid of these and just use ActionCreatorSelector type
export function useActions<Action extends ReactFlowAction>(actionSelector: ActionCreatorSelector<Action>): ActionCreator<Action>;
export function useActions<Action extends ReactFlowAction>(actionSelector: ActionMapObjectSelector<Action>): ActionCreatorsMapObject<Action>;

export function useActions<Action extends ReactFlowAction>(actionSelector: ActionSelector<Action>) {
  const dispatch: ReactFlowDispatch = reduxUseDispatch();

  // the memoization here makes sense only for ActionSelector actually, not so much for ActionMapObjectSelector
  const currAction = actionSelector(actions);

  const action = useMemo(() => {
    // this looks weird but required if both ActionSelector and ActionMapObjectSelector are supported
    return typeof currAction === 'function'
      ? bindActionCreators(currAction, dispatch)
      : bindActionCreators(currAction, dispatch);
  }, [dispatch, currAction]);

  return action;
}
```

**Comment by moklick** [comment]
Thanks a lot @alexkuz :) This looks pretty good. I think it was the last missing piece in the refactor/redux branch. Without immer we are hopefully more flexible to do some performance improvements inside the redux actions/ reducers. The version is also about 10kb smaller.
