### ISSUE TITLE
 How to add a "custom control" Edge? 

### ISSUE THREAD

**Issue by mwei2018** [wbkd/react-flow#887]
![image](https://user-images.githubusercontent.com/2967082/107204675-e7d25980-6a37-11eb-8cd0-778055bf2a5d.png)
![image](https://user-images.githubusercontent.com/2967082/107205008-54e5ef00-6a38-11eb-9314-55b2e283d65a.png)

I want to have one single custom control(eg:icon/button) for all edges, just like the picture. What would be the best way to achieve this?

**Comment by moklick** [comment]
Hey @mwei2018 

you need to implement a custom edge (example: https://reactflow.dev/examples/edges/, docs: https://reactflow.dev/docs/api/edge-types/). For implementing the edge and finding the edge center you can use the edge utils https://reactflow.dev/docs/api/edge-utils/ .

**Comment by rawars** [comment]
Hello! @moklick, could you guide me how I can add a custom button? is that I am adding the button in a custom border but it does not appear in the interface, I need the button in the center of the border with a trash can icon to allow deleting the border.

Thank you very much and great bookstore.

**Comment by ilanskogan** [comment]
@moklick im with @rawars , cant seem to implement a custom element on top of the edge, it seems like only a simple label is possilble

**Comment by chenhui996** [comment]
@moklick im with @rawars , cant implement a custom element on top of the edge, it seems like only a simple label is possilble

**Comment by rawars** [comment]
@chenhui996 @ @ilanskogan I could have had to do it with svg, I managed to apply it to the node and edge, I had to do it with svg and path elements because with html I couldn't render it, if you need help I can pass you the custom node component.

This is the component for the custom node:
`
import React, { memo, useRef, useEffect, useState, useContext } from 'react';

import { Handle } from 'react-flow-renderer';

import { ReactComponent as FlowIcon } from '../../../Assets/flow.svg';

export default memo((payload) => {

    const el = useRef(null);

    const [HandleNo, setHandleNo] = useState(100);

    const [HandleYes, setHandleYes] = useState(70);

    return (
        <>

            <button style={{
                background: "#D04881",
                border: "0px",
                width: "35px",
                height: "35px",
                borderRadius: "50%",
                paddingTop: "5px",
                cursor: "pointer"
            }}>

                <svg version="1.1" width="18px" height="18px" viewBox="0 0 330 330" >
                    <path fill="#fff" d="M240,121.076V90h15c8.284,0,15-6.716,15-15s-6.716-15-15-15h-30h-15V15c0-8.284-6.716-15-15-15H75c-8.284,0-15,6.716-15,15
            v45H45H15C6.716,60,0,66.716,0,75s6.716,15,15,15h15v185c0,8.284,6.716,15,15,15h60h37.596c19.246,24.347,49.031,40,82.404,40
            c57.897,0,105-47.103,105-105C330,172.195,290.817,128.377,240,121.076z M210,121.076c-10.588,1.521-20.671,4.625-30,9.069V90h15
            h15V121.076z M90,30h90v30h-15h-60H90V30z M60,90h15h15v170H60V90z M120,260v-35V90h30v61.596c-18.546,18.946-30,44.86-30,73.404
            c0,12.268,2.122,24.047,6.006,35H120z M225,300c-41.355,0-75-33.645-75-75s33.645-75,75-75s75,33.645,75,75S266.355,300,225,300z"
                    />

                    <path fill="#fff" d="M256.819,193.181c-5.857-5.857-15.355-5.857-21.213,0L225,203.787l-10.606-10.606c-5.857-5.857-15.355-5.857-21.213,0
            c-5.858,5.857-5.858,15.355,0,21.213L203.787,225l-10.606,10.606c-5.858,5.857-5.858,15.355,0,21.213
            c2.929,2.929,6.768,4.394,10.606,4.394s7.678-1.465,10.606-4.394L225,246.213l10.606,10.606c2.929,2.929,6.768,4.394,10.606,4.394
            s7.678-1.465,10.606-4.394c5.858-5.857,5.858-15.355,0-21.213L246.213,225l10.606-10.606
            C262.678,208.536,262.678,199.038,256.819,193.181z"/>

                </svg>


            </button>

            <div className="block" style={{
                border: "2px solid #fff",
                padding: "2px",
                borderRadius: "7px",
                maxWidth: "300px",
                minWidth: "200px",
                background: "#fff"
            }} onClick={
                () => {

                }
            }>
                <Handle
                    type="target"
                    position="left"
                    style={{
                        left: "-8px",
                        width: "15px",
                        height: "15px",
                        background: '#000',
                        border: "2px solid #fff"
                    }}
                    onConnect={(connection) => {

                    }}
                />
                <div>
                    <div style={{
                        color: "#38405f",
                        fontWeight: "700",
                        padding: "10px",
                        display: "flex",
                        alignItems: "center"
                    }}>
                        <div>
                            <FlowIcon style={{
                                width: "25px",
                                height: "25px",
                                fill: "#435369"
                            }} />
                        </div>
                        <div style={{
                            marginLeft: "10px"
                        }}>Nombre del nodo</div>
                    </div>
                    <div ref={el} style={{
                        background: "#fff",
                        padding: "10px",
                        color: "#fff"
                    }}>
                        <div>
                            Contenido del nodo
                        </div>
                    </div>
                </div>

                <Handle
                    type="source"
                    position="right"
                    id="a"
                    style={{
                        top: HandleYes,
                        right: -8,
                        width: "15px",
                        height: "15px",
                        background: '#3CCFA0',
                        border: "2px solid #fff"
                    }}
                    onConnect={(connection) => {


                    }}
                />

                <Handle
                    type="source"
                    position="right"
                    id="b"
                    style={{
                        top: HandleNo,
                        right: -8,
                        width: "15px",
                        height: "15px",
                        background: '#d04881',
                        border: "2px solid #fff"
                    }}
                    onConnect={(connection) => {

                    }}
                />

            </div>

        </>

    );
});
`
This is the code for a custom edge:

`
import React, { useRef, useEffect, useState, useContext } from 'react';

import { getMarkerEnd, getSmoothStepPath, getBezierPath, getEdgeCenter, removeElements } from 'react-flow-renderer';

export default function CustomEdge({
    id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    style = {},
    data,
    arrowHeadType,
    markerEndId,
    borderRadius = 5,
}) {

    const edgePath = getBezierPath({ sourceX, sourceY, sourcePosition, targetX, targetY, targetPosition });

    const markerEnd = getMarkerEnd(arrowHeadType, markerEndId);

    const [Ratio, setRatio] = useState(15);

    const [centerX, centerY] = getEdgeCenter({ sourceX, sourceY, targetX, targetY });

    return (
        <>
            <g>
                <path id={id} style={{ ...style, stroke: "#BBC7D5" }} className="react-flow__edge-path" d={edgePath} markerEnd={markerEnd} />

                <g onMouseEnter={
                    () => {
                        setRatio(20)
                    }
                } onMouseLeave={
                    () => {
                        setRatio(15)
                    }
                } width={20} style={{
                    width: 20
                }}>
                    <circle fill="#D04881" style={{
                        cursor: "pointer"
                    }} className="avoid-clicks" cx={centerX} cy={centerY} onMouseEnter={
                        () => {
                            setRatio(20)
                        }
                    } r={Ratio} />
                    <svg version="1.1" width="20px" height="20px" x={(centerX - 10) + "px"} y={(centerY - 10) + "px"}
                        viewBox="0 0 330 330" >
                        <path fill="#fff" d="M240,121.076V90h15c8.284,0,15-6.716,15-15s-6.716-15-15-15h-30h-15V15c0-8.284-6.716-15-15-15H75c-8.284,0-15,6.716-15,15
		v45H45H15C6.716,60,0,66.716,0,75s6.716,15,15,15h15v185c0,8.284,6.716,15,15,15h60h37.596c19.246,24.347,49.031,40,82.404,40
		c57.897,0,105-47.103,105-105C330,172.195,290.817,128.377,240,121.076z M210,121.076c-10.588,1.521-20.671,4.625-30,9.069V90h15
		h15V121.076z M90,30h90v30h-15h-60H90V30z M60,90h15h15v170H60V90z M120,260v-35V90h30v61.596c-18.546,18.946-30,44.86-30,73.404
		c0,12.268,2.122,24.047,6.006,35H120z M225,300c-41.355,0-75-33.645-75-75s33.645-75,75-75s75,33.645,75,75S266.355,300,225,300z"
                        />
                        <path fill="#fff" d="M256.819,193.181c-5.857-5.857-15.355-5.857-21.213,0L225,203.787l-10.606-10.606c-5.857-5.857-15.355-5.857-21.213,0
		c-5.858,5.857-5.858,15.355,0,21.213L203.787,225l-10.606,10.606c-5.858,5.857-5.858,15.355,0,21.213
		c2.929,2.929,6.768,4.394,10.606,4.394s7.678-1.465,10.606-4.394L225,246.213l10.606,10.606c2.929,2.929,6.768,4.394,10.606,4.394
		s7.678-1.465,10.606-4.394c5.858-5.857,5.858-15.355,0-21.213L246.213,225l10.606-10.606
		C262.678,208.536,262.678,199.038,256.819,193.181z"/>
                    </svg>
                </g>
            </g>
        </>
    );
}
`

I hope and it is helpful to you.

**Comment by moklick** [comment]
I just added an example "Edge With Button" https://reactflow.dev/examples/edge-with-button

**Comment by mwei2018** [comment]
It seems that this feature is relatively common, and I have implemented it before. Today I am very happy to see the author made a demo, but I still have a troublesome problem. If the node dynamically changes the content, the height of the node becomes higher, but the position of the button in the middle of the line will not be centered in the future.
![image](https://user-images.githubusercontent.com/2967082/122529827-755e2f80-d050-11eb-9d0a-21acff83af61.png)

**Comment by depveloper** [comment]
> I just added an example "Edge With Button" https://reactflow.dev/examples/edge-with-button

How I can remove the edge when i click the button edge in the example ?

thx  a lot

**Comment by ilanskogan** [comment]
> > I just added an example "Edge With Button" https://reactflow.dev/examples/edge-with-button
> 
> How I can remove the edge when i click the button edge in the example ?
> 
> thx a lot

you should probably just run a .filter() on the nodes array to remove the edge clicked on. you do have the edge id on the onClick callback you pass for the edge

**Comment by dxtri94** [comment]
> > > I just added an example "Edge With Button" https://reactflow.dev/examples/edge-with-button
> > 
> > 
> > How I can remove the edge when i click the button edge in the example ?
> > thx a lot
> 
> you should probably just run a .filter() on the nodes array to remove the edge clicked on. you do have the edge id on the onClick callback you pass for the edge

hi @ilanskogan , can you explain more ? How can i pass all elements to custom edge that i can filter? , and back "New Elements" after removed to ReactFlow component ? 
Thank you so much

**Comment by MrRainesE** [comment]
@ilanskogan  can you explain more? or do you have a working example?

> > > I just added an example "Edge With Button" https://reactflow.dev/examples/edge-with-button
> > 
> > 
> > How I can remove the edge when i click the button edge in the example ?
> > thx a lot
> 
> you should probably just run a .filter() on the nodes array to remove the edge clicked on. you do have the edge id on the onClick callback you pass for the edge

**Comment by corpulent** [comment]
@moklick I tried to get this example working https://reactflow.dev/examples/edge-with-button and the button is always off.  Your example is also missing the index.css,  so I think there might be something in there that I am missing.  Also, my nodes are different heights.  I am trying to not use jsplumb in my new project.  I just need an arrow to indicate where the edge is going.

**Comment by benobab** [comment]
How to communicate from a node to the parent container?
In your example, you're calling a popup, you're not at all deleting the edge. Should we pass a method or fire a redux event?

Please make your example working, thanks a lot!

**Comment by benobab** [comment]
@mwei2018 how di you manage to update your elements from the button on the edge? Thanks for your help.

**Comment by sahitha-desilva** [comment]
any update on this?

**Comment by wardoost** [comment]
> How to communicate from a node to the parent container? In your example, you're calling a popup, you're not at all deleting the edge. Should we pass a method or fire a redux event?

@benobab I use React Context to pass through data or event dispatchers to custom edges or nodes. If you're using Redux you could probably use [useDispatch](https://react-redux.js.org/api/hooks#usedispatch).

**Comment by moklick** [comment]
I wrote a guide on how to use React Flow with a state management library. This should help you to get started: https://reactflow.dev/docs/guides/state-management/
