### ISSUE TITLE
Internal state management doesn't seem to leverage React key

### ISSUE THREAD

**Issue by Zeroster** [wbkd/react-flow#888]
I'm trying to use a [key](https://reactjs.org/docs/lists-and-keys.html#keys) on the react flow component to separate instances by resetting component state. Changing a key doesn't seem to fully reset the state in react flow. When the onLoad handler is specified, it fires when the key changes but the internal state of react flow doesn't seem to have been cleared.

For example, calling fitView() in onLoad works as expected but nodes that were previously moved retain their previous positions with the new instance. The previous zoom state is also carried over: zoom into a node, change the key, triggers fitView() and then trying to zoom doesn't work as expected (it uses the previous zoom level as the starting point).

I would expect all the internal state to be cleared when the key is changed. I wonder if this would affect having multiple instances of react flow on a page.

code sandbox: https://codesandbox.io/s/blue-lake-g4hf1?file=/src/App.js

```javascript
import React, { useState } from "react";
import ReactFlow from "react-flow-renderer";

const elements = [
  { id: "1", data: { label: "Node 1" }, position: { x: 250, y: 5 } },
  // you can also pass a React component as a label
  { id: "2", data: { label: <div>Node 2</div> }, position: { x: 100, y: 100 } },
  { id: "e1-2", source: "1", target: "2", animated: true }
];

const onLoad = (reactFlowInstance) => {
  reactFlowInstance.fitView();
};

export default function App() {
  const [key, setKey] = useState(0);

  return (
    <div style={{ width: "1000px", height: "800px", background: "lightgray" }}>
      <div>Key is {key}</div>
      <button onClick={() => setKey(Date.now())}>Change key</button>
      <ReactFlow key={key} onLoad={onLoad} elements={elements} />
    </div>
  );
}
```

**Comment by moklick** [comment]
As a workaround you can wrap the flow with the `ReactFlowProvider`. This should work:

```jsx
...
<ReactFlowProvider key={key}>
  <ReactFlow onLoad={onLoad} elements={elements} />
</ReactFlowProvider>
...
```

We will try to solve this. Thanks for the hint.

**Comment by Zeroster** [comment]
Thanks! The workaround seems to be working as expected.
