### ISSUE TITLE
Need help understanding how onElementsRemove works

### ISSUE THREAD

**Issue by lnguyen11h** [wbkd/react-flow#890]
```jsx
/**
 * Example for checking the different edge types and source and target positions
 */
import React, { useState } from 'react';

import ReactFlow, { removeElements, addEdge, MiniMap, Controls, Background } from 'react-flow-renderer';
import { getElements } from './utils';

const onLoad = (reactFlowInstance) => {
  reactFlowInstance.fitView();
  console.log(reactFlowInstance.getElements());
};

const initialElements = getElements();

const EdgeTypesFlow = () => {
  const [elements, setElements] = useState(initialElements);
  const onElementsRemove = (elementsToRemove) => setElements((els) => removeElements(elementsToRemove, els));
  const onConnect = (params) => setElements((els) => addEdge(params, els));

  return (
    <ReactFlow
      elements={elements}
      onLoad={onLoad}
      onElementsRemove={onElementsRemove}
      onConnect={onConnect}
      minZoom={0.2}
    >
      <MiniMap />
      <Controls />
      <Background />
    </ReactFlow>
  );
};

export default EdgeTypesFlow;
```

I'm having a hard time understanding this particular line:

`  const onElementsRemove = (elementsToRemove) => setElements((els) => removeElements(elementsToRemove, els));
`

I understand that we call **removeElements** to remove the **elementsToRemove** from the collection of all elements **els**. I see that **elementsToRemove** get passed in as a parameter. However, I don't understand how **els** get populated or get its value.

**Comment by moklick** [comment]
Hey @lnguyen11h

this has nothing to do with react-flow but with react in general. `useState` returns a value and function to update that value. You can pass a value or a function to the update function. You can find more information about it in the react docs https://reactjs.org/docs/hooks-reference.html#functional-updates
