### ISSUE TITLE
Question: Possibility of auto generating position of nodes

### ISSUE THREAD

**Issue by AshwinTayson** [wbkd/react-flow#892]
I went through the documentation. Not sure whether this is already available. But is it possible to add nodes dynamically and generate the position automatically?

**Comment by moklick** [comment]
You can add nodes dynamically by populating the elements array. We have a layouting example on the website: https://reactflow.dev/examples/layouting/

**Comment by AshwinTayson** [comment]
Ya just saw this. Thanks
