### ISSUE TITLE
Edge not proper when sourcePosition is marked as "left" and the other node is on bottom left of the node

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#893]
[{
                id: "3",
                data: {
                  label: (
                    <div>
                      Node A
                    </div>
                  ),
                },
                position: { x: 500, y: 300 },
                targetPosition: "right" as any,
                sourcePosition: "left" as any,
              },
{
                id: "5",
                data: {
                  label: (
                    <div>Node B</div>
                  ),
                },
                position: { x: 250, y: 370 },
              },
              {
                id: "e3-5",
                source: "3",
                target: "5",
                type: "smoothstep",
                style: { stroke: "#A1AAB2" },
                arrowHeadType: "arrowclosed" as ArrowHeadType,
 }]
  
  Expected: 
<img width="360" alt="Screenshot 2021-02-11 at 11 52 12 PM" src="https://user-images.githubusercontent.com/22545835/107680688-3562f680-6cc4-11eb-9c6e-bc9e8f8ff3a3.png">

Actual: 
<img width="375" alt="Screenshot 2021-02-11 at 11 51 57 PM" src="https://user-images.githubusercontent.com/22545835/107680716-3eec5e80-6cc4-11eb-9524-7ebef089b04f.png">

**Comment by vraja-nayaka** [comment]
Same issue with getSmoothStepPath for left and right positions
GetSmoothStepPath behaves differently depending on (source.x < target.x)

Not nice:
![not nice for left and right](https://user-images.githubusercontent.com/52737608/112730749-52861880-8f44-11eb-93c8-1e07fe5acf74.gif)

Expected: Behavior does not change depending on source.x and target.x  

All other cases (for example top and bottom positions or getBezierPath) have a nice behavior:

Nice:
![nice for top and bottom](https://user-images.githubusercontent.com/52737608/112731085-4bf8a080-8f46-11eb-9ee3-44dbd85a6425.gif)

**Comment by moklick** [comment]
This is fixed with v11.
