### ISSUE TITLE
Add support for drag handle

### ISSUE THREAD

**Issue by obaid** [wbkd/react-flow#906]
The library `react-draggable` does support custom drag handle for each node. See https://github.com/STRML/react-draggable#draggablecore for more details.

There should be a way to pass this info for each node in react-flow as well.

**Comment by moklick** [comment]
Hey @obaid 

can you explain what you want to do? Do you want to pass the `handle` prop to a node?

**Comment by obaid** [comment]
Yes, I want to define my own drag handle for each node.

**Comment by moklick** [comment]
You can only define areas that should not work as a handler. You can do that by adding the class name `nodrag` to an element. Let me know if it works for you.

**Comment by obaid** [comment]
Thanks @moklick. That helped.
