### ISSUE TITLE
paneMoveable isn't working when elementsSelectable is true(default)

### ISSUE THREAD

**Issue by maciag-dev** [wbkd/react-flow#908]
Hi,

I've set paneMoveable to true in the ReactFlow component, but I'm not able to drag/move the tree selecting a node. Draging the tree is working only clicking background. Is there any other possibility to do this selecting a node?

Props setup:

```    
<ReactFlow
     onLoad={onLoad}
     elements={treeData}
     nodeTypes={nodeTypes}
     edgeTypes={edgeType}
     nodesConnectable={false}
     nodesDraggable={false}
>
```

Thanks in advance!

**Comment by moklick** [comment]
hey @maciag-dev 

it seems that you set `nodesDraggable=false`. If that's the case, you can't drag nodes.

**Comment by maciag-dev** [comment]
hey @moklick 

thanks for the fast response.

I don't want to drag a selected node. Thats why is `nodesDraggable=false`. I want to move the whole diagram clicking on a node.

**Comment by moklick** [comment]
This is an interesting use case. I am not sure if it is possible right now. You can select all nodes on click programmatically (as we do it in [this example](https://reactflow.dev/examples/provider/)) but a node needs to be draggable if you want to move the graph.

**Comment by maciag-dev** [comment]
Currently i can move the diagram clicking on a background and dragging. As you can see in the video below, clicking on a node the mouse cursor changes to the drag mode (hand icon), but the diagram does not move. I would be awesome to have this use case. Would it take a lot of effort to add that?


https://user-images.githubusercontent.com/62408263/108381535-2fab6a80-7208-11eb-85b9-850a09a48f41.mov

**Comment by moklick** [comment]
This should work:

1. set `nodesDraggable=true` when the user hovers a node
2. select all nodes programatically with `setSelectedElements`
3. set `nodesDraggable=false` after the mouse leaves the node
