### ISSUE TITLE
Can't double click to select all text on text input

### ISSUE THREAD

**Issue by 001123** [wbkd/react-flow#909]
I'm having an issue with input field in the builder **can't double click to select all text**, only Ctrl + A work. 😕 
Anybody know how to fix this?

Version use: ^8.8.0
Browser: Chrome 89, Windows 10

![image](https://user-images.githubusercontent.com/32441266/108168374-c6552a00-7129-11eb-8ff0-787b6ba30c6c.png)

Thanks for read.

**Comment by moklick** [comment]
Try to add the class `nodrag` to the input.

**Comment by 001123** [comment]
Wow, It worked 🎉 

Many thank 😄.

**Comment by moklick** [comment]
I think we need better documentation for this ;) May a "FAQ" or "Known Issues" section would be helpful
