### ISSUE TITLE
Image Node Drag and Drop issue

### ISSUE THREAD

**Issue by Tush2890** [wbkd/react-flow#911]
When I drag my image node which looks like below :-
```
  const newNode = {
                id: getId(),
                type: 'img',
                position,
                data: { label: <div><img src={imgSrc} /></div> }
    };
```
Sometimes, I see a snapshot of an image that is being dragged and sometimes I see the actual node is getting dragged. The issue is with the former case. 

**Issue** - The actual node remains at the same position while the snapshot becomes the draggable item. When I release the item at different position, I don't see the actual node gets dropped at new position. Now if I move my cursor a bit, then actual node becomes the draggable item and then I am able to put it successfully wherever I want to. 

**Unfortunately, I am unable to show the recording here because when I start the recording, I am unable to drag the node. This might be another issue with the library which I am totally unsure about.**

I am on Mac using chrome.

**Comment by moklick** [comment]
The ids must be strings. If the issue still occurs please create a codesandbox so that we can have a look.

**Comment by Tush2890** [comment]
@moklick Thank you for your response :-)

The ids are in strings only. 

As asked, I have created the demo on `codesandbox` [https://codesandbox.io/s/busy-ishizaka-suj71?file=/src/App.js](url).
The issue can be clearly seen here as well that whenever I drag the image, the actual node does not get dragged rather the snapshot of it. When I release my cursor, I don't see the node getting dropped to new position. Now, if I move my cursor a bit, I will start seeing the actual node being dragged with my cursor and now I can put it wherever I want to.

Please let me know if you need more details.

**Comment by moklick** [comment]
I never added an image to a node. I think you need to prevent the default browser behaviour with `pointer-events: none` for the image.

**Comment by Tush2890** [comment]
Perfect! Thank you so much.
