### ISSUE TITLE
How to change the color of the markerEnd in a custom Edge?

### ISSUE THREAD

**Issue by JulienDemarque** [wbkd/react-flow#915]
using style={{stroke:  'blue'}} on the path works to change the color of the path but not the edge...

**Comment by moklick** [comment]
The option `arrowHeadColor` should work here  https://reactflow.dev/docs/api/component-props/

**Comment by JulienDemarque** [comment]
@moklick Thanks but I am trying to get a different color for different custom edges, this seems to set it for all edges.

**Comment by ambroseus** [comment]
@JulienDemarque  https://stackoverflow.com/questions/16664584/changing-an-svg-markers-color-css

**Comment by ambroseus** [comment]
possible solution:
1. create different custom markers
https://gist.github.com/ambroseus/2f1ea898f39e8460e49cd80c9b5e9f5c
![Selection_002](https://user-images.githubusercontent.com/380645/108588125-3947e600-7360-11eb-91ea-12c3b2048e55.png)

2. implement custom edges with different markers selected  by edge type
https://github.com/wbkd/react-flow/blob/main/example/src/Edges/CustomEdge.js

**Comment by MetaMmodern** [comment]
Hello @ambroseus, the link that you've shared doesn't work anymore. I checked the docs for customEdge [here](https://reactflow.dev/examples/edges/custom-edges). I'm trying to color the edges in my custom edges based on label and I wanted this logic to be embedded into CustomEdge itself. Is there a way to do that?

CC @moklick

**Comment by ambroseus** [comment]
> Hello @ambroseus, the link that you've shared doesn't work anymore. I checked the docs for customEdge [here](https://reactflow.dev/examples/edges/custom-edges). I'm trying to color the edges in my custom edges based on label and I wanted this logic to be embedded into CustomEdge itself. Is there a way to do that?
> 
> CC @moklick 

Hi :) there have been a lot of changes since my contribution to the project 4 years ago...
guess now it should be easier to customize edges (as i see in examples)
