### ISSUE TITLE
How to get the dynamic position of the mouse moving in the node

### ISSUE THREAD

**Issue by mwei2018** [wbkd/react-flow#928]
I want tootip to follow the mouse when the mouse moves in node. 
But the client position obtained through the mouse is not really the position in the node.
How to deal with it?
![image](https://user-images.githubusercontent.com/2967082/108677901-4a8e1f80-7525-11eb-9068-0e3768ab4340.png)

mouse  position 
![image](https://user-images.githubusercontent.com/2967082/108677260-6218d880-7524-11eb-9606-10dd9e16bc24.png)
I check the source code and found that there is no event of mouse movement on node
my code:
![image](https://user-images.githubusercontent.com/2967082/108677358-870d4b80-7524-11eb-8b99-21e4cd1c33d7.png)
![image](https://user-images.githubusercontent.com/2967082/108677417-9c827580-7524-11eb-860a-c293dc854fdd.png)
![image](https://user-images.githubusercontent.com/2967082/108677465-af954580-7524-11eb-81e0-1552a2ec56f1.png)

**Comment by moklick** [comment]
Hey @mwei2018 

I would use `onMouseEnter` for activating the tooltip, `onMouseMove` for setting the position and `onMouseLeave` for hiding it. You can add the event handlers on the wrapper of your custom node. 

When you are working with `e.clientX` and `e.clientY` you always need to subtract the parent offset (in your case the node itself). Something like this:

```js 
const nodeBounds = customNodeRef.current.getBoundingClientRect();
const tooltipPosition = {
  x: e.clientX - nodeBounds.x,
  y: e.clientY - nodeBounds.y
};
```

**Comment by mwei2018** [comment]
Thank you very much for your reply and guidance.
