### ISSUE TITLE
Node dragged on resize event

### ISSUE THREAD

**Issue by clement-faure** [wbkd/react-flow#929]
I'm trying to use react-resizable inside a custom node.

**The issue is that resize event trigger drag event.**

All works fine when **draggable** property is set to **false** in my node but i would like to be able to drag it and resize it all the time.

---

Uploading Enregistrement de l’écran 2021-02-22 à 09.47.40.mov…

--- 
 "react-flow-renderer": "^9.0.1"

**Comment by moklick** [comment]
Can you try to add the class `nodrag` to your resizable element?

**Comment by clement-faure** [comment]
Thank you so much for the quick response, i was missing this part.

**Comment by clement-faure** [comment]
Have a good day :)
