### ISSUE TITLE
Limit number of connections to a Handle

### ISSUE THREAD

**Issue by xdevapps** [wbkd/react-flow#930]
I have made custom nodes and I want to limit the number of connections at target handles to 1. I can't seem to find a way to do that. Any help will be appreciated.

Thanks for the great project!

**Comment by moklick** [comment]
You can check within the `onConnect` function if there is already a connection or you can use the `isValidConnection` of a handle for that.

**Comment by xdevapps** [comment]
Can you please explaing how I can get the existing connections at the particular handle? Do I have to iterate through the edges?

**Comment by moklick** [comment]
Yes. That is the way.

**Comment by xdevapps** [comment]
Thank you @moklick. This was very helpful.
