### ISSUE TITLE
Babel runtime dependency will crash node (esm modules)

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#934]
## Issue

Running tests without any transpilation with nodejs will lead to issues with `react-flow v9+`. This wasn't the case before.

## Reproduce

Repository with steps how to reproduce this issue:
https://github.com/andys8/react-flow-node-issue-example

## Error

```
internal/modules/cjs/loader.js:1092
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/user/dev/repository/react-flow-node-issue-example/node_modules/@babel/runtime/helpers/esm/extends.js
require() of ES modules is not supported.
require() of /home/user/dev/repository/react-flow-node-issue-example/node_modules/@babel/runtime/helpers/esm/extends.js from /home/user/dev/repository/react-flow-node-issue-example/node_modules/react-flow-renderer/dist/ReactFlow.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename extends.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/user/dev/repository/react-flow-node-issue-example/node_modules/@babel/runtime/helpers/esm/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:13)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/dev/repository/react-flow-node-issue-example/node_modules/react-flow-renderer/dist/ReactFlow.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14) {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! Test failed.  See above for more details.
```

**Comment by andys8** [comment]
Based on this issue https://github.com/rollup/plugins/issues/381, this

https://github.com/wbkd/react-flow/blob/42019a6a6659b201beefb873d950db2983493fdf/rollup.config.js#L52

might be  a workaround. In that case, maybe `skipPreflightCheck: true` as suggested [in this comment](https://github.com/rollup/plugins/issues/381#issuecomment-627215009) could be an alternative.

I tested that both workarounds result in `react-flow` building, while it wouldn't without. I don't know if this change would resolve the initial issue, but it could very well do so.

**Comment by moklick** [comment]
Thanks for the report. Which node version are you using?

**Comment by andys8** [comment]
Latest lts (v14). See: https://github.com/andys8/react-flow-node-issue-example#versions

**Comment by moklick** [comment]
This is really strange. We haven't change the babel plugins or the rollup config. The problem is that these packages are required by the current production build:

```js 
require('@babel/runtime/helpers/esm/extends');
require('@babel/runtime/helpers/esm/objectWithoutPropertiesLoose');
```

In v8.8.0 the weren't. Maybe there is a new option for one of the babel or rollup plugins. I will try to fix it.

**Comment by moklick** [comment]
can you try v9.0.3?

**Comment by Codesleuth** [comment]
> can you try v9.0.3?

Fixed the issue for me. Thanks!

**Comment by andys8** [comment]
Awesome, the issue is fixed. Great work!

https://github.com/andys8/react-flow-node-issue-example/blob/master/README.md#update-issue-fixed
