### ISSUE TITLE
Feature: possibility to define custom edge updater shape

### ISSUE THREAD

**Issue by ambroseus** [wbkd/react-flow#936]
It will be helpful to have a possibility to define custom edge updater instead of default `circle`

 (for ex. not circle but fat ring with own radius or square with different dimensions)

```jsx
{handleEdgeUpdate && (
          <g
            onMouseDown={onEdgeUpdaterSourceMouseDown}
            onMouseEnter={onEdgeUpdaterMouseEnter}
            onMouseOut={onEdgeUpdaterMouseOut}
          >
            <circle
              className="react-flow__edgeupdater"
              cx={sourceX}
              cy={sourceY}
              r={10}
              stroke="transparent"
              fill="transparent"
            />
          </g>
        )}
```
```jsx
 {handleEdgeUpdate && (<EdgeUpdaterShape 
    onMouseDown={onEdgeUpdaterSourceMouseDown}
    onMouseEnter={onEdgeUpdaterMouseEnter}
    onMouseOut={onEdgeUpdaterMouseOut}
    cx={sourceX}
    cy={sourceY}
 />)}
```

**Comment by ambroseus** [comment]
@moklick  I'll prepare PR soon..

**Comment by ambroseus** [comment]
@moklick  at least this PR would be helpful ;) https://github.com/wbkd/react-flow/pull/946

**Comment by moklick** [comment]
can we close this issue or do you still need another shape for the updater?

**Comment by ambroseus** [comment]
@moklick  already no need :) maybe in the future.... so closing right now
btw, guess it would be useful to enable and use `Discussions` tab for features/questions instead of creating issues..
what do you think?

**Comment by moklick** [comment]
Good idea! See you there ;)
