### ISSUE TITLE
Size and position of edge label not changed on update

### ISSUE THREAD

**Issue by mi01** [wbkd/react-flow#939]
I'm writing a React application using this great library, where the user can change nearly every aspect of the graph, as well as the text of the labels. But when updating it, the size of the label background and the position of the label (centering) is not adjusted. I prepared a Codesandbox showing my approach and the problem [here](https://codesandbox.io/s/determined-wave-1ij8l). Would be great to know, if this is an real issue or i missed something here.

Version: current 9.0.2

**Comment by moklick** [comment]
Thanks for the report :) Can you check v9.0.4?

**Comment by mi01** [comment]
The fix seems to work. Thank you!
