### ISSUE TITLE
"Error: Must use import to load ES Module " when update to version 9.

### ISSUE THREAD

**Issue by 001123** [wbkd/react-flow#940]
Hi, I'm building a web app with nextjs after update version 8.8.0 to 9.0.2 got this error.
Anyone know why I got this.
many thanks.

![image](https://user-images.githubusercontent.com/32441266/109129020-b91be900-7782-11eb-9867-c404851c1f63.png)

OS: Windows 10
Node: v14.15.0

**Comment by moklick** [comment]
I will close this because we already have an issue for this #934

It seems that babel runtime is now required by the production build.. That is throwing the error.

**Comment by moklick** [comment]
can you check v9.0.3?
