### ISSUE TITLE
Edge Removal Improvements

### ISSUE THREAD

**Issue by loreggia** [wbkd/react-flow#943]
Greetings

I would like to propose two features that would arguably improve the UX of removing edges.
If I'm not missing something, the current possibilities of removing edges (without removing the connected nodes) are:

1. Select the edge and press the "deleteKeyCode" key
2. Use connectionMode="loose" and remove an edge when dragging it on itself

The problems I see with this:
(1.) implies that the user knows that there is a delete key and what key it is. Also it's not usable with touch input.
(2.) is kind of a workaround for the problem. My current use case requires strict mode, so I can't use this.
Both methods are not discoverable without explicit instructions.

My two propositions to improve this are as follows:
1. Add a new onEdgeContextMenu context menu handler for edges, similar to onNodeContextMenu/onPaneContextMenu. This would allow adding a context menu with an option to delete the edge.
2. Cause "onEdgeUpdate" to also fire when not targeting a handle.
For example, on mouse-up over the panel, onEdgeUpdate would fire and have either of the "newConnection.source" or "newConnection.target" parameter properties be null.
Since this seems like a breaking change, I would introduce a flag to enable this behaviour (sadly I can't think of a good name for this at the moment..).

I love the library so far, keep up the good work :)

**Comment by moklick** [comment]
Hey @loreggia 

thanks for your input. I added an `onEdgeContextMenu` handler and I will also think about the `onEdgeUpdate` change. We will release the new handler in the next days.

**Comment by loreggia** [comment]
Awesome, that will already help a ton!

**Comment by moklick** [comment]
The `onEdgeContextMenu` is available in 9.1.0
