### ISSUE TITLE
React Flow doesn't update position while dragging.

### ISSUE THREAD

**Issue by daljeetv** [wbkd/react-flow#947]
React-flow doesn't update the position of the node when it's being dragged. 
So when i finish dragging it and want to shift the position another time based on where i dragged it, I have to first set it's current position and then set it's new position.

**Comment by moklick** [comment]
Hey. Could you create a codesandbox or a repo so that we can have a look at the code?

**Comment by daljeetv** [comment]
Here you go:
https://codesandbox.io/s/small-sea-iykjf?file=/src/flowchart/FlowChart.tsx

To replicate issue:
- Drag two elements into the canvas, creating a parent child connection.
- Then move child closer to the parent. It should snap back to it's original position onNodeDragStop, but it doesn't.

To see workaround:
Search for: TO FIX: UNCOMMENT THIS BLOCK. 

Thank you!

**Comment by moklick** [comment]
This is indeed a problem with react-flow respectively the elements API. I would like to have controlled elements with an API like `onElementUpdate` that you would always need to call when an element changes. Right now your elements and the internal react-flow elements are out of sync. For the most cases this is not an issue but we will change this in the future. 

Right now you have two ways to get current node elements.

1. Use the `const nodes = useStoreState(state => state.nodes);`
2. Use the `const store = useStore();`And then `store.getState().nodes` inside your `onNodeDragStop` handler

**Comment by daljeetv** [comment]
This should then be mentioned in this example:

https://reactflow.dev/examples/update-node/

**Comment by moklick** [comment]
That's a good point. It would be helpful to add some descriptions to the examples.

**Comment by moklick** [comment]
I added a discussion here: https://github.com/wbkd/react-flow/discussions/960
