### ISSUE TITLE
Clickable Edge Label

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#948]
Hello, I'm trying to create a clickable label but I cant pass components as label, so I tried to create my custom edge

![image](https://user-images.githubusercontent.com/36650520/109434143-8d9f3580-79f2-11eb-9588-88ecb15f4b94.png)

The "clickable" works as expect but I need the same label format for it (with automatic orientation, background without the line inside)... What Can I do? Cuz I tried to create other components than text on custom edge but got no sucess on it

**Comment by CamboimGabriel** [comment]
I tried use EdgeText but I cant use onClick effect on it

```
 return (
    <>
      <path
        id={id}
        style={style}
        fill="none"
        className="react-flow__edge-path"
        d={edgePath}
        markerEnd={markerEnd}
      />
      <EdgeText
        onClick={hybridClick}
        x={center[0]}
        y={center[1]}
        label={data.text}
        labelStyle={labelStyle}
        labelShowBg={labelShowBg}
        labelBgStyle={labelBgStyle}
        labelBgPadding={labelBgPadding}
        labelBgBorderRadius={labelBgBorderRadius}
      />
    </>
  );
```

**Comment by CamboimGabriel** [comment]
Solved adding <g> </g> wrapping edgeText

**Comment by moklick** [comment]
With v9.1.0 you can pass all standard react HTML attributes like `onClick`, `className` and so on to the `EdgeText` component
