### ISSUE TITLE
Does React - Flow support multiple React Flow Windows on a page and have their own functionality?

### ISSUE THREAD

**Issue by v-cat** [wbkd/react-flow#957]
Does React - Flow support multiple React Flow Windows on a page and have their own functionality?

There's a need for that
You can open multiple TAB tabs to create multiple React Flow Windows showing different data。

**Comment by moklick** [comment]
Yes it's possible but you need to wrap each flow with the `ReactFlowProvider` component https://reactflow.dev/docs/api/components/provider/

**Comment by v-cat** [comment]
Thank you very much
