### ISSUE TITLE
Label in Smoothstep

### ISSUE THREAD

**Issue by obaid** [wbkd/react-flow#961]
The label in `smoothstep` is not positioned properly. This occurs if you have a path from left to top direction.

<img width="305" alt="Screen Shot 2021-03-02 at 12 16 17 PM" src="https://user-images.githubusercontent.com/12336/109687316-1e8c2300-7b51-11eb-8a5c-e45ef81bfce7.png">

**Comment by DovahBrownies** [comment]
Getting the same issue when connecting default nodes to custom nodes:
![image](https://user-images.githubusercontent.com/35106956/110774722-c945c500-8266-11eb-889e-85be1048fbb9.png)

Issue doesn't arise when connecting custom nodes to each other:
![image](https://user-images.githubusercontent.com/35106956/110774827-e37fa300-8266-11eb-92dd-f0b87ad54205.png)

Tried messing around with the custom nodes handles but nothing worked.

**Comment by moklick** [comment]
Hey! Could you check v9.4.0?

**Comment by denis-yasnitsky** [comment]
Yep, I have the same issue with an edge from the left to top handle. Upgrading to 9.4.2 didn't help.

**Comment by moklick** [comment]
hey @denis-yasnitsky thanks for the feedback here. Could you try 9.4.3? 

@obaid and @DovahBrownies could you check the label position for your cases with the latest version?

**Comment by denis-yasnitsky** [comment]
9.4.3 is close to perfection, but there is one little detail remains: line is not perpendicular to a box, seems like several degrees rotation clockwise:

![image](https://user-images.githubusercontent.com/36707844/113611355-12671a00-9657-11eb-8292-a4ec8b0d88a3.png)

**Comment by moklick** [comment]
@denis-yasnitsky thanks. Could you check 9.4.4?

**Comment by denis-yasnitsky** [comment]
Nailed it! Thanks a lot!
