### ISSUE TITLE
Node: Removeable

### ISSUE THREAD

**Issue by RickCraig** [wbkd/react-flow#965]
I have a node that I want to make permanent. I've written a small amendment to the basic `removeElements` function called from onElementsRemove. It looks something like this:

```js
const onElementsRemove = () => {
  // Some elements cannot be removed...
  const noRemove = ['email'];
  // Filter out any elements that cannot be removed
  const filtered = e.filter(el => !noRemove.some(nr => nr === el.type));
  // Remove valid elements from the state
  setElements(els => removeElements(filtered, els));
};
```
In this scenario, I don't want to remove any 'email' nodes (which I also have limited to 1). This works and stops the element from being removed, but the edge that I have attached to the a 'target' handle is removed automatically.

For reference, this isn't called on delete, and I don't have any other edge callbacks:
```js
const onEdgeUpdate = (old, newCon) => setElements(els => updateEdge(old, newCon, els));
```
Can anyone tell me what i'm doing wrong, maybe i've missed something, happy to take guidance?
Maybe you could add a `removable` prop to nodes, default true, when false stops the node from being removed?

Thanks, an amazing framework!

**Comment by moklick** [comment]
Hey @RickCraig

the problem is that `onElementsRemove` also returns the edges that are connected to the nodes. That means that you would need to filter them too. You can use the [`getConnectedEdges`](https://reactflow.dev/docs/api/helper-functions/) util function for that.

I haven't tested it but something like this:

```js
const edges = e.filter(isEdge);
const noRemoveNodes = e.filter(el => noRemove.some(nr => nr === el.type));
const noRemoveEdges =  getConnectedEdges(noRemoveNodes, edges);
const noRemoveElements = [...noRemoveNodes, ...noRemoveEdges];

const filtered = e.filter(el => !noRemoveElements.some(nr => nr.id === e.id));
```

Does it help?

**Comment by RickCraig** [comment]
Ah I get it! I knew it would be something simple that I missed. Thanks for the code sample.

I'm usually lazy when it comes to giving praise where it's due, but this is a great framework, that I'm yet to find any limitations with. Keep up the amazing work!

**Comment by ngolin** [comment]
Please reopen.
