### ISSUE TITLE
Clicking on an edge will fails to unselect selected nodes.

### ISSUE THREAD

**Issue by kid-icarus** [wbkd/react-flow#966]
Repro steps:

1. Select multiple nodes
2. Click on any edge outside of the node selection

Expected behavior:
The NodesSelection component is not rendered

Actual behavior:
The NodesSelection component is rendered

![image](https://user-images.githubusercontent.com/864752/109905295-6bf0b900-7c53-11eb-8a1a-9f6857c3185f.png)

I believe this is due to the stacking context itself, the pane having a zIndex of 1 whereas edges have 2, and nodes have 3. My use case is that I have a rather large edge (which I will change), but I thought perhaps another solution could involve having the edge click handler detect if there's a node selection, and if so, run the on pane click handlers as well.

**Comment by kid-icarus** [comment]
A quick hack for my large edge was just to add `pointer-events: none` to its styles.

**Comment by moklick** [comment]
That's a bug. Thanks for the report. I will fix it :)

**Comment by moklick** [comment]
Fixed in v9.1.1
