### ISSUE TITLE
Performance drop when panning or zooming

### ISSUE THREAD

**Issue by wladimiiir** [wbkd/react-flow#967]
We have a graph with over 600 elements and when panning and/or zooming there seems to be performance drop and the movement gets laggy. This can also be experienced in https://reactflow.dev/examples/stress example after randomizing positions and panning around - especially when nodes get outside of visible area.

After some investigation it seems that in case nodes getting outside/inside of visible area the internal state nodes (`useStoreState(store => store.nodes)` change - which can be improved by setting `onlyRenderVisibleElements={false}` prop on `ReactFlow` component (which removes some of the lags for our case).

But there is also re-render of `Edge` due to `transform` prop change, however I am not sure that this is the main cause of the issue.

I wonder if changing `transform` should automatically trigger re-render of Edge, especially when re-render of Nodes is not triggered in such case.

Thank you.

PS: the library is great, thanks for your hard work, BTW :)

**Comment by moklick** [comment]
Hey @wladimiiir 

since react flow is DOM based we have some limitations. I would say that ~1000 nodes is the limit depending on the complexity of the nodes. 

The `onlyRenderVisibleElements` was supposed to speed up the flows but at the moment it does the opposite :( When nodes reenter the view they have to be expensively reinitialized. The `Edge` component needs the current `transform` value only to check if it's inside the viewport (when `onlyRenderVisibleElements=true`).. So for nodes and edges `onlyRenderVisibleElements=true` is actually bad right now. 

I am aware of this and I will try to improve this over the next weeks!

**Comment by wladimiiir** [comment]
Thanks for your response.

**Comment by Xalsar** [comment]
Hi @moklick I am experiencing the same problem but in a larger scale. I am working on a project with thousands of nodes, but the performance drops a lot. 

I highly appreciate that you are working on it, but I would like to know if the library is planned to handle this quantity of nodes in a near future or if there is a way to solve (at least partially) the problem right now.

**Comment by moklick** [comment]
Hey @Xalsar 

react-flow is not made for flows with more than 1000+ nodes. I am not sure if a DOM based renderer can satisfy your requirements here. I would check out a canvas based solution in your case.

**Comment by jwang0306** [comment]
> react-flow is not made for flows with more than 1000+ nodes. I am not sure if a DOM based renderer can satisfy your requirements here. I would check out a canvas based solution in your case.
@moklick I'd like to ask if you know any of the canvas based solutions?

**Comment by Alan-Fisher** [comment]
@moklick 
> I am aware of this and I will try to improve this over the next weeks!

Thanks, looking forward to it!

**Comment by OrhanTozan** [comment]
@moklick #723 is a very similar issue. Should we mark one of them as duplicate?

**Comment by moklick** [comment]
Yes @OrhanTozan . I will close this in favor of #723

**Comment by lgj9172** [comment]
@moklick Hi. Is the current version 11 also unsuitable for more than 1000 nodes?

**Comment by CamboimGabriel** [comment]
up!

**Comment by CdTgr** [comment]
I faced this issue even with just 3 groups and 10 nodes inside each ( which is 33 nodes ).
I had a blur on the node backgrounds, and upon removing the blur ( `filter: blur(xxx)` ) everything worked smoothly.

It is not always the number of nodes having issues with the performance, sometimes styling can also bring performance impacts.

> Posting it so, it might be helpful for someone who has a similar issue.
