### ISSUE TITLE
Cannot resolve 'react' dependency of react-flow

### ISSUE THREAD

**Issue by popey456963** [wbkd/react-flow#968]
In JavaScript, trying to `import {} from 'react-flow-renderer'`.  Getting errors saying it can't find react.  Doesn't seem to exist in your package.json under 'dependencies', only 'devDependencies':

    https://github.com/wbkd/react-flow/blob/main/package.json

Our project has a dependency on 'react' which works, so it's definitely installed in our node_modules.

**Comment by moklick** [comment]
React is a peerDependency or react flow. Can you paste your code and the error here?

**Comment by popey456963** [comment]
I'm not able to reproduce this in a new project.  I've clearly done something very wrong.  Apologies for bothering.

Any ideas on how to solve would be lovely, as I'm drawing a blank :)

**Comment by popey456963** [comment]
So, for future people who get this.  Make sure you don't have multiple levels of package.json files and node_modules.  I had a structure like:

```
Documents/
  node_modules/
    <react-flow-renderer in here>
  project/
    node_modules/
      <react in here>
```

Which meant that I wasn't getting any missing dependencies messages, but react-flow-renderer couldn't find react as it was in a child node_modules folder!
