### ISSUE TITLE
Feature: alternative mode for node connection

### ISSUE THREAD

**Issue by alexkuz** [wbkd/react-flow#969]
Currently the only(?) way to connect two nodes is to drag the pointer from source handle to target one. This doesn't feel very convenient and accessible¹ (especially when nodes are far away from each other). This could be improved by:

- adding a mode where handles are connected by two sequential clicks rather than one dragging;
- allowing to use whole node area as a target (possibly defining areas for each input handle by using classnames).

--
¹ Actually, the whole thing is quite inaccessible, but that should be a separate extensive issue I think.

**Comment by celdrake** [comment]
There is a property `connectionMode` that you can set as `loose` that lets you connect either from a source handle or a target handle.

However, it doesn't seem to alter the order of the nodes in the `onConnect` function so I have this issue and I'm trying to figure out if I can identify which is the source handle on each connection.

**Comment by moklick** [comment]
hey @alexkuz 

* I like the idea of connecting nodes by clicking on the handles. Maybe this could be a flag that is true by default for touch screens like `connectOnClick=true|false`. Do you have an idea for a prop name? 
* you can already do this but there is some custom implementation needed. In my view thats OK.

**Comment by alexkuz** [comment]
I think `connectOnClick` would be okay.

As for "node as target", I guess this could be implemented by using "target" classname and some attributes, but I feel this should be documented, I only got this by looking at code. It is a feasible solution though.

**Comment by Alan-Fisher** [comment]
Waiting for this feature :)

**Comment by moklick** [comment]
I will collect new feature ideas in the "Discussions/New Features" section. This issue will be closed in favour of #1021
