### ISSUE TITLE
Blank screen when rendering basic example in NextJS

### ISSUE THREAD

**Issue by popey456963** [wbkd/react-flow#970]
```
npx create-next-project react-flow-error
cd react-flow-error
yarn add react-flow-renderer
cd pages
vim test.js // or your favourite editor
```

Paste the following code:

```
import React from 'react';
import ReactFlow from 'react-flow-renderer';

const elements = [
  { id: '1', data: { label: 'Node 1' }, position: { x: 250, y: 5 } },
  // you can also pass a React component as a label
  { id: '2', data: { label: <div>Node 2</div> }, position: { x: 100, y: 100 } },
  { id: 'e1-2', source: '1', target: '2', animated: true },
];

const BasicFlow = () => <ReactFlow elements={elements} />;

export default BasicFlow;
```

(just the default 'getting started' code with an export added at the bottom)

```
yarn dev
```

Visit http://localhost:3000/test (or, if that port is taken, another port will be generated by next).  Observe a blank screen.

OS: Windows 10
Browser: Firefox Stable

**Comment by clementgalopin** [comment]
hi @popey456963 , I have the same issue with all examples, how have you solved it? Thanks!

**Comment by moklick** [comment]
The parent container needs a width and height. Check the logs if you get a warning.

**Comment by clementgalopin** [comment]
Thanks @moklick, solved it.

**Comment by popey456963** [comment]
Whoops, apologies for not putting down how I fixed it.  Yeah, lots of examples don't give set width / height which caught me out!
