### ISSUE TITLE
is multiple ports supported + other queries

### ISSUE THREAD

**Issue by nsisodiya** [wbkd/react-flow#979]
Q1 - Can we  have multiple input/output ports? like this
![image](https://user-images.githubusercontent.com/333455/110282998-6bff0900-8005-11eb-9547-798a62c450d6.png)

Q2 - Can we have hover over edge to display ports name
![image](https://user-images.githubusercontent.com/333455/110283146-9bae1100-8005-11eb-9a30-d4f974f4cc95.png)

Q3 - Can we have different colors to different edges
![image](https://user-images.githubusercontent.com/333455/110283752-956c6480-8006-11eb-9833-09c0a1bc63d6.png)

**Comment by moklick** [comment]
Q1: yes you can achieve this by implementing custom nodes
Q2: yes, with a custom edge
Q3: yes!

**Comment by nsisodiya** [comment]
@moklick -  so in custom node, we we define ports too.
```
CN1 (custom node 1) - out ports - (o1, o2) 
CN2 (custom node 2) - in ports - (i3, i4) 
connection - edges - 
e1 = from o1 to i3
e2 = from o2 to i4
```

**Comment by moklick** [comment]
Yes, thats possible as you can see in this example https://reactflow.dev/examples/custom-node/
