### ISSUE TITLE
Support for multi-points edges

### ISSUE THREAD

**Issue by gfox1984** [wbkd/react-flow#980]
Hi,

I'm trying to use ReactFlow with Dagre. Unlike in your [layouting example](https://reactflow.dev/examples/layouting/), I would like ReactFlow to draw the edges according to the list of points computed by Dagre.

I've attempted to modify the example with the following code:

```
const getLayoutedElements = (elements) => {
    ...
    
    return elements.map((el) => {
      if (isNode(el)) {
        ...
      } else {
        const edgeWithPosition = dagreGraph.edge(el.source, el.target, el.id); 
        el.data = { points: edgeWithPosition.points };
        el.type = 'custom';
      }
      return el;
    });
  };
```

with this implementation of 'custom' Edge:

```
export function CustomEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  style = {},
  data,
  arrowHeadType,
  markerEndId
}): JSX.Element {
  const edgePath = data.points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ');
  const markerEnd = getMarkerEnd(arrowHeadType, markerEndId);
  return (
    <>
      <path id={id} style={style} className="react-flow__edge-path" d={edgePath} markerEnd={markerEnd} />
      ...
    </>
  );
```

but the paths drawn seem out of place...

Is there anything I'm missing (some scaling or transformation)? Would you consider building that feature in so the integration with a layouting library can be made easier?

**Comment by obaid** [comment]
Can you create a codesandbox environment for this? I have been dealing with something similar on a client project and would be happy to help if i can :)

**Comment by gfox1984** [comment]
Here is the sandbox with the modified Layouting example: https://codesandbox.io/s/zealous-wilson-disyc?file=/src/LayoutFlow.tsx

**Comment by gfox1984** [comment]
> Hey @gfox1984
> 
> thanks for input! Do I get it right, that width=172 and height=36 is correct for the layouting example on the website? I will mention the anchor point issue in the example.

With index.css and layouting.css from the example folder I get nodes that measure 172x36 in codesandbox. Having said that, if I measure the nodes at https://reactflow.dev/examples/layouting/, it seems to be more like 172x43 (probably some extra CSS in there?). A stronger (and maybe costlier) approach would be to actually measure the nodes, but I'm not sure if it's possible or wanted.

**Comment by moklick** [comment]
Regarding your question: The only problem I see here is that the source and targets are at the center of the node but not at the center of the handle. You could adjust your path creation like that:

```js 
const edgePath = data.points
    .map((point, index, points) => {
      if (index === 0) {
        return `M ${sourceX} ${sourceY}`;
      } else if (index === points.length - 1) {
        return `L ${targetX} ${targetY}`;
      }

      return `L ${point.x} ${point.y}`;
    })
    .join(" ");
```

does it work for you? We will not integrate this into the library since we want you to be as flexible as possible. There are a lot of different layouting solutions.

**Comment by gfox1984** [comment]
Thanks @moklick, it definitely looks neater when the edges come out of the handles, as you suggested (even we're not strictly following the points given by dagre). See an example here: https://codesandbox.io/s/cocky-perlman-15vj9?file=/src/LayoutFlow.tsx

**Comment by gfox1984** [comment]
@moklick, FYI I have been playing with [elkjs](https://github.com/kieler/elkjs) too, as an alternative to Dagre which I was not 100% happy with. Would you like to see another codesandbox with elkjs and maybe consider adding another layouting example to your site?

**Comment by moklick** [comment]
I just added some comments to the existing layouting example and added nodeWidth and nodeHeight. What kind of layouting example are you missing?

**Comment by gfox1984** [comment]
Nah i don't really need another example. I was just thinking of demonstrating that layouting can also be handled by another popular, more powerful library and how.

**Comment by moklick** [comment]
We need the possibility to add some text to the examples. I think it would help.
