### ISSUE TITLE
Can we have an Event Handler as 'onEdgeMouseEnter' like we do have for Nodes

### ISSUE THREAD

**Issue by harshambastha** [wbkd/react-flow#987]
I want to show a div on hover over the edge. For that I am creating a custom edge and adding the React 'onMouseEnter' Event Handler there and passing the props in the main component, but when I hover over the edge the background of canvas goes blank. So I was wondering if we can have the Event Handler for edge so that we dont have to create a custom Edge.

**Comment by moklick** [comment]
Yes, we will add `onEdgeMouseEnter`, `onEdgeMouseMove` and `onEdgeMouseLeave`.

**Comment by harshambastha** [comment]
Thank You so much @moklick for considering my feature request.

**Comment by moklick** [comment]
added in v9.2.0
