### ISSUE TITLE
Group nodes in a container

### ISSUE THREAD

**Issue by awjreynolds** [wbkd/react-flow#988]
I'm looking for a library that can replace my use of Graphviz that offers much more flexibility and this looks almost perfect. Directed graphs can "group" nodes together: 
![image](https://user-images.githubusercontent.com/1948692/110936872-7254f400-8329-11eb-85bd-c52ecfcbfb25.png)

I this feature seems to be missing from this library. It's not a child node, it's simply grouping these nodes logically together.

Hope this makes sense.

**Comment by moklick** [comment]
Yep, de definitely need this :) there is also an issue for this #658
