### ISSUE TITLE
Is it possible to hear the change in the elements?

### ISSUE THREAD

**Issue by Dricosta** [wbkd/react-flow#990]
Hello, I'm a new react flow user.
I'm trying to listen to the changes being made to my array of elements, to give feedback to the user that he can save the flow. 

For example: I have a save button, and another button to cancel changes, I would like that when changing, deleting or adding any element, my save button would change the color giving feedback to the user that the flow needs to be saved.

is there any method like onElementsChange maybe, that will let me know about this change?

**Comment by moklick** [comment]
There is no `onElementsChange`. You would need to listen to several events. These should work for you `onNodeDragStop`, `onConnect` and `onElementsRemove`.
