### ISSUE TITLE
Layout example with dynamic width and height values

### ISSUE THREAD

**Issue by BorisGiba** [wbkd/react-flow#991]
Hello,

first of all, thank you for creating this library! This is by far the best library I've seen for creating interactive graphs. 😄

In the Layout-example (https://reactflow.dev/examples/layouting/) the widths and heights are hardcoded.
The comment says that it is possible to access the real widths and heights using
`const nodes = useStoreState(state => state.nodes) `

However, this only works in a child element of ReactFlow, where the nodes can be accessed (if I understood it correctly). I.e. it is not possible to access state.nodes before the graph has been created.

My question would be how exactly can we apply the real widths and heights to the nodes when generating the graph? 😅

I've read #5 and I have tried to apply the code provided by @mymywang but could not get it to work at all 😅

From my understanding, state.nodes would only be accessible in a scenario like this one:

```
<ReactFlow elements={TheseAreTheNodesWeWantToAccess}>
     <ComponentToAccessStateNodes/>
<ReactFlow/
```

and in `ComponentToAccessStateNodes` it is possible to access state.nodes and then iterate over every node and get the widths and height using `node.__rf.width` and `node.__rf.height`. But by that point, the graph already has been generated with the predefined widths and heights (which are in turn needed to generate the graph in the first place?).

I'm sorry if this is a trivial question but I really don't seem to figure out how to do this.
If someone could provide a minimal working example, that would be really kind.

**Comment by moklick** [comment]
Hey @BorisGiba 

if you want to access the internal state you can do this inside the children or wrap your app with the [ReactFlowProvider](https://reactflow.dev/docs/api/components/provider/) - example: https://reactflow.dev/examples/provider/ as you can see the sidebar is not a children of the ReactFlow component but we can access the store.

Regarding the layouting: When you don't know anything about the dimensions of your nodes you need to render the graph before you can do a proper layouting. React flow measures all nodes on initialisation and stores that information that you could then use for your layout. You would need to do something like:

1. render the graph (you can also set the opacity of your elements to 0 if you don't want them to jump around/flicker)
2. receive the dimensions from the nodes in the internal store
3. do the layouting (set opacity of the elements to 1)


Another solution is to give your nodes a fixed width and height that you could use for the layouting.

**Comment by BorisGiba** [comment]
Thank you for the quick reply!
I completely forgot about the provider, thank you for mentioning that!

This 3-step solution sounds like it should do the job.
I will test it out and comment on the results 👍

**Comment by BorisGiba** [comment]
I'm having a few issues with the implementation. This is the main react-flow component:

```
// flow class
  const LayoutFlow = () => {
    // elements + styling
	const elements = [
		{ id: '1', style: { background: '#121e30',border: "1px solid white"}, data: { label: <a href="">testing</a> }, position: { x: 250, y: 5 } },
		{ id: '2', data: { label: 'Node 2' }, position: { x: 100, y: 100 } },
		{ id: 'e1-2', source: '1', target: '2', animated: true },
	]; // just an example

	const flowStyles = { background:"#192a43", height: "30em", boxShadow:"0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)" };

	const dagreGraph = new dagre.graphlib.Graph();
	dagreGraph.setDefaultEdgeLabel(() => ({}));
    const [elements, setElements] = useState(elements);
  
    return (
      <div className="layoutflow">
        <ReactFlowProvider>
          <ReactFlow
            elements={elements}
            connectionLineType="smoothstep"
            style={flowStyles}
          />
          <Controls/>
          <NodeLayouter/> // <------------------------------ this component should do the layouting
        </ReactFlowProvider>
      </div>
    );
  };
```

and NodeLayouter looks like this:

```
  const NodeLayouter = (props) => {
    const nodes = useStoreState(state => state.nodes)       // access internal state


    // modified helper function by @mymywang
    const createGraphLayout = (flowNodeStates: Node[]): Node[] => {

      flowNodeStates.forEach((el) => {
        if (isNode(el)) {
          dagreGraph.setNode(el.id, {
            label: el.id,
            width: el.__rf.width,
            height: el.__rf.height,
          })
        } else {
          dagreGraph.setEdge(el.source, el.target);
        }
      });

      return flowNodeStates.map((nodeState) => {
        const node = dagreGraph.node(nodeState.id);
        return {
          ...nodeState,
          position: {
              x: node.x - nodeWidth / 2 + Math.random() / 1000,
              y: node.y,
          },
        };
      });}

      // this function should handle the dynamic width and height values
      const changeDimensions= useCallback(
        () => {
          console.log("changing dimensions..") // is printed
          const layoutedElements = createGraphLayout(nodes);
          // how can I update the nodes? <-------------------------------------------------------
          dagre.layout(dagreGraph);
        },
        [nodes]
      );

      return (<button onClick={()=>{changeDimensions()}} style={{background:"#000"}}>Change Dimensions</button>)
    }

```

So when I click the "Change Dimensions"-button, the nodes should get their respective height and width values.
But how exactly can I update the nodes of the graph?
In the layouting example, `setElements` was used, but NodeLayouter has no access to that function. I have tried passing it as props (like this: `<NodeLayouter nodeUpdateFunction={setElements}/>`) and then calling it this way, but this just made all nodes disappear (?).
In the Provider-example `useStoreActions` was used. I tried this too. The NodeLayouter-class looked like this with these two attempts:
```
const NodeLayouter = (props) => {
    const nodes = useStoreState(state => state.nodes) //and then node.__rf.width, node.__rf.height
    const setSelectedElements = useStoreActions((actions) => actions.setSelectedElements);

    // modified helper function by @mymywang
    const createGraphLayout = (flowNodeStates: Node[]): Node[] => {
    
      flowNodeStates.forEach((el) => {
        if (isNode(el)) {
          dagreGraph.setNode(el.id, {
            label: el.id,
            width: el.__rf.width,
            height: el.__rf.height,
          })
        } else {
          dagreGraph.setEdge(el.source, el.target);
        }
      });

      return flowNodeStates.map((nodeState) => {
        const node = dagreGraph.node(nodeState.id);
        return {
          ...nodeState,
          position: {
              x: node.x - nodeWidth / 2 + Math.random() / 1000,
              y: node.y,
          },
        };
      });}

      
      // this function should handle the dynamic width and height values
      const changeDimensions= useCallback(
        () => {
          console.log("changing dimensions..") // is printed
          const layoutedElements = createGraphLayout(nodes);

          props.setter(layoutedElements) <------------------------------ first attempt

          setSelectedElements(layoutedElements) <------------------------------ second attempt



          dagre.layout(dagreGraph);
        },
        [nodes]
      );

      return (<button onClick={()=>{changeDimensions()}} style={{background:"#000"}}>Layout</button>)
    }
```

Using setSelectedElements had no effect at all. What am I doing wrong?

**Comment by moklick** [comment]
Hey @BorisGiba. Could you already solve this? You would need to pass down the `setElements` function and then update the positions like in this example https://reactflow.dev/examples/layouting/ 

Please create a codesandbox or a repo when the issue still occurs.

**Comment by BorisGiba** [comment]
Yes, after some time I could get it to work now.
Passing setElements as props did work, I just had some bug in my own code
that made the elements disappear.
For anyone who has a similar issue and reads this in the future, here is how I implemented it:

I used a higher-order component that contains the layouting helper-function `createGraphLayout`
as well as a helper component that takes care of the layouting. Said helper component
calls the layouting-helper and sets the elements using the passed setElements function.
When loading the graph, it is first layouted with static widths and heights.
Then, after pressing the button rendered by NodeLayouter, a dynamic layout is generated.
The code looks like this:

```jsx
import React, { useState } from 'react';
import ReactFlow, {
  ReactFlowProvider,
  isNode,
  Node,
  useStoreState,
} from 'react-flow-renderer';
import dagre from 'dagre';


// higher order component (this component renders the entire page content in my case)
const TreeSearch: React.FC<TreeProps> = ({data}) => {

	const nodeWidth = 210;
	const nodeHeight = 156;

	  // slightly modified version of the function taken directly from the Layout-example: https://reactflow.dev/examples/layouting/ 
	  const getLayoutedElements = (elements, direction = 'BT') => {
		const isHorizontal = direction === 'LR';
		dagreGraph.setGraph({ rankdir: direction });
	  
		elements.forEach((el) => {
		  if (typeof el != "boolean") {
			if (isNode(el)) {
			  dagreGraph.setNode(el.id, { width: nodeWidth, height: nodeHeight });
			} else {
			  dagreGraph.setEdge(el.source, el.target);
			}
		  }});
	  
		dagre.layout(dagreGraph);
	  
		return elements.map((el,idx) => {
		  if (typeof el != "boolean") {
		  if (isNode(el)) {
			const nodeWithPosition = dagreGraph.node(el.id);
			el.targetPosition = isHorizontal ? 'left' : 'bottom';
			el.sourcePosition = isHorizontal ? 'right' : 'top';
	  
			// unfortunately we need this little hack to pass a slighltiy different position
			// to notify react flow about the change. More over we are shifting the dagre node position
			// (anchor=center center) to the top left so it matches the react flow node anchor point (top left).
			el.position = {
			  x: nodeWithPosition.x - nodeWidth / 2 + Math.random() / 1000,
			  y: nodeWithPosition.y - nodeHeight / 2,
			};
		  }}
	  
		  return el;
		});
	  }; 

	//initialElements = ... (your data)
	const layoutedElements = getLayoutedElements(initialElements); // default to static layout

	// helper function
	// slightly modified version of @mymywang's function
	const createGraphLayout = (graph, flowNodeStates: Node[], edges): Node[] => {

	  flowNodeStates.forEach((node) => {
		if (typeof node != "boolean") { // without this I experienced some weird behaviour, might not be necessary for your use case
		  if (isNode(node)) {
			graph.setNode(node.id, {
			  label: node.id,
			  width: node.__rf.width,
			  height: node.__rf.height,
			});
		  }
		}
	  });

	  edges.forEach((edge) => {
		graph.setEdge(edge.source, edge.target);
	  })

	  dagre.layout(graph);

	  return flowNodeStates.map((nodeState) => {
		const node = graph.node(nodeState.id);
		return {
		  ...nodeState,
		  position: {
			// The position from dagre layout is the center of the node.
			// Calculating the position of the top left corner for rendering.
			x: node.x - node.width / 2 + Math.random() / 1000,
			y: node.y - node.height / 2,
		  },
		};
	  });
	};

	// internal helper component that manages layouting/
	 const NodeLayouter = (props) => {
		const nodeStates = useStoreState((store) => store.nodes)
		const edgeStates = useStoreState((store) => store.edges) // store.nodes does not fetch edges, so this is needed to fetch edges
	  
		const nodeHasDimension = node => (node.__rf !=null && node.position != null)
	  
		const changeLayout = () => {
		  if (nodeStates.length>0 && nodeStates.every(nodeHasDimension)) {
			const elementsWithLayout = createGraphLayout(props.graph,nodeStates,edgeStates) // get dynamically layouted elements
			props.elementsSetter(elementsWithLayout.concat(edgeStates)) // concat edges and nodes together
		  }
		};

		  return (<button className="tightLayouterButton" onClick={()=>{changeLayout()}}>change layout</button>)
		}
	
	// flow component
	  const LayoutFlow = props => {
	    const [elements, setElements] = useState(layoutedElements);
		const flowStyles = {height: "30em"}
		// define onLoad, etc.
	 
		return (
		  <div className="layoutflow">
			<ReactFlowProvider>
			  <ReactFlow
				elements={elements}
				connectionLineType="smoothstep"
				style={flowStyles}
				/>
			  <Controls/>
			  <NodeLayouter graph={dagreGraph} elementsSetter={setElements}/>
			
			</ReactFlowProvider>
		  </div>
		);
	  };
	  
	  return (
				<...> // your page here
				<LayoutFlow/>
				</...>)
```

Before implementing this I wondered how the dynamic layout actually looks like when compared directly to the static layout (whether it's better or not). If you have the same question, I created a small gif to show the differences between the static and the dynamic layout. Of course, you can use 1.1 * the .__rf.width and height to make it more spacious, but here is how it looks like when using just .__rf.width and height:

![dynamicLayoutDemo](https://user-images.githubusercontent.com/32174937/112746108-2357c180-8fad-11eb-8e60-ee997545c855.gif)

**Comment by moklick** [comment]
Thanks for the example code. Looks very nice 👌

**Comment by kenzouno1** [comment]
> Xin chào@BorisGiba,@moklickTrong trường hợp sử dụng của mình, tôi sẽ tự động thêm hoặc xóa các nút. Vì vậy, nếu không có bất kỳ sự can thiệp nào của người dùng, làm thế nào tôi có thể tự động điều chỉnh bố cục của mình?

i have same the question

**Comment by SivaGanesh56** [comment]
+1

**Comment by AGontcharov** [comment]
> Hi @BorisGiba , @moklick In my use case, I'll be dynamically adding or deleting the nodes. So without any user intervention, how will I be able to do auto adjust my layout?

Same question as above. Is there a way to auto layout the graph when nodes are added are to the graph using their dynamic width and height?

**Comment by shobrook** [comment]
Is there any update on this?

**Comment by dolfinus** [comment]
Here is slightly updated code to match current release:
```tsx
import { ReactFlow, ReactFlowProps, useReactFlow, Node, Panel } from "@xyflow/react";

const NodeLayouter = () => {
    const {getNodes, getEdges, setNodes, setEdges} = useReactFlow()

    const nodeHasDimension = (node: Node) => (node.measured != null && node.position != null)

    const updateLayout = () => {
        const nodes = getNodes();
        const edges = getEdges();

        if (nodes.length > 0 && nodes.every(nodeHasDimension)) {
            const layout = buildLineageLayout({nodes, edges})
            setNodes(layout.nodes)
            setEdges(layout.edges)
        }
    }

    return <buttononClick={()=>{updateLayout()}}>Update layout</button>;
}

const ReactFlowWithUpdateLayoutButton = (props: ReactFlowProps) => {
        <ReactFlow {...props}>
            <Panel>
                <NodeLayouter />
            </Panel>
        </ReactFlow>
  );
}
```

But for me this produces too tightly packed graph which is harder to read than original one with fixed wigth.
